---
permalink: sm-storage/actions-you-can-perform-on-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volumes 
summary: 볼륨에 대해 용량 증가, 삭제, 복사, 초기화, 재배포 등의 다양한 작업을 수행할 수 있습니다. 소유권 변경, 캐시 설정 변경 및 미디어 스캔 설정 변경 
---
= 볼륨에 대해 수행할 수 있는 작업입니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨에 대해 용량 증가, 삭제, 복사, 초기화, 재배포 등의 다양한 작업을 수행할 수 있습니다. 소유권 변경, 캐시 설정 변경 및 미디어 스캔 설정 변경



== 용량 증가

다음과 같은 두 가지 방법으로 볼륨의 용량을 확장할 수 있습니다.

* 풀 또는 볼륨 그룹에서 사용할 수 있는 가용 용량을 사용합니다.
+
Storage[Pools and Volume Groups > Add Capacity] 메뉴를 선택하여 볼륨에 용량을 추가합니다.

* 할당되지 않은 용량(미사용 드라이브 형태)을 볼륨의 풀 또는 볼륨 그룹에 추가합니다. 풀 또는 볼륨 그룹에 사용 가능한 용량이 없는 경우 이 옵션을 사용합니다.
+
스토리지 [풀 및 볼륨 그룹 > 용량 추가] 메뉴를 선택하여 풀 또는 볼륨 그룹에 할당되지 않은 용량을 추가합니다.

+
풀 또는 볼륨 그룹에서 사용 가능한 용량을 사용할 수 없는 경우 볼륨의 용량을 늘릴 수 없습니다. 먼저 풀 또는 볼륨 그룹의 크기를 늘리거나 미사용 볼륨을 삭제해야 합니다.



볼륨 용량을 확장한 후에는 파일 시스템 크기를 수동으로 늘려야 합니다. 이 방법은 사용 중인 파일 시스템에 따라 다릅니다. 자세한 내용은 호스트 운영 체제 설명서를 참조하십시오.



== 삭제

일반적으로 볼륨이 잘못된 매개 변수 또는 용량으로 생성되었거나, 스토리지 구성 요구 사항을 더 이상 충족하지 않거나, 백업 또는 애플리케이션 테스트에 더 이상 필요하지 않은 스냅샷 이미지일 경우 볼륨을 삭제합니다. 볼륨을 삭제하면 풀 또는 볼륨 그룹의 사용 가능한 용량이 증가합니다.

볼륨을 삭제하면 해당 볼륨의 모든 데이터가 손실됩니다. 볼륨을 삭제하면 연결된 스냅샷 이미지, 스케줄 및 스냅샷 볼륨도 삭제되고 모든 미러링 관계가 제거됩니다.



== 복사

볼륨을 복사할 때 동일한 스토리지 배열에서 두 개의 개별 볼륨, 즉 소스 볼륨과 타겟 볼륨의 시점 복제본을 생성합니다. 스토리지 [볼륨 > 복사본 서비스 > 볼륨 복사] 메뉴를 선택하여 볼륨을 복사할 수 있습니다.



== 초기화

볼륨을 초기화하면 볼륨의 모든 데이터가 지워집니다. 볼륨이 처음 생성될 때 자동으로 초기화됩니다. 그러나 Recovery Guru는 특정 장애 조건에서 복구하기 위해 볼륨을 수동으로 초기화하도록 조언할 수 있습니다. 볼륨을 초기화할 때 볼륨은 WWN, 호스트 할당, 할당된 용량 및 예약된 용량 설정을 유지합니다. 또한 동일한 DA(Data Assurance) 설정 및 보안 설정을 유지합니다.

Storage [Volumes > More > Initialize volumes] 메뉴를 선택하여 볼륨을 초기화할 수 있습니다.



== 재분포

볼륨을 재배포하여 볼륨을 기본 컨트롤러 소유자에게 다시 옮깁니다. 일반적으로 다중 경로 드라이버는 호스트 및 스토리지 어레이 사이의 데이터 경로에 문제가 발생할 경우 원하는 컨트롤러 소유자로부터 볼륨을 이동합니다.

대부분의 호스트 다중 경로 드라이버는 기본 컨트롤러 소유자에 대한 경로의 각 볼륨에 액세스를 시도합니다. 그러나 이 기본 경로를 사용할 수 없게 되면 호스트의 다중 경로 드라이버가 대체 경로로 페일오버됩니다. 이 페일오버로 볼륨 소유권이 대체 컨트롤러로 변경될 수 있습니다. 페일오버를 발생시키는 조건을 해결한 후 일부 호스트는 자동으로 볼륨 소유권을 기본 컨트롤러 소유자로 다시 이동하지만 경우에 따라 볼륨을 수동으로 재분산해야 할 수 있습니다.

Storage [Volumes > More > Redistribute volumes] 메뉴를 선택하여 볼륨을 재배포할 수 있습니다.



== 볼륨 소유권을 변경합니다

볼륨의 소유권을 변경하면 볼륨의 기본 컨트롤러 소유권이 변경됩니다. 볼륨의 기본 컨트롤러 소유자가 Storage [Volumes > View/Edit Settings > Advanced Tab] 메뉴에 나열됩니다.

스토리지 [볼륨 > 자세히 > 소유권 변경] 메뉴를 선택하여 볼륨의 소유권을 변경할 수 있습니다.



=== 미러링 및 볼륨 소유권

미러링된 쌍의 운영 볼륨이 컨트롤러 A에 의해 소유되는 경우, 보조 볼륨은 원격 스토리지 어레이의 컨트롤러 A에 의해 소유됩니다. 운영 볼륨의 소유자를 변경하면 보조 볼륨의 소유자가 자동으로 변경되어 두 볼륨이 동일한 컨트롤러에 의해 소유되도록 합니다. 기본 면의 현재 소유권 변경 사항은 보조 면의 해당 현재 소유권 변경 사항에 자동으로 적용됩니다.

미러 정합성 보장 그룹에 로컬 보조 볼륨이 포함되어 있고 컨트롤러 소유권이 변경된 경우 첫 번째 쓰기 작업에서 보조 볼륨이 자동으로 원래 컨트롤러 소유자에게 다시 전송됩니다. 소유권 변경 * 옵션을 사용하면 보조 볼륨의 컨트롤러 소유권을 변경할 수 없습니다.



=== 볼륨 및 볼륨 소유권을 복사합니다

볼륨 복사 작업 중에 동일한 컨트롤러가 소스 볼륨과 타겟 볼륨을 모두 소유해야 합니다. 복사 볼륨 작업이 시작될 때 두 볼륨에 동일한 기본 컨트롤러가 없는 경우가 있습니다. 따라서 타겟 볼륨의 소유권이 소스 볼륨의 기본 컨트롤러로 자동 전송됩니다. 볼륨 복사가 완료되거나 중지되면 대상 볼륨의 소유권이 기본 컨트롤러로 복원됩니다.

복제 볼륨 작업 중에 소스 볼륨의 소유권이 변경되면 타겟 볼륨의 소유도 변경됩니다. 특정 운영 체제 환경에서는 I/O 경로를 사용하기 전에 다중 경로 호스트 드라이버를 재구성해야 할 수 있습니다. (일부 다중 경로 드라이버는 I/O 경로를 인식하기 위해 편집이 필요합니다. 자세한 내용은 드라이버 설명서를 참조하십시오.)



== 캐시 설정을 변경합니다

캐시 메모리는 드라이브 미디어보다 액세스 시간이 빠른 컨트롤러의 임시 휘발성 저장 장치(RAM)의 영역입니다. 캐시 메모리를 사용하는 경우 다음과 같은 이유로 전반적인 I/O 성능을 높일 수 있습니다.

* 읽기를 위해 호스트에서 요청된 데이터가 이전 작업의 캐시에 이미 있을 수 있으므로 드라이브 액세스가 필요하지 않습니다.
* 쓰기 데이터는 처음에는 캐시에 기록되기 때문에 데이터가 드라이브에 기록될 때까지 기다리지 않고 애플리케이션을 계속 사용할 수 있습니다.


메뉴: 스토리지 [볼륨 > 자세히 > 캐시 설정 변경]을 선택하여 다음 캐시 설정을 변경합니다.

* * 읽기 및 쓰기 캐싱 * -- 읽기 캐시는 드라이브에서 읽은 데이터를 저장하는 버퍼입니다. 읽기 작업의 데이터가 이전 작업의 캐시에 이미 있을 수 있으므로 드라이브에 액세스할 필요가 없습니다. 데이터가 플러시될 때까지 읽기 캐시에 남아 있습니다.
+
쓰기 캐시는 드라이브에 아직 기록되지 않은 호스트의 데이터를 저장하는 버퍼입니다. 데이터는 드라이브에 기록될 때까지 쓰기 캐시에 유지됩니다. 쓰기 캐싱은 I/O 성능을 높일 수 있습니다.

* * 미러링으로 쓰기 캐싱 * -- 한 컨트롤러의 캐시 메모리에 기록된 데이터가 다른 컨트롤러의 캐시 메모리에도 쓰일 때 미러링을 사용하는 쓰기 캐시가 발생합니다. 따라서 한 컨트롤러에 장애가 발생하면 다른 컨트롤러가 처리되지 않은 모든 쓰기 작업을 완료할 수 있습니다. 쓰기 캐시 미러링은 쓰기 캐시가 설정되고 두 개의 컨트롤러가 있는 경우에만 사용할 수 있습니다. 볼륨 생성 시 기본 설정은 미러링을 사용한 쓰기 캐시입니다.
* * 배터리 없는 쓰기 캐싱 * -- 배터리 없는 쓰기 캐싱 설정을 사용하면 배터리가 없거나, 고장, 방전되거나, 완전히 충전되지 않았더라도 쓰기 캐싱을 계속할 수 있습니다. 일반적으로 배터리 없이 쓰기 캐시를 선택하는 것은 권장되지 않습니다. 전원이 끊길 경우 데이터가 손실될 수 있기 때문입니다. 일반적으로 쓰기 캐시는 배터리가 충전되거나 장애가 발생한 배터리를 교체할 때까지 컨트롤러에 의해 일시적으로 꺼집니다.
+
이 설정은 쓰기 캐시를 설정한 경우에만 사용할 수 있습니다. 씬 볼륨에는 이 설정을 사용할 수 없습니다.

* * 동적 읽기 캐시 프리페치 * -- 동적 캐시 읽기 프리페치를 사용하면 컨트롤러에서 드라이브에서 캐시로 데이터 블록을 읽는 동안 순차적 데이터 블록을 추가로 캐시에 복사할 수 있습니다. 이 캐싱은 향후 캐시에서 데이터 요청을 채울 수 있는 기회를 높여줍니다. 동적 캐시 읽기 프리페치는 순차적 I/O를 사용하는 멀티미디어 애플리케이션에 중요합니다 캐시로 프리페치되는 데이터의 속도와 양은 호스트 읽기의 속도 및 요청 크기에 따라 자동으로 조정됩니다. 랜덤 액세스로 인해 데이터를 캐시로 프리페치하지 않습니다. 이 기능은 읽기 캐시를 사용하지 않는 경우 적용되지 않습니다.
+
씬 볼륨의 경우 동적 캐시 읽기 프리페치는 항상 비활성화되어 변경할 수 없습니다.





== 미디어 스캔 설정을 변경합니다

미디어 검사는 애플리케이션에서 자주 읽지 않는 디스크 블록의 미디어 오류를 감지하고 복구합니다. 이 검사는 장애가 발생한 드라이브의 데이터가 풀 또는 볼륨 그룹의 다른 드라이브의 중복 정보와 데이터를 사용하여 재구성되므로 풀 또는 볼륨 그룹의 다른 드라이브에 장애가 발생할 경우 데이터 손실을 방지할 수 있습니다.

미디어 스캔은 스캔 용량 및 스캔 기간에 따라 일정한 속도로 계속 실행됩니다. 백그라운드 스캔은 우선 순위가 더 높은 백그라운드 작업(예: 재구성)에 의해 일시적으로 중단될 수 있지만 동일한 일정한 속도로 재개됩니다.

Storage [Volumes > More > Change media scan settings] 메뉴를 선택하여 미디어 검사가 실행되는 기간을 설정하고 설정할 수 있습니다.

스토리지 배열 및 해당 볼륨에 대해 미디어 검사 옵션이 활성화된 경우에만 볼륨이 스캔됩니다. 해당 볼륨에 대해서도 중복 검사가 활성화된 경우 볼륨에 중복성이 있는 경우 볼륨의 중복 정보가 데이터와 일관되는지 검사합니다. 중복성 검사를 통한 미디어 검사는 각 볼륨을 만들 때 기본적으로 활성화됩니다.

스캔 중에 복구할 수 없는 매체 오류가 발생하면 중복 정보를 사용하여 데이터가 복구됩니다(가능한 경우). 예를 들어, 이중화 정보는 최적의 RAID 5 볼륨 또는 최적의 RAID 6 볼륨에서 사용할 수 있으며 하나의 드라이브에만 장애가 있습니다. 복구 불가능한 오류가 중복 정보를 사용하여 복구할 수 없는 경우 데이터 블록이 읽을 수 없는 섹터 로그에 추가됩니다. 수정 가능한 미디어 오류와 수정 불가능한 미디어 오류가 모두 이벤트 로그에 보고됩니다.

중복 검사가 데이터와 중복 정보 간의 불일치를 발견하면 이벤트 로그에 보고됩니다.
