---
permalink: sm-storage/add-member-volumes-to-a-snapshot-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, member, volume, snapshot consistency group 
summary: 기존 스냅샷 정합성 보장 그룹에 새 구성원 볼륨을 추가할 수 있습니다. 새 구성원 볼륨을 추가할 때 구성원 볼륨에 대한 용량도 예약해야 합니다. 
---
= 스냅샷 정합성 보장 그룹에 구성원 볼륨을 추가합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 스냅샷 정합성 보장 그룹에 새 구성원 볼륨을 추가할 수 있습니다. 새 구성원 볼륨을 추가할 때 구성원 볼륨에 대한 용량도 예약해야 합니다.

.시작하기 전에
* 구성원 볼륨이 최적화되어야 합니다.
* 스냅샷 정합성 보장 그룹은 최대 허용 볼륨 수보다 작아야 합니다(구성에 정의된 대로).
* 예약된 각 용량 볼륨은 연결된 구성원 볼륨과 동일한 DA(Data Assurance) 및 보안 설정을 가져야 합니다.


.이 작업에 대해
표준 볼륨 또는 씬 볼륨을 스냅샷 정합성 보장 그룹에 추가할 수 있습니다. 기본 볼륨은 풀 또는 볼륨 그룹에 상주할 수 있습니다.

.단계
. 스토리지 [스냅샷] 메뉴를 선택합니다.
. 스냅샷 정합성 보장 그룹 * 탭을 선택합니다.
+
테이블이 나타나고 스토리지 시스템과 연결된 모든 스냅샷 정합성 보장 그룹이 표시됩니다.

. 수정할 스냅샷 정합성 보장 그룹을 선택한 다음 * 구성원 추가 * 를 클릭합니다.
+
구성원 추가 대화 상자가 나타납니다.

. 추가할 구성원 볼륨을 선택한 후 * 다음 * 을 클릭합니다.
+
용량 예약 단계가 나타납니다. 볼륨 후보 테이블에는 지정된 예약 용량을 지원하는 후보만 표시됩니다.

. 스피너 상자를 사용하여 구성원 볼륨에 예약된 용량을 할당합니다. 다음 작업 중 하나를 수행합니다.
+
** * 기본 설정을 적용합니다. *
+
이 권장 옵션을 사용하여 구성원 볼륨에 예약된 용량을 기본 설정으로 할당합니다.

** * 데이터 스토리지 요구 사항에 맞게 예약된 용량 설정을 할당합니다. *
+
기본 예약된 용량 설정을 변경하는 경우 * 후보 새로 고침 * 을 클릭하여 지정한 예약된 용량에 대한 후보 목록을 새로 고칩니다.

+
다음 지침에 따라 예약된 용량을 할당합니다.

+
*** 예약된 용량의 기본 설정은 기본 볼륨 용량의 40%이며 일반적으로 이 용량이면 충분합니다.
*** 필요한 용량은 볼륨에 대한 입출력 쓰기 빈도 및 크기와 스냅샷 이미지 컬렉션의 양과 기간에 따라 달라집니다.




. 구성원 볼륨을 추가하려면 * 마침 * 을 클릭합니다.

