---
permalink: sm-storage/assign-hot-spares-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, assign hot spares 
summary: RAID 1, RAID 5 또는 RAID 6 볼륨 그룹의 추가 데이터 보호를 위해 핫 스페어를 대기 드라이브로 할당할 수 있습니다. 이러한 볼륨 그룹 중 하나에서 장애가 발생하면 컨트롤러가 장애가 발생한 드라이브에서 핫 스페어로 데이터를 재구성합니다. 
---
= 핫 스페어를 할당합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RAID 1, RAID 5 또는 RAID 6 볼륨 그룹의 추가 데이터 보호를 위해 핫 스페어를 대기 드라이브로 할당할 수 있습니다. 이러한 볼륨 그룹 중 하나에서 장애가 발생하면 컨트롤러가 장애가 발생한 드라이브에서 핫 스페어로 데이터를 재구성합니다.

.시작하기 전에
* RAID 1, RAID 5 또는 RAID 6 볼륨 그룹을 만들어야 합니다. (핫 스페어는 풀에 사용할 수 없습니다. 대신 풀에서는 데이터 보호를 위해 각 드라이브 내의 여유 용량을 사용합니다.)
* 다음 기준을 충족하는 드라이브를 사용할 수 있어야 합니다.
+
** 할당되지 않음, 최적 상태
** 볼륨 그룹의 드라이브(예: SSD)와 동일한 미디어 유형입니다.
** 볼륨 그룹의 드라이브와 동일한 인터페이스 유형(예: SAS)
** 볼륨 그룹에 있는 드라이브의 사용된 용량과 같거나 더 큰 용량입니다.




.이 작업에 대해
이 작업에서는 하드웨어 페이지에서 핫 스페어를 수동으로 할당하는 방법에 대해 설명합니다. 권장되는 적용 범위는 드라이브 세트당 2개의 핫 스페어입니다.

[CAUTION]
====
핫 스페어는 초기 설정 마법사에서 할당할 수도 있습니다. 하드웨어 페이지에서 분홍색으로 표시된 드라이브 베이를 찾아 핫 스페어가 이미 할당되었는지 확인할 수 있습니다.

====
.단계
. 하드웨어 * 를 선택합니다.
. 그림에 컨트롤러가 표시되면 * Drives * 탭을 클릭합니다.
+
그래픽이 변경되어 컨트롤러 대신 드라이브가 표시됩니다.

. 핫 스페어로 사용할 할당되지 않은 드라이브(회색으로 표시됨)를 선택합니다.
+
드라이브의 컨텍스트 메뉴가 열립니다.

. 핫 스페어 할당 * 을 선택합니다.
+
드라이브가 안전하게 활성화된 경우 * 보안 지우기 드라이브 * 대화 상자가 열립니다. 보안 지원 드라이브를 핫 스페어로 사용하려면 먼저 Secure Erase(보안 지우기) 작업을 수행하여 모든 데이터를 제거하고 보안 속성을 재설정해야 합니다.

+
[CAUTION]
====
* 데이터 손실 가능성 * -- 올바른 드라이브를 선택했는지 확인하십시오. 보안 지우기 작업을 완료한 후에는 데이터를 복구할 수 없습니다.

====
+
드라이브가 * 보안 활성화되지 않음 * 인 경우 핫 스페어 드라이브 할당 확인 대화 상자가 열립니다.

. 대화 상자의 텍스트를 검토하고 작업을 확인합니다.
+
이 드라이브는 이제 핫 스페어임을 나타내는 분홍색으로 하드웨어 페이지에 표시됩니다.





== 결과

RAID 1, RAID 5 또는 RAID 6 볼륨 그룹 내의 드라이브에 장애가 발생하면 컨트롤러는 자동으로 중복 데이터를 사용하여 오류가 발생한 드라이브에서 핫 스페어로 데이터를 재구성합니다.
