---
permalink: sm-storage/automatic-versus-manual-pool-creation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, manual, pool 
summary: 풀을 자동 또는 수동으로 생성하여 물리적 스토리지를 그룹화한 다음 필요에 따라 동적으로 할당할 수 있습니다. 풀을 생성할 때 물리적 드라이브를 추가할 수 있습니다. 
---
= 자동 및 수동 풀 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
풀을 자동 또는 수동으로 생성하여 물리적 스토리지를 그룹화한 다음 필요에 따라 동적으로 할당할 수 있습니다. 풀을 생성할 때 물리적 드라이브를 추가할 수 있습니다.



== 자동 작성

System Manager에서 스토리지 어레이에서 할당되지 않은 용량을 감지하면 자동 풀 생성이 시작됩니다. 할당되지 않은 용량이 감지되면 System Manager에서 자동으로 하나 이상의 풀을 생성하거나 할당되지 않은 용량을 기존 풀에 추가하거나 이 두 풀을 모두 추가하라는 메시지를 표시합니다.

자동 풀 생성은 다음 조건 중 하나가 참일 때 발생합니다.

* 스토리지 시스템에 풀이 없으며 새 풀을 생성할 수 있는 유사한 드라이브가 충분히 있습니다.
* 풀이 하나 이상 있는 스토리지 배열에 새 드라이브가 추가됩니다.


풀의 각 드라이브는 동일한 드라이브 유형(HDD 또는 SSD)이어야 하며 용량이 유사해야 합니다. System Manager에서 다음 작업을 완료하라는 메시지를 표시합니다.

* 이러한 유형의 드라이브 수가 충분한 경우 단일 풀을 생성합니다.
* 할당되지 않은 용량이 서로 다른 드라이브 유형으로 구성된 경우 여러 풀을 생성합니다.
* 스토리지 배열에 풀이 이미 정의되어 있는 경우 기존 풀에 드라이브를 추가하고 동일한 드라이브 유형의 새 드라이브를 풀에 추가합니다.
* 동일한 드라이브 유형의 드라이브를 기존 풀에 추가하고 다른 드라이브 유형을 사용하여 새 드라이브 유형이 다른 경우 다른 풀을 생성합니다.




== 수동 생성

자동 생성에서 최적의 구성을 확인할 수 없는 경우 풀을 수동으로 생성할 수 있습니다. 이 상황은 다음 이유 중 하나로 발생할 수 있습니다.

* 새 드라이브를 둘 이상의 풀에 추가할 수 있습니다.
* 하나 이상의 새 풀 후보가 셸프 손실 방지 또는 드로어 손실 방지 기능을 사용할 수 있습니다.
* 현재 풀 후보 중 하나 이상이 선반 손실 방지 또는 서랍 손실 보호 상태를 유지할 수 없습니다.


스토리지 배열에 여러 애플리케이션이 있고 동일한 드라이브 리소스에 대해 경쟁하지 않도록 하려면 풀을 수동으로 만들어야 할 수도 있습니다. 이 경우 하나 이상의 애플리케이션에 대해 더 작은 풀을 수동으로 생성하는 것이 좋습니다. 데이터를 분산할 볼륨이 많은 대규모 풀에 워크로드를 할당하는 대신 하나 또는 두 개의 볼륨만 할당할 수 있습니다. 특정 애플리케이션의 워크로드 전용으로 별도의 풀을 수동으로 생성하면 스토리지 시스템의 운영 속도가 빨라질 수 있고 경합이 줄어듭니다.
