---
permalink: sm-storage/automatic-versus-manual-host-creation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, manual, host, 
summary: 호스트를 생성하는 것은 스토리지 어레이가 호스트에 연결된 호스트를 파악하고 볼륨에 대한 I/O 액세스를 허용하는 데 필요한 단계 중 하나입니다. 호스트를 자동으로 또는 수동으로 생성할 수 있습니다. 
---
= 자동 및 수동 호스트 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트를 생성하는 것은 스토리지 어레이가 호스트에 연결된 호스트를 파악하고 볼륨에 대한 I/O 액세스를 허용하는 데 필요한 단계 중 하나입니다. 호스트를 자동으로 또는 수동으로 생성할 수 있습니다.



== 자동 작성

SCSI 기반(NVMe-oF 아님) 호스트의 자동 호스트 생성은 HCA(Host Context Agent)에 의해 시작됩니다. HCA는 스토리지 배열에 연결된 각 호스트에 설치할 수 있는 유틸리티입니다. HCA가 설치된 각 호스트는 I/O 경로를 통해 구성 정보를 스토리지 어레이 컨트롤러로 푸시합니다. 호스트 정보에 따라 컨트롤러는 자동으로 호스트와 관련 호스트 포트를 생성하고 호스트 유형을 설정합니다. 필요한 경우 System Manager를 사용하여 호스트 구성을 추가로 변경할 수 있습니다.

HCA가 자동 검색을 수행하면 호스트가 자동으로 호스트 페이지에 다음과 같은 특성을 표시합니다.

* 호스트의 시스템 이름에서 파생된 호스트 이름입니다.
* 호스트와 연결된 호스트 식별자 포트입니다.
* 호스트의 호스트 운영 체제 유형입니다.


호스트는 독립 실행형 호스트로 생성되지만 HCA는 호스트 클러스터를 자동으로 생성하거나 추가하지 않습니다.



== 수동 생성

다음 이유 중 하나로 호스트를 수동으로 생성할 수 있습니다.

. HCA 유틸리티를 호스트에 설치하지 않도록 선택했습니다.
. 스토리지 배열 컨트롤러에서 감지한 호스트 포트 식별자가 호스트에 올바르게 연결되어 있는지 확인해야 합니다.


수동 호스트 생성 중에 호스트 포트 식별자를 목록에서 선택하거나 직접 입력하여 연결합니다. 호스트를 생성한 후 볼륨에 대한 액세스를 공유하려는 경우 호스트에 볼륨을 할당하거나 호스트 클러스터에 추가할 수 있습니다.
