---
permalink: sm-storage/capacity-for-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity, volumes, 
summary: 스토리지 배열의 드라이브는 데이터의 물리적 스토리지 용량을 제공합니다. 데이터 저장을 시작하려면 먼저 할당된 용량을 풀 또는 볼륨 그룹이라고 하는 논리적 구성 요소로 구성해야 합니다. 이러한 스토리지 객체를 사용하여 스토리지 배열의 데이터를 구성, 저장, 유지 및 보존할 수 있습니다. 
---
= 볼륨에 용량을 할당하는 방법입니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 배열의 드라이브는 데이터의 물리적 스토리지 용량을 제공합니다. 데이터 저장을 시작하려면 먼저 할당된 용량을 풀 또는 볼륨 그룹이라고 하는 논리적 구성 요소로 구성해야 합니다. 이러한 스토리지 객체를 사용하여 스토리지 배열의 데이터를 구성, 저장, 유지 및 보존할 수 있습니다.



== 용량을 사용하여 볼륨 생성 및 확장

풀 또는 볼륨 그룹의 할당되지 않은 용량 또는 사용 가능한 용량에서 볼륨을 생성할 수 있습니다.

* 할당되지 않은 용량에서 볼륨을 생성할 경우 풀 또는 볼륨 그룹과 볼륨을 동시에 생성할 수 있습니다.
* 사용 가능한 용량에서 볼륨을 생성할 때 이미 존재하는 풀 또는 볼륨 그룹에 추가 볼륨을 생성하는 것입니다.


볼륨 용량을 확장한 후에는 파일 시스템 크기를 수동으로 늘려야 합니다. 이 방법은 사용 중인 파일 시스템에 따라 다릅니다. 자세한 내용은 호스트 운영 체제 설명서를 참조하십시오.



== 일반 볼륨 및 씬 볼륨의 용량 유형입니다

일반 볼륨이나 씬 볼륨을 생성할 수 있습니다. 보고된 용량과 할당된 용량은 일반 볼륨에서 동일하지만 씬 볼륨에서는 다릅니다.

* 일반 볼륨의 경우 보고된 볼륨 용량은 할당된 물리적 스토리지 용량과 같습니다. 물리적 스토리지 용량의 전체 양이 있어야 합니다. 물리적으로 할당된 공간은 호스트에 보고된 공간과 같습니다.
+
일반적으로 일반 볼륨의 보고된 용량을 볼륨이 커질 것으로 생각되는 최대 용량으로 설정합니다. 일반 볼륨은 애플리케이션이 생성할 때 모든 가용 용량이 예약되고 할당되기 때문에 애플리케이션에 예측 가능하고 우수한 성능을 제공합니다.

* 씬 볼륨의 경우 보고된 용량은 호스트에 보고된 용량이고, 할당된 용량은 데이터 쓰기에 현재 할당된 드라이브 공간의 양입니다.
+
보고된 용량은 스토리지 배열에 할당된 용량보다 클 수 있습니다. 씬 볼륨은 현재 사용 가능한 자산에 관계없이 성장에 맞게 크기를 조정할 수 있습니다.



[NOTE]
====
SANtricity System Manager에서는 씬 볼륨을 생성하는 옵션을 제공하지 않습니다. 씬 볼륨을 생성하려면 CLI(Command Line Interface)를 사용합니다.

====


== 일반 볼륨에 대한 용량 제한입니다

일반 볼륨의 최소 용량은 1MiB이고 최대 용량은 풀 또는 볼륨 그룹의 드라이브 수와 용량에 따라 결정됩니다.

일반 볼륨에 대해 보고된 용량을 늘릴 때는 다음 지침을 염두에 두십시오.

* 최대 3개의 소수 자릿수(예: 65.375GiB)를 지정할 수 있습니다.
* 용량은 볼륨 그룹에서 사용할 수 있는 최대값보다 작거나 같아야 합니다.
+
볼륨을 생성할 때 DSS(동적 세그먼트 크기) 마이그레이션에 일부 추가 용량이 사전 할당됩니다. DSS 마이그레이션은 볼륨의 세그먼트 크기를 변경할 수 있는 소프트웨어의 기능입니다.

* 2TiB보다 큰 볼륨은 일부 호스트 운영 체제에서 지원됩니다(보고된 최대 용량은 호스트 운영 체제에 의해 결정됨). 실제로 일부 호스트 운영 체제는 최대 128TiB 볼륨을 지원합니다. 자세한 내용은 호스트 운영 체제 설명서를 참조하십시오.




== 씬 볼륨의 용량 제한입니다

보고된 용량이 크고 할당된 용량이 상대적으로 적은 씬 볼륨을 생성할 수 있으므로 스토리지 활용도와 효율성을 높이는 데 도움이 됩니다. 애플리케이션을 중단하지 않고 할당된 용량을 늘릴 수 있으므로 씬 볼륨을 사용하면 스토리지 관리를 간소화할 수 있습니다.

씬 볼륨은 보고된 용량 및 할당된 용량 외에 쓰기 용량도 포함합니다. 쓰인 용량은 씬 볼륨에 할당된 예약 용량에서 기록된 용량입니다.

다음 표에는 씬 볼륨의 용량 제한이 나와 있습니다.

[cols="3*"]
|===
| 용량 유형입니다 | 최소 크기 | 최대 크기 


 a| 
보고됨
 a| 
32MiB
 a| 
256TiB



 a| 
할당됨
 a| 
4MiB
 a| 
64TiB

|===
씬 볼륨의 경우 보고된 최대 256TiB에 도달한 경우 용량을 늘릴 수 없습니다. 씬 볼륨의 예약된 용량이 보고된 최대 용량보다 큰 크기로 설정되었는지 확인합니다.

할당된 용량 제한에 따라 할당된 용량이 자동으로 확장됩니다. 할당된 용량 제한을 사용하면 씬 볼륨의 자동 증가를 보고된 용량 이하로 제한할 수 있습니다. 기록된 데이터의 양이 할당된 용량에 근접하면 할당된 용량 제한을 변경할 수 있습니다.

할당된 용량 제한을 변경하려면 Storage [Volumes > Thin Volume Monitoring 탭 > Change Limit] 메뉴를 선택합니다.

System Manager에서는 씬 볼륨을 생성할 때 전체 용량을 할당하지 않기 때문에 풀에 사용 가능한 용량이 부족할 수 있습니다. 공간이 부족하면 씬 볼륨뿐 아니라 풀에서 용량이 필요한 다른 작업(예: 스냅샷 이미지 또는 스냅샷 볼륨)에 대해서도 풀에 대한 쓰기를 차단할 수 있습니다. 그러나 풀에서 읽기 작업은 계속 수행할 수 있습니다. 이 상황이 발생하면 경고 임계값 경고가 표시됩니다.
