---
permalink: sm-storage/capacity-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity terms 
summary: 스토리지 어레이에 적용되는 용량 조건에 대해 알아보십시오. 
---
= 용량 용어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 어레이에 적용되는 용량 조건에 대해 알아보십시오.



== 스토리지 오브젝트

다음 용어는 스토리지 어레이와 상호 작용할 수 있는 여러 유형의 스토리지 개체에 대해 설명합니다.

[cols="25h,~"]
|===
| 스토리지 객체 | 설명 


 a| 
호스트
 a| 
호스트는 스토리지 배열의 볼륨에 입출력을 전송하는 서버입니다.



 a| 
LUN을 클릭합니다
 a| 
LUN(Logical Unit Number)은 호스트가 볼륨을 액세스하는 데 사용하는 주소 공간에 할당된 번호입니다. 볼륨은 LUN 형태의 용량으로 호스트에 표시됩니다.

각 호스트에는 고유한 LUN 주소 공간이 있습니다. 따라서 서로 다른 호스트에서 동일한 LUN을 사용하여 서로 다른 볼륨에 액세스할 수 있습니다.



 a| 
미러 정합성 보장 그룹
 a| 
미러 정합성 보장 그룹은 하나 이상의 미러링된 쌍에 대한 컨테이너입니다. 비동기식 미러링 작업의 경우 미러 정합성 보장 그룹을 생성해야 합니다.



 a| 
미러링된 볼륨 쌍
 a| 
미러링된 쌍은 기본 볼륨 및 보조 볼륨이라는 두 개의 볼륨으로 구성됩니다.



 a| 
수영장
 a| 
풀은 논리적으로 그룹화된 드라이브 집합입니다. 풀을 사용하여 호스트에서 액세스할 수 있는 볼륨을 하나 이상 생성할 수 있습니다. (풀 또는 볼륨 그룹에서 볼륨을 생성하는 경우)



 a| 
스냅샷 정합성 보장 그룹
 a| 
스냅샷 정합성 보장 그룹은 스냅샷 이미지를 생성할 때 단일 개체로 처리되는 볼륨의 모음입니다. 이러한 각 볼륨에는 고유한 스냅샷 이미지가 있지만 모든 이미지는 동시에 생성됩니다.



 a| 
스냅샷 그룹
 a| 
스냅샷 그룹은 단일 기본 볼륨의 스냅샷 이미지 모음입니다.



 a| 
스냅샷 볼륨
 a| 
스냅샷 볼륨을 사용하면 호스트가 스냅샷 이미지의 데이터에 액세스할 수 있습니다. 스냅샷 볼륨에는 원래 스냅샷 이미지에 영향을 주지 않고 기본 볼륨에 대한 수정 사항을 저장하는 자체 예약 용량이 포함되어 있습니다.



 a| 
볼륨
 a| 
볼륨은 애플리케이션, 데이터베이스 및 파일 시스템이 데이터를 저장하는 컨테이너입니다. 호스트가 스토리지의 스토리지를 액세스할 수 있도록 생성되는 논리적 구성 요소입니다.



 a| 
볼륨 그룹
 a| 
볼륨 그룹은 공유 특성을 가진 볼륨의 컨테이너입니다. 볼륨 그룹의 용량과 RAID 레벨이 정의되어 있습니다. 볼륨 그룹을 사용하여 호스트에서 액세스할 수 있는 볼륨을 하나 이상 생성할 수 있습니다. 볼륨 그룹 또는 풀에서 볼륨을 생성합니다.

|===


== 스토리지 용량

다음 용어는 스토리지 배열에 사용되는 다양한 유형의 용량에 대해 설명합니다.

[cols="25h,~"]
|===
| 용량 유형입니다 | 설명 


 a| 
할당된 용량입니다
 a| 
할당된 용량은 풀 또는 볼륨 그룹의 드라이브에서 할당된 물리적 용량입니다.

할당된 용량을 사용하여 볼륨을 생성하고 복제 서비스 작업을 수행할 수 있습니다.



 a| 
여유 용량
 a| 
여유 용량은 볼륨 생성 또는 복제 서비스 작업 및 스토리지 객체에 아직 할당되지 않은 풀 또는 볼륨 그룹에서 사용할 수 있는 용량입니다.



 a| 
풀 또는 볼륨 그룹 용량입니다
 a| 
풀, 볼륨 또는 볼륨 그룹 용량은 풀 또는 볼륨 그룹에 할당된 스토리지 시스템의 용량입니다. 이 용량은 볼륨을 생성하고 복사 서비스 작업 및 스토리지 오브젝트의 다양한 용량 요구사항을 지원하는 데 사용됩니다.



 a| 
풀을 사용할 수 없는 용량입니다
 a| 
풀 사용 불가 용량은 드라이브 크기가 일치하지 않아 사용할 수 없는 풀의 공간입니다.



 a| 
보존 용량
 a| 
Preservation capacity는 잠재적 드라이브 장애를 지원하기 위해 풀에 예약된 용량(드라이브 수)입니다.



 a| 
보고된 용량입니다
 a| 
보고된 용량은 호스트에 보고되고 호스트에서 액세스할 수 있는 용량입니다.



 a| 
예약된 용량입니다
 a| 
예약된 용량은 복제 서비스 작업 및 스토리지 객체에 사용되는 물리적 할당 용량입니다. 호스트에서 직접 읽을 수 없습니다.



 a| 
SSD 캐시
 a| 
[NOTE]
====
EF600 또는 EF300 스토리지 시스템에서는 이 기능을 사용할 수 없습니다.

====
SSD Cache는 스토리지 어레이에서 논리적으로 함께 그룹화하는 SSD(Solid State Disk) 드라이브 세트입니다. SSD Cache 기능은 가장 자주 액세스되는 데이터("핫" 데이터)를 지연 시간이 짧은 SSD 드라이브에 캐싱하여 애플리케이션 워크로드를 동적으로 가속화합니다.



 a| 
할당되지 않은 용량
 a| 
할당되지 않은 용량은 스토리지 배열의 공간이며, 풀 또는 볼륨 그룹에 * 할당되지 않음 * 이 할당된 공간입니다.



 a| 
쓰인 용량
 a| 
쓰인 용량은 씬 볼륨에 할당된 예약 용량에서 기록된 용량입니다.

|===