---
permalink: sm-storage/change-settings-for-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, volume 
summary: 이름, 호스트 할당, 세그먼트 크기, 수정 우선순위, 캐싱 등 볼륨 설정을 변경할 수 있습니다. 등. 
---
= SANtricity System Manager에서 볼륨 설정 변경
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이름, 호스트 할당, 세그먼트 크기, 수정 우선순위, 캐싱 등과 같은 볼륨 설정을 변경할 수 있습니다. 등.

.시작하기 전에
변경하려는 볼륨이 최적 상태입니다.


NOTE: 볼륨 설정을 변경하는 동안 일부 작업을 사용할 수 없습니다

.단계
. 왼쪽 패널에서 menu:Storage[Volumes]를 선택합니다.
. 변경하려는 볼륨을 선택한 다음 menu:ellipsis icon[Edit Settings]을 클릭합니다.
+
선택한 볼륨의 구성 설정을 보여주는 '볼륨 설정 편집' 창이 나타납니다.

. 필요에 따라 볼륨 설정을 구성하십시오.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
이름
 a| 
볼륨의 이름을 표시합니다. 현재 이름이 더 이상 의미가 없거나 적용할 수 없는 경우 볼륨의 이름을 변경합니다.



 a| 
호스트
 a| 
볼륨 할당을 표시합니다. I/O 작업을 위해 액세스할 수 있도록 볼륨을 호스트 또는 호스트 클러스터에 할당합니다. 이 할당은 호스트 또는 호스트 클러스터에 특정 볼륨 또는 스토리지 배열의 여러 볼륨에 대한 액세스 권한을 부여합니다.

** * Assigned to * -- 선택한 볼륨에 대한 액세스 권한이 있는 호스트 또는 호스트 클러스터를 식별합니다.
** * LUN * -- 논리 단위 번호(LUN)는 호스트가 볼륨에 액세스하는 데 사용하는 주소 공간에 할당된 번호입니다. 볼륨은 LUN 형태의 용량으로 호스트에 표시됩니다. 각 호스트에는 고유한 LUN 주소 공간이 있습니다. 따라서 서로 다른 호스트에서 동일한 LUN을 사용하여 서로 다른 볼륨에 액세스할 수 있습니다.
+

NOTE: NVMe 인터페이스의 경우 이 열에는 네임스페이스 ID가 표시됩니다. 네임스페이스는 블록 액세스를 위해 포맷된 NVM 스토리지입니다. 스토리지 배열의 볼륨과 관련된 SCSI의 논리 유닛과 유사합니다. 네임스페이스 ID는 네임스페이스에 대한 NVMe 컨트롤러의 고유 식별자이며 1에서 255 사이의 값으로 설정할 수 있습니다. SCSI의 LUN(Logical Unit Number)과 유사합니다.





 a| 
세그먼트 크기 조정
 a| 
에는 볼륨 그룹의 볼륨에 대해서만 표시되는 세그먼트 크기 조정 설정이 나와 있습니다. 세그먼트 크기를 변경하여 성능을 최적화할 수 있습니다.

* 허용되는 세그먼트 크기 전환 * -- System Manager는 허용되는 세그먼트 크기 전환을 결정합니다. 현재 세그먼트 크기에서 잘못 전환되는 세그먼트 크기는 드롭다운 목록에서 사용할 수 없습니다. 허용되는 전이는 일반적으로 현재 세그먼트 크기의 두 배 또는 절반입니다. 예를 들어 현재 볼륨 세그먼트 크기가 32KiB인 경우 16KiB 또는 64KiB의 새 볼륨 세그먼트 크기가 허용됩니다.

* SSD 캐시 사용 볼륨 * -- SSD 캐시 사용 볼륨에 대해 4KiB 세그먼트 크기를 지정할 수 있습니다. 작은 블록 입출력 작업을 처리하는 SSD Cache 지원 볼륨(예: 16KiB 입출력 블록 크기 이하)에 대해서만 4KiB 세그먼트 크기를 선택해야 합니다. 대규모 블록 순차적 작업을 처리하는 SSD Cache 지원 볼륨의 세그먼트 크기로 4KiB를 선택하면 성능에 영향을 미칠 수 있습니다.

* 세그먼트 크기를 변경하는 시간 * -- 볼륨의 세그먼트 크기를 변경하는 시간은 다음 변수에 따라 다릅니다.

** 호스트로부터의 I/O 로드
** 볼륨의 수정 우선 순위입니다
** 볼륨 그룹의 드라이브 수입니다
** 드라이브 채널 수입니다
** 스토리지 어레이 컨트롤러의 처리 능력 볼륨의 세그먼트 크기를 변경하면 I/O 성능에 영향을 미치지만 데이터를 계속 사용할 수 있습니다.




 a| 
수정 우선 순위
 a| 
에는 볼륨 그룹의 볼륨에 대해서만 표시되는 수정 우선 순위 설정이 나와 있습니다.

수정 우선순위는 시스템 성능과 관련하여 볼륨 수정 작업에 할당되는 처리 시간을 정의합니다. 시스템 성능에 영향을 미칠 수 있지만 볼륨 수정 우선 순위를 높일 수 있습니다.

슬라이더 막대를 이동하여 우선 순위 수준을 선택합니다.

* 수정 우선 순위 비율 * - 최저 우선 순위 비율은 시스템 성능에 도움이 되지만 수정 작업은 더 오래 걸립니다. 가장 높은 우선 순위의 경우 수정 작업에 도움이 되지만 시스템 성능이 저하될 수 있습니다.

|===
====
. 저장 * 을 클릭합니다.
+
System Manager는 선택에 따라 볼륨 설정을 변경합니다.



.작업을 마친 후
선택한 볼륨에 대해 현재 실행 중인 변경 작업의 진행 상황을 보려면 menu:Storage[Operations in Progress]를 선택하십시오.
