---
permalink: sm-storage/change-host-port-identifiers-for-a-host.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host port, identifiers, host 
summary: 호스트 포트 식별자의 사용자 레이블을 변경하거나, 호스트에 새 호스트 포트 식별자를 추가하거나, 호스트에서 호스트 포트 식별자를 삭제하려면 호스트 포트 식별자를 변경합니다. 
---
= 호스트의 호스트 포트 식별자를 변경합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트 포트 식별자의 사용자 레이블을 변경하거나, 호스트에 새 호스트 포트 식별자를 추가하거나, 호스트에서 호스트 포트 식별자를 삭제하려면 호스트 포트 식별자를 변경합니다.

.이 작업에 대해
호스트 포트 식별자를 변경할 때 다음 지침을 염두에 두십시오.

* * 추가 * -- 호스트 포트를 추가하면 스토리지 배열에 연결하기 위해 생성한 호스트에 호스트 포트 식별자를 연결합니다. HBA(호스트 버스 어댑터) 유틸리티를 사용하여 포트 정보를 수동으로 입력할 수 있습니다.
* * 편집 * -- 호스트 포트를 편집하여 호스트 포트를 다른 호스트로 이동(연결)할 수 있습니다. 호스트 버스 어댑터 또는 iSCSI 이니시에이터를 다른 호스트로 이동했을 수 있으므로 호스트 포트를 새 호스트로 이동(연결)해야 합니다.
* * 삭제 * -- 호스트 포트를 삭제하여 호스트에서 호스트 포트를 제거(연결 해제)할 수 있습니다.


.단계
. 스토리지 [호스트] 메뉴를 선택합니다.
. 포트를 연결할 호스트를 선택한 다음 * 설정 보기/편집 * 을 클릭합니다.
+
호스트 클러스터의 호스트에 포트를 추가하려면 호스트 클러스터를 확장하고 원하는 호스트를 선택합니다. 호스트 클러스터 수준에서는 포트를 추가할 수 없습니다.

+
현재 호스트 설정을 보여주는 대화 상자가 나타납니다.

. 호스트 포트 * 탭을 클릭합니다.
+
대화 상자에 현재 호스트 포트 식별자가 표시됩니다.

. 호스트 포트 식별자 설정을 적절하게 변경합니다.
+
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
호스트 포트
 a| 
다음 옵션 중 하나를 선택할 수 있습니다.

** * Add * -- Add를 사용하여 새 호스트 포트 식별자를 호스트에 연결합니다. 호스트 포트 식별자 이름의 길이는 호스트 인터페이스 기술에 의해 결정됩니다. Fibre Channel 및 Infiniband 호스트 포트 식별자 이름은 16자여야 합니다. iSCSI 호스트 포트 식별자 이름은 최대 223자입니다. 포트는 고유해야 합니다. 이미 구성된 포트 번호는 허용되지 않습니다.
** * 삭제 * -- 호스트 포트 식별자를 제거(연결 해제)하려면 삭제를 사용합니다. 삭제 옵션은 호스트 포트를 물리적으로 제거하지 않습니다. 이 옵션은 호스트 포트와 호스트 간의 연결을 제거합니다. 호스트 버스 어댑터 또는 iSCSI 이니시에이터를 제거하지 않는 한, 호스트 포트는 컨트롤러에서 계속 인식됩니다.
+
[NOTE]
====
호스트 포트 식별자를 삭제하면 이 호스트와 더 이상 연결되지 않습니다. 또한 호스트는 이 호스트 포트 식별자를 통해 할당된 볼륨에 대한 액세스 권한을 상실합니다.

====




 a| 
라벨
 a| 
포트 레이블 이름을 변경하려면 * 편집 * 아이콘(연필)을 클릭합니다. 포트 레이블 이름은 고유해야 합니다. 이미 구성된 레이블 이름은 허용되지 않습니다.



 a| 
CHAP 암호
 a| 
iSCSI 호스트에만 표시됩니다. 이니시에이터(iSCSI 호스트)의 CHAP 암호를 설정하거나 변경할 수 있습니다.

System Manager에서는 CHAP(Challenge Handshake Authentication Protocol) 방법을 사용하여 초기 링크 중에 대상 및 초기자의 ID를 확인합니다. 인증은 CHAP 암호라는 공유 보안 키를 기반으로 합니다.

|===
. 저장 * 을 클릭합니다.

