---
permalink: sm-storage/change-the-settings-for-a-snapshot-schedule.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, settings, snapshot, schedule 
summary: 스냅샷 스케줄의 경우 자동 수집 시간 또는 수집 빈도를 변경할 수 있습니다. 
---
= 스냅샷 스케줄의 설정을 변경합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 스케줄의 경우 자동 수집 시간 또는 수집 빈도를 변경할 수 있습니다.

.이 작업에 대해
기존 스냅샷 스케줄에서 설정을 가져오거나 필요에 따라 설정을 수정할 수 있습니다.

스냅샷 스케줄은 스냅샷 그룹 또는 스냅샷 정합성 보장 그룹에 연결되기 때문에 예약된 용량은 스케줄 설정 변경의 영향을 받을 수 있습니다.

.단계
. 스토리지 [스냅샷] 메뉴를 선택합니다.
. Schedules * 탭을 클릭합니다.
. 변경할 스냅샷 스케줄을 선택한 다음 * 편집 * 을 클릭합니다.
+
스냅샷 일정 편집 대화 상자가 나타납니다.

. 다음 중 하나를 수행합니다.
+
** * 다른 스냅샷 개체에서 이전에 정의한 일정 사용 * -- * 일정 가져오기 * 를 클릭하고 가져올 일정이 있는 개체를 선택한 다음 * 가져오기 * 를 클릭합니다.
** * 스케줄 설정 편집 * -- 아래의 필드 세부 정보를 참조하십시오.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
일/월
 a| 
다음 옵션 중 하나를 선택합니다.

*** * Daily/Weekly * -- 동기화 스냅샷을 위한 개별 요일을 선택합니다. 또한 일일 일정을 원하는 경우 오른쪽 상단에서 * Select All Days * (모든 날짜 선택 *) 확인란을 선택할 수도 있습니다.
*** * Monthly/Yearly * -- 동기화 스냅샷을 위한 개별 월을 선택합니다. On day(s) * 필드에 동기화가 발생하는 날짜를 입력합니다. 유효한 항목은 * 1 * ~ * 31 * 및 * Last * 입니다. 여러 날짜를 쉼표 또는 세미콜론으로 구분할 수 있습니다. 포함 날짜에 하이픈을 사용합니다. 예: 1,3, 4,10-15, Last. 월 단위 일정을 원하는 경우 오른쪽 상단에서 * 모든 월 선택 * 확인란을 선택할 수도 있습니다.




 a| 
시작 시간
 a| 
드롭다운 목록에서 일별 스냅샷의 새 시작 시간을 선택합니다. 선택사항은 30분 단위로 제공됩니다. 시작 시간은 현재 시간보다 30분 먼저 설정됩니다.



 a| 
시간대
 a| 
드롭다운 목록에서 스토리지 어레이의 시간대를 선택합니다.



 a| 
매일 스냅샷 수

스냅샷 사이의 시간입니다
 a| 
하루에 생성할 스냅샷 이미지 수를 선택합니다.

둘 이상의 을 선택한 경우 복원 지점 사이의 시간도 선택합니다. 여러 복원 지점의 경우 충분한 예약 용량이 있어야 합니다.



 a| 
시작 날짜

종료 날짜

종료 날짜가 없습니다
 a| 
동기화를 시작할 시작 날짜를 입력합니다. 종료 날짜를 입력하거나 * 종료 날짜 없음 * 을 선택합니다.

|===
====


. 저장 * 을 클릭합니다.

