---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-snapshot-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, snapshot, group 
summary: 스냅샷 그룹의 이름, 자동 삭제 설정, 허용되는 최대 스냅샷 이미지 수, System Manager에서 예약된 용량 알림 알림을 보내는 백분율 지점 또는 예약된 용량이 정의된 최대 비율에 도달할 때 사용할 정책을 변경하도록 스냅샷 그룹의 설정을 변경할 수 있습니다. 
---
= 스냅샷 그룹에 대한 예약된 용량 설정을 변경합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 그룹의 이름, 자동 삭제 설정, 허용되는 최대 스냅샷 이미지 수, System Manager에서 예약된 용량 알림 알림을 보내는 백분율 지점 또는 예약된 용량이 정의된 최대 비율에 도달할 때 사용할 정책을 변경하도록 스냅샷 그룹의 설정을 변경할 수 있습니다.

스냅샷 그룹을 생성하는 동안 그룹에 포함된 모든 스냅샷 이미지에 대한 데이터를 저장하기 위해 예약된 용량이 생성됩니다.

.단계
. 스토리지 [풀 및 볼륨 그룹] 메뉴를 선택합니다.
. 예약된 용량 * 탭을 클릭합니다.
. 편집할 스냅샷 그룹을 선택한 다음 * 설정 보기/편집 * 을 클릭합니다.
+
스냅샷 그룹 설정 대화 상자가 나타납니다.

. 스냅샷 그룹의 설정을 적절하게 변경합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
* 스냅샷 그룹 설정 *



 a| 
이름
 a| 
스냅샷 그룹의 이름입니다. 스냅샷 그룹의 이름을 지정해야 합니다.



 a| 
자동 삭제
 a| 
그룹에 있는 총 스냅샷 이미지 수를 사용자 정의 최대치 이하로 유지하는 설정입니다. 이 옵션을 설정하면 새 스냅샷이 생성될 때마다 System Manager가 그룹에서 가장 오래된 스냅샷 이미지를 자동으로 삭제하여 그룹에 허용되는 최대 스냅샷 이미지 수를 준수합니다.



 a| 
스냅샷 이미지 제한
 a| 
스냅샷 그룹에 허용되는 최대 스냅샷 이미지 수를 지정하는 구성 가능한 값입니다.



 a| 
스냅샷 스케줄입니다
 a| 
예 인 경우 스냅샷을 자동으로 생성하도록 스케줄이 설정됩니다.



 a| 
* 예약된 용량 설정 *



 a| 
다음 경우에 알림:
 a| 
spinner 상자를 사용하여 스냅샷 그룹의 예약된 용량이 거의 꽉 찰 때 System Manager에서 경고 알림을 보내는 백분율 지점을 조정합니다.

스냅샷 그룹의 예약 용량이 지정된 임계값을 초과하면 System Manager에서 경고를 보내, 예약된 용량을 늘리거나 불필요한 개체를 삭제할 수 있습니다.



 a| 
전체 예약 용량에 대한 정책입니다
 a| 
다음 정책 중 하나를 선택할 수 있습니다.

** * 가장 오래된 스냅샷 이미지 제거 * -- System Manager는 스냅샷 그룹에서 가장 오래된 스냅샷 이미지를 자동으로 제거합니다. 그러면 스냅샷 이미지 예약 용량이 그룹 내에서 재사용될 수 있습니다.
** * 기본 볼륨에 대한 쓰기 거부 * -- 예약된 용량이 최대 정의 비율에 도달하면 System Manager가 예약된 용량 액세스를 트리거한 기본 볼륨에 대한 모든 I/O 쓰기 요청을 거부합니다.




 a| 
* 관련 개체 *



 a| 
기본 볼륨
 a| 
그룹에 사용된 기본 볼륨의 이름입니다. 기본 볼륨은 스냅샷 이미지가 생성되는 원본입니다. 일반 볼륨이거나 씬 볼륨일 수 있으며 일반적으로 호스트에 할당됩니다. 기본 볼륨은 볼륨 그룹 또는 디스크 풀에 상주할 수 있습니다.



 a| 
스냅샷 이미지
 a| 
이 그룹에서 생성된 이미지 수입니다. 스냅샷 이미지는 특정 시점에 캡처된 볼륨 데이터의 논리적 복사본입니다. 복원 지점과 마찬가지로 스냅샷 이미지를 통해 알려진 양호한 데이터 집합으로 롤백할 수 있습니다. 호스트가 스냅샷 이미지를 액세스할 수는 있지만 해당 이미지를 직접 읽거나 쓸 수는 없습니다.

|===
====
. 변경 사항을 스냅샷 그룹 설정에 적용하려면 * 저장 * 을 클릭합니다.

