---
permalink: sm-storage/change-allocated-capacity-limit-for-a-thin-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, allocated capacity, thin volume 
summary: 필요 시 공간을 할당할 수 있는 씬 볼륨의 경우 씬 볼륨이 자동으로 확장될 수 있는 할당된 용량을 제한하는 제한을 변경할 수 있습니다. 
---
= 씬 볼륨에 할당된 용량 제한을 변경합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
필요 시 공간을 할당할 수 있는 씬 볼륨의 경우 씬 볼륨이 자동으로 확장될 수 있는 할당된 용량을 제한하는 제한을 변경할 수 있습니다.

씬 볼륨이 할당된 용량 제한에 근접하면 홈 페이지의 알림 영역으로 알림(경고 임계값 초과)이 전송되는 백분율 지점을 변경할 수도 있습니다. 이 경고 알림을 활성화 또는 비활성화할 수 있습니다.

[NOTE]
====
EF600 또는 EF300 스토리지 시스템에서는 이 기능을 사용할 수 없습니다.

====
할당된 용량 제한에 따라 할당된 용량이 자동으로 확장됩니다. 할당된 용량 제한을 사용하면 씬 볼륨의 자동 증가를 보고된 용량 이하로 제한할 수 있습니다. 기록된 데이터의 양이 할당된 용량에 근접하면 할당된 용량 제한을 변경할 수 있습니다.

씬 볼륨의 할당된 용량 한도 및 경고 임계값을 변경할 때는 볼륨의 사용자 데이터와 복제 서비스 데이터 모두에서 사용할 공간을 고려해야 합니다.

.단계
. Storage [Volumes](저장소 [볼륨]) 메뉴를 선택합니다.
. Thin Volume Monitoring * 탭을 선택합니다.
+
Thin Volume Monitoring(씬 볼륨 모니터링) 보기가 나타납니다.

. 변경할 씬 볼륨을 선택한 다음 * Change Limit * 를 선택합니다.
+
변경 한도 대화 상자가 나타납니다. 이 대화 상자에 선택한 씬 볼륨의 할당된 용량 제한 및 경고 임계값 설정이 표시됩니다.

. 필요에 따라 할당된 용량 한도 및 경고 임계값을 변경합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
할당된 용량 제한을 다음으로 변경...
 a| 
쓰기가 실패하는 임계값으로, 씬 볼륨에서 추가 리소스를 사용할 수 없습니다. 이 임계값은 볼륨에서 보고된 용량 크기의 백분율입니다.



 a| 
다음 경우에 알림: (경고 임계값)
 a| 
씬 볼륨이 할당된 용량 제한에 근접할 때 시스템에서 알림을 생성하도록 하려면 확인란을 선택합니다. 이 알림은 홈 페이지의 알림 영역으로 전송됩니다. 이 임계값은 볼륨에서 보고된 용량 크기의 백분율입니다.

경고 임계값 경고 알림을 비활성화하려면 이 확인란의 선택을 취소합니다.

|===
====
. 저장 * 을 클릭합니다.

