---
permalink: sm-storage/change-the-settings-for-a-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, settings, snapshot, volume 
summary: '스냅샷 볼륨 또는 스냅샷 정합성 보장 그룹 스냅샷 볼륨에 대한 설정을 변경하여 스냅샷 볼륨 이름을 바꾸거나, SSD 캐싱을 활성화 또는 비활성화하거나, 호스트, 호스트 클러스터 또는 LUN(Logical Unit Number) 할당을 변경할 수 있습니다.' 
---
= 스냅샷 볼륨의 볼륨 설정을 변경합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 볼륨 또는 스냅샷 정합성 보장 그룹 스냅샷 볼륨에 대한 설정을 변경하여 스냅샷 볼륨 이름을 바꾸거나, SSD 캐싱을 활성화 또는 비활성화하거나, 호스트, 호스트 클러스터 또는 LUN(Logical Unit Number) 할당을 변경할 수 있습니다.

.단계
. 스토리지 [스냅샷] 메뉴를 선택합니다.
. Snapshot Volumes * 탭을 클릭합니다.
. 변경할 스냅샷 볼륨을 선택한 다음 * 설정 보기/편집 * 을 클릭합니다.
+
Snapshot Volume Settings(스냅샷 볼륨 설정) 대화 상자가 나타납니다.

. 스냅샷 볼륨에 대한 설정을 적절히 보거나 편집합니다.
+
.필드 상세정보
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
* 스냅샷 볼륨 *



 a| 
이름
 a| 
스냅샷 볼륨의 이름을 변경할 수 있습니다.



 a| 
할당 대상
 a| 
스냅샷 볼륨에 대한 호스트 또는 호스트 클러스터 할당을 변경할 수 있습니다.



 a| 
LUN을 클릭합니다
 a| 
스냅샷 볼륨에 대한 LUN 할당을 변경할 수 있습니다.



 a| 
SSD 캐시
 a| 
SSD(Solid State Disk)에서 읽기 전용 캐싱을 설정/해제할 수 있습니다.



 a| 
* 관련 개체 *



 a| 
스냅샷 이미지
 a| 
스냅샷 볼륨과 연결된 스냅샷 이미지를 볼 수 있습니다. 스냅샷 이미지는 특정 시점에 캡처된 볼륨 데이터의 논리적 복사본입니다. 복원 지점과 마찬가지로 스냅샷 이미지를 통해 알려진 양호한 데이터 집합으로 롤백할 수 있습니다. 호스트가 스냅샷 이미지를 액세스할 수는 있지만 해당 이미지를 직접 읽거나 쓸 수는 없습니다.



 a| 
기본 볼륨
 a| 
스냅샷 볼륨과 연결된 기본 볼륨을 볼 수 있습니다. 기본 볼륨은 스냅샷 이미지가 생성되는 원본입니다. 일반 볼륨이거나 씬 볼륨일 수 있으며 일반적으로 호스트에 할당됩니다. 기본 볼륨은 볼륨 그룹 또는 디스크 풀에 상주할 수 있습니다.



 a| 
스냅샷 그룹
 a| 
스냅샷 볼륨과 연결된 스냅샷 그룹을 볼 수 있습니다. 스냅샷 그룹은 단일 기본 볼륨의 스냅샷 이미지 모음입니다.

|===
====

