---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-consistency-group-member-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, consistency group, member volume 
summary: 일관성 그룹 구성원 볼륨에 대한 설정을 변경하여 구성원 볼륨에 대한 예약 용량이 거의 다 찼을 때 System Manager에서 경고 알림을 보내는 백분율 지점을 조정하고 예약 용량이 최대 정의에 도달할 때 사용할 정책을 변경할 수 있습니다 백분율. 
---
= 정합성 보장 그룹 구성원 볼륨에 대한 예약된 용량 설정을 변경합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
정합성 보장 그룹 구성원 볼륨의 설정을 변경하여 구성원 볼륨의 예약된 용량이 거의 가득 차면 SANtricity 시스템 관리자가 알림 알림을 보내는 백분율 지점을 조정하고 예약된 용량이 정의된 최대 비율에 도달할 때 사용할 정책을 변경할 수 있습니다.

.이 작업에 대해
개별 구성원 볼륨에 대한 예약된 용량 설정을 변경하면 정합성 보장 그룹에 연결된 모든 구성원 볼륨에 대한 예약된 용량 설정도 변경됩니다.

.단계
. 스토리지 [풀 및 볼륨 그룹] 메뉴를 선택합니다.
. 예약된 용량 * 탭을 클릭합니다.
. 편집할 일관성 그룹 구성원 볼륨을 선택한 다음 * 설정 보기/편집 * 을 클릭합니다.
+
구성원 볼륨 예약 용량 설정 대화 상자가 나타납니다.

. 구성원 볼륨에 대한 예약된 용량 설정을 적절하게 변경합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
다음 경우에 알림:
 a| 
스피너 상자를 사용하여 멤버 볼륨에 대한 예약된 용량이 거의 가득 찰 때 System Manager에서 경고 알림을 보내는 백분율 지점을 조정합니다.

구성원 볼륨의 예약된 용량이 지정된 임계값을 초과하면 System Manager에서 경고를 보내 예약된 용량을 늘리거나 불필요한 개체를 삭제할 수 있습니다.


NOTE: 하나의 구성원 볼륨에 대한 경고 설정을 변경하면 동일한 정합성 보장 그룹에 속한 _ALL_구성원 볼륨에 대해 이 설정이 변경됩니다.



 a| 
전체 예약 용량에 대한 정책입니다
 a| 
다음 정책 중 하나를 선택할 수 있습니다.

** * 가장 오래된 스냅샷 이미지 제거 * -- System Manager는 정합성 보장 그룹에서 가장 오래된 스냅샷 이미지를 자동으로 제거합니다. 그러면 그룹 내에서 재사용하기 위해 구성원의 예약된 용량이 해제됩니다.
** * 기본 볼륨에 대한 쓰기 거부 * -- 예약된 용량이 최대 정의 비율에 도달하면 System Manager가 예약된 용량 액세스를 트리거한 기본 볼륨에 대한 모든 I/O 쓰기 요청을 거부합니다.


|===
====
. 변경 사항을 적용하려면 * 저장 * 을 클릭합니다.


.결과
System Manager에서는 구성원 볼륨에 대한 예약된 용량 설정과 정합성 보장 그룹의 모든 구성원 볼륨에 대한 예약된 용량 설정을 변경합니다.
