---
permalink: sm-storage/comparison-between-thick-volumes-and-thin-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, comparison, thick volumes, thin volumes 
summary: 일반 볼륨은 항상 완전히 프로비저닝되므로 볼륨을 생성할 때 모든 용량이 할당됩니다. 씬 볼륨은 항상 씬 프로비저닝됩니다. 즉, 데이터가 볼륨에 쓰일 때 용량이 할당됩니다. 
---
= 일반 볼륨과 씬 볼륨 비교
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
일반 볼륨은 항상 완전히 프로비저닝되므로 볼륨을 생성할 때 모든 용량이 할당됩니다. 씬 볼륨은 항상 씬 프로비저닝됩니다. 즉, 데이터가 볼륨에 쓰일 때 용량이 할당됩니다.

[NOTE]
====
System Manager에서는 씬 볼륨을 생성하는 옵션을 제공하지 않습니다. 씬 볼륨을 생성하려면 CLI(Command Line Interface)를 사용합니다.

====
[cols="25h,~"]
|===
| 볼륨 유형입니다 | 설명 


 a| 
일반 볼륨
 a| 
* 일반 볼륨은 풀 또는 볼륨 그룹에서 생성됩니다.
* 일반 볼륨의 경우 향후 스토리지 요구 사항을 예상하여 많은 양의 스토리지 공간이 사전에 제공됩니다.
* 일반 볼륨은 볼륨을 생성할 때 물리적 스토리지에 사전 할당된 볼륨의 전체 크기로 생성됩니다. 이 사전 할당은 100GiB 볼륨을 생성하는 것이 실제로 드라이브에서 할당된 용량을 100GiB로 사용한다는 것을 의미합니다. 그러나 공간이 계속 사용되지 않아 스토리지 용량의 활용률이 부족할 수 있습니다.
* 일반 볼륨을 생성할 때 단일 볼륨에 용량을 초과 할당하지 않도록 합니다. 단일 볼륨에 용량을 초과 할당하면 시스템의 모든 물리적 스토리지를 빠르게 사용할 수 있습니다.
* 복제 서비스(스냅샷 이미지, 스냅샷 볼륨, 볼륨 복사본, 비동기식 미러링)에는 스토리지 용량도 필요하므로 일반 볼륨에 모든 용량을 할당하지 마십시오. 공간이 부족하면 풀 또는 볼륨 그룹에 대한 쓰기가 차단될 수 있습니다. 이 상황이 발생하면 여유 용량 경고 임계값 경고가 표시됩니다.




 a| 
씬 볼륨
 a| 
* 씬 볼륨은 볼륨 그룹이 아니라 풀에서만 생성됩니다.
* 씬 볼륨은 RAID 6이어야 합니다.
* EF600 또는 EF300 스토리지 시스템에서는 씬 볼륨을 사용할 수 없습니다.
* 씬 볼륨을 생성하려면 CLI를 사용해야 합니다.
* 일반 볼륨과 달리 씬 볼륨에 필요한 공간은 생성 중에 할당되지 않고 나중에 필요할 때 제공됩니다.
* 씬 볼륨을 사용하면 크기를 초과 할당할 수 있습니다. 즉, 볼륨 크기보다 큰 LUN 크기를 할당할 수 있습니다. 그런 다음 필요에 따라 LUN의 크기를 확장하지 않고(필요한 경우 프로세스에 드라이브 추가) 사용자를 분리하지 않고 볼륨을 확장할 수 있습니다.
* 씬 프로비저닝 블록 공간 재확보(UNMAP)를 사용하여 호스트에서 실행한 SCSI UNMAP 명령을 통해 스토리지 어레이에서 씬 프로비저닝된 볼륨의 블록을 재확보할 수 있습니다. 씬 프로비저닝을 지원하는 스토리지 어레이는 재확보된 공간을 재사용하여 동일한 스토리지 시스템 내에서 다른 씬 프로비저닝된 볼륨에 대한 할당 요청을 충족시킬 수 있으므로 디스크 공간 소비를 더욱 효율적으로 보고하고 리소스를 더욱 효율적으로 사용할 수 있습니다.


|===


== 씬 볼륨 제한 사항

씬 볼륨은 다음 경우를 제외하고 일반 볼륨으로 모든 작업을 지원합니다.

* 씬 볼륨의 세그먼트 크기는 변경할 수 없습니다.
* 씬 볼륨에 대한 사전 읽기 이중화 검사는 활성화할 수 없습니다.
* 볼륨 복사 작업에서는 씬 볼륨을 타겟 볼륨으로 사용할 수 없습니다.
* 씬 볼륨의 할당된 용량 한도 및 경고 임계값은 비동기 미러링된 쌍의 운영 측면에서만 변경할 수 있습니다. 기본 측에서 이러한 매개 변수를 변경하면 자동으로 보조 측으로 전파됩니다.

