---
permalink: sm-storage/convert-a-snapshot-volume-to-read-write-mode.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, convert, snapshot, volume, read-write mode 
summary: 필요한 경우 읽기 전용 스냅샷 볼륨 또는 스냅샷 정합성 보장 그룹 스냅샷 볼륨을 읽기-쓰기 모드로 변환할 수 있습니다. 
---
= 스냅샷 볼륨을 읽기-쓰기 모드로 변환합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
필요한 경우 읽기 전용 스냅샷 볼륨 또는 스냅샷 정합성 보장 그룹 스냅샷 볼륨을 읽기-쓰기 모드로 변환할 수 있습니다.

읽기-쓰기 액세스가 가능하도록 변환된 스냅샷 볼륨에는 고유한 예약 용량이 포함되어 있습니다. 이 용량은 참조된 스냅샷 이미지에 영향을 주지 않고 호스트 애플리케이션이 수정한 후속 사항을 기본 볼륨에 저장하는 데 사용됩니다.

.단계
. 스토리지 [스냅샷] 메뉴를 선택합니다.
. Snapshot Volumes * 탭을 선택합니다.
+
Snapshot Volumes 테이블이 나타나고 스토리지 어레이와 연결된 모든 스냅샷 볼륨이 표시됩니다.

. 변환할 읽기 전용 스냅샷 볼륨을 선택한 다음 * 읽기/쓰기로 변환 * 을 클릭합니다.
+
읽기/쓰기로 변환 대화 상자에 * 용량 예약 * 단계가 활성화된 상태로 나타납니다. 볼륨 후보 테이블에는 지정된 예약 용량을 지원하는 후보만 표시됩니다.

. 읽기-쓰기 스냅샷 볼륨에 예약된 용량을 할당하려면 다음 작업 중 하나를 수행합니다.
+
** * 기본 설정 수락 * -- 이 권장 옵션을 사용하여 스냅샷 볼륨에 예약된 용량을 기본 설정으로 할당합니다.
** * 데이터 스토리지 요구 사항에 맞게 예약된 용량 설정 할당 * -- 다음 지침에 따라 예약된 용량을 할당합니다.
+
*** 예약된 용량의 기본 설정은 기본 볼륨 용량의 40%이며 일반적으로 이 용량이면 충분합니다.
*** 필요한 용량은 볼륨에 대한 I/O 쓰기의 빈도 및 크기에 따라 달라집니다.




. 설정을 검토하거나 편집하려면 * 다음 * 을 선택하십시오.
+
설정 편집 대화 상자가 나타납니다.

. 스냅샷 볼륨에 대한 설정을 적절히 수락하거나 지정한 다음 * 마침 * 을 선택하여 스냅샷 볼륨을 변환합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
* 예약된 용량 설정 *



 a| 
다음 경우에 알림:
 a| 
spinner 상자를 사용하여 스냅샷 그룹의 예약된 용량이 거의 가득 찰 때 시스템에서 경고 알림을 보내는 백분율 지점을 조정합니다.

스냅샷 볼륨에 대한 예약된 용량이 지정된 임계값을 초과하면 예약된 용량을 늘리거나 불필요한 객체를 삭제할 수 있는 알림이 시스템에 전송됩니다.

|===
====

