---
permalink: sm-storage/copy-volume-function.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy, volume, 
summary: 볼륨 복사 기능을 사용하면 동일한 스토리지 배열에 소스 볼륨과 타겟 볼륨이라는 두 개의 개별 볼륨을 생성하여 볼륨의 시점 복제본을 생성할 수 있습니다. 
---
= 볼륨 복사 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 복사 기능을 사용하면 동일한 스토리지 배열에 소스 볼륨과 타겟 볼륨이라는 두 개의 개별 볼륨을 생성하여 볼륨의 시점 복제본을 생성할 수 있습니다.

이 기능은 소스 볼륨에서 타겟 볼륨으로 바이트 단위 복제를 수행하여 타겟 볼륨의 데이터를 소스 볼륨의 데이터와 동일하게 만듭니다.



== 데이터 복사로 액세스 향상

볼륨 변경에 대한 스토리지 요구 사항으로 볼륨 복사 기능을 사용하면 용량이 작은 드라이브를 사용하는 풀 또는 볼륨 그룹에서 용량이 큰 드라이브를 사용하는 풀 또는 볼륨 그룹으로 데이터를 복사할 수 있습니다. 예를 들어, 볼륨 복사 기능을 사용하여 다음을 수행할 수 있습니다.

* 데이터를 더 큰 드라이브로 이동:
* 데이터 전송 속도가 더 빠른 드라이브로 변경합니다.
* 새로운 기술을 사용하여 드라이브로 변경하여 성능을 높일 수 있습니다.
* 씬 볼륨을 일반 볼륨으로 변경합니다.


복제 소스 볼륨과 타겟 볼륨의 호스트 주소 지정 가능/논리적 블록 크기(섹터 크기)가 동일해야 합니다.

보고된 볼륨 블록 크기:

* * 기본 블록 크기 * – 볼륨의 블록 크기와 드라이브 블록 크기(512 또는 4K)가 일치합니다.
* * Emulated 512 블록 크기 * - 드라이브는 4K이지만 보고된 블록 크기는 512입니다.




== 씬 볼륨을 일반 볼륨으로 변경합니다

씬 볼륨을 일반 볼륨으로 변경하려면 볼륨 복사 작업을 사용하여 씬 볼륨의 복사본을 만듭니다. 볼륨 복사 작업의 대상은 항상 일반 볼륨입니다.

[NOTE]
====
System Manager에서는 씬 볼륨을 생성하는 옵션을 제공하지 않습니다. 씬 볼륨을 생성하려면 CLI(Command Line Interface)를 사용합니다.

====


== 데이터 백업

볼륨 복사 기능을 사용하면 동일한 스토리지 배열의 한 볼륨에서 다른 볼륨으로 데이터를 복사하여 볼륨을 백업할 수 있습니다. 타겟 볼륨을 소스 볼륨의 백업, 시스템 테스트 또는 테이프 드라이브와 같은 다른 디바이스에 백업할 수 있습니다.



== 스냅샷 볼륨 데이터를 기본 볼륨으로 복원합니다

연결된 스냅샷 볼륨에서 기본 볼륨으로 데이터를 복원해야 하는 경우 볼륨 복사 기능을 사용하여 스냅샷 볼륨에서 기본 볼륨으로 데이터를 복사할 수 있습니다. 스냅샷 볼륨에 데이터의 볼륨 복사본을 생성한 다음 데이터를 기본 볼륨으로 복사할 수 있습니다.



== 소스 및 타겟 볼륨

다음 표에는 Copy Volume(볼륨 복사) 기능을 사용하여 소스 및 타겟 볼륨에 사용할 수 있는 볼륨 유형이 나와 있습니다.

[cols="1a,1a,1a,1a"]
|===
| 볼륨 유형입니다 | 오프라인 볼륨 복사본 소스 볼륨 | 온라인 볼륨 복사본 소스 볼륨 | 온라인 및 오프라인 대상 볼륨 


 a| 
풀의 일반 볼륨입니다
 a| 
예
 a| 
예
 a| 
예



 a| 
볼륨 그룹의 일반 볼륨입니다
 a| 
예
 a| 
예
 a| 
예



 a| 
씬 볼륨
 a| 
예 ^1^
 a| 
예
 a| 
아니요



 a| 
스냅샷 볼륨
 a| 
예 ^2^
 a| 
아니요
 a| 
아니요



 a| 
Snapshot 기본 볼륨
 a| 
예
 a| 
예
 a| 
아니요



 a| 
원격 미러 운영 볼륨
 a| 
예 ^3^
 a| 
예
 a| 
아니요

|===
^1^ 타겟 볼륨의 용량이 씬 볼륨에서 보고된 용량과 같거나 커야 합니다.

^2^ 온라인 복사 작업이 완료될 때까지 스냅샷 볼륨 복사본을 사용할 수 없습니다.

^3^ 소스 볼륨이 기본 볼륨인 경우 타겟 볼륨의 용량은 소스 볼륨의 사용 가능한 용량과 같거나 커야 합니다.
