---
permalink: sm-storage/copy-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy volume 
summary: '동일한 스토리지 배열의 한 볼륨에서 다른 볼륨으로 데이터를 복사하고 소스 볼륨의 물리적 시점 중복(클론)을 생성할 수 있습니다.' 
---
= 볼륨 복사
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
동일한 스토리지 배열의 한 볼륨에서 다른 볼륨으로 데이터를 복사하고 소스 볼륨의 물리적 시점 중복(클론)을 생성할 수 있습니다.

.시작하기 전에
* 소스 볼륨과 타겟 볼륨에 대한 모든 입출력 작업을 중지해야 합니다.
* 소스 볼륨과 타겟 볼륨의 모든 파일 시스템은 마운트 해제해야 합니다.
* 이전에 볼륨 복사 작업에서 타겟 볼륨을 사용한 경우 해당 데이터가 더 이상 필요하지 않거나 데이터를 백업한 것입니다.


.이 작업에 대해
소스 볼륨은 호스트 입출력을 수락하고 애플리케이션 데이터를 저장하는 볼륨입니다. Copy Volume(볼륨 복사)이 시작되면 소스 볼륨의 데이터가 전체 대상 볼륨에 복사됩니다.

타겟 볼륨은 소스 볼륨의 데이터 복제본을 유지하는 표준 볼륨입니다. 볼륨 복사 작업이 완료된 후 타겟 볼륨이 소스 볼륨과 동일합니다. 타겟 볼륨의 용량이 소스 볼륨과 같거나 커야 하지만 RAID 레벨이 다를 수 있습니다.

.온라인 및 오프라인 복사본에 대한 자세한 정보
[%collapsible]
====
* 온라인 사본 *

온라인 복사본은 스토리지 어레이 내의 모든 볼륨에 대한 시점 복사본을 생성하지만, 복제가 진행 중인 볼륨에 쓸 수는 있습니다. 이 기능은 볼륨의 스냅샷을 생성하고 스냅샷을 복제본의 실제 소스 볼륨으로 사용하여 수행합니다. 시점 이미지가 생성되는 볼륨을 기본 볼륨이라고 하며 표준 볼륨이거나 스토리지 어레이의 씬 볼륨일 수 있습니다.

* 오프라인 복사 *

오프라인 복제는 소스 볼륨에서 데이터를 읽고 타겟 볼륨에 복사하는 한편, 진행 중인 복제본으로 소스 볼륨에 대한 모든 업데이트를 일시 중지시킵니다. 소스 볼륨에 대한 모든 업데이트가 일시 중지되어 타겟 볼륨에 시간 정합성이 보장되지 않는 항목이 생성되는 것을 방지합니다. 오프라인 볼륨 복사본 관계는 소스 볼륨과 타겟 볼륨 사이에 있습니다.

====
[NOTE]
====
볼륨 복사 작업은 타겟 볼륨의 데이터를 덮어쓰고 타겟 볼륨과 연결된 모든 스냅샷 볼륨에 실패합니다(있는 경우).

====
.단계
. Storage [Volumes](저장소 [볼륨]) 메뉴를 선택합니다.
. 볼륨 복사 작업의 소스로 사용할 볼륨을 선택한 다음 메뉴: 서비스 복사 [볼륨 복사] 를 선택합니다.
+
Copy Volume - Select Target(볼륨 복사 - 대상 선택) 대화 상자가 나타납니다.

. 데이터를 복사할 대상 볼륨을 선택합니다.
+
이 대화 상자에 표시된 표에는 모든 대상 볼륨이 나열됩니다.

. 볼륨 복사 작업의 복사 우선 순위를 설정하려면 슬라이더 막대를 사용합니다.
+
복제 우선 순위는 서비스 입출력 요청과 비교하여 볼륨 복사 작업을 완료하는 데 사용되는 시스템 리소스의 양을 결정합니다.

+
.복사 우선 순위 속도에 대해 자세히 알아보세요
[%collapsible]
====
복사 우선 순위 비율은 5가지입니다.

** 최저
** 낮음
** 중간
** 높음
** 최고


복사 우선 순위가 가장 낮은 속도로 설정된 경우 입출력 작업의 우선 순위가 지정되고 볼륨 복사 작업이 더 오래 걸립니다. 복사 우선 순위가 가장 높은 속도로 설정된 경우 볼륨 복사 작업의 우선 순위가 지정되지만 스토리지 배열의 입출력 작업에 영향을 줄 수 있습니다.

====
. 온라인 복사본을 만들지, 아니면 오프라인 복사본을 만들지 선택합니다. 온라인 복사본을 만들려면 복사 작업 중** 소스 볼륨을 온라인으로 유지 확인란을 선택합니다.
. 다음 중 하나를 수행합니다.
+
** online_copy 작업을 수행하려면 * 다음 * 을 클릭하여 * 용량 예약 * 대화 상자로 계속 진행합니다.
** offline_copy 작업을 수행하려면 * Finish * 를 클릭하여 오프라인 복사를 시작합니다.


. 온라인 복사본을 만들도록 선택한 경우 온라인 복사본에 대한 데이터 및 기타 정보를 저장하는 데 필요한 예약 용량을 설정한 다음 * 마침 * 을 클릭하여 온라인 복사본을 시작합니다.
+
지정된 예약 용량을 지원하는 후보만 볼륨 후보 테이블에 표시됩니다. 예약된 용량은 복제 서비스 작업 및 스토리지 객체에 사용되는 물리적 할당 용량입니다. 호스트에서 직접 읽을 수 없습니다.

+
다음 지침에 따라 예약된 용량을 할당합니다.

+
** 예약된 용량의 기본 설정은 기본 볼륨 용량의 40%이며 일반적으로 이 용량이면 충분합니다.
** 그러나 예약된 용량은 원래 데이터의 변경 횟수에 따라 달라집니다. 스토리지 객체가 활성 상태가 길수록 예약된 용량이 커야 합니다.




.결과
System Manager는 소스 볼륨의 모든 데이터를 타겟 볼륨으로 복사합니다. 볼륨 복사 작업이 완료되면 타겟 볼륨은 호스트에 대해 자동으로 읽기 전용이 됩니다.

.작업을 마친 후
Copy Volume(볼륨 복사) 작업의 진행률을 보려면 Home(홈) [View Operations in Progress(진행 중인 작업 보기)] 메뉴를 선택합니다. 이 작업은 시간이 오래 걸릴 수 있으며 시스템 성능에 영향을 줄 수 있습니다.
