---
permalink: sm-storage/create-snapshot-image.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, snapshot, image 
summary: 기본 볼륨 또는 스냅샷 정합성 보장 그룹에서 스냅샷 이미지를 수동으로 생성할 수 있습니다. 이를 인스턴트 스냅샷 또는 인스턴트 이미지라고도 합니다. 
---
= 스냅샷 이미지를 생성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본 볼륨 또는 스냅샷 정합성 보장 그룹에서 스냅샷 이미지를 수동으로 생성할 수 있습니다. 이를 _instant snapshot_or_instant image_라고도 합니다.

.시작하기 전에
* 기본 볼륨이 최적화되어야 합니다.
* 드라이브가 최적이어야 합니다.
* 스냅샷 그룹은 "재제공"으로 지정할 수 없습니다.
* 예약된 용량 볼륨의 경우 스냅샷 그룹에 대해 연결된 기본 볼륨과 동일한 DA(Data Assurance) 설정을 사용해야 합니다.


.단계
. 다음 작업 중 하나를 수행하여 스냅샷 이미지를 생성합니다.
+
** Storage [Volumes](저장소 [볼륨]) 메뉴를 선택합니다. 개체(기본 볼륨 또는 스냅샷 정합성 보장 그룹)를 선택한 다음 메뉴, 복제 서비스 [인스턴트 스냅샷 생성]을 선택합니다.
** 스토리지 [스냅샷] 메뉴를 선택합니다. 스냅샷 이미지 * 탭을 선택한 다음 메뉴 생성 [즉시 스냅샷] 을 선택합니다.
+
스냅샷 이미지 생성 대화 상자가 나타납니다. 객체(기본 볼륨 또는 스냅샷 정합성 보장 그룹)를 선택하고 * Next * 를 클릭합니다. 볼륨 또는 스냅샷 정합성 보장 그룹에 대해 이전 스냅샷 이미지가 생성된 경우 시스템에서 즉시 인스턴트 스냅샷을 생성합니다. 그렇지 않으면 볼륨 또는 스냅샷 정합성 보장 그룹에 대해 스냅샷 이미지를 처음 생성하는 경우 스냅샷 이미지 생성 확인 대화 상자가 나타납니다.



. 예약된 용량이 필요하다는 알림을 수락하고 Reserve Capacity 단계로 진행하려면 * Create * 를 클릭합니다.
+
용량 예약 대화 상자가 나타납니다.

. 스피너 상자를 사용하여 용량 비율을 조정한 후 * 다음 * 을 클릭하여 표에 강조 표시된 대상 볼륨을 적용합니다.
+
설정 편집 대화 상자가 나타납니다.

. 스냅샷 이미지에 대한 설정을 적절하게 선택하고 작업을 수행할지 확인합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
* 스냅샷 이미지 설정 *



 a| 
스냅샷 이미지 제한
 a| 
스냅샷 이미지를 지정된 제한 이후 자동으로 삭제하려면 확인란을 선택하고, 제한을 변경하려면 스피너 상자를 사용합니다. 이 확인란의 선택을 취소하면 32개 이미지 후에 스냅샷 이미지 생성이 중지됩니다.



 a| 
* 예약된 용량 설정 *



 a| 
다음 경우에 알림:
 a| 
spinner 상자를 사용하여 스냅샷 그룹의 예약된 용량이 거의 가득 찰 때 시스템에서 경고 알림을 보내는 백분율 지점을 조정합니다.

스냅샷 그룹의 예약된 용량이 지정된 임계값을 초과하는 경우 사전 알림을 사용하여 예약된 용량을 늘리거나 남은 공간이 부족해지기 전에 불필요한 객체를 삭제하십시오.



 a| 
전체 예약 용량에 대한 정책입니다
 a| 
다음 정책 중 하나를 선택합니다.

** * Purge Oldest snapshot image * -- 시스템이 스냅샷 그룹에서 가장 오래된 스냅샷 이미지를 자동으로 제거합니다. 그러면 그룹 내에서 재사용하기 위해 스냅샷 이미지 예약 용량이 해제됩니다.
** * 기본 볼륨에 대한 쓰기 거부 * -- 예약된 용량이 최대 정의 비율에 도달하면 시스템은 예약된 용량 액세스를 트리거한 기본 볼륨에 대한 모든 I/O 쓰기 요청을 거부합니다.


|===
====


.결과
* System Manager는 스냅샷 이미지 테이블에 새 스냅샷 이미지를 표시합니다. 이 표에는 타임 스탬프와 관련 기본 볼륨 또는 스냅샷 정합성 보장 그룹을 기준으로 새 이미지가 나열됩니다.
* 다음 조건 때문에 스냅샷 생성이 보류 상태로 유지될 수 있습니다.
+
** 이 스냅샷 이미지가 포함된 기본 볼륨은 비동기식 미러 그룹의 구성원입니다.
** 기본 볼륨이 현재 동기화 작업 중입니다. 동기화 작업이 완료되는 즉시 스냅샷 이미지 생성이 완료됩니다.



