---
permalink: sm-storage/create-workloads.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, workloads 
summary: 모든 유형의 애플리케이션에 대한 워크로드를 생성할 수 있습니다. 
---
= 워크로드 생성
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 유형의 애플리케이션에 대한 워크로드를 생성할 수 있습니다.

워크로드는 애플리케이션을 지원하는 스토리지 객체입니다. 애플리케이션별로 하나 이상의 워크로드 또는 인스턴스를 정의할 수 있습니다. 일부 애플리케이션의 경우 시스템에서 기본 볼륨 특성이 비슷한 볼륨을 포함하도록 워크로드를 구성합니다. 이러한 볼륨 특성은 워크로드가 지원하는 애플리케이션 유형에 따라 최적화됩니다. 예를 들어, Microsoft SQL Server 애플리케이션을 지원하는 워크로드를 생성한 다음 해당 워크로드에 대한 볼륨을 생성하는 경우 기본 볼륨 특성은 Microsoft SQL Server를 지원하도록 최적화되어 있습니다.

System Manager에서는 다음 애플리케이션 유형에 대해서만 최적화된 볼륨 구성을 권장합니다.

* Microsoft ® SQL Server ™ 를 참조하십시오
* Microsoft ® Exchange Server ™ 를 참조하십시오
* 비디오 감시
* VMware ESXi ™ (가상 머신 파일 시스템과 함께 사용할 볼륨용)


다음 지침을 염두에 두십시오.

* _애플리케이션별 워크로드를 사용하는 경우, 시스템은 애플리케이션 워크로드 I/O와 애플리케이션 인스턴스의 기타 트래픽 간의 경합을 최소화하기 위해 최적화된 볼륨 구성을 권장합니다. 볼륨 추가/편집 대화 상자를 사용하여 권장 볼륨 구성을 검토한 다음 시스템 권장 볼륨 및 특성을 편집, 추가 또는 삭제할 수 있습니다.
* _ 다른 애플리케이션 유형을 사용할 때 볼륨 추가/편집 대화 상자를 사용하여 수동으로 볼륨 구성을 지정합니다.


.단계
. Storage [Volumes](저장소 [볼륨]) 메뉴를 선택합니다.
. 메뉴: Create [Workload](워크로드 생성)를 선택합니다.
+
애플리케이션 워크로드 생성 대화 상자가 나타납니다.

. 드롭다운 목록을 사용하여 워크로드를 생성할 애플리케이션 유형을 선택한 다음 워크로드 이름을 입력합니다.
. Create * 를 클릭합니다.


생성한 워크로드에 스토리지 용량을 추가할 준비가 되었습니다. 볼륨 생성 * 옵션을 사용하여 응용 프로그램에 대해 하나 이상의 볼륨을 생성하고 각 볼륨에 특정 양의 용량을 할당할 수 있습니다.
