---
permalink: sm-storage/create-snapshot-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, snapshot, consistency group 
summary: 정합성이 보장된 복제본을 유지하려면 스냅샷 정합성 보장 그룹이라는 여러 볼륨 세트를 생성할 수 있습니다. 
---
= 스냅샷 정합성 보장 그룹을 생성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
정합성이 보장된 복제본을 유지하려면 _ 스냅샷 정합성 보장 그룹 _ 이라는 여러 볼륨 세트를 생성할 수 있습니다.

이 그룹을 사용하면 일관성을 위해 모든 볼륨의 스냅샷 이미지를 동시에 만들 수 있습니다. 스냅샷 정합성 보장 그룹에 속한 각 볼륨을 _member volume_이라고 합니다. 스냅샷 정합성 보장 그룹에 볼륨을 추가하면 시스템에서 이 구성원 볼륨에 해당하는 새 스냅샷 그룹을 자동으로 생성합니다.

스냅샷 정합성 보장 그룹 생성 시퀀스를 사용하여 그룹의 구성원 볼륨을 선택하고 구성원 볼륨에 용량을 할당할 수 있습니다.

스냅샷 정합성 보장 그룹을 생성하는 프로세스는 여러 단계로 이루어집니다.



== 1단계: 스냅샷 정합성 보장 그룹에 구성원 추가

구성원을 선택하여 스냅샷 정합성 보장 그룹을 구성하는 볼륨의 컬렉션을 지정합니다. 스냅샷 정합성 보장 그룹에서 수행하는 모든 작업은 선택한 구성원 볼륨으로 균일하게 확장됩니다.

구성원 볼륨이 최적화되어야 합니다.

.단계
. 스토리지 [스냅샷] 메뉴를 선택합니다.
. 스냅샷 정합성 보장 그룹 * 탭을 클릭합니다.
. [스냅샷 일관성 그룹] 생성 메뉴를 선택합니다.
+
스냅샷 정합성 보장 그룹 생성 대화 상자가 나타납니다.

. 구성원 볼륨으로 추가할 볼륨을 스냅샷 정합성 보장 그룹에 선택합니다.
. 다음 * 을 클릭하고 으로 이동합니다  2: Reserve capacity for snapshot consistency group.




== 2단계: 스냅샷 정합성 보장 그룹의 용량 예약

예약된 용량을 스냅샷 정합성 보장 그룹에 연결합니다. System Manager에서는 스냅샷 정합성 보장 그룹의 속성을 기준으로 볼륨 및 용량을 제안합니다. 권장 예약 용량 구성을 수락하거나 할당된 스토리지를 사용자 지정할 수 있습니다.

용량 예약 대화 상자의 볼륨 대상 테이블에는 지정된 예약 용량을 지원하는 후보만 표시됩니다. 예약된 용량은 복제 서비스 작업 및 스토리지 객체에 사용되는 물리적 할당 용량입니다. 호스트에서 직접 읽을 수 없습니다.

.단계
. 스피너 상자를 사용하여 스냅샷 정합성 보장 그룹에 예약된 용량을 할당합니다. 다음 작업 중 하나를 수행합니다.
+
** * 기본 설정을 적용합니다 *.
+
이 권장 옵션을 사용하여 각 구성원 볼륨에 예약된 용량을 기본 설정으로 할당합니다.

** * 데이터 스토리지 요구 사항에 맞게 예약된 용량 설정을 할당합니다. *
+
다음 지침에 따라 예약된 용량을 할당합니다.

+
*** 예약된 용량의 기본 설정은 기본 볼륨 용량의 40%입니다. 일반적으로 이 용량이면 충분합니다.
*** 필요한 용량은 볼륨에 대한 입출력 쓰기 빈도 및 크기와 스냅샷 이미지 컬렉션의 양과 기간에 따라 달라집니다.




. * 선택 사항: * 기본 예약된 용량 설정을 변경하는 경우 * 후보 새로 고침 * 을 클릭하여 지정한 예약된 용량에 대한 후보 목록을 새로 고칩니다.
. 다음 * 을 클릭하고 으로 이동합니다  3: Edit settings for snapshot consistency group.




== 3단계: 스냅샷 정합성 보장 그룹에 대한 설정을 편집합니다

스냅샷 정합성 보장 그룹에 대한 자동 삭제 설정 및 예약된 용량 알림 임계값을 적용하거나 선택합니다.

스냅샷 정합성 보장 그룹 생성 시퀀스를 사용하여 그룹의 구성원 볼륨을 선택하고 구성원 볼륨에 용량을 할당할 수 있습니다.

.단계
. 필요에 따라 스냅샷 정합성 보장 그룹의 기본 설정을 적용하거나 변경합니다.
+
.필드 상세정보
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
* 스냅샷 정합성 보장 그룹 설정 *



 a| 
이름
 a| 
스냅샷 정합성 보장 그룹의 이름을 지정합니다.



 a| 
다음과 같은 경우 스냅샷 이미지 자동 삭제 활성화
 a| 
스냅샷 이미지를 지정된 제한 이후 자동으로 삭제하려면 확인란을 선택하고, 제한을 변경하려면 스피너 상자를 사용합니다. 이 확인란의 선택을 취소하면 32개 이미지 후에 스냅샷 이미지 생성이 중지됩니다.



 a| 
* 예약된 용량 설정 *



 a| 
다음 경우에 알림:
 a| 
spinner 상자를 사용하여 스냅샷 정합성 보장 그룹의 예약된 용량이 거의 꽉 찼을 때 시스템에서 경고 알림을 보내는 백분율 지점을 조정합니다.

스냅샷 정합성 보장 그룹에 예약된 용량이 지정된 임계값을 초과할 경우 사전 알림을 사용하여 예약된 용량을 늘리거나 남은 공간이 부족해지기 전에 불필요한 객체를 삭제하십시오.



 a| 
전체 예약 용량에 대한 정책입니다
 a| 
다음 정책 중 하나를 선택합니다.

** * Purge Oldest snapshot image * -- 시스템이 스냅샷 정합성 보장 그룹에서 가장 오래된 스냅샷 이미지를 자동으로 제거합니다. 이 경우 그룹 내에서 재사용할 수 있도록 스냅샷 이미지 예약 용량이 해제됩니다.
** * 기본 볼륨에 대한 쓰기 거부 * -- 예약된 용량이 최대 정의 비율에 도달하면 시스템은 예약된 용량 액세스를 트리거한 기본 볼륨에 대한 모든 I/O 쓰기 요청을 거부합니다.


|===
====
. 스냅샷 정합성 보장 그룹 구성이 만족스러우면 * 마침 * 을 클릭합니다.

