---
permalink: sm-storage/create-volume-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, volume, group 
summary: 볼륨 그룹을 사용하여 호스트에서 액세스할 수 있는 볼륨을 하나 이상 생성할 수 있습니다. 볼륨 그룹은 RAID 레벨 및 용량과 같은 공유 특성을 가진 볼륨의 컨테이너입니다. 
---
= 볼륨 그룹을 생성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 그룹을 사용하여 호스트에서 액세스할 수 있는 볼륨을 하나 이상 생성할 수 있습니다. 볼륨 그룹은 RAID 레벨 및 용량과 같은 공유 특성을 가진 볼륨의 컨테이너입니다.

대용량 드라이브를 사용하고 여러 컨트롤러에 볼륨을 분산할 수 있으므로 볼륨 그룹당 둘 이상의 볼륨을 생성하는 것이 스토리지 용량을 사용하고 데이터를 보호하는 좋은 방법입니다.

.시작하기 전에
볼륨 그룹을 생성하기 전에 다음 지침을 검토하십시오.

* 할당되지 않은 드라이브가 하나 이상 필요합니다.
* 단일 볼륨 그룹에 포함할 수 있는 드라이브 수에 제한이 있습니다. 이러한 제한은 RAID 레벨에 따라 다릅니다.
* 쉘프/서랍 손실 보호를 활성화하려면 최소 3개의 쉘프 또는 서랍에 있는 드라이브를 사용하는 볼륨 그룹을 생성해야 합니다. 단, RAID 1을 사용하는 경우는 예외입니다. 여기서 두 개의 쉘프/서랍이 최소값이 됩니다.
* EF600 또는 EF300 스토리지 어레이를 사용하는 경우 볼륨 그룹을 수동으로 생성하려면 각 컨트롤러가 처음 12개 슬롯에서 동일한 수의 드라이브에 액세스하고 마지막 12개 슬롯에서 동일한 수의 드라이브에 액세스해야 합니다. 이 구성을 사용하면 컨트롤러가 드라이브 측 PCIe 버스를 보다 효과적으로 사용할 수 있습니다. 현재 System Manager에서는 볼륨 그룹을 생성할 때 고급 기능 아래에서 드라이브를 선택할 수 있습니다.
* 선택한 RAID 레벨이 볼륨 그룹의 결과 용량에 미치는 영향을 검토합니다.
+
** RAID 1을 선택한 경우 미러링된 쌍이 선택되었는지 확인하기 위해 한 번에 두 개의 드라이브를 추가해야 합니다. 4개 이상의 드라이브를 선택하면 미러링 및 스트라이핑(RAID 10 또는 RAID 1+0이라고 함)이 수행됩니다.
** RAID 5를 선택한 경우 최소 3개의 드라이브를 추가하여 볼륨 그룹을 만들어야 합니다.
** RAID 6을 선택한 경우 최소 5개의 드라이브를 추가하여 볼륨 그룹을 생성해야 합니다.




.단계
. 스토리지 [풀 및 볼륨 그룹] 메뉴를 선택합니다.
. 메뉴 [Volume group](볼륨 그룹)을 클릭합니다.
+
Create Volume Group 대화상자가 나타납니다.

. 볼륨 그룹의 이름을 입력합니다.
. 데이터 스토리지 및 보호 요구사항에 가장 적합한 RAID 레벨을 선택합니다.
+
볼륨 그룹 후보 테이블이 나타나고 선택한 RAID 레벨을 지원하는 후보만 표시됩니다.

. * 선택 사항: * 스토리지 배열에 둘 이상의 드라이브 유형이 있는 경우 사용할 드라이브 유형을 선택합니다.
+
볼륨 그룹 후보 테이블이 나타나고 선택한 드라이브 유형과 RAID 레벨을 지원하는 후보만 표시됩니다.

. * 선택 사항: * 자동 방법이나 수동 방법을 선택하여 볼륨 그룹에서 사용할 드라이브를 정의할 수 있습니다. 자동 방법이 기본 선택 항목입니다.
+
드라이브를 수동으로 선택하려면 * Manually select drives (advanced) * 링크를 클릭합니다. 클릭하면 자동으로 드라이브 선택(고급) * 으로 변경됩니다.

+
Manual(수동) 방법을 사용하면 볼륨 그룹을 구성하는 특정 드라이브를 선택할 수 있습니다. 할당되지 않은 특정 드라이브를 선택하여 필요한 용량을 확보할 수 있습니다. 스토리지 배열에 다른 미디어 유형 또는 다른 인터페이스 유형의 드라이브가 포함된 경우, 단일 드라이브 유형에 대해 구성되지 않은 용량만 선택하여 새 볼륨 그룹을 생성할 수 있습니다.

+
[NOTE]
====
드라이브 중복성과 최적의 드라이브 구성을 이해하는 전문가만 수동 방법을 사용해야 합니다.

====
. 표시된 드라이브 특성에 따라 볼륨 그룹에서 사용할 드라이브를 선택한 다음 * Create * 를 클릭합니다.
+
표시되는 드라이브 특성은 자동 방법 또는 수동 방법을 선택했는지 여부에 따라 달라집니다.

+
.자동 메서드 드라이브 특성
[%collapsible]
====
[cols="25h,~"]
|===
| 특징 | 사용 


 a| 
사용 가능한 용량
 a| 
에는 사용 가능한 용량이 GiB 단위로 표시됩니다. 애플리케이션의 스토리지 요구사항에 필요한 용량을 갖춘 볼륨 그룹 후보를 선택합니다.



 a| 
총 드라이브 수
 a| 
이 볼륨 그룹에 사용할 수 있는 드라이브 수를 표시합니다. 원하는 드라이브 수가 있는 볼륨 그룹 대상을 선택합니다.



 a| 
드라이브 블록 크기(EF300 및 EF600만 해당)
 a| 
그룹의 드라이브가 쓸 수 있는 블록 크기(섹터 크기)를 표시합니다. 다음과 같은 값이 포함될 수 있습니다.

** 512--512바이트 섹터 크기
** 4k--4,096바이트 섹터 크기




 a| 
보안 가능
 a| 
이 볼륨 그룹 대상이 전체 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있는 전체 보안 가능 드라이브로 구성되어 있는지 여부를 나타냅니다.

** 드라이브 보안으로 볼륨 그룹을 보호할 수 있지만 이 기능을 사용하려면 모든 드라이브가 안전해야 합니다.
** FDE 전용 볼륨 그룹을 생성하려면 Secure-Capable 열에서 * Yes-FDE * 를 찾습니다. FIPS 전용 볼륨 그룹을 생성하려면 * Yes-FIPS * 또는 * Yes-FIPS(Mixed) * 를 찾습니다. "혼합"은 140-3단계 드라이브와 140-3단계 드라이브의 혼합을 나타냅니다. 이러한 수준을 혼합하여 사용하는 경우 볼륨 그룹이 낮은 보안 수준(140-2)에서 작동합니다.
** 보안이 가능하거나 보안이 가능하지 않거나 보안 수준이 혼합된 드라이브로 구성된 볼륨 그룹을 생성할 수 있습니다. 볼륨 그룹의 드라이브에 보안 기능이 지원되지 않는 드라이브가 포함되어 있으면 볼륨 그룹을 안전하게 만들 수 없습니다.




 a| 
보안을 활성화하시겠습니까?
 a| 
에서는 보안 가능 드라이브를 사용하여 드라이브 보안 기능을 활성화하는 옵션을 제공합니다. 볼륨 그룹이 보안 기능이 있고 보안 키를 설정한 경우 확인란을 선택하여 드라이브 보안을 활성화할 수 있습니다.


NOTE: 활성화된 후 Drive Security를 제거하는 유일한 방법은 볼륨 그룹을 삭제하고 드라이브를 지우는 것입니다.



 a| 
DA 가능
 a| 
이 그룹에 대해 DA(Data Assurance)를 사용할 수 있는지 여부를 나타냅니다. DA(Data Assurance)는 컨트롤러를 통해 드라이브로 데이터가 전송될 때 발생할 수 있는 오류를 확인하고 수정합니다.

DA를 사용하려면 DA를 지원하는 볼륨 그룹을 선택합니다. (DA 지원 드라이브의 경우 풀에 생성된 볼륨에서 DA가 자동으로 활성화됩니다.)

볼륨 그룹에는 DA를 사용할 수 있거나 DA를 사용할 수 없는 드라이브가 포함될 수 있지만 모든 드라이브는 DA를 통해 이 기능을 사용할 수 있어야 합니다.



 a| 
리소스 프로비저닝 가능(EF300 및 EF600만 해당)
 a| 
이 그룹에 대해 리소스 프로비저닝을 사용할 수 있는지 여부를 표시합니다. 리소스 프로비저닝은 EF300 및 EF600 스토리지 어레이에서 사용 가능한 기능으로, 백그라운드 초기화 프로세스 없이 볼륨을 즉시 사용할 수 있도록 지원합니다.



 a| 
선반 손실 방지
 a| 
쉘프 손실 방지 기능이 사용 가능한지 여부를 표시합니다. 쉘프 손실 보호는 쉘프에 대한 통신이 완전히 손실되는 경우 볼륨 그룹의 볼륨에 있는 데이터에 액세스할 수 있도록 보장합니다.



 a| 
서랍 손실 방지
 a| 
드로어 손실 보호가 사용 가능한지 여부를 표시합니다. 이 보호 기능은 드로어가 포함된 드라이브 쉘프를 사용하는 경우에만 제공됩니다. 드로어 손실 방지 기능은 드라이브 쉘프의 단일 드로어에서 전체 통신 장애가 발생할 경우 볼륨 그룹의 볼륨에 있는 데이터에 액세스할 수 있도록 보장합니다.



 a| 
지원되는 볼륨 블록 크기(EF300 및 EF600만 해당)
 a| 
에는 그룹의 볼륨에 대해 생성할 수 있는 블록 크기가 나와 있습니다.

** 512n -- 512바이트 네이티브
** 512e -- 512바이트가 에뮬레이트됨
** 4k--4,096바이트.


|===
====
+
.수동 방식 드라이브 특성
[%collapsible]
====
[cols="25h,~"]
|===
| 특징 | 사용 


 a| 
미디어 유형
 a| 
용지 종류를 나타냅니다. 지원되는 용지 종류는 다음과 같습니다.

** 하드 드라이브
** 솔리드 스테이트 디스크(SSD)


볼륨 그룹의 모든 드라이브는 동일한 미디어 유형(모든 SSD 또는 모든 하드 드라이브)이어야 합니다. 볼륨 그룹은 미디어 유형 또는 인터페이스 유형을 혼합하여 사용할 수 없습니다.



 a| 
드라이브 블록 크기(EF300 및 EF600만 해당)
 a| 
그룹의 드라이브가 쓸 수 있는 블록 크기(섹터 크기)를 표시합니다. 다음과 같은 값이 포함될 수 있습니다.

** 512--512바이트 섹터 크기
** 4k--4,096바이트 섹터 크기




 a| 
드라이브 용량
 a| 
드라이브 용량을 나타냅니다.

** 가능하면 볼륨 그룹의 현재 드라이브 용량과 동일한 용량을 가진 드라이브를 선택합니다.
** 용량이 더 작은 할당되지 않은 드라이브를 추가해야 하는 경우, 볼륨 그룹에 현재 있는 각 드라이브의 가용 용량이 줄어듭니다. 따라서 드라이브 용량은 볼륨 그룹 전체에서 동일합니다.
** 용량이 더 큰 할당되지 않은 드라이브를 추가해야 하는 경우, 추가하는 할당되지 않은 드라이브의 가용 용량이 볼륨 그룹의 현재 드라이브 용량과 일치하도록 감소한다는 점을 유념하십시오.




 a| 
용지함
 a| 
드라이브의 트레이 위치를 나타냅니다.



 a| 
슬롯
 a| 
드라이브의 슬롯 위치를 나타냅니다.



 a| 
속도(rpm)
 a| 
드라이브의 속도를 나타냅니다.



 a| 
논리 섹터 크기
 a| 
섹터 크기 및 형식을 나타냅니다.



 a| 
보안 가능
 a| 
이 볼륨 그룹 대상이 전체 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있는 전체 보안 가능 드라이브로 구성되어 있는지 여부를 나타냅니다.

** 드라이브 보안으로 볼륨 그룹을 보호할 수 있지만 이 기능을 사용하려면 모든 드라이브가 안전해야 합니다.
** FDE 전용 볼륨 그룹을 생성하려면 Secure-Capable 열에서 * Yes-FDE * 를 찾습니다. FIPS 전용 볼륨 그룹을 생성하려면 * Yes-FIPS * 또는 * Yes-FIPS(Mixed) * 를 찾습니다. "혼합"은 140-3단계 드라이브와 140-3단계 드라이브의 혼합을 나타냅니다. 이러한 수준을 혼합하여 사용하는 경우 볼륨 그룹이 낮은 보안 수준(140-2)에서 작동합니다.
** 보안이 가능하거나 보안이 가능하지 않거나 보안 수준이 혼합된 드라이브로 구성된 볼륨 그룹을 생성할 수 있습니다. 볼륨 그룹의 드라이브에 보안 기능이 지원되지 않는 드라이브가 포함되어 있으면 볼륨 그룹을 안전하게 만들 수 없습니다.




 a| 
DA 가능
 a| 
이 그룹에 대해 DA(Data Assurance)를 사용할 수 있는지 여부를 나타냅니다. DA(Data Assurance)는 컨트롤러를 통해 드라이브로 데이터가 전달될 때 발생할 수 있는 오류를 확인하고 수정합니다.

DA를 사용하려면 DA를 지원하는 볼륨 그룹을 선택합니다. (DA 지원 드라이브의 경우 풀에 생성된 볼륨에서 DA가 자동으로 활성화됩니다.)

볼륨 그룹에는 DA를 사용할 수 있거나 DA를 사용할 수 없는 드라이브가 포함될 수 있지만 모든 드라이브는 DA를 통해 이 기능을 사용할 수 있어야 합니다.



 a| 
지원되는 볼륨 블록 크기(EF300 및 EF600만 해당)
 a| 
에는 그룹의 볼륨에 대해 생성할 수 있는 블록 크기가 나와 있습니다.

** 512n -- 512바이트 네이티브
** 512e -- 512바이트가 에뮬레이트됨
** 4k--4,096바이트.




 a| 
리소스 프로비저닝 가능(EF300 및 EF600만 해당)
 a| 
이 그룹에 대해 리소스 프로비저닝을 사용할 수 있는지 여부를 표시합니다. 리소스 프로비저닝은 EF300 및 EF600 스토리지 어레이에서 사용 가능한 기능으로, 백그라운드 초기화 프로세스 없이 볼륨을 즉시 사용할 수 있도록 지원합니다.

|===
====

