---
permalink: sm-storage/create-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, volumes 
summary: 볼륨을 생성하여 애플리케이션별 워크로드에 스토리지 용량을 추가하고 생성된 볼륨을 특정 호스트 또는 호스트 클러스터에 표시할 수 있습니다. 또한 볼륨 생성 시퀀스에서는 생성하려는 각 볼륨에 특정 용량을 할당하는 옵션을 제공합니다. 
---
= 볼륨 생성
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨을 생성하여 애플리케이션별 워크로드에 스토리지 용량을 추가하고 생성된 볼륨을 특정 호스트 또는 호스트 클러스터에 표시할 수 있습니다. 또한 볼륨 생성 시퀀스에서는 생성하려는 각 볼륨에 특정 용량을 할당하는 옵션을 제공합니다.

.이 작업에 대해
대부분의 애플리케이션 유형은 사용자 정의 볼륨 구성으로 기본 설정됩니다. 일부 애플리케이션 유형에서는 볼륨 생성 시 스마트 구성이 적용됩니다. 예를 들어 Microsoft Exchange 애플리케이션용 볼륨을 만드는 경우 필요한 메일박스 수, 평균 메일박스 용량 요구 사항, 원하는 데이터베이스 복제본 수를 묻는 메시지가 표시됩니다. System Manager는 이 정보를 사용하여 최적의 볼륨 구성을 생성하므로 필요에 따라 편집할 수 있습니다.

볼륨을 생성하는 프로세스는 여러 단계로 이루어집니다.



== 1단계: 볼륨의 호스트를 선택합니다

볼륨을 생성하여 애플리케이션별 워크로드에 스토리지 용량을 추가하고 생성된 볼륨을 특정 호스트 또는 호스트 클러스터에 표시할 수 있습니다. 또한 볼륨 생성 시퀀스에서는 생성하려는 각 볼륨에 특정 용량을 할당하는 옵션을 제공합니다.

.시작하기 전에
* 호스트 타일 아래에 유효한 호스트 또는 호스트 클러스터가 있습니다.
* 호스트에 대한 호스트 포트 식별자가 정의되었습니다.
* DA 지원 볼륨을 생성하기 전에 사용하려는 호스트 연결이 DA를 지원해야 합니다. 스토리지 시스템의 컨트롤러에 있는 호스트 접속 중 하나라도 DA를 지원하지 않으면 연결된 호스트가 DA 지원 볼륨의 데이터에 액세스할 수 없습니다.


.이 작업에 대해
볼륨을 할당할 때 다음 지침을 염두에 두십시오.

* 호스트의 운영 체제에는 호스트가 액세스할 수 있는 볼륨 수에 대한 특정 제한이 있을 수 있습니다. 특정 호스트에서 사용할 볼륨을 생성할 때 이 제한 사항을 염두에 두십시오.
* 스토리지 배열의 각 볼륨에 대해 하나의 할당을 정의할 수 있습니다.
* 할당된 볼륨은 스토리지 배열의 컨트롤러 간에 공유됩니다.
* 동일한 LUN(Logical Unit Number)을 호스트 또는 호스트 클러스터에서 볼륨에 액세스하는 데 두 번 사용할 수 없습니다. 고유한 LUN을 사용해야 합니다.
* 볼륨 생성 프로세스의 속도를 높이려면 새로 생성된 볼륨이 오프라인으로 초기화되도록 호스트 할당 단계를 건너뛸 수 있습니다.


[NOTE]
====
호스트 클러스터의 호스트에 대해 설정된 할당과 충돌하는 호스트 클러스터에 볼륨을 할당하려고 하면 호스트에 볼륨을 할당할 수 없습니다.

====
.단계
. Storage [Volumes](저장소 [볼륨]) 메뉴를 선택합니다.
. 메뉴 선택: Create [Volume](체적 생성)
+
Create Volumes 대화상자가 나타납니다.

. 드롭다운 목록에서 볼륨을 할당할 특정 호스트 또는 호스트 클러스터를 선택하거나 나중에 호스트 또는 호스트 클러스터를 할당하도록 선택합니다.
. 선택한 호스트 또는 호스트 클러스터에 대한 볼륨 생성 순서를 계속하려면 * 다음 * 을 클릭하고 로 이동합니다 <<2단계: 볼륨에 대한 워크로드를 선택합니다>>.
+
워크로드 선택 대화 상자가 나타납니다.





== 2단계: 볼륨에 대한 워크로드를 선택합니다

Microsoft SQL Server, Microsoft Exchange, Video Surveillance 애플리케이션 또는 VMware와 같은 특정 애플리케이션에 맞게 스토리지 어레이 구성을 사용자 지정할 워크로드를 선택합니다. 이 스토리지 배열에서 사용하려는 애플리케이션이 목록에 없으면 "기타 애플리케이션"을 선택할 수 있습니다.

.이 작업에 대해
이 작업에서는 기존 워크로드에 대한 볼륨을 생성하는 방법에 대해 설명합니다.

* _애플리케이션별 워크로드를 사용하여 볼륨을 생성하는 경우, 시스템은 애플리케이션 워크로드 I/O와 애플리케이션 인스턴스의 기타 트래픽 간의 경합을 최소화하기 위해 최적화된 볼륨 구성을 권장할 수 있습니다. 볼륨 추가/편집 대화 상자를 사용하여 권장 볼륨 구성을 검토하고 시스템 권장 볼륨 및 특성을 편집, 추가 또는 삭제할 수 있습니다.
* _ "기타"_응용 프로그램(또는 특정 볼륨 생성이 지원되지 않는 응용 프로그램)을 사용하여 볼륨을 생성하는 경우 볼륨 추가/편집 대화 상자를 사용하여 볼륨 구성을 수동으로 지정합니다.


.단계
. 다음 중 하나를 수행합니다.
+
** 기존 워크로드에 대한 볼륨을 생성하려면 * 기존 워크로드에 대한 볼륨 생성 * 옵션을 선택합니다.
** 지원되는 애플리케이션 또는 "기타" 애플리케이션의 새 워크로드를 정의하려면 * 새 워크로드 생성 * 옵션을 선택합니다.
+
*** 드롭다운 목록에서 새 워크로드를 생성할 애플리케이션의 이름을 선택합니다.
+
이 스토리지 배열에서 사용하려는 애플리케이션이 목록에 없는 경우 "기타" 항목 중 하나를 선택합니다.

*** 생성할 워크로드의 이름을 입력합니다.




. 다음 * 을 클릭합니다.
. 워크로드가 지원되는 애플리케이션 유형과 연결되어 있는 경우 요청된 정보를 입력하고, 그렇지 않으면 로 이동합니다 <<3단계: 볼륨 추가 또는 편집>>.




== 3단계: 볼륨 추가 또는 편집

System Manager에서는 선택한 애플리케이션 또는 워크로드를 기준으로 볼륨 구성을 제안할 수 있습니다. 이 볼륨 구성은 워크로드가 지원하는 애플리케이션 유형에 따라 최적화됩니다. 권장 볼륨 구성을 적용하거나 필요에 따라 편집할 수 있습니다. "기타" 애플리케이션 중 하나를 선택한 경우 생성할 볼륨과 특성을 수동으로 지정해야 합니다.

.시작하기 전에
* 풀 또는 볼륨 그룹에 충분한 가용 용량이 있어야 합니다.
* 볼륨 그룹에서 허용되는 최대 볼륨 수는 256개입니다.
* 풀에서 허용되는 최대 볼륨 수는 스토리지 시스템 모델에 따라 다릅니다.
+
** 2,048 볼륨(EF600 및 E5700 시리즈)
** 1,024개 볼륨(EF300)
** 512 볼륨(E2800 시리즈)


* DA(Data Assurance) 지원 볼륨을 생성하려면 사용하려는 호스트 연결이 DA를 지원해야 합니다.
+
.보안 가능 풀 또는 볼륨 그룹 선택
[%collapsible]
====
DA 지원 볼륨을 생성하려면 DA를 지원하는 풀 또는 볼륨 그룹을 선택합니다(풀 및 볼륨 그룹 후보 테이블에서 "DA" 옆에 * Yes * 가 표시됨).

DA 기능은 System Manager의 풀 및 볼륨 그룹 레벨에서 제공됩니다. DA 보호 기능은 컨트롤러를 통해 드라이브로 데이터가 전송될 때 발생할 수 있는 오류를 검사하고 수정합니다. 새 볼륨에 대해 DA 가능 풀 또는 볼륨 그룹을 선택하면 오류가 감지되고 수정됩니다.

스토리지 시스템의 컨트롤러에 있는 호스트 접속 중 하나라도 DA를 지원하지 않으면 연결된 호스트가 DA 지원 볼륨의 데이터에 액세스할 수 없습니다.

====
* 보안이 설정된 볼륨을 생성하려면 스토리지 배열에 대한 보안 키를 생성해야 합니다.
+
.보안 가능 풀 또는 볼륨 그룹 선택
[%collapsible]
====
보안이 설정된 볼륨을 생성하려면 보안이 가능한 풀 또는 볼륨 그룹을 선택합니다(풀 및 볼륨 그룹 후보 테이블에서 "보안 가능" 옆에 * 예 * 가 표시됨).

드라이브 보안 기능은 System Manager의 풀 및 볼륨 그룹 레벨에서 제공됩니다. 보안 가능 드라이브는 스토리지 어레이에서 물리적으로 제거된 드라이브의 데이터에 대한 무단 액세스를 방지합니다. 보안이 설정된 드라이브는 쓰기 중에 데이터를 암호화하고, 읽을 때 unique_encryption key_를 사용하여 데이터를 해독합니다.

풀 또는 볼륨 그룹에는 보안이 가능한 드라이브와 비보안 가능 드라이브가 모두 포함될 수 있지만 모든 드라이브는 암호화 기능을 사용할 수 있어야 합니다.

====
* 리소스 프로비저닝된 볼륨을 만들려면 모든 드라이브가 DULBE(할당 취소 또는 기록되지 않은 논리적 블록 오류) 옵션이 있는 NVMe 드라이브여야 합니다.


.이 작업에 대해
풀 또는 볼륨 그룹에서 볼륨을 생성합니다. Add/Edit Volumes 대화 상자에는 스토리지 시스템의 모든 적합한 풀 및 볼륨 그룹이 표시됩니다. 해당하는 각 풀 및 볼륨 그룹에 사용 가능한 드라이브 수와 총 사용 가능한 용량이 나타납니다.

일부 애플리케이션별 워크로드의 경우, 해당되는 각 풀 또는 볼륨 그룹은 제안된 볼륨 구성을 기준으로 제안된 용량을 표시하고 남은 사용 가능 용량을 GiB 단위로 표시합니다. 다른 워크로드의 경우 제안된 용량은 풀 또는 볼륨 그룹에 볼륨을 추가하고 보고된 용량을 지정할 때 나타납니다.

.단계
. 다른 워크로드를 선택했는지와 애플리케이션별 워크로드를 기준으로 다음 작업 중 하나를 선택하십시오.
+
** * 기타 * -- 하나 이상의 볼륨을 생성하는 데 사용할 각 풀 또는 볼륨 그룹에서 * 새 볼륨 추가 * 를 클릭합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 필드에 입력합니다 | 설명 


 a| 
볼륨 이름
 a| 
볼륨을 생성하는 동안 System Manager에서 볼륨에 기본 이름을 할당합니다. 기본 이름을 그대로 사용하거나 볼륨에 저장된 데이터의 유형을 나타내는 추가 설명을 제공할 수 있습니다.



 a| 
보고된 용량
 a| 
새 볼륨의 용량과 사용할 용량 단위(MiB, GiB 또는 TiB)를 정의합니다. 일반 볼륨의 경우 최소 용량은 1MiB이고 최대 용량은 풀 또는 볼륨 그룹에 있는 드라이브의 수와 용량에 따라 결정됩니다.

복제 서비스(스냅샷 이미지, 스냅샷 볼륨, 볼륨 복사본, 원격 미러)에도 스토리지 용량이 필요하므로 표준 볼륨에 모든 용량을 할당하지 마십시오.

풀의 용량은 드라이브 유형에 따라 4GiB 또는 8GiB 단위로 할당됩니다. 4GiB 또는 8GiB의 배수에 포함되지 않은 용량은 할당되지만 사용할 수 없습니다. 전체 용량을 사용할 수 있도록 용량을 4GiB 또는 8GiB 단위로 지정합니다. 사용할 수 없는 용량이 있는 경우, 볼륨을 다시 얻을 수 있는 유일한 방법은 볼륨의 용량을 늘리는 것입니다.



 a| 
볼륨 블록 크기(EF300 및 EF600만 해당)
 a| 
볼륨에 대해 생성할 수 있는 블록 크기를 표시합니다.

*** 512 -- 512바이트
*** 4k--4,096바이트




 a| 
세그먼트 크기
 a| 
에는 볼륨 그룹의 볼륨에만 표시되는 세그먼트 크기 조정 설정이 나와 있습니다. 세그먼트 크기를 변경하여 성능을 최적화할 수 있습니다.

* 허용되는 세그먼트 크기 전환 * -- System Manager는 허용되는 세그먼트 크기 전환을 결정합니다. 현재 세그먼트 크기에서 잘못 전환되는 세그먼트 크기는 드롭다운 목록에서 사용할 수 없습니다. 허용되는 전이는 일반적으로 현재 세그먼트 크기의 두 배 또는 절반입니다. 예를 들어 현재 볼륨 세그먼트 크기가 32KiB인 경우 16KiB 또는 64KiB의 새 볼륨 세그먼트 크기가 허용됩니다.

* SSD 캐시 사용 볼륨 * -- SSD 캐시 사용 볼륨에 대해 4KiB 세그먼트 크기를 지정할 수 있습니다. 작은 블록 입출력 작업을 처리하는 SSD Cache 지원 볼륨(예: 16KiB 입출력 블록 크기 이하)에 대해서만 4KiB 세그먼트 크기를 선택해야 합니다. 대규모 블록 순차적 작업을 처리하는 SSD Cache 지원 볼륨의 세그먼트 크기로 4KiB를 선택하면 성능에 영향을 미칠 수 있습니다.

* 세그먼트 크기를 변경하는 시간 * -- 볼륨의 세그먼트 크기를 변경하는 시간은 다음 변수에 따라 다릅니다.

*** 호스트로부터의 I/O 로드
*** 볼륨의 수정 우선 순위입니다
*** 볼륨 그룹의 드라이브 수입니다
*** 드라이브 채널 수입니다
*** 스토리지 어레이 컨트롤러의 처리 능력


볼륨의 세그먼트 크기를 변경하면 I/O 성능에 영향을 미치지만 데이터를 계속 사용할 수 있습니다.



 a| 
보안 가능
 a| 
* 예 * 는 풀 또는 볼륨 그룹의 드라이브가 보안 가능한 경우에만 "보안 가능" 옆에 표시됩니다.

드라이브 보안은 스토리지 어레이에서 물리적으로 제거된 드라이브의 데이터에 대한 무단 액세스를 방지합니다. 이 옵션은 드라이브 보안 기능이 설정되어 있고 스토리지 배열에 대한 보안 키가 설정된 경우에만 사용할 수 있습니다.

풀 또는 볼륨 그룹에는 보안이 가능한 드라이브와 비보안 가능 드라이브가 모두 포함될 수 있지만 모든 드라이브는 암호화 기능을 사용할 수 있어야 합니다.



 a| 
DA
 a| 
* 예 * 는 풀 또는 볼륨 그룹의 드라이브가 DA(Data Assurance)를 지원하는 경우에만 "DA" 옆에 표시됩니다.

DA는 전체 스토리지 시스템에서 데이터 무결성을 높입니다. DA를 사용하면 데이터를 컨트롤러를 통해 드라이브로 전송할 때 발생할 수 있는 오류를 스토리지 어레이에서 확인할 수 있습니다. 새 볼륨에 DA를 사용하면 오류가 감지됩니다.



 a| 
리소스 프로비저닝(EF300 및 EF600만 해당)
 a| 
드라이브가 이 옵션을 지원하는 경우에만 * 예 * 가 "리소스 프로비저닝" 옆에 표시됩니다. 리소스 프로비저닝은 EF300 및 EF600 스토리지 어레이에서 사용 가능한 기능으로, 백그라운드 초기화 프로세스 없이 볼륨을 즉시 사용할 수 있도록 지원합니다.

|===
====
** * 애플리케이션별 워크로드 * -- * 다음 * 을 클릭하여 선택한 워크로드에 대해 시스템 권장 볼륨 및 특성을 수락하거나 * 볼륨 편집 * 을 클릭하여 선택한 워크로드에 대해 시스템 권장 볼륨 및 특성을 변경, 추가 또는 삭제합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="1a,1a"]
|===
| 필드에 입력합니다 | 설명 


 a| 
볼륨 이름
 a| 
볼륨을 생성하는 동안 System Manager에서 볼륨에 기본 이름을 할당합니다. 기본 이름을 그대로 사용하거나 볼륨에 저장된 데이터의 유형을 나타내는 추가 설명을 제공할 수 있습니다.



 a| 
보고된 용량
 a| 
새 볼륨의 용량과 사용할 용량 단위(MiB, GiB 또는 TiB)를 정의합니다. 일반 볼륨의 경우 최소 용량은 1MiB이고 최대 용량은 풀 또는 볼륨 그룹에 있는 드라이브의 수와 용량에 따라 결정됩니다.

복제 서비스(스냅샷 이미지, 스냅샷 볼륨, 볼륨 복사본, 원격 미러)에도 스토리지 용량이 필요하므로 표준 볼륨에 모든 용량을 할당하지 마십시오.

풀의 용량은 드라이브 유형에 따라 4GiB 또는 8GiB 단위로 할당됩니다. 4GiB 또는 8GiB의 배수에 포함되지 않은 용량은 할당되지만 사용할 수 없습니다. 전체 용량을 사용할 수 있도록 용량을 4GiB 또는 8GiB 단위로 지정합니다. 사용할 수 없는 용량이 있는 경우, 볼륨을 다시 얻을 수 있는 유일한 방법은 볼륨의 용량을 늘리는 것입니다.



 a| 
볼륨 유형
 a| 
볼륨 유형은 애플리케이션별 워크로드에 대해 생성한 볼륨 유형을 나타냅니다.



 a| 
볼륨 블록 크기(EF300 및 EF600만 해당)
 a| 
볼륨에 대해 생성할 수 있는 블록 크기를 표시합니다.

*** 512 -- 512바이트
*** 4k--4,096바이트




 a| 
세그먼트 크기
 a| 
에는 볼륨 그룹의 볼륨에만 표시되는 세그먼트 크기 조정 설정이 나와 있습니다. 세그먼트 크기를 변경하여 성능을 최적화할 수 있습니다.

* 허용되는 세그먼트 크기 전환 * -- System Manager는 허용되는 세그먼트 크기 전환을 결정합니다. 현재 세그먼트 크기에서 잘못 전환되는 세그먼트 크기는 드롭다운 목록에서 사용할 수 없습니다. 허용되는 전이는 일반적으로 현재 세그먼트 크기의 두 배 또는 절반입니다. 예를 들어 현재 볼륨 세그먼트 크기가 32KiB인 경우 16KiB 또는 64KiB의 새 볼륨 세그먼트 크기가 허용됩니다.

* SSD 캐시 사용 볼륨 * -- SSD 캐시 사용 볼륨에 대해 4KiB 세그먼트 크기를 지정할 수 있습니다. 작은 블록 입출력 작업을 처리하는 SSD Cache 지원 볼륨(예: 16KiB 입출력 블록 크기 이하)에 대해서만 4KiB 세그먼트 크기를 선택해야 합니다. 대규모 블록 순차적 작업을 처리하는 SSD Cache 지원 볼륨의 세그먼트 크기로 4KiB를 선택하면 성능에 영향을 미칠 수 있습니다.

* 세그먼트 크기를 변경하는 시간 * -- 볼륨의 세그먼트 크기를 변경하는 시간은 다음 변수에 따라 다릅니다.

*** 호스트로부터의 I/O 로드
*** 볼륨의 수정 우선 순위입니다
*** 볼륨 그룹의 드라이브 수입니다
*** 드라이브 채널 수입니다
*** 스토리지 어레이 컨트롤러의 처리 능력 볼륨의 세그먼트 크기를 변경하면 I/O 성능에 영향을 미치지만 데이터를 계속 사용할 수 있습니다.




 a| 
보안 가능
 a| 
* 예 * 는 풀 또는 볼륨 그룹의 드라이브가 보안 가능한 경우에만 "보안 가능" 옆에 표시됩니다.

드라이브 보안은 스토리지 어레이에서 물리적으로 제거된 드라이브의 데이터에 대한 무단 액세스를 방지합니다. 이 옵션은 드라이브 보안 기능이 설정되어 있고 스토리지 배열에 대한 보안 키가 설정된 경우에만 사용할 수 있습니다.

풀 또는 볼륨 그룹에는 보안이 가능한 드라이브와 비보안 가능 드라이브가 모두 포함될 수 있지만 모든 드라이브는 암호화 기능을 사용할 수 있어야 합니다.



 a| 
DA
 a| 
* 예 * 는 풀 또는 볼륨 그룹의 드라이브가 DA(Data Assurance)를 지원하는 경우에만 "DA" 옆에 표시됩니다.

DA는 전체 스토리지 시스템에서 데이터 무결성을 높입니다. DA를 사용하면 데이터를 컨트롤러를 통해 드라이브로 전송할 때 발생할 수 있는 오류를 스토리지 어레이에서 확인할 수 있습니다. 새 볼륨에 DA를 사용하면 오류가 감지됩니다.



 a| 
리소스 프로비저닝(EF300 및 EF600만 해당)
 a| 
드라이브가 이 옵션을 지원하는 경우에만 * 예 * 가 "리소스 프로비저닝" 옆에 표시됩니다. 리소스 프로비저닝은 EF300 및 EF600 스토리지 어레이에서 사용 가능한 기능으로, 백그라운드 초기화 프로세스 없이 볼륨을 즉시 사용할 수 있도록 지원합니다.

|===
====


. 선택한 응용 프로그램에 대한 볼륨 생성 순서를 계속하려면 * 다음 * 을 클릭하고 로 이동합니다 <<4단계: 볼륨 구성을 검토합니다>>.




== 4단계: 볼륨 구성을 검토합니다

생성하려는 볼륨의 요약을 검토하고 필요한 사항을 변경합니다.

.단계
. 생성할 볼륨을 검토합니다. 변경하려면 * 뒤로 * 를 클릭합니다.
. 볼륨 구성이 만족스러우면 * 마침 * 을 클릭합니다.


.결과
System Manager는 선택한 풀 및 볼륨 그룹에 새 볼륨을 생성한 다음 All Volumes 테이블에 새 볼륨을 표시합니다.

.작업을 마친 후
* 응용 프로그램이 볼륨을 사용할 수 있도록 응용 프로그램 호스트에서 필요한 모든 운영 체제 수정을 수행합니다.
* 운영 체제 특정 유틸리티(타사 공급업체에서 제공)를 실행한 다음 SMcli 명령을 실행합니다 `-identifyDevices` 볼륨 이름과 호스트 스토리지 배열 이름을 서로 연관시킵니다.
+
SMcli는 SANtricity System Manager를 통해 직접 사용할 수 있습니다. SMcli의 다운로드 가능한 버전은 EF600, EF300, E5700, EF570, E2800에서 사용할 수 있습니다. EF280 컨트롤러: SANtricity 시스템 관리자 내에서 SMcli를 다운로드하려면 * 설정 * > * 시스템 * 및 * 추가 기능 * > * 명령줄 인터페이스 * 를 선택합니다.


