---
permalink: sm-storage/create-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, snapshot, volume 
summary: 스냅샷 볼륨을 생성하여 볼륨 또는 스냅샷 정합성 보장 그룹의 스냅샷 이미지에 대한 호스트 액세스를 제공합니다. 스냅샷 볼륨을 읽기 전용 또는 읽기-쓰기로 지정할 수 있습니다. 
---
= 스냅샷 볼륨을 생성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 볼륨을 생성하여 볼륨 또는 스냅샷 정합성 보장 그룹의 스냅샷 이미지에 대한 호스트 액세스를 제공합니다. 스냅샷 볼륨을 읽기 전용 또는 읽기-쓰기로 지정할 수 있습니다.

스냅샷 볼륨 생성 시퀀스를 사용하여 스냅샷 이미지에서 스냅샷 볼륨을 생성하고 볼륨이 읽기/쓰기일 경우 예약된 용량을 할당하는 옵션을 제공합니다. 스냅샷 볼륨은 다음 중 하나로 지정할 수 있습니다.

* 읽기 전용 스냅샷 볼륨은 호스트 애플리케이션에 스냅샷 이미지에 포함된 데이터 복제본에 대한 읽기 액세스 권한을 제공하지만 스냅샷 이미지를 수정할 수는 없습니다. 읽기 전용 스냅샷 볼륨에는 연결된 예약 용량이 없습니다.
* 읽기-쓰기 스냅샷 볼륨은 호스트 애플리케이션에 스냅샷 이미지에 포함된 데이터 복제본에 대한 쓰기 액세스 권한을 제공합니다. 호스트 애플리케이션이 수정한 후속 사항을 참조 스냅샷 이미지에 영향을 주지 않고 기본 볼륨에 저장하는 데 사용되는 고유한 예약 용량을 가지고 있습니다.


스냅샷 볼륨을 생성하는 프로세스는 여러 단계로 이루어집니다.



== 1단계: 스냅샷 볼륨의 구성원을 검토합니다

기본 볼륨의 스냅샷 이미지 또는 스냅샷 정합성 보장 그룹을 선택합니다. 스냅샷 정합성 보장 그룹 스냅샷 이미지를 선택하면 스냅샷 정합성 보장 그룹의 구성원 볼륨이 검토를 위해 표시됩니다.

.단계
. 스토리지 [스냅샷] 메뉴를 선택합니다.
. Snapshot Volumes * 탭을 선택합니다.
. Create * 를 선택합니다.
+
스냅샷 볼륨 생성 대화 상자가 나타납니다.

. 스냅샷 볼륨으로 변환할 스냅샷 이미지(볼륨 또는 스냅샷 정합성 보장 그룹)를 선택하고 * 다음 * 을 클릭합니다. 필터 * 필드의 텍스트 항목을 사용하여 목록 범위를 좁힙니다.
+
스냅샷 정합성 보장 그룹 스냅샷 이미지를 선택한 경우 구성원 검토 대화 상자가 나타납니다.

+
Review Members(구성원 검토) 대화 상자에서 스냅샷 볼륨으로 변환하기 위해 선택한 볼륨 목록을 검토한 후 * Next * (다음 *)를 클릭합니다.

. 로 이동합니다 <<Step 2: Assign snapshot volume to host>>.




== 2단계: 호스트에 스냅샷 볼륨을 할당합니다

특정 호스트 또는 호스트 클러스터를 선택하여 스냅샷 볼륨에 할당합니다. 이 할당은 호스트 또는 호스트 클러스터에 스냅샷 볼륨에 대한 액세스 권한을 부여합니다. 필요한 경우 나중에 호스트를 할당할 수 있습니다.

.시작하기 전에
* 호스트 페이지에 유효한 호스트 또는 호스트 클러스터가 있습니다.
* 호스트에 대해 호스트 포트 식별자를 정의해야 합니다.
* DA 지원 볼륨을 생성하기 전에 계획된 호스트 연결이 DA(Data Assurance) 기능을 지원하는지 확인하십시오. 스토리지 시스템의 컨트롤러에 있는 호스트 접속 중 하나라도 DA를 지원하지 않으면 연결된 호스트가 DA 지원 볼륨의 데이터에 액세스할 수 없습니다.


볼륨을 할당할 때 다음 지침을 염두에 두십시오.

* 호스트의 운영 체제에는 호스트가 액세스할 수 있는 볼륨 수에 대한 특정 제한이 있을 수 있습니다.
* 스토리지 배열의 각 스냅샷 볼륨에 대해 하나의 호스트 할당을 정의할 수 있습니다.
* 할당된 볼륨은 스토리지 배열의 컨트롤러 간에 공유됩니다.
* 동일한 LUN(Logical Unit Number)은 호스트 또는 호스트 클러스터에서 스냅샷 볼륨을 액세스하는 데 두 번 사용할 수 없습니다. 고유한 LUN을 사용해야 합니다.


[NOTE]
====
호스트 클러스터의 호스트에 대해 설정된 할당과 충돌하는 호스트 클러스터에 볼륨을 할당하려고 하면 호스트에 볼륨을 할당할 수 없습니다.

====
.단계
. 호스트에 할당 * 대화 상자에서 새 볼륨에 할당할 호스트 또는 호스트 클러스터를 선택합니다. 호스트를 할당하지 않고 볼륨을 생성하려면 드롭다운 목록에서 * 나중에 할당 * 을 선택합니다.
. 액세스 모드를 선택합니다. 다음 중 하나를 선택합니다.
+
** * 읽기/쓰기 * -- 이 옵션은 스냅샷 볼륨에 대한 읽기/쓰기 액세스를 호스트에 제공하며 예약된 용량이 필요합니다.
** * 읽기 전용 * -- 이 옵션은 스냅샷 볼륨에 대한 읽기 전용 액세스를 호스트에 제공하며 예약된 용량이 필요하지 않습니다.


. 다음 * 을 클릭하고 다음 중 하나를 수행합니다.
+
** 스냅샷 볼륨이 읽기/쓰기 상태인 경우 용량 검토 대화 상자가 나타납니다. 로 이동합니다 <<Step 3: Reserve capacity for a snapshot volume>>.
** 스냅샷 볼륨이 읽기 전용인 경우 우선 순위 편집 대화 상자가 나타납니다. 로 이동합니다 <<Step 4: Edit settings for a snapshot volume>>.






== 3단계: 스냅샷 볼륨의 예비 용량을 설정합니다

예약된 용량을 읽기/쓰기 스냅샷 볼륨에 연결합니다. System Manager에서는 기본 볼륨 또는 스냅샷 정합성 보장 그룹의 속성을 기준으로 볼륨 및 용량을 제안합니다. 권장 예약 용량 구성을 수락하거나 할당된 스토리지를 사용자 지정할 수 있습니다.

필요에 따라 스냅샷 볼륨의 예약된 용량을 늘리거나 줄일 수 있습니다. 스냅샷 예약 용량이 필요한 용량보다 큰 경우 크기를 줄여 다른 논리적 볼륨에서 필요한 공간을 확보할 수 있습니다.

.단계
. 스피너 상자를 사용하여 스냅샷 볼륨에 예약된 용량을 할당합니다.
+
볼륨 후보 테이블에는 지정된 예약 용량을 지원하는 후보만 표시됩니다.

+
다음 작업 중 하나를 수행합니다.

+
** * 기본 설정을 적용합니다 *.
+
이 권장 옵션을 사용하여 스냅샷 볼륨에 예약된 용량을 기본 설정으로 할당합니다.

** * 데이터 스토리지 요구 사항을 충족하기 위해 자체 예약된 용량 설정을 할당합니다. *.
+
기본 예약된 용량 설정을 변경하는 경우 * 후보 새로 고침 * 을 클릭하여 지정한 예약된 용량에 대한 후보 목록을 새로 고칩니다.

+
다음 지침에 따라 예약된 용량을 할당합니다.

+
*** 예약된 용량의 기본 설정은 기본 볼륨 용량의 40%이며 일반적으로 이 용량이면 충분합니다.
*** 필요한 용량은 볼륨에 대한 입출력 쓰기 빈도 및 크기와 스냅샷 이미지 컬렉션의 양과 기간에 따라 달라집니다.




. * 선택 사항: * 스냅샷 정합성 보장 그룹에 대한 스냅샷 볼륨을 생성하는 경우 예약된 용량 후보 테이블에 "후보 변경" 옵션이 나타납니다. 후보 변경 * 을 클릭하여 예약된 대체 용량을 선택합니다.
. 다음 * 을 클릭하고 으로 이동합니다 <<Step 4: Edit settings for a snapshot volume>>.




== 4단계: 스냅샷 볼륨에 대한 설정을 편집합니다

이름, 캐싱, 예약된 용량 알림 임계값 등과 같은 스냅샷 볼륨의 설정을 변경합니다.

읽기 전용 성능을 개선하기 위해 SSD(Solid State Disk) 캐시에 볼륨을 추가할 수 있습니다. SSD 캐시는 스토리지 어레이에서 논리적으로 그룹화하는 SSD 드라이브 세트로 구성됩니다.

.단계
. 스냅샷 볼륨에 대한 설정을 적절히 적용하거나 변경합니다.
+
.필드 상세정보
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
* 스냅샷 볼륨 설정 *



 a| 
이름
 a| 
스냅샷 볼륨의 이름을 지정합니다.



 a| 
SSD Cache를 활성화합니다
 a| 
SSD에서 읽기 전용 캐싱을 설정하려면 이 옵션을 선택합니다. 참고: EF600 또는 EF300 스토리지 시스템에서는 이 기능을 사용할 수 없습니다.



 a| 
* 예약된 용량 설정 *



 a| 
다음 경우에 알림:
 a| 
* 는 읽기/쓰기 스냅샷 볼륨에 대해서만 표시됩니다 *.

spinner 상자를 사용하여 스냅샷 그룹의 예약된 용량이 거의 가득 찰 때 시스템에서 경고 알림을 보내는 백분율 지점을 조정합니다.

스냅샷 그룹의 예약된 용량이 지정된 임계값을 초과하는 경우 사전 알림을 사용하여 예약된 용량을 늘리거나 남은 공간이 부족해지기 전에 불필요한 객체를 삭제하십시오.

|===
====
. 스냅샷 볼륨 구성을 검토합니다. 변경하려면 * 뒤로 * 를 클릭합니다.
. 스냅샷 볼륨 구성이 만족스러우면 * 마침 * 을 클릭합니다.

