---
permalink: sm-storage/data-integrity-and-data-security-for-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, data, integrity, security, volumes 
summary: '볼륨에서 DA(Data Assurance) 기능 및 드라이브 보안 기능을 사용하도록 설정할 수 있습니다. 이러한 기능은 풀 및 볼륨 그룹 레벨에서 제공됩니다.' 
---
= 볼륨에 대한 데이터 무결성 및 데이터 보안
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨에서 DA(Data Assurance) 기능 및 드라이브 보안 기능을 사용하도록 설정할 수 있습니다. 이러한 기능은 풀 및 볼륨 그룹 레벨에서 제공됩니다.



== 데이터 무결성 보장

DA(Data Assurance)는 T10 PI(보호 정보) 표준을 구현하여 I/O 경로를 통해 데이터가 전송될 때 발생할 수 있는 오류를 확인하고 수정하여 데이터 무결성을 향상합니다. 일반적으로 Data Assurance 기능을 사용하면 컨트롤러와 드라이브 사이의 입출력 경로 부분을 확인할 수 있습니다. DA 기능은 풀 및 볼륨 그룹 레벨에서 제공됩니다.

이 기능을 활성화하면 스토리지 배열은 볼륨의 각 데이터 블록에 오류 검사 코드(순환 중복 검사 또는 CRC라고도 함)를 추가합니다. 데이터 블록이 이동된 후 스토리지 배열은 이러한 CRC 코드를 사용하여 전송 중에 오류가 발생했는지 확인합니다. 잠재적으로 손상된 데이터는 디스크에 기록되거나 호스트에 반환되지 않습니다. DA 기능을 사용하려면 새 볼륨을 생성할 때 DA를 지원하는 풀 또는 볼륨 그룹을 선택합니다(풀 및 볼륨 그룹 후보 테이블에서 "DA" 옆에 있는 "예"를 확인합니다).



== 드라이브 보안

드라이브 보안은 스토리지 어레이에서 제거할 때 보안이 설정된 드라이브의 데이터에 대한 무단 액세스를 방지하는 기능입니다. 이러한 드라이브는 연방 정보 처리 표준 140-2 레벨 2(FIPS 드라이브)를 충족하도록 인증된 전체 디스크 암호화(FDE) 드라이브 또는 드라이브일 수 있습니다.



=== 드라이브 보안 작동 방식

FDE 또는 FIPS 중 어떤 보안 가능 드라이브도 쓰기 중에 데이터를 암호화하고 읽기 중에 데이터를 해독합니다. 이 암호화 및 암호 해독은 성능 또는 사용자 워크플로에 영향을 주지 않습니다. 각 드라이브에는 드라이브에서 전송할 수 없는 고유한 암호화 키가 있습니다.



=== 드라이브 보안이 볼륨 수준에서 작동하는 방식

보안 가능 드라이브에서 풀 또는 볼륨 그룹을 생성할 때 해당 풀 또는 볼륨 그룹에 대해 드라이브 보안을 설정할 수도 있습니다. Drive Security 옵션을 사용하면 드라이브 및 관련 볼륨 그룹과 풀의 보안이 __enabled_로 설정됩니다. 풀 또는 볼륨 그룹에는 보안이 가능한 드라이브와 비보안 가능 드라이브가 모두 포함될 수 있지만 모든 드라이브는 암호화 기능을 사용할 수 있어야 합니다.



=== 드라이브 보안을 구현하는 방법

드라이브 보안을 구현하려면 다음 단계를 수행하십시오.

. 스토리지 어레이에 FDE 드라이브 또는 FIPS 드라이브와 같은 보안 지원 드라이브를 제공합니다. (FIPS 지원이 필요한 볼륨의 경우 FIPS 드라이브만 사용합니다. 볼륨 그룹 또는 풀에서 FIPS 및 FDE 드라이브를 혼합하면 모든 드라이브가 FDE 드라이브로 처리됩니다. 또한 FDE 드라이브는 All-FIPS 볼륨 그룹 또는 풀에서 스페어로 추가하거나 사용할 수 없습니다.)
. 컨트롤러 및 드라이브에서 읽기/쓰기 액세스를 위해 공유하는 일련의 문자인 보안 키를 생성합니다. 컨트롤러의 영구 메모리에서 내부 키를 만들거나 키 관리 서버에서 외부 키를 만들 수 있습니다. 외부 키 관리의 경우 키 관리 서버를 사용하여 인증을 설정해야 합니다.
. 풀 및 볼륨 그룹에 대해 드라이브 보안 설정:
+
** 풀 또는 볼륨 그룹을 생성합니다(후보 테이블의 * Secure-Capable * 열에서 * Yes * 를 찾습니다).
** 새 볼륨을 생성할 때 풀 또는 볼륨 그룹을 선택합니다(풀 및 볼륨 그룹 후보 테이블에서 * 보안 가능 * 옆에 * 예 * 가 표시됨).
+
드라이브 보안 기능을 사용하면 스토리지 배열의 보안 지원 드라이브와 컨트롤러 간에 공유되는 보안 키를 만들 수 있습니다. 드라이브 전원을 껐다가 켤 때마다 보안 활성 드라이브는 컨트롤러가 보안 키를 적용할 때까지 보안 잠금 상태로 변경됩니다.




