---
permalink: sm-storage/decide-to-use-a-pool-or-volume-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, pool, volume group 
summary: 풀 또는 볼륨 그룹을 사용하여 볼륨을 생성할 수 있습니다. 최적의 선택은 주로 예상되는 I/O 워크로드, 성능 요구 사항 및 데이터 보호 요구 사항과 같은 주요 스토리지 요구 사항에 따라 달라집니다. 
---
= 풀 또는 볼륨 그룹을 사용할지 여부를 결정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
풀 또는 볼륨 그룹을 사용하여 볼륨을 생성할 수 있습니다. 최적의 선택은 주로 예상되는 I/O 워크로드, 성능 요구 사항 및 데이터 보호 요구 사항과 같은 주요 스토리지 요구 사항에 따라 달라집니다.



== 풀 또는 볼륨 그룹을 선택해야 하는 이유

* 풀을 선택하십시오 *

* 더 빠른 드라이브 리빌드 및 단순화된 스토리지 관리가 필요한 경우, 씬 볼륨 또는 랜덤 워크로드가 필요합니다.
* 풀을 구성하는 드라이브 세트에 각 볼륨의 데이터를 무작위로 분산하려는 경우
+
풀 또는 풀의 볼륨은 RAID 레벨을 설정하거나 변경할 수 없습니다. 풀은 RAID 레벨 6을 사용합니다.



* 볼륨 그룹을 선택합니다 *

* 최대 시스템 대역폭이 필요한 경우 스토리지 설정을 조정할 수 있고 워크로드가 매우 순차적입니다.
* RAID 레벨을 기반으로 드라이브에 데이터를 배포하려는 경우 볼륨 그룹을 생성할 때 RAID 레벨을 지정할 수 있습니다.
* 볼륨 그룹을 구성하는 드라이브 세트를 통해 각 볼륨의 데이터를 순차적으로 쓰려는 경우


[NOTE]
====
풀은 볼륨 그룹과 함께 존재할 수 있으므로 스토리지 어레이에는 풀과 볼륨 그룹이 모두 포함될 수 있습니다.

====


== 풀과 볼륨 그룹 간의 기능 차이

다음 표에서는 볼륨 그룹과 풀을 비교하여 보여 줍니다.

[cols="1a,1a,1a"]
|===
| 사용 | 수영장 | 볼륨 그룹 


 a| 
워크로드 임의
 a| 
더 좋습니다
 a| 
좋습니다



 a| 
순차 워크로드
 a| 
좋습니다
 a| 
더 좋습니다



 a| 
드라이브 리빌드 시간
 a| 
더 빠른 속도
 a| 
느린 속도



 a| 
성능(최적 모드)
 a| 
양호: 소규모 블록, 랜덤 워크로드에 적합
 a| 
좋음: 대규모 블록, 순차적 워크로드에 적합



 a| 
성능(드라이브 리빌드 모드)
 a| 
우수: 일반적으로 RAID 6보다 우수
 a| 
성능 저하: 최대 40% 성능 저하



 a| 
다중 드라이브 장애
 a| 
데이터 보호 향상: 리빌드 속도 향상 및 우선순위 지정
 a| 
데이터 보호 기능 저하: 느린 리빌드, 더 높은 데이터 손실 위험



 a| 
드라이브 추가
 a| 
빠른 속도: 즉석에서 풀에 추가
 a| 
느림: 동적 용량 확장 작업이 필요합니다



 a| 
씬 볼륨이 지원됩니다
 a| 
예
 a| 
아니요



 a| 
SSD(Solid State Disk) 지원
 a| 
예
 a| 
예



 a| 
단순한 관리
 a| 
예: 구성할 핫 스페어 또는 RAID 설정이 없습니다
 a| 
아니요: 핫 스페어를 할당하고 RAID를 구성해야 합니다



 a| 
성능 조정 가능
 a| 
아니요
 a| 
예

|===


== 풀 및 볼륨 그룹의 기능 비교

풀과 볼륨 그룹의 기능과 용도는 동일합니다. 두 오브젝트 모두 논리적으로 그룹화된 드라이브 세트이며 호스트가 액세스할 수 있는 볼륨을 생성하는 데 사용됩니다.

다음 표에서는 풀 또는 볼륨 그룹이 스토리지 요구 사항에 가장 적합한지 여부를 결정하는 데 도움이 됩니다.

[cols="1a,1a,1a"]
|===
| 기능 | 수영장 | 볼륨 그룹 


 a| 
다른 RAID 레벨이 지원됩니다
 a| 
아니요 항상 System Manager의 RAID 6을 사용하십시오.
 a| 
예. RAID 0, 1, 10, 5 및 6을 사용할 수 있습니다.



 a| 
씬 볼륨이 지원됩니다
 a| 
예
 a| 
아니요



 a| 
FDE(전체 디스크 암호화)가 지원됩니다
 a| 
예
 a| 
예



 a| 
DA(Data Assurance) 지원
 a| 
예
 a| 
예



 a| 
쉘프 손실 보호가 지원됩니다
 a| 
예
 a| 
예



 a| 
서랍 손실 보호가 지원됩니다
 a| 
예
 a| 
예



 a| 
혼합 드라이브 속도가 지원됩니다
 a| 
같은 것을 권장하지만 필수는 아닙니다. 가장 느린 드라이브는 모든 드라이브의 속도를 결정합니다.
 a| 
같은 것을 권장하지만 필수는 아닙니다. 가장 느린 드라이브는 모든 드라이브의 속도를 결정합니다.



 a| 
혼합 드라이브 용량이 지원됩니다
 a| 
같은 것을 권장하지만 필수는 아닙니다. 가장 작은 드라이브는 모든 드라이브의 용량을 결정합니다.
 a| 
같은 것을 권장하지만 필수는 아닙니다. 가장 작은 드라이브는 모든 드라이브의 용량을 결정합니다.



 a| 
최소 드라이브 수입니다
 a| 
11
 a| 
RAID 레벨에 따라 다릅니다. RAID 0에는 1이 필요합니다. RAID 1 또는 10에는 2가 필요합니다(짝수 필요). 최소 RAID 5는 3입니다. 최소 RAID 6은 5입니다.



 a| 
최대 드라이브 수입니다
 a| 
스토리지 배열의 최대 제한입니다
 a| 
RAID 1 및 10 - 스토리지 어레이 RAID 5, 6-30개 드라이브의 최대 제한입니다



 a| 
볼륨을 생성할 때 개별 드라이브를 선택할 수 있습니다
 a| 
아니요
 a| 
예



 a| 
볼륨을 생성할 때 세그먼트 크기를 지정할 수 있습니다
 a| 
예. 128K가 지원됩니다.
 a| 
예



 a| 
볼륨을 생성할 때 입출력 특성을 지정할 수 있습니다
 a| 
아니요
 a| 
예. 파일 시스템, 데이터베이스, 멀티미디어 및 맞춤형 지원



 a| 
드라이브 장애 방지
 a| 
풀의 각 드라이브에서 보존 용량을 사용하므로 재구성 속도가 빨라집니다.
 a| 
핫 스페어 드라이브를 사용합니다. 드라이브 IOP에 따라 재구성이 제한됩니다.



 a| 
용량 제한에 도달할 때 경고가 표시됩니다
 a| 
예. 사용된 용량이 최대 용량의 비율에 도달하면 경고를 설정할 수 있습니다.
 a| 
아니요



 a| 
지원되는 다른 스토리지 어레이로 마이그레이션
 a| 
아니요 먼저 볼륨 그룹으로 마이그레이션해야 합니다.
 a| 
예



 a| 
동적 세그먼트 크기(DSS)
 a| 
아니요
 a| 
예



 a| 
RAID 레벨을 변경할 수 있습니다
 a| 
아니요
 a| 
예



 a| 
볼륨 확장(용량 증가)
 a| 
예
 a| 
예



 a| 
용량 확장(용량 추가)
 a| 
예
 a| 
예



 a| 
용량 절감
 a| 
예
 a| 
아니요

|===
[NOTE]
====
혼합 드라이브 유형(HDD, SSD)은 풀 또는 볼륨 그룹에서 지원되지 않습니다.

====