---
permalink: sm-storage/delete-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, volume 
summary: 일반적으로 볼륨이 잘못된 매개 변수 또는 용량으로 생성되었거나, 스토리지 구성 요구 사항을 더 이상 충족하지 않거나, 백업 또는 애플리케이션 테스트에 더 이상 필요하지 않은 스냅샷 이미지일 경우 볼륨을 삭제합니다. 
---
= 볼륨을 삭제합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
일반적으로 볼륨이 잘못된 매개 변수 또는 용량으로 생성되었거나, 스토리지 구성 요구 사항을 더 이상 충족하지 않거나, 백업 또는 애플리케이션 테스트에 더 이상 필요하지 않은 스냅샷 이미지일 경우 볼륨을 삭제합니다.

볼륨을 삭제하면 풀 또는 볼륨 그룹의 사용 가능한 용량이 증가합니다. 삭제할 볼륨을 하나 이상 선택할 수 있습니다.

.시작하기 전에
삭제하려는 볼륨에서 다음 사항을 확인합니다.

* 모든 데이터가 백업됩니다.
* 모든 입출력(I/O)이 중지됩니다.
* 모든 디바이스 및 파일 시스템이 마운트 해제되었습니다.


.이 작업에 대해
다음 조건 중 하나가 있는 볼륨은 삭제할 수 없습니다.

* 볼륨을 초기화하는 중입니다.
* 볼륨을 재구성하는 중입니다.
* 볼륨은 카피백 작업을 진행 중인 드라이브가 포함된 볼륨 그룹의 일부입니다.
* 볼륨이 이제 실패 상태가 아닌 경우, 볼륨이 세그먼트 크기 변경과 같은 수정 작업을 진행 중입니다.
* 볼륨에 모든 유형의 영구 예약이 있습니다.
* 볼륨은 복사 볼륨의 소스 볼륨 또는 대상 볼륨이며 보류 중, 진행 중 또는 실패 상태입니다.


[CAUTION]
====
볼륨을 삭제하면 해당 볼륨의 모든 데이터가 손실됩니다.

====
[NOTE]
====
볼륨이 지정된 크기(현재 128TB)를 초과할 경우 백그라운드에서 삭제가 수행되고 있으며 확보된 공간을 즉시 사용할 수 없습니다.

====
.단계
. Storage [Volumes](저장소 [볼륨]) 메뉴를 선택합니다.
. 삭제 * 를 클릭합니다.
+
Delete Volumes(볼륨 삭제) 대화 상자가 나타납니다.

. 삭제할 볼륨을 하나 이상 선택하고 작업을 수행할지 확인합니다.
. 삭제 * 를 클릭합니다.


.결과
System Manager는 다음 작업을 수행합니다.

* 연결된 스냅샷 이미지, 스케줄 및 스냅샷 볼륨을 삭제합니다.
* 미러링 관계를 제거합니다.
* 풀 또는 볼륨 그룹의 사용 가능한 용량을 늘립니다.

