---
permalink: sm-storage/disable-resource-provisioning-on-existing-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, disable, resource provisioning, 
summary: 기존 풀 또는 볼륨 그룹에서 리소스 프로비저닝을 설정하거나 해제할 수 있습니다. 
---
= 기존 볼륨 그룹 및 풀에서 리소스 프로비저닝을 설정하거나 해제합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 DULBE 가능 드라이브의 경우 풀 또는 볼륨 그룹의 기존 볼륨에서 리소스 프로비저닝을 설정하거나 해제할 수 있습니다.

리소스 프로비저닝은 EF300 및 EF600 스토리지 어레이에서 사용 가능한 기능으로, 백그라운드 초기화 프로세스 없이 볼륨을 즉시 사용할 수 있도록 지원합니다. 볼륨에 할당된 모든 드라이브 블록이 할당 해제(매핑 해제)되어 SSD 마모 수명을 개선하고 최대 쓰기 성능을 높일 수 있습니다.

기본적으로 드라이브가 DULBE를 지원하는 시스템에서 리소스 프로비저닝이 설정됩니다. 이전에 리소스 프로비저닝을 사용하지 않도록 설정하지 않았다면 리소스 프로비저닝을 설정할 필요가 없습니다.

.시작하기 전에
* EF300 또는 EF600 스토리지 어레이가 있어야 합니다.
* 모든 드라이브에서 NVMe 할당 해제 또는 DULBE(UnWritten Logical Block Error Enable) 오류 복구 기능을 지원하는 SSD 볼륨 그룹 또는 풀이 있어야 합니다. 그렇지 않으면 리소스 프로비저닝 옵션을 사용할 수 없습니다.


.이 작업에 대해
기존 볼륨 그룹 및 풀에 대한 리소스 프로비저닝을 설정하면 선택한 볼륨 그룹 또는 풀에 있는 모든 볼륨을 변경하여 블록을 할당 해제할 수 있습니다. 이 프로세스에는 매핑 해제 세분화 수준에서 일관된 할당을 보장하기 위한 백그라운드 작업이 포함될 수 있습니다. 이 작업에서는 공간을 매핑 해제하지 않습니다. 백그라운드 작업이 완료되면 운영 체제에서 사용하지 않는 블록의 매핑을 해제해야 여유 공간을 만들 수 있습니다.

기존 볼륨 그룹 또는 풀에 대해 리소스 프로비저닝을 사용하지 않도록 설정하면 백그라운드 작업이 모든 볼륨의 모든 논리적 블록을 다시 기록합니다. 기존 데이터는 그대로 유지됩니다. 쓰기 작업은 볼륨 그룹 또는 풀과 연결된 드라이브의 블록을 매핑하거나 프로비저닝합니다.


NOTE: 새 볼륨 그룹 및 풀의 경우 Settings[System>Additional Settings>Enable/Disable Resource-provisioned Volumes] 메뉴에서 리소스 프로비저닝을 설정하거나 해제할 수 있습니다.

.단계
. 스토리지 [풀 및 볼륨 그룹] 메뉴를 선택합니다.
. 목록에서 풀 또는 볼륨 그룹을 하나 선택합니다.
+
한 번에 하나의 풀 또는 볼륨 그룹만 선택할 수 있습니다. 목록을 아래로 스크롤하여 추가 풀 또는 볼륨 그룹을 확인합니다.

. Uncommon Tasks * 를 선택한 다음 * Enable resource provisioning * 또는 * Disable resource provisioning * 을 선택합니다.
. 대화 상자에서 작업을 확인합니다.



NOTE: * DULBE * 를 다시 활성화한 경우 백그라운드 작업이 완료된 후 호스트를 재부팅하여 DULBE 구성 변경 사항을 탐지한 다음 모든 파일 시스템을 다시 마운트해야 할 수 있습니다.
