---
permalink: sm-storage/disable-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, disable, snapshot, volume 
summary: 스냅샷 정합성 보장 그룹이 더 이상 필요하지 않거나 일시적으로 사용을 중지하려는 경우 스냅샷 볼륨 또는 스냅샷 볼륨을 비활성화할 수 있습니다. 
---
= 스냅샷 볼륨을 비활성화합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 정합성 보장 그룹이 더 이상 필요하지 않거나 일시적으로 사용을 중지하려는 경우 스냅샷 볼륨 또는 스냅샷 볼륨을 비활성화할 수 있습니다.

.이 작업에 대해
다음 조건 중 하나가 적용되는 경우 비활성화 옵션을 사용합니다.

* 스냅샷 볼륨 또는 스냅샷 정합성 보장 그룹 스냅샷 볼륨 사용을 마쳤습니다.
* 나중에 스냅샷 볼륨 또는 스냅샷 정합성 보장 그룹 스냅샷 볼륨(읽기-쓰기로 지정됨)을 다시 생성하려고 하며 다시 생성할 필요가 없도록 관련 예약 용량을 유지하려는 경우
* 읽기-쓰기 스냅샷 볼륨에 대한 쓰기 작업을 중지하여 스토리지 시스템 성능을 높이려는 경우


스냅샷 볼륨 또는 스냅샷 정합성 보장 그룹 스냅샷 볼륨이 읽기/쓰기로 지정된 경우 이 옵션을 사용하여 연결된 예약된 용량 볼륨에 대한 추가 쓰기 작업을 중지할 수도 있습니다. 스냅샷 볼륨 또는 스냅샷 정합성 보장 그룹 스냅샷 볼륨을 다시 생성하려는 경우 동일한 기본 볼륨에서 스냅샷 이미지를 선택해야 합니다.

[NOTE]
====
스냅샷 볼륨 또는 스냅샷 정합성 보장 그룹 스냅샷 볼륨이 온라인 복제 관계의 일부인 경우 볼륨에 대해 Disable 옵션을 수행할 수 없습니다.

====
.단계
. 스토리지 [스냅샷] 메뉴를 선택합니다.
. Snapshot Volumes * 탭을 선택합니다.
+
System Manager는 스토리지 배열에 연결된 모든 스냅샷 볼륨을 표시합니다.

. 비활성화할 스냅샷 볼륨을 선택한 다음 메뉴(Uncommon Tasks[Disable])를 선택합니다.
. 작업을 수행할지 확인한 다음 * Disable * 을 클릭합니다.


.결과
* 스냅샷 볼륨은 기본 볼륨과 연결되어 있습니다.
* 스냅샷 볼륨은 WWN(World Wide Name)을 유지합니다.
* 읽기-쓰기일 경우 스냅샷 볼륨은 연결된 예약 용량을 유지합니다.
* 스냅샷 볼륨은 호스트 할당 및 액세스를 유지합니다. 그러나 읽기-쓰기 요청은 실패합니다.
* 스냅샷 볼륨과 스냅샷 이미지의 연결이 끊어집니다.

