---
permalink: sm-storage/faq-pools-volume-groups.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager에 대한 풀 및 볼륨 그룹 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 볼륨 그룹이란 무엇입니까?

볼륨 그룹은 공유 특성을 가진 볼륨의 컨테이너입니다. 볼륨 그룹의 용량과 RAID 레벨이 정의되어 있습니다. 볼륨 그룹을 사용하여 호스트에서 액세스할 수 있는 볼륨을 하나 이상 생성할 수 있습니다. 볼륨 그룹 또는 풀에서 볼륨을 생성합니다.



== 풀이란?

풀은 논리적으로 그룹화된 드라이브 집합입니다. 풀을 사용하여 호스트에서 액세스할 수 있는 볼륨을 하나 이상 생성할 수 있습니다. (풀 또는 볼륨 그룹에서 볼륨을 생성하는 경우)

관리자는 풀을 통해 각 호스트의 사용량을 모니터링하여 스토리지 공간이 부족해질 가능성이 있는지 확인하고 기존의 디스크 크기 조정 중단을 방지할 수 있습니다. 풀이 고갈될 경우 운영 중단 없이 풀에 드라이브를 추가할 수 있으며 용량 증가는 호스트에 투명합니다.

풀을 사용하면 균형 상태를 유지하기 위해 데이터가 자동으로 재배포됩니다. 풀 전체에 패리티 정보 및 여유 용량을 분산하여 풀의 모든 드라이브를 장애가 발생한 드라이브를 재구축하는 데 사용할 수 있습니다. 이 방식에서는 전용 핫 스페어 드라이브를 사용하지 않으며 풀 전체에 보존(스페어) 용량이 예약됩니다. 드라이브 장애가 발생하면 다른 드라이브의 세그먼트를 읽어서 데이터를 다시 생성합니다. 그런 다음 새 드라이브를 선택하여 장애 발생 드라이브에 있던 각 세그먼트를 작성함으로써 드라이브 전체의 데이터 분배를 유지합니다.



== 예약 용량이란?

예약된 용량은 스냅샷 이미지, 정합성 보장 그룹 구성원 볼륨 및 미러링된 쌍 볼륨과 같은 복제 서비스 개체에 대한 데이터를 저장하는 물리적으로 할당된 용량입니다.

복제 서비스 작업과 연결된 예약된 용량 볼륨은 풀 또는 볼륨 그룹에 상주합니다. 풀 또는 볼륨 그룹에서 예약된 용량을 생성합니다.



== FDE/FIPS 보안이란 무엇입니까?

FDE/FIPS 보안이란 읽기 중에 고유 암호화 키를 사용하여 데이터를 암호화하고 해독하는 동안 데이터를 보호하는 보안 가능 드라이브를 말합니다. 이러한 보안 가능 드라이브는 스토리지 어레이에서 물리적으로 제거된 드라이브의 데이터에 대한 무단 액세스를 방지합니다.

보안이 가능한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다. FIPS 드라이브는 인증 테스트를 거쳤습니다.

[NOTE]
====
FIPS 지원이 필요한 볼륨의 경우 FIPS 드라이브만 사용합니다. 볼륨 그룹 또는 풀에서 FIPS 및 FDE 드라이브를 혼합하면 모든 드라이브가 FDE 드라이브로 처리됩니다. 또한 FDE 드라이브는 All-FIPS 볼륨 그룹 또는 풀에서 스페어로 추가하거나 사용할 수 없습니다.

====


== 중복 검사란?

중복 검사는 풀 또는 볼륨 그룹의 볼륨에 있는 데이터가 일관되는지 여부를 확인합니다. 이중화 데이터는 풀 또는 볼륨 그룹의 드라이브 중 하나에 장애가 발생할 경우 교체 드라이브에 대한 정보를 빠르게 재구성하는 데 사용됩니다.

한 번에 하나의 풀 또는 볼륨 그룹에서만 이 검사를 수행할 수 있습니다. 볼륨 중복 검사는 다음 작업을 수행합니다.

* RAID 3 볼륨, RAID 5 볼륨 또는 RAID 6 볼륨의 데이터 블록을 검색한 다음 각 블록의 중복 정보를 확인합니다. (RAID 3은 명령줄 인터페이스를 사용하는 볼륨 그룹에만 할당할 수 있습니다.)
* RAID 1 미러링 드라이브의 데이터 블록을 비교합니다.
* 데이터가 컨트롤러 펌웨어와 일치하지 않는 것으로 확인되면 중복 오류를 반환합니다.


[NOTE]
====
동일한 풀 또는 볼륨 그룹에서 중복 검사를 즉시 실행하면 오류가 발생할 수 있습니다. 이 문제를 방지하려면 동일한 풀 또는 볼륨 그룹에서 다른 중복 검사를 실행하기 전에 1-2분 정도 기다리십시오.

====


== 풀과 볼륨 그룹의 차이점은 무엇입니까?

풀은 볼륨 그룹과 유사하며 다음과 같은 차이점이 있습니다.

* 풀의 데이터는 동일한 드라이브 세트에 저장되는 볼륨 그룹의 데이터와 달리 풀의 모든 드라이브에 무작위로 저장됩니다.
* 드라이브 장애가 발생할 경우 풀의 성능 저하가 줄어들고 재구성 시간이 단축됩니다.
* 풀에는 보존 용량이 내장되어 있으므로 전용 핫 스페어 드라이브가 필요하지 않습니다.
* 풀을 사용하면 많은 수의 드라이브를 그룹화할 수 있습니다.
* 풀은 지정된 RAID 레벨이 필요하지 않습니다.




== 풀을 수동으로 구성하는 이유는 무엇입니까?

다음 예에서는 풀을 수동으로 구성하려는 이유를 설명합니다.

* 스토리지 배열에 여러 애플리케이션이 있고 동일한 드라이브 리소스에 대해 경쟁하지 않으려는 경우 하나 이상의 애플리케이션에 대해 더 작은 풀을 수동으로 생성하는 것이 좋습니다.
+
데이터를 분산할 볼륨이 많은 대규모 풀에 워크로드를 할당하는 대신 하나 또는 두 개의 볼륨만 할당할 수 있습니다. 특정 애플리케이션의 워크로드 전용으로 별도의 풀을 수동으로 생성하면 스토리지 시스템의 운영 속도가 빨라질 수 있고 경합이 줄어듭니다.

+
풀을 수동으로 생성하려면 * 스토리지 * 를 선택한 다음 * 풀 및 볼륨 그룹 * 을 선택합니다. All Capacity 탭에서 Create [Pool] 메뉴를 클릭합니다.

* 동일한 드라이브 유형의 풀이 여러 개 있는 경우 System Manager에서 풀에 대한 드라이브를 자동으로 추천할 수 없다는 메시지가 나타납니다. 그러나 기존 풀에 드라이브를 수동으로 추가할 수 있습니다.
+
기존 풀에 드라이브를 수동으로 추가하려면 풀 및 볼륨 그룹 페이지에서 풀을 선택한 다음 * 용량 추가 * 를 클릭합니다.





== 용량 알림이 중요한 이유는 무엇입니까?

용량 알림은 풀에 드라이브를 추가할 시점을 나타냅니다. 스토리지 배열 작업을 성공적으로 수행하려면 풀에 충분한 가용 용량이 필요합니다. 풀의 사용 가능한 용량이 지정된 비율에 도달하거나 초과될 때 알림을 보내도록 SANtricity 시스템 관리자를 구성하여 이러한 작업이 중단되지 않도록 할 수 있습니다.

풀 자동 구성 * 옵션 또는 * 풀 생성 * 옵션을 사용하여 풀을 생성할 때 이 비율을 설정합니다. 자동 옵션을 선택하면 기본 설정에 따라 알림 수신 시기를 자동으로 결정합니다. 풀을 수동으로 생성하기로 선택한 경우 알림 알림 설정을 확인하거나, 원하는 경우 기본 설정을 적용할 수 있습니다. 이 설정은 나중에 메뉴에서 설정 [알림]을 조정할 수 있습니다.

[NOTE]
====
풀의 사용 가능한 용량이 지정된 비율에 도달하면 알림 구성에 지정된 방법을 사용하여 알림 알림이 전송됩니다.

====


== 왜 보존 용량을 늘릴 수 없나요?

사용 가능한 모든 용량에 볼륨을 생성한 경우 보존 용량을 늘릴 수 없습니다.

Preservation capacity는 잠재적 드라이브 장애를 지원하기 위해 풀에 예약된 용량(드라이브 수)입니다. 풀이 생성되면 시스템은 풀의 드라이브 수에 따라 기본 보존 용량을 자동으로 예약합니다. 사용 가능한 모든 용량에 볼륨을 생성한 경우 드라이브를 추가하거나 볼륨을 삭제하여 풀에 용량을 추가하지 않으면 보존 용량을 늘릴 수 없습니다.

풀 및 볼륨 그룹 * 에서 보존 용량을 변경할 수 있습니다. 편집할 풀을 선택합니다. 설정 보기/편집 * 을 클릭한 다음 * 설정 * 탭을 선택합니다.

[NOTE]
====
보존 용량은 풀의 드라이브에 실제 보존 용량이 분산되어 있더라도 여러 드라이브로 지정됩니다.

====


== 풀에서 제거할 수 있는 드라이브 수에 제한이 있습니까?

SANtricity System Manager는 풀에서 제거할 수 있는 드라이브 수에 대한 제한을 설정합니다.

* 풀의 드라이브 수를 11개 미만으로 줄일 수는 없습니다.
* 풀의 남은 드라이브에 데이터가 재분배될 때 제거된 드라이브의 데이터를 포함할 여유 용량이 충분하지 않으면 드라이브를 제거할 수 없습니다.
* 한 번에 최대 60개의 드라이브를 제거할 수 있습니다. 60개 이상의 드라이브를 선택하면 드라이브 제거 옵션이 비활성화됩니다. 60개 이상의 드라이브를 제거해야 하는 경우 드라이브 제거 작업을 반복합니다.




== 드라이브에 지원되는 미디어 유형은 무엇입니까?

지원되는 미디어 유형은 하드 디스크 드라이브(HDD) 및 솔리드 스테이트 디스크(SSD)입니다.



== 일부 드라이브가 표시되지 않는 이유는 무엇입니까?

Add Capacity 대화 상자에서 기존 풀 또는 볼륨 그룹에 용량을 추가하는 데 일부 드라이브를 사용할 수 없습니다.

드라이브는 다음과 같은 이유로 적합하지 않습니다.

* 드라이브를 할당하지 않고 안전하게 사용할 수 없어야 합니다. 다른 풀, 다른 볼륨 그룹에 이미 속해 있거나 핫 스페어로 구성된 드라이브는 사용할 수 없습니다. 드라이브 할당이 취소되었지만 보안이 설정된 경우 해당 드라이브를 수동으로 지워야 사용할 수 있습니다.
* 최적화되지 않은 상태의 드라이브는 해당되지 않습니다.
* 드라이브 용량이 너무 작으면 대상에서 제외됩니다.
* 드라이브 미디어 유형은 풀 또는 볼륨 그룹 내에서 일치해야 합니다. 다음을 혼합할 수 없습니다.
+
** 솔리드 스테이트 디스크(SSD)가 장착된 하드 디스크 드라이브(HDD)
** SAS 드라이브를 포함한 NVMe
** 512바이트 및 4KiB 볼륨 블록 크기의 드라이브


* 풀 또는 볼륨 그룹에 모든 보안 가능 드라이브가 포함되어 있는 경우 비보안 가능 드라이브가 표시되지 않습니다.
* 풀 또는 볼륨 그룹에 모든 FIPS(Federal Information Processing Standards) 드라이브가 포함되어 있는 경우 비 FIPS 드라이브가 나열되지 않습니다.
* 풀 또는 볼륨 그룹에 모든 DA(Data Assurance) 가능 드라이브가 포함되어 있고 풀 또는 볼륨 그룹에 하나 이상의 DA 지원 볼륨이 있는 경우, DA를 사용할 수 없는 드라이브는 사용할 수 없으므로 해당 풀 또는 볼륨 그룹에 추가할 수 없습니다. 그러나 풀 또는 볼륨 그룹에 DA 지원 볼륨이 없는 경우 DA를 사용할 수 없는 드라이브를 해당 풀 또는 볼륨 그룹에 추가할 수 있습니다. 이러한 드라이브를 혼합하려는 경우 DA 지원 볼륨을 생성할 수 없습니다.


[NOTE]
====
새 드라이브를 추가하거나 풀 또는 볼륨 그룹을 삭제하여 스토리지 시스템에서 용량을 늘릴 수 있습니다.

====


== 선반/서랍 손실 방지 기능을 어떻게 유지합니까?

풀 또는 볼륨 그룹에 대한 쉘프/드로어 손실 보호를 유지하려면 다음 표에 나와 있는 기준을 사용하십시오.

[cols="1a,1a,1a"]
|===
| 레벨 | 선반/서랍 손실 방지 기준 | 필요한 최소 쉘프/서랍 수 


 a| 
수영장
 a| 
쉘프의 경우 풀에는 단일 쉘프에 2개 이상의 드라이브가 없어야 합니다.

드로어의 경우 풀에는 각 드로어의 드라이브 수가 동일해야 합니다.
 a| 
선반용 6개

5 서랍용



 a| 
RAID 6
 a| 
볼륨 그룹은 단일 쉘프 또는 서랍에 2개 이상의 드라이브를 포함하지 않습니다.
 a| 
3



 a| 
RAID 3 또는 RAID 5
 a| 
볼륨 그룹의 각 드라이브는 별도의 쉘프 또는 드로어에 있습니다.
 a| 
3



 a| 
RAID 1
 a| 
미러링된 쌍의 각 드라이브는 별도의 쉘프 또는 드로어에 위치해야 합니다.
 a| 
2



 a| 
RAID 0
 a| 
선반/서랍 손실 방지를 달성할 수 없습니다.
 a| 
해당 없음

|===
[NOTE]
====
풀 또는 볼륨 그룹에서 드라이브가 이미 장애가 발생한 경우에는 쉘프/드로어 손실 보호가 유지되지 않습니다. 이 경우, 드라이브 쉘프 또는 드로어에 액세스하지 못하게 되고 결과적으로 풀 또는 볼륨 그룹의 다른 드라이브가 데이터 손실을 유발합니다.

====


== 풀 및 볼륨 그룹에 가장 적합한 드라이브 포지셔닝은 무엇입니까?

풀 및 볼륨 그룹을 생성할 때는 드라이브 선택 항목의 균형을 상단 및 하단 드라이브 슬롯 사이에서 조정해야 합니다.

EF600 및 EF300 컨트롤러의 경우 드라이브 슬롯 0-11은 하나의 PCI 브리지에 연결되고 슬롯 12-23은 다른 PCI 브리지에 연결됩니다. 최적의 성능을 얻으려면 드라이브 선택 항목의 균형을 조정하여 위쪽 및 아래쪽 슬롯의 드라이브 수가 대략적으로 같아야 합니다. 이러한 포지셔닝을 통해 볼륨이 필요한 것보다 더 빠르게 대역폭 제한을 넘지 않도록 할 수 있습니다.



== 애플리케이션에 가장 적합한 RAID 레벨은 무엇입니까?

볼륨 그룹의 성능을 최대화하려면 적절한 RAID 레벨을 선택해야 합니다. 볼륨 그룹에 액세스하는 응용 프로그램의 읽기 및 쓰기 비율을 알면 적절한 RAID 레벨을 결정할 수 있습니다. 성능 페이지를 사용하여 이러한 비율을 얻습니다.



=== RAID 레벨 및 애플리케이션 성능

RAID는 _levels_라는 일련의 구성을 사용하여 드라이브에서 사용자 및 중복 데이터를 기록하고 검색하는 방법을 결정합니다. 각 RAID 레벨은 서로 다른 성능 기능을 제공합니다. RAID 5 및 RAID 6 구성의 탁월한 읽기 성능 때문에 읽기 비율이 높은 응용 프로그램은 RAID 5 볼륨 또는 RAID 6 볼륨을 사용하여 잘 수행됩니다.

읽기 백분율(쓰기 집약적)이 낮은 응용 프로그램은 RAID 5 볼륨 또는 RAID 6 볼륨에서 제대로 작동하지 않습니다. 성능 저하는 컨트롤러가 RAID 5 볼륨 그룹 또는 RAID 6 볼륨 그룹의 드라이브에 데이터 및 중복 데이터를 기록하는 방식으로 인해 발생합니다.

다음 정보를 기반으로 RAID 레벨을 선택합니다.

* RAID 0 *

* * 설명 *
+
** 비중복, 스트라이핑 모드


* * 작동 방식 *
+
** RAID 0은 볼륨 그룹의 모든 드라이브에 데이터를 스트라이핑합니다.


* * 데이터 보호 기능 *
+
** 고가용성 요구 사항에 대해서는 RAID 0을 권장하지 않습니다. RAID 0은 중요하지 않은 데이터에 적합합니다.
** 볼륨 그룹에서 단일 드라이브에 장애가 발생하면 연결된 모든 볼륨이 실패하고 모든 데이터가 손실됩니다.


* * 드라이브 번호 요구 사항 *
+
** RAID 레벨 0에는 최소 하나의 드라이브가 필요합니다.
** RAID 0 볼륨 그룹은 30개 이상의 드라이브를 가질 수 있습니다.
** 스토리지 배열의 모든 드라이브를 포함하는 볼륨 그룹을 생성할 수 있습니다.




* RAID 1 또는 RAID 10 *

* * 설명 *
+
** 스트라이핑/미러 모드


* * 작동 방식 *
+
** RAID 1은 디스크 미러링을 사용하여 두 개의 중복 디스크에 동시에 데이터를 씁니다.
** RAID 10은 드라이브 스트라이핑을 사용하여 미러링된 드라이브 쌍의 집합에 걸쳐 데이터를 스트라이핑합니다.


* * 데이터 보호 기능 *
+
** RAID 1 및 RAID 10은 고성능과 최상의 데이터 가용성을 제공합니다.
** RAID 1 및 RAID 10은 드라이브 미러링을 사용하여 한 드라이브에서 다른 드라이브로 정확하게 복사합니다.
** 드라이브 쌍의 드라이브 중 하나에 장애가 발생하면 스토리지 어레이가 데이터 또는 서비스의 손실 없이 다른 드라이브로 즉시 전환할 수 있습니다.
** 단일 드라이브 장애로 인해 관련 볼륨의 성능이 저하됩니다. 미러 드라이브를 통해 데이터에 액세스할 수 있습니다.
** 볼륨 그룹의 드라이브 쌍 장애로 인해 연결된 모든 볼륨이 장애가 발생하고 데이터 손실이 발생할 수 있습니다.


* * 드라이브 번호 요구 사항 *
+
** RAID 1에는 사용자 데이터용 드라이브 1개와 미러링된 데이터용 드라이브 1개 등 최소 2개의 드라이브가 필요합니다.
** 드라이브를 4개 이상 선택하면 사용자 데이터를 위한 드라이브 2개와 미러링된 데이터를 위한 드라이브 2개 등 RAID 10이 볼륨 그룹 전체에 자동으로 구성됩니다.
** 볼륨 그룹에 짝수의 드라이브가 있어야 합니다. 드라이브 수가 짝수이고 할당되지 않은 드라이브가 일부 있는 경우 * Pools & Volume Groups * 로 이동하여 볼륨 그룹에 드라이브를 추가하고 작업을 재시도하십시오.
** RAID 1 및 RAID 10 볼륨 그룹은 30개 이상의 드라이브를 가질 수 있습니다. 스토리지 배열의 모든 드라이브를 포함하는 볼륨 그룹을 생성할 수 있습니다.




* RAID 5 *

* * 설명 *
+
** 높은 I/O 모드.


* * 작동 방식 *
+
** 사용자 데이터 및 중복 정보(패리티)는 드라이브에 스트라이핑됩니다.
** 하나의 드라이브에 해당하는 용량이 중복 정보에 사용됩니다.


* * 데이터 보호 기능 *
+
** RAID 5 볼륨 그룹에서 단일 드라이브에 장애가 발생하면 연결된 모든 볼륨의 성능이 저하됩니다. 중복 정보를 통해 데이터에 계속 액세스할 수 있습니다.
** RAID 5 볼륨 그룹에서 두 개 이상의 드라이브에 장애가 발생하면 연결된 모든 볼륨에 장애가 발생하고 모든 데이터가 손실됩니다.


* * 드라이브 번호 요구 사항 *
+
** 볼륨 그룹에 최소 3개의 드라이브가 있어야 합니다.
** 일반적으로 볼륨 그룹에서 최대 30개의 드라이브로 제한됩니다.




* RAID 6 *

* * 설명 *
+
** 높은 I/O 모드.


* * 작동 방식 *
+
** 사용자 데이터 및 중복 정보(이중 패리티)는 드라이브에 스트라이핑됩니다.
** 두 드라이브의 동일한 용량이 중복 정보에 사용됩니다.


* * 데이터 보호 기능 *
+
** RAID 6 볼륨 그룹에서 하나 또는 두 개의 드라이브에 장애가 발생하면 연결된 모든 볼륨의 성능이 저하되지만 중복 정보를 통해 데이터에 계속 액세스할 수 있습니다.
** RAID 6 볼륨 그룹에서 3개 이상의 드라이브에 장애가 발생하면 연결된 모든 볼륨에 장애가 발생하고 모든 데이터가 손실됩니다.


* * 드라이브 번호 요구 사항 *
+
** 볼륨 그룹에 최소 5개의 드라이브가 있어야 합니다.
** 일반적으로 볼륨 그룹에서 최대 30개의 드라이브로 제한됩니다.




[NOTE]
====
풀의 RAID 레벨은 변경할 수 없습니다. 사용자 인터페이스는 풀을 RAID 6으로 자동 구성합니다.

====


=== RAID 레벨 및 데이터 보호

RAID 1, RAID 5 및 RAID 6은 드라이브 미디어에 중복 데이터를 기록하여 내결함성을 제공합니다. 중복 데이터는 데이터 사본(미러링)이거나 데이터에서 파생된 오류 정정 코드일 수 있습니다. 드라이브 장애가 발생할 경우 중복 데이터를 사용하여 교체 드라이브에 대한 정보를 빠르게 재구성할 수 있습니다.

단일 볼륨 그룹에서 단일 RAID 레벨을 구성합니다. 해당 볼륨 그룹의 모든 중복 데이터는 볼륨 그룹 내에 저장됩니다. 볼륨 그룹의 용량은 구성원 드라이브의 총 용량에서 중복 데이터를 위해 예약된 용량을 뺀 값입니다. 중복성에 필요한 용량은 사용된 RAID 레벨에 따라 다릅니다.



== Data Assurance란 무엇입니까?

DA(Data Assurance)는 T10 PI(보호 정보) 표준을 구현하여 I/O 경로를 통해 데이터가 전송될 때 발생할 수 있는 오류를 확인하고 수정하여 데이터 무결성을 향상합니다.

일반적으로 Data Assurance 기능을 사용하면 컨트롤러와 드라이브 사이의 입출력 경로 부분을 확인할 수 있습니다. DA 기능은 풀 및 볼륨 그룹 레벨에서 제공됩니다.

이 기능을 활성화하면 스토리지 배열은 볼륨의 각 데이터 블록에 오류 검사 코드(순환 중복 검사 또는 CRC라고도 함)를 추가합니다. 데이터 블록이 이동된 후 스토리지 배열은 이러한 CRC 코드를 사용하여 전송 중에 오류가 발생했는지 확인합니다. 잠재적으로 손상된 데이터는 디스크에 기록되거나 호스트에 반환되지 않습니다. DA 기능을 사용하려면 새 볼륨을 생성할 때 DA를 지원하는 풀 또는 볼륨 그룹을 선택합니다(풀 및 볼륨 그룹 후보 테이블에서 "DA" 옆에 있는 "예"를 확인합니다).

DA가 가능한 입출력 인터페이스를 사용하여 이러한 DA 지원 볼륨을 호스트에 할당해야 합니다. DA를 지원할 수 있는 I/O 인터페이스로는 파이버 채널, SAS, iSCSI over TCP/IP, NVMe/FC, NVMe/IB, InfiniBand를 통한 NVMe/RoCE 및 iSER(RDMA/IB용 iSCSI 확장) DA는 InfiniBand를 통한 SRP에서 지원되지 않습니다.



== 보안 기능(드라이브 보안)이란 무엇입니까?

드라이브 보안은 스토리지 어레이에서 제거할 때 보안이 설정된 드라이브의 데이터에 대한 무단 액세스를 방지하는 기능입니다. 이러한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다.



== 예약된 용량 증가에 대해 알아야 할 사항은 무엇입니까?

일반적으로 예약된 용량이 가득 찰 위험이 있다는 경고가 나타나면 용량을 늘려야 합니다. 예약 용량은 8GiB의 증분으로 늘릴 수 있습니다.

* 필요한 경우 확장할 수 있도록 풀 또는 볼륨 그룹에 충분한 가용 용량이 있어야 합니다.
+
풀 또는 볼륨 그룹에 사용 가능한 용량이 없는 경우, 할당되지 않은 용량을 미사용 드라이브 형식으로 풀 또는 볼륨 그룹에 추가할 수 있습니다.

* 풀 또는 볼륨 그룹의 볼륨은 최적 상태여야 하며 수정 상태가 아니어야 합니다.
* 용량을 늘리기 위해 사용할 풀 또는 볼륨 그룹에 사용 가능한 용량이 있어야 합니다.
* 읽기 전용인 스냅샷 볼륨에 대해 예약된 용량을 늘릴 수 없습니다. 읽기-쓰기의 스냅샷 볼륨에만 예약된 용량이 필요합니다.


스냅샷 작업의 경우 예약된 용량은 일반적으로 기본 볼륨의 40%입니다. 비동기식 미러링 작업의 경우 예약된 용량은 일반적으로 기본 볼륨의 20%입니다. 기본 볼륨에 많은 변경이 있을 것으로 예상되거나 스토리지 오브젝트의 복사 서비스 작업 예상 수명이 매우 길 경우 더 높은 비율을 사용하십시오.



== 왜 감소시킬 금액을 더 선택할 수 없나요?

예약된 용량을 늘리기 위해 사용한 양으로만 줄일 수 있습니다. 구성원 볼륨에 대해 예약된 용량은 추가된 역순으로 제거할 수 있습니다.

다음 조건 중 하나가 존재할 경우 스토리지 객체에 대한 예약 용량을 줄일 수 없습니다.

* 스토리지 객체가 미러링된 페어 볼륨인 경우
* 스토리지 객체에 예약된 용량에 대해 하나의 볼륨만 포함된 경우 스토리지 객체에는 예약된 용량을 위한 볼륨이 2개 이상 있어야 합니다.
* 스토리지 객체가 비활성화된 스냅샷 볼륨인 경우
* 스토리지 객체에 하나 이상의 연결된 스냅샷 이미지가 포함되어 있는 경우


예약된 용량에 대한 볼륨은 추가된 역순으로 제거할 수 있습니다.

연결된 예약 용량이 없기 때문에 읽기 전용인 스냅샷 볼륨에 대해 예약된 용량을 줄일 수 없습니다. 읽기-쓰기의 스냅샷 볼륨에만 예약된 용량이 필요합니다.



== 각 구성원 볼륨에 대해 예약된 용량이 필요한 이유는 무엇입니까?

스냅샷 정합성 보장 그룹의 각 구성원 볼륨은 호스트 애플리케이션이 수정한 내용을 참조된 정합성 보장 그룹 스냅샷 이미지에 영향을 주지 않고 기본 볼륨에 저장하려면 고유한 예약 용량을 가져야 합니다. 예약된 용량은 읽기-쓰기로 지정된 구성원 볼륨에 포함된 데이터의 복제본에 대한 쓰기 액세스 권한을 호스트 애플리케이션에 제공합니다.

정합성 보장 그룹 스냅샷 이미지는 호스트에서 직접 읽거나 쓸 수 없습니다. 대신, 스냅샷 이미지는 기본 볼륨에서 캡처된 데이터만 저장하는 데 사용됩니다.

읽기-쓰기로 지정된 일관성 그룹 스냅샷 볼륨을 생성하는 동안 System Manager는 일관성 그룹의 각 구성원 볼륨에 대해 예약된 용량을 생성합니다. 이 예약된 용량은 호스트 애플리케이션에서 정합성 보장 그룹 스냅샷 이미지에 포함된 데이터 복제본에 대한 쓰기 액세스를 제공합니다.



== 모든 SSD Cache 통계를 보고 해석하려면 어떻게 해야 합니까?

SSD Cache에 대한 공칭 통계 및 세부 통계를 볼 수 있습니다. 공칭 통계는 상세 통계의 하위 집합입니다.

모든 SSD 통계를 '.csv' 파일로 내보낼 때만 상세 통계를 볼 수 있습니다. 통계를 검토 및 해석할 때는 통계의 조합을 통해 일부 해석이 파생된다는 점을 염두에 두십시오.



=== 공칭 통계

SSD Cache 통계를 보려면 스토리지 [풀 및 볼륨 그룹] 메뉴를 선택합니다. 통계를 보려는 SSD Cache를 선택한 다음 menu:More [View Statistics](추가 [통계 보기])를 선택합니다. 공칭 통계는 SSD 캐시 통계 보기 대화 상자에 표시됩니다.

다음 목록에는 상세 통계의 하위 집합인 공칭 통계가 나와 있습니다.

[cols="25h,~"]
|===
| 공칭 통계 | 설명 


 a| 
읽기/쓰기
 a| 
SSD Cache 지원 볼륨에서 또는 호스트에서 데이터를 쓸 수 있는 총 호스트 읽기 수입니다. 쓰기에 상대적인 읽기를 비교합니다. 유효 SSD 캐시 작업을 위해서는 읽기 작업이 쓰기 보다 커야 합니다. 읽기-쓰기의 비율이 클수록 캐시 작업이 향상됩니다.



 a| 
캐시 적중 횟수
 a| 
캐시 적중 횟수



 a| 
캐시 적중 횟수(%)
 a| 
캐시 적중 횟수/(읽기+쓰기)에서 파생됩니다. 유효 SSD 캐시 작업의 캐시 적중률은 50%보다 커야 합니다. 작은 숫자는 다음과 같은 몇 가지 사항을 나타낼 수 있습니다.

* 읽기-쓰기의 비율이 너무 작습니다
* 읽기는 반복되지 않습니다
* 캐시 용량이 너무 작습니다




 a| 
캐시 할당(%)
 a| 
할당된 SSD Cache 스토리지의 양으로, 이 컨트롤러에서 사용할 수 있는 SSD Cache 스토리지의 백분율로 표시됩니다. 할당된 바이트/사용 가능한 바이트에서 파생됩니다. 캐시 할당 비율은 일반적으로 100%로 표시됩니다. 이 수치가 100% 미만일 경우 캐시가 워밍업되지 않았거나 SSD Cache 용량이 액세스하는 모든 데이터에 비해 크기 초과임을 의미합니다. 후자의 경우, SSD Cache 용량이 작으면 동일한 수준의 성능을 제공할 수 있습니다. 이는 캐싱된 데이터가 SSD Cache에 배치되었음을 나타내는 것이 아니라 SSD Cache에 데이터를 저장하기 위한 준비 단계일 뿐입니다.



 a| 
캐시 활용률(%)
 a| 
SSD Cache 스토리지에 할당된 SSD Cache 스토리지의 백분율로, 활성화된 볼륨의 데이터가 포함된 SSD Cache 스토리지의 양입니다. 이 값은 사용자 데이터 바이트/할당된 바이트에서 파생된 SSD Cache의 사용률 또는 밀도를 나타냅니다. 일반적으로 캐시 활용률 백분율은 100%보다 낮으며, 이보다 훨씬 낮을 수 있습니다. 이 수치는 캐시 데이터로 채워진 SSD Cache 용량의 비율을 나타냅니다. SSD Cache의 각 할당 유닛인 SSD Cache 블록이 약간 독립적인 서브블록이라는 작은 유닛으로 분리되기 때문에 이 수치는 100%보다 낮습니다. 일반적으로 숫자가 클수록 좋지만 숫자가 적더라도 성능이 크게 향상될 수 있습니다.

|===


=== 자세한 통계

세부 통계는 공칭 통계와 추가 통계로 구성됩니다. 이러한 추가 통계는 공칭 통계와 함께 저장되지만, 공칭 통계와 달리 SSD 캐시 통계 보기 대화 상자에 표시되지 않습니다. 통계를 '.csv' 파일로 내보낸 후에만 상세 통계를 볼 수 있습니다.

'.csv' 파일을 볼 때, 공칭 통계 다음에 상세 통계가 나열된다는 것을 주의하시오.

[cols="25h,~"]
|===
| 자세한 통계 | 설명 


 a| 
블럭 읽기
 a| 
호스트 읽기의 블록 수입니다.



 a| 
블럭 쓰기
 a| 
호스트 쓰기의 블록 수입니다.



 a| 
전체 적중 블록
 a| 
캐시 적중의 블록 수입니다. 전체 적중 블록은 SSD Cache에서 완전히 읽은 블록 수를 나타냅니다. SSD Cache는 전체 캐시 적중률이 높은 작업의 성능에만 도움이 됩니다.



 a| 
부분 조회수
 a| 
SSD Cache에서 하나 이상의 블록이 있지만 모든 블록이 있는 호스트 읽기 수입니다. 부분 적중은 기본 볼륨에서 읽기가 처리된 SSD Cache * Miss * 입니다.



 a| 
부분 조회수 - 블록
 a| 
부분 조회수(Partial Hits)의 블록 수입니다. 부분 캐시 적중 및 부분 캐시 적중 블록은 SSD Cache에 일부 데이터만 있는 작업으로 인해 발생합니다. 이 경우 작업은 캐시된 하드 디스크 드라이브(HDD) 볼륨에서 데이터를 받아야 합니다. SSD Cache는 이러한 유형의 적중에는 성능 이점이 없습니다. 부분 캐시 적중 블록 수가 전체 캐시 적중 블록보다 많을 경우 다른 I/O 특성 유형(파일 시스템, 데이터베이스 또는 웹 서버)을 사용하면 성능이 향상될 수 있습니다. SSD 캐시가 워밍업 중일 때는 캐시 적중 횟수와 비교하여 부분 적중 횟수 및 실패 횟수가 더 많은 것으로 예상됩니다.



 a| 
실패
 a| 
SSD Cache에 블록이 없는 호스트 읽기 수입니다. SSD Cache 누락은 기본 볼륨에서 읽기가 만족스러우면 발생합니다. SSD 캐시가 워밍업 중일 때는 캐시 적중 횟수와 비교하여 부분 적중 횟수 및 실패 횟수가 더 많은 것으로 예상됩니다.



 a| 
비적중 - 블록
 a| 
비적중 블록 수입니다.



 a| 
작업 채우기(호스트 읽기)
 a| 
기본 볼륨에서 SSD Cache로 데이터가 복사된 호스트 읽기 수입니다.



 a| 
작업 채우기(호스트 읽기) - 블록
 a| 
작업 채우기(호스트 읽기)의 블록 수입니다.



 a| 
작업 채우기(호스트 쓰기)
 a| 
기본 볼륨에서 SSD Cache로 데이터가 복사된 호스트 쓰기 수입니다. 쓰기 입출력 작업의 결과로 캐시를 채우지 않는 캐시 구성 설정의 경우 작업 채우기(호스트 쓰기) 수가 0일 수 있습니다.



 a| 
작업 채우기(호스트 쓰기) - 블록
 a| 
작업 채우기(호스트 쓰기)의 블록 수입니다.



 a| 
작업을 무효화합니다
 a| 
데이터가 SSD Cache에서 무효화되거나 제거된 횟수입니다. 캐시 무효화 작업은 각 호스트 쓰기 요청, FUA(Forced Unit Access)가 포함된 각 호스트 읽기 요청, 각 확인 요청 및 기타 일부 상황에 대해 수행됩니다.



 a| 
작업 재활용
 a| 
SSD Cache 블록이 다른 기본 볼륨 및/또는 다른 LBA(논리 블록 주소 지정) 범위에 다시 사용된 횟수 효과적인 캐시 작업을 위해서는 읽기 및 쓰기 작업의 조합 수에 비해 재활용 횟수가 적어야 합니다. 재활용 작업 수가 결합된 읽기 및 쓰기 수에 근접하면 SSD 캐시는 스래싱(thrashing)입니다. 캐시 용량을 늘려야 하거나 워크로드를 SSD Cache와 함께 사용하는 것이 적합하지 않습니다.



 a| 
사용 가능한 바이트
 a| 
이 컨트롤러에서 SSD Cache에서 사용할 수 있는 바이트 수입니다.



 a| 
할당된 바이트
 a| 
이 컨트롤러가 SSD Cache에서 할당한 바이트 수입니다. SSD Cache에서 할당된 바이트가 비어 있거나 기본 볼륨의 데이터가 포함되어 있을 수 있습니다.



 a| 
사용자 데이터 바이트
 a| 
SSD Cache에서 기본 볼륨의 데이터를 포함하는 할당된 바이트 수입니다. 사용 가능한 바이트, 할당된 바이트 및 사용자 데이터 바이트는 캐시 할당 백분율 및 캐시 사용률 비율을 계산하는 데 사용됩니다.

|===


== 풀의 최적화 용량은 얼마입니까?

SSD 드라이브는 용량의 일부가 할당되지 않은 경우 수명이 더 길고 쓰기 성능이 극대화됩니다.

풀과 연결된 드라이브의 경우 할당되지 않은 용량은 풀의 보존 용량, 사용 가능한 용량(볼륨에서 사용하지 않는 용량), 추가 최적화 용량으로 남겨 둔 사용 가능한 용량의 일부로 구성됩니다. 추가 최적화 용량은 사용 가능한 용량을 줄여 최적화 용량을 최소화하므로 볼륨 생성에 사용할 수 없습니다.

풀을 생성할 때 성능, 드라이브 마모 수명 및 가용 용량의 균형을 제공하는 권장 최적화 용량이 생성됩니다. Pool Settings(풀 설정) 대화 상자에 있는 Additional Optimization Capacity(추가 최적화 용량) 슬라이더를 사용하여 풀의 최적화 용량을 조정할 수 있습니다. 슬라이더를 조정하면 사용 가능한 용량을 희생하여 더 나은 성능과 드라이브 마모 수명을 얻을 수 있고, 성능과 드라이브 마모 수명을 희생하여 사용 가능한 추가 용량을 확보할 수 있습니다.

[NOTE]
====
추가 최적화 용량 슬라이더는 EF600 및 EF300 스토리지 시스템에서만 사용할 수 있습니다.

====


== 볼륨 그룹의 최적화 용량은 무엇입니까?

SSD 드라이브는 용량의 일부가 할당되지 않은 경우 수명이 더 길고 쓰기 성능이 극대화됩니다.

볼륨 그룹과 연결된 드라이브의 경우 할당되지 않은 용량은 볼륨 그룹의 여유 용량(볼륨에서 사용하지 않는 용량)과 최적화 용량으로 남겨 둔 사용 가능한 용량의 일부로 구성됩니다. 추가 최적화 용량은 사용 가능한 용량을 줄여 최적화 용량을 최소화하므로 볼륨 생성에 사용할 수 없습니다.

볼륨 그룹이 생성되면 성능, 드라이브 마모 수명 및 가용 용량의 균형을 제공하는 권장 최적화 용량이 생성됩니다. 볼륨 그룹 설정 대화 상자의 추가 최적화 용량 슬라이더를 사용하여 볼륨 그룹의 최적화 용량을 조정할 수 있습니다. 슬라이더를 조정하면 사용 가능한 용량을 희생하여 더 나은 성능과 드라이브 마모 수명을 얻을 수 있고, 성능과 드라이브 마모 수명을 희생하여 사용 가능한 추가 용량을 확보할 수 있습니다.

[NOTE]
====
추가 최적화 용량 슬라이더는 EF600 및 EF300 스토리지 시스템에서만 사용할 수 있습니다.

====


== 리소스 프로비저닝 기능은 무엇입니까?

리소스 프로비저닝은 EF300 및 EF600 스토리지 어레이에서 사용 가능한 기능으로, 백그라운드 초기화 프로세스 없이 볼륨을 즉시 사용할 수 있도록 지원합니다.

리소스 프로비저닝된 볼륨은 SSD 볼륨 그룹 또는 풀의 일반 볼륨으로, 볼륨이 생성될 때 드라이브 용량이 할당되지만 드라이브 블록이 할당 해제(매핑 해제)됩니다. 이에 비해 기존의 일반 볼륨에서는 Data Assurance 보호 정보 필드를 초기화하고 각 RAID 스트라이프에서 데이터 및 RAID 패리티를 일관되게 만들기 위해 백그라운드 볼륨 초기화 작업 중에 모든 드라이브 블록이 매핑되거나 할당됩니다. 리소스 프로비저닝된 볼륨에서는 시간 제한이 없는 백그라운드 초기화가 없습니다. 대신 각 RAID 스트라이프는 스트라이프의 볼륨 블록에 처음으로 쓸 때 초기화됩니다.

리소스 프로비저닝된 볼륨은 SSD 볼륨 그룹 및 풀에서만 지원되며, 그룹 또는 풀의 모든 드라이브에서 DULBE(Logical Block Error Enable) 오류 복구 기능을 지원합니다. 리소스 프로비저닝된 볼륨이 생성되면 볼륨에 할당된 모든 드라이브 블록의 할당 해제(매핑 해제)가 발생합니다. 또한 호스트는 NVMe 데이터 세트 관리 명령 또는 SCSI Unmap 명령을 사용하여 볼륨에서 논리적 블록을 할당 해제할 수 있습니다. 블록을 할당 해제하면 SSD 마모 수명을 개선하고 최대 쓰기 성능을 높일 수 있습니다. 개선 정도는 드라이브 모델 및 용량에 따라 다릅니다.


NOTE: 현재 EF300C 또는 EF600C 스토리지 어레이에서는 DULBE가 지원되지 않습니다.



== 리소스 프로비저닝된 볼륨 기능에 대해 알아야 할 내용은 무엇입니까?

리소스 프로비저닝은 EF300 및 EF600 스토리지 어레이에서 사용 가능한 기능으로, 백그라운드 초기화 프로세스 없이 볼륨을 즉시 사용할 수 있도록 지원합니다.

리소스 프로비저닝된 볼륨은 SSD 볼륨 그룹 또는 풀의 일반 볼륨으로, 볼륨이 생성될 때 드라이브 용량이 할당되지만 드라이브 블록이 할당 해제(매핑 해제)됩니다. 이에 비해 기존의 일반 볼륨에서는 Data Assurance 보호 정보 필드를 초기화하고 각 RAID 스트라이프에서 데이터 및 RAID 패리티를 일관되게 만들기 위해 백그라운드 볼륨 초기화 작업 중에 모든 드라이브 블록이 매핑되거나 할당됩니다. 리소스 프로비저닝된 볼륨에서는 시간 제한이 없는 백그라운드 초기화가 없습니다. 대신 각 RAID 스트라이프는 스트라이프의 볼륨 블록에 처음으로 쓸 때 초기화됩니다.

리소스 프로비저닝된 볼륨은 SSD 볼륨 그룹 및 풀에서만 지원되며, 그룹 또는 풀의 모든 드라이브에서 DULBE(Logical Block Error Enable) 오류 복구 기능을 지원합니다. 리소스 프로비저닝된 볼륨이 생성되면 볼륨에 할당된 모든 드라이브 블록의 할당 해제(매핑 해제)가 발생합니다. 또한 호스트는 NVMe 데이터 세트 관리 명령 또는 SCSI Unmap 명령을 사용하여 볼륨에서 논리적 블록을 할당 해제할 수 있습니다. 블록을 할당 해제하면 SSD 마모 수명을 개선하고 최대 쓰기 성능을 높일 수 있습니다. 개선 정도는 드라이브 모델 및 용량에 따라 다릅니다.

드라이브가 DULBE를 지원하는 시스템에서는 리소스 프로비저닝이 기본적으로 사용됩니다. 풀 및 볼륨 그룹 * 에서 기본 설정을 비활성화할 수 있습니다.


NOTE: 현재 EF300C 또는 EF600C 스토리지 어레이에서는 DULBE가 지원되지 않습니다.
