---
permalink: sm-storage/faq-remote-storage.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager에 대한 원격 스토리지 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 원격 스토리지 접속을 생성하기 전에 알아야 할 사항은 무엇입니까?

원격 스토리지 기능을 구성하려면 iSCSI를 통해 원격 디바이스 및 타겟 스토리지 시스템을 직접 연결해야 합니다.

iSCSI 시스템 연결을 설정하려면 다음을 참조하십시오.

* link:../sm-hardware/configure-iscsi-ports-hardware.html["iSCSI 포트를 구성합니다"]
* https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["원격 스토리지 기술 보고서"^]




== 원격 볼륨을 제거하라는 메시지가 표시되는 이유는 무엇입니까?

최대 원격 볼륨 수에 도달하면 스토리지 시스템이 사용되지 않는 원격 볼륨을 자동으로 감지하여 제거하라는 메시지를 표시합니다.

생성 프로세스 중에 사용되지 않는 원격 볼륨이 정리되지 않는 경우가 있습니다. 추가 가져오기 작업을 시작하기 전에 시스템이 최적이고 네트워크 연결이 안정적인지 확인하십시오.



== 대상 어레이에서 모든 볼륨이 보이지 않는 이유는 무엇입니까?

원격 스토리지 기능에 대한 가져오기를 구성할 때 블록 크기, 용량 또는 볼륨 가용성 때문에 일부 볼륨이 대상 후보 목록에 나타나지 않을 수 있습니다.

목록에 표시하려면 볼륨 후보:

* 원격 볼륨과 같거나 큰 용량입니다.
* 원격 볼륨과 동일한 블록 크기
* 현재 최적 상태입니다.


다음과 같은 경우 목록에서 볼륨 후보가 제외됩니다.

* 볼륨 복사본, 스냅샷 또는 미러링과 같은 모든 관계
* 재구성 작업이 진행 중입니다.
* 다른 디바이스(호스트 또는 호스트 클러스터)에 매핑
* 읽기 플래시 캐시가 설정되었습니다.




== 가져오기 시 원격 볼륨에 대해 알아야 할 사항은 무엇입니까?

원격 스토리지 기능을 사용할 때는 원격 볼륨이 데이터를 가져온 소스라는 점에 유의해야 합니다.

가져오기가 진행 중이면 데이터가 원격 볼륨에서 대상 스토리지 시스템의 타겟 볼륨으로 전송됩니다. 이러한 두 볼륨의 블록 크기가 일치해야 합니다.



== 원격 스토리지 가져오기를 시작하기 전에 알아야 할 내용은 무엇입니까?

원격 스토리지 기능을 사용하면 원격 스토리지 시스템의 데이터를 로컬 E-Series 스토리지 시스템의 볼륨으로 복사할 수 있습니다. 이 기능을 사용하기 전에 다음 지침을 검토하십시오.



=== 구성

원격 스토리지 가져오기를 생성하기 전에 다음 작업을 완료하고 다음 조건을 확인해야 합니다.

* 로컬 E-Series 스토리지 시스템의 각 컨트롤러에 원격 스토리지 시스템에 대한 iSCSI 연결이 있는지 확인합니다.
* 로컬 E-Series 스토리지 시스템에서 가져오기 작업을 위한 타겟 볼륨을 생성합니다. 볼륨에 소스 볼륨과 같거나 큰 용량이 있고, 소스 볼륨과 일치하는 블록 크기가 있으며, 매핑되지 않았는지 확인합니다. 을 참조하십시오 link:create-volumes.html["볼륨 생성"].
* IQN(iSCSI Qualified Name)을 사용하여 원격 시스템에서 로컬 E-Series 스토리지 시스템을 호스트로 설정합니다. 설정 [시스템 > iSCSI 설정 > 대상 IQN] 메뉴에서 IQN을 볼 수 있습니다. 또한 사용 중인 시스템에 따라 적절한 호스트 유형을 설정해야 합니다.
* 모든 입출력을 중지하고, 파일 시스템을 마운트 해제하고, 원격 스토리지 시스템에서 선택한 볼륨에 대한 호스트 또는 애플리케이션에 대한 할당을 제거합니다.
* 원격 스토리지 시스템에 볼륨을 새로 생성한 로컬 E-Series 스토리지 시스템 호스트에 할당합니다.
* 가져오기를 생성할 수 있도록 원격 스토리지 시스템에서 다음 정보를 수집합니다.
+
** IQN(iSCSI Qualified Name)
** iSCSI IP 주소입니다
** 소스 데이터가 생성되는 원격 스토리지 디바이스의 LUN 번호입니다


* 가져오기 프로세스가 시작되면 전체 로컬 대상 볼륨을 복사된 데이터로 덮어씁니다. 로컬 대상 볼륨에 기록된 새 데이터는 가져오기가 생성된 후 원격 스토리지 장치의 볼륨에 전파됩니다. 따라서 가져오기 프로세스를 시작하기 전에 원격 스토리지 시스템의 볼륨을 백업하는 것이 좋습니다.




=== 가져오기 프로세스

다음 단계에서는 가져오기 프로세스를 간략하게 설명합니다.

. System Manager 인터페이스에 액세스한 다음 * 원격 스토리지 * 페이지로 이동합니다. 가져오기 * 를 선택하여 새 가져오기 생성을 시작합니다. 자세한 지침은 을 참조하십시오 link:rtv-import-remote-storage.html["원격 저장소 가져오기"].
+
오프라인 가져오기를 수행하려면 가져오기가 완료될 때까지 대상 볼륨을 매핑하지 마십시오.

. 가져오기 진행률을 모니터링합니다.
+
가져오기가 시작되면 타겟 볼륨을 매핑할 수 있습니다. 가져오기 작업을 완료하는 데 필요한 시간은 원격 스토리지 디바이스(소스 볼륨) 크기, 가져오기의 우선 순위 설정, 스토리지 시스템과 관련 볼륨 모두의 입출력 로드 양에 따라 달라집니다.

+
가져오기 완료 후 타겟 볼륨은 소스의 중복입니다.

. 매핑 관계를 끊을 준비가 되면 * Operations in Progress * 패널에서 가져오기 개체에 대해 * Disconnect * 를 수행합니다.


가져오기의 연결이 끊기면 로컬 대상의 성능이 정상으로 되돌아가고 원격 연결의 영향을 더 이상 받지 않습니다.



=== 제한 사항

원격 스토리지 기능에는 다음과 같은 제한 사항이 있습니다.

* 미러링이 비활성화되어야 합니다.
* E-Series 시스템의 타겟 볼륨에 스냅샷이 없어야 합니다.
* 가져오기를 시작하기 전에 E-Series 시스템의 타겟 볼륨을 호스트에 매핑해서는 안 됩니다.
* E-Series 시스템의 타겟 볼륨에 리소스 프로비저닝이 비활성화되어 있어야 합니다.
* 원격 스토리지 볼륨을 호스트나 여러 호스트에 직접 매핑하지 않습니다.
* 웹 서비스 프록시는 지원되지 않습니다.
* iSCSI CHAP 암호는 지원되지 않습니다.
* SMcli는 지원되지 않습니다.
* VMware 데이터 저장소는 지원되지 않습니다.
* 가져오기 페어가 있는 경우 관계/가져오기 페어에 있는 스토리지 시스템 하나만 한 번에 업그레이드할 수 있습니다.




=== 추가 정보

원격 스토리지 기능에 대한 자세한 내용은 에서 확인할 수 있습니다 https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["원격 스토리지 기술 보고서"^].
