---
permalink: sm-storage/faq-storage-array-settings.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager에 대한 스토리지 어레이 설정 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 자동 로드 밸런싱이란 무엇입니까?

자동 로드 밸런싱 기능은 자동화된 I/O 밸런싱을 제공하고 호스트에서 들어오는 I/O 트래픽이 두 컨트롤러 간에 동적으로 관리 및 균형 조정되도록 합니다.

자동 로드 밸런싱 기능은 시간이 지남에 따라 로드 변화에 동적으로 반응하여 볼륨 컨트롤러 소유권을 자동으로 조정하여 컨트롤러 간에 워크로드가 이동할 때 발생하는 로드 불균형 문제를 해결하여 I/O 리소스 관리를 향상시킵니다.

각 컨트롤러의 워크로드는 지속적으로 모니터링되며 호스트에 설치된 다중 경로 드라이버의 협력을 통해 필요할 때마다 자동으로 균형을 맞출 수 있습니다. 컨트롤러 간에 워크로드가 자동으로 재조정되면 스토리지 관리자는 스토리지 어레이의 로드 변경을 수용하기 위해 볼륨 컨트롤러 소유권을 수동으로 조정해야 하는 부담을 덜 수 있습니다.

자동 로드 밸런싱이 활성화되면 다음 기능을 수행합니다.

* 컨트롤러 리소스 활용률을 자동으로 모니터링 및 균형 조정
* 필요한 경우 볼륨 컨트롤러 소유권을 자동으로 조정하여 호스트와 스토리지 어레이 간의 I/O 대역폭을 최적화합니다.


[NOTE]
====
컨트롤러의 SSD Cache를 사용하도록 할당된 볼륨은 자동 로드 밸런싱 전송을 지원하지 않습니다.

====


== 컨트롤러 캐시란 무엇입니까?

컨트롤러 캐시는 두 가지 유형의 I/O(I/O) 작업, 즉 컨트롤러 및 호스트 간, 컨트롤러 및 디스크 간 작업을 간소화하는 물리적 메모리 공간입니다.

읽기 및 쓰기 데이터 전송의 경우 호스트와 컨트롤러는 고속 연결을 통해 통신합니다. 그러나 디스크가 상대적으로 느린 장치이기 때문에 컨트롤러의 백엔드에서 디스크와의 통신이 느려집니다.

컨트롤러 캐시가 데이터를 수신하면 컨트롤러는 데이터가 현재 보유 중인 호스트 애플리케이션에 확인합니다. 이렇게 하면 호스트 애플리케이션이 I/O가 디스크에 기록될 때까지 기다릴 필요가 없습니다. 대신 응용 프로그램에서 작업을 계속할 수 있습니다. 또한 서버 애플리케이션에서 캐시된 데이터에 쉽게 액세스할 수 있으므로 데이터에 액세스하기 위해 디스크를 추가로 읽을 필요가 없습니다.

컨트롤러 캐시는 다음과 같은 여러 가지 방법으로 스토리지 어레이의 전반적인 성능에 영향을 줍니다.

* 캐시는 버퍼 역할을 하므로 호스트 및 디스크 데이터 전송을 동기화할 필요가 없습니다.
* 호스트의 읽기 또는 쓰기 작업에 대한 데이터가 이전 작업의 캐시에 있을 수 있으므로 디스크를 액세스할 필요가 없습니다.
* 쓰기 캐시를 사용하는 경우 이전 쓰기 작업의 데이터가 디스크에 기록되기 전에 호스트에서 후속 쓰기 명령을 전송할 수 있습니다.
* 캐시 프리페치가 설정된 경우 순차적 읽기 액세스가 최적화됩니다. 캐시 프리페치를 사용하면 디스크에서 데이터를 읽는 대신 캐시에서 데이터를 더 많이 찾을 수 있습니다.


[CAUTION]
====
* 데이터 손실 가능성 * -- 배터리 없이 * 쓰기 캐싱 * 옵션을 활성화하고 보호를 위한 범용 전원 공급 장치가 없는 경우 데이터가 손실될 수 있습니다. 또한 컨트롤러 배터리가 없고 * 배터리 없이 쓰기 캐싱 * 옵션을 활성화하면 데이터가 손실될 수 있습니다.

====


== 캐시 플러싱이란 무엇입니까?

캐시에 기록되지 않은 데이터의 양이 특정 수준에 도달하면 컨트롤러는 캐시된 데이터를 드라이브에 주기적으로 씁니다. 이 쓰기 프로세스를 "플러시"라고 합니다.

컨트롤러는 캐시 플러싱에 두 가지 알고리즘(요구 기반 및 사용 기간 기반)을 사용합니다. 컨트롤러는 캐시된 데이터의 양이 캐시 플러시 임계값 아래로 떨어질 때까지 수요 기반 알고리즘을 사용합니다. 기본적으로 플러시는 캐시의 80%가 사용 중일 때 시작됩니다.

System Manager에서 "Start demand cache flashing" 임계값을 설정하여 사용자 환경에서 사용되는 입출력 유형을 가장 잘 지원할 수 있습니다. 주로 쓰기 작업을 수행하는 환경에서는 "Start demand cache flashing" 비율을 높게 설정하여 새 쓰기 요청을 디스크로 이동하지 않고 캐시로 처리할 수 있는 확률을 높여야 합니다. 백분율 설정은 더 많은 데이터가 캐시에 남아 있도록 캐시 플러시 수를 제한하여 캐시 적중률이 증가할 수 있습니다.

입출력 오류가 발생하는 환경(데이터 급증)에서는 낮은 캐시 플러시를 사용하여 시스템이 데이터 버스트 사이에 캐시를 자주 플러시할 수 있습니다. 다양한 부하를 처리하는 다양한 I/O 환경에서 또는 로드 유형을 알 수 없는 경우 임계값을 양호한 중간 지면으로 50%로 설정합니다. 시작 비율이 80%보다 낮은 경우 호스트 읽기에 필요한 데이터를 사용할 수 없기 때문에 성능이 저하될 수 있습니다. 낮은 비율을 선택하면 캐시 레벨을 유지하는 데 필요한 디스크 쓰기 수도 증가하여 시스템 오버헤드가 증가합니다.

연령 기반 알고리즘은 쓰기 데이터가 디스크에 플러시되기 전에 캐시에 남아 있을 수 있는 기간을 지정합니다. 컨트롤러는 캐시 플러시 임계값에 도달할 때까지 연령 기반 알고리즘을 사용합니다. 기본값은 10초이지만 이 기간은 비활성 기간 동안에만 계산됩니다. System Manager에서 플러시 타이밍을 수정할 수 없습니다. 대신 CLI(Command-Line Interface)에서 * 스토리지 배열 설정 * 명령을 사용해야 합니다.

[CAUTION]
====
* 데이터 손실 가능성 * -- 배터리 없이 * 쓰기 캐싱 * 옵션을 활성화하고 보호를 위한 범용 전원 공급 장치가 없는 경우 데이터가 손실될 수 있습니다. 또한 컨트롤러 배터리가 없고 * 배터리 없이 쓰기 캐싱 * 옵션을 활성화하면 데이터가 손실될 수 있습니다.

====


== 캐시 블록 크기란 무엇입니까?

스토리지 시스템의 컨트롤러는 캐시를 "블록"으로 구성합니다. 이는 8, 16, 32KiB 크기의 메모리 청크입니다. 스토리지 시스템의 모든 볼륨이 동일한 캐시 공간을 공유하기 때문에 볼륨에 캐시 블록 크기가 하나만 있을 수 있습니다.

애플리케이션은 스토리지 성능에 영향을 미칠 수 있는 다양한 블록 크기를 사용합니다. 기본적으로 System Manager의 블록 크기는 32KiB이지만 값을 8, 16, 32KiB로 설정할 수 있습니다. 파일 시스템 또는 데이터베이스 애플리케이션에 적합한 크기는 더 작습니다. 크기가 클수록 대용량 데이터 전송, 순차 I/O 또는 멀티미디어와 같은 고대역폭이 필요한 응용 프로그램에 적합합니다.



== 스토리지 배열 클록은 언제 동기화해야 합니까?

SANtricity 시스템 관리자에 표시된 타임스탬프가 관리 클라이언트(브라우저를 통해 SANtricity System Manager에 액세스하는 컴퓨터)에 표시된 타임스탬프와 일치하지 않는 경우 스토리지 배열의 컨트롤러 시계를 수동으로 동기화해야 합니다. 이 작업은 SANtricity System Manager에서 NTP(네트워크 시간 프로토콜)가 활성화되어 있지 않은 경우에만 필요합니다.

[NOTE]
====
시계를 수동으로 동기화하는 대신 NTP 서버를 사용하는 것이 좋습니다. NTP는 SNTP(Simple Network Time Protocol)를 사용하여 외부 서버와 시계를 자동으로 동기화합니다.

====
시스템 페이지에서 사용할 수 있는 스토리지 배열 시계 동기화 대화 상자에서 동기화 상태를 확인할 수 있습니다. 대화 상자에 표시된 시간이 일치하지 않으면 동기화를 실행합니다. 이 대화 상자를 주기적으로 볼 수 있습니다. 이 대화 상자는 컨트롤러 시계의 시간 디스플레이가 서로 분리되어 더 이상 동기화되지 않았음을 나타냅니다.
