---
permalink: sm-storage/faq-volumes-workloads.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager의 볼륨 및 작업 부하 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 볼륨이란 무엇입니까?

볼륨은 애플리케이션, 데이터베이스 및 파일 시스템이 데이터를 저장하는 컨테이너입니다. 호스트가 스토리지의 스토리지를 액세스할 수 있도록 생성되는 논리적 구성 요소입니다.

볼륨은 풀 또는 볼륨 그룹에서 사용할 수 있는 용량에서 생성됩니다. 볼륨에 정의된 용량이 있습니다. 볼륨이 두 개 이상의 드라이브로 구성될 수 있지만 볼륨은 호스트에 하나의 논리적 구성 요소로 나타납니다.



== 볼륨 그룹에 볼륨을 생성할 충분한 가용 용량이 있는 경우 용량 초과 할당 오류가 발생하는 이유는 무엇입니까?

선택한 볼륨 그룹에 하나 이상의 사용 가능한 용량 영역이 있을 수 있습니다. 사용 가능한 용량 영역은 볼륨 삭제 또는 볼륨 생성 중 사용 가능한 모든 용량을 사용하지 않함으로 인해 발생할 수 있는 사용 가능한 용량입니다.

하나 이상의 사용 가능한 용량 영역이 있는 볼륨 그룹에서 볼륨을 생성할 때 볼륨의 용량은 해당 볼륨 그룹에서 가장 큰 사용 가능한 용량 영역으로 제한됩니다. 예를 들어, 볼륨 그룹의 사용 가능한 용량이 총 15GiB이고 사용 가능한 최대 용량 영역이 10GiB인 경우 생성할 수 있는 최대 볼륨은 10GiB입니다.

볼륨 그룹에 사용 가능한 용량 영역이 있는 경우 볼륨 그룹 그래프에는 기존 사용 가능한 용량 영역의 수를 나타내는 링크가 포함되어 있습니다. 링크를 선택하면 각 영역의 용량을 나타내는 팝업 창이 표시됩니다.

여유 용량을 통합하면 볼륨 그룹의 최대 사용 가능 용량에서 추가 볼륨을 생성할 수 있습니다. 다음 방법 중 하나를 사용하여 선택한 볼륨 그룹에서 기존 사용 가능한 용량을 통합할 수 있습니다.

* 볼륨 그룹에 대해 사용 가능한 용량 영역이 하나 이상 감지되면 알림 영역의 홈 페이지에 "사용 가능한 용량 통합" 권장 사항이 표시됩니다. 무료 용량 통합 * 링크를 클릭하여 대화 상자를 시작합니다.
* Pools & Volume Groups [Uncommon Tasks > Consolidate volume group free capacity] 메뉴를 선택하여 대화 상자를 시작할 수도 있습니다.


최대 가용 용량 영역이 아닌 특정 가용 용량 영역을 사용하려면 CLI(Command Line Interface)를 사용합니다.



== 선택한 워크로드가 볼륨 생성에 어떤 영향을 미칩니까?

볼륨 생성 중에 워크로드 사용에 대한 정보를 묻는 메시지가 표시됩니다. 시스템에서는 이 정보를 사용하여 최적의 볼륨 구성을 생성합니다. 이 구성은 필요에 따라 편집할 수 있습니다. 선택적으로 볼륨 생성 순서에서 이 단계를 건너뛸 수 있습니다.

워크로드는 애플리케이션을 지원하는 스토리지 객체입니다. 애플리케이션별로 하나 이상의 워크로드 또는 인스턴스를 정의할 수 있습니다. 일부 애플리케이션의 경우 시스템에서 기본 볼륨 특성이 비슷한 볼륨을 포함하도록 워크로드를 구성합니다. 이러한 볼륨 특성은 워크로드가 지원하는 애플리케이션 유형에 따라 최적화됩니다. 예를 들어, Microsoft SQL Server 애플리케이션을 지원하는 워크로드를 생성한 다음 해당 워크로드에 대한 볼륨을 생성하는 경우 기본 볼륨 특성은 Microsoft SQL Server를 지원하도록 최적화되어 있습니다.

* * 응용 프로그램별 * -- 응용 프로그램별 작업 부하를 사용하여 볼륨을 생성할 때 응용 프로그램 작업 부하 I/O와 응용 프로그램 인스턴스의 다른 트래픽 간의 경합을 최소화하기 위해 최적화된 볼륨 구성을 권장할 수 있습니다. I/O 유형, 세그먼트 크기, 컨트롤러 소유권, 읽기 및 쓰기 캐시와 같은 볼륨 특성은 자동으로 권장 사항이며 다음과 같은 애플리케이션 유형에 대해 생성되는 워크로드에 최적화되어 있습니다.
+
** Microsoft ® SQL Server ™ 를 참조하십시오
** Microsoft ® Exchange Server ™ 를 참조하십시오
** 비디오 감시 애플리케이션
** VMware ESXi ™ (가상 머신 파일 시스템과 함께 사용할 볼륨용)
+
볼륨 추가/편집 대화 상자를 사용하여 권장 볼륨 구성을 검토하고 시스템 권장 볼륨 및 특성을 편집, 추가 또는 삭제할 수 있습니다.



* * 기타 * (또는 특정 볼륨 생성을 지원하지 않는 애플리케이션) -- 다른 워크로드는 볼륨 구성을 사용하며, 특정 애플리케이션과 연결되지 않은 워크로드를 생성하려는 경우 또는 스토리지 어레이에서 사용하려는 애플리케이션에 대한 내장 최적화가 없는 경우 수동으로 지정해야 합니다. 볼륨 추가/편집 대화 상자를 사용하여 볼륨 구성을 수동으로 지정해야 합니다.




== 이러한 볼륨이 작업 부하와 연결되지 않는 이유는 무엇입니까?

CLI(Command Line Interface)를 사용하여 볼륨을 생성했거나 다른 스토리지 어레이에서 마이그레이션(가져오기/내보내기)한 경우 볼륨은 워크로드에 연결되지 않습니다.



== 선택한 작업 부하를 삭제할 수 없는 이유는 무엇입니까?

이 워크로드는 CLI(Command Line Interface)를 사용하여 생성되거나 다른 스토리지 어레이에서 마이그레이션(가져오기/내보내기)된 볼륨 그룹으로 구성됩니다. 따라서 이 워크로드의 볼륨은 애플리케이션별 워크로드와 연결되지 않으므로 워크로드를 삭제할 수 없습니다.



== 애플리케이션별 워크로드를 사용하면 스토리지 어레이를 관리하는 데 어떤 도움이 됩니까?

애플리케이션별 워크로드의 볼륨 특성에 따라 스토리지 어레이의 구성 요소와 워크로드가 상호 작용하는 방식이 결정되며, 지정된 구성에서 환경의 성능을 파악하는 데 도움이 됩니다.

애플리케이션은 SQL Server 또는 Exchange와 같은 소프트웨어입니다. 각 애플리케이션을 지원할 워크로드를 하나 이상 정의합니다.



== 이 정보를 제공하면 스토리지를 생성하는 데 어떤 도움이 됩니까?

워크로드 정보는 선택한 워크로드에 대한 I/O 유형, 세그먼트 크기, 읽기/쓰기 캐시 등과 같은 볼륨 특성을 최적화하는 데 사용됩니다. 이처럼 최적화된 특성을 바탕으로 워크로드가 스토리지 어레이 구성요소와 상호 작용하는 방식이 결정됩니다.

제공하는 워크로드 정보를 기반으로 System Manager에서 적절한 볼륨을 생성하여 현재 시스템에 존재하는 사용 가능한 풀 또는 볼륨 그룹에 배치합니다. 시스템이 볼륨을 생성하고 선택한 워크로드에 대한 현재 모범 사례를 기반으로 해당 특성을 최적화합니다.

특정 워크로드에 대한 볼륨 생성을 완료하기 전에 볼륨 추가/편집 대화 상자를 사용하여 권장 볼륨 구성을 검토하고 시스템 권장 볼륨 및 특성을 편집, 추가 또는 삭제할 수 있습니다.

모범 사례 정보는 응용 프로그램별 설명서를 참조하십시오.



== 확장된 용량을 인식하려면 어떻게 해야 합니까?

볼륨의 용량을 늘릴 경우 호스트에서 즉시 볼륨 용량 증가를 인식하지 못할 수 있습니다.

대부분의 운영 체제는 볼륨 확장이 시작된 후 확장된 볼륨 용량을 인식하고 자동으로 확장합니다. 그러나 일부는 그렇지 않을 수도 있습니다. OS에서 확장된 볼륨 용량을 자동으로 인식하지 못하는 경우 디스크 재검색 또는 재부팅을 수행해야 할 수 있습니다.

볼륨 용량을 확장한 후에는 파일 시스템 크기를 수동으로 늘려야 합니다. 이 방법은 사용 중인 파일 시스템에 따라 다릅니다.

자세한 내용은 호스트 운영 체제 설명서를 참조하십시오.



== 왜 내 풀 및/또는 볼륨 그룹이 모두 보이지 않나요?

볼륨을 이동할 수 없는 풀 또는 볼륨 그룹이 목록에 표시되지 않습니다.

풀 또는 볼륨 그룹은 다음과 같은 이유로 적합하지 않습니다.

* 풀 또는 볼륨 그룹 풀의 DA(Data Assurance) 기능이 일치하지 않습니다.
* 풀 또는 볼륨 그룹이 최적화되지 않은 상태입니다.
* 풀 또는 볼륨 그룹의 용량이 너무 작습니다.




== 세그먼트 크기란?

세그먼트는 스토리지 어레이가 스트라이프의 다음 드라이브(RAID 그룹)로 이동하기 전에 드라이브에 저장되는 데이터의 양(KB)입니다. 세그먼트 크기는 풀이 아닌 볼륨 그룹에만 적용됩니다.

세그먼트 크기는 포함된 데이터 블록 수로 정의됩니다. 세그먼트 크기를 결정할 때 볼륨에 저장할 데이터 유형을 알아야 합니다. 일반적으로 애플리케이션에서 작은 랜덤 읽기/쓰기(IOPS)를 사용하는 경우, 작은 세그먼트 크기가 더 작을수록 더 우수한 성능을 얻을 수 있습니다. 또는 애플리케이션에 대규모 순차 읽기 및 쓰기(처리량)가 있는 경우 일반적으로 큰 세그먼트 크기가 더 좋습니다.

애플리케이션에서 작은 랜덤 읽기 및 쓰기를 사용하든, 대규모 순차 읽기 및 쓰기를 사용하든, 세그먼트 크기가 일반적인 데이터 블록 청크 크기보다 클 경우 스토리지 어레이가 더 뛰어난 성능을 발휘합니다. 따라서 일반적으로 드라이브에서 데이터에 더 쉽고 빠르게 액세스할 수 있으며, 이는 스토리지 어레이 성능 향상을 위해 중요합니다.



=== IOPS 성능이 중요한 환경

IOPS(초당 입출력 작업) 환경에서 드라이브에 읽기/쓰기가 수행되는 일반 데이터 블록 크기(""청크")보다 큰 세그먼트 크기를 사용하면 스토리지 시스템의 성능이 향상됩니다. 이렇게 하면 각 청크가 단일 드라이브에 기록됩니다.



=== 처리량이 중요한 환경

처리량 환경에서 세그먼트 크기는 데이터의 총 드라이브 수와 일반적인 데이터 청크 크기(I/O 크기)의 짝수 부분이 되어야 합니다. 이렇게 하면 데이터가 볼륨 그룹의 드라이브에 단일 스트라이프로 분산되므로 읽기 및 쓰기 속도가 빨라집니다.



== 선호하는 컨트롤러 소유권은 무엇입니까?

선호 컨트롤러 소유권은 볼륨의 소유 또는 주 컨트롤러로 지정된 컨트롤러를 정의합니다.

컨트롤러 소유권은 매우 중요하며 신중하게 계획해야 합니다. 전체 I/O에 대해 컨트롤러를 최대한 균형 조정해야 합니다.

예를 들어, 하나의 컨트롤러가 주로 대규모 순차 데이터 블록을 읽고 다른 컨트롤러에 빈번한 읽기 및 쓰기 작업을 수행하는 작은 데이터 블록이 있으면 로드가 매우 달라집니다. 어떤 볼륨에 어떤 데이터 유형이 포함되어 있는지 이해하면 두 컨트롤러 모두에서 I/O 전송 균형을 동일하게 유지할 수 있습니다.



== 나중에 호스트 할당 선택 항목을 언제 사용하시겠습니까?

볼륨 생성 프로세스의 속도를 높이려면 새로 생성된 볼륨이 오프라인으로 초기화되도록 호스트 할당 단계를 건너뛸 수 있습니다.

새로 생성된 볼륨을 초기화해야 합니다. 시스템은 두 가지 모드(즉시 사용 가능한 형식(iaf) 백그라운드 초기화 프로세스 또는 오프라인 프로세스) 중 하나를 사용하여 이러한 모드를 초기화할 수 있습니다.

볼륨을 호스트에 매핑하면 해당 그룹의 초기화 볼륨이 백그라운드 초기화로 강제로 전환됩니다. 이 백그라운드 초기화 프로세스를 사용하면 동시 호스트 입출력이 허용되므로 시간이 오래 걸릴 수 있습니다.

볼륨 그룹의 볼륨 중 어느 것도 매핑되지 않은 경우 오프라인 초기화가 수행됩니다. 오프라인 프로세스는 백그라운드 프로세스보다 훨씬 빠릅니다.



== 호스트 블록 크기 요구 사항에 대해 알아야 할 내용은 무엇입니까?

EF300 및 EF600 시스템의 경우 512바이트 또는 4KiB 블록 크기("섹터 크기"라고도 함)를 지원하도록 볼륨을 설정할 수 있습니다. 볼륨을 생성하는 동안 올바른 값을 설정해야 합니다. 가능한 경우 시스템은 적절한 기본값을 제안합니다.

볼륨 블록 크기를 설정하기 전에 다음 제한 사항 및 지침을 읽으십시오.

* 일부 운영 체제와 가상 머신(현재 VMware 등)에는 512바이트 블록 크기가 필요하며 4KiB를 지원하지 않으므로 볼륨을 생성하기 전에 호스트 요구 사항을 알아야 합니다. 일반적으로 볼륨을 4KiB 블록 크기로 설정하여 최상의 성능을 얻을 수 있지만 호스트에서 4KiB(""4Kn") 블록을 허용하는지 확인합니다.
* 풀 또는 볼륨 그룹에 대해 선택하는 드라이브 유형에 따라 지원되는 볼륨 블록 크기가 다음과 같이 결정됩니다.
+
** 512바이트 블록에 쓰는 드라이브를 사용하여 볼륨 그룹을 생성하는 경우 512바이트 블록의 볼륨만 생성할 수 있습니다.
** 4KiB 블록에 쓰는 드라이브를 사용하여 볼륨 그룹을 생성하는 경우 512바이트 또는 4KiB 블록으로 볼륨을 생성할 수 있습니다.


* 어레이에 iSCSI 호스트 인터페이스 카드가 있는 경우 모든 볼륨은 볼륨 그룹 블록 크기와 관계없이 512바이트 블록으로 제한됩니다. 이는 특정 하드웨어 구현 때문입니다.
* 블록 크기를 설정한 후에는 변경할 수 없습니다. 블록 크기를 변경해야 하는 경우 볼륨을 삭제하고 다시 생성해야 합니다.

