---
permalink: sm-storage/faq-snapshots.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager에 대한 스냅샷 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 볼륨, 호스트 또는 호스트 클러스터가 모두 표시되지 않는 이유는 무엇입니까?

DA 지원 기본 볼륨이 있는 스냅샷 볼륨은 DA(Data Assurance) 기능이 지원되지 않는 호스트에 할당할 수 없습니다. DA를 사용할 수 없는 호스트에 스냅샷 볼륨을 할당하기 전에 기본 볼륨에서 DA를 비활성화해야 합니다.

스냅샷 볼륨을 할당할 호스트에 대한 다음 지침을 고려하십시오.

* DA를 사용할 수 없는 입출력 인터페이스를 통해 스토리지 시스템에 접속된 호스트의 경우 DA를 사용할 수 없습니다.
* DA를 사용할 수 없는 호스트 구성원이 하나 이상 있는 경우 호스트 클러스터를 DA를 사용할 수 없습니다.


[NOTE]
====
스냅샷과 연결된 볼륨(정합성 보장 그룹, 스냅샷 그룹, 스냅샷 이미지 및 스냅샷 볼륨), 볼륨 복제본에서는 DA를 비활성화할 수 없습니다. 있습니다. 기본 볼륨에서 DA를 비활성화하기 전에 관련된 모든 예약 용량 및 스냅샷 객체를 삭제해야 합니다.

====


== 스냅샷 이미지란 무엇입니까?

스냅샷 이미지는 특정 시점에 캡처된 볼륨 콘텐츠의 논리적 복사본입니다. 스냅샷 이미지는 최소한의 저장 공간을 사용합니다.

스냅샷 이미지 데이터는 다음과 같이 저장됩니다.

* 스냅샷 이미지가 생성되면 기본 볼륨과 정확히 일치합니다. 스냅샷이 생성된 후 기본 볼륨의 블록 또는 블록 세트에 대해 첫 번째 쓰기 요청이 발생하면 새 데이터가 기본 볼륨에 쓰기되기 전에 원래 데이터가 스냅샷 예약 용량에 복사됩니다.
* 후속 스냅샷에는 첫 번째 스냅샷 이미지가 생성된 이후 변경된 데이터 블록만 포함됩니다. 이후의 각 COW(Copy-On-Write) 작업은 새 데이터를 기본 볼륨에 쓰기 전에 기본 볼륨에서 덮어쓰려고 하는 원본 데이터를 스냅샷 예약 용량에 저장합니다.




== 스냅샷 이미지를 사용하는 이유

스냅샷을 사용하여 실수로 또는 악의적으로 데이터가 손실되거나 손상되지 않도록 보호하고 복구할 수 있습니다.

스냅샷 정합성 보장 그룹이라고 하는 기본 볼륨 또는 기본 볼륨 그룹을 선택한 후 다음 방법 중 하나 이상으로 스냅샷 이미지를 캡처합니다.

* 단일 기본 볼륨의 스냅샷 이미지 또는 여러 기본 볼륨으로 구성된 스냅샷 정합성 보장 그룹을 생성할 수 있습니다.
* 스냅샷을 수동으로 생성하거나 기본 볼륨 또는 스냅샷 정합성 보장 그룹에 대한 스케줄을 생성하여 주기적 스냅샷 이미지를 자동으로 캡처할 수 있습니다.
* 스냅샷 이미지의 호스트 액세스 가능 스냅샷 볼륨을 생성할 수 있습니다.
* 롤백 작업을 수행하여 스냅샷 이미지를 복구할 수 있습니다.


시스템은 여러 스냅샷 이미지를 복원 지점으로 유지하며, 특정 시점에 알려진 양호한 데이터 세트로 롤백하는 데 사용할 수 있습니다. 롤백 기능을 사용하면 실수로 인한 데이터 삭제 및 데이터 손상을 방지할 수 있습니다.



== 스냅숏에 사용할 수 있는 볼륨의 종류는 무엇입니까?

표준 볼륨과 씬 볼륨은 스냅샷 이미지를 저장하는 데 사용할 수 있는 유일한 볼륨 유형입니다. 비표준 볼륨은 사용할 수 없습니다. 기본 볼륨은 풀 또는 볼륨 그룹에 상주할 수 있습니다.



== 스냅샷 정합성 보장 그룹을 생성하는 이유는 무엇입니까?

스냅샷 정합성 보장 그룹은 여러 볼륨에서 동시에 스냅샷 이미지를 생성하려는 경우에 생성됩니다.

예를 들어, 복구를 위해 일관성을 유지해야 하는 여러 볼륨으로 구성된 데이터베이스의 경우 모든 볼륨의 조정된 스냅샷을 수집하여 전체 데이터베이스를 복원하는 데 사용하려면 스냅샷 정합성 보장 그룹이 필요합니다.

스냅샷 정합성 보장 그룹에 포함된 볼륨을 _member volumes_라고 합니다.

스냅샷 정합성 보장 그룹에 대해 다음 스냅샷 작업을 수행할 수 있습니다.

* 구성원 볼륨의 동시 이미지를 가져올 스냅샷 정합성 보장 그룹의 스냅샷 이미지를 생성합니다.
* 구성원 볼륨의 주기적인 동시 이미지를 자동으로 캡처할 스냅샷 정합성 보장 그룹의 스케줄을 생성합니다.
* 스냅샷 정합성 보장 그룹 이미지의 호스트 액세스 가능 스냅샷 볼륨을 생성합니다.
* 스냅샷 정합성 보장 그룹에 대해 롤백 작업을 수행합니다.




== 스냅샷 볼륨이란 무엇이며 예약 용량은 언제 필요합니까?

스냅샷 볼륨을 사용하면 호스트가 스냅샷 이미지의 데이터에 액세스할 수 있습니다. 스냅샷 볼륨에는 원래 스냅샷 이미지에 영향을 주지 않고 기본 볼륨에 대한 수정 사항을 저장하는 자체 예약 용량이 포함되어 있습니다. 스냅샷 이미지는 호스트에서 읽기 또는 쓰기 액세스가 지원되지 않습니다. 스냅샷 데이터를 읽거나 쓰려면 스냅샷 볼륨을 생성하여 호스트에 할당합니다.

두 가지 유형의 스냅샷 볼륨을 생성할 수 있습니다. 스냅샷 볼륨의 유형에 따라 예약된 용량을 사용할지 여부가 결정됩니다.

* * 읽기 전용 * -- 읽기 전용으로 생성된 스냅샷 볼륨은 호스트 응용 프로그램에 스냅샷 이미지에 포함된 데이터 복제본에 대한 읽기 액세스 권한을 제공합니다. 읽기 전용 스냅샷 볼륨은 예약된 용량을 사용하지 않습니다.
* * 읽기-쓰기 * -- 읽기-쓰기로 생성된 스냅샷 볼륨을 사용하면 참조된 스냅샷 이미지에 영향을 주지 않고 스냅샷 볼륨을 변경할 수 있습니다. 읽기-쓰기 스냅샷 볼륨은 예약된 용량을 사용하여 이러한 변경 사항을 저장합니다. 언제든지 읽기 전용 스냅샷 볼륨을 읽기-쓰기로 변환할 수 있습니다.




== 스냅샷 그룹이란 무엇입니까?

스냅샷 그룹은 연결된 단일 기본 볼륨의 시점 스냅샷 이미지 모음입니다.

System Manager는 스냅샷 이미지를 _ 스냅샷 그룹 _ 으로 구성합니다. 스냅샷 그룹은 사용자 작업이 필요하지 않지만 언제든지 스냅샷 그룹의 예약된 용량을 조정할 수 있습니다. 또한 다음 조건이 충족되면 예약된 용량을 생성하라는 메시지가 표시될 수 있습니다.

* 아직 스냅샷 그룹이 없는 기본 볼륨의 스냅샷을 생성할 때마다 System Manager는 자동으로 스냅샷 그룹을 생성합니다. 이렇게 하면 후속 스냅샷 이미지를 저장하는 데 사용되는 기본 볼륨에 예약된 용량이 생성됩니다.
* 기본 볼륨에 대한 스냅샷 스케줄을 생성할 때마다 System Manager가 자동으로 스냅샷 그룹을 생성합니다.




== 스냅샷 볼륨을 사용하지 않도록 설정하는 이유는 무엇입니까?

스냅샷 이미지에 다른 스냅샷 볼륨을 할당하려는 경우 스냅샷 볼륨을 사용하지 않도록 설정합니다. 비활성화된 스냅샷 볼륨을 나중에 사용할 수 있도록 예약할 수 있습니다.

스냅샷 볼륨이나 정합성 보장 그룹 스냅샷 볼륨이 더 이상 필요하지 않고 나중에 다시 생성하지 않으려는 경우 볼륨을 사용하지 않도록 설정하는 대신 삭제해야 합니다.



== 사용 안 함 상태란 무엇입니까?

사용 안 함 상태의 스냅샷 볼륨은 현재 스냅샷 이미지에 할당되어 있지 않습니다. 스냅샷 볼륨을 활성화하려면 다시 생성 작업을 사용하여 비활성화된 스냅샷 볼륨에 새 스냅샷 이미지를 할당해야 합니다.

스냅샷 볼륨 특성은 할당된 스냅샷 이미지에 의해 정의됩니다. 읽기-쓰기 작업은 비활성화 상태의 스냅샷 볼륨에서 일시 중단됩니다.



== 스냅샷 스케줄을 일시 중지하는 이유는 무엇입니까?

스케줄이 일시 중지되면 예약된 스냅샷 이미지 생성이 수행되지 않습니다. 스토리지 공간을 절약하기 위해 스냅샷 스케줄을 일시 중지한 다음 나중에 예약된 스냅샷을 다시 시작할 수 있습니다.

스냅샷 스케줄이 필요하지 않은 경우 스케줄을 일시 중지하는 대신 삭제해야 합니다.
