---
permalink: sm-storage/faq-systems-clusters.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager에 대한 호스트 시스템 및 호스트 클러스터 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 호스트 및 호스트 클러스터란 무엇입니까?

호스트는 스토리지 배열의 볼륨에 입출력을 전송하는 서버입니다. 호스트 클러스터는 호스트 그룹입니다. 호스트 클러스터를 생성하여 동일한 볼륨을 여러 호스트에 쉽게 할당할 수 있습니다.

호스트를 별도로 정의합니다. 독립적인 엔티티이거나 호스트 클러스터에 추가할 수 있습니다. 개별 호스트에 볼륨을 할당하거나 호스트 클러스터의 다른 호스트와 하나 이상의 볼륨에 대한 액세스를 공유하는 호스트 클러스터의 일부가 될 수 있습니다.

호스트 클러스터는 SANtricity System Manager에서 생성한 논리적 엔터티입니다. 볼륨을 할당하려면 먼저 호스트를 호스트 클러스터에 추가해야 합니다.



== 호스트 클러스터를 생성해야 하는 이유는 무엇입니까?

동일한 볼륨 세트에 대한 액세스를 공유하는 호스트가 2개 이상인 경우 호스트 클러스터를 생성해야 합니다. 일반적으로 개별 호스트에는 볼륨 액세스를 조정하기 위해 클러스터링 소프트웨어가 설치되어 있습니다.



== 어떤 호스트 운영 체제 유형이 올바른지 어떻게 알 수 있습니까?

호스트 운영 체제 유형 필드에는 호스트의 운영 체제가 들어 있습니다. 드롭다운 목록에서 권장 호스트 유형을 선택할 수 있습니다.

드롭다운 목록에 표시되는 호스트 유형은 스토리지 어레이 모델 및 펌웨어 버전에 따라 다릅니다. 가장 최신 버전은 가장 일반적인 옵션을 먼저 표시하며, 이 옵션이 가장 적절할 가능성이 높습니다. 이 목록의 모양은 옵션이 완전히 지원됨을 의미하지는 않습니다.

[NOTE]
====
호스트 지원에 대한 자세한 내용은 를 참조하십시오 https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 툴"^].

====
다음 호스트 유형 중 일부가 목록에 나타날 수 있습니다.

[cols="35h,~"]
|===
| 호스트 운영 체제 유형입니다 | 운영 체제(OS) 및 다중 경로 드라이버 


 a| 
Linux DM-MP(커널 3.10 이상)
 a| 
3.10 이상의 커널과 함께 장치 매퍼 다중 경로 페일오버 솔루션을 사용하여 Linux 운영 체제를 지원합니다.



 a| 
VMware ESXi
 a| 
VMware 기본 제공 스토리지 어레이 유형 정책 모듈 SATP_ALUA를 사용하여 NMP(Native Multipathing Plug-in) 아키텍처를 실행하는 VMware ESXi 운영 체제를 지원합니다.



 a| 
Windows(클러스터형 또는 비클러스터형)
 a| 
ATTO 다중 경로 드라이버를 실행하지 않는 Windows 클러스터 또는 클러스터링되지 않은 구성을 지원합니다.



 a| 
ATTO 클러스터(모든 운영 체제)
 a| 
ATTO Technology, Inc., 다중 경로 드라이버를 사용하는 모든 클러스터 구성을 지원합니다.



 a| 
Linux(Veritas DMP)
 a| 
Veritas DMP 다중 경로 솔루션을 사용하여 Linux 운영 체제를 지원합니다.



 a| 
Linux(ATTO)
 a| 
ATTO Technology, Inc., 다중 경로 드라이버를 사용하는 Linux 운영 체제를 지원합니다.



 a| 
Mac OS(ATTO)
 a| 
ATTO Technology, Inc., 다중 경로 드라이버를 사용하는 Mac OS 버전을 지원합니다.



 a| 
Windows(ATTO)
 a| 
ATTO Technology, Inc., 다중 경로 드라이버를 사용하는 Windows 운영 체제를 지원합니다.



 a| 
IBM SVC
 a| 
IBM SAN Volume Controller 구성을 지원합니다.



 a| 
공장 출하 시 기본값
 a| 
스토리지 배열의 초기 시작용으로 예약되어 있습니다. 호스트 운영 체제 유형이 출하 시 기본값으로 설정되어 있는 경우 연결된 호스트에서 실행 중인 호스트 운영 체제 및 다중 경로 드라이버에 맞게 변경합니다.



 a| 
Linux DM-MP(커널 3.9 이상)
 a| 
3.9 이하의 커널과 함께 장치 매퍼 다중 경로 장애 조치 솔루션을 사용하여 Linux 운영 체제를 지원합니다.



 a| 
Window Clustered(더 이상 사용되지 않음)
 a| 
호스트 운영 체제 유형이 이 값으로 설정되어 있으면 Windows(클러스터형 또는 비클러스터형) 설정을 대신 사용합니다.

|===


== HBA와 어댑터 포트란 무엇입니까?

HBA(호스트 버스 어댑터)는 호스트에 상주하며 하나 이상의 호스트 포트를 포함하는 보드입니다. 호스트 포트는 컨트롤러에 대한 물리적 연결을 제공하고 I/O 작업에 사용되는 호스트 버스 어댑터(HBA)의 포트입니다.

HBA의 어댑터 포트를 호스트 포트라고 합니다. 대부분의 HBA에는 하나 또는 두 개의 호스트 포트가 있습니다. HBA에는 고유한 WWID(World Wide Identifier)가 있으며 각 HBA 호스트 포트에는 고유한 WWID가 있습니다. 호스트 포트 식별자는 SANtricity System Manager를 통해 호스트를 수동으로 생성할 때 적절한 HBA를 물리적 호스트와 연결하는 데 사용됩니다.



== 호스트 포트를 호스트에 일치시키려면 어떻게 해야 합니까?

호스트를 수동으로 생성하는 경우 먼저 호스트에서 사용할 수 있는 적절한 HBA(호스트 버스 어댑터) 유틸리티를 사용하여 호스트에 설치된 각 HBA와 연결된 호스트 포트 식별자를 확인해야 합니다.

이 정보가 있는 경우 Create Host 대화 상자에 제공된 목록에서 스토리지 배열에 로그인한 호스트 포트 식별자를 선택합니다.

[NOTE]
====
생성 중인 호스트에 대해 적절한 호스트 포트 식별자를 선택해야 합니다. 잘못된 호스트 포트 식별자를 연결하면 다른 호스트에서 이 데이터에 의도하지 않은 액세스가 발생할 수 있습니다.

====


== CHAP 암호를 생성하려면 어떻게 해야 합니까?

스토리지 배열에 연결된 iSCSI 호스트에서 CHAP(Challenge Handshake Authentication Protocol) 인증을 설정하는 경우 각 iSCSI 호스트에 대해 해당 초기자 CHAP 암호를 다시 입력해야 합니다.

이렇게 하려면 호스트 생성 작업의 일부로 또는 설정 보기/편집 옵션을 통해 System Manager를 사용할 수 있습니다.

CHAP 상호 인증을 사용하는 경우 설정 페이지에서 스토리지 배열에 대한 대상 CHAP 암호도 정의하고 각 iSCSI 호스트에서 해당 대상 CHAP 암호를 다시 입력해야 합니다.



== 기본 클러스터는 무엇입니까?

기본 클러스터는 기본 클러스터에 할당된 볼륨에 대한 액세스 권한을 얻기 위해 스토리지 배열에 로그인한 연결되지 않은 호스트 포트 식별자를 허용하는 시스템 정의 엔티티입니다. 연결되지 않은 호스트 포트 식별자는 특정 호스트와 논리적으로 연결되지 않지만 호스트에 물리적으로 설치되어 스토리지 배열에 로그인하는 호스트 포트입니다.

[NOTE]
====
호스트가 스토리지 배열의 특정 볼륨에 특정 액세스를 가지도록 하려면 기본 클러스터를 _사용하지_않아야 합니다. 대신 호스트 포트 식별자를 해당 호스트에 연결해야 합니다. 이 작업은 Create Host(호스트 생성) 작업 중에 수동으로 수행할 수 있습니다. 그런 다음 개별 호스트 또는 호스트 클러스터에 볼륨을 할당합니다.

====
외부 스토리지 환경이 모든 호스트 및 스토리지 배열에 연결된 모든 로그인 호스트 포트 식별자를 모든 볼륨에 액세스할 수 있도록 허용하는 특수한 상황에서는 _ 전용 _ 기본 클러스터를 사용해야 합니다(모든 액세스 모드). 호스트를 스토리지 시스템 또는 사용자 인터페이스에 특별히 알려주지 않습니다.

처음에는 CLI(Command Line Interface)를 통해 기본 클러스터에만 볼륨을 할당할 수 있습니다. 그러나 기본 클러스터에 볼륨을 한 개 이상 할당한 후에는 이 개체(기본 클러스터라고 함)가 사용자 인터페이스에 표시되며, 여기에서 이 엔터티를 관리할 수 있습니다.



== 호스트 연결 보고란 무엇입니까?

호스트 연결 보고가 설정되면 스토리지 어레이는 컨트롤러와 구성된 호스트 간의 연결을 지속적으로 모니터링한 다음 연결이 중단되면 경고를 표시합니다.

느슨하거나 손상되거나 누락된 케이블이 있거나 호스트에 다른 문제가 있는 경우 연결이 중단될 수 있습니다. 이러한 경우, 시스템이 Recovery Guru 메시지를 열 수 있습니다.

* * 호스트 중복성 손실* -- 두 컨트롤러가 호스트와 통신할 수 없는 경우 열립니다.
* * 잘못된 호스트 유형 * -- 호스트 유형이 스토리지 배열에 잘못 지정되어 장애 조치 문제가 발생할 경우 열립니다.


컨트롤러를 재부팅하면 연결 시간 초과보다 오래 걸릴 수 있는 상황에서 호스트 연결 보고를 사용하지 않도록 설정할 수 있습니다. 이 기능을 사용하지 않도록 설정하면 복구 Gurus 메시지가 표시되지 않습니다.

[NOTE]
====
호스트 연결 보고를 비활성화하면 컨트롤러 리소스 사용을 모니터링 및 밸런싱하는 자동 로드 밸런싱도 비활성화됩니다. 그러나 호스트 연결 보고를 다시 활성화하면 자동 로드 밸런싱 기능이 자동으로 다시 활성화되지 않습니다.

====