---
permalink: sm-storage/faq-storage-drives.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager를 위한 스토리지 드라이브 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 핫 스페어 드라이브란 무엇입니까?

핫 스페어는 RAID 1, RAID 5 또는 RAID 6 볼륨 그룹의 대기 드라이브 역할을 합니다. 데이터가 없는 완전한 기능을 갖춘 드라이브입니다. 볼륨 그룹에서 드라이브에 장애가 발생하면 컨트롤러는 장애가 발생한 드라이브에서 핫 스페어로 데이터를 자동으로 재구성합니다.

스토리지 배열의 드라이브에 오류가 발생하면 물리 스왑 없이 핫 스페어 드라이브가 장애가 발생한 드라이브로 자동 대체됩니다. 드라이브에 오류가 발생할 때 핫 스페어 드라이브를 사용할 수 있는 경우 컨트롤러는 중복 데이터를 사용하여 오류가 발생한 드라이브에서 핫 스페어 드라이브로 데이터를 재구성합니다.

핫 스페어 드라이브는 특정 볼륨 그룹 전용이 아닙니다. 대신 용량이 같거나 더 작은 스토리지 배열의 모든 장애 드라이브에 핫 스페어 드라이브를 사용할 수 있습니다. 핫 스페어 드라이브는 보호 드라이브와 동일한 미디어 유형(HDD 또는 SSD)이어야 합니다.

[NOTE]
====
핫 스페어 드라이브는 풀에서 지원되지 않습니다. 풀은 핫 스페어 드라이브 대신 풀을 구성하는 각 드라이브 내의 보존 용량을 사용합니다.

====


== 보존 용량이란?

Preservation capacity는 잠재적 드라이브 장애를 지원하기 위해 풀에 예약된 용량(드라이브 수)입니다.

풀이 생성되면 시스템은 풀의 드라이브 수에 따라 기본 보존 용량을 자동으로 예약합니다.

풀은 재구성 중에 보존 용량을 사용하지만 볼륨 그룹은 동일한 목적으로 핫 스페어 드라이브를 사용합니다. 보존 용량 방법은 재구성을 더 빠르게 수행할 수 있도록 핫 스페어 드라이브에 비해 향상된 기능입니다. 보존 용량은 핫 스페어 드라이브의 경우 드라이브 하나가 아닌 풀의 여러 드라이브에 분산되므로 드라이브 한 개의 속도나 가용성에 의해 제한되지 않습니다.



== 드라이브를 논리적으로 교체하는 이유는 무엇입니까?

드라이브에 장애가 발생하거나 다른 이유로 드라이브를 교체하고 스토리지 어레이에 할당되지 않은 드라이브가 있는 경우, 장애가 발생한 드라이브를 할당되지 않은 드라이브로 논리적으로 교체할 수 있습니다. 할당되지 않은 드라이브가 없는 경우 드라이브를 물리적으로 교체할 수 있습니다.

원래 드라이브의 데이터는 교체 드라이브에 복사 또는 재구성됩니다.



== 재구성 중인 드라이브의 상태는 어디에서 확인할 수 있습니까?

Operations In Progress 대시보드에서 드라이브 재구성 상태를 볼 수 있습니다.

홈 페이지에서 오른쪽 상단의 * View Operations in Progress * 링크를 클릭합니다.

드라이브에 따라 전체 재구성에 상당한 시간이 걸릴 수 있습니다. 볼륨 소유권이 변경된 경우 신속한 재구성 대신 전체 재구성이 이루어질 수 있습니다.
