---
permalink: sm-storage/host-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host, terms 
summary: 호스트 용어가 스토리지 어레이에 어떻게 적용되는지 알아보십시오. 
---
= 호스트 용어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트 용어가 스토리지 어레이에 어떻게 적용되는지 알아보십시오.

[cols="25h,~"]
|===
| 구성 요소 | 정의 


 a| 
호스트
 a| 
호스트는 스토리지 배열의 볼륨에 입출력을 전송하는 서버입니다.



 a| 
호스트 이름입니다
 a| 
호스트 이름은 호스트의 시스템 이름과 같아야 합니다.



 a| 
호스트 클러스터
 a| 
호스트 클러스터는 호스트 그룹입니다. 호스트 클러스터를 생성하여 동일한 볼륨을 여러 호스트에 쉽게 할당할 수 있습니다.



 a| 
호스트 인터페이스 프로토콜입니다
 a| 
호스트 인터페이스 프로토콜은 컨트롤러와 호스트 간의 연결(예: 파이버 채널, iSCSI 등)입니다.



 a| 
HBA 또는 네트워크 인터페이스 카드(NIC)
 a| 
HBA(호스트 버스 어댑터)는 호스트에 상주하며 하나 이상의 호스트 포트를 포함하는 보드입니다.



 a| 
호스트 포트
 a| 
호스트 포트는 컨트롤러에 대한 물리적 연결을 제공하고 I/O 작업에 사용되는 호스트 버스 어댑터(HBA)의 포트입니다.



 a| 
호스트 포트 식별자입니다
 a| 
호스트 포트 식별자는 HBA(호스트 버스 어댑터)의 각 호스트 포트와 연결된 고유한 전역 이름입니다.

* iSCSI(Internet Small Computer System Interface) 호스트 포트 식별자는 1자에서 233자 사이여야 합니다. iSCSI 호스트 포트 식별자는 표준 IQN 형식으로 표시됩니다(예: ' iqn.xxx.com.xxx:8b3ad`).
* Fibre Channel 및 SAS(Serial Attached SCSI)와 같은 비 iSCSI 호스트 포트 식별자는 두 문자(예: "xx:yy:zz")마다 콜론으로 구분됩니다. Fibre Channel 호스트 포트 식별자는 16자여야 합니다.




 a| 
호스트 운영 체제 유형입니다
 a| 
호스트 운영 체제 유형은 스토리지 배열의 컨트롤러가 호스트의 운영 체제(또는 버전)에 따라 I/O에 반응하는 방식을 정의하는 구성 설정입니다. 이 이름은 간단한 경우 _host type_이라고도 합니다.



 a| 
컨트롤러 호스트 포트입니다
 a| 
컨트롤러 호스트 포트는 호스트에 대한 물리적 연결을 제공하고 I/O 작업에 사용되는 컨트롤러의 포트입니다.



 a| 
LUN을 클릭합니다
 a| 
LUN(Logical Unit Number)은 호스트가 볼륨을 액세스하는 데 사용하는 주소 공간에 할당된 번호입니다. 볼륨은 LUN 형태의 용량으로 호스트에 표시됩니다.

각 호스트에는 고유한 LUN 주소 공간이 있습니다. 따라서 서로 다른 호스트에서 동일한 LUN을 사용하여 서로 다른 볼륨에 액세스할 수 있습니다.

|===