---
permalink: sm-storage/how-ssd-cache-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd cache, 
summary: 'SSD Cache 기능은 컨트롤러 기반 솔루션으로, 가장 자주 액세스하는 데이터("핫" 데이터)를 지연 시간이 짧은 SSD(Solid State Drive)에 캐싱하여 시스템 성능을 동적으로 향상합니다. SSD Cache는 호스트 읽기에만 사용됩니다.' 
---
= SSD Cache의 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSD Cache 기능은 컨트롤러 기반 솔루션으로, 가장 자주 액세스하는 데이터("핫" 데이터)를 지연 시간이 짧은 SSD(Solid State Drive)에 캐싱하여 시스템 성능을 동적으로 향상합니다. SSD Cache는 호스트 읽기에만 사용됩니다.



== SSD Cache와 운영 캐시 비교

SSD Cache는 컨트롤러의 동적 DRAM(Random Access Memory)의 기본 캐시와 함께 사용되는 보조 캐시입니다.

SSD Cache는 운영 캐시와 다르게 작동합니다.

* 운영 캐시의 경우 각 I/O 작업에서 캐시를 통해 데이터를 스테이징해야 작업을 수행할 수 있습니다.
+
운영 캐시에서 데이터는 호스트 읽기 후 DRAM에 저장됩니다.

* SSD Cache는 데이터를 캐시에 저장하여 전체 시스템 성능을 향상하는 경우에만 사용됩니다.
+
SSD Cache에서는 데이터가 볼륨에서 복사되어 두 개의 내부 RAID 볼륨(컨트롤러당 1개)에 저장됩니다. SSD Cache는 사용자가 SSD Cache를 생성할 때 자동으로 생성됩니다.



내부 RAID 볼륨은 내부 캐시 처리를 위해 사용됩니다. 이러한 볼륨은 사용자 인터페이스에 액세스하거나 표시할 수 없습니다. 그러나 이러한 두 볼륨은 스토리지 어레이에서 허용되는 총 볼륨 수에 대해 계산됩니다.



== SSD Cache의 사용 방법

지능형 캐싱은 데이터를 지연 시간이 짧은 드라이브에 배치하므로 향후 데이터 요청에 더욱 빠르게 대응할 수 있습니다. 프로그램이 캐시에 있는 데이터("캐시 적중"이라고 함)를 요청하면 지연 시간이 낮은 드라이브에서 해당 트랜잭션을 처리할 수 있습니다. 그렇지 않으면 ""캐시 누락""이 발생하고 데이터는 속도가 느린 원래 드라이브에서 액세스해야 합니다. 캐시 적중률이 높아질수록 전반적인 성능이 향상됩니다.

호스트 프로그램이 스토리지 어레이의 드라이브에 액세스하면 데이터가 SSD Cache에 저장됩니다. 호스트 프로그램에서 동일한 데이터에 다시 액세스할 때 하드 드라이브 대신 SSD Cache에서 데이터를 읽습니다. 일반적으로 액세스하는 데이터는 SSD Cache에 저장됩니다. 하드 드라이브는 SSD Cache에서 데이터를 읽을 수 없는 경우에만 액세스할 수 있습니다.

SSD Cache는 데이터를 캐시에 저장하여 전체 시스템 성능을 향상하는 경우에만 사용됩니다.

CPU가 읽기 데이터를 처리해야 하는 경우 다음 단계를 따릅니다.

. DRAM 캐시를 확인합니다.
. DRAM 캐시에서 발견되지 않으면 SSD Cache를 확인합니다.
. SSD Cache에서 찾을 수 없는 경우 하드 드라이브에서 가져옵니다. 데이터를 캐싱할 가치가 있는 것으로 판단되면 SSD Cache로 복사하십시오.




== 향상된 성능

액세스 빈도가 가장 높은 데이터(핫 스폿)를 SSD Cache에 복사하면 하드 디스크의 작동 효율성이 증가하고, 지연 시간이 단축되고, 읽기 및 쓰기 속도가 빨라집니다. 고성능 SSD를 사용하여 HDD 볼륨의 데이터를 캐싱하면 I/O 성능과 응답 시간이 향상됩니다.

간단한 볼륨 I/O 메커니즘을 사용하여 데이터를 SSD Cache로 이동하거나 SSD Cache에서 이동할 수 있습니다. 데이터를 SSD에 캐싱하고 저장한 후에는 SSD Cache에서 해당 데이터의 후속 읽기가 수행되므로 HDD 볼륨에 액세스할 필요가 없습니다.



== SSD Cache 및 드라이브 보안 기능

또한 Drive Security(보안 활성화)를 사용하는 볼륨에서 SSD Cache를 사용하려면 볼륨과 SSD Cache의 드라이브 보안 기능이 일치해야 합니다. 일치하지 않으면 볼륨이 보안 활성화되지 않습니다.



== SSD Cache 구축

SSD Cache를 구현하려면 다음을 수행합니다.

. SSD Cache를 생성합니다.
. SSD Cache를 SSD 읽기 캐싱을 구현할 볼륨과 연결합니다.


[NOTE]
====
컨트롤러의 SSD Cache를 사용하도록 할당된 볼륨은 자동 로드 밸런싱 전송을 지원하지 않습니다.

====