---
permalink: sm-storage/how-reserved-capacity-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved, capacity, 
summary: 볼륨에 대해 스냅샷 또는 비동기식 미러링 작업과 같은 복제 서비스 작업이 제공되면 예약된 용량이 자동으로 생성됩니다. 
---
= 예약 용량 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨에 대해 스냅샷 또는 비동기식 미러링 작업과 같은 복제 서비스 작업이 제공되면 예약된 용량이 자동으로 생성됩니다.

예약된 용량의 목적은 문제가 발생할 경우 이러한 볼륨에 데이터 변경 사항을 저장하는 것입니다. 볼륨과 마찬가지로 예약된 용량은 풀 또는 볼륨 그룹에서 생성됩니다.



== 예약 용량을 사용하는 서비스 객체를 복사합니다

예약 용량은 다음과 같은 복사본 서비스 개체에서 사용하는 기본 스토리지 메커니즘입니다.

* 스냅샷 그룹
* 스냅샷 볼륨 읽기/쓰기
* 정합성 보장 그룹 구성원 볼륨입니다
* 미러링 쌍 볼륨


이러한 복제 서비스 객체를 생성하거나 확장하는 경우 풀 또는 볼륨 그룹에서 새 예약 용량을 생성해야 합니다. 예약된 용량은 일반적으로 스냅샷 작업을 위한 기본 볼륨의 40%와 비동기식 미러링 작업을 위한 기본 볼륨의 20%입니다. 그러나 예약된 용량은 원래 데이터의 변경 횟수에 따라 달라집니다.



== 씬 볼륨 및 예약된 용량입니다

씬 볼륨의 경우 보고된 최대 256TiB에 도달한 경우 용량을 늘릴 수 없습니다. 씬 볼륨의 예약된 용량이 보고된 최대 용량보다 큰 크기로 설정되었는지 확인합니다. 씬 볼륨은 항상 씬 프로비저닝되므로 볼륨에 데이터를 쓸 때 용량이 할당됩니다.

풀의 씬 볼륨을 사용하여 예약된 용량을 생성하는 경우 다음 작업과 예약된 용량에 대한 결과를 검토하십시오.

* 씬 볼륨의 예약된 용량에 장애가 발생하면 씬 볼륨 자체가 Failed(실패) 상태로 자동 전환되지 않습니다. 그러나 씬 볼륨의 모든 I/O 작업은 예약된 용량 볼륨에 대한 액세스를 요구하기 때문에 입출력 작업은 항상 확인 조건을 요청 호스트로 반환합니다. 예약된 용량 볼륨의 기본 문제를 해결할 수 있는 경우 예약된 용량 볼륨이 최적의 상태로 반환되고 씬 볼륨이 다시 작동합니다.
* 기존 씬 볼륨을 사용하여 비동기식 미러링 쌍을 완료하는 경우 해당 씬 볼륨은 새로 예약된 용량 볼륨으로 다시 초기화됩니다. 초기 동기화 프로세스 중에는 운영 측의 프로비저닝된 블록만 전송됩니다.




== 용량 알림

복제 서비스 개체에는 구성 가능한 용량 경고 및 경고 임계값과 예약된 용량이 가득 찬 경우 구성 가능한 응답이 있습니다.

복제 서비스 개체 볼륨의 예약된 용량이 가득 찰 수준에 이르면 사용자에게 경고가 표시됩니다. 기본적으로 이 알림은 예약된 용량 볼륨이 75% 찼을 때 발생하지만 필요에 따라 이 알림 지점을 위 또는 아래로 조정할 수 있습니다. 이 경고가 표시되면 해당 시점에 예약된 용량 볼륨의 용량을 늘릴 수 있습니다. 이러한 관점에서 각 복제 서비스 개체를 독립적으로 구성할 수 있습니다.



== 분리된 예약 용량 볼륨

분리된 예약 용량 볼륨은 연결된 복사본 서비스 개체가 삭제되어 복사 서비스 작업을 위해 더 이상 데이터를 저장하지 않는 볼륨입니다. 복제 서비스 객체가 삭제되면 예약된 용량 볼륨도 삭제해야 합니다. 그러나 예약된 용량 볼륨을 삭제하지 못했습니다.

분리된 예약된 용량 볼륨은 호스트에서 액세스하지 않으므로 재확보할 수 있습니다. 분리된 예약 용량 볼륨을 수동으로 삭제하여 해당 용량을 다른 작업에 사용할 수 있습니다.

System Manager는 홈 페이지의 알림 영역에 "사용되지 않는 용량 재확보" 메시지와 함께 고립된 예약된 용량 볼륨에 대한 알림을 표시합니다. 사용되지 않는 용량 재확보 * 를 클릭하면 사용되지 않는 용량 재확보 대화 상자가 표시되어 고립된 예약된 용량 볼륨을 삭제할 수 있습니다.



== 예약된 용량의 특성

* 여유 용량을 충분히 확보하기 위해 볼륨 생성 중에 예약된 용량에 할당된 용량을 고려해야 합니다.
* 예약된 용량은 기본 볼륨보다 작을 수 있습니다(최소 크기는 8MiB).
* 일부 공간은 메타데이터에서 소비되지만 192KiB는 매우 작기 때문에 예약된 용량 볼륨의 크기를 결정할 때 고려하지 않아도 됩니다.
* 예약된 용량은 호스트에서 직접 읽거나 쓸 수 없습니다.
* 각 읽기/쓰기 스냅샷 볼륨, 스냅샷 그룹, 정합성 보장 그룹 구성원 볼륨 및 미러링된 쌍 볼륨에 대해 예약된 용량이 있습니다.

