---
permalink: sm-storage/how-do-i-view-and-interpret-all-ssd-cache-statistics.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd cache, statistics 
summary: SSD Cache에 대한 공칭 통계 및 세부 통계를 볼 수 있습니다. 공칭 통계는 상세 통계의 하위 집합입니다. 
---
= 모든 SSD Cache 통계를 보고 해석하려면 어떻게 해야 합니까?
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSD Cache에 대한 공칭 통계 및 세부 통계를 볼 수 있습니다. 공칭 통계는 상세 통계의 하위 집합입니다.

모든 SSD 통계를 '.csv' 파일로 내보낼 때만 상세 통계를 볼 수 있습니다. 통계를 검토 및 해석할 때는 통계의 조합을 통해 일부 해석이 파생된다는 점을 염두에 두십시오.



== 공칭 통계

SSD Cache 통계를 보려면 스토리지 [풀 및 볼륨 그룹] 메뉴를 선택합니다. 통계를 보려는 SSD Cache를 선택한 다음 menu:More [View Statistics](추가 [통계 보기])를 선택합니다. 공칭 통계는 SSD 캐시 통계 보기 대화 상자에 표시됩니다.

다음 목록에는 상세 통계의 하위 집합인 공칭 통계가 나와 있습니다.

[cols="25h,~"]
|===
| 공칭 통계 | 설명 


 a| 
읽기/쓰기
 a| 
SSD Cache 지원 볼륨에서 또는 호스트에서 데이터를 쓸 수 있는 총 호스트 읽기 수입니다. 쓰기에 상대적인 읽기를 비교합니다. 유효 SSD 캐시 작업을 위해서는 읽기 작업이 쓰기 보다 커야 합니다. 읽기-쓰기의 비율이 클수록 캐시 작업이 향상됩니다.



 a| 
캐시 적중 횟수
 a| 
캐시 적중 횟수



 a| 
캐시 적중 횟수(%)
 a| 
캐시 적중 횟수/(읽기+쓰기)에서 파생됩니다. 유효 SSD 캐시 작업의 캐시 적중률은 50%보다 커야 합니다. 작은 숫자는 다음과 같은 몇 가지 사항을 나타낼 수 있습니다.

* 읽기-쓰기의 비율이 너무 작습니다
* 읽기는 반복되지 않습니다
* 캐시 용량이 너무 작습니다




 a| 
캐시 할당(%)
 a| 
할당된 SSD Cache 스토리지의 양으로, 이 컨트롤러에서 사용할 수 있는 SSD Cache 스토리지의 백분율로 표시됩니다. 할당된 바이트/사용 가능한 바이트에서 파생됩니다. 캐시 할당 비율은 일반적으로 100%로 표시됩니다. 이 수치가 100% 미만일 경우 캐시가 워밍업되지 않았거나 SSD Cache 용량이 액세스하는 모든 데이터에 비해 크기 초과임을 의미합니다. 후자의 경우, SSD Cache 용량이 작으면 동일한 수준의 성능을 제공할 수 있습니다. 이는 캐싱된 데이터가 SSD Cache에 배치되었음을 나타내는 것이 아니라 SSD Cache에 데이터를 저장하기 위한 준비 단계일 뿐입니다.



 a| 
캐시 활용률(%)
 a| 
SSD Cache 스토리지에 할당된 SSD Cache 스토리지의 백분율로, 활성화된 볼륨의 데이터가 포함된 SSD Cache 스토리지의 양입니다. 이 값은 사용자 데이터 바이트/할당된 바이트에서 파생된 SSD Cache의 사용률 또는 밀도를 나타냅니다. 일반적으로 캐시 활용률 백분율은 100%보다 낮으며, 이보다 훨씬 낮을 수 있습니다. 이 수치는 캐시 데이터로 채워진 SSD Cache 용량의 비율을 나타냅니다. SSD Cache의 각 할당 유닛인 SSD Cache 블록이 약간 독립적인 서브블록이라는 작은 유닛으로 분리되기 때문에 이 수치는 100%보다 낮습니다. 일반적으로 숫자가 클수록 좋지만 숫자가 적더라도 성능이 크게 향상될 수 있습니다.

|===


== 자세한 통계

세부 통계는 공칭 통계와 추가 통계로 구성됩니다. 이러한 추가 통계는 공칭 통계와 함께 저장되지만, 공칭 통계와 달리 SSD 캐시 통계 보기 대화 상자에 표시되지 않습니다. 통계를 '.csv' 파일로 내보낸 후에만 상세 통계를 볼 수 있습니다.

'.csv' 파일을 볼 때, 공칭 통계 다음에 상세 통계가 나열된다는 것을 주의하시오.

[cols="25h,~"]
|===
| 자세한 통계 | 설명 


 a| 
블럭 읽기
 a| 
호스트 읽기의 블록 수입니다.



 a| 
블럭 쓰기
 a| 
호스트 쓰기의 블록 수입니다.



 a| 
전체 적중 블록
 a| 
캐시 적중의 블록 수입니다. 전체 적중 블록은 SSD Cache에서 완전히 읽은 블록 수를 나타냅니다. SSD Cache는 전체 캐시 적중률이 높은 작업의 성능에만 도움이 됩니다.



 a| 
부분 조회수
 a| 
SSD Cache에서 하나 이상의 블록이 있지만 모든 블록이 있는 호스트 읽기 수입니다. 부분 적중은 기본 볼륨에서 읽기가 처리된 SSD Cache * Miss * 입니다.



 a| 
부분 조회수 - 블록
 a| 
부분 조회수(Partial Hits)의 블록 수입니다. 부분 캐시 적중 및 부분 캐시 적중 블록은 SSD Cache에 일부 데이터만 있는 작업으로 인해 발생합니다. 이 경우 작업은 캐시된 하드 디스크 드라이브(HDD) 볼륨에서 데이터를 받아야 합니다. SSD Cache는 이러한 유형의 적중에는 성능 이점이 없습니다. 부분 캐시 적중 블록 수가 전체 캐시 적중 블록보다 많을 경우 다른 I/O 특성 유형(파일 시스템, 데이터베이스 또는 웹 서버)을 사용하면 성능이 향상될 수 있습니다. SSD 캐시가 워밍업 중일 때는 캐시 적중 횟수와 비교하여 부분 적중 횟수 및 실패 횟수가 더 많은 것으로 예상됩니다.



 a| 
실패
 a| 
SSD Cache에 블록이 없는 호스트 읽기 수입니다. SSD Cache 누락은 기본 볼륨에서 읽기가 만족스러우면 발생합니다. SSD 캐시가 워밍업 중일 때는 캐시 적중 횟수와 비교하여 부분 적중 횟수 및 실패 횟수가 더 많은 것으로 예상됩니다.



 a| 
비적중 - 블록
 a| 
비적중 블록 수입니다.



 a| 
작업 채우기(호스트 읽기)
 a| 
기본 볼륨에서 SSD Cache로 데이터가 복사된 호스트 읽기 수입니다.



 a| 
작업 채우기(호스트 읽기) - 블록
 a| 
작업 채우기(호스트 읽기)의 블록 수입니다.



 a| 
작업 채우기(호스트 쓰기)
 a| 
기본 볼륨에서 SSD Cache로 데이터가 복사된 호스트 쓰기 수입니다. 쓰기 입출력 작업의 결과로 캐시를 채우지 않는 캐시 구성 설정의 경우 작업 채우기(호스트 쓰기) 수가 0일 수 있습니다.



 a| 
작업 채우기(호스트 쓰기) - 블록
 a| 
작업 채우기(호스트 쓰기)의 블록 수입니다.



 a| 
작업을 무효화합니다
 a| 
데이터가 SSD Cache에서 무효화되거나 제거된 횟수입니다. 캐시 무효화 작업은 각 호스트 쓰기 요청, FUA(Forced Unit Access)가 포함된 각 호스트 읽기 요청, 각 확인 요청 및 기타 일부 상황에 대해 수행됩니다.



 a| 
작업 재활용
 a| 
SSD Cache 블록이 다른 기본 볼륨 및/또는 다른 LBA(논리 블록 주소 지정) 범위에 다시 사용된 횟수 효과적인 캐시 작업을 위해서는 읽기 및 쓰기 작업의 조합 수에 비해 재활용 횟수가 적어야 합니다. 재활용 작업 수가 결합된 읽기 및 쓰기 수에 근접하면 SSD 캐시는 스래싱(thrashing)입니다. 캐시 용량을 늘려야 하거나 워크로드를 SSD Cache와 함께 사용하는 것이 적합하지 않습니다.



 a| 
사용 가능한 바이트
 a| 
이 컨트롤러에서 SSD Cache에서 사용할 수 있는 바이트 수입니다.



 a| 
할당된 바이트
 a| 
이 컨트롤러가 SSD Cache에서 할당한 바이트 수입니다. SSD Cache에서 할당된 바이트가 비어 있거나 기본 볼륨의 데이터가 포함되어 있을 수 있습니다.



 a| 
사용자 데이터 바이트
 a| 
SSD Cache에서 기본 볼륨의 데이터를 포함하는 할당된 바이트 수입니다. 사용 가능한 바이트, 할당된 바이트 및 사용자 데이터 바이트는 캐시 할당 백분율 및 캐시 사용률 비율을 계산하는 데 사용됩니다.

|===