---
permalink: sm-storage/how-workloads-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, application, workloads, volume, 
summary: 볼륨을 생성할 때 특정 애플리케이션에 대한 스토리지 어레이 구성을 사용자 지정할 워크로드를 선택합니다. 
---
= 작업 부하 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨을 생성할 때 특정 애플리케이션에 대한 스토리지 어레이 구성을 사용자 지정할 워크로드를 선택합니다.

워크로드는 애플리케이션을 지원하는 스토리지 객체입니다. 애플리케이션별로 하나 이상의 워크로드 또는 인스턴스를 정의할 수 있습니다. 일부 애플리케이션의 경우 시스템에서 기본 볼륨 특성이 비슷한 볼륨을 포함하도록 워크로드를 구성합니다. 이러한 볼륨 특성은 워크로드가 지원하는 애플리케이션 유형에 따라 최적화됩니다. 예를 들어, Microsoft SQL Server 애플리케이션을 지원하는 워크로드를 생성한 다음 해당 워크로드에 대한 볼륨을 생성하는 경우 기본 볼륨 특성은 Microsoft SQL Server를 지원하도록 최적화되어 있습니다.

볼륨을 생성하는 동안 시스템에서 워크로드 사용에 대한 질문에 답하라는 메시지를 표시합니다. 예를 들어 Microsoft Exchange용 볼륨을 만드는 경우 필요한 메일박스 수, 평균 메일박스 용량 요구 사항, 원하는 데이터베이스 복제본 수를 묻는 메시지가 표시됩니다. 시스템에서는 이 정보를 사용하여 최적의 볼륨 구성을 생성합니다. 이 구성은 필요에 따라 편집할 수 있습니다. 선택적으로 볼륨 생성 순서에서 이 단계를 건너뛸 수 있습니다.



== 워크로드의 유형입니다

두 가지 유형의 워크로드, 즉 애플리케이션별 워크로드와 기타 워크로드를 생성할 수 있습니다.

* * 응용 프로그램별 *. 애플리케이션별 워크로드를 사용하여 볼륨을 생성하는 경우, 애플리케이션 워크로드 I/O와 애플리케이션 인스턴스의 기타 트래픽 간의 경합을 최소화하기 위해 최적화된 볼륨 구성을 권장할 수 있습니다. I/O 유형, 세그먼트 크기, 컨트롤러 소유권, 읽기 및 쓰기 캐시와 같은 볼륨 특성은 자동으로 권장 사항이며 다음과 같은 애플리케이션 유형에 대해 생성되는 워크로드에 최적화되어 있습니다.
+
** Microsoft ® SQL Server ™ 를 참조하십시오
** Microsoft ® Exchange Server ™ 를 참조하십시오
** 비디오 감시 애플리케이션
** VMware ESXi ™ (가상 머신 파일 시스템과 함께 사용할 볼륨용)
+
볼륨 추가/편집 대화 상자를 사용하여 권장 볼륨 구성을 검토하고 시스템 권장 볼륨 및 특성을 편집, 추가 또는 삭제할 수 있습니다.



* * 기타 * (또는 특정 볼륨 생성을 지원하지 않는 애플리케이션). 다른 워크로드는 볼륨 구성을 사용하며, 특정 애플리케이션과 연결되지 않은 워크로드를 생성하려는 경우 또는 스토리지 어레이에서 사용하려는 애플리케이션에 대한 최적화 기능이 시스템에 내장되어 있지 않은 경우 수동으로 지정해야 합니다. 볼륨 추가/편집 대화 상자를 사용하여 볼륨 구성을 수동으로 지정해야 합니다.




== 애플리케이션 및 워크로드 뷰

애플리케이션 및 워크로드를 보려면 SANtricity 시스템 관리자를 시작하십시오. 이 인터페이스를 통해 다음과 같은 몇 가지 방법으로 애플리케이션별 워크로드와 관련된 정보를 볼 수 있습니다.

* 볼륨 타일에서 * 애플리케이션 및 워크로드 * 탭을 선택하여 스토리지 어레이의 볼륨을 워크로드별로 그룹화하고 워크로드가 연결된 애플리케이션 유형을 볼 수 있습니다.
* 성능 타일에서 * 애플리케이션 및 워크로드 * 탭을 선택하여 논리적 객체에 대한 성능 메트릭(지연 시간, IOPS 및 MBs)을 볼 수 있습니다. 오브젝트는 애플리케이션 및 관련 워크로드별로 그룹화됩니다. 이 성능 데이터를 정기적으로 수집하면 기준 측정을 설정하고 추세를 분석할 수 있습니다. 이렇게 하면 I/O 성능과 관련된 문제를 조사하는 데 도움이 됩니다.

