---
permalink: sm-storage/how-volumes-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, copy, 
summary: 볼륨은 스토리지 어레이에서 스토리지 공간을 관리하고 구성하는 데이터 컨테이너입니다. 
---
= 볼륨 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨은 스토리지 어레이에서 스토리지 공간을 관리하고 구성하는 데이터 컨테이너입니다.

스토리지 어레이에서 사용 가능한 스토리지 용량에서 볼륨을 생성하여 시스템 리소스를 쉽게 구성 및 사용할 수 있습니다. 이 개념은 컴퓨터에서 폴더/디렉터리를 사용하여 쉽고 빠르게 액세스할 수 있도록 파일을 구성하는 것과 비슷합니다.

볼륨은 호스트에서 볼 수 있는 유일한 데이터 계층입니다. SAN 환경에서 볼륨은 호스트에 표시되는 LUN(Logical Unit Number)에 매핑됩니다. LUN은 FC, iSCSI 및 SAS를 비롯하여 스토리지 어레이에서 지원하는 하나 이상의 호스트 액세스 프로토콜을 사용하여 액세스할 수 있는 사용자 데이터를 저장합니다.



== 풀 및 볼륨 그룹에서 생성할 수 있는 볼륨 유형입니다

볼륨은 풀 또는 볼륨 그룹에서 용량을 그립니다. 스토리지 시스템에 있는 풀 또는 볼륨 그룹에서 다음 유형의 볼륨을 생성할 수 있습니다.

* * from pool * -- 풀에서 _fully-provisioned(thick) volumes_or_thin-provisioned(thin) volumes. _ 로 볼륨을 생성할 수 있습니다
+
[NOTE]
====
System Manager 인터페이스에서는 씬 볼륨을 생성하는 옵션을 제공하지 않습니다. 씬 볼륨을 생성하려면 CLI(Command Line Interface)를 사용합니다.

====
* * 볼륨 그룹에서 * -- 볼륨 그룹에서 _완전히 프로비저닝된(일반) 볼륨으로만 볼륨을 생성할 수 있습니다.


일반 볼륨 및 씬 볼륨은 스토리지 배열에서 다음과 같은 다양한 방식으로 용량을 그립니다.

* 볼륨을 생성할 때 일반 볼륨의 용량이 할당됩니다.
* 씬 볼륨의 용량은 볼륨에 쓸 때 데이터로 할당됩니다.


씬 프로비저닝은 낭비되는 할당 용량을 방지하고 초기 스토리지 비용을 줄여 줍니다. 그러나 일반 볼륨이 생성될 때 모든 스토리지가 한 번에 할당되므로 전체 프로비저닝의 이점은 지연 시간이 줄어듭니다.

[NOTE]
====
EF600 및 EF300 스토리지 시스템은 씬 프로비저닝을 지원하지 않습니다.

====


== 볼륨의 특성

풀 또는 볼륨 그룹의 각 볼륨은 어떤 유형의 데이터가 저장되어 있는지 기준으로 고유한 개별 특성을 가질 수 있습니다. 이러한 특징에는 다음이 포함됩니다.

* * 세그먼트 크기 * -- 세그먼트는 스토리지 어레이가 스트라이프의 다음 드라이브(RAID 그룹)로 이동하기 전에 드라이브에 저장되는 데이터의 양(KB)입니다. 세그먼트 크기는 볼륨 그룹의 용량과 같거나 그보다 작습니다. 세그먼트 크기가 고정되어 풀의 경우 변경할 수 없습니다.
* * 용량 * -- 풀 또는 볼륨 그룹에서 사용 가능한 용량을 사용하여 볼륨을 생성합니다. 볼륨을 생성하기 전에 풀 또는 볼륨 그룹이 이미 있어야 하며 볼륨을 생성할 수 있는 충분한 가용 용량이 있어야 합니다.
* * 컨트롤러 소유권 * -- 모든 스토리지 어레이에는 하나 또는 두 개의 컨트롤러가 있을 수 있습니다. 단일 컨트롤러 어레이에서 볼륨 워크로드는 단일 컨트롤러에서 관리합니다. 듀얼 컨트롤러 어레이에서 볼륨은 볼륨을 "소유"하는 기본 컨트롤러(A 또는 B)를 갖게 됩니다. 이중 컨트롤러 구성에서는 컨트롤러 간에 워크로드가 이동할 때 자동 로드 밸런싱 기능을 사용하여 볼륨 소유권을 자동으로 조정하여 로드 밸런싱 문제를 해결합니다. 자동 로드 밸런싱은 자동화된 I/O 워크로드 밸런싱을 제공하고 호스트에서 들어오는 I/O 트래픽을 두 컨트롤러 간에 동적으로 관리 및 밸런싱합니다.
* * 볼륨 할당 * -- 볼륨을 생성할 때 또는 나중에 호스트에 볼륨에 대한 액세스를 제공할 수 있습니다. 모든 호스트 액세스는 LUN(Logical Unit Number)을 통해 관리됩니다. 호스트는 다시 볼륨에 할당된 LUN을 감지합니다. 여러 호스트에 볼륨을 할당하는 경우 클러스터링 소프트웨어를 사용하여 모든 호스트에서 볼륨을 사용할 수 있는지 확인합니다.
+
호스트 유형에는 호스트가 액세스할 수 있는 볼륨 수에 대한 특정 제한이 있을 수 있습니다. 특정 호스트에서 사용할 볼륨을 생성할 때 이 제한 사항을 염두에 두십시오.

* * 설명적 이름 * - - - 어떤 이름을 원하든 볼륨의 이름을 지정할 수 있지만 이름을 설명하는 것이 좋습니다.


볼륨 생성 중에 각 볼륨에 용량이 할당되며 이름, 세그먼트 크기(볼륨 그룹만 해당), 컨트롤러 소유권 및 볼륨-호스트 할당이 할당됩니다. 볼륨 데이터는 필요에 따라 컨트롤러 전체에서 자동으로 로드 밸런싱됩니다.
