---
permalink: sm-storage/increase-capacity-of-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, increase, capacity, volume 
summary: '풀 또는 볼륨 그룹에서 사용할 수 있는 가용 용량을 사용하여 볼륨의 보고된 용량(호스트에 보고된 용량)을 늘릴 수 있습니다.' 
---
= 볼륨의 용량을 늘립니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
풀 또는 볼륨 그룹에서 사용할 수 있는 가용 용량을 사용하여 볼륨의 보고된 용량(호스트에 보고된 용량)을 늘릴 수 있습니다.

.시작하기 전에
* 볼륨의 연결된 풀 또는 볼륨 그룹에서 충분한 가용 용량을 사용할 수 있습니다.
* 볼륨은 최적이며 수정 상태가 아닙니다.
* 씬 볼륨의 보고된 최대 용량 256TiB에 도달하지 않았습니다.
* 볼륨에서 사용 중인 핫 스페어 드라이브가 없습니다. (볼륨 그룹의 볼륨에만 적용됩니다.)



NOTE: 한 번에 볼륨 용량을 최대 128TiB까지만 확장할 수 있습니다.

.이 작업에 대해
이 풀 또는 볼륨 그룹의 다른 볼륨에 대해서는 향후 용량 요구 사항을 염두에 두십시오. 스냅샷 이미지, 스냅샷 볼륨 또는 원격 미러를 생성할 수 있는 여유 용량을 충분히 확보하십시오.

[NOTE]
====
볼륨 용량 증가는 특정 운영 체제에서만 지원됩니다. 지원되지 않는 호스트 운영 체제에서 볼륨 용량을 늘릴 경우 확장된 용량을 사용할 수 없으며 원래 볼륨 용량을 복원할 수 없습니다.

====
.단계
. Storage [Volumes](저장소 [볼륨]) 메뉴를 선택합니다.
. 용량을 늘릴 볼륨을 선택한 다음 * 용량 증가 * 를 선택합니다.
+
용량 증가 확인 대화 상자가 나타납니다.

. 계속하려면 * 예 * 를 선택하십시오.
+
보고된 용량 증가 대화 상자가 나타납니다.

+
이 대화 상자에는 볼륨의 현재 보고된 용량과 볼륨의 연결된 풀 또는 볼륨 그룹에서 사용 가능한 가용 용량이 표시됩니다.

. 보고된 용량을 현재 사용 가능한 보고된 용량에 추가하려면 * 보고 용량 증가... * 상자를 사용합니다. 용량 값을 변경하여 메비바이트(MiB), 기비바이트(GiB) 또는 테비바이트(TiB)로 표시할 수 있습니다.
. 증가 * 를 클릭합니다.


.결과
* System Manager는 선택에 따라 볼륨의 용량을 늘립니다.
* Home[View Operations in Progress] 메뉴를 선택하여 선택한 볼륨에 대해 현재 실행 중인 용량 증가 작업의 진행률을 확인합니다. 이 작업은 시간이 오래 걸릴 수 있으며 시스템 성능에 영향을 줄 수 있습니다.


.작업을 마친 후
볼륨 용량을 확장한 후에는 파일 시스템 크기를 수동으로 늘려야 합니다. 이 방법은 사용 중인 파일 시스템에 따라 다릅니다. 자세한 내용은 호스트 운영 체제 설명서를 참조하십시오.
