---
permalink: sm-storage/increase-reserved-capacity.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, increase, reserved, capacity 
summary: 스토리지 오브젝트의 모든 복제 서비스 작업에 사용되는 물리적으로 할당된 용량인 예약 용량을 늘릴 수 있습니다. 
---
= 예약된 용량을 늘립니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 오브젝트의 모든 복제 서비스 작업에 사용되는 물리적으로 할당된 용량인 예약 용량을 늘릴 수 있습니다.

스냅샷 작업의 경우 일반적으로 기본 볼륨의 40%이며, 비동기식 미러링 작업의 경우 일반적으로 기본 볼륨의 20%입니다. 일반적으로 스토리지 객체의 예약된 용량이 가득 차고 있다는 경고가 표시되면 예약 용량을 늘립니다.

.시작하기 전에
* 풀 또는 볼륨 그룹의 볼륨은 최적 상태여야 하며 수정 상태가 아니어야 합니다.
* 용량을 늘리기 위해 사용할 풀 또는 볼륨 그룹에 사용 가능한 용량이 있어야 합니다.
+
풀 또는 볼륨 그룹에 사용 가능한 용량이 없는 경우, 할당되지 않은 용량을 미사용 드라이브 형식으로 풀 또는 볼륨 그룹에 추가할 수 있습니다.



.이 작업에 대해
다음과 같은 스토리지 객체에 대해 예약 용량을 8GiB씩 늘릴 수 있습니다.

* 스냅샷 그룹
* 스냅샷 볼륨
* 정합성 보장 그룹 구성원 볼륨입니다
* 미러링 쌍 볼륨


운영 볼륨에 많은 변경이 있을 것으로 생각되거나 특정 복사 서비스 작업의 수명이 매우 길 경우 높은 비율을 사용하십시오.

[NOTE]
====
읽기 전용인 스냅샷 볼륨에 대해 예약된 용량을 늘릴 수 없습니다. 읽기-쓰기의 스냅샷 볼륨에만 예약된 용량이 필요합니다.

====
.단계
. 스토리지 [풀 및 볼륨 그룹] 메뉴를 선택합니다.
. Reserved Capacity * 탭을 선택합니다.
. 예약된 용량을 늘릴 스토리지 객체를 선택한 다음 * 용량 증가 * 를 클릭합니다.
+
예약된 용량 증가 대화 상자가 나타납니다.

. 스피너 상자를 사용하여 용량 비율을 조정합니다.
+
선택한 스토리지 객체가 포함된 풀 또는 볼륨 그룹에 사용 가능한 용량이 없고 스토리지 배열에 할당되지 않은 용량이 있는 경우 새 풀 또는 볼륨 그룹을 생성할 수 있습니다. 그런 다음 해당 풀 또는 볼륨 그룹의 새 가용 용량을 사용하여 이 작업을 다시 시도할 수 있습니다.

. 증가 * 를 클릭합니다.


.결과
System Manager는 다음 작업을 수행합니다.

* 스토리지 객체에 대한 예약 용량을 늘립니다.
* 새로 추가된 예약된 용량을 표시합니다.

