---
permalink: sm-storage/interpret-performance-data.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, interpret, performance data 
summary: 성능 데이터를 통해 스토리지 어레이의 성능을 튜닝할 수 있습니다. 
---
= 성능 데이터를 해석합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 데이터를 통해 스토리지 어레이의 성능을 튜닝할 수 있습니다.

성능 데이터를 해석할 때는 여러 요소가 스토리지 어레이의 성능에 영향을 미친다는 점을 염두에 두십시오. 다음 표에서는 고려해야 할 주요 영역에 대해 설명합니다.

[cols="25h,~"]
|===
| 성능 데이터 | 성능 튜닝에 미치는 영향 


 a| 
지연 시간(밀리초 또는 ms)
 a| 
특정 객체의 입출력 작업을 모니터링합니다.

병목 현상이 있는 개체를 식별할 수 있습니다.

* 볼륨 그룹이 여러 볼륨 간에 공유되는 경우, 개별 볼륨은 드라이브의 순차적 성능을 개선하고 지연 시간을 단축하기 위해 자체 볼륨 그룹이 필요할 수 있습니다.
* 풀을 사용할 경우 지연 시간이 더 길어지며, 드라이브 간에 워크로드가 불균일하여 지연 시간의 가치가 더 적고 일반적으로 더 높습니다.
* 드라이브 유형과 속도가 지연 시간에 영향을 미칩니다. 랜덤 I/O를 사용하면 회전식 드라이브를 더욱 빠르게 디스크의 서로 다른 위치로 이동하는 데 드는 시간이 줄어듭니다.
* 드라이브 수가 너무 적으면 명령 대기 시간이 많아지고 드라이브에서 명령을 처리하는 데 더 오랜 시간이 소요되어 시스템의 일반적인 지연 시간이 길어집니다.
* I/O가 클수록 데이터 전송에 따른 추가 시간 때문에 지연 시간이 길어집니다.
* 지연 시간이 길수록 I/O 패턴이 자연에서 랜덤으로 나타날 수 있습니다. 랜덤 I/O가 있는 드라이브는 순차적 스트림을 사용하는 드라이브보다 지연 시간이 더 짧습니다.
* 공통 볼륨 그룹의 드라이브 또는 볼륨 간 지연 시간 차이가 있으면 드라이브 속도가 느릴 수 있습니다.




 a| 
IOPS
 a| 
IOPS 또는 IO/초(Input/Output Operation per Second)에 영향을 주는 요인은 다음과 같습니다.

* 액세스 패턴(랜덤 또는 순차)
* I/O 크기
* RAID 레벨
* 캐시 블록 크기
* 읽기 캐싱 설정 여부
* 쓰기 캐싱 설정 여부
* 동적 캐시 읽기 프리페치
* 세그먼트 크기
* 볼륨 그룹 또는 스토리지 배열의 드라이브 수입니다


캐시 적중률이 높을수록 입출력 속도가 높아집니다. 쓰기 캐시가 설정된 경우 해제된 경우에 비해 쓰기 입출력 속도가 더 높습니다. 개별 볼륨에 대해 쓰기 캐시를 사용할지 여부를 결정할 때 현재 IOPS와 최대 IOPS를 확인합니다. 랜덤 I/O 패턴보다 순차적 I/O 패턴의 속도가 더 높습니다. I/O 패턴과 상관없이 쓰기 캐시를 설정하여 I/O 속도를 최대화하고 애플리케이션 응답 시간을 단축합니다.

볼륨의 IOPS 통계에서 세그먼트 크기를 변경하여 성능이 향상된 것을 확인할 수 있습니다. 최적의 세그먼트 크기를 결정하거나 파일 시스템 크기 또는 데이터베이스 블록 크기를 사용하십시오.



 a| 
MIB/s
 a| 
전송 또는 처리 속도는 애플리케이션 입출력 크기 및 입출력 속도에 따라 결정됩니다. 일반적으로 애플리케이션 입출력 요청이 작을수록 전송 속도는 낮아지지만 입출력 속도가 빨라지고 응답 시간이 단축됩니다. 애플리케이션 I/O 요청이 클수록 처리 속도가 더 높아질 수 있습니다.

일반적인 애플리케이션 I/O 패턴을 이해하면 특정 스토리지 어레이에 대한 최대 I/O 전송 속도를 결정하는 데 도움이 됩니다.



 a| 
CPU
 a| 
이 값은 사용 중인 처리 용량의 백분율입니다.

동일한 유형의 객체에 대한 CPU 사용량의 차이를 확인할 수 있습니다. 예를 들어, 한 컨트롤러의 CPU 사용량이 무겁거나 시간이 지남에 따라 증가하는 반면 다른 컨트롤러의 CPU 사용량은 더 가볍고 안정적입니다. 이 경우 하나 이상의 볼륨에서 컨트롤러 소유권을 더 낮은 CPU 비율의 컨트롤러로 변경할 수 있습니다.

스토리지 배열의 CPU를 모니터링할 수 있습니다. 애플리케이션 성능이 저하되면서 CPU가 시간이 지나면서 계속 증가하는 경우 스토리지 어레이를 추가해야 할 수 있습니다. 기업에 스토리지 어레이를 추가하면 허용되는 성능 수준에서 애플리케이션 요구를 계속해서 충족할 수 있습니다.



 a| 
여유 공간
 a| 
여유 공간은 컨트롤러, 컨트롤러 호스트 채널 및 컨트롤러 드라이브 채널의 나머지 성능 기능을 나타냅니다. 이 값은 백분율로 표현되며 이러한 개체가 제공할 수 있는 최대 성능과 현재 성능 수준 사이의 간격을 나타냅니다.

* 컨트롤러의 경우 여유 공간은 최대 IOPS의 비율입니다.
* 채널의 여유 공간은 최대 처리량 또는 MiB/s의 비율입니다 이 계산에는 읽기 처리량, 쓰기 처리량, 양방향 처리량이 포함됩니다.


|===