---
permalink: sm-storage/overview-pools-volume-groups.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, pools, volume groups 
summary: 스토리지 어레이의 할당되지 않은 드라이브 서브셋에서 논리적 스토리지 용량을 생성할 수 있습니다. 이 논리적 용량은 환경의 요구 사항에 따라 풀 또는 볼륨 그룹의 형태를 취할 수 있습니다. 
---
= 풀 및 볼륨 그룹 개요
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 어레이의 할당되지 않은 드라이브 서브셋에서 논리적 스토리지 용량을 생성할 수 있습니다. 이 논리적 용량은 환경의 요구 사항에 따라 풀 또는 볼륨 그룹의 형태를 취할 수 있습니다.



== 풀 및 볼륨 그룹이란 무엇입니까?

A_POOL_은 논리적으로 그룹화된 드라이브 집합입니다. 볼륨 그룹 _ 은(는) 공유 특성을 가진 볼륨의 컨테이너입니다. 풀 또는 볼륨 그룹을 사용하여 호스트에서 액세스할 수 있는 볼륨을 생성할 수 있습니다.

자세한 내용:

* link:how-pools-and-volume-groups-work.html["풀 및 볼륨 그룹의 작동 방식"]
* link:capacity-terminology.html["용량 용어"]
* link:decide-to-use-a-pool-or-volume-group.html["풀 또는 볼륨 그룹을 사용할지 여부를 결정합니다"]




== 풀을 생성하려면 어떻게 해야 합니까?

스토리지 어레이에서 할당되지 않은 용량을 감지하면 System Manager에서 자동으로 풀을 생성하도록 허용할 수 있습니다. 또는 자동 생성으로 최적의 구성을 확인할 수 없는 경우 메뉴에서 스토리지 [풀 및 볼륨 그룹] 풀을 수동으로 생성할 수 있습니다.

자세한 내용:

* link:automatic-versus-manual-pool-creation.html["자동 및 수동 풀 생성"]
* link:create-pool-automatically.html["풀을 자동으로 생성합니다"]
* link:create-pool-manually.html["풀을 수동으로 생성합니다"]
* link:add-capacity-to-a-pool-or-volume-group.html["풀 또는 볼륨 그룹에 용량을 추가합니다"]




== 볼륨 그룹을 어떻게 생성합니까?

스토리지 [풀 및 볼륨 그룹] 메뉴에서 볼륨 그룹을 생성할 수 있습니다.

자세한 내용:

* link:create-volume-group.html["볼륨 그룹을 생성합니다"]
* link:add-capacity-to-a-pool-or-volume-group.html["풀 또는 볼륨 그룹에 용량을 추가합니다"]




== 관련 정보

풀 및 볼륨 그룹과 관련된 개념에 대해 자세히 알아보십시오.

* link:how-reserved-capacity-works.html["예약 용량 작동 방식"]
* link:how-ssd-cache-works.html["SSD Cache의 작동 방식"]

