---
permalink: sm-storage/performance-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, performance, terms 
summary: 스토리지 어레이에 적용되는 성능 조건에 대해 알아보십시오. 
---
= 성능 용어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 어레이에 적용되는 성능 조건에 대해 알아보십시오.

[cols="25h,~"]
|===
| 기간 | 설명 


 a| 
응용 프로그램
 a| 
애플리케이션은 SQL 또는 Exchange와 같은 소프트웨어 프로그램입니다.



 a| 
CPU
 a| 
CPU가 "중앙 처리 장치"에 대해 짧습니다. CPU는 사용 중인 스토리지 시스템의 처리 용량 비율을 나타냅니다.



 a| 
호스트
 a| 
호스트는 스토리지 배열의 볼륨에 입출력을 전송하는 서버입니다.



 a| 
IOPS
 a| 
IOPS는 초당 입출력 작업의 약어입니다.



 a| 
지연 시간
 a| 
지연 시간은 읽기 또는 쓰기 명령에 대한 요청과 호스트 또는 스토리지 시스템의 응답 사이의 시간 간격입니다.



 a| 
LUN을 클릭합니다
 a| 
LUN(Logical Unit Number)은 호스트가 볼륨을 액세스하는 데 사용하는 주소 공간에 할당된 번호입니다. 볼륨은 LUN 형태의 용량으로 호스트에 표시됩니다.

각 호스트에는 고유한 LUN 주소 공간이 있습니다. 따라서 서로 다른 호스트에서 동일한 LUN을 사용하여 서로 다른 볼륨에 액세스할 수 있습니다.



 a| 
MIB
 a| 
MIB는 mibibyte(mega binary byte)의 약어입니다. 1MiB는 220 또는 1,048,576바이트입니다. 기본 10 값을 나타내는 MB와 비교합니다. 1MB는 1,024바이트입니다.



 a| 
오브젝트
 a| 
개체는 논리적 또는 물리적 스토리지 구성 요소입니다.

논리적 객체에는 볼륨 그룹, 풀 및 볼륨이 포함됩니다. 물리적 객체에는 스토리지 어레이, 어레이 컨트롤러, 호스트 및 드라이브가 포함됩니다.



 a| 
수영장
 a| 
풀은 논리적으로 그룹화된 드라이브 집합입니다. 풀을 사용하여 호스트에서 액세스할 수 있는 볼륨을 하나 이상 생성할 수 있습니다. (풀 또는 볼륨 그룹에서 볼륨을 생성하는 경우)



 a| 
읽기
 a| 
읽기 작업은 "읽기 작업"에 대한 짧은 것으로, 호스트가 스토리지 시스템에서 데이터를 요청할 때 발생합니다.



 a| 
볼륨
 a| 
볼륨은 애플리케이션, 데이터베이스 및 파일 시스템이 데이터를 저장하는 컨테이너입니다. 호스트가 스토리지의 스토리지를 액세스할 수 있도록 생성되는 논리적 구성 요소입니다.

볼륨은 풀 또는 볼륨 그룹에서 사용할 수 있는 용량에서 생성됩니다. 볼륨에 정의된 용량이 있습니다. 볼륨이 두 개 이상의 드라이브로 구성될 수 있지만 볼륨은 호스트에 하나의 논리적 구성 요소로 나타납니다.



 a| 
볼륨 이름입니다
 a| 
볼륨 이름은 볼륨 생성 시 볼륨에 할당된 문자열, 기본 이름을 그대로 사용하거나 볼륨에 저장된 데이터의 유형을 나타내는 보다 설명이 포함된 이름을 제공할 수 있습니다.



 a| 
볼륨 그룹
 a| 
볼륨 그룹은 공유 특성을 가진 볼륨의 컨테이너입니다. 볼륨 그룹의 용량과 RAID 레벨이 정의되어 있습니다. 볼륨 그룹을 사용하여 호스트에서 액세스할 수 있는 볼륨을 하나 이상 생성할 수 있습니다. 볼륨 그룹 또는 풀에서 볼륨을 생성합니다.



 a| 
워크로드
 a| 
워크로드는 애플리케이션을 지원하는 스토리지 객체입니다. 애플리케이션별로 하나 이상의 워크로드 또는 인스턴스를 정의할 수 있습니다. 일부 애플리케이션의 경우 시스템에서 기본 볼륨 특성이 비슷한 볼륨을 포함하도록 워크로드를 구성합니다. 이러한 볼륨 특성은 워크로드가 지원하는 애플리케이션 유형에 따라 최적화됩니다. 예를 들어, Microsoft SQL Server 애플리케이션을 지원하는 워크로드를 생성한 다음 해당 워크로드에 대한 볼륨을 생성하는 경우 기본 볼륨 특성은 Microsoft SQL Server를 지원하도록 최적화되어 있습니다.



 a| 
쓰기
 a| 
"쓰기 작업"에 대한 쓰기 작업이 짧아 호스트에서 스토리지에 데이터를 전송할 때 쓰기가 짧습니다.

|===