---
permalink: sm-storage/re-create-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, re-create, snapshot, volume 
summary: 이전에 해제한 스냅샷 볼륨 또는 스냅샷 정합성 보장 그룹 스냅샷 볼륨을 다시 생성할 수 있습니다. 스냅샷 볼륨을 다시 생성하는 데 새 볼륨을 생성하는 것보다 시간이 적게 소요됩니다. 
---
= 스냅샷 볼륨을 다시 생성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이전에 해제한 스냅샷 볼륨 또는 스냅샷 정합성 보장 그룹 스냅샷 볼륨을 다시 생성할 수 있습니다. 스냅샷 볼륨을 다시 생성하는 데 새 볼륨을 생성하는 것보다 시간이 적게 소요됩니다.

.시작하기 전에
* 스냅샷 볼륨은 Optimal(최적) 또는 Disabled(비활성화) 상태여야 합니다.
* 모든 구성원 스냅샷 볼륨은 사용 안 함 상태여야 스냅샷 정합성 보장 그룹 스냅샷 볼륨을 다시 생성할 수 있습니다.


.이 작업에 대해
개별 구성원 스냅샷 볼륨을 다시 생성할 수 없습니다. 전체 스냅샷 정합성 보장 그룹 스냅샷 볼륨만 다시 생성할 수 있습니다.

[NOTE]
====
스냅샷 볼륨 또는 스냅샷 정합성 보장 그룹 스냅샷 볼륨이 온라인 복제 관계의 일부인 경우 볼륨에 대해 다시 생성 옵션을 수행할 수 없습니다.

====
.단계
. 스토리지 [스냅샷] 메뉴를 선택합니다.
. Snapshot Volumes * 탭을 선택합니다.
+
Snapshot Volumes 테이블이 나타나고 스토리지 어레이와 연결된 모든 스냅샷 볼륨이 표시됩니다.

. 다시 생성할 스냅샷 볼륨을 선택한 다음 메뉴(Uncommon Tasks[recreate])를 선택합니다.
+
스냅샷 볼륨 다시 생성 대화 상자가 나타납니다.

. 다음 옵션 중 하나를 선택합니다.
+
** * 볼륨 <name> * 에서 생성된 기존 스냅샷 이미지입니다
+
스냅샷 볼륨을 다시 생성할 기존 스냅샷 이미지를 나타내려면 이 옵션을 선택합니다.

** * 볼륨 <name> * 의 새(즉시) 스냅샷 이미지
+
스냅샷 볼륨을 다시 생성할 새 스냅샷 이미지를 생성하려면 이 옵션을 선택합니다.



. 재생성 * 을 클릭합니다.


.결과
System Manager는 다음 작업을 수행합니다.

* 연결된 스냅샷 저장소 볼륨에서 모든 '쓰기' 데이터를 삭제합니다.
* 스냅샷 볼륨 또는 스냅샷 정합성 보장 그룹 스냅샷 볼륨 매개 변수는 이전에 비활성화된 볼륨 매개 변수와 동일하게 유지됩니다.
* 스냅샷 볼륨 또는 스냅샷 정합성 보장 그룹 스냅샷 볼륨의 원래 이름을 유지합니다.

