---
permalink: sm-storage/requirements-and-guidelines-for-snapshots.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, requirements, guidelines, snapshots 
summary: 스냅샷을 생성 및 사용할 때는 다음 요구 사항 및 지침을 검토하십시오. 
---
= 스냅샷 요구 사항 및 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷을 생성 및 사용할 때는 다음 요구 사항 및 지침을 검토하십시오.



== 스냅샷 이미지 및 스냅샷 그룹

* 각 스냅샷 이미지는 정확히 하나의 스냅샷 그룹에 연결됩니다.
* 연결된 객체에 대해 예약된 스냅샷 또는 인스턴트 스냅샷 이미지를 처음 생성할 때 스냅샷 그룹이 생성됩니다. 이렇게 하면 예약된 용량이 생성됩니다.
+
풀 및 볼륨 그룹 페이지에서 스냅샷 그룹을 볼 수 있습니다.

* 스토리지 배열이 오프라인이거나 전원이 꺼진 경우에는 예약된 스냅샷 이미지가 발생하지 않습니다.
* 스냅샷 스케줄이 있는 스냅샷 그룹을 삭제하면 스냅샷 스케줄도 삭제됩니다.
* 더 이상 필요하지 않은 스냅샷 볼륨이 있는 경우 이를 삭제하는 대신 연결된 예약된 용량과 함께 다시 사용할 수 있습니다. 이렇게 하면 동일한 기본 볼륨의 다른 스냅샷 볼륨이 생성됩니다. 스냅샷 이미지가 동일한 기본 볼륨에 있는 경우 스냅샷 볼륨 또는 스냅샷 정합성 보장 그룹 스냅샷 볼륨을 동일한 스냅샷 이미지 또는 다른 스냅샷 이미지와 다시 연결할 수 있습니다.




== 스냅샷 정합성 보장 그룹

* 스냅샷 정합성 보장 그룹은 스냅샷 정합성 보장 그룹의 구성원인 각 볼륨에 대해 하나의 스냅샷 그룹을 포함합니다.
* 스냅샷 정합성 보장 그룹을 하나의 스케줄에만 연결할 수 있습니다.
* 스냅샷 스케줄이 있는 스냅샷 정합성 보장 그룹을 삭제하면 스냅샷 스케줄도 삭제됩니다.
* 스냅샷 정합성 보장 그룹에 연결된 스냅샷 그룹은 개별적으로 관리할 수 없습니다. 대신 스냅샷 정합성 보장 그룹 레벨에서 관리 작업(스냅샷 이미지 생성, 스냅샷 이미지 또는 스냅샷 그룹 삭제, 스냅샷 이미지 롤백)을 수행해야 합니다.




== 기본 볼륨

* 스냅샷 볼륨은 연결된 기본 볼륨과 동일한 DA(Data Assurance) 및 보안 설정을 가져야 합니다.
* 장애가 발생한 기본 볼륨의 스냅샷 볼륨은 생성할 수 없습니다.
* 기본 볼륨이 볼륨 그룹에 있는 경우 연결된 스냅샷 정합성 보장 그룹의 구성원 볼륨은 풀 또는 볼륨 그룹에 상주할 수 있습니다.
* 기본 볼륨이 풀에 있는 경우 연결된 스냅샷 정합성 보장 그룹의 모든 구성원 볼륨은 기본 볼륨과 동일한 풀에 상주해야 합니다.




== 예약된 용량입니다

* 예약 용량은 하나의 기본 볼륨에만 연결됩니다.
* 스케줄을 사용하면 많은 수의 스냅샷 이미지가 생성될 수 있습니다. 예약된 스냅샷에 대한 예약된 용량이 충분한지 확인합니다.
* 스냅샷 정합성 보장 그룹에 대해 예약된 용량 볼륨은 스냅샷 정합성 보장 그룹 구성원 볼륨에 대해 연결된 기본 볼륨과 동일한 DA(Data Assurance) 및 보안 설정을 가져야 합니다.




== 보류 중인 스냅샷 이미지

스냅샷 이미지 생성은 다음과 같은 조건에서 보류 상태로 유지될 수 있습니다.

* 이 스냅샷 이미지가 포함된 기본 볼륨은 비동기식 미러 그룹의 구성원입니다.
* 기본 볼륨이 현재 동기화 작업 중입니다. 동기화 작업이 완료되는 즉시 스냅샷 이미지 생성이 완료됩니다.




== 최대 스냅샷 이미지 수입니다

* 볼륨이 스냅샷 정합성 보장 그룹의 구성원인 경우 System Manager는 해당 구성원 볼륨에 대한 스냅샷 그룹을 생성합니다. 이 스냅샷 그룹은 기본 볼륨당 허용되는 최대 스냅샷 그룹 수에 대해 계산됩니다.
* 스냅샷 그룹 또는 스냅샷 정합성 보장 그룹에 스냅샷 이미지를 생성하려고 하지만 연결된 그룹이 최대 스냅샷 이미지 수에 도달했을 경우 다음 두 가지 옵션을 사용할 수 있습니다.
+
** 스냅샷 그룹 또는 스냅샷 정합성 보장 그룹에 대해 자동 삭제를 설정합니다.
** 스냅샷 그룹 또는 스냅샷 정합성 보장 그룹에서 하나 이상의 스냅샷 이미지를 수동으로 삭제하고 작업을 다시 시도하십시오.






== 자동 삭제

스냅샷 그룹 또는 스냅샷 정합성 보장 그룹이 자동 삭제되도록 설정된 경우 시스템이 그룹에 대한 새 스냅샷 이미지를 생성할 때 가장 오래된 스냅샷 이미지가 삭제됩니다.



== 롤백 작업

* 롤백 작업이 진행 중일 때는 다음 작업을 수행할 수 없습니다.
+
** 롤백에 사용 중인 스냅샷 이미지를 삭제합니다.
** 롤백 작업에 참여하고 있는 기본 볼륨에 대한 새 스냅샷 이미지를 생성합니다.
** 연결된 스냅샷 그룹의 리포지토리 - 전체 정책을 변경합니다.


* 다음 작업 중 하나라도 진행 중인 경우에는 롤백 작업을 시작할 수 없습니다.
+
** 용량 확장(풀 또는 볼륨 그룹에 용량 추가)
** 볼륨 확장(볼륨 용량 증가)
** 볼륨 그룹의 RAID 레벨 변경
** 볼륨의 세그먼트 크기 변경


* 기본 볼륨이 볼륨 복사본에 참여하고 있는 경우에는 롤백 작업을 시작할 수 없습니다.
* 기본 볼륨이 원격 미러의 2차 볼륨인 경우에는 롤백 작업을 시작할 수 없습니다.
* 연결된 스냅샷 저장소 볼륨에서 사용된 용량 중 읽을 수 없는 섹터가 있는 경우 롤백 작업이 실패합니다.

