---
permalink: sm-storage/rtv-import-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, import, remote, storage 
summary: 원격 시스템에서 로컬 E-Series 스토리지 시스템으로 스토리지 가져오기를 시작하려면 원격 스토리지 가져오기 마법사를 사용합니다. 
---
= 원격 저장소 가져오기
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
원격 시스템에서 로컬 E-Series 스토리지 시스템으로 스토리지 가져오기를 시작하려면 원격 스토리지 가져오기 마법사를 사용합니다.

.시작하기 전에
* E-Series 스토리지 시스템은 원격 스토리지 시스템과 통신하도록 구성해야 합니다.
+
[NOTE]
====
하드웨어 구성에 대한 자세한 내용은 의 E-Series 및 SANtricity 문서 센터에서 제공되는 원격 스토리지 기능의 사용자 가이드를 참조하십시오 https://docs.netapp.com/us-en/e-series/remote-storage-volumes/setup-remote-volumes-concept.html["하드웨어를 구성합니다"^], 및 에 있습니다 https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["원격 스토리지 기술 보고서"^].

====
* 원격 스토리지 시스템의 경우 다음 정보를 수집합니다.
+
** iSCSI IQN입니다
** iSCSI IP 주소입니다
** 원격 스토리지 디바이스의 LUN 번호(소스 볼륨)


* 로컬 E-Series 스토리지 시스템의 경우 데이터 가져오기에 사용할 볼륨을 생성하거나 선택합니다. 을 참조하십시오 link:create-volumes.html["볼륨 생성"]. 타겟 볼륨은 다음 요구 사항을 충족해야 합니다.
+
** 원격 스토리지 디바이스(소스 볼륨)의 블록 크기와 일치합니다.
** 원격 스토리지 디바이스보다 크거나 같은 용량을 가지고 있습니다.
** 은(는) 최적 상태이며 사용 가능합니다.




전체 요구 사항 목록은 을 참조하십시오 link:rtv-remote-storage-volume-requirements.html["원격 스토리지 볼륨 요구 사항"].

* * 권장: * 가져오기 프로세스를 시작하기 전에 원격 스토리지 시스템의 볼륨을 백업합니다.


이 작업에서는 원격 스토리지 장치와 로컬 E-Series 스토리지 시스템의 볼륨 간에 매핑을 생성합니다. 구성을 마치면 불러오기가 시작됩니다.

[NOTE]
====
많은 변수가 가져오기 작업과 완료 시간에 영향을 줄 수 있으므로 먼저 더 작은 ""테스트"" 가져오기를 수행하는 것이 좋습니다. 이 테스트를 사용하여 모든 연결이 예상대로 작동하는지, 가져오기 작업이 적절한 시간 내에 완료되는지 확인합니다.

====
.단계
. Storage[Remote storage](저장[원격 저장]) 메뉴를 선택합니다.
. 원격 저장소 가져오기 * 를 클릭합니다.
+
원격 스토리지 가져오기 마법사가 표시됩니다.

. 소스 구성 패널의 * 단계 1a * 에서 연결 정보를 입력합니다. 다른 iSCSI 연결을 추가하려면 * 다른 IP 주소 추가 * 를 클릭하여 원격 스토리지에 대한 추가 IP 주소를 포함합니다. 완료되면 * 다음 * 을 클릭합니다.
+
.필드 상세정보
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
이름
 a| 
System Manager 인터페이스에서 식별할 원격 스토리지 디바이스의 이름을 입력합니다.

이름에는 최대 30자를 사용할 수 있으며 문자, 숫자 및 밑줄(_), 대시(-) 및 해시 기호(#)와 같은 특수 문자만 포함할 수 있습니다. 이름에는 공백이 포함될 수 없습니다.



 a| 
iSCSI 연결 속성
 a| 
원격 스토리지 디바이스의 접속 속성을 입력합니다.

** * IQN(iSCSI Qualified Name) *: iSCSI IQN을 입력합니다.
** * IP 주소 *: IPv4 주소를 입력합니다.
** * 포트 *: 소스 디바이스와 타겟 디바이스 간의 통신에 사용할 포트 번호를 입력합니다. 기본적으로 포트 번호는 3260입니다.


|===
====
+
Next*를 클릭하면 Configure Source 패널의 * Step 1b*가 표시됩니다.

. LUN * 필드에서 소스로 사용할 원격 스토리지 디바이스의 LUN 번호를 선택한 후 * Next * 를 클릭합니다.
+
Configure Target(대상 구성) 패널이 열리고 가져오기의 대상으로 사용할 볼륨 후보를 표시합니다. 일부 볼륨은 블록 크기, 용량 또는 볼륨 가용성 때문에 후보 목록에 표시되지 않습니다.

. 이 표에서 E-Series 스토리지 시스템의 타겟 볼륨을 선택합니다. 필요한 경우 슬라이더를 사용하여 가져오기 우선 순위를 변경합니다. 다음 * 을 클릭합니다. 다음 대화 상자에서 '계속'을 입력한 다음 * 계속 * 을 클릭하여 작업을 확인합니다.
+
타겟 볼륨의 용량이 소스 볼륨보다 큰 경우 E-Series 시스템에 연결된 호스트에 추가 용량이 보고되지 않습니다. 새 용량을 사용하려면 가져오기 작업이 완료되고 연결이 끊긴 후에 호스트에서 파일 시스템 확장 작업을 수행해야 합니다.

+
대화 상자에서 구성을 확인하면 Review(검토) 패널이 표시됩니다.

. Review(검토) 패널에서 설정이 정확한지 확인한 다음 * Finish(마침) * 를 클릭하여 가져오기를 시작합니다.
+
다른 가져오기를 시작할지 묻는 다른 대화 상자가 열립니다.

. 필요한 경우 * 예 * 를 클릭하여 다른 원격 스토리지 가져오기를 생성합니다. 예 * 를 클릭하면 소스 구성 패널의 * 단계 1a * 로 돌아갑니다. 여기서 기존 구성을 선택하거나 새 구성을 추가할 수 있습니다. 다른 불러오기를 생성하지 않으려면 * No * 를 클릭하여 대화 상자를 종료합니다.
+
가져오기 프로세스가 시작되면 전체 타겟 볼륨을 복사된 데이터로 덮어씁니다. 이 프로세스 중에 호스트가 타겟 볼륨에 새 데이터를 쓰는 경우 새 데이터가 원격 디바이스(소스 볼륨)로 다시 전파됩니다.

. 원격 스토리지 패널 아래의 작업 보기 대화 상자에서 작업 진행률을 확인합니다.


가져오기 작업을 완료하는 데 필요한 시간은 원격 스토리지 시스템의 크기, 가져오기에 대한 우선 순위 설정 및 스토리지 시스템과 관련 볼륨 모두의 입출력 로드 양에 따라 달라집니다.

가져오기가 완료되면 로컬 볼륨은 원격 저장소 장치의 중복입니다.

두 볼륨 간의 관계를 끊을 준비가 되면 Operations in Progress(작업 진행 중) 보기에서 가져오기 개체의 * Disconnect *(연결 해제 *)를 선택합니다. 관계가 끊기면 로컬 볼륨의 성능이 정상으로 돌아오며 더 이상 원격 연결의 영향을 받지 않습니다.
