---
permalink: sm-storage/rtv-remote-storage-volume-requirements.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage, volume, requirements 
summary: 가져오기에 사용되는 볼륨은 크기, 상태 및 기타 조건에 대한 요구 사항을 충족해야 합니다. 
---
= 원격 스토리지 볼륨 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가져오기에 사용되는 볼륨은 크기, 상태 및 기타 조건에 대한 요구 사항을 충족해야 합니다.



== 원격 스토리지 볼륨

가져오기의 소스 볼륨을 "원격 저장소 볼륨"이라고 합니다. 이 볼륨은 다음 기준을 충족해야 합니다.

* 다른 불러오기의 일부가 될 수 없습니다
* 온라인 상태여야 합니다


가져오기가 시작되면 컨트롤러 펌웨어가 백그라운드에서 원격 저장소 볼륨을 생성합니다. 이러한 백그라운드 프로세스로 인해 원격 스토리지 볼륨은 System Manager에서 관리할 수 없으며 가져오기 작업에만 사용할 수 있습니다.

생성된 원격 스토리지 볼륨은 E-Series 시스템에서 다른 표준 볼륨과 마찬가지로 취급되며, 다음과 같은 예외가 있습니다.

* 원격 스토리지 디바이스의 프록시로 사용할 수 있습니다.
* 다른 볼륨 복사본 또는 스냅샷의 대상으로 사용할 수 없습니다.
* 가져오기가 진행 중인 동안에는 Data Assurance 설정을 변경할 수 없습니다.
* 가져오기 작업을 위해 엄격하게 예약되었으므로 어떤 호스트에도 매핑할 수 없습니다.


각 원격 스토리지 볼륨은 하나의 원격 스토리지 오브젝트에만 연결되지만 하나의 원격 스토리지 객체는 여러 원격 스토리지 볼륨과 연결될 수 있습니다. 원격 스토리지 볼륨은 다음 조합을 사용하여 고유하게 식별됩니다.

* 원격 스토리지 객체 식별자입니다
* 원격 스토리지 디바이스 LUN 번호입니다




== 타겟 볼륨 후보

타겟 볼륨은 로컬 E-Series 시스템의 타겟 볼륨입니다. 대상 볼륨은 다음 기준을 충족해야 합니다.

* RAID/DDP 볼륨이어야 합니다.
* 원격 스토리지 볼륨과 같거나 큰 용량이 있어야 합니다.
* 원격 스토리지 볼륨과 동일한 블록 크기가 있어야 합니다.
* 유효한 상태(최적)가 있어야 합니다.
* 볼륨 복사본, 스냅샷 복사본, 비동기식 또는 동기식 미러링과 같은 관계는 가질 수 없습니다.
* DDP, 동적 볼륨 확장, 동적 용량 확장, 동적 세그먼트 크기, 동적 RAID 마이그레이션, 동적 용량 감소 등의 재구성 작업을 수행할 수 없습니다. 또는 조각 모음.
* 가져오기를 시작하기 전에 호스트에 매핑할 수 없습니다. 그러나 가져오기가 완료된 후에 매핑할 수 있습니다.
* FRC(Flash Read Cached)를 활성화할 수 없습니다.


System Manager는 원격 스토리지 가져오기 마법사의 일부로 이러한 요구 사항을 자동으로 확인합니다. 대상 볼륨 선택을 위해 모든 요구 사항을 충족하는 볼륨만 표시됩니다.
