---
permalink: sm-storage/rtv-how-remote-storage-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage 
summary: 원격 스토리지 기능을 사용하면 원격 스토리지 시스템에서 로컬 E-Series 스토리지 시스템으로 데이터를 가져올 수 있습니다. 이 기능은 장비를 업그레이드하는 동안 다운타임을 최소화하면서 데이터 마이그레이션을 간소화하려는 경우에 유용합니다. 
---
= 원격 스토리지의 작동 방식
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
원격 스토리지 기능을 사용하면 원격 스토리지 시스템에서 로컬 E-Series 스토리지 시스템으로 데이터를 가져올 수 있습니다. 이 기능은 장비를 업그레이드하는 동안 다운타임을 최소화하면서 데이터 마이그레이션을 간소화하려는 경우에 유용합니다.

원격 스토리지 기능을 구성하려면 하드웨어를 설정한 다음 System Manager를 사용하여 원격 스토리지 객체를 생성해야 합니다. 이 구성이 완료되면 가져오기 프로세스가 시작됩니다.



== 하드웨어 설정

다음 워크플로를 사용하여 하드웨어 연결을 준비합니다.

다음 단계에 대한 자세한 내용은 의 E-Series 및 SANtricity 문서 센터에서 제공되는 원격 스토리지 기능에 대한 사용자 가이드를 참조하십시오 https://docs.netapp.com/us-en/e-series/remote-storage-volumes/index.html["원격 스토리지 볼륨 개요"^], 및 에 있습니다 https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["원격 스토리지 기술 보고서"^].


NOTE: SANtricity 원격 저장소 볼륨은 현재 E4000 시스템에서 지원되지 않습니다.

로컬 E-Series 스토리지 시스템:

. 각 컨트롤러에 원격 스토리지 시스템에 대한 iSCSI 연결이 있는지 확인합니다. 이 연결을 통해 로컬 E-Series 시스템은 원격 시스템에서 호스트로 설정할 수 있는 iSCSI 이니시에이터 역할을 합니다.
. 가져오기 작업을 위한 대상 볼륨을 생성합니다. 볼륨에 원격 스토리지 시스템의 소스 볼륨과 같거나 큰 용량이 있고 블록 크기가 일치하며 매핑되지 않았는지 확인합니다. 을 참조하십시오 link:create-volumes.html["볼륨 생성"].
. System Manager 인터페이스에서 로컬 E-Series 시스템에 대한 IQN(iSCSI Qualified Name)을 수집합니다. IQN은 나중에 로컬 E-Series 시스템을 원격 스토리지 시스템의 호스트로 설정하는 데 사용됩니다. System Manager에서 메뉴: 설정 [시스템 > iSCSI 설정 > 대상 IQN] 으로 이동합니다.


원격 스토리지 시스템에서 다음을 수행합니다.

. IQN을 사용하여 원격 시스템에서 로컬 E-Series 시스템을 호스트로 설정합니다. 다음과 같이 적절한 호스트 유형을 설정해야 합니다.
+
** 원격 시스템이 E-Series 모델인 경우 를 참조하십시오 link:overview-hosts.html["호스트 및 호스트 클러스터 개요"]. "공장 출하 시 기본값"의 호스트 유형을 사용합니다.
** 원격 시스템이 다른 공급업체의 시스템인 경우 사용 가능한 옵션에 따라 적절한 호스트 유형을 선택합니다.


. 모든 I/O를 중지하고, 파일 시스템을 마운트 해제하고, 소스 볼륨의 호스트 또는 애플리케이션에 대한 할당을 제거합니다.
. 새로 생성한 로컬 E-Series 스토리지 시스템 호스트에 볼륨을 할당합니다.
. 선택한 소스 볼륨에 대해 원격 스토리지 시스템에서 다음 정보를 수집하여 가져오기를 생성할 수 있도록 합니다.
+
** IQN(iSCSI Qualified Name)
** iSCSI IP 주소입니다
** 소스 볼륨의 LUN 번호입니다






== System Manager 설정

다음 워크플로우를 사용하여 가져올 원격 스토리지 객체를 생성합니다.

. System Manager 인터페이스의 원격 스토리지 마법사를 사용하여 원격 스토리지 장치(데이터 가져오기 소스)를 E-Series 시스템의 타겟 볼륨에 매핑합니다. 마침 * 을 선택하면 가져오기 프로세스가 시작됩니다.
. View Operations(작업 보기) 대화 상자 또는 Operations in Progress(작업 진행 중) 패널에서 가져오기를 모니터링합니다. 필요한 경우 프로세스를 일시 중지하고 다시 시작할 수도 있습니다.
. 필요한 경우 가져오기가 완료되면 소스 볼륨과 타겟 볼륨 간의 연결을 끊거나 향후 가져오기를 위해 연결을 유지합니다.

