---
permalink: sm-storage/rtv-manage-progress-of-remote-volume-import.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage, imports 
summary: 가져오기 프로세스가 시작된 후 진행 상황을 확인하고 조치를 취할 수 있습니다. 
---
= 원격 스토리지 가져오기 진행률을 관리합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가져오기 프로세스가 시작된 후 진행 상황을 확인하고 조치를 취할 수 있습니다.

.이 작업에 대해
각 가져오기 작업에 대해 작업 진행 중 대화 상자에 완료율과 남은 예상 시간이 표시됩니다. 작업에는 가져오기 우선 순위 변경, 작업 중지 및 다시 시작, 작업 연결 해제 등이 있습니다.

홈 페이지(메뉴: 홈 [진행 중인 작업 표시])에서 진행 중인 작업을 볼 수도 있습니다.

.단계
. 원격 저장소 페이지에서 * 작업 보기 * 를 선택합니다.
+
작업 진행 중 대화 상자가 표시됩니다.

. 필요한 경우 * Actions * 열의 링크를 사용하여 작업을 중지 및 재개하거나, 우선 순위를 변경하거나, 작업 연결을 끊습니다.
+
** * 우선 순위 변경 * -- 진행 중이거나 보류 중인 작업의 처리 우선 순위를 변경하려면 * 우선 순위 변경 * 을 선택합니다. 작업에 우선 순위를 적용하고 * OK * 를 클릭합니다.
** * 중지 * -- 원격 저장 장치에서 데이터 복사를 일시 중지하려면 * 중지 * 를 선택합니다. 가져오기 쌍 간의 관계는 그대로 유지되며 가져오기 작업을 계속할 준비가 되면 * Resume * 을 선택할 수 있습니다.
** * 재개 * -- 중지된 위치에서 중지되거나 실패한 프로세스를 시작하려면 * 재시작 * 을 선택합니다. 그런 다음 Resume 작업에 우선 순위를 적용하고 * OK * 를 클릭합니다. 이 작업은 처음부터 가져오기를 _not_다시 시작합니다. 처음부터 프로세스를 다시 시작하려면 * Disconnect * 를 선택한 다음 원격 저장소 가져오기 마법사를 통해 가져오기를 다시 만들어야 합니다.
** * Disconnect * -- 중지, 완료 또는 실패한 가져오기 작업을 위해 소스 볼륨과 대상 볼륨 간의 관계를 끊으려면 * Disconnect * 를 선택합니다.



