---
permalink: sm-storage/schedule-snapshot-images.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, schedule, snapshot, images 
summary: 기본 볼륨에 문제가 있는 경우 복구를 설정하고 예약된 백업을 수행하는 스냅샷 스케줄을 생성합니다. 기본 볼륨 또는 스냅샷 정합성 보장 그룹의 스냅샷은 매일, 매주 또는 매월 언제든지 생성할 수 있습니다. 
---
= 스냅샷 이미지를 예약합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본 볼륨에 문제가 있는 경우 복구를 설정하고 예약된 백업을 수행하는 스냅샷 스케줄을 생성합니다. 기본 볼륨 또는 스냅샷 정합성 보장 그룹의 스냅샷은 매일, 매주 또는 매월 언제든지 생성할 수 있습니다.

.시작하기 전에
기본 볼륨이 최적화되어야 합니다.

.이 작업에 대해
이 작업에서는 기존 스냅샷 정합성 보장 그룹 또는 기본 볼륨에 대한 스냅샷 스케줄을 생성하는 방법에 대해 설명합니다.

[NOTE]
====
기본 볼륨 또는 스냅샷 정합성 보장 그룹의 스냅샷 이미지를 생성하는 동시에 스냅샷 스케줄을 생성할 수도 있습니다.

====
.단계
. 다음 작업 중 하나를 수행하여 스냅샷 스케줄을 생성합니다.
+
** Storage [Volumes](저장소 [볼륨]) 메뉴를 선택합니다.
+
이 스냅샷 스케줄에 대한 객체(볼륨 또는 스냅샷 정합성 보장 그룹)를 선택한 다음 메뉴: 복제 서비스 [스냅샷 스케줄 생성]을 선택합니다.

** 스토리지 [스냅샷] 메뉴를 선택합니다.
+
Schedules * 탭을 선택한 다음 * Create * 를 클릭합니다.



. 이 스냅샷 스케줄의 객체(볼륨 또는 스냅샷 정합성 보장 그룹)를 선택하고 * 다음 * 을 클릭합니다.
+
스냅샷 일정 생성 대화 상자가 나타납니다.

. 다음 작업 중 하나를 수행합니다.
+
** * 다른 스냅샷 개체에서 이전에 정의한 스케줄을 사용합니다 *.
+
고급 옵션이 표시되는지 확인합니다. 추가 옵션 표시 * 를 클릭합니다. 일정 가져오기 * 를 클릭하고 가져올 일정이 있는 개체를 선택한 다음 * 가져오기 * 를 클릭합니다.

** * 기본 또는 고급 옵션을 수정합니다 *.
+
대화 상자의 오른쪽 위에서 * 더 많은 옵션 표시 * 를 클릭하여 모든 옵션을 표시한 후 다음 표를 참조하십시오.



+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 필드에 입력합니다 | 설명 


 a| 
* 기본 설정 *



 a| 
일 을 선택합니다
 a| 
스냅샷 이미지에 대한 요일을 개별적으로 선택합니다.



 a| 
시작 시간
 a| 
드롭다운 목록에서 일별 스냅샷의 새 시작 시간을 선택합니다(선택 항목은 30분 단위로 제공됨). 시작 시간은 현재 시간보다 30분 먼저 설정됩니다.



 a| 
시간대
 a| 
드롭다운 목록에서 스토리지의 시간대를 선택합니다.



 a| 
* 고급 설정 *



 a| 
일/월
 a| 
다음 옵션 중 하나를 선택합니다.

** * Daily/Weekly * -- 동기화 스냅샷을 위한 개별 요일을 선택합니다. 또한 일일 일정을 원하는 경우 오른쪽 상단에서 * Select All Days * (모든 날짜 선택 *) 확인란을 선택할 수도 있습니다.
** * Monthly/Yearly * -- 동기화 스냅샷을 위한 개별 월을 선택합니다. On day(s) * 필드에 동기화가 발생하는 날짜를 입력합니다. 유효한 항목은 * 1 * ~ * 31 * 및 * Last * 입니다. 여러 날짜를 쉼표 또는 세미콜론으로 구분할 수 있습니다. 포함 날짜에 하이픈을 사용합니다. 예: 1,3, 4,10-15, Last. 월 단위 일정을 원하는 경우 오른쪽 상단에서 * 모든 월 선택 * 확인란을 선택할 수도 있습니다.




 a| 
시작 시간
 a| 
드롭다운 목록에서 일별 스냅샷의 새 시작 시간을 선택합니다(선택 항목은 30분 단위로 제공됨). 시작 시간은 현재 시간보다 30분 먼저 설정됩니다.



 a| 
시간대
 a| 
드롭다운 목록에서 스토리지의 시간대를 선택합니다.



 a| 
스냅샷 간의 일별/시간 스냅샷
 a| 
하루에 생성할 스냅샷 이미지 수를 선택합니다. 둘 이상의 를 선택한 경우 스냅샷 이미지 사이의 시간도 선택합니다. 여러 스냅샷 이미지의 경우 충분한 예약 용량이 있어야 합니다.



 a| 
지금 스냅샷 이미지를 생성하시겠습니까?
 a| 
예약 중인 자동 이미지 외에 인스턴트 이미지를 만들려면 이 확인란을 선택합니다.



 a| 
시작/종료 날짜 또는 종료 날짜 없음
 a| 
동기화를 시작할 시작 날짜를 입력합니다. 종료 날짜를 입력하거나 * 종료 날짜 없음 * 을 선택합니다.

|===
====
. 다음 작업 중 하나를 수행합니다.
+
** 객체가 스냅샷 정합성 보장 그룹인 경우 * 생성 * 을 클릭하여 설정을 적용하고 스케줄을 생성합니다.
** 객체가 볼륨인 경우 * Next * 를 클릭하여 스냅샷 이미지에 예약된 용량을 할당합니다.
+
지정된 예약 용량을 지원하는 후보만 볼륨 후보 테이블에 표시됩니다. 예약된 용량은 복제 서비스 작업 및 스토리지 객체에 사용되는 물리적 할당 용량입니다. 호스트에서 직접 읽을 수 없습니다.



. 스피너 상자를 사용하여 스냅샷 이미지에 예약된 용량을 할당합니다. 다음 작업 중 하나를 수행합니다.
+
** * 기본 설정을 적용합니다. *
+
이 권장 옵션을 사용하여 스냅샷 이미지에 예약된 용량을 기본 설정으로 할당합니다.

** * 데이터 스토리지 요구 사항에 맞게 예약된 용량 설정을 할당합니다. *
+
기본 예약된 용량 설정을 변경하는 경우 * 후보 새로 고침 * 을 클릭하여 지정한 예약된 용량에 대한 후보 목록을 새로 고칩니다.

+
다음 지침에 따라 예약된 용량을 할당합니다.

+
*** 예약된 용량의 기본 설정은 기본 볼륨 용량의 40%입니다. 일반적으로 이 용량이면 충분합니다.
*** 필요한 용량은 볼륨에 대한 입출력 쓰기 빈도 및 크기와 스냅샷 이미지 컬렉션의 양과 기간에 따라 달라집니다.




. 다음 * 을 클릭합니다.
+
설정 편집 대화 상자가 나타납니다.

. 필요에 따라 스냅샷 스케줄의 설정을 편집한 다음 * 마침 * 을 클릭합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
* 스냅샷 이미지 제한 *



 a| 
다음과 같은 경우 스냅샷 이미지 자동 삭제 활성화
 a| 
스냅샷 이미지를 지정된 제한 이후 자동으로 삭제하려면 확인란을 선택하고, 제한을 변경하려면 스피너 상자를 사용합니다. 이 확인란의 선택을 취소하면 32개 이미지 후에 스냅샷 이미지 생성이 중지됩니다.



 a| 
* 예약된 용량 설정 *



 a| 
다음 경우에 알림:
 a| 
스피너 상자를 사용하여 스케줄의 예약된 용량이 거의 가득 찰 때 시스템에서 경고 알림을 보내는 백분율 지점을 조정합니다.

스케줄에 예약된 용량이 지정된 임계값을 초과하는 경우 사전 알림을 사용하여 예약된 용량을 늘리거나 남은 공간이 부족해지기 전에 불필요한 객체를 삭제하십시오.



 a| 
전체 예약 용량에 대한 정책입니다
 a| 
다음 정책 중 하나를 선택합니다.

** * Purge Oldest snapshot image * -- 시스템이 가장 오래된 스냅샷 이미지를 자동으로 지퍼하여 스냅샷 그룹 내에서 재사용할 수 있도록 스냅샷 이미지 예약 용량을 해제합니다.
** * 기본 볼륨에 대한 쓰기 거부 * -- 예약된 용량이 최대 정의 비율에 도달하면 시스템은 예약된 용량 액세스를 트리거한 기본 볼륨에 대한 모든 I/O 쓰기 요청을 거부합니다.


|===
====

