---
permalink: sm-storage/snapshot-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, snapshot, terms 
summary: 스냅샷 조건이 스토리지 어레이에 적용되는 방식에 대해 알아보십시오. 
---
= 스냅샷 용어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 조건이 스토리지 어레이에 적용되는 방식에 대해 알아보십시오.

[cols="25h,~"]
|===
| 기간 | 설명 


 a| 
스냅샷 기능
 a| 
스냅샷 기능은 볼륨의 이미지를 생성하고 관리하는 데 사용됩니다.



 a| 
스냅샷 이미지
 a| 
스냅샷 이미지는 특정 시점에 캡처된 볼륨 데이터의 논리적 복사본입니다. 복원 지점과 마찬가지로 스냅샷 이미지를 통해 알려진 양호한 데이터 집합으로 롤백할 수 있습니다. 호스트가 스냅샷 이미지를 액세스할 수는 있지만 해당 이미지를 직접 읽거나 쓸 수는 없습니다.



 a| 
기본 볼륨
 a| 
기본 볼륨은 스냅샷 이미지가 생성되는 원본입니다. 일반 볼륨이거나 씬 볼륨일 수 있으며 일반적으로 호스트에 할당됩니다. 기본 볼륨은 볼륨 그룹 또는 디스크 풀에 상주할 수 있습니다.



 a| 
스냅샷 볼륨
 a| 
스냅샷 볼륨을 사용하면 호스트가 스냅샷 이미지의 데이터에 액세스할 수 있습니다. 스냅샷 볼륨에는 원래 스냅샷 이미지에 영향을 주지 않고 기본 볼륨에 대한 수정 사항을 저장하는 자체 예약 용량이 포함되어 있습니다.



 a| 
스냅샷 그룹
 a| 
스냅샷 그룹은 단일 기본 볼륨의 스냅샷 이미지 모음입니다.



 a| 
예약된 용량 볼륨입니다
 a| 
예약된 용량 볼륨은 기본 볼륨의 데이터 블록 및 해당 블록의 보존된 콘텐츠를 추적합니다.



 a| 
스냅샷 스케줄입니다
 a| 
스냅샷 스케줄은 자동화된 스냅샷 이미지를 생성하는 시간표입니다. 일정을 통해 이미지 생성 빈도를 제어할 수 있습니다.



 a| 
스냅샷 정합성 보장 그룹
 a| 
스냅샷 정합성 보장 그룹은 스냅샷 이미지를 생성할 때 단일 개체로 처리되는 볼륨의 모음입니다. 이러한 각 볼륨에는 고유한 스냅샷 이미지가 있지만 모든 이미지는 동시에 생성됩니다.



 a| 
스냅샷 정합성 보장 그룹 구성원 볼륨입니다
 a| 
스냅샷 정합성 보장 그룹에 속한 각 볼륨을 구성원 볼륨이라고 합니다. 스냅샷 정합성 보장 그룹에 볼륨을 추가하면 System Manager에서 이 구성원 볼륨에 해당하는 새 스냅샷 그룹을 자동으로 생성합니다.



 a| 
롤백
 a| 
롤백은 기본 볼륨의 데이터를 이전 시점으로 되돌리는 프로세스입니다.



 a| 
예약된 용량입니다
 a| 
예약된 용량은 복제 서비스 작업 및 스토리지 객체에 사용되는 물리적 할당 용량입니다. 호스트에서 직접 읽을 수 없습니다.

|===