---
permalink: sm-storage/start-snapshot-image-rollback-for-base-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, start, snapshot, image, rollback, base, volume 
summary: 롤백 작업을 수행하여 스냅샷 이미지에 저장된 컨텐츠와 일치하도록 기본 볼륨의 콘텐츠를 변경할 수 있습니다. 롤백 작업은 기본 볼륨과 연결된 스냅샷 이미지의 콘텐츠를 변경하지 않습니다. 
---
= 기본 볼륨에 대한 스냅샷 이미지 롤백을 시작합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
롤백 작업을 수행하여 스냅샷 이미지에 저장된 컨텐츠와 일치하도록 기본 볼륨의 콘텐츠를 변경할 수 있습니다.

롤백 작업은 기본 볼륨과 연결된 스냅샷 이미지의 콘텐츠를 변경하지 않습니다.

.시작하기 전에
* 롤백 작업을 시작할 수 있는 충분한 예약 용량을 사용할 수 있습니다.
* 선택한 스냅샷 이미지가 최적이고 선택한 볼륨이 최적입니다.
* 선택한 볼륨에 이미 진행 중인 롤백 작업이 없습니다.


.이 작업에 대해
롤백 시작 시퀀스를 사용하면 스토리지 용량을 추가하는 옵션을 제공하면서 기본 볼륨의 스냅샷 이미지에서 롤백을 시작할 수 있습니다. 기본 볼륨에 대해 한 번에 두 개 이상의 롤백 작업을 시작할 수 없습니다.

[NOTE]
====
호스트는 새로 롤백된 기본 볼륨에 즉시 액세스할 수 있지만, 롤백이 시작된 후 기존 기본 볼륨에서 호스트 읽기-쓰기 액세스를 허용하지 않습니다. 롤백을 시작하기 직전에 기본 볼륨의 스냅샷을 생성하여 복구를 위해 롤백 전 기본 볼륨을 보존할 수 있습니다.

====
.단계
. 스토리지 [스냅샷] 메뉴를 선택합니다.
. 스냅샷 이미지 * 탭을 선택합니다.
. 스냅샷 영상을 선택한 다음 Rollback [Start](롤백[시작]) 메뉴를 선택합니다.
+
롤백 시작 확인 대화 상자가 나타납니다.

. * 선택 사항: * 필요한 경우 * 용량 증가 * 옵션을 선택합니다.
+
예약된 용량 증가 대화 상자가 나타납니다.

+
.. 스피너 상자를 사용하여 용량 비율을 조정합니다.
+
선택한 스토리지 객체가 포함된 풀 또는 볼륨 그룹에 사용 가능한 용량이 없고 스토리지 배열에 할당되지 않은 용량이 있는 경우 용량을 추가할 수 있습니다. 새 풀 또는 볼륨 그룹을 생성한 다음 해당 풀 또는 볼륨 그룹의 새 가용 용량을 사용하여 이 작업을 다시 시도할 수 있습니다.

.. 증가 * 를 클릭합니다.


. 이 작업을 수행할지 확인한 다음 * Rollback * 을 클릭합니다.


.결과
System Manager는 다음 작업을 수행합니다.

* 선택한 스냅샷 이미지에 저장된 컨텐츠로 볼륨을 복원합니다.
* 롤백된 볼륨을 호스트 액세스에 즉시 사용할 수 있도록 합니다. 롤백 작업이 완료될 때까지 기다릴 필요가 없습니다.


.작업을 마친 후
롤백 작업의 진행률을 보려면 홈 [View Operations in Progress] 메뉴를 선택합니다.

롤백 작업이 성공하지 못하면 작업이 일시 중지됩니다. 일시 중지된 작업을 다시 시작하고 여전히 실패하면 Recovery Guru 절차에 따라 문제를 해결하거나 기술 지원 부서에 문의하십시오.
