---
permalink: sm-storage/types-of-copy-volume-operations.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy, volume, 
summary: 오프라인 볼륨 복사 작업 또는 온라인 볼륨 복사 작업을 수행할 수 있습니다. 오프라인 작업은 소스 볼륨에서 데이터를 읽고 타겟 볼륨에 복사합니다. 온라인 작업에서는 스냅샷 볼륨을 소스로 사용하고 해당 데이터를 타겟 볼륨에 복사합니다. 
---
= 볼륨 복사 작업의 유형입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
offline_Copy Volume 작업 또는 _online_Copy Volume 작업을 수행할 수 있습니다. 오프라인 작업은 소스 볼륨에서 데이터를 읽고 타겟 볼륨에 복사합니다. 온라인 작업에서는 스냅샷 볼륨을 소스로 사용하고 해당 데이터를 타겟 볼륨에 복사합니다.

데이터 무결성을 보장하기 위해 타겟 볼륨에 대한 모든 입출력 작업은 볼륨 복사 작업 중 어느 유형이든 일시 중단됩니다. 이 서스펜션은 절차가 완료될 때까지 타겟 볼륨의 데이터 상태가 일관되지 않기 때문에 발생합니다.

오프라인 및 온라인 볼륨 복사 작업은 아래에 설명되어 있습니다.



== 오프라인 복사본 볼륨 작업입니다

오프라인 복사본 볼륨 관계는 소스 볼륨과 타겟 볼륨 사이에 있습니다. 오프라인 복제는 소스 볼륨에서 데이터를 읽고 타겟 볼륨에 복사하는 한편, 진행 중인 복제본으로 소스 볼륨에 대한 모든 업데이트를 일시 중지시킵니다. 소스 볼륨에 대한 모든 업데이트가 일시 중지되어 타겟 볼륨에 시간 정합성이 보장되지 않는 항목이 생성되는 것을 방지합니다.

[cols="25h,~"]
|===
2+| 오프라인 복사 작업에 대해 알아야 할 사항 


 a| 
읽기 및 쓰기 요청
 a| 
* 오프라인 복사본에 사용 중인 소스 볼륨은 볼륨 복사 작업의 상태가 진행 중 또는 보류 중 인 동안 읽기 전용 입출력 작업에 사용할 수 있습니다.
* 오프라인 복제가 완료된 후에는 쓰기 요청이 허용됩니다.
* 쓰기 방지 오류 메시지를 방지하려면 볼륨 복사 작업에 참여하고 있는 소스 볼륨에 진행 중 상태로 액세스하지 마십시오.




 a| 
저널링 파일 시스템
 a| 
* 소스 볼륨이 저널링 파일 시스템으로 포맷된 경우, 소스 볼륨에 대한 읽기 요청을 발급하려는 시도는 스토리지 어레이 컨트롤러에 의해 거부될 수 있으며 오류 메시지가 나타날 수 있습니다.
* 저널링 파일 시스템 드라이버는 읽기 요청을 발급하기 전에 쓰기 요청을 발행합니다. 컨트롤러가 쓰기 요청을 거부하면 쓰기 요청이 거부되어 읽기 요청이 실행되지 않을 수 있습니다. 이 경우 소스 볼륨이 쓰기 보호되어 있음을 나타내는 오류 메시지가 나타날 수 있습니다.
* 이 문제가 발생하지 않도록 하려면 볼륨 복사 작업의 상태가 진행 중인 동안에는 오프라인 복사본에 참여하고 있는 소스 볼륨에 액세스하지 마십시오.


|===


== 온라인 볼륨 복사 작업입니다

온라인 볼륨 복사 관계는 스냅샷 볼륨과 타겟 볼륨 사이에 있습니다. 소스 볼륨이 온라인 상태이고 데이터 쓰기에 사용할 수 있는 동안 볼륨 복사 작업을 시작할 수 있습니다. 이 기능은 볼륨의 스냅샷을 생성하고 스냅샷을 복제본의 실제 소스 볼륨으로 사용하여 수행합니다.

소스 볼륨에 대해 볼륨 복사 작업을 시작하면 System Manager에서 기본 볼륨의 스냅샷 이미지와 기본 볼륨의 스냅샷 이미지와 타겟 볼륨 간의 복제 관계를 생성합니다. 스냅샷 이미지를 소스 볼륨으로 사용하면 복제가 진행되는 동안 스토리지 어레이가 소스 볼륨에 계속 쓸 수 있습니다.

온라인 복사 작업 중에 COW(Copy-On-Write) 절차로 인해 성능에 영향을 줍니다. 온라인 복사가 완료되면 기본 볼륨 성능이 복원됩니다.

[cols="25h,~"]
|===
2+| 온라인 복사 작업에 대해 알아야 할 사항 


 a| 
어떤 종류의 볼륨을 사용할 수 있습니까?
 a| 
* 시점 이미지가 생성되는 볼륨을 기본 볼륨이라고 하며 스토리지 배열의 표준 볼륨 또는 씬 볼륨이어야 합니다.
* 타겟 볼륨은 볼륨 그룹의 표준 볼륨이거나 풀의 표준 볼륨일 수 있습니다. 타겟 볼륨은 씬 볼륨이거나 스냅샷 그룹의 기본 볼륨일 수 없습니다.
* 온라인 볼륨 복사 기능을 사용하여 씬 볼륨의 데이터를 동일한 스토리지 시스템 내에 있는 풀의 표준 볼륨으로 복사할 수 있습니다. 그러나 Copy Volume(볼륨 복사) 기능을 사용하여 표준 볼륨에서 씬 볼륨으로 데이터를 복사할 수는 없습니다.




 a| 
기본 볼륨 성능
 a| 
* 복사 소스로 사용되는 스냅샷 볼륨이 활성 상태이면 COW(Copy-On-Write) 작업으로 인해 기본 볼륨 성능이 저하됩니다. 복제가 완료되면 스냅샷이 비활성화되고 기본 볼륨 성능이 복원됩니다. 스냅샷이 해제되더라도 예약된 용량 볼륨 및 복제 관계는 그대로 유지됩니다.




 a| 
생성된 볼륨의 유형입니다
 a| 
* 온라인 복제 작업 중에 스냅샷 볼륨 및 예약된 용량 볼륨이 생성됩니다.
* 스냅샷 볼륨은 데이터가 포함된 실제 볼륨이 아니라 특정 시간에 볼륨에 포함된 데이터에 대한 참조입니다.
* 생성된 각 스냅샷에 대해 예약된 용량 볼륨이 생성되어 스냅샷에 대한 데이터를 보유합니다. 예약된 용량 볼륨은 스냅샷 이미지를 관리하는 데만 사용됩니다.




 a| 
예약된 용량 볼륨입니다
 a| 
* 소스 볼륨의 데이터 블록이 수정되기 전에 수정할 블록의 내용이 보호되도록 예약된 용량 볼륨에 복사됩니다.
* 예약된 용량 볼륨에 원래 데이터의 복사본이 이러한 데이터 블록에 저장되기 때문에 이러한 데이터 블록에 대한 추가 변경 사항은 소스 볼륨에만 기록됩니다.
* 예약된 용량 볼륨에 저장된 데이터 블록만이 스냅샷 시간 이후에 변경된 데이터 블록이므로 온라인 복제 작업에서는 전체 물리적 복사본보다 디스크 공간이 적게 사용됩니다.


|===