---
permalink: sm-storage/view-performance-data-graphical.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, graphical, performance, 
summary: 논리적 오브젝트, 물리적 오브젝트, 애플리케이션 및 워크로드의 그래픽 성능 데이터를 볼 수 있습니다. 
---
= SANtricity System Manager에서 그래픽 성능 데이터 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
논리적 오브젝트, 물리적 오브젝트, 애플리케이션 및 워크로드의 그래픽 성능 데이터를 볼 수 있습니다.

.이 작업에 대해
성능 그래프에는 기록 데이터와 현재 캡처 중인 라이브 데이터가 표시됩니다. 실시간 업데이트 라고 표시된 그래프의 세로선은 기록 데이터를 라이브 데이터와 구분합니다.

*대시보드 보기*

대시보드에는 스토리지 어레이 수준의 성능을 보여주는 그래프가 있습니다. 이 보기에서 제한된 메트릭을 선택하거나, *성능 세부 정보 보기*를 클릭하여 메뉴:모니터링[성능]으로 이동한 후 사용 가능한 모든 메트릭을 선택할 수 있습니다.

* 상세 보기 *

성능 페이지에서 확인할 수 있는 그래프는 사용자의 선택 사항을 기반으로 합니다.

* * 오브젝트 유형 * -- 포함할 오브젝트 범주를 선택합니다(예: 스토리지 어레이, 컨트롤러, 풀 및 볼륨 그룹, 애플리케이션, 워크로드, 볼륨, 채널 및 드라이브).
* *오브젝트* -- 선택한 오브젝트 유형에 대해 최대 5개의 특정 오브젝트를 선택합니다.


.단계
. 메뉴 선택: 모니터링[성능].
. 표시할 데이터를 선택하려면 *오브젝트 유형*과 *오브젝트*를 사용하십시오. 최대 5개의 오브젝트를 선택할 수 있으며, *오브젝트* 목록의 검색 필드를 사용하여 오브젝트 이름 또는 부분 이름을 검색할 수 있습니다.
+
모든 오브젝트 유형에 대해 모든 메트릭을 사용할 수 있는 것은 아닙니다. 스토리지 어레이와 컨트롤러는 지연 시간을 보고하지 않으며, 컨트롤러만 CPU 사용률을 보고하고, 컨트롤러와 채널만 헤드룸을 보고합니다.

. 표시할 기간을 선택하려면 *시간 범위*를 사용하십시오.
. *새로 고침*을 클릭합니다.
. *선택 사항:* 개별 그래프에서 *비교* 기능을 사용하여 동일한 오브젝트에 대해 다른 유형의 측정값을 겹쳐 표시할 수 있습니다.
. 필요에 따라 성능 데이터를 볼 수 있는 추가 옵션을 사용합니다.
+
.추가 옵션
[%collapsible]
====
[cols="25h,~"]
|===
| 옵션을 선택합니다 | 설명 


 a| 
시간 범위
 a| 
보려는 시간(5분, 1시간, 8시간, 1일, 7일, 또는 30일). 기본값은 1시간입니다.


NOTE: 30일간의 성능 데이터를 불러오는 데 몇 분이 소요될 수 있습니다. 데이터가 로드되는 동안 웹페이지를 벗어나거나, 새로고침하거나, 브라우저를 닫지 마십시오.



 a| 
데이터 포인트 세부 정보
 a| 
그래프 위로 커서를 이동하면 특정 데이터 지점에 대한 메트릭이 표시됩니다.



 a| 
스크롤 막대
 a| 
그래프 아래의 스크롤 막대를 사용하여 이전 또는 이후 기간을 봅니다.



 a| 
확대/축소 막대
 a| 
그래프 아래에서 확대/축소 막대 핸들을 끌어 시간 범위를 축소합니다. 확대/축소 막대가 넓을수록 그래프의 상세 정보가 덜 세분됩니다.

그래프를 재설정하려면 시간 프레임 옵션 중 하나를 선택합니다.



 a| 
끌어서 놓기
 a| 
그래프에서 특정 시점에서 다른 지점으로 커서를 드래그하여 기간을 확대합니다.

그래프를 재설정하려면 시간 프레임 옵션 중 하나를 선택합니다.

|===
====

