---
permalink: sm-storage/view-performance-data-graphical.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, graphical, performance, 
summary: 논리적 오브젝트, 물리적 오브젝트, 애플리케이션 및 워크로드의 그래픽 성능 데이터를 볼 수 있습니다. 
---
= 그래픽 성능 데이터를 봅니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
논리적 오브젝트, 물리적 오브젝트, 애플리케이션 및 워크로드의 그래픽 성능 데이터를 볼 수 있습니다.

.이 작업에 대해
성능 그래프에는 기록 데이터와 현재 캡처 중인 라이브 데이터가 표시됩니다. 실시간 업데이트 라고 표시된 그래프의 세로선은 기록 데이터를 라이브 데이터와 구분합니다.

* 홈 페이지 보기 *

홈 페이지에는 스토리지 레벨 성능을 보여 주는 그래프가 포함되어 있습니다. 이 보기에서 제한된 메트릭을 선택하거나 * 성능 세부 정보 보기 * 를 클릭하여 사용 가능한 모든 메트릭을 선택할 수 있습니다.

* 상세 보기 *

상세 성능 보기에서 사용할 수 있는 그래프는 다음 세 가지 탭 아래에 있습니다.

* * Logical View * -- 볼륨 그룹 및 풀별로 그룹화된 논리 오브젝트의 성능 데이터를 표시합니다. 논리적 객체에는 볼륨 그룹, 풀 및 볼륨이 포함됩니다.
* * Physical View * -- 컨트롤러, 호스트 채널, 드라이브 채널 및 드라이브에 대한 성능 데이터를 표시합니다.
* * 애플리케이션 및 워크로드 보기 * -- 정의한 애플리케이션 유형 및 워크로드별로 그룹화된 논리적 오브젝트(볼륨) 목록을 표시합니다.


.단계
. Home * 을 선택합니다.
. 스토리지 레벨 뷰를 선택하려면 IOPS, MiB/s 또는 CPU 버튼을 클릭합니다.
. 자세한 내용을 보려면 * 성능 세부 정보 보기 * 를 클릭하십시오.
. Logical View * 탭, * Physical View * 탭 또는 * Applications & 워크로드 View * 탭을 선택합니다.
+
개체 유형에 따라 각 탭에 다른 그래프가 표시됩니다.

+
[cols="25h,~"]
|===
| 보기 탭 | 각 오브젝트 유형에 대한 성능 데이터가 표시됩니다 


 a| 
논리적 뷰
 a| 
** * 스토리지 어레이 *: IOPS, MiB/s
** * 풀 *: 지연 시간, IOPS, MiB/s
** * 볼륨 그룹 *: 지연 시간, IOPS, MiB/s
** * 볼륨 *: 지연 시간, IOPS, MiB/s




 a| 
물리적 보기
 a| 
** * 컨트롤러 *: IOPS, MiB/s, CPU, 여유 공간
** * 호스트 채널 *: 지연 시간, IOPS, MiB/s, 여유 공간
** * 드라이브 채널 *: 지연 시간, IOPS, MiB/s
** * 드라이브 *: 지연 시간, IOPS, MiB/s




 a| 
애플리케이션 및 워크로드 뷰
 a| 
** * 스토리지 어레이 *: IOPS, MiB/s
** * 애플리케이션 *: 지연 시간, IOPS, MiB/s
** * 워크로드 *: 지연 시간, IOPS, MiB/s
** * 볼륨 *: 지연 시간, IOPS, MiB/s


|===
. 필요한 개체 및 정보를 보려면 옵션을 사용합니다.
+
.옵션
[%collapsible]
====
[cols="25h,~"]
|===
| 개체 보기 옵션 | 설명 


 a| 
문서함을 확장하여 개체 목록을 봅니다.
 a| 
_Navigation 드로어_ 에는 풀, 볼륨 그룹 및 드라이브와 같은 스토리지 객체가 포함됩니다.

문서함을 클릭하여 문서함의 개체 목록을 표시합니다.



 a| 
보려는 객체를 선택합니다.
 a| 
각 개체의 왼쪽에 있는 확인란을 선택하여 보려는 성능 데이터를 선택합니다.



 a| 
필터를 사용하여 개체 이름 또는 부분 이름을 찾습니다.
 a| 
필터 상자에 드로어에 있는 개체만 나열할 개체의 이름이나 부분 이름을 입력합니다.



 a| 
개체를 선택한 후 * 그래프 새로 고침 * 을 클릭합니다.
 a| 
문서함에서 개체를 선택한 후 * 그래프 새로 고침 * 을 선택하여 선택한 항목에 대한 그래픽 데이터를 봅니다.



 a| 
그래프를 숨기거나 표시합니다
 a| 
그래프를 숨기거나 표시하려면 그래프 제목을 선택합니다.

|===
====
. 필요에 따라 성능 데이터를 볼 수 있는 추가 옵션을 사용합니다.
+
.추가 옵션
[%collapsible]
====
[cols="25h,~"]
|===
| 옵션을 선택합니다 | 설명 


 a| 
시간 프레임
 a| 
보려는 시간(5분, 1시간, 8시간, 1일, 7일, 또는 30일). 기본값은 1시간입니다.


NOTE: 30일 기간 동안 성능 데이터를 로드하는 데 몇 분이 걸릴 수 있습니다. 데이터가 로드되는 동안 웹 페이지에서 멀리 이동하거나 웹 페이지를 새로 고치거나 브라우저를 닫지 마십시오.



 a| 
데이터 포인트 세부 정보
 a| 
그래프 위로 커서를 이동하면 특정 데이터 지점에 대한 메트릭이 표시됩니다.



 a| 
스크롤 막대
 a| 
그래프 아래의 스크롤 막대를 사용하여 이전 또는 이후 기간을 봅니다.



 a| 
확대/축소 막대
 a| 
그래프 아래에서 확대/축소 막대 핸들을 끌어 시간 범위를 축소합니다. 확대/축소 막대가 넓을수록 그래프의 상세 정보가 덜 세분됩니다.

그래프를 재설정하려면 시간 프레임 옵션 중 하나를 선택합니다.



 a| 
끌어서 놓기
 a| 
그래프에서 특정 시점에서 다른 지점으로 커서를 드래그하여 기간을 확대합니다.

그래프를 재설정하려면 시간 프레임 옵션 중 하나를 선택합니다.

|===
====

