---
permalink: sm-storage/volume-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volume, terms 
summary: 볼륨 조건이 스토리지 어레이에 적용되는 방식에 대해 알아보십시오. 
---
= SANtricity 소프트웨어의 볼륨 용어에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 조건이 스토리지 어레이에 적용되는 방식에 대해 알아보십시오.



== 모든 볼륨 유형

[cols="25h,~"]
|===
| 기간 | 설명 


 a| 
할당된 용량입니다
 a| 
할당된 용량을 사용하여 볼륨을 생성하고 복제 서비스 작업을 수행할 수 있습니다.

할당된 용량과 보고된 용량은 일반 볼륨에 대해 동일하지만 씬 볼륨에 대해서는 다릅니다. 일반 볼륨의 경우 물리적으로 할당된 공간은 호스트에 보고된 공간과 같습니다. 씬 볼륨의 경우 보고된 용량은 호스트에 보고된 용량이고, 할당된 용량은 데이터 쓰기에 현재 할당된 드라이브 공간의 양입니다.



 a| 
응용 프로그램
 a| 
애플리케이션은 SQL Server 또는 Exchange와 같은 소프트웨어입니다. 각 애플리케이션을 지원할 워크로드를 하나 이상 정의합니다. 일부 애플리케이션의 경우, 시스템은 스토리지를 최적화하는 볼륨 구성을 자동으로 권장합니다. 볼륨 구성에는 I/O 유형, 세그먼트 크기, 컨트롤러 소유권, 읽기 및 쓰기 캐시 같은 특성이 포함됩니다.



 a| 
용량
 a| 
용량은 볼륨에 저장할 수 있는 데이터의 양입니다.



 a| 
컨트롤러 소유권
 a| 
컨트롤러 소유권은 볼륨의 소유 또는 기본 컨트롤러로 지정된 컨트롤러를 정의합니다. 볼륨은 볼륨을 "소유"하는 기본 컨트롤러(A 또는 B)를 가질 수 있습니다. 컨트롤러 간에 워크로드가 이동할 때 로드 밸런싱 문제를 해결하려면 자동 로드 밸런싱 기능을 사용하여 볼륨 소유권을 자동으로 조정합니다. 자동 로드 밸런싱은 자동화된 I/O 워크로드 밸런싱을 제공하고 호스트에서 들어오는 I/O 트래픽이 두 컨트롤러 간에 동적으로 관리 및 균형 조정되도록 합니다.



 a| 
동적 캐시 읽기 프리페치
 a| 
동적 캐시 읽기 프리페치를 사용하면 컨트롤러에서 드라이브에서 캐시로 데이터 블록을 읽는 동안 순차적 데이터 블록을 추가로 캐시에 복사할 수 있습니다. 이 캐싱은 향후 캐시에서 데이터 요청을 채울 수 있는 기회를 높여줍니다. 동적 캐시 읽기 프리페치는 순차적 I/O를 사용하는 멀티미디어 애플리케이션에 중요합니다 캐시로 프리페치되는 데이터의 속도와 양은 호스트 읽기의 속도 및 요청 크기에 따라 자동으로 조정됩니다. 랜덤 액세스로 인해 데이터를 캐시로 프리페치하지 않습니다. 이 기능은 읽기 캐시를 사용하지 않는 경우 적용되지 않습니다.

씬 볼륨의 경우 동적 캐시 읽기 프리페치는 항상 비활성화되어 변경할 수 없습니다.



 a| 
가용 용량 영역
 a| 
사용 가능한 용량 영역은 볼륨 삭제 또는 볼륨 생성 중 사용 가능한 모든 용량을 사용하지 않함으로 인해 발생할 수 있는 사용 가능한 용량입니다. 하나 이상의 사용 가능한 용량 영역이 있는 볼륨 그룹에서 볼륨을 생성할 때 볼륨의 용량은 해당 볼륨 그룹에서 가장 큰 사용 가능한 용량 영역으로 제한됩니다. 예를 들어, 볼륨 그룹의 사용 가능한 용량이 총 15GiB이고 사용 가능한 최대 용량 영역이 10GiB인 경우 생성할 수 있는 최대 볼륨은 10GiB입니다.

여유 용량을 통합하면 볼륨 그룹의 최대 사용 가능 용량에서 추가 볼륨을 생성할 수 있습니다.



 a| 
호스트
 a| 
호스트는 스토리지 배열의 볼륨에 입출력을 전송하는 서버입니다.



 a| 
호스트 클러스터
 a| 
호스트 클러스터는 호스트 그룹입니다. 호스트 클러스터를 생성하여 동일한 볼륨을 여러 호스트에 쉽게 할당할 수 있습니다.



 a| 
핫 스페어 드라이브
 a| 
핫 스페어 드라이브는 볼륨 그룹에서만 지원됩니다. 핫 스페어 드라이브에는 데이터가 없으며 볼륨 그룹에 포함된 RAID 1, RAID 3, RAID 5 또는 RAID 6 볼륨에서 드라이브 장애가 발생할 경우 대기 상태로 작동합니다. 핫 스페어 드라이브는 스토리지 배열에 또 다른 수준의 중복성을 추가합니다.



 a| 
LUN을 클릭합니다
 a| 
LUN(Logical Unit Number)은 호스트가 볼륨을 액세스하는 데 사용하는 주소 공간에 할당된 번호입니다. 볼륨은 LUN 형태의 용량으로 호스트에 표시됩니다.

각 호스트에는 고유한 LUN 주소 공간이 있습니다. 따라서 서로 다른 호스트에서 동일한 LUN을 사용하여 서로 다른 볼륨에 액세스할 수 있습니다.



 a| 
미디어 스캔
 a| 
미디어 검사를 통해 드라이브에서 읽거나 쓰는 동안 드라이브 미디어 오류가 발견되기 전에 이를 감지할 수 있습니다. 미디어 검사는 백그라운드 작업으로 수행되고 정의된 사용자 볼륨에서 모든 데이터 및 중복 정보를 검사합니다.



 a| 
네임스페이스
 a| 
네임스페이스는 블록 액세스를 위해 포맷된 NVM 스토리지입니다. 스토리지 배열의 볼륨과 관련된 SCSI의 논리 유닛과 유사합니다.



 a| 
수영장
 a| 
풀은 논리적으로 그룹화된 드라이브 집합입니다. 풀을 사용하여 호스트에서 액세스할 수 있는 볼륨을 하나 이상 생성할 수 있습니다. (풀 또는 볼륨 그룹에서 볼륨을 생성하는 경우)



 a| 
풀 또는 볼륨 그룹 용량입니다
 a| 
풀, 볼륨 또는 볼륨 그룹 용량은 풀 또는 볼륨 그룹에 할당된 스토리지 시스템의 용량입니다. 이 용량은 볼륨을 생성하고 복사 서비스 작업 및 스토리지 오브젝트의 다양한 용량 요구사항을 지원하는 데 사용됩니다.



 a| 
읽기 캐시
 a| 
읽기 캐시는 드라이브에서 읽은 데이터를 저장하는 버퍼입니다. 읽기 작업의 데이터가 이전 작업의 캐시에 이미 있을 수 있으므로 드라이브에 액세스할 필요가 없습니다. 데이터가 플러시될 때까지 읽기 캐시에 남아 있습니다.



 a| 
보고된 용량입니다
 a| 
보고된 용량은 호스트에 보고되고 호스트에서 액세스할 수 있는 용량입니다.

보고된 용량과 할당된 용량은 일반 볼륨에서 동일하지만 씬 볼륨에서는 다릅니다. 일반 볼륨의 경우 물리적으로 할당된 공간은 호스트에 보고된 공간과 같습니다. 씬 볼륨의 경우 보고된 용량은 호스트에 보고된 용량이고, 할당된 용량은 데이터 쓰기에 현재 할당된 드라이브 공간의 양입니다.



 a| 
세그먼트 크기
 a| 
세그먼트는 스토리지 어레이가 스트라이프의 다음 드라이브(RAID 그룹)로 이동하기 전에 드라이브에 저장되는 데이터의 양(KB)입니다. 세그먼트 크기는 볼륨 그룹의 용량과 같거나 그보다 작습니다. 세그먼트 크기가 고정되어 풀의 경우 변경할 수 없습니다.



 a| 
스트라이핑
 a| 
스트라이핑은 스토리지 배열에 데이터를 저장하는 방식입니다. 스트라이핑은 데이터 흐름을 특정 크기의 블록("블록 크기")으로 분할한 다음 이러한 블록을 드라이브에 하나씩 씁니다. 이러한 데이터 저장 방식은 여러 물리적 드라이브에 데이터를 배포하고 저장하는 데 사용됩니다. 스트라이핑은 RAID 0과 동의어이며 패리티를 사용하지 않고 RAID 그룹의 모든 드라이브에 데이터를 분산합니다.



 a| 
볼륨
 a| 
볼륨은 애플리케이션, 데이터베이스 및 파일 시스템이 데이터를 저장하는 컨테이너입니다. 호스트가 스토리지의 스토리지를 액세스할 수 있도록 생성되는 논리적 구성 요소입니다.



 a| 
볼륨 할당
 a| 
볼륨 할당은 호스트 LUN이 볼륨에 할당되는 방법입니다.



 a| 
볼륨 이름입니다
 a| 
볼륨 이름은 볼륨 생성 시 볼륨에 할당된 문자열, 기본 이름을 그대로 사용하거나 볼륨에 저장된 데이터의 유형을 나타내는 보다 설명이 포함된 이름을 제공할 수 있습니다.



 a| 
볼륨 그룹
 a| 
볼륨 그룹은 공유 특성을 가진 볼륨의 컨테이너입니다. 볼륨 그룹의 용량과 RAID 레벨이 정의되어 있습니다. 볼륨 그룹을 사용하여 호스트에서 액세스할 수 있는 볼륨을 하나 이상 생성할 수 있습니다. 볼륨 그룹 또는 풀에서 볼륨을 생성합니다.



 a| 
워크로드
 a| 
워크로드는 애플리케이션을 지원하는 스토리지 객체입니다. 애플리케이션별로 하나 이상의 워크로드 또는 인스턴스를 정의할 수 있습니다. 일부 애플리케이션의 경우 시스템에서 기본 볼륨 특성이 비슷한 볼륨을 포함하도록 워크로드를 구성합니다. 이러한 볼륨 특성은 워크로드가 지원하는 애플리케이션 유형에 따라 최적화됩니다. 예를 들어, Microsoft SQL Server 애플리케이션을 지원하는 워크로드를 생성한 다음 해당 워크로드에 대한 볼륨을 생성하는 경우 기본 볼륨 특성은 Microsoft SQL Server를 지원하도록 최적화되어 있습니다.



 a| 
쓰기 캐시
 a| 
쓰기 캐시는 드라이브에 아직 기록되지 않은 호스트의 데이터를 저장하는 버퍼입니다. 데이터는 드라이브에 기록될 때까지 쓰기 캐시에 유지됩니다. 쓰기 캐싱은 I/O 성능을 높일 수 있습니다.



 a| 
미러링을 통한 쓰기 캐싱
 a| 
미러링으로 쓰기 캐싱은 한 컨트롤러의 캐시 메모리에 기록된 데이터가 다른 컨트롤러의 캐시 메모리에도 기록될 때 발생합니다. 따라서 한 컨트롤러에 장애가 발생하면 다른 컨트롤러가 처리되지 않은 모든 쓰기 작업을 완료할 수 있습니다. 쓰기 캐시 미러링은 쓰기 캐시가 설정되고 두 개의 컨트롤러가 있는 경우에만 사용할 수 있습니다. 볼륨 생성 시 기본 설정은 미러링을 사용한 쓰기 캐시입니다.



 a| 
배터리 없이 쓰기 캐싱
 a| 
배터리가 없는 쓰기 캐싱 설정을 사용하면 배터리가 없거나 고장, 완전히 방전되었거나 완전히 충전되지 않은 경우에도 쓰기 캐시가 계속 유지됩니다. 일반적으로 배터리 없이 쓰기 캐시를 선택하는 것은 권장되지 않습니다. 전원이 끊길 경우 데이터가 손실될 수 있기 때문입니다. 일반적으로 쓰기 캐시는 배터리가 충전되거나 장애가 발생한 배터리를 교체할 때까지 컨트롤러에 의해 일시적으로 꺼집니다.

|===


== 씬 볼륨에만 적용됩니다

[NOTE]
====
System Manager에서는 씬 볼륨을 생성하는 옵션을 제공하지 않습니다. 씬 볼륨을 생성하려면 CLI(Command Line Interface)를 사용합니다.

====
[NOTE]
====
EF600/EF600C 또는 EF300/EF300C 스토리지 시스템에서는 씬 볼륨을 사용할 수 없습니다.

====
[cols="25h,~"]
|===
| 기간 | 설명 


 a| 
할당된 용량 제한입니다
 a| 
할당된 용량 제한은 씬 볼륨에 할당된 물리적 용량을 확장할 수 있는 용량의 한도를 나타냅니다.



 a| 
쓰인 용량
 a| 
쓰인 용량은 씬 볼륨에 할당된 예약 용량에서 기록된 용량입니다.



 a| 
경고 임계값
 a| 
씬 볼륨에 할당된 용량이 최대 백분율(경고 임계값)에 도달하면 경고 임계값 알림이 발생하도록 설정할 수 있습니다.

|===