---
permalink: sm-mirroring/asynchronous-mirror-status.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, asynchronous, mirror, status, consistency, group, 
summary: 미러 상태는 미러 정합성 보장 그룹 및 미러링된 볼륨 쌍의 상태를 정의합니다. 
---
= 비동기식 미러 상태입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
미러 상태는 미러 정합성 보장 그룹 및 미러링된 볼륨 쌍의 상태를 정의합니다.



== 미러 정합성 보장 그룹의 상태입니다

[cols="25h,~"]
|===
| 상태 | 설명 


 a| 
동기화 중(초기 동기화)
 a| 
미러링된 볼륨 쌍 간에 완료된 초기 데이터 동기화 진행률

초기 동기화 중에 볼륨이 Degraded/Failed/Optimal/Unknown 상태로 전환될 수 있습니다.



 a| 
동기화 중(간격 동기화)
 a| 
미러링된 볼륨 쌍 간에 완료된 주기적 데이터 동기화 진행률



 a| 
시스템이 일시 중단되었습니다
 a| 
스토리지 시스템 - 미러 정합성 보장 그룹 레벨에서 미러링된 모든 쌍의 데이터에 대한 일시 중지된 동기화

미러 정합성 보장 그룹에 있는 하나 이상의 미러링된 페어가 중지됨 또는 실패 상태입니다.



 a| 
사용자가 일시 중단되었습니다
 a| 
미러 정합성 보장 그룹 레벨에서 미러링된 모든 쌍의 데이터에 대한 사용자 일시 중단 동기화

이 상태는 로컬 스토리지 배열의 변경된 데이터가 원격 스토리지 배열에 복사되는 동안 발생할 수 있는 호스트 응용 프로그램에 대한 성능 영향을 줄이는 데 도움이 됩니다.



 a| 
일시 중지되었습니다
 a| 
원격 스토리지 배열에 액세스하는 동안 오류가 발생하여 데이터 동기화 프로세스가 일시적으로 중지되었습니다.



 a| 
Orphan.(
 a| 
분리된 미러링된 쌍 볼륨은 정합성 보장 미러 그룹의 구성원 볼륨이 정합성 보장 미러 그룹(운영 측 또는 2차 측)의 한쪽에서 제거되었지만 다른 측에서는 제거되지 않은 경우에 존재합니다.

스토리지 간 통신이 복구되고 미러 구성의 양측이 미러 매개 변수를 조정할 때 분리된 미러링된 쌍 볼륨이 감지됩니다.

미러링된 쌍을 제거하여 분리된 미러 쌍 상태를 수정할 수 있습니다.



 a| 
역할 변경 보류/진행 중
 a| 
미러 정합성 보장 그룹 간의 역할 변경이 보류 중이거나 진행 중입니다.

역할 전환 변경(기본 역할 또는 보조 역할)은 선택한 미러 정합성 보장 그룹 내의 모든 비동기식 미러링 쌍에 영향을 줍니다.

보류 중인 역할 변경은 취소할 수 있지만 진행 중인 역할 변경은 취소할 수 없습니다.



 a| 
역할 충돌
 a| 
역할 변경 작업 중에 로컬 스토리지와 원격 스토리지 시스템 간의 통신 문제로 인해 미러 정합성 보장 그룹 간에 역할 충돌이 발생했습니다.

통신 문제가 해결되면 역할 충돌이 발생합니다. Recovery Guru를 사용하여 이 오류를 복구합니다.

역할 충돌을 해결할 때는 강제 승격이 허용되지 않습니다.

|===


== 미러링된 쌍의 상태입니다

미러링된 쌍의 상태는 운영 볼륨과 2차 볼륨의 데이터가 동기화되었는지 여부를 나타냅니다.

[cols="25h,~"]
|===
| 상태 | 설명 


 a| 
동기화 중입니다
 a| 
미러링된 쌍 간에 완료된 초기 또는 주기적 데이터 동기화의 진행 상태

동기화에는 초기 동기화와 주기적 동기화의 두 가지 유형이 있습니다. 초기 동기화 진행률은 장기 실행 작업 대화 상자에도 표시됩니다.



 a| 
최적
 a| 
미러링된 쌍의 볼륨은 동기화되며, 이는 스토리지 어레이 간의 접속이 작동하고 각 볼륨이 원하는 작업 조건에 있음을 나타냅니다.



 a| 
완료되지 않았습니다
 a| 
미러링된 쌍 생성 시퀀스가 System Manager에서 지원되지 않고 미러링된 쌍이 보조 스토리지에서 완료되지 않았기 때문에 원격 스토리지 시스템에서 비동기식 미러링 쌍이 불완전합니다.

원격 스토리지 시스템의 미러 정합성 보장 그룹에 볼륨을 추가하면 미러링된 페어 생성 프로세스가 완료됩니다. 이 볼륨은 비동기식 미러링 쌍의 2차 볼륨이 됩니다.

원격 스토리지 배열이 System Manager에 의해 관리되는 경우 미러링된 쌍은 자동으로 완료됩니다.



 a| 
실패했습니다
 a| 
운영 볼륨, 보조 볼륨 또는 미러 예약 용량에 장애가 발생하여 비동기식 미러링 작업이 정상적으로 작동하지 않습니다.



 a| 
Orphan.(
 a| 
분리된 미러링된 쌍 볼륨은 정합성 보장 미러 그룹의 구성원 볼륨이 정합성 보장 미러 그룹(운영 측 또는 2차 측)의 한쪽에서 제거되었지만 다른 측에서는 제거되지 않은 경우에 존재합니다.

분리된 미러링된 쌍 볼륨은 두 스토리지 어레이와 미러 구성의 두 측면 간에 통신이 복구되면 감지되며 미러 매개 변수가 조정됩니다.

미러링된 쌍을 제거하여 분리된 미러 쌍 상태를 수정할 수 있습니다.



 a| 
중지되었습니다
 a| 
미러 정합성 보장 그룹이 시스템 일시 중단 상태이므로 미러링된 페어가 중지 상태입니다.

|===