---
permalink: sm-mirroring/change-synchronization-settings-for-a-mirror-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, synchronization, settings, mirror, consistency, group, 
summary: 데이터가 처음 동기화될 때 또는 비동기식 미러링 작업 중에 데이터가 다시 동기화될 때 로컬 스토리지 시스템의 미러 정합성 보장 그룹이 사용하는 동기화 설정 및 경고 임계값을 변경할 수 있습니다. 
---
= 미러 정합성 보장 그룹의 동기화 설정을 변경합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터가 처음 동기화될 때 또는 비동기식 미러링 작업 중에 데이터가 다시 동기화될 때 로컬 스토리지 시스템의 미러 정합성 보장 그룹이 사용하는 동기화 설정 및 경고 임계값을 변경할 수 있습니다.

.이 작업에 대해
동기화 설정을 변경하면 미러 정합성 보장 그룹 내의 모든 미러링된 쌍의 동기화 작업에 영향을 줍니다.

.단계
. 메뉴: 스토리지 [비동기 미러링]을 선택합니다.
. 미러 정합성 보장 그룹 * 탭을 선택합니다.
+
미러링된 정합성 보장 그룹 테이블이 나타나고 스토리지 시스템과 연결된 모든 미러 정합성 보장 그룹이 표시됩니다.

. 편집하려는 미러 정합성 보장 그룹을 선택한 다음 MENU: More [Edit Settings] 를 선택합니다.
+
설정 편집 대화 상자가 표시됩니다.

. 동기화 및 알림 설정을 적절히 편집한 다음 * 저장 * 을 클릭합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 필드에 입력합니다 | 설명 


 a| 
미러링된 쌍 동기화...
 a| 
원격 스토리지 배열의 미러링된 쌍을 수동 또는 자동으로 동기화할지 여부를 지정합니다.

** ** 수동** – 원격 스토리지 배열의 미러링된 쌍을 수동으로 동기화하려면 이 옵션을 선택합니다.
** 자동, 매** – 이전 업데이트 시작에서 다음 업데이트 시작까지의 시간 간격을 지정하여 원격 스토리지 배열의 미러링된 쌍을 자동으로 동기화하려면 이 옵션을 선택합니다. 기본 간격은 10분입니다.




 a| 
알림...
 a| 
동기화 방법을 자동으로 발생하도록 설정한 경우 다음 경고를 설정합니다.

** ** 동기화** – System Manager가 동기화가 완료되지 않은 알림을 보낸 후 시간을 설정합니다.
** ** 원격 복구 지점** – System Manager가 원격 스토리지 배열의 복구 지점 데이터가 정의된 시간 제한보다 오래되었음을 나타내는 경고를 보낸 후 시간 제한을 설정합니다. 이전 업데이트 종료에서 시간 제한을 정의합니다.
** ** 예약된 용량 임계값** – 예약된 용량 임계값에 근접한 알림을 System Manager에서 보내는 예약 용량 양을 정의합니다. 남은 용량 대비 임계값을 정의합니다.


|===
====


.결과
System Manager는 미러 정합성 보장 그룹의 모든 미러링된 쌍에 대한 동기화 설정을 변경합니다.
