---
permalink: sm-mirroring/change-mirror-consistency-group-role-to-primary-or-secondary.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, mirror, consistency group, primary, secondary 
summary: 관리를 위해 또는 로컬 스토리지 시스템에 재해가 발생한 경우 미러 정합성 보장 그룹 간에 역할을 변경할 수 있습니다. 
---
= 미러 정합성 보장 그룹 역할을 운영 또는 2차 역할로 변경합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리를 위해 또는 로컬 스토리지 시스템에 재해가 발생한 경우 미러 정합성 보장 그룹 간에 역할을 변경할 수 있습니다.

.이 작업에 대해
로컬 스토리지 시스템에 생성된 미러 정합성 보장 그룹은 운영 역할을 담당합니다. 원격 스토리지 시스템에 생성된 미러 정합성 보장 그룹은 2차 역할을 수행합니다. 로컬 미러 정합성 보장 그룹을 보조 역할로 하향 이동하거나 원격 미러 정합성 보장 그룹을 운영 역할로 상향 이동할 수 있습니다.

.단계
. 메뉴: 스토리지 [비동기 미러링]을 선택합니다.
. 미러 정합성 보장 그룹 * 탭을 선택합니다.
+
미러 정합성 보장 그룹 테이블이 나타나고 스토리지 시스템과 연결된 모든 미러 정합성 보장 그룹이 표시됩니다.

. 역할을 변경할 미러 정합성 보장 그룹을 선택한 다음 More [Change role to <Primary|Secondary>] *> * 메뉴를 선택합니다.
+
확인 메시지가 표시됩니다.

. 미러 정합성 보장 그룹의 역할을 변경할 것인지 확인한 다음 * 역할 변경 * 을 클릭합니다.
+
[NOTE]
====
역할 변경이 요청되었지만 원격 스토리지 어레이에 연결할 수 없는 경우 스토리지 시스템에 연결할 수 없음 대화 상자가 표시됩니다. 예 * 를 클릭하여 역할 변경을 강제 적용합니다.

====


.결과
System Manager는 다음 작업을 수행합니다.

* 미러 정합성 보장 그룹 테이블에는 역할 변경을 진행 중인 미러 정합성 보장 그룹 옆에 "보류 중" 또는 "진행 중" 상태가 표시됩니다. 테이블 셀에 있는 * Cancel * 링크를 클릭하여 보류 중인 역할 변경 작업을 취소할 수 있습니다.
* 연결된 미러 정합성 보장 그룹에 접속할 수 있으면 미러 정합성 보장 그룹 간의 역할이 변경됩니다. System Manager는 보조 미러 정합성 보장 그룹을 기본 역할로 상향 이동하거나 선택 항목에 따라 기본 미러 정합성 보장 그룹을 보조 역할로 하향 이동합니다. 역할 변경은 선택한 미러 정합성 보장 그룹 내의 모든 미러링된 쌍에 영향을 줍니다.

