---
permalink: sm-mirroring/complete-mirrored-pair-for-primary-volumes-created-on-legacy-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, complete, mirrored, pair, volumes, created, legacy, 
summary: SANtricity System Manager로 관리할 수 없는 기존 스토리지 어레이에서 운영 볼륨을 생성한 경우, System Manager로 이 어레이에 2차 볼륨을 생성할 수 있습니다. 
---
= 기존 시스템에서 생성된 운영 볼륨에 대해 완전한 미러링 쌍을 제공합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager로 관리할 수 없는 기존 스토리지 어레이에서 운영 볼륨을 생성한 경우 System Manager로 이 어레이에 2차 볼륨을 생성할 수 있습니다.

.이 작업에 대해
다른 인터페이스를 사용하는 기존 어레이와 System Manager에서 관리할 수 있는 최신 어레이 간에 비동기식 미러링을 수행할 수 있습니다.

* System Manager를 사용하는 두 스토리지 어레이 간에 미러링할 경우 미러링된 쌍의 생성 순서에 따라 이미 완료된 것이므로 이 작업을 건너뛸 수 있습니다.
* 원격 스토리지 시스템에서 이 작업을 수행합니다.


.단계
. 메뉴: 스토리지 [비동기 미러링]을 선택합니다.
. Mirrored Pair * 탭을 선택합니다.
+
미러링된 페어 테이블이 나타나고 스토리지 배열과 연결된 모든 미러링된 쌍이 표시됩니다.

. Incomplete(미완료) 상태의 미러링된 쌍 볼륨을 찾은 다음 미러링된 쌍 열에 표시된 * Complete Mirrored pair(완전 미러링 쌍) * 링크를 클릭합니다.
. 다음 라디오 버튼 중 하나를 선택하여 미러링된 쌍 생성 시퀀스를 자동으로 완료할지 아니면 수동으로 완료할지를 선택합니다.
+
** * 자동 * -- 새 보조 볼륨을 생성합니다.
+
2차 볼륨을 생성할 기존 풀 또는 볼륨 그룹을 선택하여 미러링된 쌍의 원격 측에 대한 기본 설정을 적용합니다. 이 권장 옵션을 사용하여 보조 볼륨에 예약된 용량을 기본 설정으로 할당합니다.

** * 수동 * -- 기존 볼륨을 선택합니다.
+
2차 볼륨에 대한 매개 변수를 정의합니다.

+
... 다음 * 을 클릭하여 보조 볼륨을 선택합니다.
... 보조 볼륨으로 사용할 기존 볼륨을 선택한 후 * Next * 를 클릭하여 예약된 용량을 할당합니다.
... 예약된 용량을 할당합니다. 다음 중 하나를 수행합니다.
+
**** 기본 설정을 적용합니다.
+
예약된 용량의 기본 설정은 기본 볼륨 용량의 20%이며 일반적으로 이 용량이면 충분합니다.

**** 비동기식 미러링과 관련된 데이터 스토리지 요구 사항을 충족하기 위해 예약 용량 설정을 직접 할당합니다.
+
필요한 용량은 운영 볼륨에 대한 I/O 쓰기의 빈도 및 크기와 용량을 유지하는 데 필요한 기간에 따라 달라집니다. 일반적으로 다음 조건 중 하나 또는 둘 다 존재할 경우 예약된 용량에 더 큰 용량을 선택합니다.

+
***** 미러링 쌍을 장기간 유지하려고 합니다.
***** 입출력 작업이 많은 경우 운영 볼륨에서 데이터 블록의 비율이 크게 변경됩니다. 기간별 성능 데이터 또는 기타 운영 체제 유틸리티를 사용하여 기본 볼륨에 대한 일반적인 I/O 작업을 결정할 수 있습니다.








. 완료 * 를 선택합니다.


.결과
System Manager는 다음 작업을 수행합니다.

* 원격 스토리지 시스템에 보조 볼륨을 생성하고 미러링된 쌍의 원격 측에 예약된 용량을 할당합니다.
* 로컬 스토리지와 원격 스토리지 시스템 간의 초기 동기화를 시작합니다.
* 미러링되는 볼륨이 씬 볼륨인 경우 초기 동기화 중에 할당된 블록만 보조 볼륨으로 전송됩니다. 이 전송으로 초기 동기화를 완료하기 위해 전송해야 하는 데이터의 양이 줄어듭니다.
* 로컬 스토리지 시스템 및 원격 스토리지 시스템에서 미러링된 쌍에 대한 예약된 용량을 생성합니다.

