---
permalink: sm-mirroring/faq-sync-mirroring.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager에 대한 동기화 미러링 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 비동기식 미러링은 동기식 미러링과 어떻게 다릅니까?

비동기 미러링 기능은 동기 미러링 기능과 다릅니다. 한 가지 중요한 방법은 특정 시점의 소스 볼륨 상태를 캡처하고 마지막 이미지 캡처 이후 변경된 데이터만 복사하는 것입니다.

동기식 미러링을 사용하면 기본 볼륨의 상태가 특정 시점에 캡처되지 않고 기본 볼륨에서 2차 볼륨으로 이루어진 모든 변경 사항을 반영합니다. 이 유형의 미러에서는 주 볼륨에 쓸 때마다 보조 볼륨에 쓰기가 수행되므로 2차 볼륨은 매 순간마다 1차 볼륨과 동일합니다. 보조 볼륨이 운영 볼륨에서 수행된 변경 사항으로 성공적으로 업데이트될 때까지 호스트는 쓰기가 성공했다는 확인 메시지를 받지 않습니다.

비동기식 미러링을 사용하면 원격 스토리지 시스템이 로컬 스토리지 어레이와 완전히 동기화되지 않으므로 로컬 스토리지 어레이의 손실로 인해 애플리케이션을 원격 스토리지 어레이로 전환해야 하는 경우 일부 트랜잭션이 손실될 수 있습니다.

대칭 복사 피처 비교:

[cols="1a,1a"]
|===
| 비동기 미러링 | 동기 미러링 


 a| 
* 복제 방법 *



 a| 
* * 시점 *
+
미러링은 사용자 정의 일정에 따라 필요 시 또는 자동으로 수행됩니다. 일정은 분 단위로 정의할 수 있습니다. 동기화 사이의 최소 시간은 10분입니다.


 a| 
* * 연속 *
+
미러링은 모든 호스트 쓰기에서 데이터를 복사하여 지속적으로 자동 실행됩니다.





 a| 
* 예약된 용량 *



 a| 
* * 다중 *
+
각 미러링된 쌍에 대해 예약된 용량 볼륨이 필요합니다.


 a| 
* * 단일 *
+
미러링된 모든 볼륨에 단일 예약 용량 볼륨이 필요합니다.





 a| 
* 커뮤니케이션 *



 a| 
* * iSCSI 및 파이버 채널 *
+
스토리지 시스템 간의 iSCSI 및 Fibre Channel 인터페이스를 지원합니다.


 a| 
* 파이버 채널 *
+
스토리지 시스템 간 Fibre Channel 인터페이스만 지원합니다.





 a| 
* 거리 *



 a| 
* * 무제한 *
+
로컬 스토리지 어레이와 원격 스토리지 시스템 간의 거리 제한이 거의 없으며, 일반적으로 네트워크 기능과 채널 확장 기술에 의해서만 거리가 제한됩니다.


 a| 
* * 제한 *
+
일반적으로 지연 시간 및 애플리케이션 성능 요구 사항을 충족하려면 로컬 스토리지 어레이에서 약 10km(6.2마일) 이내에 있어야 합니다.



|===


== 동기식 미러링 - 왜 모든 볼륨이 보이지 않나요?

미러링된 쌍의 기본 볼륨을 선택하면 목록에 모든 적격 볼륨이 표시됩니다.

사용할 수 없는 볼륨은 해당 목록에 표시되지 않습니다. 볼륨은 다음과 같은 이유로 적합하지 않을 수 있습니다.

* 볼륨은 스냅샷 볼륨 또는 씬 볼륨과 같은 비표준 볼륨입니다.
* 볼륨이 최적이 아닙니다.
* 볼륨이 이미 미러링 관계에 있습니다.




== 동기식 미러링 - 원격 스토리지 어레이의 모든 볼륨이 표시되지 않는 이유는 무엇입니까?

원격 스토리지 어레이에서 보조 볼륨을 선택할 경우 목록에 해당 미러링된 쌍에 대해 적합한 볼륨이 모두 표시됩니다.

사용할 수 없는 볼륨은 해당 목록에 표시되지 않습니다. 볼륨은 다음과 같은 이유로 적합하지 않을 수 있습니다.

* 볼륨은 스냅샷 볼륨 또는 씬 볼륨과 같은 비표준 볼륨입니다.
* 볼륨이 최적이 아닙니다.
* 볼륨이 이미 미러링 관계에 있습니다.
* DA(Data Assurance)를 사용하는 경우 운영 볼륨과 보조 볼륨의 DA 설정이 동일해야 합니다.
+
** 운영 볼륨이 DA를 사용하는 경우 보조 볼륨은 DA를 활성화해야 합니다.
** 운영 볼륨이 DA를 사용하지 않는 경우 보조 볼륨을 DA로 설정하지 않아야 합니다.






== 동기식 미러링 - 미러링된 쌍을 만들기 전에 알아야 할 것은 무엇입니까?

SANtricity Unified Manager 인터페이스에서 미러링된 쌍을 구성한 다음, SANtricity System Manager에서 쌍을 관리합니다.

대칭 복사 쌍을 만들기 전에 다음 지침을 따릅니다.

* 두 개의 스토리지 어레이가 있어야 합니다.
* 각 스토리지 어레이에는 2개의 컨트롤러가 필요합니다.
* 기본 어레이와 보조 어레이의 각 컨트롤러에는 이더넷 관리 포트가 구성되어 있어야 하며 네트워크에 연결되어 있어야 합니다.
* 로컬 및 원격 스토리지 어레이는 파이버 채널 패브릭을 통해 연결됩니다.
* 스토리지 어레이의 펌웨어 버전은 최소 7.84입니다. (각 OS 버전은 서로 다를 수 있음)
* 로컬 및 원격 스토리지 배열의 암호를 알아야 합니다.
* 미러링할 운영 볼륨과 같거나 더 큰 보조 볼륨을 생성하려면 원격 스토리지 시스템에 사용 가능한 용량이 충분해야 합니다.
* 웹 서비스 프록시 및 Unified Manager를 설치했습니다. 미러링된 쌍은 Unified Manager 인터페이스에 구성됩니다.
* 두 스토리지 어레이가 Unified Manager에서 검색됩니다.




== 동기화 우선 순위가 동기화 속도에 어떤 영향을 미칩니까?

동기화 우선 순위는 시스템 성능과 관련하여 동기화 작업에 할당되는 처리 시간을 정의합니다.

운영 볼륨의 컨트롤러 소유자가 이 작업을 백그라운드에서 수행합니다. 동시에 컨트롤러 소유자가 운영 볼륨에 대한 로컬 I/O 쓰기 및 보조 볼륨에 대한 관련 원격 쓰기를 처리합니다. 재동기화는 컨트롤러 처리 리소스를 입출력 작업에서 전환하므로 재동기화는 호스트 애플리케이션의 성능에 영향을 미칠 수 있습니다.

동기화 우선 순위가 얼마나 오래 걸릴 수 있고 동기화 우선 순위가 시스템 성능에 어떤 영향을 미칠 수 있는지 결정할 수 있도록 이 지침을 염두에 두십시오.

.동기화 우선 순위 속도 정보
[%collapsible]
====
다음과 같은 우선 순위가 있습니다.

* 최저
* 낮음
* 중간
* 높음
* 최고


우선 순위가 가장 낮은 속도는 시스템 성능을 지원하지만 재동기화에 더 많은 시간이 걸립니다. 우선 순위가 가장 높은 속도가 재동기화를 지원하지만 시스템 성능이 저하될 수 있습니다.

====
이 지침은 우선 순위 간의 차이를 대략적으로 나타냅니다.

[cols="35h,~"]
|===
| 전체 동기화의 우선 순위 속도 | 최고 동기화 속도에 비해 경과된 시간입니다 


 a| 
최저
 a| 
최고 우선 순위인 경우 약 8배



 a| 
낮음
 a| 
최고 우선 순위인 경우 약 6배



 a| 
중간
 a| 
가장 높은 우선 순위에서 약 3배 반 정도 소요됩니다.



 a| 
높음
 a| 
최고 우선 순위보다 약 2배 긴 시간.

|===
볼륨 크기 및 호스트 I/O 속도 로드는 동기화 시간 비교에 영향을 줍니다.



== 수동 동기화 정책을 사용하는 것이 권장되는 이유는 무엇입니까?

수동 재동기화는 재동기화 프로세스를 관리하여 데이터를 복구할 수 있는 최적의 기회를 제공하기 때문에 권장됩니다.

자동 재동기화 정책을 사용하고 재동기화 중에 간헐적인 통신 문제가 발생하는 경우 보조 볼륨의 데이터가 일시적으로 손상될 수 있습니다. 재동기화가 완료되면 데이터가 수정됩니다.
