---
permalink: sm-mirroring/faq-async-mirroring.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager에 대한 비동기 미러링 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 비동기식 미러링은 동기식 미러링과 어떻게 다릅니까?

비동기 미러링 기능은 동기 미러링 기능과 다릅니다. 한 가지 중요한 방법은 특정 시점의 소스 볼륨 상태를 캡처하고 마지막 이미지 캡처 이후 변경된 데이터만 복사하는 것입니다.

동기식 미러링을 사용하면 기본 볼륨의 상태가 특정 시점에 캡처되지 않고 기본 볼륨에서 2차 볼륨으로 이루어진 모든 변경 사항을 반영합니다. 이 유형의 미러에서는 주 볼륨에 쓸 때마다 보조 볼륨에 쓰기가 수행되므로 2차 볼륨은 매 순간마다 1차 볼륨과 동일합니다. 보조 볼륨이 운영 볼륨에서 수행된 변경 사항으로 성공적으로 업데이트될 때까지 호스트는 쓰기가 성공했다는 확인 메시지를 받지 않습니다.

비동기식 미러링을 사용하면 원격 스토리지 시스템이 로컬 스토리지 어레이와 완전히 동기화되지 않으므로 로컬 스토리지 어레이의 손실로 인해 애플리케이션을 원격 스토리지 어레이로 전환해야 하는 경우 일부 트랜잭션이 손실될 수 있습니다.

대칭 복사 피처 비교:

[cols="1a,1a"]
|===
| 비동기 미러링 | 동기 미러링 


 a| 
* 복제 방법 *



 a| 
* * 시점 *
+
미러링은 사용자 정의 일정에 따라 필요 시 또는 자동으로 수행됩니다. 일정은 분 단위로 정의할 수 있습니다. 동기화 사이의 최소 시간은 10분입니다.


 a| 
* * 연속 *
+
미러링은 모든 호스트 쓰기에서 데이터를 복사하여 지속적으로 자동 실행됩니다.





 a| 
* 예약된 용량 *



 a| 
* * 다중 *
+
각 미러링된 쌍에 대해 예약된 용량 볼륨이 필요합니다.


 a| 
* * 단일 *
+
미러링된 모든 볼륨에 단일 예약 용량 볼륨이 필요합니다.





 a| 
* 커뮤니케이션 *



 a| 
* * iSCSI 및 파이버 채널 *
+
스토리지 시스템 간의 iSCSI 및 Fibre Channel 인터페이스를 지원합니다.


 a| 
* 파이버 채널 *
+
스토리지 시스템 간 Fibre Channel 인터페이스만 지원합니다.





 a| 
* 거리 *



 a| 
* * 무제한 *
+
로컬 스토리지 어레이와 원격 스토리지 시스템 간의 거리 제한이 거의 없으며, 일반적으로 네트워크 기능과 채널 확장 기술에 의해서만 거리가 제한됩니다.


 a| 
* * 제한 *
+
일반적으로 지연 시간 및 애플리케이션 성능 요구 사항을 충족하려면 로컬 스토리지 어레이에서 약 10km(6.2마일) 이내에 있어야 합니다.



|===


== 선택한 미러링 기능에 왜 액세스할 수 없나요?

미러링은 SANtricity Unified Manager 인터페이스에서 구성됩니다.

[NOTE]
====
EF600/EF600C 또는 EF300/EF300C 스토리지 어레이에서는 동기식 미러링을 사용할 수 없습니다.

====
두 어레이 간에 미러링을 설정하고 구성하려면 다음을 확인하십시오.

* 웹 서비스 프록시 서비스가 실행되고 있어야 합니다. (Unified Manager는 웹 서비스 프록시와 함께 호스트 시스템에 설치됩니다.)
* Unified Manager는 HTTPS 연결을 통해 로컬 호스트에서 실행되고 있어야 합니다.
* 미러링에 사용할 두 스토리지 어레이가 Unified Manager에서 검색되어야 합니다.
* Unified Manager에는 스토리지 어레이에 대한 유효한 SSL 인증서가 있어야 합니다. 자체 서명된 인증서를 수락하거나 Unified Manager에서 CA 서명 인증서를 설치할 수 있습니다.


구성 지침은 다음을 참조하십시오.

* link:../um-manage/create-asynchronous-mirrored-pair-um.html["Unified Manager에서 비동기 미러링된 쌍 생성"]
* link:../um-manage/create-synchronous-mirrored-pair-um.html["동기식 미러링 쌍 생성(Unified Manager에서)"]




== 미러 정합성 보장 그룹을 생성하기 전에 알아야 할 내용은 무엇입니까?

미러 일관성 그룹을 생성하기 전에 다음 지침을 따르십시오.

[NOTE]
====
EF600/EF600C 또는 EF300/EF300C 스토리지 시스템에서는 동기식 미러링을 사용할 수 없습니다.

====
Unified Manager의 미러링된 쌍 생성 마법사에서 일관성 그룹을 생성합니다.

Unified Manager에 대한 다음 요구사항을 충족합니다.

* 웹 서비스 프록시 서비스가 실행되고 있어야 합니다.
* Unified Manager는 HTTPS 연결을 통해 로컬 호스트에서 실행되고 있어야 합니다.
* Unified Manager에 스토리지 시스템에 대한 유효한 SSL 인증서가 표시되어야 합니다. 자체 서명된 인증서를 수락하거나 Unified Manager를 사용하여 인증서 [인증서 관리] 메뉴로 이동하여 자체 보안 인증서를 설치할 수 있습니다.


또한 스토리지 어레이에 대한 다음 요구 사항도 충족해야 합니다.

* Unified Manager에서 2개의 스토리지 어레이가 검색되어야 합니다.
* 각 스토리지 어레이에는 2개의 컨트롤러가 필요합니다.
* 기본 어레이와 보조 어레이의 각 컨트롤러에는 이더넷 관리 포트가 구성되어 있어야 하며 네트워크에 연결되어 있어야 합니다.
* 스토리지 어레이의 펌웨어 버전은 최소 7.84입니다. (각 OS 버전은 서로 다를 수 있음)
* 로컬 및 원격 스토리지 배열의 암호를 알아야 합니다.
* 로컬 및 원격 스토리지 어레이는 파이버 채널 패브릭 또는 iSCSI 인터페이스를 통해 연결됩니다.




== 비동기 미러링 - 미러링된 쌍을 만들기 전에 알아야 할 것은 무엇입니까?

SANtricity Unified Manager 인터페이스에서 미러링된 쌍을 구성한 다음, SANtricity System Manager에서 쌍을 관리합니다.

대칭 복사된 쌍을 만들기 전에 다음 지침을 따릅니다.

* 두 개의 스토리지 어레이가 있어야 합니다.
* 각 스토리지 어레이에는 2개의 컨트롤러가 필요합니다.
* 기본 어레이와 보조 어레이의 각 컨트롤러에는 이더넷 관리 포트가 구성되어 있어야 하며 네트워크에 연결되어 있어야 합니다.
* 로컬 및 원격 스토리지 어레이는 파이버 채널 패브릭 또는 iSCSI 인터페이스를 통해 연결됩니다.
* 스토리지 어레이의 펌웨어 버전은 최소 7.84입니다. (각 OS 버전은 서로 다를 수 있음)
* 로컬 및 원격 스토리지 배열의 암호를 알아야 합니다.
* 미러링할 운영 볼륨과 같거나 더 큰 보조 볼륨을 생성하려면 원격 스토리지 시스템에 사용 가능한 용량이 충분해야 합니다.
* 웹 서비스 프록시 및 Unified Manager를 설치했습니다. 미러링된 쌍은 Unified Manager 인터페이스에 구성됩니다.
* 두 스토리지 어레이가 Unified Manager에서 검색됩니다.
* 스토리지 시스템에 하나 이상의 미러 정합성 보장 그룹이 있어야 합니다. Unified Manager의 미러링된 쌍 생성 마법사에서 일관성 그룹을 생성합니다.




== 미러링된 쌍 볼륨에서 예약된 용량을 증가시키기 전에 무엇을 알아야 합니까?

일반적으로 미러링된 쌍에 대한 예약된 용량이 가득 차고 있다는 경고가 나타나면 예약된 용량을 늘려야 합니다. 예약 용량은 8GiB의 증분으로 늘릴 수 있습니다.

비동기식 미러링 작업의 경우 예약 용량은 일반적으로 기본 볼륨의 20%입니다. 다음 조건 중 하나 또는 둘 다 존재할 경우 예약된 용량에 더 큰 용량을 선택합니다.

* 미러링 쌍을 장기간 유지하려고 합니다.
* 입출력 작업이 많은 경우 운영 볼륨에서 데이터 블록의 비율이 크게 변경됩니다. 기간별 성능 데이터 또는 기타 운영 체제 유틸리티를 사용하여 기본 볼륨에 대한 일반적인 I/O 작업을 결정할 수 있습니다.


다음 작업 중 하나를 수행하여 미러링된 쌍에 대해 예약된 용량을 늘릴 수 있습니다.

* Storage[Pools and Volumes Groups](스토리지[풀 및 볼륨 그룹]) 메뉴를 선택한 다음 * Reserved Capacity *(예약된 용량) 탭을 클릭하여 미러링된 쌍 볼륨의 용량 비율을 조정합니다.
* 풀 또는 볼륨 그룹에서 사용 가능한 용량을 사용하여 새 볼륨을 생성합니다.
+
풀 또는 볼륨 그룹에 사용 가능한 용량이 없는 경우 구성되지 않은 용량을 미사용 드라이브 형태로 풀 또는 볼륨 그룹에 추가할 수 있습니다.





== 요청한 양만큼 예약된 용량을 늘릴 수 없는 이유는 무엇인가요?

예약 용량은 4GiB의 증분으로 늘릴 수 있습니다.

다음 지침을 검토하십시오.

* 필요한 경우 확장할 수 있도록 풀 또는 볼륨 그룹에 충분한 가용 용량이 있어야 합니다.
+
풀 또는 볼륨 그룹에 사용 가능한 용량이 없는 경우, 할당되지 않은 용량을 미사용 드라이브 형식으로 풀 또는 볼륨 그룹에 추가할 수 있습니다.

* 풀 또는 볼륨 그룹의 볼륨은 최적 상태여야 하며 수정 상태가 아니어야 합니다.
* 용량을 늘리기 위해 사용할 풀 또는 볼륨 그룹에 사용 가능한 용량이 있어야 합니다.


비동기식 미러링 작업의 경우 예약된 용량은 일반적으로 기본 볼륨의 20%입니다. 기본 볼륨에 많은 변경이 있을 것으로 예상되거나 스토리지 오브젝트의 복사 서비스 작업 예상 수명이 매우 길 경우 더 높은 비율을 사용하십시오.



== 이 비율을 변경하는 이유는 무엇입니까?

예약된 용량은 일반적으로 스냅샷 작업을 위한 기본 볼륨의 40%와 비동기식 미러링 작업을 위한 기본 볼륨의 20%입니다.

일반적으로 이 용량이면 충분합니다. 필요한 용량은 기본 볼륨에 대한 I/O 쓰기의 빈도 및 크기와 스토리지 오브젝트의 복사 서비스 작업을 사용할 기간에 따라 달라집니다.

일반적으로 다음 조건 중 하나 또는 둘 다 존재할 경우 예약된 용량에 더 큰 비율을 선택합니다.

* 특정 스토리지 오브젝트의 복사 서비스 작업 수명이 매우 긴 경우
* 입출력 작업이 많은 경우 기본 볼륨에서 데이터 블록의 비율이 크게 변경될 수 있습니다. 기간별 성능 데이터 또는 기타 운영 체제 유틸리티를 사용하여 기본 볼륨에 대한 일반적인 I/O 작업을 결정할 수 있습니다.




== 예약된 용량이 두 개 이상 표시되는 이유는 무엇입니까?

풀 또는 볼륨 그룹에 스토리지 객체에 대해 선택한 용량 비율을 충족하는 볼륨이 두 개 이상 있는 경우 여러 후보가 표시됩니다.

복사 서비스 작업을 위해 기본 볼륨에 예약할 물리적 드라이브 공간의 비율을 변경하여 권장되는 후보 목록을 새로 고칠 수 있습니다. 선택한 내용에 따라 가장 적합한 후보가 표시됩니다.



== 테이블에 사용할 수 없는 값이 표시되는 이유는 무엇입니까?

원격 스토리지 배열에 있는 데이터를 표시할 수 없는 경우 테이블에는 사용할 수 없는 값이 나열됩니다.

원격 스토리지 시스템 데이터를 표시하려면 Unified Manager에서 System Manager를 실행합니다.



== 왜 내 풀과 볼륨 그룹이 모두 보이지 않나요?

비동기식 미러링 쌍의 보조 볼륨을 생성하면 비동기식 미러링 쌍의 적합한 풀 및 볼륨 그룹 목록이 표시됩니다. 사용할 수 없는 풀 또는 볼륨 그룹은 해당 목록에 표시되지 않습니다.

풀 또는 볼륨 그룹은 다음과 같은 이유로 적합하지 않을 수 있습니다.

* 풀 또는 볼륨 그룹의 보안 기능이 일치하지 않습니다.
* 풀 또는 볼륨 그룹이 최적화되지 않은 상태입니다.
* 풀 또는 볼륨 그룹의 용량이 너무 작습니다.




== 비동기 미러링 - 왜 모든 볼륨이 보이지 않나요?

미러링된 쌍의 기본 볼륨을 선택하면 목록에 모든 적격 볼륨이 표시됩니다.

사용할 수 없는 볼륨은 해당 목록에 표시되지 않습니다. 볼륨은 다음과 같은 이유로 적합하지 않을 수 있습니다.

* 볼륨이 최적이 아닙니다.
* 볼륨이 이미 미러링 관계에 있습니다.
* 씬 볼륨의 경우 자동 확장이 활성화되어야 합니다.



NOTE: EF600 및 EF300 컨트롤러의 경우 비동기식 미러링 쌍의 운영 볼륨과 2차 볼륨이 동일한 프로토콜, 트레이 레벨, 세그먼트 크기, 보안 유형 및 RAID 레벨과 일치해야 합니다. 사용 가능한 볼륨 목록에 비적격한 비동기 미러링 쌍이 나타나지 않습니다.



== 비동기 미러링 - 원격 스토리지 어레이의 모든 볼륨이 표시되지 않는 이유는 무엇입니까?

원격 스토리지 어레이에서 보조 볼륨을 선택할 경우 목록에 해당 미러링된 쌍에 대해 적합한 볼륨이 모두 표시됩니다.

사용할 수 없는 볼륨은 해당 목록에 표시되지 않습니다. 볼륨은 다음과 같은 이유로 적합하지 않을 수 있습니다.

* 볼륨이 최적이 아닙니다.
* 볼륨이 이미 미러링 관계에 있습니다.
* 운영 볼륨과 2차 볼륨 사이의 씬 볼륨 속성이 일치하지 않습니다.
* DA(Data Assurance)를 사용하는 경우 운영 볼륨과 보조 볼륨의 DA 설정이 동일해야 합니다.
+
** 운영 볼륨이 DA를 사용하는 경우 보조 볼륨은 DA를 활성화해야 합니다.
** 운영 볼륨이 DA를 사용하지 않는 경우 보조 볼륨을 DA로 설정하지 않아야 합니다.






== 원격 스토리지 어레이의 IP 주소를 업데이트해야 하는 이유는 무엇입니까?

iSCSI 포트의 IP 주소가 변경되고 로컬 스토리지 배열이 원격 스토리지 배열과 통신할 수 없을 때 원격 스토리지 배열의 IP 주소를 업데이트합니다.

iSCSI 접속과 비동기 미러링 관계를 설정할 때 로컬 및 원격 스토리지 배열은 비동기 미러링 구성에서 원격 스토리지 배열의 IP 주소에 대한 레코드를 저장합니다. iSCSI 포트의 IP 주소가 변경되면 해당 포트를 사용하려는 원격 스토리지 어레이에 통신 오류가 발생합니다.

IP 주소가 변경된 스토리지 배열은 iSCSI 연결을 통해 미러링하도록 구성된 미러 정합성 보장 그룹과 연결된 각 원격 스토리지 배열에 메시지를 보냅니다. 이 메시지를 수신하는 스토리지 어레이는 원격 대상 IP 주소를 자동으로 업데이트합니다.

변경된 IP 주소를 가진 스토리지 배열이 원격 스토리지 배열에 배열 간 메시지를 보낼 수 없는 경우, 시스템은 연결 문제에 대한 경고를 보냅니다. 원격 IP 주소 업데이트 옵션을 사용하여 로컬 스토리지 어레이와의 연결을 다시 설정합니다.
