---
permalink: sm-mirroring/how-does-asynchronous-mirroring-differ-from-synchronous-mirroring-sync.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, asynchronous, mirroring, differ, synchronous, mirroring, 
summary: 비동기 미러링 기능은 동기 미러링 기능과 다릅니다. 한 가지 중요한 방법은 특정 시점의 소스 볼륨 상태를 캡처하고 마지막 이미지 캡처 이후 변경된 데이터만 복사하는 것입니다. 
---
= 비동기식 미러링은 동기식 미러링과 어떻게 다릅니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
비동기 미러링 기능은 동기 미러링 기능과 다릅니다. 한 가지 중요한 방법은 특정 시점의 소스 볼륨 상태를 캡처하고 마지막 이미지 캡처 이후 변경된 데이터만 복사하는 것입니다.

동기식 미러링을 사용하면 기본 볼륨의 상태가 특정 시점에 캡처되지 않고 기본 볼륨에서 2차 볼륨으로 이루어진 모든 변경 사항을 반영합니다. 이 유형의 미러에서는 주 볼륨에 쓸 때마다 보조 볼륨에 쓰기가 수행되므로 2차 볼륨은 매 순간마다 1차 볼륨과 동일합니다. 보조 볼륨이 운영 볼륨에서 수행된 변경 사항으로 성공적으로 업데이트될 때까지 호스트는 쓰기가 성공했다는 확인 메시지를 받지 않습니다.

비동기식 미러링을 사용하면 원격 스토리지 시스템이 로컬 스토리지 어레이와 완전히 동기화되지 않으므로 로컬 스토리지 어레이의 손실로 인해 애플리케이션을 원격 스토리지 어레이로 전환해야 하는 경우 일부 트랜잭션이 손실될 수 있습니다.

대칭 복사 피처 비교:

[cols="1a,1a"]
|===
| 비동기 미러링 | 동기 미러링 


 a| 
* 복제 방법 *



 a| 
* * 시점 *
+
미러링은 사용자 정의 일정에 따라 필요 시 또는 자동으로 수행됩니다. 일정은 분 단위로 정의할 수 있습니다. 동기화 사이의 최소 시간은 10분입니다.


 a| 
* * 연속 *
+
미러링은 모든 호스트 쓰기에서 데이터를 복사하여 지속적으로 자동 실행됩니다.





 a| 
* 예약된 용량 *



 a| 
* * 다중 *
+
각 미러링된 쌍에 대해 예약된 용량 볼륨이 필요합니다.


 a| 
* * 단일 *
+
미러링된 모든 볼륨에 단일 예약 용량 볼륨이 필요합니다.





 a| 
* 커뮤니케이션 *



 a| 
* * iSCSI 및 파이버 채널 *
+
스토리지 시스템 간의 iSCSI 및 Fibre Channel 인터페이스를 지원합니다.


 a| 
* 파이버 채널 *
+
스토리지 시스템 간 Fibre Channel 인터페이스만 지원합니다.





 a| 
* 거리 *



 a| 
* * 무제한 *
+
로컬 스토리지 어레이와 원격 스토리지 시스템 간의 거리 제한이 거의 없으며, 일반적으로 네트워크 기능과 채널 확장 기술에 의해서만 거리가 제한됩니다.


 a| 
* * 제한 *
+
일반적으로 지연 시간 및 애플리케이션 성능 요구 사항을 충족하려면 로컬 스토리지 어레이에서 약 10km(6.2마일) 이내에 있어야 합니다.



|===