---
permalink: sm-mirroring/requirements-for-using-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, requirements, asynchronous, mirroring, 
summary: 비동기식 미러링을 사용하려는 경우 다음 요구사항을 염두에 두십시오. 
---
= SANtricity 소프트웨어에서 비동기 미러링을 사용하기 위한 요구 사항
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
비동기식 미러링을 사용하려는 경우 다음 요구사항을 염두에 두십시오.



== Unified Manager를 참조하십시오

두 어레이 간에 미러링을 설정하고 구성하려면 Unified Manager 인터페이스를 사용해야 합니다. Unified Manager는 웹 서비스 프록시와 함께 호스트 시스템에 설치됩니다.

* 웹 서비스 프록시 서비스가 실행되고 있어야 합니다.
* Unified Manager는 HTTPS 연결을 통해 로컬 호스트에서 실행되고 있어야 합니다.
* Unified Manager에 스토리지 시스템에 대한 유효한 SSL 인증서가 표시되어야 합니다. 자체 서명된 인증서를 수락하거나 Unified Manager를 사용하여 인증서 [인증서 관리] 메뉴로 이동하여 자체 보안 인증서를 설치할 수 있습니다.




== 지원합니다

* 두 개의 스토리지 어레이가 있어야 합니다.
* 각 스토리지 어레이에는 2개의 컨트롤러가 필요합니다.
* Unified Manager에서 2개의 스토리지 어레이가 검색되어야 합니다.
* 기본 어레이와 보조 어레이의 각 컨트롤러에는 이더넷 관리 포트가 구성되어 있어야 하며 네트워크에 연결되어 있어야 합니다.
* 스토리지 어레이의 펌웨어 버전은 최소 7.84입니다. (각 OS 버전은 서로 다를 수 있음)
* 로컬 및 원격 스토리지 배열의 암호를 알아야 합니다.
* 미러링할 운영 볼륨과 같거나 더 큰 보조 볼륨을 생성하려면 원격 스토리지 시스템에 사용 가능한 용량이 충분해야 합니다.
* 로컬 및 원격 스토리지 어레이는 파이버 채널 패브릭 또는 iSCSI 인터페이스를 통해 연결됩니다.




== 지원되는 연결입니다

비동기 미러링은 FC 또는 iSCSI 연결을 사용하거나 둘 다 로컬 및 원격 스토리지 시스템 간의 통신에 사용할 수 있습니다. 미러 정합성 보장 그룹을 생성할 때 관리자는 둘 다 원격 스토리지 시스템에 접속된 경우 해당 그룹에 대해 FC 또는 iSCSI를 선택할 수 있습니다. 한 채널 유형에서 다른 채널 유형으로 대체 작동이 없습니다.

비동기식 미러링은 스토리지 시스템의 호스트 측 I/O 포트를 사용하여 미러링된 데이터를 운영 측에서 2차 측으로 전달합니다.

* * 파이버 채널(FC) 인터페이스를 통한 미러링 *
+
스토리지 어레이의 각 컨트롤러는 가장 높은 번호가 지정된 FC 호스트 포트를 미러링 작업에 사용합니다.

+
컨트롤러에 기본 FC 포트와 HIC(호스트 인터페이스 카드) FC 포트가 모두 있는 경우 가장 높은 번호가 지정된 포트가 HIC에 있습니다. 전용 포트에 로그온한 호스트는 로그아웃되며 호스트 로그인 요청은 허용되지 않습니다. 이 포트의 I/O 요청은 미러링 작업에 사용되는 컨트롤러에서만 허용됩니다.

+
전용 미러링 포트는 디렉토리 서비스 및 네임 서비스 인터페이스를 지원하는 FC 패브릭 환경에 연결해야 합니다. 특히 FC-AL 및 지점 간 연결 옵션은 미러 관계에 참여하는 컨트롤러 간의 연결 옵션으로 지원되지 않습니다.

* * iSCSI 인터페이스를 통한 미러링 *
+
FC와 달리 iSCSI에는 전용 포트가 필요하지 않습니다. iSCSI 환경에서 비동기 미러링을 사용하는 경우 비동기 미러링에 사용하기 위해 스토리지 어레이의 프런트 엔드 iSCSI 포트 중 하나를 전용으로 지정할 필요가 없습니다. 이러한 포트는 비동기 미러 트래픽과 호스트-스토리지 I/O 연결을 위해 모두 공유됩니다.

+
컨트롤러는 iSCSI 이니시에이터가 세션을 설정하려고 시도하는 원격 스토리지 시스템의 목록을 유지합니다. iSCSI 연결을 성공적으로 설정하는 첫 번째 포트는 해당 원격 스토리지 시스템과의 이후의 모든 통신에 사용됩니다. 통신이 실패하면 사용 가능한 모든 포트를 사용하여 새 세션이 시도됩니다.

+
iSCSI 포트는 포트별로 어레이 레벨에서 구성됩니다. 구성 메시징 및 데이터 전송을 위한 컨트롤러 간 통신은 다음 설정을 포함한 글로벌 설정을 사용합니다.

+
** VLAN: 로컬 시스템과 원격 시스템 모두 동일한 VLAN 설정을 사용하여 통신해야 합니다
** iSCSI 수신 포트입니다
** 점보 프레임
** 이더넷 우선 순위
+
[NOTE]
====
iSCSI 인터컨트롤러 통신은 관리 이더넷 포트가 아닌 호스트 연결 포트를 사용해야 합니다.

====


+
비동기식 미러링은 스토리지 시스템의 호스트 측 I/O 포트를 사용하여 미러링된 데이터를 운영 측에서 2차 측으로 전달합니다. 비동기 미러링은 대기 시간이 더 짧고 비용이 저렴한 네트워크에 사용하기 때문에 iSCSI(TCP/IP 기반) 연결이 적합합니다. iSCSI 환경에서 비동기 미러링을 사용하는 경우 비동기 미러링에 사용하기 위해 어레이의 프런트 엔드 iSCSI 포트 중 하나를 전용으로 지정할 필요가 없습니다. 이러한 포트는 비동기 미러 트래픽과 호스트-스토리지 I/O 연결을 위해 모두 공유됩니다



[NOTE]
====
E4000은 iSCSI 프로토콜을 사용하는 동안 비동기 미러링을 지원하지 않습니다.

====


== 미러링 볼륨 후보

* RAID 레벨, 캐싱 매개 변수 및 세그먼트 크기는 비동기식 미러링 쌍의 운영 볼륨과 2차 볼륨에서 서로 다를 수 있습니다.
+

NOTE: EF600 및 EF300 컨트롤러의 경우 비동기식 미러링 쌍의 운영 볼륨과 2차 볼륨이 동일한 프로토콜, 트레이 레벨, 세그먼트 크기, 보안 유형 및 RAID 레벨과 일치해야 합니다. 사용 가능한 볼륨 목록에 비적격한 비동기 미러링 쌍이 나타나지 않습니다.

* 2차 볼륨의 크기는 운영 볼륨만큼 크지 않아야 합니다.
* 볼륨은 하나의 미러 관계에만 참여할 수 있습니다.
* 볼륨 후보는 동일한 데이터 보안 기능을 공유해야 합니다.
+
** 운영 볼륨이 FIPS를 지원할 수 있는 경우 보조 볼륨은 FIPS를 지원해야 합니다.
** 기본 볼륨이 FDE를 지원할 수 있는 경우 보조 볼륨은 FDE를 지원할 수 있어야 합니다.
** 주 볼륨이 드라이브 보안을 사용하지 않는 경우 보조 볼륨이 드라이브 보안을 사용하지 않아야 합니다.


* 운영 볼륨과 2차 볼륨은 동일한 드라이브 유형을 공유해야 합니다. 운영 볼륨과 2차 볼륨 간에 NVMe 및 SAS 드라이브를 혼합할 수 없습니다.




== 예약된 용량입니다

* 컨트롤러 재설정 및 기타 임시 중단으로부터 복구하기 위해 쓰기 정보를 로깅하기 위해 미러링된 쌍의 보조 볼륨과 운영 볼륨에 예약된 용량 볼륨이 필요합니다.
* 미러링 쌍의 운영 볼륨과 2차 볼륨 모두에 추가 예약 용량이 필요하므로 미러 관계의 두 스토리지 어레이에서 사용 가능한 용량이 있는지 확인해야 합니다.
* 예약된 용량 볼륨은 연결된 미러 볼륨과 동일한 드라이브 유형을 공유해야 합니다.
+
** 예약 용량 볼륨이 NVMe 드라이브에 생성된 경우 미러 볼륨도 NVMe 드라이브에 생성해야 합니다.
** 예약된 용량 볼륨이 SAS 드라이브에 생성된 경우 미러 볼륨도 SAS 드라이브에 생성해야 합니다.






== 드라이브 보안 기능

* 보안 가능 드라이브를 사용하는 경우 기본 볼륨 및 보조 볼륨에 호환되는 보안 설정이 있어야 합니다. 이 제한은 적용되지 않으므로 직접 확인해야 합니다.
* 보안 가능 드라이브를 사용하는 경우 기본 볼륨과 보조 볼륨은 동일한 드라이브 유형을 사용해야 합니다. 이 제한은 적용되지 않으므로 직접 확인해야 합니다.
* DA(Data Assurance)를 사용하는 경우 운영 볼륨과 보조 볼륨의 DA 설정이 동일해야 합니다.

