---
permalink: sm-mirroring/requirements-for-using-synchronous-mirroring.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, requirements, synchronous, mirroring, 
summary: 동기식 미러링을 사용하려는 경우 다음 요구사항을 염두에 두십시오. 
---
= 동기 미러링 사용에 대한 요구 사항
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
동기식 미러링을 사용하려는 경우 다음 요구사항을 염두에 두십시오.



== Unified Manager를 참조하십시오

두 어레이 간에 미러링을 설정하고 구성하려면 Unified Manager 인터페이스를 사용해야 합니다. Unified Manager는 웹 서비스 프록시와 함께 호스트 시스템에 설치됩니다.

* 웹 서비스 프록시 서비스가 실행되고 있어야 합니다.
* Unified Manager는 HTTPS 연결을 통해 로컬 호스트에서 실행되고 있어야 합니다.
* Unified Manager에 스토리지 시스템에 대한 유효한 SSL 인증서가 표시되어야 합니다. 자체 서명된 인증서를 수락하거나 Unified Manager를 사용하여 인증서 [인증서 관리] 메뉴로 이동하여 자체 보안 인증서를 설치할 수 있습니다.




== 지원합니다

[NOTE]
====
동기식 미러링은 EF300 또는 EF600 스토리지 어레이에서 사용할 수 없습니다.

====
* 두 개의 스토리지 어레이가 있어야 합니다.
* 각 스토리지 어레이에는 2개의 컨트롤러가 필요합니다.
* Unified Manager에서 2개의 스토리지 어레이가 검색되어야 합니다.
* 기본 어레이와 보조 어레이의 각 컨트롤러에는 이더넷 관리 포트가 구성되어 있어야 하며 네트워크에 연결되어 있어야 합니다.
* 스토리지 어레이의 펌웨어 버전은 최소 7.84입니다. (각 OS 버전은 서로 다를 수 있음)
* 로컬 및 원격 스토리지 배열의 암호를 알아야 합니다.
* 미러링할 운영 볼륨과 같거나 더 큰 보조 볼륨을 생성하려면 원격 스토리지 시스템에 사용 가능한 용량이 충분해야 합니다.
* 로컬 및 원격 스토리지 어레이는 파이버 채널 패브릭을 통해 연결됩니다.




== 지원되는 연결입니다

동기식 미러링을 위한 통신은 FC(Fibre Channel) 호스트 포트가 있는 컨트롤러에서만 지원됩니다.

동기 미러링은 로컬 스토리지 배열과 원격 스토리지 배열의 각 컨트롤러에서 가장 높은 번호의 호스트 포트를 사용합니다. 컨트롤러 HBA(호스트 버스 어댑터) 호스트 포트 4는 일반적으로 미러 데이터 전송용으로 예약되어 있습니다.



== 미러링 볼륨 후보

* 동기식 미러링 쌍의 운영 볼륨과 2차 볼륨에서는 RAID 레벨, 캐싱 매개 변수, 세그먼트 크기가 다를 수 있습니다.
* 동기식 미러링 쌍의 운영 볼륨과 2차 볼륨은 표준 볼륨이어야 합니다. 씬 볼륨 또는 스냅샷 볼륨일 수 없습니다.
* 2차 볼륨의 크기는 운영 볼륨만큼 크지 않아야 합니다.
* 운영 볼륨에만 연결된 스냅샷이 있거나 볼륨 복제 작업의 소스 또는 타겟 볼륨일 수 있습니다.
* 볼륨은 하나의 미러 관계에만 참여할 수 있습니다.
* 지정된 스토리지 어레이에서 지원되는 볼륨 수는 제한됩니다. 스토리지 배열에 구성된 볼륨 수가 지원되는 제한보다 적었는지 확인합니다. 동기식 미러링이 활성 상태인 경우 생성된 2개의 예약된 용량 볼륨이 볼륨 제한에 대해 계산됩니다.




== 예약된 용량입니다

* 컨트롤러 재설정 및 기타 임시 중단으로부터 복구하기 위해 쓰기 정보를 로깅하기 위해 운영 볼륨과 보조 볼륨에 예약된 용량이 필요합니다.
* 예약된 용량 볼륨은 동기식 미러링이 활성화될 때 자동으로 생성됩니다. 미러링된 쌍의 운영 볼륨과 2차 볼륨 모두에 예약된 용량이 필요하므로 동기 미러 관계에 참여하는 두 스토리지 시스템에서 사용 가능한 용량이 충분한지 확인해야 합니다.




== 드라이브 보안 기능

* 보안 가능 드라이브를 사용하는 경우 기본 볼륨 및 보조 볼륨에 호환되는 보안 설정이 있어야 합니다. 이 제한은 적용되지 않으므로 직접 확인해야 합니다.
* 보안 가능 드라이브를 사용하는 경우 기본 볼륨과 보조 볼륨은 동일한 드라이브 유형을 사용해야 합니다. 이 제한은 적용되지 않으므로 직접 확인해야 합니다.
+
** 기본 볼륨에서 FDE(전체 디스크 암호화) 드라이브를 사용하는 경우 보조 볼륨에서 FDE 드라이브를 사용해야 합니다.
** 운영 볼륨이 FIPS(Federal Information Processing Standards 140-2) 검증 드라이브를 사용하는 경우 2차 볼륨은 FIPS 140-2 검증을 거친 드라이브를 사용해야 합니다.


* DA(Data Assurance)를 사용하는 경우 운영 볼륨과 보조 볼륨의 DA 설정이 동일해야 합니다.

