---
permalink: sm-mirroring/role-change-of-a-mirror-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, role, change, mirror, consistency, group, secondary, mirror, consistency, group, 
summary: 미러 정합성 보장 그룹에서 미러링된 페어 간에 역할을 변경할 수 있습니다. 이 작업은 운영 미러 정합성 보장 그룹을 보조 역할로 하향 이동하거나 보조 미러 정합성 보장 그룹을 운영 역할로 상향 이동하여 수행할 수 있습니다. 
---
= 미러 정합성 보장 그룹의 역할 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
미러 정합성 보장 그룹에서 미러링된 페어 간에 역할을 변경할 수 있습니다. 이 작업은 운영 미러 정합성 보장 그룹을 보조 역할로 하향 이동하거나 보조 미러 정합성 보장 그룹을 운영 역할로 상향 이동하여 수행할 수 있습니다.

역할 변경 작업에 대한 다음 정보를 검토합니다.

* 역할 변경은 선택한 미러 정합성 보장 그룹 내의 모든 미러링된 쌍에 영향을 줍니다.
* 미러 정합성 보장 그룹이 보조 역할로 하향 이동되면 해당 미러 정합성 보장 그룹 내의 미러링된 모든 쌍도 보조 역할로 하향 이동되고 그 반대의 경우도 마찬가지입니다.
* 운영 미러 정합성 보장 그룹이 보조 역할로 하향 이동되면 해당 그룹 내의 구성원 볼륨에 할당된 호스트는 더 이상 해당 볼륨에 대한 쓰기 액세스 권한을 갖게 되지 않습니다.
* 미러 정합성 보장 그룹이 운영 역할로 상향 이동되면 해당 그룹 내의 구성원 볼륨을 액세스하는 모든 호스트가 해당 그룹에 쓸 수 있습니다.
* 로컬 스토리지 배열이 원격 스토리지 배열과 통신할 수 없는 경우 로컬 스토리지 배열에서 역할 변경을 강제 실행할 수 있습니다.




== 역할 변경 강제 적용

로컬 스토리지와 원격 스토리지 시스템 간의 통신 문제로 인해 2차 미러 정합성 보장 그룹 내의 구성원 볼륨이 상향 이동하거나 1차 미러 정합성 보장 내의 구성원 볼륨이 하향 이동하는 것을 방지할 경우 미러 정합성 보장 그룹 간에 역할을 강제로 변경할 수 있습니다 그룹.

보조 측의 미러 정합성 보장 그룹을 운영 역할로 강제 전환할 수 있습니다. 그런 다음 복구 호스트가 해당 미러 정합성 보장 그룹 내에서 새로 상향 이동된 구성원 볼륨에 액세스할 수 있으며 비즈니스 작업을 계속할 수 있습니다.



== 강제 승급이 허용되고 허용되지 않는 경우는 언제입니까?

미러 정합성 보장 그룹의 모든 구성원 볼륨이 동기화되어 정합성 보장 복구 지점이 있는 경우에만 미러 정합성 보장 그룹의 강제 상향 이동이 허용됩니다.

다음 조건에서는 미러 정합성 보장 그룹의 강제 상향 이동이 허용되지 않습니다.

* 미러 정합성 보장 그룹의 구성원 볼륨 중 하나라도 초기 동기화 중입니다.
* 미러 정합성 보장 그룹의 구성원 볼륨에는 복구 지점의 시점 이미지가 없습니다(예: 예약된 전체 용량 오류).
* 미러 정합성 보장 그룹에 구성원 볼륨이 포함되어 있지 않습니다.
* 미러 정합성 보장 그룹이 Failed, Role-Change-Pending 또는 Role-Change-In-Progress 상태에 있거나 연결된 구성원 볼륨 또는 예약된 용량 볼륨 중 하나라도 장애가 발생한 경우




== 미러 그룹 역할 충돌

로컬 스토리지와 원격 스토리지 시스템 간의 통신 문제가 해결되면 미러 그룹 역할 충돌 조건이 발생합니다. Recovery Guru를 사용하여 이 오류를 복구합니다. 이중 역할 충돌을 해결할 때는 강제 승격이 허용되지 않습니다.

미러 그룹 역할 충돌 조건 및 후속 복구 단계를 방지하려면 스토리지 시스템 간의 접속이 작동할 때까지 기다린 후 역할을 변경해야 합니다.



== 역할 변경 진행 중 상태

미러링 구성의 두 스토리지 시스템이 분리되고 미러 정합성 보장 그룹의 운영 측이 강제로 2차 역할로 하향 이동되고 미러 정합성 보장 그룹의 2차 사이트가 1차 역할로 강제 프로모션되는 경우 그런 다음 통신이 복구되면 두 스토리지 시스템의 미러 정합성 보장 그룹이 Role-Change-In-Progress 상태로 전환됩니다.

시스템은 변경 로그를 전송하고, 다시 동기화하고, 미러 정합성 보장 그룹 상태를 정상 작동 상태로 다시 설정하고, 정기적인 동기화를 수행하여 역할 변경 프로세스를 완료합니다.
