---
permalink: sm-mirroring/role-change-of-volumes-in-a-mirrored-pair.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, role, change, between, volume, mirrored, pair, 
summary: 미러링된 쌍의 볼륨 간에 역할을 변경할 수 있습니다. 이 작업은 운영 볼륨을 보조 역할로 하향 이동하거나 보조 볼륨을 기본 역할로 상향 이동하여 수행할 수 있습니다. 
---
= 미러링된 쌍의 볼륨 간 역할 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
미러링된 쌍의 볼륨 간에 역할을 변경할 수 있습니다. 이 작업은 운영 볼륨을 보조 역할로 하향 이동하거나 보조 볼륨을 기본 역할로 상향 이동하여 수행할 수 있습니다.

[NOTE]
====
EF600 또는 EF300 스토리지 시스템에서는 동기식 미러링을 사용할 수 없습니다.

====
역할 변경 작업에 대한 다음 정보를 검토합니다.

* 운영 볼륨이 2차 역할로 하향 이동되면 해당 미러링된 쌍의 2차 볼륨이 1차 역할로 상향 이동되거나 그 반대로 상향 이동됩니다.
* 운영 볼륨이 보조 역할로 하향 이동되면 해당 볼륨에 할당된 호스트는 더 이상 해당 볼륨에 대한 쓰기 액세스 권한을 가질 수 없습니다.
* 보조 볼륨이 운영 역할로 프로모션되면 해당 볼륨에 액세스하는 모든 호스트에서 볼륨에 쓸 수 있습니다.
* 로컬 스토리지 배열이 원격 스토리지 배열과 통신할 수 없는 경우 로컬 스토리지 배열에서 역할 변경을 강제 실행할 수 있습니다.




== 역할 변경 강제 적용

로컬 스토리지 어레이와 원격 스토리지 시스템 간의 통신 문제로 인해 보조 볼륨의 상향 이동 또는 운영 볼륨의 하향 이동이 차단되는 경우 미러링된 쌍의 볼륨 간에 역할 변경을 강제 실행할 수 있습니다.

보조 측의 볼륨을 운영 역할로 강제 전환할 수 있습니다. 그런 다음 복구 호스트가 새로 상향 이동된 볼륨에 액세스할 수 있으며 비즈니스 작업을 계속할 수 있습니다.

[NOTE]
====
원격 스토리지 배열이 복구되고 통신 문제가 해결되면 동기 미러링 - 1차 볼륨 충돌 조건이 발생합니다. 복구 단계에는 볼륨 재동기화가 포함됩니다. Recovery Guru를 사용하여 이 오류를 복구합니다.

====


== 강제 승급이 허용되고 허용되지 않는 경우는 언제입니까?

다음 조건에서는 미러링된 쌍의 볼륨을 강제로 승격할 수 없습니다.

* 미러링된 쌍의 볼륨은 초기 동기화 중에 있습니다.
* 미러링된 페어는 실패, 역할 - 변경 - 보류 또는 역할 - 변경 - 진행 중 상태에 있거나 연결된 예약된 용량 볼륨 중 하나라도 실패하면




== 역할 변경 진행 중 상태

미러링 구성의 두 스토리지 시스템이 분리되고 미러링된 쌍의 기본 볼륨이 보조 역할로 강제 퇴등되고 미러링된 쌍의 보조 볼륨이 기본 역할로 강제 상향 이동된 경우, 그런 다음 통신이 복구되면 두 스토리지 시스템의 볼륨이 Role-Change-In-Progress 상태가 됩니다.

시스템은 변경 로그를 전송하고, 다시 동기화하고, 미러링된 페어 상태를 정상 작동 상태로 다시 설정하고, 동기화를 계속 수행하여 역할 변경 프로세스를 완료합니다.
