---
permalink: sm-mirroring/suspend-or-resume-mirror-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, suspend, resume, synchronization, mirror, consistency, group, 
summary: 미러 정합성 보장 그룹 내의 모든 미러링된 쌍에서 데이터 동기화를 일시 중지하거나 다시 시작할 수 있으므로 개별 미러링된 쌍에서 동기화를 일시 중지하거나 다시 시작하는 것보다 효율적입니다. 
---
= 미러 정합성 보장 그룹에 대한 동기화를 일시 중지하거나 다시 시작합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
미러 정합성 보장 그룹 내의 모든 미러링된 쌍에서 데이터 동기화를 일시 중지하거나 다시 시작할 수 있으므로 개별 미러링된 쌍에서 동기화를 일시 중지하거나 다시 시작하는 것보다 효율적입니다.

.이 작업에 대해
그룹에서 동기화를 일시 중단하고 다시 시작하면 호스트 응용 프로그램에 대한 성능 영향을 줄일 수 있습니다. 이 문제는 로컬 스토리지 배열의 변경된 데이터가 원격 스토리지 배열에 복사되는 동안 발생할 수 있습니다.

동기화 작업을 재개하기 위해 Resume 옵션을 사용할 때까지 미러 정합성 보장 그룹 및 미러 페어의 상태가 일시 중지된 상태로 유지됩니다.

.단계
. 메뉴: 스토리지 [비동기 미러링]을 선택합니다.
. 미러 정합성 보장 그룹 * 탭을 선택합니다.
+
미러링된 정합성 보장 그룹 테이블이 나타나고 스토리지 시스템과 연결된 모든 미러 정합성 보장 그룹이 표시됩니다.

. 일시 중단 또는 재개하려는 미러 정합성 보장 그룹을 선택한 다음 More[Suspend] 또는 menu:More[Resume] 메뉴를 선택합니다.
+
확인 메시지가 표시됩니다.

. 예 * 를 선택하여 확인합니다.


.결과
System Manager는 다음 작업을 수행합니다.

* 미러 관계를 제거하지 않고 미러 정합성 보장 그룹의 미러링된 모든 쌍 간에 데이터 전송을 일시 중단하거나 재개합니다.
* 미러 그룹이 일시 중지된 동안 미러 정합성 보장 그룹의 운영 측에 기록된 모든 데이터를 기록하고 미러 그룹이 재개될 때 미러 정합성 보장 그룹의 보조 측에 데이터를 자동으로 씁니다. 전체 동기화가 필요하지 않습니다.
* suspended_mirror 정합성 보장 그룹의 경우 미러 정합성 보장 그룹 테이블에 * user-suspended * 가 표시됩니다.
* refused_mirror 정합성 보장 그룹의 경우 미러 정합성 보장 그룹이 일시 중지된 동안 운영 볼륨에 기록된 데이터가 보조 볼륨에 즉시 기록됩니다. 자동 동기화 간격이 설정된 경우 주기적 동기화가 다시 시작됩니다.

