---
permalink: sm-mirroring/synchronous-mirroring-status.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, synchronous, mirroring, status, 
summary: 동기식 미러링 쌍의 상태는 운영 볼륨과 보조 볼륨의 데이터가 동기화되었는지 여부를 나타냅니다. 미러 상태는 미러링된 쌍에 있는 볼륨의 구성 요소 상태와 무관합니다. 
---
= 동기 미러링 상태
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
동기식 미러링 쌍의 상태는 운영 볼륨과 2차 볼륨의 데이터가 동기화되었는지 여부를 나타냅니다. 미러 상태는 미러링된 쌍에 있는 볼륨의 구성 요소 상태와 무관합니다.

[NOTE]
====
EF600 또는 EF300 스토리지 시스템에서는 이 기능을 사용할 수 없습니다.

====
동기식 미러링 쌍은 다음 상태 중 하나일 수 있습니다.

* * 최적 *
+
미러링된 쌍의 볼륨이 동기화되었음을 나타냅니다. 즉, 스토리지 어레이 간의 패브릭 연결이 작동 중이고 각 볼륨이 원하는 작업 상태에 있음을 나타냅니다.

* * 동기화 중 *
+
미러링된 쌍 간의 데이터 동기화 진행률을 보여 줍니다. 이 상태는 초기 동기화 중에도 표시됩니다.

+
통신 링크가 중단된 후에는 링크가 중단된 동안 운영 볼륨에서 변경된 데이터 블록만 보조 볼륨으로 복사됩니다.

* * 동기화되지 않음 *
+
운영 볼륨의 스토리지 배열이 원격 배열에 들어오는 데이터를 쓸 수 없음을 나타냅니다. 로컬 호스트는 계속 운영 볼륨에 쓸 수 있지만 원격 쓰기는 적용되지 않습니다. 운영 볼륨의 스토리지 배열이 들어오는 데이터를 보조 볼륨에 쓰는 것을 방지할 수 있는 조건이 다를 수 있습니다. 예를 들면 다음과 같습니다.

+
** 보조 볼륨에 액세스할 수 없습니다.
** 원격 스토리지 배열에 액세스할 수 없습니다.
** 스토리지 시스템 간의 Fabric 접속에 액세스할 수 없습니다.
** 2차 볼륨은 새로운 WWID(World Wide Identifier)로 업데이트할 수 없습니다.


* * 일시 중단됨 *
+
사용자가 동기 미러링 작업을 일시 중단했음을 나타냅니다. 미러링된 쌍이 일시 중지되면 보조 볼륨에 연결을 시도하지 않습니다. 운영 볼륨에 대한 모든 쓰기는 미러 예약 용량 볼륨에 영구적으로 기록됩니다.

* * 실패 *
+
운영 볼륨, 보조 볼륨 또는 미러 예약 용량에 장애가 발생하여 동기식 미러링 작업이 정상적으로 작동하지 않음을 나타냅니다.


