---
permalink: sm-mirroring/test-communication-for-mirror-consistency-groups.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, test, communication, mirror, consistency, groups, 
summary: 통신 링크를 테스트하여 로컬 스토리지 시스템과 미러 정합성 보장 그룹에 연결된 원격 스토리지 시스템 간의 통신 문제를 진단할 수 있습니다. 
---
= 미러 정합성 보장 그룹에 대한 통신을 테스트합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
통신 링크를 테스트하여 로컬 스토리지 시스템과 미러 정합성 보장 그룹에 연결된 원격 스토리지 시스템 간의 통신 문제를 진단할 수 있습니다.

.시작하기 전에
테스트할 미러 정합성 보장 그룹이 로컬 및 원격 스토리지 시스템에 있어야 합니다.

.이 작업에 대해
다음 네 가지 테스트를 실행할 수 있습니다.

* * 연결 * -- 두 컨트롤러가 통신 경로를 가지고 있는지 확인합니다. 연결 테스트에서는 스토리지 시스템 간에 스토리지 간 메시지를 보낸 다음 원격 스토리지 시스템에 있는 해당 미러 정합성 보장 그룹이 있는지 확인합니다. 또한 원격 스토리지 시스템에 있는 미러 정합성 보장 그룹의 구성원 볼륨이 로컬 스토리지 시스템에 있는 미러 정합성 보장 그룹의 구성원 볼륨과 일치하는지 확인합니다.
* * 지연 시간 * -- 미러 정합성 보장 그룹에 연결된 원격 스토리지 시스템의 각 미러링된 볼륨에 SCSI 테스트 유닛 명령을 전송하여 최소, 평균 및 최대 지연 시간을 테스트합니다.
* * 대역폭 * -- 검사를 수행하는 어레이에 있는 포트의 협상된 링크 속도뿐만 아니라 최소, 평균 및 최대 대역폭을 테스트하기 위해 원격 스토리지 배열에 두 개의 배열 간 메시지를 보냅니다.
* * 포트 연결 * -- 로컬 스토리지 배열의 미러링에 사용되는 포트와 원격 스토리지 배열의 미러링된 데이터를 수신하는 포트를 표시합니다.


.단계
. 메뉴: 스토리지 [비동기 미러링]을 선택합니다.
. 미러 정합성 보장 그룹 * 탭을 선택한 다음 테스트할 미러 정합성 보장 그룹을 선택합니다.
. 통신 테스트 * 를 선택합니다.
+
통신 테스트 대화 상자가 나타납니다.

. 선택한 미러 정합성 보장 그룹에 연결된 로컬 및 원격 스토리지 시스템 간에 수행할 통신 테스트를 하나 이상 선택한 다음 * 테스트 * 를 클릭합니다.
. 결과 창에 표시된 정보를 검토합니다.
+
[cols="35h,~"]
|===
| 통신 테스트 상태 | 설명 


 a| 
정상, 오류 없음
 a| 
미러 정합성 보장 그룹이 올바르게 통신하고 있습니다.



 a| 
통과 상태(정상은 아님)
 a| 
가능한 네트워크 또는 연결 문제를 확인하고 테스트를 다시 시도하십시오.



 a| 
실패 상태입니다
 a| 
실패 이유가 표시됩니다. 문제를 해결하려면 Recovery Guru를 참조하십시오.



 a| 
포트 연결 오류입니다
 a| 
로컬 스토리지 배열이 연결되어 있지 않거나 원격 스토리지 배열에 연결할 수 없기 때문일 수 있습니다. 문제를 해결하려면 Recovery Guru를 참조하십시오.

|===


.결과
통신 테스트가 완료되면 이 대화 상자에 정상 상태, 통과 상태 또는 실패 상태가 표시됩니다.

통신 테스트가 실패 상태를 반환하는 경우 미러 정합성 보장 그룹 간의 통신이 복구될 때까지 이 대화 상자를 닫은 후에도 테스트가 계속 실행됩니다.
