---
permalink: sm-mirroring/workflow-for-mirroring-a-volume-asynchronously.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, workflow, mirroring, asynchronously, 
summary: 다음 워크플로우를 사용하여 비동기식 미러링을 구성합니다. 
---
= 볼륨을 비동기적으로 미러링하는 워크플로
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 워크플로우를 사용하여 비동기식 미러링을 구성합니다.

. Unified Manager에서 초기 구성을 수행합니다.
+
.. 로컬 스토리지 배열을 데이터 전송 소스로 선택합니다.
.. 로컬 스토리지의 운영 볼륨과 원격 스토리지의 보조 볼륨을 위한 컨테이너인 기존 미러 정합성 보장 그룹을 생성하거나 선택합니다. 운영 볼륨과 2차 볼륨을 "미러링된 쌍"이라고 합니다. 미러 정합성 보장 그룹을 처음 생성하는 경우 수동 동기화 또는 예약된 동기화를 수행할지 여부를 지정합니다.
.. 로컬 스토리지 어레이에서 운영 볼륨을 선택한 다음 예약된 용량을 확인합니다. 예약된 용량은 복제 작업에 사용할 물리적 할당 용량입니다.
.. 원격 스토리지 시스템을 전송 대상, 보조 볼륨으로 선택한 다음 예약된 용량을 결정합니다.
.. 운영 볼륨에서 보조 볼륨으로 초기 데이터 전송을 시작합니다. 볼륨 크기에 따라 이 초기 전송에 몇 시간이 걸릴 수 있습니다.


. 초기 동기화 진행률을 확인합니다.
+
.. Unified Manager에서 로컬 어레이에 대한 System Manager를 시작합니다.
.. System Manager에서 미러링 작업의 상태를 봅니다. 미러링이 완료되면 미러링된 쌍의 상태가 "Optimal(최적)"입니다.


. * 선택 사항: * System Manager에서 후속 데이터 전송을 다시 예약하거나 수동으로 수행할 수 있습니다. 운영 볼륨에서 2차 볼륨으로 새 블록과 변경된 블록만 전송합니다.
+
[NOTE]
====
비동기식 복제는 정기적으로 수행되므로 시스템에서 변경된 블록을 통합하고 네트워크 대역폭을 보존할 수 있습니다. 쓰기 처리량과 쓰기 지연 시간에 미치는 영향은 미미합니다.

====

