---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, admin password 
summary: 무단 액세스로부터 보호하려면 관리자 암호를 사용하여 스토리지 배열을 구성해야 합니다. 
---
= SANtricity System Manager에서 암호 보호 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
무단 액세스로부터 스토리지 배열을 보호하려면 암호를 사용하여 스토리지 배열을 구성해야 합니다.



== 암호를 설정하고 변경합니다

System Manager를 처음 시작하면 관리자 암호를 설정하라는 메시지가 표시됩니다. admin 암호를 가진 사용자는 개체 또는 설정을 추가, 변경 또는 제거하는 등의 스토리지 배열 구성을 변경할 수 있습니다. 초기 시작 중에 관리자 암호를 설정하려면 을 참조하십시오 link:../san-getstarted/access-sam.html["System Manager에 액세스합니다"].

보안을 위해 스토리지 배열이 "잠금" 상태가 되기 5회만 암호를 입력할 수 있습니다. 이 상태에서는 스토리지 배열이 후속 암호 시도를 거부합니다. 암호를 다시 입력하기 전에 스토리지 배열이 "정상" 상태로 재설정되도록 10분 정도 기다려야 합니다.

스토리지 배열에는 관리자 암호 외에 하나 이상의 역할이 매핑된 사전 정의된 사용자 프로파일이 포함됩니다. 자세한 내용은 을 참조하십시오 link:../sm-settings/permissions-for-mapped-roles.html["매핑된 역할에 대한 권한"]. 사용자 프로파일과 매핑은 변경할 수 없습니다. 암호만 수정할 수 있습니다. admin 암호 또는 기타 사용자 암호를 변경하려면 을 참조하십시오 link:../sm-settings/change-passwords.html["암호를 변경합니다"].



== 세션 시간 초과 후 암호를 다시 입력합니다

단일 관리 세션 중에 암호를 입력하라는 메시지가 한 번만 표시됩니다. 그러나 30분 동안 사용하지 않으면 세션 시간이 초과되며, 이 경우 암호를 다시 입력해야 합니다. 세션이 진행되는 동안 다른 관리 클라이언트에서 동일한 스토리지 배열을 관리하는 다른 사용자가 암호를 변경하는 경우 다음에 구성 작업 또는 보기 작업을 시도할 때 암호를 입력하라는 메시지가 표시됩니다.

세션 시간 초과를 조정하거나 세션 시간 초과를 모두 비활성화할 수 있습니다. 을 참조하십시오 link:../sm-settings/manage-session-timeouts-sam.html["세션 시간 제한을 관리합니다"].



== 드라이브 또는 암호 보호를 제거합니다

암호로 보호된 드라이브를 제거하거나 암호 보호를 사용하지 않으려면 다음 사항에 유의하십시오.

* * 암호 보호 기능이 있는 드라이브를 제거하면 * -- 암호는 스토리지 배열의 각 드라이브의 예약된 영역에 저장됩니다. 스토리지 배열에서 모든 드라이브를 제거하면 해당 암호가 더 이상 작동하지 않습니다. 이 상태를 해결하려면 스토리지 배열에 원래 드라이브 중 하나를 다시 설치하십시오.
* * 암호 보호 * -- 명령을 더 이상 암호로 보호하지 않으려면 현재 관리자 암호를 입력하고 새 암호 텍스트 상자를 비워 둡니다.


[CAUTION]
====
스토리지 어레이에서 구성 명령을 실행하면 데이터 손실을 비롯한 심각한 손상이 발생할 수 있습니다. 따라서 스토리지 배열에 대한 관리자 암호를 항상 설정해야 합니다. 15자 이상의 영숫자로 이루어진 긴 관리자 암호를 사용하여 보안을 강화합니다.

====