---
permalink: sm-interface/faq-management-interface.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager에 대한 관리 인터페이스 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 지원되는 브라우저는 무엇입니까?

SANtricity System Manager에서는 이러한 브라우저 버전을 지원합니다.

[cols="1a,1a"]
|===
| 브라우저 | 최소 버전 


 a| 
Google Chrome
 a| 
89



 a| 
Mozilla Firefox
 a| 
80



 a| 
사파리
 a| 
14



 a| 
Microsoft Edge를 참조하십시오
 a| 
90

|===


== 키보드 바로 가기는 무엇입니까?

키보드만 사용하여 SANtricity System Manager 주변을 탐색할 수 있습니다.



=== 전체 탐색

[cols="1a,1a"]
|===
| 조치 | 바로 가기 키 


 a| 
다음 항목으로 이동합니다.
 a| 
탭을 클릭합니다



 a| 
이전 항목으로 이동합니다.
 a| 
Shift+Tab



 a| 
항목을 선택합니다.
 a| 
를 입력합니다



 a| 
드롭다운 목록 -- 다음 또는 이전 항목으로 이동합니다.
 a| 
아래쪽 화살표 키 또는 위쪽 화살표 키를 누릅니다



 a| 
확인란 -- 항목을 선택합니다.
 a| 
스페이스바



 a| 
라디오 버튼 -- 항목 간 전환
 a| 
아래쪽 화살표 키 또는 위쪽 화살표 키를 누릅니다



 a| 
확장 가능한 텍스트 -- 항목을 확장하거나 축소합니다.
 a| 
를 입력합니다

|===


=== 테이블 탐색

[cols="1a,1a"]
|===
| 조치 | 바로 가기 키 


 a| 
행을 선택합니다.
 a| 
Tab 키를 눌러 행을 선택한 다음 Enter 키를 누릅니다



 a| 
위 또는 아래로 스크롤합니다.
 a| 
아래쪽 화살표/위쪽 화살표 또는 Page Down/Page Up



 a| 
열의 정렬 순서를 변경합니다.
 a| 
Tab 키를 눌러 열 머리글을 선택한 다음 Enter 키를 누릅니다

|===


=== 일정 탐색

[cols="1a,1a"]
|===
| 조치 | 바로 가기 키 


 a| 
이전 달로 이동합니다.
 a| 
페이지 위로



 a| 
다음 달로 이동한다.
 a| 
페이지를 아래로 내립니다



 a| 
이전 연도에 이전하십시오.
 a| 
컨트롤 + 페이지 위로



 a| 
내년으로 넘어가.
 a| 
컨트롤 + 페이지 아래로



 a| 
닫힌 경우 날짜 선택을 엽니다.
 a| 
Ctrl+Home을 누릅니다



 a| 
현재 달로 이동합니다.
 a| 
Control/Command + Home



 a| 
이전 날로 이동합니다.
 a| 
Control/Command+왼쪽



 a| 
다음 날로 이동한다.
 a| 
Control/Command + 오른쪽



 a| 
이전 주로 이동합니다.
 a| 
Control/Command+Up



 a| 
다음 주로 이동한다.
 a| 
Control/Command+Down



 a| 
포커스된 날짜를 선택합니다.
 a| 
를 입력합니다



 a| 
날짜 선택을 닫고 날짜를 지웁니다.
 a| 
제어/명령+종료



 a| 
선택 없이 날짜 선택을 닫습니다.
 a| 
Esc를 누릅니다

|===


== 개별 볼륨의 성능 통계가 총합과 어떤 관련이 있습니까?

풀 및 볼륨 그룹에 대한 통계는 예약된 용량 볼륨을 비롯한 모든 볼륨을 집계하여 계산합니다.

예약된 용량은 스토리지 시스템에서 씬 볼륨, 스냅샷 및 비동기 미러링을 지원하기 위해 내부적으로 사용되며 I/O 호스트에는 표시되지 않습니다. 따라서 풀, 컨트롤러 및 스토리지 어레이 통계가 볼 수 있는 볼륨의 합으로 합산되지 않을 수 있습니다.

그러나 애플리케이션 및 워크로드 통계의 경우 표시되는 볼륨만 집계됩니다.



== 데이터가 그래프 및 테이블에 0으로 표시되는 이유는 무엇입니까?

그래프 및 테이블의 데이터 지점에 대해 0이 표시되면 해당 시점의 오브젝트에 대한 I/O 활동이 없다는 의미입니다. 이 상황은 호스트가 해당 객체에 대한 입출력을 시작하지 않았거나 객체 자체에 문제가 있을 수 있기 때문에 발생할 수 있습니다.

객체에 대한 기록 데이터를 계속 볼 수 있습니다. 오브젝트에 대한 I/O 활동이 시작되면 그래프 및 표에 0이 아닌 데이터가 표시됩니다.

다음 표에서는 주어진 개체에 대해 데이터 요소 값이 0인 가장 일반적인 이유를 보여 줍니다.

[cols="25h,~"]
|===
| 스토리지 레벨 객체 유형입니다 | 이유 데이터는 0으로 표시됩니다 


 a| 
볼륨
 a| 
* 볼륨에 호스트 할당이 없습니다.




 a| 
볼륨 그룹
 a| 
* 볼륨 그룹을 가져오는 중입니다.
* 볼륨 그룹에 호스트에 할당된 볼륨이 포함되어 있지 않습니다. * _ 및 _ * 볼륨 그룹에 예약된 용량이 없습니다.




 a| 
드라이브
 a| 
* 드라이브에 오류가 발생했습니다.
* 드라이브가 제거되었습니다.
* 드라이브가 알 수 없는 상태입니다.




 a| 
컨트롤러
 a| 
* 컨트롤러가 오프라인 상태입니다.
* 컨트롤러에 장애가 발생했습니다.
* 컨트롤러가 제거되었습니다.
* 컨트롤러가 알 수 없는 상태입니다.




 a| 
스토리지 시스템
 a| 
* 스토리지 배열에 볼륨이 포함되어 있지 않습니다.


|===


== 지연 시간 그래프는 무엇을 표시합니까?

지연 시간 그래프는 볼륨, 볼륨 그룹, 풀에 대한 지연 시간 통계(밀리초(ms))를 워크로드에 적합합니다. 이 그래프는 Logical View, Physical View 및 Applications & 워크로드 보기 탭에 나타납니다.

지연 시간은 데이터가 읽기 또는 쓰일 때 발생하는 지연을 나타냅니다. 그래프의 한 지점 위로 커서를 가져가면 해당 시점에 대한 다음 값(밀리초(ms))이 표시됩니다.

* 읽기 시간.
* 쓰기 시간.
* 평균 I/O 크기




== IOPS 그래프에 표시되는 것은 무엇입니까?

IOPS 그래프에는 초당 입출력 작업에 대한 통계가 표시됩니다. 홈 페이지에서 이 그래프는 스토리지 배열에 대한 통계를 표시합니다. Logical View, Physical View, Applications & 워크로드 성능 타일의 보기 탭에서 이 그래프는 스토리지, 볼륨, 볼륨 그룹, 풀, 애플리케이션에 대한 통계를 표시합니다. 보장합니다.

IOPS는 초당 _INPUT/OUTPUT(I/O) 작업의 약어입니다. 그래프의 한 지점 위로 커서를 가져가면 해당 시점에 대한 다음 값을 볼 수 있습니다.

* 읽기 작업 수입니다.
* 쓰기 작업 수입니다.
* 총 읽기 및 쓰기 작업이 결합되었습니다.




== MiB/s 그래프는 무엇을 표시합니까?

MiB/s 그래프는 전송 속도 통계를 초당 메비바이트 단위로 표시합니다. 홈 페이지에서 이 그래프는 스토리지 배열에 대한 통계를 표시합니다. Logical View, Physical View, Applications & 워크로드 성능 타일의 보기 탭에서 이 그래프는 스토리지, 볼륨, 볼륨 그룹, 풀, 애플리케이션에 대한 통계를 표시합니다. 보장합니다.

MIB/s는 초당 _mebytes_ 또는 1,048,576바이트의 약어입니다. 그래프의 한 지점 위로 커서를 가져가면 해당 시점에 대한 다음 값을 볼 수 있습니다.

* 읽은 데이터의 양
* 기록된 데이터의 양
* 읽고 쓴 데이터의 총 양입니다.




== CPU 그래프는 무엇을 표시합니까?

CPU 그래프는 각 컨트롤러(컨트롤러 A 및 컨트롤러 B)에 대한 처리 용량 통계를 표시합니다. CPU는 _ 중앙 처리 장치 _ 의 약어입니다. 홈 페이지에서 이 그래프는 스토리지 배열에 대한 통계를 표시합니다. 성능 타일의 Physical View 탭에서 이 그래프는 스토리지 배열 및 드라이브에 대한 통계를 표시합니다.

CPU 그래프는 스토리지의 작업에 사용되는 CPU 처리 용량의 백분율을 보여 줍니다. 외부 I/O가 발생하지 않는 경우에도 스토리지 운영 체제가 백그라운드 작업 및 모니터링을 수행할 수 있으므로 CPU 활용률이 0이 아닐 수 있습니다. 그래프의 한 지점 위로 커서를 가져가면 해당 시점에 사용되는 처리 기능의 백분율을 볼 수 있습니다.



== 여유 공간 그래프에 표시되는 것은 무엇입니까?

여유 공간 그래프는 스토리지 어레이 컨트롤러의 남은 성능 기능과 관련이 있습니다. 이 그래프는 홈 페이지와 성능 타일의 물리적 보기 탭에 표시됩니다.

여유 공간 그래프에는 스토리지 시스템에 있는 물리적 개체의 남은 성능 용량이 나와 있습니다. 그래프의 한 지점 위로 커서를 가져가면 컨트롤러 A 및 컨트롤러 B에 대해 남아 있는 IOPS 및 MiB/s 용량의 백분율이 표시됩니다



== 디스플레이 기본 설정에 대한 자세한 정보는 어디에서 찾을 수 있습니까?

사용 가능한 표시 옵션에 대한 정보를 찾으려면

* 용량 값을 표시하는 기본 단위에 대한 자세한 내용은 을 참조하십시오 link:set-default-units-for-capacity-values.html["용량 값의 기본 단위를 설정합니다"].
* 성능 그래프 표시를 위한 기본 기간에 대한 자세한 내용은 을 참조하십시오 link:set-default-time-frame-for-performance-graphs.html["성능 그래프의 기본 기간을 설정합니다"].

