---
permalink: sm-interface/faq-storage-system-setup.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager를 위한 스토리지 시스템 설정 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 모든 하드웨어 구성 요소가 보이지 않으면 어떻게 되나요?

하드웨어 확인 대화 상자에 모든 하드웨어 구성 요소가 표시되지 않으면 드라이브 쉘프가 올바로 연결되지 않았거나 스토리지 어레이에 호환되지 않는 쉘프가 설치되어 있는 것일 수 있습니다.

모든 드라이브 쉘프가 올바로 연결되었는지 확인합니다. 어떤 드라이브 쉘프가 호환되는지 확실하지 않은 경우 기술 지원 팀에 문의하십시오.



== 모든 호스트를 볼 수 없다면 어떻게 해야 하나요?

연결된 호스트가 표시되지 않으면 자동 감지에 실패했거나, 호스트가 잘못 연결되었거나, 현재 접속된 호스트가 없는 것입니다.

설치를 완료한 후 나중에 호스트를 구성할 수 있습니다. 다음과 같이 호스트를 수동으로 생성할 수 있습니다.

* 스토리지 [호스트] 메뉴로 이동하여 호스트를 수동으로 생성하고 적절한 호스트 포트 식별자를 연결할 수 있습니다. 수동으로 생성된 호스트는 * 초기 설정 * 마법사에도 표시됩니다.
* 호스트와 호스트는 호스트 포트 유형(예: iSCSI 또는 NVMe over RoCE)에 맞게 구성해야 하며 자동 탐지 기능이 작동되기 전에 설정된 스토리지에 대한 세션도 구성해야 합니다.




== 애플리케이션을 식별하면 스토리지 어레이를 관리하는 데 어떤 도움이 됩니까?

애플리케이션이 있는 경우 SANtricity System Manager에서는 애플리케이션 유형에 따라 스토리지를 최적화하는 볼륨 구성을 자동으로 권장합니다.

애플리케이션별로 볼륨을 최적화하면 데이터 스토리지 운영 효율성을 높일 수 있습니다. 볼륨 구성에는 I/O 유형, 세그먼트 크기, 컨트롤러 소유권, 읽기 및 쓰기 캐시 같은 특성이 포함됩니다. 또한 애플리케이션 및 워크로드별로 성능 데이터를 보고 지연 시간, IOPS, MiB/s와 관련 워크로드를 평가할 수 있습니다.



== 워크로드란?

네트워크의 일부 애플리케이션(예: SQL Server 또는 Exchange)에서 해당 애플리케이션에 맞게 스토리지를 최적화하는 워크로드를 정의할 수 있습니다.

워크로드는 애플리케이션을 지원하는 스토리지 객체입니다. 애플리케이션별로 하나 이상의 워크로드 또는 인스턴스를 정의할 수 있습니다. 일부 애플리케이션의 경우 시스템에서 기본 볼륨 특성이 비슷한 볼륨을 포함하도록 워크로드를 구성합니다. 이러한 볼륨 특성은 워크로드가 지원하는 애플리케이션 유형에 따라 최적화됩니다. 예를 들어, Microsoft SQL Server 애플리케이션을 지원하는 워크로드를 생성한 다음 해당 워크로드에 대한 볼륨을 생성하는 경우 기본 볼륨 특성은 Microsoft SQL Server를 지원하도록 최적화되어 있습니다.

볼륨을 생성하는 동안 시스템에서 워크로드 사용에 대한 질문에 답하라는 메시지를 표시합니다. 예를 들어 Microsoft Exchange용 볼륨을 만드는 경우 필요한 메일박스 수, 평균 메일박스 용량 요구 사항, 원하는 데이터베이스 복제본 수를 묻는 메시지가 표시됩니다. 시스템에서는 이 정보를 사용하여 최적의 볼륨 구성을 생성합니다. 이 구성은 필요에 따라 편집할 수 있습니다.



== AutoSupport에 대한 전달 방법을 구성하려면 어떻게 합니까?

AutoSupport 제공 방법에 대한 구성 작업에 액세스하려면 지원 [지원 센터] 메뉴로 이동한 다음 * AutoSupport * 탭을 클릭합니다.

지원되는 프로토콜은 HTTPS 및 SMTP입니다.



== 권장 풀 구성을 수락해야 하는지 어떻게 알 수 있습니까?

권장 풀 구성을 수락할지 여부는 몇 가지 요소에 따라 달라집니다.

다음 질문에 대답하여 요구 사항에 가장 적합한 스토리지 유형을 결정합니다.

* 용량이 더 작은 풀을 여러 개 선호하십니까?
* 풀보다 RAID 볼륨 그룹을 선호합니까?
* 권장 구성이 아닌 드라이브를 수동으로 프로비저닝하고 싶으십니까?


이러한 질문 중 하나라도 "예"로 답한 경우 권장 풀 구성을 거부하십시오.



== SANtricity 시스템 관리자가 호스트를 감지하지 못했습니다. 어떻게 해야 합니까?

연결된 호스트가 표시되지 않으면 자동 감지에 실패했거나, 호스트가 잘못 연결되었거나, 현재 접속된 호스트가 없는 것입니다.

설치를 완료한 후 나중에 호스트를 구성할 수 있습니다. 다음과 같이 호스트를 수동으로 생성할 수 있습니다.

* 스토리지 [호스트] 메뉴로 이동하여 호스트를 수동으로 생성하고 적절한 호스트 포트 식별자를 연결할 수 있습니다. 수동으로 생성된 호스트는 * 초기 설정 * 마법사에도 표시됩니다.
* 호스트와 호스트는 호스트 포트 유형(예: iSCSI 또는 NVMe over RoCE)에 맞게 구성해야 하며 자동 탐지 기능이 작동되기 전에 설정된 스토리지에 대한 세션도 구성해야 합니다.

