---
permalink: sm-interface/overview-interface-sam.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: 기본 인터페이스를 탐색하여 System Manager 기능 및 작업에 액세스합니다. 
---
= SANtricity System Manager 인터페이스에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity System Manager는 스토리지 어레이를 단일 뷰에서 관리할 수 있는 웹 기반 인터페이스입니다.



== 홈 페이지

홈 페이지는 스토리지 시스템의 일일 관리를 위한 대시보드 보기를 제공합니다. System Manager에 로그인하면 홈 페이지가 첫 번째 화면으로 표시됩니다.

대시보드 보기에는 스토리지 어레이의 상태 및 건전성에 대한 주요 정보가 포함된 세 가지 요약 영역이 있습니다. 요약 영역에서 더 자세한 정보를 확인할 수 있습니다.

[cols="25h,~"]
|===
| 영역 | 설명 


 a| 
성능
 a| 
Performance(성능) 영역에서 시간에 따른 리소스 사용량을 비교하고 대조할 수 있습니다. 응답 시간(IOPS), 전송 속도(MiB/s) 및 사용 중인 처리 용량(CPU)에 대한 스토리지 시스템의 성능 메트릭을 볼 수 있습니다.



 a| 
용량
 a| 
용량 영역에는 스토리지 배열에서 할당된 용량, 사용 가능한 스토리지 용량 및 할당되지 않은 스토리지 용량에 대한 차트 보기가 표시됩니다.



 a| 
스토리지 계층 구조입니다
 a| 
스토리지 계층 영역은 스토리지 배열에 의해 관리되는 다양한 하드웨어 구성 요소 및 스토리지 개체에 대한 체계적인 보기를 제공합니다. 드롭다운 화살표를 클릭하여 해당 하드웨어 구성 요소 또는 스토리지 개체에 대한 특정 작업을 수행합니다.

|===


== 알림 영역

알림 영역은 창 상단 모서리에 있는 종 모양 아이콘을 통해 접근할 수 있습니다. 알림 영역에는 스토리지 어레이 및 구성 요소의 상태를 나타내는 문제 알림이 표시됩니다. 또한 이 섹션에는 스토리지 환경의 다른 영역에 영향을 미치기 전에 문제를 해결하는 데 도움이 되는 자동화된 알림이 표시됩니다.



== 인터페이스 설정

기본 인터페이스에서 디스플레이 기본 설정 및 기타 설정을 변경할 수 있습니다.



== 사용자 로그인 및 암호

현재 시스템에 로그인한 사용자가 사용자 설정에 표시됩니다.

사용자 및 암호에 대한 자세한 내용은 다음을 참조하십시오.

* link:administrator-password-protection.html["관리자 암호 보호를 설정합니다"]
* link:../sm-settings/change-passwords.html["암호를 변경합니다"]

