---
permalink: sm-interface/setup-wizard-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, setup wizard 
summary: 설치 마법사를 사용하여 하드웨어, 호스트, 애플리케이션, 워크로드 등 스토리지 시스템을 구성합니다. 풀, 알림 및 AutoSupport 
---
= 설정 마법사 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
설치 마법사를 사용하여 하드웨어, 호스트, 애플리케이션, 워크로드 등 스토리지 시스템을 구성합니다. 풀, 알림 및 AutoSupport



== 최초 설정

System Manager를 처음 열면 설정 마법사가 시작됩니다. 설치 마법사는 스토리지 배열 이름 지정, 호스트 구성, 애플리케이션 선택 및 스토리지 풀 생성 등의 기본 구성 작업을 수행하라는 메시지를 표시합니다.

마법사를 취소하면 수동으로 다시 시작할 수 없습니다. System Manager를 열거나 브라우저를 새로 고치면 마법사가 자동으로 다시 시작되고, 다음 중 _ 개 이상의 조건이 충족됩니다.

* 풀 및 볼륨 그룹이 감지되지 않습니다.
* 감지된 워크로드가 없습니다.
* 알림이 구성되지 않았습니다.




== 용어

설치 마법사는 다음 용어를 사용합니다.

[cols="25h,~"]
|===
| 기간 | 설명 


 a| 
응용 프로그램
 a| 
애플리케이션은 Microsoft SQL Server 또는 Microsoft Exchange와 같은 소프트웨어 프로그램입니다.



 a| 
경고
 a| 
알림은 스토리지 시스템에서 발생하는 중요한 이벤트를 관리자에게 알립니다. 알림은 이메일, SNMP 트랩 또는 syslog를 통해 보낼 수 있습니다.



 a| 
AutoSupport
 a| 
AutoSupport 기능은 스토리지 배열의 상태를 모니터링하고 자동 디스패치를 기술 지원 부서에 보냅니다.



 a| 
하드웨어
 a| 
스토리지 시스템 하드웨어에는 스토리지 어레이, 컨트롤러 및 드라이브가 포함됩니다.



 a| 
호스트
 a| 
호스트는 스토리지 배열의 볼륨에 입출력을 전송하는 서버입니다.



 a| 
오브젝트
 a| 
개체는 논리적 또는 물리적 스토리지 구성 요소입니다. 논리적 객체에는 볼륨 그룹, 풀 및 볼륨이 포함됩니다. 물리적 객체에는 스토리지 어레이, 어레이 컨트롤러, 호스트 및 드라이브가 포함됩니다.



 a| 
수영장
 a| 
풀은 논리적으로 그룹화된 드라이브 집합입니다. 풀을 사용하여 호스트에서 액세스할 수 있는 볼륨을 하나 이상 생성할 수 있습니다. (풀 또는 볼륨 그룹에서 볼륨을 생성하는 경우)



 a| 
볼륨
 a| 
볼륨은 애플리케이션, 데이터베이스 및 파일 시스템이 데이터를 저장하는 컨테이너입니다. 호스트가 스토리지의 스토리지를 액세스할 수 있도록 생성되는 논리적 구성 요소입니다.

볼륨은 풀 또는 볼륨 그룹에서 사용할 수 있는 용량에서 생성됩니다. 볼륨에 정의된 용량이 있습니다. 볼륨이 두 개 이상의 드라이브로 구성될 수 있지만 볼륨은 호스트에 하나의 논리적 구성 요소로 나타납니다.



 a| 
볼륨 그룹
 a| 
볼륨 그룹은 공유 특성을 가진 볼륨의 컨테이너입니다. 볼륨 그룹의 용량과 RAID 레벨이 정의되어 있습니다. 볼륨 그룹을 사용하여 호스트에서 액세스할 수 있는 볼륨을 하나 이상 생성할 수 있습니다. 볼륨 그룹 또는 풀에서 볼륨을 생성합니다.



 a| 
워크로드
 a| 
워크로드는 애플리케이션을 지원하는 스토리지 객체입니다. 애플리케이션별로 하나 이상의 워크로드 또는 인스턴스를 정의할 수 있습니다. 일부 애플리케이션의 경우 시스템에서 기본 볼륨 특성이 비슷한 볼륨을 포함하도록 워크로드를 구성합니다. 이러한 볼륨 특성은 워크로드가 지원하는 애플리케이션 유형에 따라 최적화됩니다. 예를 들어, Microsoft SQL Server 애플리케이션을 지원하는 워크로드를 생성한 다음 해당 워크로드에 대한 볼륨을 생성하는 경우 기본 볼륨 특성은 Microsoft SQL Server를 지원하도록 최적화되어 있습니다.

|===