---
permalink: sm-interface/view-storage-hierarchy.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, storage hierarchy 
summary: 기본 인터페이스의 스토리지 계층 구조는 스토리지 배열에 의해 관리되는 다양한 하드웨어 구성 요소 및 스토리지 개체에 대한 조직화된 보기를 제공합니다. 
---
= 스토리지 계층 구조 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본 인터페이스의 스토리지 계층 구조는 스토리지 배열에 의해 관리되는 다양한 하드웨어 구성 요소 및 스토리지 개체에 대한 조직화된 보기를 제공합니다.

스토리지 계층을 보려면 홈 페이지로 이동하여 스토리지 배열 구성 요소 또는 스토리지 개체의 드롭다운 화살표를 클릭합니다. 스토리지 배열은 물리적 구성 요소와 논리적 구성 요소의 모음으로 구성됩니다.



== 물리적 구성 요소

스토리지 배열의 물리적 구성 요소는 이 표에 설명되어 있습니다.

[cols="25h,~"]
|===
| 구성 요소 | 설명 


 a| 
컨트롤러
 a| 
컨트롤러는 보드, 펌웨어 및 소프트웨어로 구성됩니다. 드라이브를 제어하고 System Manager 기능을 구현합니다.



 a| 
쉘프
 a| 
쉘프는 캐비닛 또는 랙에 설치된 엔클로저입니다. 여기에는 스토리지 어레이의 하드웨어 구성 요소가 포함됩니다. 쉘프는 컨트롤러 쉘프와 드라이브 쉘프의 두 가지 유형이 있습니다. 컨트롤러 쉘프는 컨트롤러와 드라이브를 포함합니다. 드라이브 쉘프는 입/출력 모듈(IOM) 및 드라이브를 포함합니다.

[NOTE]
====
스토리지 어레이에 미디어 유형 또는 인터페이스 유형이 서로 다른 경우 각 드라이브 유형에 대한 드라이브 쉘프가 표시됩니다.

====


 a| 
드라이브
 a| 
드라이브는 물리적 데이터 저장 매체를 제공하는 전자기 기계 장치 또는 솔리드 스테이트 메모리 장치입니다.



 a| 
호스트
 a| 
호스트는 스토리지 배열의 볼륨에 입출력을 전송하는 서버입니다.



 a| 
호스트 버스 어댑터(HBA)
 a| 
HBA(호스트 버스 어댑터)는 호스트에 상주하며 하나 이상의 호스트 포트를 포함하는 보드입니다.



 a| 
호스트 포트
 a| 
호스트 포트는 컨트롤러에 대한 물리적 연결을 제공하고 I/O 작업에 사용되는 호스트 버스 어댑터(HBA)의 포트입니다.



 a| 
관리 클라이언트
 a| 
관리 클라이언트는 System Manager 액세스를 위해 브라우저가 설치된 컴퓨터입니다.

|===


== 논리적 구성 요소

스토리지 배열의 드라이브는 데이터의 물리적 스토리지 용량을 제공합니다. System Manager를 사용하여 물리적 용량을 풀, 볼륨 그룹, 볼륨 등과 같은 논리적 구성 요소로 구성합니다. 이러한 구성 요소는 스토리지 어레이에서 데이터를 구성, 저장, 유지 관리 및 보존하는 데 사용하는 도구입니다. 스토리지 배열의 논리적 구성 요소는 이 표에 설명되어 있습니다.

[cols="25h,~"]
|===
| 구성 요소 | 설명 


 a| 
수영장
 a| 
풀은 논리적으로 그룹화된 드라이브 집합입니다. 풀을 사용하여 호스트에서 액세스할 수 있는 볼륨을 하나 이상 생성할 수 있습니다. (풀 또는 볼륨 그룹에서 볼륨을 생성하는 경우)



 a| 
볼륨 그룹
 a| 
볼륨 그룹은 공유 특성을 가진 볼륨의 컨테이너입니다. 볼륨 그룹의 용량과 RAID 레벨이 정의되어 있습니다. 볼륨 그룹을 사용하여 호스트에서 액세스할 수 있는 볼륨을 하나 이상 생성할 수 있습니다. 볼륨 그룹 또는 풀에서 볼륨을 생성합니다.



 a| 
볼륨
 a| 
볼륨은 애플리케이션, 데이터베이스 및 파일 시스템이 데이터를 저장하는 컨테이너입니다. 호스트가 스토리지의 스토리지를 액세스할 수 있도록 생성되는 논리적 구성 요소입니다.



 a| 
LUN(Logical Unit Number)
 a| 
LUN(Logical Unit Number)은 호스트가 볼륨을 액세스하는 데 사용하는 주소 공간에 할당된 번호입니다. 볼륨은 LUN 형태의 용량으로 호스트에 표시됩니다.

각 호스트에는 고유한 LUN 주소 공간이 있습니다. 따라서 서로 다른 호스트에서 동일한 LUN을 사용하여 서로 다른 볼륨에 액세스할 수 있습니다.

|===