---
permalink: sm-hardware/allow-remote-login.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, login, 
summary: 원격 로그인을 사용하면 로컬 영역 네트워크 외부의 사용자가 SSH 세션을 시작하고 컨트롤러의 설정을 변경할 수 있습니다. 
---
= SANtricity System Manager에서 원격 로그인(SSH) 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
원격 로그인을 활성화하면 로컬 영역 네트워크 외부의 사용자가 SSH 세션을 시작하고 컨트롤러의 설정에 액세스할 수 있습니다.

SANtricity 버전 11.74 이상에서는 사용자가 SSH 키 및/또는 SSH 암호를 입력하도록 요구하여 MFA(Multifactor Authorization)를 구성할 수도 있습니다. SANtricity 버전 11.73 및 이전 버전의 경우 이 기능에는 SSH 키 및 암호를 사용한 다단계 인증 옵션이 _NOT_포함됩니다.

[CAUTION]
====
보안 위험 * -- 보안상의 이유로 기술 지원 담당자만 원격 로그인 기능을 사용할 수 있습니다.

====
.단계
. 왼쪽 패널에서 menu:Hardware[Controllers and components]를 선택합니다.
+
그래픽이 변경되어 드라이브 대신 컨트롤러가 표시됩니다.

. 원격 로그인을 구성할 컨트롤러를 클릭합니다.
+
컨트롤러의 상황에 맞는 메뉴가 나타납니다.

. Configure remote login (SSH) * 를 선택합니다. (SANtricity 버전 11.73 및 이전 버전의 경우 이 메뉴 항목은 * 원격 로그인 변경 * 입니다.)
+
원격 로그인(SSH) 구성 페이지가 열립니다.

. 원격 로그인 사용 * 확인란을 선택합니다.
+
이 설정은 다음과 같은 세 가지 인증 옵션을 사용하여 원격 로그인을 제공합니다.

+
** * 암호만 *. 이 옵션을 선택하면 * 저장 * 을 클릭할 수 있습니다. 이중 시스템이 있는 경우 이전 단계를 수행하여 두 번째 컨트롤러에서 원격 로그인을 활성화할 수 있습니다.
** * SSH 키 또는 암호 *. 이 옵션의 경우 다음 단계를 진행하십시오.
** * 패스워드와 SSH 키 * 둘 다. 이 옵션의 경우 * 원격 로그인에 대해 승인된 공개 키 및 암호 필요 * 확인란을 선택하고 다음 단계를 진행합니다.


. *승인된 공개 키* 필드를 채우십시오. 이 필드에는 OpenSSH *authorized_keys* 파일 형식의 승인된 공개 키 목록이 포함됩니다.
+
*승인된 공개 키* 필드를 입력할 때 다음 지침에 유의하십시오.

+
** *승인된 공개 키* 필드는 두 컨트롤러 모두에 적용되며 첫 번째 컨트롤러에서만 구성하면 됩니다.
** authorized_keys * 파일은 한 줄에 하나의 키만 포함해야 합니다. # 및 빈 줄로 시작하는 줄은 무시됩니다. 파일 형식에 대한 자세한 내용은 을 참조하십시오 link:https://www.ssh.com/academy/ssh/authorized-keys-openssh["OpenSSH에 대한 인증 키 구성"^].
** authorized_keys * 파일은 다음 예제와 유사합니다.
+
[listing]
----
ssh-rsa
AAAAB3NzaC1yc2EAAAADAQABAAABAQDJlG20rYTk4ok+xFjkPHYp/R0LfJqEYDLXA5AJ49w3DvAWLrUg+1CpNq76WSqmQBmoG9jgbcAB5ABGdswdeMQZHilJcu29iJ3OKKv6SlCulAj1tHymwtbdhPuipd2wIDAQAB
----


. 작업을 마치면 * 저장 * 을 클릭합니다.
. 이중 시스템의 경우 위의 단계를 따라 두 번째 컨트롤러에서 원격 로그인을 활성화할 수 있습니다. 암호와 SSH 키 모두에 대한 옵션을 구성하는 경우 원격 로그인을 위해 * 승인된 공개 키 및 암호 필요 * 확인란을 다시 선택해야 합니다.
. 기술 지원 문제 해결이 완료되면 원격 로그인(SSH) 구성 페이지로 돌아가서 *원격 로그인 사용* 확인란을 선택 해제하여 원격 로그인을 비활성화할 수 있습니다. 두 번째 컨트롤러에서 원격 로그인이 활성화된 경우 확인 대화 상자가 열리고 두 번째 컨트롤러에서도 원격 로그인을 비활성화할 수 있습니다.
+
원격 로그인을 비활성화하면 현재 SSH 세션이 종료되고 새 로그인 요청이 거부됩니다.


