---
permalink: sm-hardware/configure-dns-server-addresses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, dns, server, addresses, 
summary: 'DNS(Domain Name System)는 컨트롤러 및 NTP(Network Time Protocol) 서버의 정규화된 도메인 이름을 확인하는 데 사용됩니다. 스토리지 배열의 관리 포트는 IPv4 또는 IPv6 프로토콜을 동시에 지원할 수 있습니다.' 
---
= SANtricity System Manager에서 DNS 서버 주소 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
DNS(Domain Name System)는 컨트롤러 및 NTP(Network Time Protocol) 서버의 정규화된 도메인 이름을 확인하는 데 사용됩니다. 스토리지 배열의 관리 포트는 IPv4 또는 IPv6 프로토콜을 동시에 지원할 수 있습니다.

.시작하기 전에
* 네트워크에 DNS 서버가 설치 및 구성되어 있어야 합니다.
* 기본 DNS 서버의 주소와 선택적 백업 DNS 서버의 주소를 알고 있습니다. 이러한 주소는 IPv4 주소 또는 IPv6 주소일 수 있습니다.


.이 작업에 대해
이 절차에서는 기본 및 백업 DNS 서버 주소를 지정하는 방법에 대해 설명합니다. 운영 DNS 서버에 장애가 발생할 경우 사용하도록 백업 DNS 서버를 선택적으로 구성할 수 있습니다.

[NOTE]
====
DHCP(Dynamic Host Configuration Protocol)를 사용하여 스토리지 배열의 관리 포트를 이미 구성했고 DHCP 설정과 연결된 하나 이상의 DNS 또는 NTP 서버가 있는 경우 DNS 또는 NTP를 수동으로 구성할 필요가 없습니다. 이 경우 스토리지 시스템은 이미 DNS/NTP 서버 주소를 자동으로 가져야만 합니다. 그러나 아래 지침에 따라 대화 상자를 열고 올바른 주소가 감지되는지 확인해야 합니다.

====
.단계
. 하드웨어 * 를 선택합니다.
. 그래픽에 드라이브가 표시되면 * Controllers & Components * 탭을 클릭하십시오.
+
그래픽이 변경되어 드라이브 대신 컨트롤러가 표시됩니다.

. 구성할 컨트롤러를 선택합니다.
+
컨트롤러의 상황에 맞는 메뉴가 나타납니다.

. DNS 서버 구성 * 을 선택합니다.
+
DNS(Domain Name System) 서버 구성 대화 상자가 열립니다.

. 다음 옵션 중 하나를 선택합니다.
+
** * DHCP 서버에서 DNS 서버 주소 자동으로 가져오기 * -- 감지된 DNS 서버 주소가 표시됩니다.
+
[NOTE]
====
스토리지 배열이 정적 DNS 주소를 사용하도록 설정된 경우 DNS 서버가 나타나지 않습니다.

====
** * DNS 서버 주소 수동 지정 * -- 기본 DNS 서버 주소와 백업 DNS 서버 주소를 입력합니다. 백업 서버는 선택 사항입니다. (이 주소 필드는 라디오 버튼을 선택하면 나타납니다.) 이러한 주소는 IPv4 주소 또는 IPv6 주소일 수 있습니다.


. 저장 * 을 클릭합니다.
. 다른 컨트롤러에 대해 이 단계를 반복합니다.


.결과
DNS 구성은 컨트롤러 설정, * DNS/NTP * 탭에 표시됩니다.
