---
permalink: sm-hardware/configure-management-ports.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, management, port, 
summary: 컨트롤러에는 시스템 관리에 사용되는 이더넷 포트가 포함되어 있습니다. 필요한 경우 전송 매개 변수와 IP 주소를 변경할 수 있습니다. 
---
= SANtricity System Manager에서 관리 포트 구성
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러에는 시스템 관리에 사용되는 이더넷 포트가 포함되어 있습니다. 필요한 경우 전송 매개 변수와 IP 주소를 변경할 수 있습니다.

.이 작업에 대해
이 절차를 수행하는 동안 포트 1을 선택한 다음 속도 및 포트 주소 지정 방법을 결정합니다. 포트 1은 관리 클라이언트가 컨트롤러 및 System Manager에 액세스할 수 있는 네트워크에 연결합니다.

[NOTE]
====
두 컨트롤러 중 하나에서 포트 2를 사용하지 마십시오. 포트 2는 기술 지원 부서에서 사용하도록 예약되어 있습니다.

====
.단계
. 하드웨어 * 를 선택합니다.
. 그래픽에 드라이브가 표시되면 * Controllers & Components * 탭을 클릭하십시오.
+
그래픽이 변경되어 드라이브 대신 컨트롤러가 표시됩니다.

. 구성할 관리 포트가 있는 컨트롤러를 클릭합니다.
+
컨트롤러의 상황에 맞는 메뉴가 나타납니다.

. 관리 포트 구성 * 을 선택합니다.
+
관리 포트 구성 대화 상자가 열립니다.

. 포트 1이 표시되는지 확인한 후 * 다음 * 을 클릭합니다.
. 구성 포트 설정을 선택한 후 * 다음 * 을 클릭합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 필드에 입력합니다 | 설명 


 a| 
속도 및 이중 모드
 a| 
자동 협상 설정 유지 System Manager가 스토리지 어레이와 네트워크 간의 전송 매개 변수를 결정하도록 하거나, 네트워크의 속도와 모드를 알고 있는 경우 드롭다운 목록에서 매개 변수를 선택합니다. 유효한 속도 및 이중 모드 조합만 목록에 표시됩니다.



 a| 
IPv4 사용/IPv6 사용
 a| 
IPv4 및 IPv6 네트워크에 대한 지원을 활성화하려면 하나 또는 두 옵션을 모두 선택하십시오.

|===
====
+
IPv4 사용 * 을 선택하면 * 다음 * 을 클릭한 후 IPv4 설정을 선택할 수 있는 대화 상자가 열립니다. IPv6 사용 * 을 선택하면 * 다음 * 을 클릭하면 IPv6 설정을 선택할 수 있는 대화 상자가 열립니다. 두 옵션을 모두 선택하면 먼저 IPv4 설정 대화 상자가 열리고 * 다음 * 을 클릭하면 IPv6 설정 대화 상자가 열립니다.

. IPv4 및/또는 IPv6 설정을 자동 또는 수동으로 구성합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 필드에 입력합니다 | 설명 


 a| 
DHCP 서버에서 자동으로 구성을 가져옵니다
 a| 
구성을 자동으로 가져오려면 이 옵션을 선택합니다.



 a| 
수동으로 정적 설정을 지정합니다
 a| 
이 옵션을 선택한 다음 컨트롤러의 IP 주소를 입력합니다. (필요한 경우 주소를 잘라내어 필드에 붙여 넣을 수 있습니다.) IPv4의 경우 네트워크 서브넷 마스크 및 게이트웨이를 포함합니다. IPv6의 경우 라우팅 가능한 IP 주소와 라우터 IP 주소를 포함합니다.


NOTE: IP 주소 구성을 변경하면 스토리지 배열에 대한 관리 경로가 손실됩니다. SANtricity Unified Manager를 사용하여 네트워크의 어레이를 전체적으로 관리하는 경우 사용자 인터페이스를 열고 관리 [Discover] 메뉴로 이동합니다. SANtricity 저장소 관리자를 사용하는 경우 EMW(엔터프라이즈 관리 창)에서 장치를 제거하고 메뉴 편집 [스토리지 배열 추가]를 선택하여 EMW에 다시 추가한 다음 새 IP 주소를 입력해야 합니다.

|===
====
. 마침 * 을 클릭합니다.


.결과
관리 포트 구성은 컨트롤러 설정, 관리 포트 탭에 표시됩니다.
