---
permalink: sm-hardware/configure-ntp-server-addresses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, ntp, server, addresses, network, time, protocol, 
summary: '컨트롤러가 NTP 서버를 주기적으로 쿼리하여 내부 시간 시계를 업데이트하도록 NTP(Network Time Protocol) 서버에 대한 연결을 구성할 수 있습니다.' 
---
= NTP 서버 주소를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러가 NTP 서버를 주기적으로 쿼리하여 내부 시간 시계를 업데이트하도록 NTP(Network Time Protocol) 서버에 대한 연결을 구성할 수 있습니다.

.시작하기 전에
* 네트워크에 NTP 서버가 설치 및 구성되어 있어야 합니다.
* 기본 NTP 서버의 주소와 선택적 백업 NTP 서버의 주소를 알아야 합니다. 이러한 주소는 정규화된 도메인 이름, IPv4 주소 또는 IPv6 주소일 수 있습니다.


[NOTE]
====
NTP 서버에 대해 하나 이상의 도메인 이름을 입력하는 경우 NTP 서버 주소를 확인하기 위해 DNS 서버도 구성해야 합니다. NTP를 구성하고 도메인 이름을 제공한 컨트롤러에서만 DNS 서버를 구성해야 합니다.

====
.이 작업에 대해
NTP를 사용하면 스토리지 어레이가 SNTP(Simple Network Time Protocol)를 사용하여 컨트롤러의 시계를 외부 호스트와 자동으로 동기화할 수 있습니다. 컨트롤러는 구성된 NTP 서버를 주기적으로 쿼리한 다음 결과를 사용하여 내부 시간 클럭을 업데이트합니다. 하나의 컨트롤러에만 NTP가 활성화되어 있는 경우 대체 컨트롤러는 NTP가 활성화된 컨트롤러와 해당 시계를 정기적으로 동기화합니다. 어떤 컨트롤러도 NTP를 활성화하지 않으면 컨트롤러가 주기적으로 시계를 서로 동기화합니다.

[NOTE]
====
두 컨트롤러 모두에서 NTP를 구성할 필요는 없지만, 그렇게 하면 하드웨어 또는 통신 장애 시 스토리지 어레이의 동기화 상태를 유지할 수 있습니다.

====
.단계
. 하드웨어 * 를 선택합니다.
. 그래픽에 드라이브가 표시되면 * Controllers & Components * 탭을 클릭하십시오.
+
그래픽이 변경되어 드라이브 대신 컨트롤러가 표시됩니다.

. 구성할 컨트롤러를 클릭합니다.
+
컨트롤러의 상황에 맞는 메뉴가 나타납니다.

. NTP 서버 구성 * 을 선택합니다.
+
NTP(네트워크 시간 프로토콜) 서버 구성 대화 상자가 열립니다.

. 컨트롤러 * (* A * 또는 * B *)에서 NTP 활성화를 선택합니다.
+
대화 상자에 추가 선택 사항이 나타납니다.

. 다음 옵션 중 하나를 선택합니다.
+
** * DHCP 서버에서 NTP 서버 주소 자동 가져오기 * -- 감지된 NTP 서버 주소가 표시됩니다.
+
[NOTE]
====
스토리지 배열이 정적 NTP 주소를 사용하도록 설정된 경우 NTP 서버가 나타나지 않습니다.

====
** * NTP 서버 주소 수동 지정 * -- 기본 NTP 서버 주소와 백업 NTP 서버 주소를 입력합니다. 백업 서버는 선택 사항입니다. (이 주소 필드는 라디오 버튼을 선택하면 나타납니다.) 서버 주소는 정규화된 도메인 이름, IPv4 주소 또는 IPv6 주소일 수 있습니다.


. * 선택 사항: * 백업 NTP 서버에 대한 서버 정보 및 인증 자격 증명을 입력합니다.
. 저장 * 을 클릭합니다.


.결과
NTP 서버 구성은 컨트롤러 설정, * DNS/NTP * 탭에 표시됩니다.
