---
permalink: sm-hardware/considerations-for-assigning-ip-addresses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, considerations, assigning, ip, addresses 
summary: 기본적으로 컨트롤러는 두 네트워크 포트에서 DHCP가 활성화된 상태로 제공됩니다. 고정 IP 주소를 할당하거나, 기본 고정 IP 주소를 사용하거나, DHCP 할당 IP 주소를 사용할 수 있습니다. IPv6 상태 비저장 자동 구성을 사용할 수도 있습니다. 
---
= IP 주소 할당 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본적으로 컨트롤러는 두 네트워크 포트에서 DHCP가 활성화된 상태로 제공됩니다. 고정 IP 주소를 할당하거나, 기본 고정 IP 주소를 사용하거나, DHCP 할당 IP 주소를 사용할 수 있습니다. IPv6 상태 비저장 자동 구성을 사용할 수도 있습니다.

[NOTE]
====
IPv6은 새 컨트롤러에서 기본적으로 해제되어 있지만 대체 방법을 사용하여 관리 포트 IP 주소를 구성한 다음 System Manager를 사용하여 관리 포트에서 IPv6을 사용하도록 설정할 수 있습니다.

====
네트워크 포트가 "링크 다운" 상태, 즉 LAN에서 연결이 끊어진 경우 시스템은 구성을 정적, 0.0.0.0(이전 릴리스) IP 주소 표시 또는 보고된 IP 주소 없이 DHCP 활성화(이후 릴리스)로 보고합니다. 네트워크 포트가 "링크 업" 상태(즉, LAN에 연결됨)에 있으면 DHCP를 통해 IP 주소를 얻으려고 시도합니다.

컨트롤러가 특정 네트워크 포트에서 DHCP 주소를 얻을 수 없는 경우 기본 IP 주소로 복원되며 이 주소는 최대 3분이 걸릴 수 있습니다. 기본 IP 주소는 다음과 같습니다.

[listing]
----
Controller 1 (port 1): IP Address: 192.168.128.101
----
[listing]
----
Controller 1 (port 2): IP Address: 192.168.129.101
----
[listing]
----
Controller 2 (port 1): IP Address: 192.168.128.102
----
[listing]
----
Controller 2 (port 2): IP Address: 192.168.129.102
----
IP 주소 할당 시:

* 고객 지원을 위해 컨트롤러에 포트 2를 예약합니다. 기본 네트워크 설정(DHCP 사용)을 변경하지 마십시오.
* E2800 및 E5700 컨트롤러의 정적 IP 주소를 설정하려면 SANtricity 시스템 관리자 를 사용합니다. E2700 및 E5600 컨트롤러의 정적 IP 주소를 설정하려면 SANtricity 스토리지 관리자를 사용하십시오. 정적 IP 주소를 구성한 후에는 모든 링크 다운/업 이벤트를 통해 설정된 상태로 유지됩니다.
* DHCP를 사용하여 컨트롤러의 IP 주소를 할당하려면 컨트롤러를 DHCP 요청을 처리할 수 있는 네트워크에 연결합니다. 영구 DHCP 임대를 사용합니다.
+
[NOTE]
====
기본 주소는 링크 다운 이벤트 간에 유지되지 않습니다. 컨트롤러의 네트워크 포트가 DHCP를 사용하도록 설정된 경우 컨트롤러는 케이블 삽입, 재부팅 및 전원 주기를 포함하여 모든 연결 이벤트에서 DHCP 주소를 가져오려고 시도합니다. DHCP 시도가 실패할 때마다 해당 포트의 기본 정적 IP 주소가 사용됩니다.

====

