---
permalink: sm-hardware/controller-states.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, controller, states, 
summary: 컨트롤러를 온라인, 오프라인 및 서비스 모드의 세 가지 상태로 둘 수 있습니다. 
---
= 컨트롤러 상태
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러를 온라인, 오프라인 및 서비스 모드의 세 가지 상태로 둘 수 있습니다.



== 온라인 상태입니다

온라인 상태는 컨트롤러의 정상 작동 상태입니다. 이는 컨트롤러가 정상적으로 작동하고 I/O 작업을 위해 사용할 수 있음을 의미합니다.

컨트롤러를 온라인 상태로 설정하면 해당 상태가 Optimal(최적)으로 설정됩니다.



== 오프라인 상태입니다

오프라인 상태는 일반적으로 스토리지 어레이에 두 개의 컨트롤러가 있을 때 교체할 컨트롤러를 준비하는 데 사용됩니다. 컨트롤러는 두 가지 방법으로 오프라인 상태를 입력할 수 있습니다. 즉, 명시적 명령을 실행하거나 컨트롤러에 장애가 발생할 수 있습니다. 컨트롤러는 다른 명시적 명령을 실행하거나 오류가 발생한 컨트롤러를 교체하여 오프라인 상태를 종료할 수 있습니다. 스토리지 어레이에 두 개의 컨트롤러가 있는 경우에만 컨트롤러를 오프라인으로 전환할 수 있습니다.

컨트롤러가 오프라인 상태인 경우 다음 조건이 적용됩니다.

* 컨트롤러는 I/O에 사용할 수 없습니다
* 해당 컨트롤러를 통해서는 스토리지 어레이를 관리할 수 없습니다.
* 해당 컨트롤러가 현재 소유한 모든 볼륨은 다른 컨트롤러로 이동됩니다.
* 캐시 미러링이 비활성화되어 있고 모든 볼륨이 캐시 모드를 통해 쓰기로 변경됩니다.




== 서비스 모드

서비스 모드는 일반적으로 기술 지원 부서에서 다른 컨트롤러를 진단할 수 있도록 모든 스토리지 어레이 볼륨을 하나의 컨트롤러로 이동하는 데 사용됩니다. 컨트롤러는 서비스 모드로 수동으로 배치되어야 하며 서비스 작업이 완료된 후 수동으로 다시 온라인 상태로 전환되어야 합니다.

컨트롤러가 서비스 모드에 있으면 다음 조건이 적용됩니다.

* 컨트롤러는 I/O에 사용할 수 없습니다
* 기술 지원 부서에서는 직렬 포트 또는 네트워크 연결을 통해 컨트롤러에 액세스하여 잠재적인 문제를 분석할 수 있습니다.
* 해당 컨트롤러가 현재 소유한 모든 볼륨은 다른 컨트롤러로 이동됩니다.
* 캐시 미러링이 비활성화되어 있고 모든 볼륨이 캐시 모드를 통해 쓰기로 변경됩니다.

