---
permalink: sm-hardware/drive-states.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, drive, states, 
summary: System Manager는 드라이브의 다양한 상태를 보고합니다. 
---
= 드라이브 상태
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager는 드라이브의 다양한 상태를 보고합니다.



== 액세스 가능성 상태

[cols="25h,~"]
|===
| 상태 | 정의 


 a| 
무시됨
 a| 
드라이브가 물리적으로 존재하지만 컨트롤러가 어느 포트에서나 드라이브와 통신할 수 없습니다.



 a| 
호환되지 않습니다
 a| 
다음 조건 중 하나가 존재합니다.

* 드라이브가 스토리지 배열에 사용하도록 인증되지 않았습니다.
* 드라이브의 섹터 크기가 다릅니다.
* 이전 또는 최신 펌웨어 버전에서 사용할 수 없는 구성 데이터가 드라이브에 있습니다.




 a| 
제거되었습니다
 a| 
스토리지 배열에서 드라이브가 부적절하게 제거되었습니다.



 a| 
발표
 a| 
컨트롤러는 두 포트의 드라이브와 통신할 수 있습니다.



 a| 
응답하지 않습니다
 a| 
드라이브가 명령에 응답하지 않습니다.

|===


== 역할 상태

[cols="25h,~"]
|===
| 상태 | 정의 


 a| 
할당됨
 a| 
드라이브가 풀 또는 볼륨 그룹의 구성원입니다.



 a| 
사용 중인 핫 스페어
 a| 
현재 드라이브가 장애가 발생한 드라이브를 대체하는 데 사용되고 있습니다. 핫 스페어는 풀이 아닌 볼륨 그룹에서만 사용됩니다.



 a| 
대기 핫 스페어
 a| 
장애가 발생한 드라이브를 교체할 준비가 되었습니다. 핫 스페어는 풀이 아닌 볼륨 그룹에서만 사용됩니다.



 a| 
할당되지 않음
 a| 
드라이브가 풀 또는 볼륨 그룹의 구성원이 아닙니다.

|===


== 가용성 상태입니다

[cols="25h,~"]
|===
| 상태 | 정의 


 a| 
실패했습니다
 a| 
드라이브가 작동하지 않습니다. 드라이브의 데이터를 사용할 수 없습니다.



 a| 
임박한 장애
 a| 
드라이브가 곧 고장날 수 있다는 것이 감지되었습니다. 드라이브의 데이터를 계속 사용할 수 있습니다.



 a| 
오프라인
 a| 
일반적으로 드라이브를 내보내는 볼륨 그룹의 일부이거나 펌웨어 업그레이드를 진행 중이므로 데이터를 저장할 수 없습니다.



 a| 
최적
 a| 
드라이브가 정상적으로 작동합니다.

|===