---
permalink: sm-hardware/erase-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, erase, drives, removal, 
summary: 지우기 옵션을 사용하여 시스템에서 제거할 할당되지 않은 드라이브를 준비할 수 있습니다. 이 절차에서는 데이터를 영구적으로 제거하여 데이터를 다시 읽을 수 없도록 합니다. 
---
= SANtricity System Manager에서 드라이브 지우기
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
지우기 옵션을 사용하여 시스템에서 제거할 할당되지 않은 드라이브를 준비할 수 있습니다. 이 절차에서는 데이터를 영구적으로 제거하여 데이터를 다시 읽을 수 없도록 합니다.

.시작하기 전에
드라이브가 할당되지 않은 상태여야 합니다.

.이 작업에 대해
드라이브의 모든 데이터를 영구적으로 제거하려는 경우에만 지우기 옵션을 사용합니다. 드라이브가 안전하게 활성화된 경우 Erase(지우기) 옵션은 암호화 지우기를 수행하고 드라이브의 보안 속성을 다시 보안 기능으로 재설정합니다.

[NOTE]
====
지우기 기능은 일부 이전 드라이브 모델을 지원하지 않습니다. 이러한 이전 모델 중 하나를 지우려고 하면 오류 메시지가 나타납니다.

====
.단계
. 하드웨어 * 를 선택합니다.
. 그림에 컨트롤러가 표시되면 * Drives * 탭을 클릭합니다.
+
그래픽이 변경되어 컨트롤러 대신 드라이브가 표시됩니다.

. 선택적으로 필터 필드를 사용하여 쉘프의 할당되지 않은 모든 드라이브를 볼 수 있습니다. Show drives that are... * 드롭다운 목록에서 * Unassigned * 를 선택합니다.
+
쉘프 보기에는 할당되지 않은 드라이브만 표시되며 다른 모든 드라이브는 회색으로 표시됩니다.

. 드라이브의 상황에 맞는 메뉴를 열려면 지울 드라이브를 클릭합니다. (여러 드라이브를 선택하려면 드라이브 지우기 대화 상자에서 선택할 수 있습니다.)
+
[CAUTION]
====
* 데이터 손실 가능성 * -- 지우기 작업을 실행 취소할 수 없습니다. 절차를 진행하는 동안 올바른 드라이브를 선택해야 합니다.

====
. 컨텍스트 메뉴에서 * Erase * 를 선택합니다.
+
Erase Drives(드라이브 지우기) 대화 상자가 열리고 지우기 작업에 사용할 수 있는 모든 드라이브가 표시됩니다.

. 필요한 경우 테이블에서 추가 드라이브를 선택합니다. ALL_DRIVE를 선택할 수 없습니다. 하나의 드라이브가 선택 해제되어 있는지 확인하십시오.
. 지우기 를 입력하여 작업을 확인한 다음 * 지우기 * 를 클릭합니다.
+
[CAUTION]
====
이 작업을 계속 진행하십시오. 다음 대화 상자에서 예를 클릭하면 작업을 중단할 수 없습니다.

====
. 예상 완료 시간 대화 상자에서 * 예 * 를 클릭하여 지우기 작업을 계속합니다.


.결과
지우기 작업에는 몇 분 또는 몇 시간이 걸릴 수 있습니다. 홈 [View Operations in Progress] 메뉴에서 상태를 볼 수 있습니다. 지우기 작업이 완료되면 다른 볼륨 그룹 또는 디스크 풀 또는 다른 스토리지 어레이에서 드라이브를 사용할 수 있습니다.

.작업을 마친 후
드라이브를 다시 사용하려면 먼저 초기화해야 합니다. 이렇게 하려면 드라이브의 컨텍스트 메뉴에서 * Initialize * 를 선택합니다.
