---
permalink: sm-hardware/fail-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, fail, drive, 
summary: 그렇게 하라는 지시가 있으면 드라이브를 수동으로 실패할 수 있습니다. 
---
= 드라이브 오류
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그렇게 하라는 지시가 있으면 드라이브를 수동으로 실패할 수 있습니다.

.이 작업에 대해
System Manager는 스토리지 배열의 드라이브를 모니터링합니다. 드라이브에서 많은 오류가 발생하는 것을 감지하면 Recovery Guru에서 드라이브 장애가 임박했음을 알립니다. 이 경우 교체 드라이브를 사용할 수 있는 경우 드라이브가 장애를 갖고 우선 조치를 취할 수 있습니다. 교체 드라이브를 사용할 수 없는 경우 드라이브가 스스로 고장날 때까지 기다릴 수 있습니다.

[CAUTION]
====
* 데이터 액세스 손실 가능성 * -- 이 작업은 데이터 손실이나 데이터 중복성의 손실을 초래할 수 있습니다. 기술 지원 부서 또는 Recovery Guru에서 지시한 경우에만 이 작업을 수행하십시오.

====
.단계
. 하드웨어 * 를 선택합니다.
. 그림에 컨트롤러가 표시되면 * Drives * 탭을 클릭합니다.
+
그래픽이 변경되어 컨트롤러 대신 드라이브가 표시됩니다.

. 실패하려는 드라이브를 클릭합니다.
+
드라이브의 컨텍스트 메뉴가 나타납니다.

. 실패 * 를 선택합니다.
. 실패 전에 * 드라이브의 내용 복사 * 확인란을 선택한 상태로 유지합니다.
+
복사 옵션은 할당된 드라이브 및 비 RAID 0 볼륨 그룹에 대해서만 나타납니다.

+
드라이브에 장애가 발생하기 전에 드라이브의 내용을 복사해야 합니다. 구성에 따라 드라이브의 내용을 먼저 복사하지 않으면 연결된 풀 또는 볼륨 그룹의 모든 데이터 또는 데이터 중복성이 손실될 수 있습니다.

+
복사 옵션을 사용하면 재구성 작업보다 더 빠르게 드라이브를 복구할 수 있으며 복사 작업 중에 다른 드라이브에 장애가 발생할 경우 볼륨 장애 가능성이 줄어듭니다.

. 드라이브에 오류가 발생할지 확인합니다.
+
드라이브에 오류가 발생한 후 30초 이상 기다린 후 제거하십시오.


