---
permalink: sm-hardware/faq-storage-shelf.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager를 위한 보관 선반 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 선반 손실 방지 및 서랍 손실 방지란 무엇입니까?

쉘프 손실 보호 및 드로어 손실 보호는 단일 쉘프 또는 드로어에 장애가 발생해도 데이터 액세스를 유지할 수 있는 풀 및 볼륨 그룹의 속성입니다.



=== 선반 손실 방지

쉘프는 드라이브 또는 드라이브와 컨트롤러를 포함합니다. 쉘프 손실 방지: 단일 드라이브 쉘프로 통신이 두절되는 경우 풀 또는 볼륨 그룹의 볼륨에서 데이터에 액세스할 수 있습니다. 예를 들어, 통신 장애가 발생할 경우 드라이브 쉘프에 대한 전원 공급이 중단되거나 두 I/O 모듈(IOM)이 모두 실패할 수 있습니다.

[NOTE]
====
풀 또는 볼륨 그룹에서 드라이브가 이미 장애가 발생한 경우에는 쉘프 손실 보호가 보장되지 않습니다. 이 경우, 드라이브 쉘프와 풀 또는 볼륨 그룹의 다른 드라이브에 액세스하지 못하면 데이터가 손실됩니다.

====
쉘프 손실 방지 기준은 다음 표에 설명된 보호 방법에 따라 다릅니다.

[cols="1a,1a,1a"]
|===
| 레벨 | 셸프 손실 방지 기준 | 필요한 최소 쉘프 수입니다 


 a| 
수영장
 a| 
풀은 5개 이상의 쉘프의 드라이브를 포함해야 하며 각 쉘프에 동일한 수의 드라이브가 있어야 합니다. 셸프 손실 보호는 고용량 셸프에는 적용되지 않습니다. 시스템에 고용량 셸프가 포함되어 있는 경우 문서함 손실 보호 를 참조하십시오.
 a| 
5



 a| 
RAID 6
 a| 
볼륨 그룹은 단일 쉘프에 드라이브를 2개 이상 포함하지 않습니다.
 a| 
3



 a| 
RAID 3 또는 RAID 5
 a| 
볼륨 그룹의 각 드라이브는 별도의 쉘프에 있습니다.
 a| 
3



 a| 
RAID 1
 a| 
RAID 1 쌍의 각 드라이브는 별도의 쉘프에 있어야 합니다.
 a| 
2



 a| 
RAID 0
 a| 
선반 손실 보호를 달성할 수 없습니다.
 a| 
해당 없음

|===


=== 서랍 손실 방지

드라이브 액세스를 위해 서랍식 용지함은 셸프의 구획 중 하나입니다. 고용량 쉘프에만 서랍이 있습니다. 드로어 손실 보호는 단일 드로어와의 통신이 완전히 손실되는 경우 풀 또는 볼륨 그룹의 볼륨에 있는 데이터에 액세스할 수 있도록 보장합니다. 통신 손실의 예로는 드로어에 대한 전원 손실 또는 드로어 내 내부 구성 요소의 고장이 있습니다.

[NOTE]
====
풀 또는 볼륨 그룹에서 드라이브에 장애가 이미 발생한 경우에는 드로어 손실 보호가 보장되지 않습니다. 이 경우 드로어(풀 또는 볼륨 그룹의 다른 드라이브)에 액세스하지 못하게 되면 데이터가 손실됩니다.

====
드로어 손실 방지 기준은 다음 표에 설명된 보호 방법에 따라 다릅니다.

[cols="1a,1a,1a"]
|===
| 레벨 | 서랍 손실 방지 기준 | 필요한 최소 드로어 수입니다 


 a| 
수영장
 a| 
풀 후보는 모든 드로어의 드라이브를 포함해야 하며 각 드로어에 동일한 수의 드라이브가 있어야 합니다.

풀에는 5개 이상의 서랍에서 나온 드라이브가 포함되어야 하며 각 드로어에 동일한 수의 드라이브가 있어야 합니다.

60-드라이브 쉘프는 15, 20, 25, 30, 35, 40, 45, 50, 55 또는 60개 드라이브. 초기 생성 후 풀에 5의 배수로 증분을 추가할 수 있습니다.
 a| 
5



 a| 
RAID 6
 a| 
볼륨 그룹은 단일 드로어에 2개 이상의 드라이브를 포함하지 않습니다.
 a| 
3



 a| 
RAID 3 또는 RAID 5
 a| 
볼륨 그룹의 각 드라이브는 별도의 드로어에 있습니다.
 a| 
3



 a| 
RAID 1
 a| 
미러링된 쌍의 각 드라이브는 별도의 드로어에 위치해야 합니다.
 a| 
2



 a| 
RAID 0
 a| 
문서함 손실 방지를 달성할 수 없습니다.
 a| 
해당 없음

|===


== 배터리 학습 사이클이란 무엇입니까?

학습 사이클은 스마트 배터리 게이지를 보정하기 위한 자동 사이클입니다.

학습 사이클은 다음과 같은 단계로 구성됩니다.

* 제어된 배터리 방전
* 휴식 기간
* 충전


배터리는 사전 설정된 임계값으로 방전됩니다. 이 단계에서는 배터리 게이지가 보정됩니다.

런 사이클에는 다음 매개변수가 필요합니다.

* 완전히 충전된 배터리
* 과열된 배터리가 없습니다


이중 컨트롤러 시스템에 대한 학습 사이클이 동시에 발생합니다. 두 개 이상의 배터리 또는 배터리 셀 세트에서 백업 전원을 사용하는 컨트롤러의 경우 학습 사이클이 순차적으로 발생합니다.

학습 사이클은 일정한 간격으로, 동시에 같은 요일에 자동으로 시작되도록 예약됩니다. 주기 사이의 간격은 주 단위로 설명됩니다.

[NOTE]
====
학습 사이클을 완료하는 데 몇 시간이 걸릴 수 있습니다.

====