---
permalink: sm-hardware/faq-storage-controller.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager용 스토리지 컨트롤러 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 자동 협상이란 무엇입니까?

자동 협상은 네트워크 인터페이스가 다른 네트워크 인터페이스와 자체 연결 매개변수(속도 및 이중 모드)를 자동으로 조정하는 기능입니다.

자동 협상은 일반적으로 관리 포트를 구성하는 데 선호되는 설정입니다. 그러나 협상에 실패하면 네트워크 인터페이스 설정이 일치하지 않으면 네트워크 성능에 심각한 영향을 미칠 수 있습니다. 이 상태가 허용되지 않는 경우 네트워크 인터페이스 설정을 올바른 구성으로 수동으로 설정해야 합니다. 자동 협상은 컨트롤러의 이더넷 관리 포트에 의해 수행됩니다. iSCSI 호스트 버스 어댑터가 자동 협상을 수행하지 않습니다.

[NOTE]
====
자동 협상이 실패할 경우 컨트롤러는 최소 공통 분모인 10BASE-T 반이중 모드로 연결을 시도합니다.

====


== IPv6 상태 비저장 주소 자동 구성이란 무엇입니까?

상태 비저장 자동 구성을 사용하는 경우 호스트는 서버에서 주소 및 기타 구성 정보를 얻지 못합니다.

IPv6의 상태 비저장 자동 구성은 링크 로컬 주소, 멀티캐스팅 및 ND(Neighbor Discovery) 프로토콜을 지원합니다. IPv6는 내부 데이터 링크 계층 주소에서 주소의 인터페이스 ID를 생성할 수 있습니다.

상태 비저장 자동 구성 및 상태 저장 자동 구성은 서로 보완됩니다. 예를 들어, 호스트는 상태 비저장 자동 구성을 사용하여 자체 주소를 구성할 수 있지만 상태 저장 자동 구성을 사용하여 다른 정보를 얻을 수 있습니다. 스테이트풀 자동 구성을 사용하면 호스트가 서버에서 주소 및 기타 구성 정보를 얻을 수 있습니다. 또한 IPv6(인터넷 프로토콜 버전 6)에서는 네트워크의 모든 IP 주소를 한 번에 다시 지정할 수 있는 방법을 정의합니다. IPv6은 서버의 필요 없이 IP 주소 및 기타 매개 변수를 자동으로 구성하는 네트워크 디바이스의 방법을 정의합니다.

상태 비저장 자동 구성을 사용하는 경우 장치는 다음 단계를 수행합니다.

. * 링크 로컬 주소 생성 * -- 장치는 링크 로컬 주소를 생성합니다. 로컬 주소는 10비트이고 그 뒤에 54개의 0이 있으며 그 뒤에 64비트 인터페이스 ID가 붙습니다.
. * 링크-로컬 주소의 고유성 테스트 * -- 노드는 생성하는 링크-로컬 주소가 로컬 네트워크에서 이미 사용되고 있지 않은지 확인하기 위해 테스트합니다. 노드는 ND 프로토콜을 사용하여 인접 요청 메시지를 보냅니다. 이에 따라, 로컬 네트워크는 다른 장치가 이미 링크 로컬 주소를 사용하고 있음을 나타내는 인접 광고 메시지를 수신 대기합니다. 이 경우 새 링크 로컬 주소를 생성하거나 자동 구성에 실패하고 다른 방법을 사용해야 합니다.
. * 링크 로컬 주소 할당 * -- 장치가 고유성 테스트를 통과하면 장치는 해당 IP 인터페이스에 링크 로컬 주소를 할당합니다. 링크 로컬 주소는 인터넷을 통한 통신이 아니라 로컬 네트워크에서의 통신에 사용할 수 있습니다.
. * 라우터 연락처 * -- 노드는 로컬 라우터에 연결을 시도하여 구성을 계속하는 방법에 대한 자세한 정보를 제공합니다. 이 연락처는 공유기가 주기적으로 보내는 라우터 알림 메시지를 듣거나 특정 라우터 요청 메시지를 전송하여 공유기에 수행할 작업에 대한 정보를 요청하는 방식으로 수행됩니다.
. * 노드 방향 제공 * -- 라우터는 자동 구성 진행 방법에 대한 노드의 방향을 제공합니다. 또는 라우터는 호스트에 글로벌 인터넷 주소를 확인하는 방법을 알려줍니다.
. * 글로벌 주소 구성 * -- 호스트는 전역적으로 고유한 인터넷 주소를 사용하여 자체적으로 구성됩니다. 이 주소는 일반적으로 라우터에 의해 호스트에 제공된 네트워크 접두사로 형성됩니다.




== DHCP와 수동 구성 중 무엇을 선택해야 합니까?

네트워크 구성의 기본 방법은 DHCP(Dynamic Host Configuration Protocol)입니다. 네트워크에 DHCP 서버가 없는 경우 항상 이 옵션을 사용하십시오.



== DHCP 서버란 무엇입니까?

DHCP(Dynamic Host Configuration Protocol)는 IP(인터넷 프로토콜) 주소 할당 작업을 자동화하는 프로토콜입니다.

TCP/IP 네트워크에 연결된 각 장치에는 고유한 IP 주소가 할당되어야 합니다. 이러한 장치에는 스토리지 배열의 컨트롤러가 포함됩니다.

DHCP를 사용하지 않으면 네트워크 관리자가 이러한 IP 주소를 수동으로 입력합니다. DHCP를 사용하는 경우 클라이언트가 TCP/IP 작업을 시작해야 할 때 클라이언트는 주소 정보 요청을 브로드캐스트합니다. DHCP 서버는 요청을 받고, 임대 기간이라는 지정된 시간 동안 새 주소를 할당하고, 클라이언트에 주소를 보냅니다. DHCP를 사용하면 장치가 네트워크에 연결될 때마다 다른 IP 주소를 가질 수 있습니다. 일부 시스템에서는 장치가 연결되어 있는 동안에도 장치의 IP 주소가 변경될 수 있습니다.



== DHCP 서버를 어떻게 구성합니까?

스토리지 배열의 컨트롤러에 대해 고정 IP(인터넷 프로토콜) 주소를 사용하려면 DHCP(동적 호스트 구성 프로토콜) 서버를 구성해야 합니다.

DHCP 서버가 할당하는 IP 주소는 일반적으로 동적이며 임대 기간이 만료되므로 변경할 수 있습니다. 서버 및 라우터와 같은 일부 장치는 정적 주소를 사용해야 합니다. 스토리지 어레이의 컨트롤러에도 고정 IP 주소가 필요합니다.

정적 주소를 할당하는 방법에 대한 자세한 내용은 DHCP 서버 설명서를 참조하십시오.



== 컨트롤러 네트워크 구성을 변경해야 하는 이유는 무엇입니까?

대역외 관리를 사용하는 경우 각 컨트롤러의 네트워크 구성(IP(인터넷 프로토콜) 주소, 서브네트워크 마스크(서브넷 마스크) 및 게이트웨이)을 설정해야 합니다.

DHCP(Dynamic Host Configuration Protocol) 서버를 사용하여 네트워크 구성을 설정할 수 있습니다. DHCP 서버를 사용하지 않는 경우 네트워크 구성을 수동으로 입력해야 합니다.



== 네트워크 구성은 어디에서 얻을 수 있습니까?

네트워크 관리자로부터 IP(인터넷 프로토콜) 주소, 서브네트워크 마스크(서브넷 마스크) 및 게이트웨이 정보를 얻을 수 있습니다.

컨트롤러에서 포트를 구성할 때 이 정보가 필요합니다.



== ICMP ping 응답이란?

ICMP(Internet Control Message Protocol)는 TCP/IP 제품군의 프로토콜 중 하나입니다.

ICMP 에코 요청과 ICMP 에코 응답 메시지는 주로 핑 메시지라고 한다. Ping은 시스템 관리자가 네트워크 장치 간의 연결을 수동으로 테스트하고 네트워크 지연 및 패킷 손실을 테스트하는 데 사용하는 문제 해결 도구입니다. ping 명령은 ICMP 에코 요청을 네트워크의 장치로 보내고, 장치는 즉시 ICMP 에코 응답으로 응답한다. 기업의 네트워크 보안 정책에는 권한이 없는 사람이 알아내기 어렵게 만들기 위해 모든 장치에서 ping(ICMP 에코 응답)을 비활성화해야 하는 경우도 있습니다.



== 포트 구성을 언제 새로 고침해야 합니까?

서버를 수정하거나 업그레이드할 때마다 DHCP 서버를 새로 고치고, 현재 스토리지 어레이와 사용할 스토리지 배열에 관련된 DHCP 정보가 변경되었습니다.

특히 DHCP 서버가 다른 주소를 할당할 것이라는 사실을 알고 있을 때 DHCP 서버에서 포트 구성 또는 iSNS 서버를 새로 고칩니다.

[NOTE]
====
포트 구성을 새로 고치면 해당 포트의 모든 iSCSI 연결이 손상될 수 있습니다.

====


== 관리 포트를 구성한 후에는 어떻게 해야 합니까?

스토리지 어레이의 IP 주소를 변경한 경우 SANtricity Unified Manager에서 글로벌 어레이 보기를 업데이트할 수 있습니다.

Unified Manager에서 글로벌 어레이 보기를 업데이트하려면 인터페이스를 열고 관리 [검색] 메뉴로 이동합니다.

SANtricity 저장소 관리자를 계속 사용하는 경우 EMW(엔터프라이즈 관리 창)로 이동하여 새 IP 주소를 제거하고 다시 추가해야 합니다.



== 스토리지 시스템이 최적화되지 않은 모드인 이유는 무엇입니까?

최적화되지 않은 모드의 스토리지 시스템은 잘못된 시스템 구성 상태로 인해 발생합니다. 이러한 상태에도 불구하고 기존 볼륨에 대한 일반 I/O 액세스는 완벽하게 지원되지만 SANtricity System Manager에서는 일부 작업을 금지합니다.

다음 이유 중 하나로 스토리지 시스템이 잘못된 시스템 구성으로 전환될 수 있습니다.

* 컨트롤러가 규정 준수 범위를 벗어났을 수 있습니다. 이는 잘못된 SMID(Submodel ID) 코드를 가지고 있거나 프리미엄 기능 제한을 초과했기 때문일 수 있습니다.
* 드라이브 펌웨어 다운로드와 같은 내부 서비스 작업이 진행 중입니다.
* 컨트롤러가 패리티 오류 임계값을 초과하고 잠금을 시작했습니다.
* 일반 잠금 조건이 발생했습니다.

