---
permalink: sm-hardware/hardware-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hardware, terms 
summary: 스토리지 어레이에 하드웨어 조건이 적용되는 방법에 대해 알아보십시오. 
---
= 하드웨어 용어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 하드웨어 용어가 스토리지 어레이에 적용됩니다.

.일반 하드웨어 용어:
[%collapsible]
====
[cols="25h,~"]
|===
| 구성 요소 | 설명 


 a| 
베이
 a| 
베이는 드라이브 또는 다른 구성 요소가 설치된 쉘프의 슬롯입니다.



 a| 
컨트롤러
 a| 
컨트롤러는 보드, 펌웨어 및 소프트웨어로 구성됩니다. 드라이브를 제어하고 System Manager 기능을 구현합니다.



 a| 
컨트롤러 쉘프
 a| 
컨트롤러 쉘프는 드라이브 세트 및 하나 이상의 컨트롤러 캐니스터를 포함합니다. 컨트롤러 캐니스터에는 컨트롤러, 호스트 인터페이스 카드(HIC) 및 배터리가 들어 있습니다.



 a| 
드라이브
 a| 
드라이브는 물리적 데이터 저장 매체를 제공하는 전자기 기계 장치 또는 솔리드 스테이트 메모리 장치입니다.



 a| 
드라이브 쉘프
 a| 
확장 쉘프라고도 하는 드라이브 쉘프에는 드라이브 세트 및 IOXM(입출력 모듈) 2개가 포함됩니다. IOM에는 드라이브 쉘프를 컨트롤러 쉘프 또는 다른 드라이브 쉘프에 연결하는 SAS 포트가 포함되어 있습니다.



 a| 
IOM(ESM)
 a| 
IOM은 드라이브 쉘프를 컨트롤러 쉘프에 연결하기 위한 SAS 포트가 포함된 입력/출력 모듈입니다. 이전 컨트롤러 모델에서 IOM은 환경 서비스 모듈(ESM)이라고 했습니다.



 a| 
전원/팬 캐니스터
 a| 
전원/팬 캐니스터는 선반으로 미끄러지는 어셈블리입니다. 여기에는 전원 공급 장치 및 내장형 팬이 포함됩니다.



 a| 
SFP
 a| 
SFP는 SFP(Small Form-factor Pluggable) 트랜시버입니다.



 a| 
쉘프
 a| 
쉘프는 캐비닛 또는 랙에 설치된 엔클로저입니다. 여기에는 스토리지 어레이의 하드웨어 구성 요소가 포함됩니다. 쉘프는 컨트롤러 쉘프와 드라이브 쉘프의 두 가지 유형이 있습니다. 컨트롤러 쉘프는 컨트롤러와 드라이브를 포함합니다. 드라이브 쉘프는 입/출력 모듈(IOM) 및 드라이브를 포함합니다.



 a| 
스토리지 시스템
 a| 
스토리지 어레이에는 쉘프, 컨트롤러, 드라이브, 소프트웨어 및 펌웨어가 포함되어 있습니다.

|===
====
.컨트롤러 용어:
[%collapsible]
====
[cols="25h,~"]
|===
| 구성 요소 | 설명 


 a| 
컨트롤러
 a| 
컨트롤러는 보드, 펌웨어 및 소프트웨어로 구성됩니다. 드라이브를 제어하고 System Manager 기능을 구현합니다.



 a| 
컨트롤러 쉘프
 a| 
컨트롤러 쉘프는 드라이브 세트 및 하나 이상의 컨트롤러 캐니스터를 포함합니다. 컨트롤러 캐니스터에는 컨트롤러, 호스트 인터페이스 카드(HIC) 및 배터리가 들어 있습니다.



 a| 
DHCP를 선택합니다
 a| 
DHCP(Dynamic Host Configuration Protocol)는 IP 주소와 같은 네트워크 구성 매개 변수를 동적으로 배포하기 위해 IP(인터넷 프로토콜) 네트워크에서 사용되는 프로토콜입니다.



 a| 
DNS
 a| 
DNS(Domain Name System)는 인터넷 또는 개인 네트워크에 연결된 장치의 명명 시스템입니다. DNS 서버는 도메인 이름의 디렉터리를 유지 관리하고 이를 IP(인터넷 프로토콜) 주소로 변환합니다.



 a| 
이중 구성
 a| 
Duplex는 스토리지 배열 내의 이중 컨트롤러 모듈 구성입니다. 이중 시스템은 컨트롤러, 논리적 볼륨 경로 및 디스크 경로와 관련하여 완전히 이중화됩니다. 한 컨트롤러에 장애가 발생하면 다른 컨트롤러가 I/O를 인수하여 가용성을 유지합니다. 이중 시스템에는 이중 팬 및 전원 공급 장치가 있습니다.



 a| 
전이중/반이중 연결
 a| 
전이중 및 반이중 모드는 연결 모드를 참조하십시오. 전이중 모드에서는 두 장치가 양방향으로 동시에 통신할 수 있습니다. 반이중 모드에서는 장치가 한 번에 한 방향씩 통신할 수 있습니다(한 장치는 메시지를 보내고 다른 장치는 메시지를 받습니다).



 a| 
HIC
 a| 
HIC(호스트 인터페이스 카드)는 컨트롤러 캐니스터 내에 선택적으로 설치할 수 있습니다. 컨트롤러에 내장된 호스트 포트를 베이스보드 호스트 포트라고 합니다. HIC에 내장된 호스트 포트를 HIC 포트라고 합니다.



 a| 
ICMP ping 응답
 a| 
ICMP(Internet Control Message Protocol)는 네트워크 컴퓨터의 운영 체제에서 메시지를 보내는 데 사용되는 프로토콜입니다. ICMP 메시지는 호스트에 연결할 수 있는지 여부와 해당 호스트와 패킷을 주고 받는 데 걸리는 시간을 결정합니다.



 a| 
MAC 주소
 a| 
MAC 주소(Media Access Control Identifier)는 동일한 물리적 전송 네트워크 인터페이스의 두 포트를 연결하는 별도의 논리 채널을 구분하기 위해 이더넷에서 사용됩니다.



 a| 
관리 클라이언트
 a| 
관리 클라이언트는 System Manager 액세스를 위해 브라우저가 설치된 컴퓨터입니다.



 a| 
MTU
 a| 
MTU(Maximum Transmission Unit)는 네트워크에서 전송할 수 있는 가장 큰 크기의 패킷 또는 프레임입니다.



 a| 
NTP
 a| 
NTP(Network Time Protocol)는 데이터 네트워크의 컴퓨터 시스템 간 클록 동기화를 위한 네트워킹 프로토콜입니다.



 a| 
단일 구성
 a| 
Simplex는 스토리지 어레이 내에서 단일 컨트롤러 모듈 구성입니다. 단일 시스템은 컨트롤러 또는 디스크 경로 이중화를 제공하지 않지만 이중 팬 및 전원 공급 장치가 있습니다.



 a| 
VLAN
 a| 
VLAN(Virtual Local Area Network)은 동일한 디바이스(스위치, 라우터 등)에서 지원하는 다른 네트워크와 물리적으로 분리된 것처럼 작동하는 논리적 네트워크입니다.

|===
====
.드라이브 용어:
[%collapsible]
====
[cols="25h,~"]
|===
| 구성 요소 | 설명 


 a| 
DA
 a| 
DA(Data Assurance)는 데이터를 컨트롤러를 통해 드라이브로 전송할 때 발생할 수 있는 오류를 확인하고 수정하는 기능입니다. Fibre Channel과 같은 DA 지원 입출력 인터페이스를 사용하는 호스트에서 풀 또는 볼륨 그룹 레벨에서 Data Assurance를 설정할 수 있습니다.



 a| 
드라이브 보안 기능
 a| 
드라이브 보안은 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브를 통해 추가 보안 계층을 제공하는 스토리지 어레이 기능입니다. 이러한 드라이브를 드라이브 보안 기능과 함께 사용하는 경우 데이터에 액세스하려면 보안 키가 필요합니다. 드라이브가 어레이에서 물리적으로 제거되면 다른 어레이에 설치될 때까지 작동할 수 없으며, 이때 올바른 보안 키가 제공될 때까지 보안 잠금 상태가 됩니다.



 a| 
드라이브 쉘프
 a| 
확장 쉘프라고도 하는 드라이브 쉘프에는 드라이브 세트 및 IOXM(입출력 모듈) 2개가 포함됩니다. IOM에는 드라이브 쉘프를 컨트롤러 쉘프 또는 다른 드라이브 쉘프에 연결하는 SAS 포트가 포함되어 있습니다.



 a| 
DULBE
 a| 
DULBE(Deallocated or UnWritten Logical Block Error)는 EF300 또는 EF600 스토리지 어레이가 리소스 프로비저닝된 볼륨을 지원할 수 있도록 하는 NVMe 드라이브의 옵션입니다.



 a| 
FDE 드라이브
 a| 
FDE(전체 디스크 암호화) 드라이브는 하드웨어 레벨의 디스크 드라이브에서 암호화를 수행합니다. 하드 드라이브에는 쓰기 중에 데이터를 암호화한 다음 읽기 중에 데이터를 해독하는 ASIC 칩이 포함되어 있습니다.



 a| 
FIPS 드라이브
 a| 
FIPS 드라이브는 FIPS(Federal Information Processing Standards) 140-2 레벨 2를 사용합니다. 이러한 드라이브는 강력한 암호화 알고리즘 및 방법을 보장하는 미국 정부 표준을 준수하는 FDE 드라이브입니다. FIPS 드라이브는 FDE 드라이브보다 보안 표준이 더 높습니다.



 a| 
HDD
 a| 
하드 디스크 드라이브(HDD)는 자기 코팅으로 회전하는 금속 플래터를 사용하는 데이터 저장 장치입니다.



 a| 
핫 스페어 드라이브
 a| 
핫 스페어는 RAID 1, RAID 5 또는 RAID 6 볼륨 그룹의 대기 드라이브 역할을 합니다. 데이터가 없는 완전한 기능을 갖춘 드라이브입니다. 볼륨 그룹에서 드라이브에 장애가 발생하면 컨트롤러는 장애가 발생한 드라이브에서 핫 스페어로 데이터를 자동으로 재구성합니다.



 a| 
NVMe를 참조하십시오
 a| 
NVMe(비휘발성 메모리 익스프레스)는 SSD 드라이브와 같은 플래시 기반 스토리지 장치를 위해 설계된 인터페이스입니다. NVMe는 이전 논리 장치 인터페이스와 비교하여 I/O 오버헤드를 줄이고 성능 개선을 포함합니다.



 a| 
SAS를 참조하십시오
 a| 
SAS(Serial Attached SCSI)는 컨트롤러를 디스크 드라이브에 직접 연결하는 지점 간 직렬 프로토콜입니다.



 a| 
보안 지원 드라이브
 a| 
보안이 가능한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있으며, 이 드라이브는 쓰기 중에 데이터를 암호화하고 읽기 중에 데이터를 해독합니다. 이러한 드라이브는 드라이브 보안 기능을 사용하여 추가 보안을 위해 사용할 수 있으므로 보안 -_가능_으로 간주됩니다. 드라이브 보안 기능이 이러한 드라이브에 사용된 볼륨 그룹 및 풀에 대해 활성화된 경우 드라이브는 secure-_enabled_가 됩니다.



 a| 
보안 지원 드라이브
 a| 
보안 지원 드라이브는 드라이브 보안 기능과 함께 사용됩니다. 드라이브 보안 기능을 활성화한 다음 보안 -_가능_ 드라이브의 풀 또는 볼륨 그룹에 드라이브 보안을 적용하면 드라이브는 보안__- 사용__ 상태가 됩니다. 읽기 및 쓰기 액세스는 올바른 보안 키로 구성된 컨트롤러를 통해서만 사용할 수 있습니다. 이렇게 추가된 보안으로 인해 스토리지 어레이에서 물리적으로 제거된 드라이브의 데이터에 대한 무단 액세스가 방지됩니다.



 a| 
SSD를 지원합니다
 a| 
SSD(Solid-State Disk)는 데이터를 영구적으로 저장하기 위해 솔리드 스테이트 메모리(플래시)를 사용하는 데이터 스토리지 장치입니다. SSD는 기존의 하드 드라이브를 에뮬레이트하며 하드 드라이브에서 사용하는 것과 동일한 인터페이스로 사용할 수 있습니다.

|===
====
.iSCSI 용어:
[%collapsible]
====
[cols="25h,~"]
|===
| 기간 | 설명 


 a| 
CHAP
 a| 
CHAP(Challenge Handshake Authentication Protocol) 메서드는 초기 링크 중에 대상 및 이니시에이터의 ID를 확인합니다. 인증은 CHAP__secret__이라는 공유 보안 키를 기반으로 합니다.



 a| 
컨트롤러
 a| 
컨트롤러는 보드, 펌웨어 및 소프트웨어로 구성됩니다. 드라이브를 제어하고 System Manager 기능을 구현합니다.



 a| 
DHCP를 선택합니다
 a| 
DHCP(Dynamic Host Configuration Protocol)는 IP 주소와 같은 네트워크 구성 매개 변수를 동적으로 배포하기 위해 IP(인터넷 프로토콜) 네트워크에서 사용되는 프로토콜입니다.



 a| 
IB
 a| 
IB(InfiniBand)는 고성능 서버와 스토리지 시스템 간의 데이터 전송을 위한 통신 표준입니다.



 a| 
ICMP ping 응답
 a| 
ICMP(Internet Control Message Protocol)는 네트워크 컴퓨터의 운영 체제에서 메시지를 보내는 데 사용되는 프로토콜입니다. ICMP 메시지는 호스트에 연결할 수 있는지 여부와 해당 호스트와 패킷을 주고 받는 데 걸리는 시간을 결정합니다.



 a| 
IQN을 선택합니다
 a| 
IQN(iSCSI Qualified Name) 식별자는 iSCSI 이니시에이터 또는 iSCSI 타겟의 고유한 이름입니다.



 a| 
iSER
 a| 
iSER(iSCSI Extensions for RDMA)은 InfiniBand 또는 이더넷과 같은 RDMA 전송을 통해 작동하는 iSCSI 프로토콜을 확장하는 프로토콜입니다.



 a| 
iSNS를 선택합니다
 a| 
iSNS(Internet Storage Name Service)는 TCP/IP 네트워크에서 iSCSI 및 Fibre Channel 디바이스를 자동으로 검색, 관리 및 구성할 수 있는 프로토콜입니다.



 a| 
MAC 주소
 a| 
MAC 주소(Media Access Control Identifier)는 동일한 물리적 전송 네트워크 인터페이스의 두 포트를 연결하는 별도의 논리 채널을 구분하기 위해 이더넷에서 사용됩니다.



 a| 
관리 클라이언트
 a| 
관리 클라이언트는 System Manager 액세스를 위해 브라우저가 설치된 컴퓨터입니다.



 a| 
MTU
 a| 
MTU(Maximum Transmission Unit)는 네트워크에서 전송할 수 있는 가장 큰 크기의 패킷 또는 프레임입니다.



 a| 
RDMA 를 참조하십시오
 a| 
RDMA(Remote Direct Memory Access)는 네트워크 컴퓨터가 두 컴퓨터의 운영 체제와 관계없이 주 메모리에서 데이터를 교환할 수 있도록 하는 기술입니다.



 a| 
명명되지 않은 검색 세션
 a| 
명명되지 않은 검색 세션 옵션이 활성화된 경우 iSCSI 초기자는 컨트롤러의 정보를 검색하기 위해 타겟 IQN을 지정할 필요가 없습니다.

|===
====
.NVMe 용어:
[%collapsible]
====
[cols="25h,~"]
|===
| 기간 | 설명 


 a| 
InfiniBand
 a| 
IB(InfiniBand)는 고성능 서버와 스토리지 시스템 간의 데이터 전송을 위한 통신 표준입니다.



 a| 
네임스페이스
 a| 
네임스페이스는 블록 액세스를 위해 포맷된 NVM 스토리지입니다. 스토리지 배열의 볼륨과 관련된 SCSI의 논리 유닛과 유사합니다.



 a| 
네임스페이스 ID입니다
 a| 
네임스페이스 ID는 네임스페이스에 대한 NVMe 컨트롤러의 고유 식별자이며 1에서 255 사이의 값으로 설정할 수 있습니다. SCSI의 LUN(Logical Unit Number)과 유사합니다.



 a| 
NQN
 a| 
NVMe 정규화된 이름(NQN)은 원격 스토리지 대상(스토리지 어레이)을 식별하는 데 사용됩니다.



 a| 
NVM
 a| 
NVM(비휘발성 메모리)은 다양한 유형의 스토리지 장치에서 사용되는 영구 메모리입니다.



 a| 
NVMe를 참조하십시오
 a| 
NVMe(비휘발성 메모리 익스프레스)는 SSD 드라이브와 같은 플래시 기반 스토리지 장치를 위해 설계된 인터페이스입니다. NVMe는 이전 논리 장치 인터페이스와 비교하여 I/O 오버헤드를 줄이고 성능 개선을 포함합니다.



 a| 
NVMe - oF
 a| 
NVMe-oF(Non-Volatile Memory Express over Fabrics)는 NVMe 명령 및 데이터가 호스트와 스토리지 간의 네트워크를 통해 전송되도록 하는 사양입니다.



 a| 
NVMe 컨트롤러
 a| 
호스트 연결 프로세스 중에 NVMe 컨트롤러가 생성됩니다. 스토리지 배열의 네임스페이스와 호스트 간의 액세스 경로를 제공합니다.



 a| 
NVMe 전담팀
 a| 
큐는 NVMe 인터페이스를 통해 명령 및 메시지를 전달하는 데 사용됩니다.



 a| 
NVMe 하위 시스템
 a| 
NVMe 호스트 연결이 있는 스토리지 어레이



 a| 
RDMA 를 참조하십시오
 a| 
RDMA(Remote Direct Memory Access)를 사용하면 네트워크 인터페이스 카드(NIC) 하드웨어에 전송 프로토콜을 구현하여 서버 내외부로 데이터를 더욱 직접 이동할 수 있습니다.



 a| 
RoCE
 a| 
RoCE(RDMA over Converged Ethernet)는 이더넷 네트워크를 통한 RDMA(Remote Direct Memory Access)를 지원하는 네트워크 프로토콜입니다.



 a| 
SSD를 지원합니다
 a| 
SSD(Solid-State Disk)는 데이터를 영구적으로 저장하기 위해 솔리드 스테이트 메모리(플래시)를 사용하는 데이터 스토리지 장치입니다. SSD는 기존의 하드 드라이브를 에뮬레이트하며 하드 드라이브에서 사용하는 것과 동일한 인터페이스로 사용할 수 있습니다.

|===
====