---
permalink: sm-hardware/hardware-page-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hardware, page, components, 
summary: 하드웨어 페이지에서는 스토리지 배열의 물리적 구성 요소를 그래픽으로 보여 줍니다. 여기에서 구성 요소 상태를 확인하고 이러한 구성 요소와 관련된 일부 기능을 수행할 수 있습니다. 
---
= 하드웨어 페이지 및 구성 요소
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
하드웨어 페이지에서는 스토리지 시스템의 물리적 구성 요소를 그래픽으로 보여 줍니다. 여기에서 구성 요소 상태를 확인하고 이러한 구성 요소와 관련된 일부 기능을 수행할 수 있습니다.



== 쉘프

쉘프는 스토리지 어레이(컨트롤러, 전원/팬 캐니스터 및 드라이브)용 하드웨어를 포함하는 구성 요소입니다. 쉘프는 다음과 같은 두 가지 유형이 있습니다.

* * 컨트롤러 쉘프 * -- 드라이브, 전원/팬 캐니스터 및 컨트롤러를 포함합니다.
* * 드라이브 쉘프 * (또는 * 확장 쉘프 *) -- 드라이브, 전원/팬 캐니스터, 2개의 I/O 모듈(IOM)이 포함됩니다. ESM(환경 서비스 모듈(ESM)에는 드라이브 쉘프를 컨트롤러 쉘프에 연결하는 SAS 포트가 포함되어 있습니다.


쉘프는 최대 12, 24 또는 60개의 드라이브를 수용할 수 있도록 3가지 크기로 제공됩니다. 각 쉘프는 컨트롤러 펌웨어에 의해 할당된 ID 번호를 포함합니다. 쉘프 보기의 좌측 상단에 ID가 나타납니다.

하드웨어 페이지의 쉘프 보기에는 앞면 또는 뒷면 구성 요소가 표시됩니다. 쉘프 보기의 오른쪽 상단에서 * Drives * 또는 * Controller * 탭을 선택하여 두 보기 사이를 전환할 수 있습니다. 페이지 하단에서 * Show all front * 또는 * Show all back * 을 선택할 수도 있습니다. 전면 및 후면 뷰는 다음을 나타냅니다.

* * 전면 구성요소 * -- 드라이브 및 빈 드라이브 베이.
* * 후면 구성요소 * -- 컨트롤러, 전원/팬 캐니스터(컨트롤러 쉘프용) 또는 IOM 및 전원/팬 캐니스터(드라이브 쉘프용)


쉘프와 관련하여 다음 기능을 수행할 수 있습니다.

* 선반 위치 표시등을 켜서 캐비닛이나 랙에서 선반의 물리적 위치를 찾을 수 있도록 합니다.
* 쉘프 보기의 좌측 상단에 표시된 ID 번호를 변경합니다.
* 설치된 드라이브 유형 및 일련 번호와 같은 쉘프 설정을 확인합니다.
* 스토리지 배열의 물리적 레이아웃과 일치하도록 쉘프 보기를 위 또는 아래로 이동합니다.




== 컨트롤러

컨트롤러는 스토리지 배열 및 관리 기능을 구현하는 결합된 하드웨어 및 펌웨어입니다. 여기에는 캐시 메모리, 드라이브 지원 및 호스트 인터페이스 지원이 포함됩니다.

컨트롤러와 관련된 다음 기능을 수행할 수 있습니다.

* IP 주소 및 속도에 대한 관리 포트를 구성합니다.
* iSCSI 호스트 접속을 구성합니다(iSCSI 호스트가 있는 경우).
* NTP(Network Time Protocol) 서버 및 DNS(Domain Name System) 서버를 구성합니다.
* 컨트롤러 상태 및 설정을 봅니다.
* 로컬 영역 네트워크 외부의 사용자가 SSH 세션을 시작하고 컨트롤러의 설정을 변경할 수 있도록 합니다.
* 컨트롤러를 오프라인, 온라인 또는 서비스 모드로 전환합니다.




== 드라이브

스토리지 어레이에는 HDD(하드 디스크 드라이브) 또는 SSD(Solid State Drive)가 포함될 수 있습니다. 쉘프 크기에 따라 최대 12, 24 또는 60개의 드라이브를 쉘프에 설치할 수 있습니다.

드라이브와 관련된 다음 기능을 수행할 수 있습니다.

* 드라이브 로케이터 표시등을 켜서 쉘프에 있는 드라이브의 물리적 위치를 찾을 수 있습니다.
* 드라이브 상태 및 설정을 봅니다.
* 드라이브를 다시 할당하고(장애가 발생한 드라이브를 할당되지 않은 드라이브로 논리적으로 교체) 필요한 경우 드라이브를 수동으로 재구성합니다.
* 드라이브를 수동으로 실패하여 교체할 수 있습니다. (드라이브에 결함이 있으면 드라이브를 교체하기 전에 드라이브의 내용을 복사할 수 있습니다.)
* 핫 스페어 할당 또는 할당 취소
* 드라이브를 지웁니다.

