---
permalink: sm-hardware/hot-spare-drives.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hot, spare, drives, raid1, raid6, raid5 
summary: 핫 스페어는 System Manager의 RAID 1, RAID 5 또는 RAID 6 볼륨 그룹에서 대기 드라이브 역할을 합니다. 
---
= 핫 스페어 드라이브 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
핫 스페어는 System Manager의 RAID 1, RAID 5 또는 RAID 6 볼륨 그룹에서 대기 드라이브 역할을 합니다.

데이터가 없는 완전한 기능을 갖춘 드라이브입니다. 볼륨 그룹에서 드라이브에 장애가 발생하면 컨트롤러는 장애가 발생한 드라이브에서 핫 스페어로 할당된 드라이브로 데이터를 자동으로 재구성합니다.

핫 스페어는 특정 볼륨 그룹 전용이 아닙니다. 핫 스페어와 드라이브가 다음 속성을 공유하는 한 스토리지 배열의 모든 장애 드라이브에 사용할 수 있습니다.

* 동일한 용량(또는 핫 스페어의 더 큰 용량)
* 동일한 미디어 유형(예: HDD 또는 SSD)
* 동일한 인터페이스 유형(예: SAS)




== 핫 스페어 식별 방법

초기 설치 마법사 또는 하드웨어 페이지에서 핫 스페어를 할당할 수 있습니다. 핫 스페어가 할당되었는지 확인하려면 하드웨어 페이지로 이동하여 분홍색으로 표시된 드라이브 베이를 찾습니다.



== 핫 스페어 적용 범위

핫 스페어 범위는 다음과 같습니다.

* 할당되지 않은 드라이브는 RAID 1, RAID 5 또는 RAID 6 볼륨 그룹의 핫 스페어로 예약됩니다.
+
[NOTE]
====
핫 스페어는 데이터 보호 방법이 다른 풀에 사용할 수 없습니다. 풀은 추가 드라이브를 예약하지 않고 풀의 각 드라이브에 예비 용량(_preservation capacity_)을 예약합니다. 풀에서 드라이브에 장애가 발생할 경우 컨트롤러는 해당 여유 용량으로 데이터를 재구성합니다.

====
* RAID 1, RAID 5 또는 RAID 6 볼륨 그룹 내의 드라이브에 장애가 발생하면 컨트롤러는 자동으로 중복 데이터를 사용하여 오류가 발생한 드라이브의 데이터를 재구성합니다. 핫 스페어는 물리적 스왑 없이 장애가 발생한 드라이브를 자동으로 대체합니다.
* 장애가 발생한 드라이브를 물리적으로 교체한 경우, 핫 스페어 드라이브에서 교체한 드라이브로 데이터를 재복사하는 작업이 수행됩니다. 핫 스페어 드라이브를 볼륨 그룹의 영구 구성원으로 지정한 경우에는 카피백 작업이 필요하지 않습니다.
* 볼륨 그룹에 대한 트레이 손실 방지 및 드로어 손실 보호는 볼륨 그룹을 구성하는 드라이브의 위치에 따라 달라집니다. 드라이브 장애 및 핫 스페어 드라이브의 위치 때문에 트레이 손실 방지 및 드로어 손실 보호가 손실될 수 있습니다. 트레이 손실 방지 및 서랍 손실 보호가 영향을 받지 않도록 하려면, 카피백 프로세스를 시작하기 위해 고장난 드라이브를 교체해야 합니다.
* 핫 스페어 드라이브가 장애가 발생한 드라이브로 자동 대체되기 때문에 스토리지 어레이 볼륨은 장애가 발생한 드라이브를 교체하는 동안 온라인 상태로 유지되고 액세스할 수 있습니다.




== 핫 스페어 드라이브 용량에 대한 고려 사항

보호하려는 드라이브의 총 용량과 같거나 더 큰 용량의 드라이브를 선택합니다. 예를 들어, 18GiB 드라이브의 용량이 8GiB인 경우 9GiB 이상의 드라이브를 핫 스페어로 사용할 수 있습니다. 일반적으로 스토리지 어레이에서 가장 큰 드라이브의 용량과 같거나 큰 용량이 아니면 드라이브를 핫 스페어로 할당하지 마십시오.

[NOTE]
====
물리적 용량이 동일한 핫 스페어를 사용할 수 없는 경우 드라이브의 "사용된 용량"이 핫 스페어 드라이브의 용량보다 작거나 같은 경우 용량이 낮은 드라이브를 핫 스페어로 사용할 수 있습니다.

====


== 미디어 및 인터페이스 유형에 대한 고려 사항

핫 스페어로 사용되는 드라이브는 보호할 드라이브와 동일한 미디어 유형 및 인터페이스 유형을 공유해야 합니다. 예를 들어, HDD 드라이브는 SSD 드라이브의 핫 스페어로 사용할 수 없습니다.



== 보안 가능 드라이브에 대한 고려 사항

FDE 또는 FIPS와 같은 보안 지원 드라이브는 보안 기능이 있거나 없는 드라이브의 핫 스페어로 사용할 수 있습니다. 그러나 보안이 가능하지 않은 드라이브는 보안 기능이 있는 드라이브의 핫 스페어로 사용할 수 없습니다.

핫 스페어에 사용할 보안 지원 드라이브를 선택하면 System Manager에서 보안 지우기를 수행하라는 메시지를 표시합니다. Secure Erase는 드라이브의 보안 속성을 보안 가능 상태로 재설정하지만 보안 사용 가능으로 다시 설정합니다.

[NOTE]
====
드라이브 보안 기능을 활성화한 다음 보안 가능 드라이브에서 풀 또는 볼륨 그룹을 생성하면 해당 드라이브는 _secure-enabled_가 됩니다. 읽기 및 쓰기 액세스는 올바른 보안 키로 구성된 컨트롤러를 통해서만 사용할 수 있습니다. 이렇게 추가된 보안으로 인해 스토리지 어레이에서 물리적으로 제거된 드라이브의 데이터에 대한 무단 액세스가 방지됩니다.

====


== 권장되는 핫 스페어 드라이브 수입니다

초기 설정 마법사를 사용하여 핫 스페어를 자동으로 생성한 경우 System Manager에서는 특정 미디어 유형 및 인터페이스 유형의 드라이브 30개마다 핫 스페어 하나를 생성합니다. 그렇지 않으면 스토리지 배열의 볼륨 그룹 간에 핫 스페어 드라이브를 수동으로 생성할 수 있습니다.
