---
permalink: sm-hardware/limit-the-drive-view.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, limit, drive, view, 
summary: '스토리지 배열에 서로 다른 유형의 물리적 및 논리적 속성이 있는 드라이브가 포함되어 있는 경우 Hardware(하드웨어) 페이지에서는 드라이브 보기를 제한하고 특정 드라이브를 찾는 데 도움이 되는 필터 필드를 제공합니다.' 
---
= 드라이브 보기를 제한합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 배열에 서로 다른 유형의 물리적 및 논리적 속성이 있는 드라이브가 포함되어 있는 경우 Hardware(하드웨어) 페이지에서는 드라이브 보기를 제한하고 특정 드라이브를 찾는 데 도움이 되는 필터 필드를 제공합니다.

.이 작업에 대해
드라이브 필터는 특정 논리적 위치(예: 볼륨 그룹 1)에서 특정 보안 속성(예: 보안 가능)을 가진 특정 유형의 물리적 드라이브(예: 모든 SAS)로만 보기를 제한할 수 있습니다. 이러한 필터를 함께 또는 별도로 사용할 수 있습니다.

[NOTE]
====
모든 드라이브가 동일한 물리적 속성을 공유하는 경우 * Show drives that are... * filter 필드가 나타나지 않습니다. 모든 드라이브가 동일한 논리 속성을 공유하는 경우 스토리지 배열 * 필터 필드의 * 아무 곳이나 나타나지 않습니다.

====
.단계
. 하드웨어 * 를 선택합니다.
. 첫 번째 필터 필드(* Show drives that are... * 아래)에서 드롭다운 화살표를 클릭하여 사용 가능한 드라이브 유형 및 보안 속성을 표시합니다.
+
드라이브 유형은 다음과 같습니다.

+
** 드라이브 미디어 유형(SSD, HDD)
** 드라이브 인터페이스 유형입니다
** 드라이브 용량(최고 - 최저)
** 드라이브 속도(최고 ~ 최저) 보안 속성에는 다음이 포함될 수 있습니다.
** 보안 가능
** 보안이 설정되었습니다
** DA(Data Assurance) 가능
** FIPS 규격
** FIPS 규격(FIPS 140-2)
** FIPS 규격(FIPS 140-3)
+
이러한 속성이 모든 드라이브에서 동일한 경우 드롭다운 목록에 표시되지 않습니다. 예를 들어, 스토리지 어레이에 SAS 인터페이스 및 15000RPM의 속도가 포함된 모든 SSD 드라이브가 포함되어 있지만 일부 SSD의 용량이 서로 다른 경우, 드롭다운 목록에는 필터링 선택 항목으로서 용량만 표시됩니다.

+
필드에서 옵션을 선택하면 필터 기준과 일치하지 않는 드라이브가 그래픽 보기에서 회색으로 표시됩니다.



. 두 번째 필터 상자에서 드롭다운 화살표를 클릭하여 드라이브의 사용 가능한 논리 위치를 표시합니다.
+
[NOTE]
====
필터 기준을 지우려면 필터 상자 오른쪽 끝에 있는 * Clear * 를 선택합니다.

====
+
논리 위치는 다음과 같습니다.

+
** 풀
** 볼륨 그룹
** 핫 스페어
** SSD 캐시
** 할당되지 않음
+
필드에서 옵션을 선택하면 필터 기준과 일치하지 않는 드라이브가 그래픽 보기에서 회색으로 표시됩니다.



. 선택적으로 필터 필드 맨 오른쪽에 있는 * 로케이터 라이트 켜기 * 를 선택하여 표시된 드라이브의 로케이터 라이트를 켤 수 있습니다.
+
이렇게 하면 스토리지 배열에서 드라이브를 물리적으로 찾을 수 있습니다.


