---
permalink: sm-hardware/replace-drive-logically-hardware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, replace, drive, logically, 
summary: 드라이브에 장애가 발생하거나 다른 이유로 드라이브를 교체하고 스토리지 어레이에 할당되지 않은 드라이브가 있는 경우, 장애가 발생한 드라이브를 할당되지 않은 드라이브로 논리적으로 교체할 수 있습니다. 할당되지 않은 드라이브가 없는 경우 드라이브를 물리적으로 교체할 수 있습니다. 
---
= 드라이브를 논리적으로 교체합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
드라이브에 장애가 발생하거나 다른 이유로 인해 드라이브를 교체하려는 경우, 장애가 발생한 드라이브를 할당되지 않은 드라이브 또는 완전히 통합된 핫 스페어로 논리적으로 교체할 수 있습니다.

.이 작업에 대해
드라이브를 논리적으로 교체하면 드라이브가 할당되고 연결된 풀 또는 볼륨 그룹의 영구 구성원이 됩니다.

논리 교체 옵션을 사용하여 다음 유형의 드라이브를 교체할 수 있습니다.

* 오류가 발생한 드라이브
* 드라이브가 없습니다
* Recovery Guru에서 SSD 드라이브의 수명이 거의 다 되었음을 알립니다
* Recovery Guru에서 드라이브 오류가 임박한 것으로 통보한 하드 드라이브입니다
* 할당된 드라이브(풀이 아닌 볼륨 그룹의 드라이브에 대해서만 사용 가능)


.시작하기 전에
교체 드라이브의 특징은 다음과 같습니다.

* 최적 상태
* 할당되지 않음 상태
* 교체할 드라이브와 동일한 속성(미디어 유형, 인터페이스 유형 등)
* 동일한 FDE 기능(권장, 필수 아님)
* 동일한 DA 기능(권장, 필수 아님)


.단계
. 하드웨어 * 를 선택합니다.
. 그림에 컨트롤러가 표시되면 * Drives * 탭을 클릭합니다.
+
그래픽이 변경되어 컨트롤러 대신 드라이브가 표시됩니다.

. 논리적으로 교체할 드라이브를 클릭합니다.
+
드라이브의 컨텍스트 메뉴가 나타납니다.

. 논리적으로 바꾸기 * 를 클릭합니다.
. * 선택 사항: * 교체 후 * 실패 드라이브 * 확인란을 선택하여 교체 후 원래 드라이브에 장애가 발생합니다.
+
이 확인란은 원래 할당된 드라이브가 실패했거나 누락되지 않은 경우에만 활성화됩니다.

. Select a replacement drive* 표에서 사용할 교체 드라이브를 선택합니다.
+
이 표에는 교체하려는 드라이브와 호환되는 드라이브만 나열되어 있습니다. 가능한 경우 쉘프 손실 방지 및 드로어 손실 방지 기능을 유지하는 드라이브를 선택합니다.

. 바꾸기 * 를 클릭합니다.
+
원래 드라이브에 오류가 발생하거나 누락된 경우 패리티 정보를 사용하여 교체 드라이브에서 데이터가 재구성됩니다. 이 재구성이 자동으로 시작됩니다. 드라이브 장애 표시등이 꺼지고 풀 또는 볼륨 그룹의 드라이브 작동 표시등이 깜박이기 시작합니다.

+
원본 드라이브에 오류가 발생하거나 누락된 경우 해당 데이터가 교체 드라이브로 복사됩니다. 이 복사 작업은 자동으로 시작됩니다. 복사 작업이 완료되면 시스템은 원래 드라이브를 할당되지 않은 상태로 전환하거나 이 확인란을 선택한 경우 실패 상태로 전환합니다.


