---
permalink: sm-hardware/unlock-or-reset-a-locked-nvme-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, unlock, reset, locked, fips, nvme, drives, 
summary: '하나 이상의 잠긴 NVMe 또는 FIPS 드라이브를 스토리지 어레이에 삽입하면 드라이브와 연결된 보안 키 파일을 추가하여 드라이브 데이터의 잠금을 해제할 수 있습니다. 보안 키가 없는 경우 PSID(Physical Security ID)를 입력하여 잠긴 각 드라이브에서 재설정을 수행하여 보안 속성을 재설정하고 드라이브 데이터를 지울 수 있습니다.' 
---
= SANtricity System Manager에서 잠긴 NVMe 또는 FIPS 드라이브 잠금 해제 또는 재설정
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
하나 이상의 잠긴 NVMe 또는 FIPS 드라이브를 스토리지 어레이에 삽입하면 드라이브와 연결된 보안 키 파일을 추가하여 드라이브 데이터의 잠금을 해제할 수 있습니다. 보안 키가 없는 경우 PSID(Physical Security ID)를 입력하여 잠긴 각 드라이브에서 재설정을 수행하여 보안 속성을 재설정하고 드라이브 데이터를 지울 수 있습니다.

.시작하기 전에
* 잠금 해제 옵션을 사용하려면 보안 키 파일(확장자가 `.slk`인 파일)이 관리 클라이언트(System Manager에 액세스하는 데 사용되는 브라우저가 있는 시스템)에서 사용 가능한지 확인하십시오. 또한 키와 관련된 암호를 알고 있어야 합니다.
* 재설정 옵션의 경우 재설정할 각 드라이브에서 PSID를 찾아야 합니다. PSID를 찾으려면 드라이브를 물리적으로 분리하고 드라이브 레이블에서 PSID 문자열(최대 32자)을 찾은 다음 드라이브를 다시 설치합니다.


.이 작업에 대해
이 작업에서는 보안 키 파일을 스토리지 어레이로 가져와서 NVMe 또는 FIPS 드라이브에서 데이터를 잠금 해제하는 방법을 설명합니다. 보안 키를 사용할 수 없는 경우 이 작업에서는 잠긴 드라이브에서 재설정을 수행하는 방법도 설명합니다.

[NOTE]
====
외부 키 관리 서버를 사용하여 드라이브가 잠겨 있는 경우 System Manager에서 menu:System[Security key management]를 선택하여 외부 키 관리를 구성하고 드라이브의 잠금을 해제하십시오.

====
하드웨어 페이지 또는 menu:System[Security key management]에서 잠금 해제 기능에 접근할 수 있습니다. 아래 작업은 하드웨어 페이지에서 접근하는 방법을 설명합니다.

.단계
. 왼쪽 패널에서 menu:Hardware[Drives]를 선택합니다.
. 잠금 해제 또는 재설정할 NVMe 또는 FIPS 드라이브를 선택합니다.
+
드라이브의 컨텍스트 메뉴가 열립니다.

. 보안 키 파일을 적용하려면 * 잠금 해제 * 를 선택하고, 보안 키 파일이 없으면 * 재설정 * 을 선택합니다.
+
이러한 옵션은 잠긴 NVMe 또는 FIPS 드라이브를 선택한 경우에만 표시됩니다.

+
[CAUTION]
====
재설정 작업 중에는 모든 데이터가 삭제됩니다. 보안 키가 없는 경우에만 재설정을 수행하십시오. 잠긴 드라이브를 재설정하면 드라이브의 모든 데이터가 영구적으로 제거되고 보안 속성이 "보안 가능"으로 재설정되지만 활성화되지는 않습니다. * 이 작업은 되돌릴 수 없습니다. *

====
. 다음 중 하나를 수행합니다.
+
.. *잠금 해제*: *보안 드라이브 잠금 해제* 페이지에서 잠금 해제하려는 드라이브에 해당하는 보안 키 파일을 선택합니다. 그런 다음 암호를 입력하고 *잠금 해제*를 클릭합니다.
.. *재설정*: *잠긴 드라이브 재설정* 대화 상자에서 PSID 문자열을 필드에 입력한 다음  `RESET`을 입력하여 확인합니다. *재설정*을 클릭합니다.
+
잠금 해제 작업의 경우 이 작업을 한 번만 수행하면 모든 NVMe 또는 FIPS 드라이브를 잠금 해제할 수 있습니다. 재설정 작업의 경우 재설정할 각 드라이브를 개별적으로 선택해야 합니다.





.결과
이제 드라이브를 다른 볼륨 그룹 또는 디스크 풀 또는 다른 스토리지 어레이에서 사용할 수 있습니다.
