---
permalink: sm-hardware/view-controller-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, controller, settings 
summary: 호스트 인터페이스, 드라이브 인터페이스 및 관리 포트의 상태와 같은 컨트롤러에 대한 정보를 볼 수 있습니다. 
---
= SANtricity System Manager에서 컨트롤러 설정 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트 인터페이스, 드라이브 인터페이스 및 관리 포트의 상태와 같은 컨트롤러에 대한 정보를 볼 수 있습니다.

.단계
. 왼쪽 패널에서 menu:Hardware[Controllers and components]를 선택합니다.
. 다음 작업 중 하나를 수행하여 컨트롤러 설정을 표시합니다.
+
** 컨트롤러를 클릭하여 컨텍스트 메뉴를 표시한 다음 * 설정 보기 * 를 선택합니다.
** 컨트롤러 아이콘(* Shelf* 드롭다운 목록 옆에 있음)을 선택합니다. 이중 구성의 경우, 대화 상자에서 * 컨트롤러 A * 또는 * 컨트롤러 B * 를 선택한 후 * 다음 * 을 클릭합니다.
+
컨트롤러 설정 슬라이딩 메뉴가 열립니다.



. 섹션을 검토하여 컨트롤러 속성 설정 간에 이동합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 섹션을 참조하십시오 | 설명 


 a| 
세부 정보
 a| 
컨트롤러 상태, 날짜/시간, 모델명 및 교체 부품 번호를 표시합니다.



 a| 
현재 구성
 a| 
현재 펌웨어 버전과 NVRAM 버전을 표시합니다.



 a| 
데이터 캐시
 a| 
데이터 캐시 총계를 보여줍니다.



 a| 
데이터 캐시 모듈
 a| 
캐시 모듈의 위치, 상태 및 용량을 표시합니다.



 a| 
프로세서 캐시
 a| 
프로세서 캐시 총량을 보여줍니다.



 a| 
캐시 백업 장치
 a| 
캐시 백업 장치의 위치, 상태 및 용량을 표시합니다.



 a| 
호스트 인터페이스
 a| 
각 포트에 대한 호스트 인터페이스 정보와 링크 상태를 표시합니다.



 a| 
드라이브 인터페이스
 a| 
각 포트에 대한 드라이브 인터페이스 정보와 링크 상태를 표시합니다.



 a| 
관리 포트 설정
 a| 
컨트롤러 호스트 이름, 원격 로그인 및 IP 네트워크 설정을 포함한 관리 포트 세부 정보를 표시합니다.



 a| 
도메인 이름 시스템(DNS) 서버 설정
 a| 
DNS 구성, 기본 DNS 서버 및 백업 DNS 서버를 표시합니다.



 a| 
네트워크 시간 프로토콜(NTP) 서버 설정
 a| 
NTP 서비스 및 NTP 서버 구성 세부 정보를 표시합니다.

|===
====
. 닫기 * 를 클릭합니다.

