---
permalink: sm-hardware/view-drive-status-and-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, drive, status, settings, media, 
summary: 미디어 유형, 인터페이스 유형, 용량 등 드라이브의 상태와 설정을 볼 수 있습니다. 
---
= 드라이브 상태 및 설정을 봅니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
미디어 유형, 인터페이스 유형, 용량 등 드라이브의 상태와 설정을 볼 수 있습니다.

.단계
. 하드웨어 * 를 선택합니다.
. 그래픽에 컨트롤러가 표시되면 * 쉘프 전면 표시 * 를 클릭합니다.
+
그래픽이 변경되어 컨트롤러 대신 드라이브가 표시됩니다.

. 상태 및 설정을 보려는 드라이브를 선택합니다.
+
드라이브의 컨텍스트 메뉴가 열립니다.

. 설정 보기 * 를 선택합니다.
+
드라이브 설정 대화 상자가 열립니다.

. 모든 설정을 보려면 대화 상자 오른쪽 위에 있는 * 더 많은 설정 표시 * 를 클릭합니다.
+
.필드 상세정보
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
상태
 a| 
최적, 오프라인, 중요하지 않은 오류 및 실패를 표시합니다. 최적 상태는 원하는 작동 상태를 나타냅니다.



 a| 
모드를 선택합니다
 a| 
Assigned, Unassigned, Hot Spare Standby 또는 Hot Spare 사용 중 을 표시합니다.



 a| 
위치
 a| 
에서는 드라이브가 위치한 쉘프 및 베이 번호를 보여 줍니다.



 a| 
보호 대상/보호 대상/보호 가능
 a| 
드라이브가 풀, 볼륨 그룹 또는 SSD 캐시에 할당된 경우 이 필드에 "할당됨"이 표시됩니다. 풀 이름, 볼륨 그룹 이름 또는 SSD 캐시 이름을 사용할 수 있습니다. 드라이브가 핫 스페어에 할당되고 해당 모드가 대기 모드인 경우 이 필드에 "보호 가능"이 표시됩니다. 핫 스페어가 하나 이상의 볼륨 그룹을 보호할 수 있는 경우 볼륨 그룹 이름이 나타납니다. 볼륨 그룹을 보호할 수 없는 경우 0개의 볼륨 그룹이 표시됩니다.

드라이브가 핫 스페어에 할당되고 해당 모드가 사용 중인 경우 이 필드에 "보호 중"이 표시됩니다. 값은 영향을 받는 볼륨 그룹의 이름입니다.

드라이브를 지정하지 않으면 이 필드가 나타나지 않습니다.



 a| 
미디어 유형
 a| 
하드 디스크 드라이브(HDD) 또는 솔리드 스테이트 디스크(SSD)일 수 있는 드라이브에서 사용하는 레코딩 미디어의 유형을 표시합니다.



 a| 
사용된 내구성(SSD 드라이브가 있는 경우에만 표시됨)
 a| 
현재까지 드라이브에 기록된 데이터의 양을 이론적인 총 쓰기 한계로 나눈 값입니다.



 a| 
인터페이스 유형입니다
 a| 
SAS와 같이 드라이브에서 사용하는 인터페이스 유형을 표시합니다.



 a| 
드라이브 경로 이중화
 a| 
드라이브와 컨트롤러 사이의 연결이 중복되었는지(예) 여부를 표시합니다(아니요).



 a| 
용량(GiB)
 a| 
드라이브의 가용 용량(구성된 총 용량)을 표시합니다.



 a| 
속도(RPM)
 a| 
RPM으로 속도를 표시합니다(SSD의 경우 표시되지 않음).



 a| 
현재 데이터 속도입니다
 a| 
드라이브와 스토리지 어레이 간의 데이터 전송 속도를 표시합니다.



 a| 
논리 섹터 크기(바이트)
 a| 
드라이브가 사용하는 논리 섹터 크기를 표시합니다.



 a| 
물리적 섹터 크기(바이트)
 a| 
드라이브가 사용하는 물리적 섹터 크기를 표시합니다. 일반적으로 물리적 섹터 크기는 하드 디스크 드라이브의 경우 4096바이트입니다.



 a| 
드라이브 펌웨어 버전입니다
 a| 
드라이브 펌웨어의 버전 레벨을 표시합니다.



 a| 
전 세계 식별자
 a| 
드라이브의 고유한 16진수 식별자를 표시합니다.



 a| 
제품 ID
 a| 
제조업체에서 할당한 제품 ID를 표시합니다.



 a| 
일련 번호입니다
 a| 
드라이브의 일련 번호를 표시합니다.



 a| 
제조업체
 a| 
드라이브의 공급업체를 표시합니다.



 a| 
제조 날짜
 a| 
드라이브가 빌드된 날짜를 표시합니다.


NOTE: NVMe 드라이브에는 사용할 수 없습니다.



 a| 
보안 가능
 a| 
드라이브가 안전한지(예) 여부를 표시합니다(아니요). 보안이 가능한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브(레벨 140-2 또는 140-3)일 수 있으며, 이 드라이브는 쓰기 중 데이터를 암호화하고 읽기 중에 데이터를 해독합니다. 이러한 드라이브는 드라이브 보안 기능을 사용하여 추가 보안을 위해 사용할 수 있으므로 보안 -_가능_으로 간주됩니다. 드라이브 보안 기능이 이러한 드라이브에 사용된 볼륨 그룹 및 풀에 대해 활성화된 경우 드라이브는 secure-_enabled_가 됩니다.



 a| 
보안이 설정되었습니다
 a| 
드라이브가 안전한지(예) 여부를 표시합니다(아니요). 보안 지원 드라이브는 드라이브 보안 기능과 함께 사용됩니다. 드라이브 보안 기능을 활성화한 다음 보안 -_가능_드라이브의 풀 또는 볼륨 그룹에 드라이브 보안을 적용하면 드라이브가 보안 -_활성화됨_이 됩니다. 읽기 및 쓰기 액세스는 올바른 보안 키로 구성된 컨트롤러를 통해서만 사용할 수 있습니다. 이렇게 추가된 보안으로 인해 스토리지 어레이에서 물리적으로 제거된 드라이브의 데이터에 대한 무단 액세스가 방지됩니다.



 a| 
읽기/쓰기 액세스가 가능합니다
 a| 
드라이브가 읽기/쓰기 액세스 가능(예) 상태인지 여부(아니요)를 표시합니다.



 a| 
드라이브 보안 키 식별자입니다
 a| 
에는 보안 지원 드라이브의 보안 키가 나와 있습니다. 드라이브 보안은 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브를 통해 추가 보안 계층을 제공하는 스토리지 어레이 기능입니다. 이러한 드라이브를 드라이브 보안 기능과 함께 사용하는 경우 데이터에 액세스하려면 보안 키가 필요합니다. 드라이브가 어레이에서 물리적으로 제거되면 다른 어레이에 설치될 때까지 작동할 수 없으며, 이때 올바른 보안 키가 제공될 때까지 보안 잠금 상태가 됩니다.



 a| 
DA(Data Assurance) 가능
 a| 
DA(Data Assurance) 기능의 사용 여부(예) 또는 사용 안 함(아니요)을 표시합니다. DA(Data Assurance)는 데이터를 컨트롤러를 통해 드라이브로 전송할 때 발생할 수 있는 오류를 확인하고 수정하는 기능입니다. Fibre Channel과 같은 DA 지원 입출력 인터페이스를 사용하는 호스트에서 풀 또는 볼륨 그룹 레벨에서 Data Assurance를 설정할 수 있습니다.



 a| 
DULBE 가능
 a| 
할당 해제 또는 기록되지 않은 논리 블록 오류(DULBE)의 옵션이 사용(예) 또는 사용 안 함(아니요)으로 설정되어 있는지 여부를 나타냅니다. DULBE는 EF300 또는 EF600 스토리지 어레이가 리소스 프로비저닝된 볼륨을 지원할 수 있도록 NVMe 드라이브에 대한 옵션입니다.

|===
====
. 닫기 * 를 클릭합니다.

