---
permalink: sm-hardware/view-hardware-components.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, hardware, components, filtering, 
summary: 하드웨어 페이지에서는 부품을 쉽게 찾을 수 있는 정렬 및 필터링 기능을 제공합니다. 
---
= 하드웨어 구성 요소 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
하드웨어 페이지에서는 부품을 쉽게 찾을 수 있는 정렬 및 필터링 기능을 제공합니다.

.단계
. 하드웨어 * 를 선택합니다.
. 다음 표에 설명된 기능을 사용하여 하드웨어 구성 요소를 봅니다.


[cols="25h,~"]
|===
| 기능 | 설명 


 a| 
드라이브, 컨트롤러 및 구성 요소 보기
 a| 
전면 및 후면 쉘프 보기 사이를 전환하려면 맨 오른쪽에서 * 드라이브 * 또는 * 컨트롤러 및 구성 요소 * 를 선택합니다(현재 보기에 따라 표시되는 링크). Drives* 보기에는 드라이브 및 비어 있는 드라이브 베이가 표시됩니다. 컨트롤러 및 구성요소 * 보기에는 컨트롤러 및 모든 IOM(ESM) 모듈, 전원/팬 캐니스터 또는 빈 컨트롤러 베이가 표시됩니다. 페이지 하단에서 * Show all drives * 를 선택할 수도 있습니다.



 a| 
드라이브 보기 필터
 a| 
스토리지 배열에 다른 유형의 물리적 및 논리적 속성이 있는 드라이브가 포함된 경우 * Hardware * 페이지에는 드라이브 보기 필터가 포함됩니다. 이러한 필터 필드를 사용하면 페이지에 표시되는 드라이브 유형을 제한하여 특정 드라이브를 빠르게 찾을 수 있습니다. Show drives that are... * 에서 왼쪽에 있는 필터 필드(기본적으로 * any drive type * 표시)를 클릭하여 물리적 속성(예: 용량 및 속도)의 드롭다운 목록을 표시합니다. 오른쪽에 있는 필터 필드를 클릭하면(기본적으로 스토리지 배열의 * 아무 곳이나 표시) 논리적 속성(예: 볼륨 그룹 할당)의 드롭다운 목록이 표시됩니다. 이러한 필터를 함께 또는 별도로 사용할 수 있습니다.

[NOTE]
====
스토리지 배열에 동일한 물리적 속성을 공유하는 드라이브가 포함되어 있으면 왼쪽에 있는 * Any drive type * 필드가 나타나지 않습니다. 드라이브가 모두 동일한 논리 위치에 있는 경우 오른쪽에 있는 스토리지 배열 * 필드의 * 아무 곳이나 나타나지 않습니다.

====


 a| 
범례
 a| 
구성 요소는 특정 색상으로 표시되어 해당 역할 상태를 나타냅니다. 이러한 상태에 대한 설명을 확장하고 축소하려면 * 범례 * 를 클릭합니다.



 a| 
상태 아이콘 세부 정보를 표시합니다
 a| 
상태 표시기에는 가용성 상태에 대한 텍스트 설명이 포함될 수 있습니다. 이 상태 텍스트를 표시하거나 숨기려면 * 상태 아이콘 세부 정보 표시 * 를 클릭합니다.



 a| 
쉘프/쉘프 아이콘
 a| 
각 쉘프 뷰에는 속성 및 상태와 함께 관련 명령 목록이 제공됩니다. 명령 드롭다운 목록을 보려면 * Shelf * 를 클릭합니다. 상단에 있는 아이콘 중 하나를 선택하여 컨트롤러, IOM(ESM), 전원 공급 장치, 팬, 온도, 배터리 및 SFP.



 a| 
쉘프 주문
 a| 
하드웨어 페이지에서 쉘프를 재정렬할 수 있습니다. 각 쉘프 보기의 오른쪽 위에 있는 위/아래 화살표를 사용하여 쉘프의 위/아래 순서를 변경합니다.

|===