---
permalink: sm-hardware/view-controller-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, controller, settings 
summary: 호스트 인터페이스, 드라이브 인터페이스 및 관리 포트의 상태와 같은 컨트롤러에 대한 정보를 볼 수 있습니다. 
---
= 컨트롤러 설정을 봅니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트 인터페이스, 드라이브 인터페이스 및 관리 포트의 상태와 같은 컨트롤러에 대한 정보를 볼 수 있습니다.

.단계
. 하드웨어 * 를 선택합니다.
. 그래픽에 드라이브가 표시되면 * Controllers & Components * 탭을 클릭하십시오.
+
그래픽이 변경되어 드라이브 대신 컨트롤러가 표시됩니다.

. 다음 작업 중 하나를 수행하여 컨트롤러 설정을 표시합니다.
+
** 컨트롤러를 클릭하여 컨텍스트 메뉴를 표시한 다음 * 설정 보기 * 를 선택합니다.
** 컨트롤러 아이콘(* Shelf* 드롭다운 목록 옆에 있음)을 선택합니다. 이중 구성의 경우, 대화 상자에서 * 컨트롤러 A * 또는 * 컨트롤러 B * 를 선택한 후 * 다음 * 을 클릭합니다.
+
컨트롤러 설정 대화 상자가 열립니다.



. 속성 설정 간에 이동할 탭을 선택합니다.
+
일부 탭에는 오른쪽 위에 * 더 많은 설정 표시 * 에 대한 링크가 있습니다.

+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 탭을 클릭합니다 | 설명 


 a| 
베이스
 a| 
컨트롤러 상태, 모델 이름, 교체 부품 번호, 현재 펌웨어 버전 및 비휘발성 NVSRAM(Static Random Access Memory) 버전을 표시합니다.



 a| 
캐시
 a| 
데이터 캐시, 프로세서 캐시 및 캐시 백업 장치를 포함하는 컨트롤러의 캐시 설정을 표시합니다. 캐시 백업 디바이스는 컨트롤러의 전원이 끊길 경우 캐시의 데이터를 백업하는 데 사용됩니다. 상태는 최적, 실패, 제거, 알 수 없음, 쓰기 보호됨, 또는 호환되지 않습니다.



 a| 
호스트 인터페이스
 a| 
에서는 호스트 인터페이스 정보 및 각 포트의 링크 상태를 보여 줍니다. 호스트 인터페이스는 컨트롤러와 호스트(예: 파이버 채널 또는 iSCSI) 간의 연결입니다.


NOTE: HIC(호스트 인터페이스 카드) 위치는 베이스보드 또는 슬롯(베이)에 있습니다. "베이스보드"는 HIC 포트가 컨트롤러에 내장되어 있음을 나타냅니다. "슬롯" 포트는 HIC 옵션 중 입니다.



 a| 
드라이브 인터페이스
 a| 
에서는 드라이브 인터페이스 정보 및 각 포트의 링크 상태를 보여 줍니다. 드라이브 인터페이스는 컨트롤러와 드라이브(예: SAS) 간의 연결입니다.



 a| 
관리 포트
 a| 
에는 컨트롤러에 액세스하는 데 사용되는 호스트 이름 및 원격 로그인이 활성화되었는지 여부와 같은 관리 포트 세부 정보가 나와 있습니다. 관리 포트는 컨트롤러와 관리 클라이언트를 연결합니다. 관리 클라이언트는 System Manager에 액세스하기 위해 브라우저가 설치되어 있습니다.



 a| 
DNS/NTP
 a| 
에서는 DNS 서버와 NTP 서버의 주소 지정 방법 및 IP 주소를 보여 줍니다(이러한 서버가 System Manager에서 구성된 경우).

DNS(Domain Name System)는 인터넷 또는 개인 네트워크에 연결된 장치의 명명 시스템입니다. DNS 서버는 도메인 이름의 디렉터리를 유지 관리하고 이를 IP(인터넷 프로토콜) 주소로 변환합니다.

NTP(Network Time Protocol)는 데이터 네트워크의 컴퓨터 시스템 간 클록 동기화를 위한 네트워킹 프로토콜입니다.

|===
====
. 닫기 * 를 클릭합니다.

