---
permalink: sm-hardware/what-is-ipv6-stateless-address-auto-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ipv6, stateless, address, auto, configuration, 
summary: 상태 비저장 자동 구성을 사용하는 경우 호스트는 서버에서 주소 및 기타 구성 정보를 얻지 못합니다. 
---
= IPv6 상태 비저장 주소 자동 구성이란 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
상태 비저장 자동 구성을 사용하는 경우 호스트는 서버에서 주소 및 기타 구성 정보를 얻지 못합니다.

IPv6의 상태 비저장 자동 구성은 링크 로컬 주소, 멀티캐스팅 및 ND(Neighbor Discovery) 프로토콜을 지원합니다. IPv6는 내부 데이터 링크 계층 주소에서 주소의 인터페이스 ID를 생성할 수 있습니다.

상태 비저장 자동 구성 및 상태 저장 자동 구성은 서로 보완됩니다. 예를 들어, 호스트는 상태 비저장 자동 구성을 사용하여 자체 주소를 구성할 수 있지만 상태 저장 자동 구성을 사용하여 다른 정보를 얻을 수 있습니다. 스테이트풀 자동 구성을 사용하면 호스트가 서버에서 주소 및 기타 구성 정보를 얻을 수 있습니다. 또한 IPv6(인터넷 프로토콜 버전 6)에서는 네트워크의 모든 IP 주소를 한 번에 다시 지정할 수 있는 방법을 정의합니다. IPv6은 서버의 필요 없이 IP 주소 및 기타 매개 변수를 자동으로 구성하는 네트워크 디바이스의 방법을 정의합니다.

상태 비저장 자동 구성을 사용하는 경우 장치는 다음 단계를 수행합니다.

. * 링크 로컬 주소 생성 * -- 장치는 링크 로컬 주소를 생성합니다. 로컬 주소는 10비트이고 그 뒤에 54개의 0이 있으며 그 뒤에 64비트 인터페이스 ID가 붙습니다.
. * 링크-로컬 주소의 고유성 테스트 * -- 노드는 생성하는 링크-로컬 주소가 로컬 네트워크에서 이미 사용되고 있지 않은지 확인하기 위해 테스트합니다. 노드는 ND 프로토콜을 사용하여 인접 요청 메시지를 보냅니다. 이에 따라, 로컬 네트워크는 다른 장치가 이미 링크 로컬 주소를 사용하고 있음을 나타내는 인접 광고 메시지를 수신 대기합니다. 이 경우 새 링크 로컬 주소를 생성하거나 자동 구성에 실패하고 다른 방법을 사용해야 합니다.
. * 링크 로컬 주소 할당 * -- 장치가 고유성 테스트를 통과하면 장치는 해당 IP 인터페이스에 링크 로컬 주소를 할당합니다. 링크 로컬 주소는 인터넷을 통한 통신이 아니라 로컬 네트워크에서의 통신에 사용할 수 있습니다.
. * 라우터 연락처 * -- 노드는 로컬 라우터에 연결을 시도하여 구성을 계속하는 방법에 대한 자세한 정보를 제공합니다. 이 연락처는 공유기가 주기적으로 보내는 라우터 알림 메시지를 듣거나 특정 라우터 요청 메시지를 전송하여 공유기에 수행할 작업에 대한 정보를 요청하는 방식으로 수행됩니다.
. * 노드 방향 제공 * -- 라우터는 자동 구성 진행 방법에 대한 노드의 방향을 제공합니다. 또는 라우터는 호스트에 글로벌 인터넷 주소를 확인하는 방법을 알려줍니다.
. * 글로벌 주소 구성 * -- 호스트는 전역적으로 고유한 인터넷 주소를 사용하여 자체적으로 구성됩니다. 이 주소는 일반적으로 라우터에 의해 호스트에 제공된 네트워크 접두사로 형성됩니다.

