---
permalink: um-manage/considerations-for-discovering-arrays.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, considerations, discovering, arrays 
summary: Unified Manager가 스토리지 리소스를 표시하고 관리하기 전에 조직의 네트워크에서 관리하려는 스토리지 어레이를 검색해야 합니다. 여러 어레이를 검색할 수도 있고 단일 어레이를 검색할 수도 있습니다. 
---
= 스토리지 검색 시 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager가 스토리지 리소스를 표시하고 관리하기 전에 먼저 조직의 네트워크에서 관리할 스토리지 어레이를 검색해야 합니다. 여러 어레이를 검색할 수도 있고 단일 어레이를 검색할 수도 있습니다.



== 여러 스토리지 시스템을 검색하는 중입니다

여러 어레이를 검색하도록 선택한 경우 네트워크 IP 주소 범위를 입력한 다음 Unified Manager가 해당 범위의 각 IP 주소에 대한 개별 연결을 시도합니다. 성공적으로 도달한 스토리지 배열이 검색 페이지에 표시되고 관리 도메인에 추가될 수 있습니다.



== 단일 스토리지 시스템 검색

단일 어레이를 검색하도록 선택한 경우 스토리지 어레이에서 컨트롤러 중 하나에 대한 단일 IP 주소를 입력한 다음 개별 스토리지 어레이가 추가됩니다.

[NOTE]
====
Unified Manager는 컨트롤러에 할당된 범위 내에서 단일 IP 주소 또는 IP 주소만 검색하여 표시합니다. 이 단일 IP 주소 또는 IP 주소 범위를 벗어나는 컨트롤러에 할당된 대체 컨트롤러 또는 IP 주소가 있는 경우 Unified Manager는 이를 검색 또는 표시하지 않습니다. 그러나 스토리지 배열을 추가하면 연결된 모든 IP 주소가 검색되어 관리 보기에 표시됩니다.

====


== 사용자 자격 증명

검색 프로세스 중에 추가할 각 스토리지 배열에 대해 관리자 암호를 제공해야 합니다.



== 웹 서비스 인증서

검색 프로세스의 일부로 Unified Manager는 검색된 스토리지 시스템이 신뢰할 수 있는 소스의 인증서를 사용하고 있는지 확인합니다. Unified Manager에서는 브라우저에 설정한 모든 연결에 대해 두 가지 유형의 인증서 기반 인증을 사용합니다.

* * 신뢰할 수 있는 인증서 *
+
Unified Manager에서 검색된 스토리지의 경우 인증 기관에서 제공하는 신뢰할 수 있는 인증서를 추가로 설치해야 할 수 있습니다.

+
이러한 인증서를 가져오려면 * 가져오기 * 버튼을 사용합니다. 이전에 이 어레이에 연결한 경우 하나 또는 두 컨트롤러 인증서 중 하나가 만료되었거나 해지되었거나 인증서 체인에 루트 인증서 또는 중간 인증서가 누락되었습니다. 스토리지 배열을 관리하기 전에 만료되었거나 해지된 인증서를 교체하거나 누락된 루트 인증서 또는 중간 인증서를 추가해야 합니다.

* * 자체 서명된 인증서 *
+
자체 서명된 인증서도 사용할 수 있습니다. 관리자가 서명된 인증서를 가져오지 않고 어레이를 검색하려고 하면 Unified Manager에 관리자가 자체 서명된 인증서를 수락할 수 있는 오류 대화 상자가 표시됩니다. 스토리지 시스템의 자체 서명된 인증서가 신뢰할 수 있는 것으로 표시되고 스토리지 시스템이 Unified Manager에 추가됩니다.

+
스토리지 배열에 대한 연결을 신뢰하지 않는 경우, Unified Manager에 스토리지 배열을 추가하기 전에 * Cancel * 을 선택하고 스토리지 배열의 보안 인증서 전략을 확인합니다.


