---
permalink: um-manage/create-asynchronous-mirrored-pair-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, create, asynchronous, mirrored, pair 
summary: 비동기식 미러링을 구성하려면 로컬 스토리지의 기본 볼륨과 원격 스토리지의 보조 볼륨을 포함하는 미러링된 쌍을 생성합니다. 
---
= 비동기 미러링 쌍을 생성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
비동기식 미러링을 구성하려면 로컬 스토리지의 기본 볼륨과 원격 스토리지의 보조 볼륨을 포함하는 미러링된 쌍을 생성합니다.

.시작하기 전에
미러링된 쌍을 생성하기 전에 Unified Manager에 대한 다음 요구사항을 충족해야 합니다.

* 웹 서비스 프록시 서비스가 실행되고 있어야 합니다.
* Unified Manager는 HTTPS 연결을 통해 로컬 호스트에서 실행되고 있어야 합니다.
* Unified Manager에 스토리지 시스템에 대한 유효한 SSL 인증서가 표시되어야 합니다. 자체 서명된 인증서를 수락하거나 Unified Manager를 사용하여 인증서 [인증서 관리] 메뉴로 이동하여 자체 보안 인증서를 설치할 수 있습니다.


또한 스토리지 어레이 및 볼륨에 대한 다음 요구 사항도 충족해야 합니다.

* 각 스토리지 어레이에는 2개의 컨트롤러가 필요합니다.
* Unified Manager에서 2개의 스토리지 어레이가 검색되어야 합니다.
* 기본 어레이와 보조 어레이의 각 컨트롤러에는 이더넷 관리 포트가 구성되어 있어야 하며 네트워크에 연결되어 있어야 합니다.
* 스토리지 어레이의 펌웨어 버전은 최소 7.84입니다. (각 OS 버전은 서로 다를 수 있음)
* 로컬 및 원격 스토리지 배열의 암호를 알아야 합니다.
* 미러링할 운영 볼륨과 같거나 더 큰 보조 볼륨을 생성하려면 원격 스토리지 시스템에 사용 가능한 용량이 충분해야 합니다.
* 로컬 및 원격 스토리지 어레이는 파이버 채널 패브릭 또는 iSCSI 인터페이스를 통해 연결됩니다.
* 비동기식 미러 관계에 사용할 운영 볼륨과 2차 볼륨을 모두 생성했습니다.
* 2차 볼륨의 크기는 운영 볼륨만큼 크지 않아야 합니다.


.이 작업에 대해
비동기 미러링 쌍을 만드는 프로세스는 다단계 절차입니다.



== 1단계: 미러 정합성 보장 그룹을 생성하거나 선택합니다

이 단계에서는 새 미러 일관성 그룹을 생성하거나 기존 미러 일관성 그룹을 선택합니다. 미러 정합성 보장 그룹은 운영 볼륨과 2차 볼륨(미러링된 페어)의 컨테이너로, 그룹의 모든 페어에 대해 원하는 재동기화 방법(수동 또는 자동)을 지정합니다.

.단계
. Manage * 페이지에서 소스에 사용할 로컬 스토리지 배열을 선택합니다.
. 메뉴 선택: 작업 [비동기 미러링 쌍 만들기].
+
Create Asynchronous Mirrored Pair 마법사가 열립니다.

. 기존 미러 정합성 보장 그룹을 선택하거나 새 미러 정합성 보장 그룹을 생성합니다.
+
기존 그룹을 선택하려면 * 기존 미러 정합성 보장 그룹 * 이 선택되어 있는지 확인한 다음 테이블에서 그룹을 선택합니다. 일관성 그룹에는 여러 개의 미러링된 쌍이 포함될 수 있습니다.

+
새 그룹을 만들려면 다음을 수행합니다.

+
.. 새 미러 정합성 보장 그룹 * 을 선택한 후 * 다음 * 을 클릭합니다.
.. 두 스토리지 배열 간에 미러링될 볼륨의 데이터를 가장 잘 설명하는 고유한 이름을 입력합니다. 이름은 문자, 숫자 및 밑줄(_), 대시(-) 및 해시 기호(#)로만 구성될 수 있습니다. 이름은 30자를 초과할 수 없으며 공백을 포함할 수 없습니다.
.. 로컬 스토리지 시스템과 미러 관계를 설정할 원격 스토리지 시스템을 선택합니다.
+
[NOTE]
====
원격 스토리지 배열이 암호로 보호되어 있는 경우 암호를 입력하라는 메시지가 표시됩니다.

====
.. 미러링된 쌍을 수동으로 동기화할지 또는 자동으로 동기화할지 여부를 선택합니다.
+
*** * 수동 * -- 이 그룹 내에서 미러링된 모든 쌍의 동기화를 수동으로 시작하려면 이 옵션을 선택합니다. 나중에 재동기화를 수행하려면 운영 스토리지 시스템에 대해 System Manager를 시작한 다음 메뉴(Storage [Asynchronous Mirroring])로 이동하여 * Mirror Consistency Groups * 탭에서 그룹을 선택한 다음 menu: More [Manually resyncize] 를 선택합니다.
*** * 자동 * - 이전 업데이트 시작에서 다음 업데이트 시작까지 원하는 간격을 * 분 *, * 시간 * 또는 * 일 * 으로 선택합니다. 예를 들어 동기화 간격이 30분으로 설정되어 있고 동기화 프로세스가 오후 4시에 시작되는 경우 다음 프로세스는 오후 4시 30분에 시작됩니다


.. 원하는 알림 설정을 선택합니다.
+
*** 수동 동기화의 경우 알림을 받을 때의 임계값(남은 용량 백분율로 정의)을 지정합니다.
*** 자동 동기화의 경우 세 가지 알림 방법을 설정할 수 있습니다. 특정 시간 동안 동기화가 완료되지 않은 경우, 원격 스토리지의 복구 지점 데이터가 특정 시간 제한보다 오래되고 예약된 용량이 특정 임계값(남은 용량 백분율로 정의)에 근접하는 경우




. Next * 를 선택하고 로 이동합니다 <<2단계: 운영 볼륨을 선택합니다>>.
+
새 미러 정합성 보장 그룹을 정의한 경우 Unified Manager는 먼저 로컬 스토리지 시스템에 미러 정합성 보장 그룹을 생성한 다음 원격 스토리지 시스템에 미러 정합성 보장 그룹을 생성합니다. 각 어레이에 대해 System Manager를 시작하여 미러 정합성 보장 그룹을 보고 관리할 수 있습니다.

+
[NOTE]
====
Unified Manager가 로컬 스토리지 시스템에 미러 정합성 보장 그룹을 생성했지만 원격 스토리지 시스템에 생성하지 못한 경우 로컬 스토리지 시스템에서 미러 정합성 보장 그룹이 자동으로 삭제됩니다. Unified Manager에서 미러 정합성 보장 그룹을 삭제하려는 동안 오류가 발생하면 수동으로 삭제해야 합니다.

====




== 2단계: 운영 볼륨을 선택합니다

이 단계에서는 미러 관계에 사용할 운영 볼륨을 선택하고 예약된 용량을 할당합니다. 로컬 스토리지 배열에서 운영 볼륨을 선택하면 해당 미러링된 쌍에 대해 적합한 모든 볼륨 목록이 표시됩니다. 사용할 수 없는 볼륨은 해당 목록에 표시되지 않습니다.

로컬 스토리지 시스템의 미러 정합성 보장 그룹에 추가하는 모든 볼륨은 미러 관계에서 기본 역할을 유지합니다.

.단계
. 사용 가능한 볼륨 목록에서 운영 볼륨으로 사용할 볼륨을 선택한 후 * Next * 를 클릭하여 예약된 용량을 할당합니다.
. 적합한 후보 목록에서 운영 볼륨에 대해 예약된 용량을 선택합니다.
+
다음 지침을 염두에 두십시오.

+
** 예약된 용량의 기본 설정은 기본 볼륨 용량의 20%이며 일반적으로 이 용량이면 충분합니다. 비율을 변경한 경우 * 후보 새로 고침 * 을 클릭합니다.
** 필요한 용량은 운영 볼륨에 대한 I/O 쓰기의 빈도 및 크기와 용량을 유지하는 데 필요한 기간에 따라 달라집니다.
** 일반적으로 다음 조건 중 하나 또는 둘 다 존재할 경우 예약된 용량에 더 큰 용량을 선택합니다.
+
*** 미러링 쌍을 장기간 유지하려고 합니다.
*** 입출력 작업이 많은 경우 운영 볼륨에서 데이터 블록의 비율이 크게 변경됩니다. 기간별 성능 데이터 또는 기타 운영 체제 유틸리티를 사용하여 기본 볼륨에 대한 일반적인 I/O 작업을 결정할 수 있습니다.




. Next * 를 선택하고 로 이동합니다 <<3단계: 보조 볼륨을 선택합니다>>.




== 3단계: 보조 볼륨을 선택합니다

이 단계에서는 미러 관계에 사용할 보조 볼륨을 선택하고 예약된 용량을 할당합니다. 원격 스토리지 어레이에서 보조 볼륨을 선택하면 해당 미러링된 쌍에 대해 적합한 모든 볼륨 목록이 표시됩니다. 사용할 수 없는 볼륨은 해당 목록에 표시되지 않습니다.

원격 스토리지 시스템의 미러 정합성 보장 그룹에 추가하는 모든 볼륨은 미러 관계에서 2차 역할을 유지합니다.

.단계
. 적합한 볼륨 목록에서 미러링된 쌍의 보조 볼륨으로 사용할 볼륨을 선택한 후 * Next * 를 클릭하여 예약된 용량을 할당합니다.
. 적합한 후보 목록에서 2차 볼륨에 대해 예약된 용량을 선택합니다.
+
다음 지침을 염두에 두십시오.

+
** 예약된 용량의 기본 설정은 기본 볼륨 용량의 20%이며 일반적으로 이 용량이면 충분합니다. 비율을 변경한 경우 * 후보 새로 고침 * 을 클릭합니다.
** 필요한 용량은 운영 볼륨에 대한 I/O 쓰기의 빈도 및 크기와 용량을 유지하는 데 필요한 기간에 따라 달라집니다.
** 일반적으로 다음 조건 중 하나 또는 둘 다 존재할 경우 예약된 용량에 더 큰 용량을 선택합니다.
+
*** 미러링 쌍을 장기간 유지하려고 합니다.
*** 입출력 작업이 많은 경우 운영 볼륨에서 데이터 블록의 비율이 크게 변경됩니다. 기간별 성능 데이터 또는 기타 운영 체제 유틸리티를 사용하여 기본 볼륨에 대한 일반적인 I/O 작업을 결정할 수 있습니다.




. 비동기 미러링 시퀀스를 완료하려면 * Finish * 를 선택합니다.


.결과
Unified Manager는 다음 작업을 수행합니다.

* 로컬 스토리지와 원격 스토리지 시스템 간의 초기 동기화를 시작합니다.
* 로컬 스토리지 시스템 및 원격 스토리지 시스템에서 미러링된 쌍에 대한 예약된 용량을 생성합니다.



NOTE: 미러링되는 볼륨이 씬 볼륨인 경우 초기 동기화 중에 프로비저닝된 블록(보고된 용량이 아닌 할당된 용량)만 보조 볼륨으로 전송됩니다. 이렇게 하면 초기 동기화를 완료하기 위해 전송해야 하는 데이터의 양이 줄어듭니다.
