---
permalink: um-manage/create-synchronous-mirrored-pair-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, create, synchronous, mirrored, pair 
summary: 동기식 미러링을 구성하려면 로컬 스토리지의 기본 볼륨과 원격 스토리지의 보조 볼륨을 포함하는 미러링된 쌍을 생성합니다. 
---
= 동기식 미러링 쌍을 생성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
동기식 미러링을 구성하려면 로컬 스토리지의 기본 볼륨과 원격 스토리지의 보조 볼륨을 포함하는 미러링된 쌍을 생성합니다.

[NOTE]
====
EF600 또는 EF300 스토리지 시스템에서는 이 기능을 사용할 수 없습니다.

====
.시작하기 전에
미러링된 쌍을 생성하기 전에 Unified Manager에 대한 다음 요구사항을 충족해야 합니다.

* 웹 서비스 프록시 서비스가 실행되고 있어야 합니다.
* Unified Manager는 HTTPS 연결을 통해 로컬 호스트에서 실행되고 있어야 합니다.
* Unified Manager에 스토리지 시스템에 대한 유효한 SSL 인증서가 표시되어야 합니다. 자체 서명된 인증서를 수락하거나 Unified Manager를 사용하여 인증서 [인증서 관리] 메뉴로 이동하여 자체 보안 인증서를 설치할 수 있습니다.


또한 스토리지 어레이 및 볼륨에 대한 다음 요구 사항도 충족해야 합니다.

* 미러링에 사용할 두 스토리지 어레이가 Unified Manager에서 검색됩니다.
* 각 스토리지 어레이에는 2개의 컨트롤러가 필요합니다.
* 기본 어레이와 보조 어레이의 각 컨트롤러에는 이더넷 관리 포트가 구성되어 있어야 하며 네트워크에 연결되어 있어야 합니다.
* 스토리지 어레이의 펌웨어 버전은 최소 7.84입니다. (각 OS 버전은 서로 다를 수 있음)
* 로컬 및 원격 스토리지 배열의 암호를 알아야 합니다.
* 로컬 및 원격 스토리지 어레이는 파이버 채널 패브릭을 통해 연결됩니다.
* 동기식 미러 관계에 사용할 운영 볼륨과 2차 볼륨을 모두 생성했습니다.
* 운영 볼륨은 표준 볼륨이어야 합니다. 씬 볼륨이거나 스냅샷 볼륨일 수 없습니다.
* 2차 볼륨은 표준 볼륨이어야 합니다. 씬 볼륨이거나 스냅샷 볼륨일 수 없습니다.
* 2차 볼륨의 크기는 운영 볼륨만큼 크지 않아야 합니다.


.이 작업에 대해
동기식 미러링 쌍을 생성하는 프로세스는 여러 단계로 이루어집니다.



== 1단계: 운영 볼륨을 선택합니다

이 단계에서는 동기식 미러 관계에 사용할 운영 볼륨을 선택합니다. 로컬 스토리지 배열에서 운영 볼륨을 선택하면 해당 미러링된 쌍에 대해 적합한 모든 볼륨 목록이 표시됩니다. 사용할 수 없는 볼륨은 해당 목록에 표시되지 않습니다. 선택한 볼륨은 미러 관계에서 1차 역할을 보유합니다.

.단계
. Manage * 페이지에서 소스에 사용할 로컬 스토리지 배열을 선택합니다.
. 메뉴 선택: 작업 [동기식 미러링 쌍 생성].
+
동기식 미러링 쌍 생성 마법사가 열립니다.

. 적합한 볼륨 목록에서 미러의 운영 볼륨으로 사용할 볼륨을 선택합니다.
. Next * 를 선택하고 로 이동합니다 <<2단계: 보조 볼륨을 선택합니다>>.




== 2단계: 보조 볼륨을 선택합니다

이 단계에서는 미러 관계에 사용할 보조 볼륨을 선택합니다. 원격 스토리지 어레이에서 보조 볼륨을 선택하면 해당 미러링된 쌍에 대해 적합한 모든 볼륨 목록이 표시됩니다. 사용할 수 없는 볼륨은 해당 목록에 표시되지 않습니다. 선택한 볼륨은 미러 관계에서 2차 역할을 유지합니다.

.단계
. 로컬 스토리지 시스템과 미러 관계를 설정할 원격 스토리지 시스템을 선택합니다.
+
[NOTE]
====
원격 스토리지 배열이 암호로 보호되어 있는 경우 암호를 입력하라는 메시지가 표시됩니다.

====
+
** 스토리지 배열은 해당 스토리지 배열 이름으로 나열됩니다. 스토리지 배열의 이름을 지정하지 않은 경우 이름이 "UNNAMED(명명되지 않음)"으로 표시됩니다.
** 사용하려는 스토리지 어레이가 목록에 없는 경우 Unified Manager에서 검색된 스토리지인지 확인합니다.


. 적합한 볼륨 목록에서 미러의 2차 볼륨으로 사용할 볼륨을 선택합니다.
+
[NOTE]
====
운영 볼륨보다 큰 용량으로 2차 볼륨을 선택하는 경우 사용 가능한 용량이 운영 볼륨의 크기로 제한됩니다.

====
. 다음 * 을 클릭하고 으로 이동합니다 <<3단계: 동기화 설정을 선택합니다>>.




== 3단계: 동기화 설정을 선택합니다

이 단계에서는 통신 중단 후 데이터 동기화 방법을 결정하는 설정을 선택합니다. 통신이 중단된 후 기본 볼륨의 컨트롤러 소유자가 데이터를 보조 볼륨과 재동기화하는 우선 순위를 설정할 수 있습니다. 수동 또는 자동 재동기화 정책도 선택해야 합니다.

.단계
. 슬라이더 막대를 사용하여 동기화 우선 순위를 설정합니다.
+
동기화 우선 순위는 서비스 입출력 요청과 비교하여 통신 중단 후 초기 동기화 및 재동기화 작업을 완료하는 데 사용되는 시스템 리소스의 양을 결정합니다.

+
이 대화 상자에 설정된 우선 순위는 운영 볼륨과 2차 볼륨 모두에 적용됩니다. 나중에 System Manager로 이동하여 메뉴에서 스토리지 [동기식 미러링 > 자세히 > 설정 편집]을 선택하여 기본 볼륨의 속도를 수정할 수 있습니다.

+
동기화 우선 순위는 5가지입니다.

+
** 최저
** 낮음
** 중간
** 높음
** 최고
+
동기화 우선 순위가 가장 낮은 속도로 설정된 경우 입출력 작업의 우선 순위가 지정되고 재동기화 작업이 더 오래 걸립니다. 동기화 우선 순위가 가장 높은 속도로 설정된 경우 재동기화 작업의 우선 순위가 지정되지만 스토리지 시스템의 입출력 작업이 영향을 받을 수 있습니다.



. 원격 스토리지 시스템에서 미러링된 쌍을 수동 또는 자동으로 재동기화할지 여부를 선택합니다.
+
** * 수동 * (권장 옵션) -- 미러링된 쌍으로 통신이 복구된 후 수동으로 동기화를 재개하려면 이 옵션을 선택합니다. 이 옵션은 데이터를 복구할 수 있는 최적의 기회를 제공합니다.
** * 자동 * -- 통신이 미러링된 쌍으로 복구된 후 재동기화를 자동으로 시작하려면 이 옵션을 선택합니다.
+
동기화를 수동으로 재개하려면 System Manager로 이동하여 메뉴에서 Storage [Synchronous Mirroring](저장소 [Synchronous Mirroring])을 선택하고 표에서 미러링된 쌍을 강조 표시한 다음 * More *(기타 *) * 에서 * Resume * 을 선택합니다.



. 동기식 미러링 시퀀스를 완료하려면 * Finish * 를 클릭합니다.


.결과
미러링이 활성화되면 시스템은 다음 작업을 수행합니다.

* 로컬 스토리지와 원격 스토리지 시스템 간의 초기 동기화를 시작합니다.
* 동기화 우선 순위 및 재동기화 정책을 설정합니다.
* 미러 데이터 전송을 위해 컨트롤러 HIC에서 가장 높은 번호의 포트를 예약합니다.
+
이 포트에서 수신된 I/O 요청은 미러링된 쌍에 있는 보조 볼륨의 원격 기본 컨트롤러 소유자만이 허용됩니다. (기본 볼륨에 대한 예약이 허용됩니다.)

* 각 컨트롤러에 대해 하나씩, 예약된 용량 볼륨 2개를 생성합니다. 이 볼륨은 컨트롤러 재설정 및 기타 임시 중단으로부터 복구하기 위한 쓰기 정보를 로깅하는 데 사용됩니다.
+
각 볼륨의 용량은 128MiB입니다. 하지만 볼륨이 풀에 배치되면 4GiB가 각 볼륨에 대해 예약됩니다.



.작업을 마친 후
System Manager로 이동하여 Home [View Operations in Progress] 메뉴를 선택하여 동기 미러링 작업의 진행률을 확인합니다. 이 작업은 시간이 오래 걸릴 수 있으며 시스템 성능에 영향을 줄 수 있습니다.
