---
permalink: um-manage/discover-multiple-arrays.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, discover, multiple, storage, arrays 
summary: 여러 어레이를 검색하여 관리 서버가 있는 서브넷에서 모든 스토리지 어레이를 검색하고 검색된 어레이를 관리 도메인에 자동으로 추가합니다. 
---
= 여러 스토리지 시스템을 검색합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
여러 어레이를 검색하여 관리 서버가 있는 서브넷에서 모든 스토리지 어레이를 검색하고 검색된 어레이를 관리 도메인에 자동으로 추가합니다.

.시작하기 전에
* 보안 관리자 권한이 포함된 사용자 프로필로 로그인해야 합니다.
* 스토리지 배열이 올바르게 설정 및 구성되어 있어야 합니다.
* 스토리지 배열 암호는 System Manager의 액세스 관리 타일을 사용하여 설정해야 합니다.
* 신뢰할 수 없는 인증서를 해결하려면 CA(인증 기관)의 신뢰할 수 있는 인증서 파일이 있어야 하며 로컬 시스템에서 인증서 파일을 사용할 수 있어야 합니다.


어레이 검색 절차는 여러 단계로 이루어진 절차입니다.



== 1단계: 네트워크 주소를 입력합니다

로컬 하위 네트워크에서 검색할 네트워크 주소 범위를 입력합니다. 성공적으로 도달한 스토리지 배열이 검색 페이지에 표시되고 관리 도메인에 추가될 수 있습니다.

어떤 이유로든 검색 작업을 중지해야 하는 경우 * 검색 중지 * 를 클릭합니다.

.단계
. 관리 페이지에서 * 추가/검색 * 을 선택합니다.
+
추가/검색 대화 상자가 나타납니다.

. 네트워크 범위 내의 모든 스토리지 배열 검색 * 라디오 버튼을 선택합니다.
. 로컬 하위 네트워크를 검색할 시작 네트워크 주소와 끝 네트워크 주소를 입력한 다음 * 검색 시작 * 을 클릭합니다.
+
검색 프로세스가 시작됩니다. 이 검색 프로세스를 완료하는 데 몇 분 정도 걸릴 수 있습니다. 스토리지 배열이 검색되면 검색 페이지의 테이블이 채워집니다.

+
[NOTE]
====
관리 가능한 어레이가 검색되지 않으면 스토리지 어레이가 네트워크에 올바르게 연결되어 있고 할당된 주소가 범위 내에 있는지 확인합니다. 추가/검색 페이지로 돌아가려면 * New Discovery Parameters * 를 클릭합니다.

====
. 검색된 스토리지 시스템의 목록을 검토합니다.
. 관리 도메인에 추가할 스토리지 배열 옆의 확인란을 선택하고 * 다음 * 을 클릭합니다.
+
Unified Manager는 관리 도메인에 추가할 각 어레이에서 자격 증명 검사를 수행합니다. 해당 배열과 연결된 자체 서명된 인증서 및 신뢰할 수 없는 인증서를 확인해야 할 수 있습니다.

. 마법사의 다음 단계로 진행하려면 * Next * (다음 *)를 클릭합니다.




== 2단계: 검색 중에 자체 서명된 인증서 해결

검색 프로세스의 일부로 시스템은 스토리지 어레이가 신뢰할 수 있는 소스의 인증서를 사용하고 있는지 확인합니다.

.단계
. 다음 중 하나를 수행합니다.
+
** 검색된 스토리지 배열에 대한 접속을 신뢰할 수 있는 경우 마법사의 다음 카드로 계속 진행합니다. 자체 서명된 인증서는 신뢰할 수 있는 인증서로 표시되며 스토리지 시스템이 Unified Manager에 추가됩니다.
** 스토리지 어레이에 대한 연결을 신뢰할 수 없는 경우 * Cancel * 을 선택하고 각 스토리지 어레이의 보안 인증서 전략을 확인한 다음 Unified Manager에 추가합니다.


. 마법사의 다음 단계로 진행하려면 * Next * (다음 *)를 클릭합니다.




== 3단계: 검색 중에 신뢰할 수 없는 인증서를 해결합니다

신뢰할 수 없는 인증서는 스토리지 어레이에서 Unified Manager에 대한 보안 연결을 설정하려고 시도하지만 연결이 보안으로 확인하지 못할 때 발생합니다. 어레이 검색 프로세스 중에 신뢰할 수 있는 타사에서 발급한 CA(인증 기관) 인증서 또는 CA 서명 인증서를 가져와 신뢰할 수 없는 인증서를 해결할 수 있습니다.

다음 중 하나라도 해당되는 경우 신뢰할 수 있는 CA 인증서를 추가로 설치해야 할 수 있습니다.

* 최근에 스토리지 배열을 추가했습니다.
* 하나 이상의 인증서가 만료되었습니다.
* 하나 이상의 인증서가 해지되었습니다.
* 하나 이상의 인증서에 루트 또는 중간 인증서가 없습니다.


.단계
. 신뢰할 수 없는 인증서를 확인할 스토리지 배열 옆의 확인란을 선택한 다음 ** 가져오기** 버튼을 선택합니다.
+
신뢰할 수 있는 인증서 파일을 가져올 수 있는 대화 상자가 열립니다.

. Browse * 를 클릭하여 스토리지 배열에 대한 인증서 파일을 선택합니다.
+
대화 상자에 파일 이름이 표시됩니다.

. 가져오기 * 를 클릭합니다.
+
파일이 업로드되고 검증됩니다.

+
[NOTE]
====
신뢰할 수 없는 인증서 문제가 해결되지 않은 스토리지 어레이는 Unified Manager에 추가되지 않습니다.

====
. 마법사의 다음 단계로 진행하려면 * Next * (다음 *)를 클릭합니다.




== 4단계: 암호를 입력합니다

관리 도메인에 추가할 스토리지 배열에 대한 암호를 입력해야 합니다.

.단계
. Unified Manager에 추가할 각 스토리지 어레이의 암호를 입력합니다.
. * 선택 사항: * 그룹에 스토리지 어레이 연결: 드롭다운 목록에서 선택한 스토리지 어레이와 연결할 그룹을 선택합니다.
. 마침 * 을 클릭합니다.


.작업을 마친 후
스토리지 배열이 관리 도메인에 추가되고 선택한 그룹에 연결됩니다(지정된 경우).

[NOTE]
====
Unified Manager가 지정된 스토리지 어레이에 연결하는 데 몇 분 정도 걸릴 수 있습니다.

====