---
permalink: um-manage/discover-single-array.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, discover, single, array 
summary: 단일 스토리지 배열 추가/검색 옵션을 사용하여 조직의 네트워크에 단일 스토리지 배열을 수동으로 검색하고 추가합니다. 
---
= 단일 스토리지를 검색합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
단일 스토리지 배열 추가/검색 옵션을 사용하여 조직의 네트워크에 단일 스토리지 배열을 수동으로 검색하고 추가합니다.

.시작하기 전에
* 스토리지 배열이 올바르게 설정 및 구성되어 있어야 합니다.
* 스토리지 배열 암호는 System Manager의 액세스 관리 타일을 사용하여 설정해야 합니다.


.단계
. 관리 페이지에서 * 추가/검색 * 을 선택합니다.
+
추가/검색 대화 상자가 나타납니다.

. Discover a single storage array * 라디오 버튼을 선택합니다.
. 스토리지 배열에 있는 컨트롤러 중 하나의 IP 주소를 입력한 다음 * 검색 시작 * 을 클릭합니다.
+
Unified Manager가 지정된 스토리지 어레이에 연결하는 데 몇 분 정도 걸릴 수 있습니다.

+
[NOTE]
====
지정된 컨트롤러의 IP 주소에 대한 연결이 실패하면 스토리지 어레이에 액세스할 수 없음 메시지가 나타납니다.

====
. 메시지가 표시되면 자체 서명된 인증서를 모두 해결합니다.
+
검색 프로세스의 일부로 검색된 스토리지 시스템이 신뢰할 수 있는 소스의 인증서를 사용하고 있는지 확인합니다. 스토리지 배열에 대한 디지털 인증서를 찾을 수 없는 경우 보안 예외를 추가하여 CA(인증 기관)에서 서명하지 않은 인증서를 확인하라는 메시지가 표시됩니다.

. 메시지가 나타나면 신뢰할 수 없는 인증서를 모두 확인합니다.
+
신뢰할 수 없는 인증서는 스토리지 어레이에서 Unified Manager에 대한 보안 연결을 설정하려고 시도하지만 연결이 보안으로 확인하지 못할 때 발생합니다. 신뢰할 수 있는 제3자가 발급한 CA(인증 기관) 인증서를 가져와 신뢰할 수 없는 인증서를 해결합니다.

. 다음 * 을 클릭합니다.
. * 선택 사항: * 검색된 스토리지 배열을 그룹에 연결: 드롭다운 목록에서 스토리지 배열에 연결할 그룹을 선택합니다.
+
기본적으로 "모두" 그룹이 선택됩니다.

. 관리 도메인에 추가할 스토리지 배열의 관리자 암호를 입력한 다음 * 확인 * 을 클릭합니다.


.작업을 마친 후
스토리지 시스템이 Unified Manager에 추가되고 지정된 경우 선택한 그룹에 추가됩니다.

자동 지원 데이터 수집이 설정된 경우 추가하는 스토리지 배열에 대한 지원 데이터가 자동으로 수집됩니다.
