---
permalink: um-manage/faq-import-settings.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity Unified Manager에 대한 가져오기 설정 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 가져올 설정은 무엇입니까?

설정 가져오기 기능은 하나의 스토리지 어레이에서 여러 스토리지 어레이로 구성을 로드하는 일괄 작업입니다. 이 작업 중에 가져온 설정은 SANtricity 시스템 관리자에서 소스 스토리지 배열이 구성된 방식에 따라 다릅니다.

다음 설정을 여러 스토리지 어레이로 가져올 수 있습니다.

* * 이메일 경고 * -- 설정에는 메일 서버 주소와 경고 받는 사람의 이메일 주소가 포함됩니다.
* * Syslog alerts * -- 설정에는 syslog 서버 주소와 UDP 포트가 포함됩니다.
* SNMP 경고 * -- 설정에는 SNMP 서버에 대한 커뮤니티 이름과 IP 주소가 포함됩니다.
* * AutoSupport * -- 설정에는 별도 기능(기본 AutoSupport, AutoSupport OnDemand 및 원격 진단), 유지보수 윈도우, 제공 방법, 및 발송 일정을 참조하십시오.
* * 디렉토리 서비스 * -- 구성에는 LDAP(Lightweight Directory Access Protocol) 서버의 도메인 이름 및 URL과 LDAP 서버의 사용자 그룹에 대한 스토리지 배열의 사전 정의된 역할에 대한 매핑이 포함됩니다.
* * 스토리지 구성 * -- 구성에는 볼륨(일반 및 비리포지토리 볼륨만), 볼륨 그룹, 풀 및 핫 스페어 드라이브 할당이 포함됩니다.
* * 시스템 설정 * -- 구성에는 볼륨에 대한 미디어 스캔 설정, 컨트롤러에 대한 SSD 캐시, 자동 로드 밸런싱(호스트 연결 보고 제외)이 포함됩니다.




== 내 스토리지 배열이 모두 보이지 않는 이유는 무엇인가요?

설정 가져오기 작업 중에 일부 스토리지 배열을 대상 선택 대화 상자에서 사용하지 못할 수 있습니다.

다음과 같은 이유로 스토리지 어레이가 나타나지 않을 수 있습니다.

* 펌웨어 버전이 8.50 미만입니다.
* 스토리지 배열이 오프라인입니다.
* 시스템이 해당 어레이와 통신할 수 없습니다(예: 어레이에 인증서, 암호 또는 네트워킹 문제가 있음).

