---
permalink: um-manage/faq-storage-mirroring.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity Unified Manager에 대한 스토리지 미러링 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 미러 정합성 보장 그룹을 생성하기 전에 알아야 할 내용은 무엇입니까?

미러 일관성 그룹을 생성하기 전에 다음 지침을 따르십시오.

Unified Manager에 대한 다음 요구사항을 충족합니다.

* 웹 서비스 프록시 서비스가 실행되고 있어야 합니다.
* Unified Manager는 HTTPS 연결을 통해 로컬 호스트에서 실행되고 있어야 합니다.
* Unified Manager에 스토리지 시스템에 대한 유효한 SSL 인증서가 표시되어야 합니다. 자체 서명된 인증서를 수락하거나 Unified Manager를 사용하여 인증서 [인증서 관리] 메뉴로 이동하여 자체 보안 인증서를 설치할 수 있습니다.


또한 스토리지 어레이에 대한 다음 요구 사항도 충족해야 합니다.

* Unified Manager에서 2개의 스토리지 어레이가 검색되어야 합니다.
* 각 스토리지 어레이에는 2개의 컨트롤러가 필요합니다.
* 기본 어레이와 보조 어레이의 각 컨트롤러에는 이더넷 관리 포트가 구성되어 있어야 하며 네트워크에 연결되어 있어야 합니다.
* 스토리지 어레이의 펌웨어 버전은 최소 7.84입니다. (각 OS 버전은 서로 다를 수 있음)
* 로컬 및 원격 스토리지 배열의 암호를 알아야 합니다.
* 로컬 및 원격 스토리지 어레이는 파이버 채널 패브릭 또는 iSCSI 인터페이스를 통해 연결됩니다.


[NOTE]
====
EF600/EF600C 또는 EF300/EF300C 스토리지 시스템에서는 동기식 미러링을 사용할 수 없습니다.

====


== 미러링된 쌍을 만들기 전에 알아야 할 내용은 무엇입니까?

대칭 복사된 쌍을 만들기 전에 다음 지침을 따릅니다.

* 두 개의 스토리지 어레이가 있어야 합니다.
* 각 스토리지 어레이에는 2개의 컨트롤러가 필요합니다.
* Unified Manager에서 2개의 스토리지 어레이가 검색되어야 합니다.
* 기본 어레이와 보조 어레이의 각 컨트롤러에는 이더넷 관리 포트가 구성되어 있어야 하며 네트워크에 연결되어 있어야 합니다.
* 스토리지 어레이의 펌웨어 버전은 최소 7.84입니다. (각 OS 버전은 서로 다를 수 있음)
* 로컬 및 원격 스토리지 배열의 암호를 알아야 합니다.
* 미러링할 운영 볼륨과 같거나 더 큰 보조 볼륨을 생성하려면 원격 스토리지 시스템에 사용 가능한 용량이 충분해야 합니다.
* 비동기 미러링은 FC(파이버 채널) 또는 iSCSI 호스트 포트가 있는 컨트롤러에서 지원되며, 동기식 미러링은 FC 호스트 포트가 있는 컨트롤러에서만 지원됩니다.


[NOTE]
====
EF600/EF600C 또는 EF300/EF300C 스토리지 시스템에서는 동기식 미러링을 사용할 수 없습니다.

====


== 이 비율을 변경하는 이유는 무엇입니까?

일반적으로 예약된 용량은 비동기식 미러링 작업을 위한 기본 볼륨의 20%입니다. 일반적으로 이 용량이면 충분합니다.

필요한 용량은 기본 볼륨에 대한 I/O 쓰기의 빈도 및 크기와 스토리지 오브젝트의 복사 서비스 작업을 사용할 기간에 따라 달라집니다. 일반적으로 다음 조건 중 하나 또는 둘 다 존재할 경우 예약된 용량에 더 큰 비율을 선택합니다.

* 특정 스토리지 오브젝트의 복사 서비스 작업 수명이 매우 긴 경우
* 입출력 작업이 많은 경우 기본 볼륨에서 데이터 블록의 비율이 크게 변경될 수 있습니다. 기간별 성능 데이터 또는 기타 운영 체제 유틸리티를 사용하여 기본 볼륨에 대한 일반적인 I/O 작업을 결정할 수 있습니다.




== 예약된 용량이 두 개 이상 표시되는 이유는 무엇입니까?

풀 또는 볼륨 그룹에 스토리지 객체에 대해 선택한 용량 비율을 충족하는 볼륨이 두 개 이상 있는 경우 여러 후보가 표시됩니다.

복사 서비스 작업을 위해 기본 볼륨에 예약할 물리적 드라이브 공간의 비율을 변경하여 권장되는 후보 목록을 새로 고칠 수 있습니다. 선택한 내용에 따라 가장 적합한 후보가 표시됩니다.



== 왜 내 모든 볼륨이 보이지 않나요?

미러링된 쌍의 기본 볼륨을 선택하면 목록에 모든 적격 볼륨이 표시됩니다.

사용할 수 없는 볼륨은 해당 목록에 표시되지 않습니다. 볼륨은 다음과 같은 이유로 적합하지 않을 수 있습니다.

* 볼륨이 최적이 아닙니다.
* 볼륨이 이미 미러링 관계에 있습니다.
* 동기식 미러링의 경우 미러링된 쌍의 운영 볼륨과 2차 볼륨이 표준 볼륨이어야 합니다. 씬 볼륨 또는 스냅샷 볼륨일 수 없습니다.
* 비동기식 미러링의 경우 씬 볼륨에 자동 확장이 설정되어 있어야 합니다.



NOTE: EF600 및 EF300 컨트롤러의 경우 비동기식 미러링 쌍의 운영 볼륨과 2차 볼륨이 동일한 프로토콜, 트레이 레벨, 세그먼트 크기, 보안 유형 및 RAID 레벨과 일치해야 합니다. 사용 가능한 볼륨 목록에 비적격한 비동기 미러링 쌍이 나타나지 않습니다.



== 원격 스토리지 배열의 모든 볼륨이 표시되지 않는 이유는 무엇입니까?

원격 스토리지 어레이에서 보조 볼륨을 선택할 경우 목록에 해당 미러링된 쌍에 대해 적합한 볼륨이 모두 표시됩니다.

사용할 수 없는 볼륨은 해당 목록에 표시되지 않습니다. 볼륨은 다음과 같은 이유로 적합하지 않을 수 있습니다.

* 볼륨은 스냅샷 볼륨과 같이 비표준 볼륨입니다.
* 볼륨이 최적이 아닙니다.
* 볼륨이 이미 미러링 관계에 있습니다.
* 비동기식 미러링의 경우 운영 볼륨과 2차 볼륨 간의 씬 볼륨 특성이 일치하지 않습니다.
* DA(Data Assurance)를 사용하는 경우 운영 볼륨과 보조 볼륨의 DA 설정이 동일해야 합니다.
+
** 운영 볼륨이 DA를 사용하는 경우 보조 볼륨은 DA를 활성화해야 합니다.
** 운영 볼륨이 DA를 사용하지 않는 경우 보조 볼륨을 DA로 설정하지 않아야 합니다.


* 비동기식 미러링의 경우 운영 볼륨과 2차 볼륨의 드라이브 보안 기능이 동일해야 합니다.
+
** 운영 볼륨이 FIPS를 지원할 수 있는 경우 보조 볼륨은 FIPS를 지원해야 합니다.
** 기본 볼륨이 FDE를 지원할 수 있는 경우 보조 볼륨은 FDE를 지원할 수 있어야 합니다.
** 주 볼륨이 드라이브 보안을 사용하지 않는 경우 보조 볼륨이 드라이브 보안을 사용하지 않아야 합니다.






== 동기화 우선 순위가 동기화 속도에 어떤 영향을 미칩니까?

동기화 우선 순위는 시스템 성능과 관련하여 동기화 작업에 할당되는 처리 시간을 정의합니다.

운영 볼륨의 컨트롤러 소유자가 이 작업을 백그라운드에서 수행합니다. 동시에 컨트롤러 소유자가 운영 볼륨에 대한 로컬 I/O 쓰기 및 보조 볼륨에 대한 관련 원격 쓰기를 처리합니다. 재동기화는 컨트롤러 처리 리소스를 입출력 작업에서 전환하므로 재동기화는 호스트 애플리케이션의 성능에 영향을 미칠 수 있습니다.

동기화 우선 순위가 얼마나 오래 걸릴 수 있고 동기화 우선 순위가 시스템 성능에 어떤 영향을 미칠 수 있는지 결정할 수 있도록 이 지침을 염두에 두십시오.

다음과 같은 우선 순위가 있습니다.

* 최저
* 낮음
* 중간
* 높음
* 최고


우선 순위가 가장 낮은 속도는 시스템 성능을 지원하지만 재동기화에 더 많은 시간이 걸립니다. 우선 순위가 가장 높은 속도가 재동기화를 지원하지만 시스템 성능이 저하될 수 있습니다.

이 지침은 우선 순위 간의 차이를 대략적으로 나타냅니다.

[cols="45h,~"]
|===
| 전체 동기화의 우선 순위 속도 | 최고 동기화 속도에 비해 경과된 시간입니다 


 a| 
최저
 a| 
최고 우선 순위인 경우 약 8배



 a| 
낮음
 a| 
최고 우선 순위인 경우 약 6배



 a| 
중간
 a| 
가장 높은 우선 순위에서 약 3배 반 정도 소요됩니다.



 a| 
높음
 a| 
최고 우선 순위보다 약 2배 긴 시간.

|===
볼륨 크기 및 호스트 I/O 속도 로드는 동기화 시간 비교에 영향을 줍니다.



== 수동 동기화 정책을 사용하는 것이 권장되는 이유는 무엇입니까?

수동 재동기화는 재동기화 프로세스를 관리하여 데이터를 복구할 수 있는 최적의 기회를 제공하기 때문에 권장됩니다.

자동 재동기화 정책을 사용하고 재동기화 중에 간헐적인 통신 문제가 발생하는 경우 보조 볼륨의 데이터가 일시적으로 손상될 수 있습니다. 재동기화가 완료되면 데이터가 수정됩니다.
