---
permalink: um-manage/how-import-settings-works.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, import, settings, 
summary: Unified Manager를 사용하여 한 스토리지 어레이에서 여러 스토리지 어레이로 설정을 가져올 수 있습니다. 설정 가져오기 기능은 네트워크에 여러 어레이를 구성해야 할 때 시간을 절약할 수 있는 일괄 작업입니다. 
---
= 가져오기 설정 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity Unified Manager를 사용하여 한 스토리지 어레이에서 여러 스토리지 어레이로 설정을 가져올 수 있습니다. 설정 가져오기 기능은 네트워크에 여러 어레이를 구성해야 할 때 시간을 절약할 수 있는 일괄 작업입니다.



== 가져올 수 있는 설정입니다

다음 구성을 여러 어레이로 가져올 수 있습니다.

* * Alerts * -- e-메일, syslog 서버 또는 SNMP 서버를 사용하여 중요한 이벤트를 관리자에게 보내는 경고 방법입니다.
* * AutoSupport * -- 스토리지 어레이의 상태를 모니터링하고 자동 디스패치를 기술 지원 부서에 보내는 기능입니다.
* * 디렉터리 서비스 * -- LDAP(Lightweight Directory Access Protocol) 서버 및 디렉터리 서비스(예: Microsoft의 Active Directory)를 통해 관리되는 사용자 인증 방법입니다.
* * 스토리지 구성 * -- 다음과 관련된 구성:
+
** 볼륨(일반 및 비리포지토리 볼륨만 해당)
** 볼륨 그룹 및 풀
** 핫 스페어 드라이브 할당


* * 시스템 설정 * -- 다음과 관련된 구성:
+
** 볼륨에 대한 미디어 스캔 설정입니다
** SSD 설정
** 자동 로드 밸런싱(호스트 연결 보고 포함 안 함)






== 구성 워크플로우

설정을 가져오려면 다음 워크플로를 따릅니다.

. 소스로 사용할 스토리지 배열에서 System Manager를 사용하여 설정을 구성합니다.
. 타겟으로 사용할 스토리지 어레이에서 System Manager를 사용하여 구성을 백업합니다.
. Unified Manager에서 * 관리 * 페이지로 이동하여 설정을 가져옵니다.
. Operations * 페이지에서 설정 가져오기 작업의 결과를 검토합니다.

