---
permalink: um-manage/mirroring-configuration-workflow.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, configuration, workflow 
summary: Unified Manager에서 비동기식 또는 동기식 미러링을 구성한 다음 System Manager를 사용하여 동기화를 관리합니다. 
---
= 미러링 구성 워크플로우
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager에서 비동기식 또는 동기식 미러링을 구성한 다음 System Manager를 사용하여 동기화를 관리합니다.



== 비동기식 미러링 워크플로우

비동기식 미러링에는 다음 워크플로우가 포함됩니다.

. Unified Manager에서 초기 구성을 수행합니다.
+
.. 로컬 스토리지 배열을 데이터 전송 소스로 선택합니다.
.. 로컬 스토리지의 운영 볼륨과 원격 스토리지의 보조 볼륨을 위한 컨테이너인 기존 미러 정합성 보장 그룹을 생성하거나 선택합니다. 운영 볼륨과 2차 볼륨을 "미러링된 쌍"이라고 합니다. 미러 정합성 보장 그룹을 처음 생성하는 경우 수동 동기화 또는 예약된 동기화를 수행할지 여부를 지정합니다.
.. 로컬 스토리지 어레이에서 운영 볼륨을 선택한 다음 예약된 용량을 확인합니다. 예약된 용량은 복제 작업에 사용할 물리적 할당 용량입니다.
.. 원격 스토리지 시스템을 전송 대상, 보조 볼륨으로 선택한 다음 예약된 용량을 결정합니다.
.. 운영 볼륨에서 보조 볼륨으로 초기 데이터 전송을 시작합니다. 볼륨 크기에 따라 이 초기 전송에 몇 시간이 걸릴 수 있습니다.


. 초기 동기화 진행률을 확인합니다.
+
.. Unified Manager에서 로컬 어레이에 대한 System Manager를 시작합니다.
.. System Manager에서 미러링 작업의 상태를 봅니다. 미러링이 완료되면 미러링된 쌍의 상태가 "Optimal(최적)"입니다.


. 선택적으로 System Manager에서 후속 데이터 전송을 다시 예약하거나 수동으로 수행할 수 있습니다. 운영 볼륨에서 2차 볼륨으로 새 블록과 변경된 블록만 전송합니다.
+
[NOTE]
====
비동기식 복제는 정기적으로 수행되므로 시스템에서 변경된 블록을 통합하고 네트워크 대역폭을 보존할 수 있습니다. 쓰기 처리량과 쓰기 지연 시간에 미치는 영향은 미미합니다.

====




== 동기 미러링 워크플로우

동기식 미러링에는 다음 워크플로우가 포함됩니다.

. Unified Manager에서 초기 구성을 수행합니다.
+
.. 데이터 전송을 위한 소스로 로컬 스토리지 배열을 선택합니다.
.. 로컬 스토리지 어레이에서 운영 볼륨을 선택합니다.
.. 데이터 전송 대상으로 원격 스토리지 시스템을 선택한 다음 보조 볼륨을 선택합니다.
.. 동기화 및 재동기화 우선 순위를 선택합니다.
.. 운영 볼륨에서 보조 볼륨으로 초기 데이터 전송을 시작합니다. 볼륨 크기에 따라 이 초기 전송에 몇 시간이 걸릴 수 있습니다.


. 초기 동기화 진행률을 확인합니다.
+
.. Unified Manager에서 로컬 어레이에 대한 System Manager를 시작합니다.
.. System Manager에서 미러링 작업의 상태를 봅니다. 미러링이 완료되면 미러링된 쌍의 상태가 "Optimal(최적)"입니다. 두 스토리지는 정상 작업을 통해 동기화된 상태를 유지하려고 합니다. 운영 볼륨에서 2차 볼륨으로 새 블록과 변경된 블록만 전송합니다.


. 선택적으로 System Manager에서 동기화 설정을 변경할 수 있습니다.
+
[NOTE]
====
동기식 복제는 지속적이기 때문에 두 사이트 간의 복제 링크는 충분한 대역폭 기능을 제공해야 합니다.

====

