---
permalink: um-manage/mirroring-overview.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, 
summary: Unified Manager에는 SANtricity 미러링 기능을 위한 구성 옵션이 포함되어 있어 관리자가 데이터 보호를 위해 두 스토리지 어레이 간에 데이터를 복제할 수 있습니다. 
---
= 미러링의 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager에는 SANtricity 미러링 기능을 위한 구성 옵션이 포함되어 있어 관리자가 데이터 보호를 위해 두 스토리지 어레이 간에 데이터를 복제할 수 있습니다.

[NOTE]
====
EF600 또는 EF300 스토리지 시스템에서는 동기식 미러링을 사용할 수 없습니다.

====


== 미러링 유형

SANtricity 애플리케이션에는 두 가지 유형의 미러링, 즉 비동기식과 동기식이 있습니다.

비동기식 미러링은 데이터 볼륨을 필요 시 또는 일정에 따라 복제하여 데이터 손상 또는 손실로 인한 다운타임을 최소화 또는 방지합니다. 비동기식 미러링은 특정 시점에 기본 볼륨의 상태를 캡처하고 마지막 이미지 캡처 이후 변경된 데이터만 복사합니다. 운영 사이트를 즉시 업데이트할 수 있으며 대역폭이 허용할 경우 보조 사이트를 업데이트할 수 있습니다. 네트워크 리소스를 사용할 수 있게 되면 정보가 캐시되어 나중에 전송됩니다. 이러한 유형의 미러링은 백업 및 아카이빙과 같은 주기적인 프로세스에 이상적입니다.

동기식 미러링은 데이터 볼륨을 실시간으로 복제하여 지속적인 가용성을 보장합니다. 두 스토리지 어레이 중 하나에서 재해가 발생할 경우 중요 데이터의 복사본을 사용할 수 있으므로 RPO(복구 시점 목표)를 달성할 수 있습니다. 복제본은 운영 볼륨에 쓸 때마다 보조 볼륨에 쓰기가 수행되므로 항상 운영 데이터와 동일합니다. 보조 볼륨이 운영 볼륨에서 수행된 변경 사항으로 업데이트될 때까지 호스트에 쓰기가 성공했다는 확인 메시지가 표시되지 않습니다. 이러한 유형의 미러링은 재해 복구와 같은 비즈니스 연속성 목적으로 이상적입니다.



== 미러링 유형의 차이점

다음 표에서는 두 미러링 유형의 주요 차이점을 설명합니다.

[cols="1a,1a,1a"]
|===
| 속성 | 비동기식 | 동기식이다 


 a| 
복제 방법입니다
 a| 
시점 -- 미러링은 사용자 정의 일정에 따라 필요 시 또는 자동으로 수행됩니다.
 a| 
연속 -- 미러링은 모든 호스트 쓰기에서 데이터를 복사하여 지속적으로 자동 실행됩니다.



 a| 
거리
 a| 
어레이 간 장거리 지원. 일반적으로 거리는 네트워크 및 채널 확장 기술의 성능에 의해서만 제한됩니다.
 a| 
어레이 간 거리가 짧아집니다. 일반적으로 지연 시간 및 애플리케이션 성능 요구 사항을 충족하려면 로컬 스토리지 어레이에서 약 10km(6.2마일) 이내에 있어야 합니다.



 a| 
통신 방법
 a| 
표준 IP 또는 Fibre Channel 네트워크
 a| 
Fibre Channel 네트워크만 해당.



 a| 
볼륨 유형
 a| 
표준 또는 얇은.
 a| 
표준 전용.

|===