---
permalink: um-manage/mirroring-terminology.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, mirroring, terminology 
summary: 미러링 조건이 스토리지 어레이에 어떻게 적용되는지 알아보십시오. 
---
= 미러링 용어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
미러링 조건이 스토리지 어레이에 어떻게 적용되는지 알아보십시오.

[cols="25h,~"]
|===
| 기간 | 설명 


 a| 
로컬 스토리지 시스템입니다
 a| 
로컬 스토리지 배열은 사용자가 수행하는 스토리지 배열입니다.



 a| 
미러 정합성 보장 그룹
 a| 
미러 정합성 보장 그룹은 하나 이상의 미러링된 쌍에 대한 컨테이너입니다. 비동기식 미러링 작업의 경우 미러 정합성 보장 그룹을 생성해야 합니다. 그룹의 모든 미러링된 쌍이 동시에 재동기화되므로 일관된 복구 지점이 유지됩니다.

동기식 미러링은 미러 정합성 보장 그룹을 사용하지 않습니다.



 a| 
미러링 쌍
 a| 
미러링된 쌍은 기본 볼륨 및 보조 볼륨이라는 두 개의 볼륨으로 구성됩니다.

비동기식 미러링에서는 미러링된 쌍이 항상 미러 정합성 보장 그룹에 속합니다. 쓰기 작업은 먼저 운영 볼륨에 대해 수행된 다음 보조 볼륨에 복제됩니다. 미러 정합성 보장 그룹의 미러링된 각 쌍은 동일한 동기화 설정을 공유합니다.



 a| 
운영 볼륨
 a| 
미러링된 쌍의 기본 볼륨은 미러링될 소스 볼륨입니다.



 a| 
원격 스토리지 시스템
 a| 
원격 스토리지 시스템은 일반적으로 미러링 구성의 데이터 복제본을 보관하는 보조 사이트로 지정됩니다.



 a| 
예약된 용량입니다
 a| 
예약된 용량은 복제 서비스 작업 및 스토리지 객체에 사용되는 물리적 할당 용량입니다. 호스트에서 직접 읽을 수 없습니다.

이러한 볼륨은 컨트롤러가 운영 상태에서 미러링을 유지하는 데 필요한 정보를 지속적으로 저장할 수 있도록 하기 위해 필요합니다. 여기에는 델타 로그 및 쓰기 시 복사 데이터와 같은 정보가 포함됩니다.



 a| 
2차 볼륨
 a| 
미러링된 쌍의 보조 볼륨은 일반적으로 보조 사이트에 위치하며 데이터 복제본을 보관합니다.



 a| 
동기화
 a| 
동기화는 로컬 스토리지와 원격 스토리지 시스템 간의 초기 동기화에서 수행됩니다. 동기화는 통신 중단 후 운영 볼륨과 2차 볼륨의 동기화가 중단된 경우에도 발생합니다. 통신 링크가 다시 작동되면 복제되지 않은 모든 데이터가 보조 볼륨의 스토리지 시스템에 동기화됩니다.

|===