---
permalink: um-manage/overview-upgrade-center-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, upgrade, center 
summary: 업그레이드 센터에서 여러 스토리지 어레이에 대한 SANtricity OS 소프트웨어 및 NVSRAM 업그레이드를 관리할 수 있습니다. 
---
= 업그레이드 센터 개요
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드 센터에서 여러 스토리지 어레이에 대한 SANtricity OS 소프트웨어 및 NVSRAM 업그레이드를 관리할 수 있습니다.



== 업그레이드는 어떻게 작동합니까?

최신 OS 소프트웨어를 다운로드한 다음 하나 이상의 어레이를 업그레이드합니다.



=== 워크플로우 업그레이드

다음 단계에서는 소프트웨어 업그레이드를 수행하기 위한 높은 수준의 워크플로우를 제공합니다.

. Support 사이트에서 최신 SANtricity OS 소프트웨어 파일을 다운로드합니다(지원 페이지의 Unified Manager에서 링크 사용 가능). 관리 호스트 시스템(브라우저에서 Unified Manager에 액세스하는 호스트)에 파일을 저장한 다음 파일의 압축을 풉니다.
. Unified Manager에서 SANtricity OS 소프트웨어 파일과 NVSRAM 파일을 리포지토리(파일이 저장되는 웹 서비스 프록시 서버 영역)에 로드합니다. 업그레이드 센터 [SANtricity OS 소프트웨어 업그레이드 또는 업그레이드 센터 > 소프트웨어 저장소 관리] 메뉴에서 파일을 추가할 수 있습니다.
. 저장소에 파일이 로드되면 업그레이드에 사용할 파일을 선택할 수 있습니다. SANtricity OS 소프트웨어 업그레이드 페이지(메뉴: 업그레이드 센터 [SANtricity OS 소프트웨어 업그레이드])에서 SANtricity OS 소프트웨어 파일과 NVSRAM 파일을 선택합니다. 소프트웨어 파일을 선택하면 호환되는 스토리지 배열 목록이 이 페이지에 표시됩니다. 그런 다음 새 소프트웨어로 업그레이드할 스토리지 어레이를 선택합니다. (호환되지 않는 어레이는 선택할 수 없습니다.)
. 그런 다음 즉시 소프트웨어 전송 및 활성화를 시작하거나 나중에 활성화할 파일을 준비하도록 선택할 수 있습니다. 업그레이드 프로세스 중에 Unified Manager는 다음 작업을 수행합니다.
+
.. 스토리지 배열의 상태 점검을 수행하여 업그레이드가 완료되지 못할 수 있는 조건이 있는지 확인합니다. 상태 확인에 실패한 어레이가 있으면 해당 특정 어레이를 건너뛰고 다른 어레이를 계속 업그레이드할 수 있습니다. 또는 전체 프로세스를 중지하고 통과하지 못한 어레이의 문제를 해결할 수 있습니다.
.. 각 컨트롤러로 업그레이드 파일을 전송합니다.
.. 컨트롤러를 재부팅하여 한 번에 하나의 컨트롤러인 새로운 SANtricity OS 소프트웨어를 활성화합니다. 활성화 중에 기존 SANtricity OS 파일이 새 파일로 대체됩니다.
+
[NOTE]
====
나중에 소프트웨어가 활성화되도록 지정할 수도 있습니다.

====






=== 즉시 또는 단계별 업그레이드

업그레이드를 즉시 활성화하거나 나중에 스테이징할 수 있습니다. 다음과 같은 이유로 나중에 정품 인증을 선택할 수 있습니다.

* * 시간 * -- 소프트웨어를 활성화하는 데 시간이 오래 걸릴 수 있으므로 I/O 부하가 더 가벼워질 때까지 기다려야 할 수 있습니다. I/O 로드 및 캐시 크기에 따라 컨트롤러 업그레이드를 완료하는 데 일반적으로 15~25분 정도 걸릴 수 있습니다. 활성화 중에 컨트롤러가 재부팅되고 페일오버되므로 업그레이드가 완료될 때까지 성능이 평소보다 저하될 수 있습니다.
* * 패키지 유형 * -- 다른 스토리지 어레이의 파일을 업그레이드하기 전에 한 스토리지 어레이에서 새 소프트웨어 및 펌웨어를 테스트할 수 있습니다.


스테이징된 소프트웨어를 활성화하려면 메뉴 [업그레이드 센터]로 이동한 후 SANtricity OS 컨트롤러 소프트웨어 업그레이드라고 표시된 영역에서 * 활성화 * 를 클릭합니다.



=== 상태 점검

상태 점검은 업그레이드 프로세스의 일부로 실행되지만 시작하기 전에 별도로 상태 점검을 실행할 수도 있습니다(메뉴: 업그레이드 센터 [사전 업그레이드 상태 점검]).

상태 점검을 통해 모든 스토리지 시스템 구성요소를 평가하여 업그레이드를 진행할 수 있는지 확인합니다. 다음 조건에서는 업그레이드가 되지 않을 수 있습니다.

* 할당된 드라이브에 오류가 발생했습니다
* 핫 스페어가 사용 중입니다
* 볼륨 그룹이 불완전합니다
* 단독 운영 실행 중
* 볼륨이 누락되었습니다
* 컨트롤러가 최적화되지 않은 상태입니다
* 이벤트 로그 이벤트의 수가 너무 넘습니다
* 구성 데이터베이스 유효성 검사에 실패했습니다
* DACstore의 이전 버전이 있는 드라이브입니다




== 업그레이드하기 전에 알아야 할 사항은 무엇입니까?

여러 스토리지 시스템을 업그레이드하기 전에 계획의 일환으로 주요 고려 사항을 검토하십시오.



=== 현재 버전

검색된 각 스토리지 시스템에 대해 Unified Manager의 관리 페이지에서 현재 SANtricity OS 소프트웨어 버전을 확인할 수 있습니다. 이 버전은 SANtricity OS 소프트웨어 열에 표시됩니다. 각 행에서 SANtricity OS 버전을 클릭하면 컨트롤러 펌웨어 및 NVSRAM 정보를 팝업 대화 상자에서 사용할 수 있습니다.



=== 업그레이드가 필요한 기타 구성 요소

업그레이드 프로세스 중에 호스트가 컨트롤러와 올바르게 상호 작용할 수 있도록 호스트의 다중 경로/페일오버 드라이버 또는 HBA 드라이버를 업그레이드해야 할 수도 있습니다.

호환성 정보는 을 참조하십시오 https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스"^]. 또한 운영 체제의 Express Guide에 있는 절차를 참조하십시오. Express 가이드는 에서 사용할 수 있습니다 https://docs.netapp.com/us-en/e-series/index.html["E-Series 및 SANtricity 설명서"^].



=== 듀얼 컨트롤러

스토리지 어레이에 2개의 컨트롤러가 포함되어 있고 다중 경로 드라이버가 설치되어 있는 경우, 업그레이드가 진행되는 동안 스토리지 어레이에서 I/O를 계속 처리할 수 있습니다. 업그레이드 중에 다음 프로세스가 발생합니다.

. 컨트롤러 A는 모든 LUN을 컨트롤러 B로 페일오버합니다
. 컨트롤러 A에서 업그레이드가 발생합니다
. 컨트롤러 A는 LUN과 모든 컨트롤러 B의 LUN을 백업합니다.
. 컨트롤러 B에서 업그레이드가 발생합니다


업그레이드가 완료된 후 컨트롤러 간에 볼륨을 수동으로 재배포하여 볼륨이 올바른 소유 컨트롤러로 돌아가도록 해야 할 수 있습니다.
