---
permalink: sm-settings/access-management-tokens.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access management, tokens 
summary: 액세스 토큰은 사용자 이름과 암호를 노출하지 않고 스토리지에 대한 액세스를 제공합니다. 
---
= 액세스 토큰
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
액세스 토큰은 사용자 이름과 암호를 노출하지 않고 REST API 또는 CLI(Command Line Interface)를 사용하여 인증 방법을 제공합니다. 토큰은 특정 사용자(LDAP 사용자 포함)에 연결되며 권한 집합 및 만료가 포함됩니다.



== SAML 및 JSON 웹 토큰 액세스

기본적으로 SAML이 활성화된 시스템은 기존 명령줄 도구에 대한 액세스를 허용하지 않습니다. MFA 워크플로우에서 인증을 위해 ID 공급자 서버로 리디렉션해야 하므로 REST API 및 CLI가 효과적으로 작동하지 않습니다. 따라서 사용자는 MFA를 통해 인증을 받아야 하는 토큰을 System Manager에서 생성해야 합니다.


NOTE: SAML이 웹 토큰을 사용하도록 설정할 필요는 없지만 최고 수준의 보안을 위해 SAML이 권장됩니다.



== 토큰 생성 및 사용 워크플로

. System Manager에서 토큰을 생성하고 해당 만료일을 확인합니다.
. 토큰 텍스트를 클립보드에 복사하거나 파일로 다운로드한 다음 안전한 위치에 토큰 텍스트를 저장합니다.
. 다음과 같이 토큰을 사용합니다.
+
** * REST API *: REST API 요청에서 토큰을 사용하려면 요청에 HTTP 헤더를 추가하십시오. 예를 들면 다음과 같습니다.
`Authorization: Bearer _<access-token-value>_`
** * Secure CLI *: CLI에서 토큰을 사용하려면 명령줄에 토큰 값을 추가하거나 토큰 값이 포함된 파일의 경로를 사용합니다. 예를 들면 다음과 같습니다.
+
*** 명령줄에서 토큰 값: `-t _access-token-value_`
*** 토큰 값이 포함된 파일의 경로: `-T _access-token-file_`






자세한 내용:

* link:access-management-tokens-create.html["액세스 토큰을 생성합니다"]
* link:access-management-tokens-edit.html["액세스 토큰을 편집합니다"]
* link:access-management-tokens-revoke.html["액세스 토큰을 취소합니다"]

