---
permalink: sm-settings/access-management-tokens-create.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access management, create tokens 
summary: 사용자 이름과 암호 대신 REST API 또는 명령줄 인터페이스를 사용하여 인증하는 데 사용되는 액세스 토큰을 만들 수 있습니다. 
---
= SANtricity System Manager에서 액세스 토큰 생성
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자 이름과 암호 대신 REST API 또는 CLI(Command Line Interface)를 사용하여 인증할 액세스 토큰을 생성할 수 있습니다.


NOTE: 토큰에는 암호가 없으므로 주의해서 관리해야 합니다.

.단계
. 메뉴: 설정 [Access Management](액세스 관리)를 선택합니다.
. Access Tokens * 탭을 선택합니다.
. 액세스 토큰 설정 보기/편집 * 을 선택합니다. 대화 상자에서 * 액세스 토큰 사용 * 확인란이 선택되어 있는지 확인합니다. 대화 상자를 닫으려면 * 저장 * 을 클릭합니다.
. 액세스 토큰 만들기 * 를 선택합니다.
. 대화 상자에서 토큰이 유효할 기간을 선택합니다.
+

NOTE: 토큰이 만료되면 사용자의 인증 시도가 실패합니다.

. 생성 * 을 클릭합니다
. 대화 상자에서 다음 중 하나를 선택합니다.
+
** * 복사 * 를 눌러 토큰 텍스트를 클립보드에 저장합니다.
** * 토큰 텍스트를 파일에 저장하려면 * 다운로드 * 를 클릭합니다.
+

NOTE: 토큰 텍스트를 저장해야 합니다. 대화 상자를 닫기 전에 텍스트를 볼 수 있는 유일한 기회입니다.



. 닫기 * 를 클릭합니다.
. 다음과 같이 토큰을 사용합니다.
+
** * REST API *: REST API 요청에서 토큰을 사용하려면 요청에 HTTP 헤더를 추가하십시오. 예를 들면 다음과 같습니다.
`Authorization: Bearer _<access-token-value>_`
** * Secure CLI *: CLI에서 토큰을 사용하려면 명령줄에 토큰 값을 추가하거나 토큰 값이 포함된 파일의 경로를 사용합니다. 예를 들면 다음과 같습니다.
+
*** 명령줄에서 토큰 값: `-t _access-token-value_`
*** 토큰 값이 포함된 파일의 경로: `-T _access-token-file_`
+

NOTE: 사용자 이름, 암호 또는 토큰이 지정되지 않은 경우 CLI에서 명령줄에 액세스 토큰 값을 입력하라는 메시지를 표시합니다.






