---
permalink: sm-settings/add-directory-server.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, directory, server, 
summary: 액세스 관리에 대한 인증을 구성하려면 스토리지 어레이와 LDAP 서버 간의 통신을 설정한 다음 LDAP 사용자 그룹을 스토리지의 사전 정의된 역할에 매핑할 수 있습니다. 
---
= LDAP 디렉토리 서버를 추가합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
액세스 관리에 대한 인증을 구성하려면 스토리지 어레이와 LDAP 서버 간의 통신을 설정한 다음 LDAP 사용자 그룹을 스토리지의 사전 정의된 역할에 매핑할 수 있습니다.

.시작하기 전에
* 보안 관리자 권한이 포함된 사용자 프로필로 로그인해야 합니다. 그렇지 않으면 Access Management 기능이 나타나지 않습니다.
* 사용자 그룹은 디렉토리 서비스에 정의되어 있어야 합니다.
* 도메인 이름, 서버 URL, 그리고 선택적으로 바인딩 계정 사용자 이름 및 암호를 포함하여 LDAP 서버 자격 증명을 사용할 수 있어야 합니다.
* 보안 프로토콜을 사용하는 LDAPS 서버의 경우 로컬 시스템에 LDAP 서버의 인증서 체인을 설치해야 합니다.


.이 작업에 대해
디렉토리 서버를 추가하는 과정은 2단계로 이루어집니다. 먼저 도메인 이름과 URL을 입력합니다. 서버에서 보안 프로토콜을 사용하는 경우 비표준 서명 기관에서 서명한 경우 인증을 위한 CA 인증서도 업로드해야 합니다. 바인딩 계정에 대한 자격 증명이 있는 경우 사용자 계정 이름 및 암호를 입력할 수도 있습니다. 그런 다음 LDAP 서버의 사용자 그룹을 스토리지의 사전 정의된 역할에 매핑합니다.

[NOTE]
====
LDAP 서버를 추가하는 절차 중에는 레거시 관리 인터페이스가 비활성화됩니다. 기존 관리 인터페이스(symbol)는 스토리지 배열과 관리 클라이언트 간의 통신 방법입니다. 이 기능을 해제하면 스토리지 어레이와 관리 클라이언트에서 더욱 안전한 통신 방법(https를 통한 REST API)을 사용합니다.

====
.단계
. 메뉴: 설정 [Access Management](액세스 관리)를 선택합니다.
. 디렉터리 서비스 탭에서 * 디렉터리 서버 추가 * 를 선택합니다.
+
디렉토리 서버 추가 대화 상자가 열립니다.

. 서버 설정 탭에서 LDAP 서버의 자격 증명을 입력합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
* 구성 설정 *



 a| 
도메인
 a| 
LDAP 서버의 도메인 이름을 입력합니다. 여러 도메인의 경우 쉼표로 구분된 목록에 도메인을 입력합니다. 도메인 이름은 로그인(_username_@_domain_)에서 인증할 디렉토리 서버를 지정하는 데 사용됩니다.



 a| 
서버 URL
 a| 
LDAP 서버에 액세스하기 위한 URL을 "LDAP[s]://* host*: * port*" 형식으로 입력합니다.



 a| 
인증서 업로드(선택 사항)
 a| 

NOTE: 이 필드는 LDAPS 프로토콜이 위의 서버 URL 필드에 지정된 경우에만 나타납니다.

찾아보기 * 를 클릭하고 업로드할 CA 인증서를 선택합니다. LDAP 서버를 인증하는 데 사용되는 신뢰할 수 있는 인증서 또는 인증서 체인입니다.



 a| 
BIND ACCOUNT(선택 사항)
 a| 
LDAP 서버에 대한 검색 쿼리 및 그룹 내에서 검색할 읽기 전용 사용자 계정을 입력합니다. LDAP 유형 형식으로 계정 이름을 입력합니다. 예를 들어 바인딩 사용자가 "bindacct"라고 하는 경우 "CN=bindacct, CN=Users, DC=CPoC, DC=local"과 같은 값을 입력할 수 있습니다.



 a| 
바인딩 암호(선택 사항)
 a| 

NOTE: 이 필드는 위에 바인딩 계정을 입력할 때 나타납니다.

바인딩 계정의 암호를 입력합니다.



 a| 
추가하기 전에 서버 연결을 테스트합니다
 a| 
스토리지 배열이 입력한 LDAP 서버 구성과 통신할 수 있는지 확인하려면 이 확인란을 선택합니다. 이 테스트는 대화 상자 하단의 * 추가 * 를 클릭하면 발생합니다. 이 확인란을 선택하고 테스트에 실패하면 구성이 추가되지 않습니다. 오류를 해결하거나 확인란을 선택 취소해야 테스트를 건너뛰고 구성을 추가할 수 있습니다.



 a| 
** 권한 설정**



 a| 
검색 기준 DN
 a| 
LDAP 컨텍스트를 입력하여 사용자를 검색합니다(일반적으로 의 형식) `CN=Users, DC=cpoc, DC=local`.



 a| 
사용자 이름 특성입니다
 a| 
인증을 위해 사용자 ID에 바인딩된 특성을 입력합니다. 예를 들어, 'sAMAccountName'을 입력합니다.



 a| 
그룹 속성
 a| 
그룹 대 역할 매핑에 사용되는 사용자의 그룹 속성 목록을 입력합니다. 예를 들어, memberOf , managedObjects 등이 있습니다.

|===
====
. [역할 매핑]** 탭을 클릭합니다.
. 미리 정의된 역할에 LDAP 그룹을 할당합니다. 그룹은 여러 개의 역할을 할당할 수 있습니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
* 매핑 *



 a| 
그룹 DN
 a| 
매핑할 LDAP 사용자 그룹의 그룹 DN(고유 이름)을 지정합니다. 정규식이 지원됩니다. 이러한 특수 정규식 문자는 정규식 패턴의 일부가 아닌 경우 백슬래시("\")로 이스케이프되어야 합니다. \.[]{}() <>*+-=!?^$|



 a| 
역할
 a| 
필드를 클릭하고 그룹 DN에 매핑할 스토리지 시스템의 역할 중 하나를 선택합니다. 이 그룹에 포함할 각 역할을 개별적으로 선택해야 합니다. SANtricity 시스템 관리자에 로그인하려면 모니터 역할이 다른 역할과 함께 필요합니다. 매핑된 역할에는 다음 권한이 포함됩니다.

** * 스토리지 관리자 * -- 스토리지 객체(예: 볼륨 및 디스크 풀)에 대한 전체 읽기/쓰기 액세스이지만 보안 구성에 대한 액세스는 없습니다.
** * 보안 관리자 * -- 액세스 관리, 인증서 관리, 감사 로그 관리 및 레거시 관리 인터페이스(기호)를 켜거나 끌 수 있는 기능의 보안 구성에 액세스합니다.
** * 지원 관리자 * -- 스토리지 어레이의 모든 하드웨어 리소스, 장애 데이터, MEL 이벤트 및 컨트롤러 펌웨어 업그레이드에 액세스합니다. 스토리지 객체 또는 보안 구성에 대한 액세스 권한이 없습니다.
** * Monitor * -- 모든 스토리지 객체에 대한 읽기 전용 액세스이지만 보안 구성에 대한 액세스는 없습니다.


|===
====
+
[NOTE]
====
Monitor 역할은 관리자를 포함한 모든 사용자에게 필요합니다. Monitor 역할이 없는 사용자에 대해서는 System Manager가 올바르게 작동하지 않습니다.

====
. 필요한 경우 * 다른 매핑 추가 * 를 클릭하여 그룹 대 역할 매핑을 추가로 입력합니다.
. 매핑을 마쳤으면 * 추가 * 를 클릭합니다.
+
시스템은 스토리지 시스템 및 LDAP 서버가 통신할 수 있도록 검증을 수행합니다. 오류 메시지가 나타나면 대화 상자에 입력한 자격 증명을 확인하고 필요한 경우 정보를 다시 입력합니다.


