---
permalink: sm-settings/add-trap-destinations-for-snmp-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, add, trap, destinations, SNMP, alerts, 
summary: SNMP 트랩을 보내기 위해 최대 10대의 서버를 추가할 수 있습니다. 
---
= SNMP 경고에 대한 트랩 대상을 추가합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMP 트랩을 보내기 위해 최대 10대의 서버를 추가할 수 있습니다.

.시작하기 전에
* 추가하려는 네트워크 서버는 SNMP 서비스 애플리케이션으로 구성되어야 합니다. 이벤트 모니터가 해당 주소로 트랩 메시지를 보낼 수 있도록 이 서버의 네트워크 주소(IPv4 또는 IPv6 주소)가 필요합니다. 둘 이상의 서버를 사용할 수 있습니다(최대 10대의 서버가 허용됨).
* MIB(Management Information Base) 파일이 SNMP 서비스 응용 프로그램을 사용하여 서버에서 복사 및 컴파일되었습니다. 이 MIB 파일은 모니터링 및 관리되는 데이터를 정의합니다.
+
MIB 파일이 없는 경우 NetApp Support 사이트에서 얻을 수 있습니다.

+
** 로 이동합니다 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"^].
** Downloads * 를 클릭한 다음 * Downloads * 를 선택합니다.
** E-Series SANtricity OS 컨트롤러 소프트웨어 * 를 클릭합니다.
** 최신 릴리스 다운로드 * 를 선택합니다.
** 로그인합니다.
** 주의 사항 및 라이센스 계약에 동의합니다.
** 컨트롤러 유형에 대한 MIB 파일이 표시될 때까지 아래로 스크롤한 다음 링크를 클릭하여 파일을 다운로드합니다.




.단계
. 설정 [알림] 메뉴를 선택합니다.
. SNMP * 탭을 선택합니다.
+
현재 정의된 트랩 대상이 테이블에 나타납니다.

. Add Trap Desations * 를 선택합니다.
+
트랩 대상 추가 대화 상자가 열립니다.

. 하나 이상의 트랩 대상을 입력하고 관련 커뮤니티 이름 또는 사용자 이름을 선택한 다음 * 추가 * 를 클릭합니다.
+
** * 트랩 대상 * -- SNMP 서비스를 실행하는 서버의 IPv4 또는 IPv6 주소를 입력합니다.
** * 커뮤니티 이름 또는 사용자 이름 * -- 드롭다운에서 이 트랩 대상에 대한 커뮤니티 이름(SNMPv2c) 또는 사용자 이름(SNMPv3)을 선택합니다. (하나만 정의한 경우 이 필드에 이름이 이미 나타납니다.)
** * 인증 실패 트랩 전송 * -- 인식되지 않는 커뮤니티 이름 또는 사용자 이름으로 인해 SNMP 요청이 거부될 때마다 트랩 대상에 알리려면 이 옵션(확인란)을 선택합니다. 추가 * 를 클릭하면 트랩 대상 및 관련 커뮤니티 이름 또는 사용자 이름이 테이블에 나타납니다.


. 트랩이 유효한지 확인하려면 표에서 트랩 대상을 선택한 다음 * Test Trap Destination * 을 클릭하여 구성된 주소로 테스트 트랩을 보냅니다.


이벤트 모니터는 alertable 이벤트가 발생할 때마다 SNMP 트랩을 서버로 전송합니다.
