---
permalink: sm-settings/alerts-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, alerts, terms, 
summary: 알림 조건이 스토리지 어레이에 적용되는 방식에 대해 알아보십시오. 
---
= 경고 용어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
알림 조건이 스토리지 어레이에 적용되는 방식에 대해 알아보십시오.

[cols="25h,~"]
|===
| 구성 요소 | 설명 


 a| 
이벤트 모니터
 a| 
이벤트 모니터는 스토리지 시스템에 상주하며 백그라운드 작업으로 실행됩니다. 이벤트 모니터에서 스토리지 배열의 이상 징후를 감지하면 해당 문제에 대한 정보를 이벤트 로그에 기록합니다. 배터리 오류, 최적화에서 오프라인으로 이동하는 구성 요소 또는 컨트롤러의 중복 오류와 같은 문제가 포함될 수 있습니다. 이벤트 모니터에서 이벤트가 "alertable"이라고 판단하면 구성된 경고 방법(e-메일, SNMP 및/또는 syslog)을 사용하여 알림을 보냅니다. 모든 중요 이벤트는 일부 경고 및 정보 이벤트와 함께 "alertable"으로 간주됩니다.



 a| 
메일 서버
 a| 
메일 서버는 이메일 경고를 보내고 받는 데 사용됩니다. 서버는 SMTP(Simple Mail Transfer Protocol)를 사용합니다.



 a| 
SNMP를 선택합니다
 a| 
SNMP(Simple Network Management Protocol)는 IP 네트워크의 장치 간에 정보를 관리 및 공유하는 데 사용되는 인터넷 표준 프로토콜입니다.



 a| 
SNMP 트랩
 a| 
SNMP 트랩은 SNMP 서버로 전송되는 알림입니다. 트랩에는 스토리지 배열 관련 주요 문제에 대한 정보가 포함되어 있습니다.



 a| 
SNMP 트랩 대상입니다
 a| 
SNMP 트랩 대상은 SNMP 서비스를 실행하는 서버의 IPv4 또는 IPv6 주소입니다.



 a| 
커뮤니티 이름입니다
 a| 
커뮤니티 이름은 SNMP 환경에서 네트워크 서버의 암호 역할을 하는 문자열입니다.



 a| 
MIB 파일
 a| 
MIB(Management Information Base) 파일은 스토리지 어레이에서 모니터링 및 관리되는 데이터를 정의합니다. SNMP 서비스 응용 프로그램을 사용하여 서버에서 복사 및 컴파일해야 합니다. 이 MIB 파일은 지원 사이트의 System Manager 소프트웨어와 함께 사용할 수 있습니다.



 a| 
MIB 변수
 a| 
MIB(Management Information Base) 변수는 스토리지 배열 이름, 배열 위치 및 SNMP GetRequests에 대한 응답으로 연락 담당자 등의 값을 반환할 수 있습니다.



 a| 
Syslog를 클릭합니다
 a| 
Syslog는 네트워크 장치가 로깅 서버에 이벤트 메시지를 보내는 데 사용하는 프로토콜입니다.



 a| 
UDP입니다
 a| 
UDP(User Datagram Protocol)는 패킷 헤더에서 소스 및 대상 포트 번호를 지정하는 전송 계층 프로토콜입니다.

|===