---
permalink: sm-settings/automatic-load-balancing-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, load, balancing, 
summary: 자동 로드 밸런싱은 시간이 지남에 따라 로드 변화에 동적으로 대응하고 볼륨 컨트롤러 소유권을 자동으로 조정하여 워크로드가 컨트롤러 간에 이동할 때 로드 불균형 문제를 해결함으로써 I/O 리소스 관리를 개선합니다. 
---
= 자동 로드 밸런싱 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
자동 로드 밸런싱은 시간이 지남에 따라 로드 변화에 동적으로 대응하고 볼륨 컨트롤러 소유권을 자동으로 조정하여 워크로드가 컨트롤러 간에 이동할 때 로드 불균형 문제를 해결함으로써 I/O 리소스 관리를 개선합니다.

각 컨트롤러의 워크로드는 지속적으로 모니터링되며 호스트에 설치된 다중 경로 드라이버의 협력을 통해 필요할 때마다 자동으로 균형을 맞출 수 있습니다. 컨트롤러 간에 워크로드가 자동으로 재조정되면 스토리지 관리자는 스토리지 어레이의 로드 변경을 수용하기 위해 볼륨 컨트롤러 소유권을 수동으로 조정해야 하는 부담을 덜 수 있습니다.

자동 로드 밸런싱이 활성화되면 다음 기능을 수행합니다.

* 컨트롤러 리소스 활용률을 자동으로 모니터링 및 균형 조정
* 필요한 경우 볼륨 컨트롤러 소유권을 자동으로 조정하여 호스트와 스토리지 어레이 간의 I/O 대역폭을 최적화합니다.




== 자동 로드 밸런싱 활성화 및 비활성화

자동 로드 밸런싱은 모든 스토리지 어레이에서 기본적으로 활성화됩니다.

다음과 같은 이유로 스토리지 어레이에서 자동 로드 밸런싱을 사용하지 않도록 설정할 수 있습니다.

* 워크로드의 균형을 맞추기 위해 특정 볼륨의 컨트롤러 소유권을 자동으로 변경하지 않으려는 경우
* 부하 분산이 의도적으로 설정된 고도로 조정된 환경에서 컨트롤러 간에 특정 분포를 이룰 수 있습니다.




== 자동 로드 밸런싱 기능을 지원하는 호스트 유형입니다

스토리지 어레이 레벨에서 자동 로드 밸런싱이 활성화되어 있더라도 호스트 또는 호스트 클러스터에 대해 선택하는 호스트 유형은 이 기능의 작동 방식에 직접적인 영향을 미칩니다.

여러 컨트롤러에 걸쳐 스토리지 어레이의 워크로드를 밸런싱할 때 자동 로드 밸런싱 기능은 두 컨트롤러가 액세스할 수 있고 자동 로드 밸런싱 기능을 지원할 수 있는 호스트 또는 호스트 클러스터에만 매핑된 볼륨을 이동하려고 시도합니다.

이렇게 하면 로드 밸런싱 프로세스로 인해 호스트가 볼륨에 액세스하지 못하게 됩니다. 하지만 자동 로드 밸런싱을 지원하지 않는 호스트에 매핑된 볼륨이 있으면 스토리지 시스템의 워크로드 균형 조정 기능에 영향을 줍니다. 자동 로드 균형 조정을 위해 다중 경로 드라이버는 TPGS를 지원해야 하며 호스트 유형은 다음 표에 포함되어야 합니다.

[NOTE]
====
호스트 클러스터에서 자동 로드 밸런싱을 사용하려면 해당 그룹의 모든 호스트가 자동 로드 밸런싱을 지원할 수 있어야 합니다.

====
[cols="1a,1a"]
|===
| 자동 로드 밸런싱을 지원하는 호스트 유형입니다 | 이 다중 경로 드라이버를 사용합니다 


 a| 
Windows 또는 Windows 클러스터형
 a| 
NetApp E-Series DSM을 사용한 MPIO



 a| 
Linux DM-MP(커널 3.10 이상)
 a| 
'scsi_dh_ALUA' 디바이스 핸들러가 있는 DM-MP



 a| 
VMware
 a| 
VMW_SATP_ALUA 스토리지 어레이 유형 플러그인을 사용하는 NMP(Native Multipathing Plugin

|===
[NOTE]
====
사소한 예외를 제외하고 자동 로드 밸런싱을 지원하지 않는 호스트 유형은 이 기능이 활성화되어 있는지 여부에 관계없이 계속 정상적으로 작동합니다. 한 가지 예외는 시스템에 페일오버가 있는 경우 데이터 경로가 반환될 때 스토리지 어레이가 매핑되지 않았거나 할당되지 않은 볼륨을 소유 컨트롤러로 다시 이동하는 것입니다. 비 자동 로드 밸런싱 호스트에 매핑되거나 할당된 볼륨은 이동되지 않습니다.

====
를 참조하십시오 https://mysupport.netapp.com/matrix["상호 운용성 매트릭스 툴"^] 특정 다중 경로 드라이버, OS 레벨 및 컨트롤러 드라이브 트레이 지원에 대한 호환성 정보



== 자동 로드 밸런싱 기능과 OS 호환성을 확인합니다

새(또는 기존) 시스템을 설정하기 전에 자동 로드 밸런싱 기능과 OS 호환성을 확인하십시오.

. 로 이동합니다 https://mysupport.netapp.com/matrix["상호 운용성 매트릭스 툴"^] 솔루션을 찾고 지원을 확인합니다.
+
시스템에서 Red Hat Enterprise Linux 6 또는 SUSE Linux Enterprise Server 11을 실행하는 경우 기술 지원 부서에 문의하십시오.

. '/etc/multipath.conf 파일'을 업데이트하고 구성합니다.
. 해당 벤더 및 제품에 대해 "Stain_Attached_device_handler"와 "Detect_prio"가 모두 "yes"로 설정되어 있는지 확인하거나 기본 설정을 사용하십시오.

