---
permalink: sm-settings/cache-settings-and-performance.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cache, settings, performance, 
summary: 캐시 메모리는 드라이브 미디어보다 액세스 시간이 빠른 컨트롤러의 임시 휘발성 저장 영역입니다. 
---
= 캐시 설정 및 성능
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
캐시 메모리는 드라이브 미디어보다 액세스 시간이 빠른 컨트롤러의 임시 휘발성 저장 영역입니다.

캐싱을 사용하면 전반적인 I/O 성능을 다음과 같이 향상시킬 수 있습니다.

* 읽기를 위해 호스트에서 요청된 데이터가 이전 작업의 캐시에 이미 있을 수 있으므로 드라이브 액세스가 필요하지 않습니다.
* 쓰기 데이터는 처음에는 캐시에 기록되기 때문에 데이터가 드라이브에 기록될 때까지 기다리지 않고 애플리케이션을 계속 사용할 수 있습니다.


기본 캐시 설정은 대부분의 환경에 대한 요구 사항을 충족하지만 원하는 경우 변경할 수 있습니다.



== 스토리지 캐시 설정입니다

스토리지 배열의 모든 볼륨에 대해 시스템 페이지에서 다음 값을 지정할 수 있습니다.

* * 플러싱에 대한 시작 값 * -- 캐시 플러시를 트리거하는 캐시에 기록되지 않은 데이터의 비율입니다(디스크에 쓰기). 캐시에 기록되지 않은 데이터의 지정된 시작 백분율이 있으면 플러시가 트리거됩니다. 기본적으로 컨트롤러는 캐시가 80% 찰 때 캐시를 플러시합니다.
* * 캐시 블록 크기 * -- 캐시 관리를 위한 조직 단위인 각 캐시 블록의 최대 크기입니다. 캐시 블록 크기는 기본적으로 8KiB이지만 4, 8, 16 또는 32KiB로 설정할 수 있습니다. 가장 많이 사용되는 애플리케이션의 입출력 크기로 캐시 블록 크기를 설정하는 것이 좋습니다. 파일 시스템 또는 데이터베이스 애플리케이션은 일반적으로 더 작은 크기를 사용하며, 더 큰 크기는 대용량 데이터 전송이나 순차적 I/O가 필요한 애플리케이션에 적합합니다




== 볼륨 캐시 설정입니다

스토리지 배열의 개별 볼륨의 경우 Volumes(볼륨) 페이지(메뉴: Storage(저장소) [Volumes](볼륨))에서 다음 값을 지정할 수 있습니다.

* * 읽기 캐싱 * -- 읽기 캐시는 드라이브에서 읽은 데이터를 저장하는 버퍼입니다. 읽기 작업의 데이터가 이전 작업의 캐시에 이미 있을 수 있으므로 드라이브에 액세스할 필요가 없습니다. 데이터가 플러시될 때까지 읽기 캐시에 남아 있습니다.
+
** * 동적 읽기 캐시 프리페치 * -- 동적 캐시 읽기 프리페치를 사용하면 컨트롤러에서 드라이브에서 캐시로 데이터 블록을 읽는 동안 순차적 데이터 블록을 추가로 캐시에 복사할 수 있습니다. 이 캐싱은 향후 캐시에서 데이터 요청을 채울 수 있는 기회를 높여줍니다. 동적 캐시 읽기 프리페치는 순차적 I/O를 사용하는 멀티미디어 애플리케이션에 중요합니다 캐시로 프리페치되는 데이터의 속도와 양은 호스트 읽기의 속도 및 요청 크기에 따라 자동으로 조정됩니다. 랜덤 액세스로 인해 데이터를 캐시로 프리페치하지 않습니다. 이 기능은 읽기 캐시를 사용하지 않는 경우 적용되지 않습니다.


* * 쓰기 캐시 * -- 쓰기 캐시는 아직 드라이브에 기록되지 않은 호스트의 데이터를 저장하는 버퍼입니다. 데이터는 드라이브에 기록될 때까지 쓰기 캐시에 유지됩니다. 쓰기 캐싱은 I/O 성능을 높일 수 있습니다.
+
[CAUTION]
====
* 데이터 손실 가능성 * -- 배터리 없이 * 쓰기 캐싱 * 옵션을 활성화하고 보호를 위한 범용 전원 공급 장치가 없는 경우 데이터가 손실될 수 있습니다. 또한 컨트롤러 배터리가 없고 * 배터리 없이 쓰기 캐싱 * 옵션을 활성화하면 데이터가 손실될 수 있습니다.

====
+
** * 배터리 없는 쓰기 캐싱 * -- 배터리 없는 쓰기 캐싱 설정을 사용하면 배터리가 없거나, 고장, 방전되거나, 완전히 충전되지 않았더라도 쓰기 캐싱을 계속할 수 있습니다. 일반적으로 배터리 없이 쓰기 캐시를 선택하는 것은 권장되지 않습니다. 전원이 끊길 경우 데이터가 손실될 수 있기 때문입니다. 일반적으로 쓰기 캐시는 배터리가 충전되거나 장애가 발생한 배터리를 교체할 때까지 컨트롤러에 의해 일시적으로 꺼집니다.
** * 미러링으로 쓰기 캐싱 * -- 한 컨트롤러의 캐시 메모리에 기록된 데이터가 다른 컨트롤러의 캐시 메모리에도 쓰일 때 미러링을 사용하는 쓰기 캐시가 발생합니다. 따라서 한 컨트롤러에 장애가 발생하면 다른 컨트롤러가 처리되지 않은 모든 쓰기 작업을 완료할 수 있습니다. 쓰기 캐시 미러링은 쓰기 캐시가 설정되고 두 개의 컨트롤러가 있는 경우에만 사용할 수 있습니다. 볼륨 생성 시 기본 설정은 미러링을 사용한 쓰기 캐시입니다.



