---
permalink: sm-settings/change-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, security, key, 
summary: 언제든지 보안 키를 새 키로 바꿀 수 있습니다. 회사에서 보안 위반이 발생할 가능성이 있으며 권한이 없는 직원이 드라이브의 데이터에 액세스하지 못하도록 하려면 보안 키를 변경해야 할 수 있습니다. 
---
= SANtricity System Manager에서 보안 키 변경
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
언제든지 보안 키를 새 키로 바꿀 수 있습니다. 회사에서 보안 위반이 발생할 수 있으며 권한이 없는 직원이 드라이브 데이터에 액세스하지 못하도록 하려면 보안 키를 변경해야 할 수 있습니다.

.단계
. 설정 [시스템] 메뉴를 선택합니다.
. 보안 키 관리 * 에서 * 키 변경 * 을 선택합니다.
+
보안 키 변경 대화 상자가 열립니다.

. 다음 필드에 정보를 입력합니다.
+
** * 보안 키 식별자 정의 * --(내부 보안 키에만 해당) 기본값(컨트롤러 펌웨어에서 생성되는 스토리지 배열 이름 및 타임스탬프)을 그대로 사용하거나 값을 직접 입력합니다. 공백, 구두점 또는 기호 없이 최대 189자의 영숫자 문자를 입력할 수 있습니다.
+
[NOTE]
====
추가 문자는 자동으로 생성되며 입력하는 문자열의 양쪽 끝에 추가됩니다. 생성된 문자는 식별자가 고유한지 확인하는 데 도움이 됩니다.

====
** * 암호문 정의/암호문 다시 입력 * -- 이러한 각 필드에 암호문을 입력합니다. 값은 8자에서 32자 사이여야 하며 다음 각 문자를 포함해야 합니다.
+
*** 대문자(하나 이상) 암호는 대/소문자를 구분합니다.
*** 숫자(하나 이상)
*** !, *, @(하나 이상)와 같은 영숫자 이외의 문자입니다.




. 외부 보안 키의 경우 새 보안 키를 만들 때 이전 보안 키를 삭제하려면 대화 상자 아래쪽에 있는 "현재 보안 키 삭제..." 확인란을 선택합니다.
+
[CAUTION]
====
* 나중에 사용할 수 있도록 항목을 기록해 두십시오. * -- 보안 지원 드라이브를 스토리지 배열에서 이동해야 하는 경우, 드라이브 데이터를 잠금 해제하려면 식별자와 암호를 알아야 합니다.

====
. 변경 * 을 클릭합니다.
+
새 보안 키는 더 이상 유효하지 않은 이전 키를 덮어씁니다.

+
[NOTE]
====
다운로드한 파일의 경로는 브라우저의 기본 다운로드 위치에 따라 다를 수 있습니다.

====
. 키 식별자, 암호 및 다운로드한 키 파일의 위치를 기록한 다음 * 닫기 * 를 클릭합니다.


.작업을 마친 후
키 파일이 손상되지 않도록 보안 키의 유효성을 검사해야 합니다.
