---
permalink: sm-settings/change-cache-settings-for-storage-array.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, cache, settings, 
summary: 스토리지 배열의 모든 볼륨에 대해 캐시 메모리 설정을 조정하여 플러싱과 블록 크기를 조정할 수 있습니다. 
---
= 스토리지 배열에 대한 캐시 설정을 변경합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 배열의 모든 볼륨에 대해 캐시 메모리 설정을 조정하여 플러싱과 블록 크기를 조정할 수 있습니다.

.이 작업에 대해
캐시 메모리는 컨트롤러의 임시 휘발성 저장 공간으로, 드라이브 미디어보다 액세스 시간이 더 빠릅니다. 캐시 성능을 조정하려면 다음 설정을 조정할 수 있습니다.

[cols="25h,~"]
|===
| 캐시 설정 | 설명 


 a| 
요청 캐시 플러싱을 시작합니다
 a| 
Start demand cache flashing은 캐시 플러시(디스크에 쓰기)를 트리거하는 캐시에 기록되지 않은 데이터의 비율을 지정합니다. 기본적으로 캐시 플러싱은 기록되지 않은 데이터가 80% 용량에 도달하면 시작됩니다. 쓰기 작업이 주로 수행되는 환경에서는 더 높은 비율이 적합하므로 새 쓰기 요청은 디스크로 이동할 필요 없이 캐시로 처리될 수 있습니다. 입출력 오류가 발생하는 환경(데이터 버스트 사용)에서 낮은 설정은 더 낫기 때문에 시스템이 데이터 버스트 사이에 캐시를 자주 플러시합니다. 그러나 시작 비율이 80%보다 낮으면 성능이 저하될 수 있습니다.



 a| 
캐시 블록 크기
 a| 
캐시 블록 크기는 각 캐시 블록의 최대 크기를 결정합니다. 이 크기는 캐시 관리를 위한 조직 단위입니다. 기본적으로 블록 크기는 32KiB입니다. 시스템은 캐시 블록 크기를 4, 8, 16 또는 32KiB로 설정할 수 있습니다. 애플리케이션은 스토리지 성능에 영향을 미치는 다양한 블록 크기를 사용합니다. 파일 시스템 또는 데이터베이스 애플리케이션에 적합한 크기는 더 작습니다. 더 큰 크기는 멀티미디어와 같이 순차적 I/O를 생성하는 응용 프로그램에 이상적입니다.

|===
.단계
. 설정 [시스템] 메뉴를 선택합니다.
. 아래로 스크롤하여 * 추가 설정 * 을 찾은 다음 * 캐시 설정 변경 * 을 클릭합니다.
+
캐시 설정 변경 대화 상자가 열립니다.

. 다음 값을 조정합니다.
+
** * 요청 캐시 플러싱 시작 * -- 사용자 환경에서 사용되는 I/O에 적합한 비율을 선택합니다. 80% 미만의 값을 선택하면 성능이 저하될 수 있습니다.
** ** 캐시 블록 크기 --** 응용 프로그램에 적합한 크기를 선택합니다.


. 저장 * 을 클릭합니다.

