---
permalink: sm-settings/clear-storage-array-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, clear, storage, array, configuration, 
summary: 스토리지 배열에서 모든 풀, 볼륨 그룹, 볼륨, 호스트 정의 및 호스트 할당을 삭제하려면 구성 지우기 작업을 사용합니다. 
---
= 스토리지 배열 구성을 지웁니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 배열에서 모든 풀, 볼륨 그룹, 볼륨, 호스트 정의 및 호스트 할당을 삭제하려면 구성 지우기 작업을 사용합니다.

.시작하기 전에
스토리지 배열 구성을 지우기 전에 데이터를 백업합니다.

.이 작업에 대해
스토리지 배열 구성 지우기 옵션에는 두 가지가 있습니다.

* * 볼륨 * -- 일반적으로 볼륨 옵션을 사용하여 테스트 스토리지 어레이를 프로덕션 스토리지 어레이로 재구성할 수 있습니다. 예를 들어, 테스트용으로 스토리지 어레이를 구성한 다음 테스트를 마치면 테스트 구성을 제거하고 운영 환경에 맞게 스토리지 어레이를 설정할 수 있습니다.
* * 스토리지 배열 * -- 일반적으로 스토리지 배열 옵션을 사용하여 스토리지 배열을 다른 부서 또는 그룹으로 이동할 수 있습니다. 예를 들어, 엔지니어링 팀에서 스토리지 어레이를 사용하고 있고 이제 엔지니어링 팀에서 새 스토리지 어레이를 가져오므로 현재 스토리지 어레이를 재구성할 관리 위치로 이동할 수 있습니다.
+
스토리지 배열 옵션은 일부 추가 설정을 삭제합니다.



[cols="1a,1a,1a"]
|===
|  | 볼륨 | 스토리지 


 a| 
풀 및 볼륨 그룹을 삭제합니다
 a| 
X
 a| 
X



 a| 
볼륨을 삭제합니다
 a| 
X
 a| 
X



 a| 
호스트 및 호스트 클러스터를 삭제합니다
 a| 
X
 a| 
X



 a| 
호스트 할당을 삭제합니다
 a| 
X
 a| 
X



 a| 
스토리지 배열 이름을 삭제합니다
 a| 
 a| 
X



 a| 
스토리지 캐시 설정을 기본값으로 재설정합니다
 a| 
 a| 
X

|===
[CAUTION]
====
* 데이터 손실 위험 * -- 이 작업은 스토리지 배열의 모든 데이터를 삭제합니다. (보안 지우지는 않습니다.) 이 작업을 시작한 후에는 취소할 수 없습니다. 기술 지원 부서에서 지시한 경우에만 이 작업을 수행하십시오.

====
.단계
. 설정 [시스템] 메뉴를 선택합니다.
. 스토리지 배열 구성 지우기 * 를 선택합니다.
. 드롭다운 목록에서 * Volume * 또는 * Storage Array * 를 선택합니다.
. * 선택 사항: * 데이터가 아닌 구성을 저장하려면 대화 상자의 링크를 사용합니다.
. 작업을 수행할지 확인합니다.


.결과
* 현재 구성이 삭제되어 스토리지 어레이의 기존 데이터가 모두 제거됩니다.
* 모든 드라이브가 할당되지 않았습니다.

