---
permalink: sm-settings/configure-mail-server-and-recipients-for-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, mail, server, recipients, alerts, 
summary: 전자 메일 알림을 구성하려면 메일 서버 주소와 경고 받는 사람의 전자 메일 주소를 지정해야 합니다. 최대 20개의 이메일 주소가 허용됩니다. 
---
= 메일 서버 및 받는 사람이 알림을 받도록 구성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전자 메일 알림을 구성하려면 메일 서버 주소와 경고 받는 사람의 전자 메일 주소를 지정해야 합니다. 최대 20개의 이메일 주소가 허용됩니다.

.시작하기 전에
* 메일 서버의 주소를 사용할 수 있어야 합니다. 주소는 IPv4 또는 IPv6 주소이거나 정규화된 도메인 이름일 수 있습니다.
+
[NOTE]
====
정규화된 도메인 이름을 사용하려면 두 컨트롤러 모두에서 DNS 서버를 구성해야 합니다. 하드웨어 페이지에서 DNS 서버를 구성할 수 있습니다.

====
* 알림 발송자로 사용할 이메일 주소를 사용할 수 있어야 합니다. 경고 메시지의 "보낸 사람" 필드에 나타나는 주소입니다. SMTP 프로토콜에 보낸 사람 주소가 필요합니다. 이 주소가 없으면 오류 결과가 발생합니다.
* 알림 수신자의 이메일 주소를 사용할 수 있어야 합니다. 받는 사람은 일반적으로 네트워크 관리자 또는 스토리지 관리자의 주소입니다. 최대 20개의 이메일 주소를 입력할 수 있습니다.


.이 작업에 대해
이 작업은 메일 서버를 구성하고, 보낸 사람과 받는 사람의 전자 메일 주소를 입력하고, 경고 페이지에서 입력한 모든 전자 메일 주소를 테스트하는 방법을 설명합니다.

[NOTE]
====
초기 설정 마법사에서 이메일 알림을 구성할 수도 있습니다.

====
.단계
. 설정 [알림] 메뉴를 선택합니다.
. 이메일 * 탭을 선택합니다.
+
이메일 서버가 아직 구성되지 않은 경우 이메일 탭에 "메일 서버 구성"이 표시됩니다.

. 메일 서버 구성 * 을 선택합니다.
+
메일 서버 구성 대화 상자가 열립니다.

. 메일 서버 정보를 입력한 다음 * 저장 * 을 클릭합니다.
+
** * 메일 서버 주소 * -- 메일 서버의 정규화된 도메인 이름, IPv4 주소 또는 IPv6 주소를 입력합니다.
+
[NOTE]
====
정규화된 도메인 이름을 사용하려면 두 컨트롤러 모두에서 DNS 서버를 구성해야 합니다. 하드웨어 페이지에서 DNS 서버를 구성할 수 있습니다.

====
** * 이메일 발신자 주소 * -- 이메일 발신자로 사용할 유효한 이메일 주소를 입력합니다. 이 주소는 전자 메일 메시지의 "보낸 사람" 필드에 나타납니다.
** * 암호화 * -- 메시지를 암호화하려면 암호화 유형으로 * SMTPS * 또는 * STARTTLS * 를 선택한 다음 암호화된 메시지의 포트 번호를 선택합니다. 그렇지 않으면 * 없음 * 을 선택합니다.
** * 사용자 이름 및 암호 * -- 필요한 경우 보내는 보낸 사람 및 메일 서버와 함께 인증을 위한 사용자 이름과 암호를 입력합니다.
** * 전자 메일에 연락처 정보 포함 * -- 경고 메시지에 보낸 사람의 연락처 정보를 포함하려면 이 옵션을 선택한 다음 이름과 전화 번호를 입력합니다.
+
저장 * 을 클릭하면 이메일 주소가 경고 페이지의 이메일 탭에 나타납니다.



. 이메일 추가 * 를 선택합니다.
+
이메일 추가 대화 상자가 열립니다.

. 경고 수신자에 대한 이메일 주소를 하나 이상 입력한 다음 * 추가 * 를 클릭합니다.
+
이메일 주소는 경고 페이지에 나타납니다.

. 이메일 주소가 유효한지 확인하려면 * Test all email * 을 클릭하여 수신자에게 테스트 메시지를 보냅니다.


.결과
e-메일 알림을 구성한 후 이벤트 모니터는 alertable 이벤트가 발생할 때마다 지정된 수신자에게 e-메일 메시지를 보냅니다.
