---
permalink: sm-settings/configure-iscsi-authentication.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iscsi, authentication, 
summary: 'iSCSI 네트워크의 보안을 강화하기 위해 컨트롤러(타겟)와 호스트(이니시에이터) 간에 인증을 설정할 수 있습니다.' 
---
= SANtricity System Manager에서 iSCSI 인증 구성
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI 네트워크의 보안을 강화하기 위해 컨트롤러(타겟)와 호스트(이니시에이터) 간에 인증을 설정할 수 있습니다.

System Manager에서는 CHAP(Challenge Handshake Authentication Protocol) 방법을 사용하여 초기 링크 중에 대상 및 초기자의 ID를 확인합니다. 인증은 _CHAP secret_이라는 공유 보안 키를 기반으로 합니다.

.시작하기 전에
타겟(컨트롤러)에 대한 CHAP 암호를 설정하기 전이나 후에 이니시에이터(iSCSI 호스트)에 대한 CHAP 암호를 설정할 수 있습니다. 이 작업의 지침을 따르기 전에 호스트가 iSCSI 연결을 먼저 수행할 때까지 기다린 다음 개별 호스트에 CHAP 암호를 설정해야 합니다. 연결이 완료되면 호스트의 IQN 이름과 해당 CHAP 암호가 iSCSI 인증 대화 상자(이 작업에 설명되어 있음)에 나열되며, 수동으로 입력할 필요가 없습니다.

.이 작업에 대해
CHAP 인증을 활성화한 다음 단방향 인증을 위해 대상 CHAP 암호를 지정하거나, 컨트롤러와 iSCSI 호스트 간의 양방향 인증을 위해 이니시에이터 CHAP 암호를 모두 지정할 수 있습니다.

단방향 인증은 컨트롤러가 iSCSI 호스트의 신원을 인증할 수 있도록 합니다(단방향 인증).

양방향 인증을 사용하면 컨트롤러와 iSCSI 호스트 모두 인증을 수행할 수 있습니다(양방향 인증). 이 옵션은 컨트롤러가 iSCSI 호스트의 신원을 인증하고, iSCSI 호스트도 컨트롤러의 신원을 인증할 수 있도록 하여 보안 수준을 한 단계 높여줍니다.

.단계
. 왼쪽 패널에서 *System*을 선택합니다.
. *iSCSI 설정*에서 *iSCSI 인증 구성*을 클릭합니다.
+
인증 구성 창이 나타납니다.

. CHAP 인증을 활성화하려면 *CHAP 인증 활성화* 확인란을 선택하십시오.
+
CHAP 인증을 사용하지 않으려면 해당 확인란을 선택하지 않은 상태로 두십시오.

. 단방향 인증을 활성화한 경우, 타겟에 연결하는 이니시에이터를 인증하기 위해 *Target CHAP secret*을 입력하십시오. CHAP 비밀은 12~57자의 출력 가능한 ASCII 문자여야 합니다.
+
대상 CHAP 비밀 확인 필드에 동일한 CHAP 비밀을 다시 입력하여 확인합니다.

. 컨트롤러와 iSCSI 호스트 간의 양방향 인증을 활성화하려면 이니시에이터가 컨트롤러를 인증하는 데 사용할 *이니시에이터 CHAP 비밀*을 입력하십시오. CHAP 비밀은 12~57자의 출력 가능한 ASCII 문자여야 합니다.
. 저장 * 을 클릭합니다.


.결과
인증을 지정하지 않은 경우, 컨트롤러와 iSCSI 호스트 간의 iSCSI 로그인 시퀀스 중에 인증이 발생합니다.
