---
permalink: sm-settings/configure-snmp-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, snmp, alerts, 
summary: 'SNMP(Simple Network Management Protocol) 경고를 구성하려면 스토리지 배열의 이벤트 모니터에서 SNMP 트랩을 보낼 수 있는 서버를 하나 이상 식별해야 합니다. 이 구성에는 커뮤니티 이름 또는 사용자 이름과 서버의 IP 주소가 필요합니다.' 
---
= SNMP 경고를 구성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMP(Simple Network Management Protocol) 경고를 구성하려면 스토리지 배열의 이벤트 모니터에서 SNMP 트랩을 보낼 수 있는 서버를 하나 이상 식별해야 합니다. 이 구성에는 커뮤니티 이름 또는 사용자 이름과 서버의 IP 주소가 필요합니다.

.시작하기 전에
* 네트워크 서버는 SNMP 서비스 애플리케이션으로 구성되어야 합니다. 이벤트 모니터가 해당 주소로 트랩 메시지를 보낼 수 있도록 이 서버의 네트워크 주소(IPv4 또는 IPv6 주소)가 필요합니다. 둘 이상의 서버를 사용할 수 있습니다(최대 10대의 서버가 허용됨).
* MIB(Management Information Base) 파일이 SNMP 서비스 응용 프로그램을 사용하여 서버에서 복사 및 컴파일되었습니다. 이 MIB 파일은 모니터링 및 관리되는 데이터를 정의합니다.
+
MIB 파일이 없는 경우 NetApp Support 사이트에서 얻을 수 있습니다.

+
** 로 이동합니다 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"^].
** Downloads * 탭을 클릭한 다음 * Downloads * 를 선택합니다.
** E-Series SANtricity OS 컨트롤러 소프트웨어 * 를 클릭합니다.
** 최신 릴리스 다운로드 * 를 선택합니다.
** 로그인합니다.
** 주의 사항 및 라이센스 계약에 동의합니다.
** 컨트롤러 유형에 대한 MIB 파일이 표시될 때까지 아래로 스크롤한 다음 링크를 클릭하여 파일을 다운로드합니다.




이 작업에서는 트랩 대상에 대한 SNMP 서버를 식별하고 구성을 테스트하는 방법을 설명합니다.

.단계
. 설정 [알림] 메뉴를 선택합니다.
. SNMP * 탭을 선택합니다.
+
처음 설정할 때 SNMP 탭에 "커뮤니티/사용자 구성"이 표시됩니다.

. 커뮤니티/사용자 구성 * 을 선택합니다.
+
SNMP 버전 선택 대화 상자가 열립니다.

. 경고에 대한 SNMP 버전을 선택합니다. * SNMPv2c * 또는 * SNMPv3 *.
+
선택한 항목에 따라 커뮤니티 구성 대화 상자 또는 SNMPv3 사용자 구성 대화 상자가 열립니다.

. SNMPv2c(커뮤니티) 또는 SNMPv3(사용자)에 대한 적절한 지침을 따릅니다.
+
** * SNMPv2c(커뮤니티) * -- 커뮤니티 구성 대화 상자에서 네트워크 서버에 대한 커뮤니티 문자열을 하나 이상 입력합니다. 커뮤니티 이름은 알려진 관리 스테이션 집합을 식별하는 문자열이며 일반적으로 네트워크 관리자가 만듭니다. 인쇄 가능한 ASCII 문자만 포함됩니다. 최대 256개의 커뮤니티를 추가할 수 있습니다. 완료되면 * Save * 를 클릭합니다.
** * SNMPv3(사용자) * -- SNMPv3 사용자 구성 대화 상자에서 * 추가 * 를 클릭한 후 다음 정보를 입력합니다.
+
*** * 사용자 이름 * -- 사용자를 식별할 이름을 입력합니다. 최대 31자까지 입력할 수 있습니다.
*** * 엔진 ID * -- 메시지에 대한 인증 및 암호화 키를 생성하는 데 사용되는 엔진 ID를 선택합니다. 이 ID는 관리 도메인에서 고유해야 합니다. 대부분의 경우 * Local * 을 선택해야 합니다. 비표준 구성이 있는 경우 * 사용자 정의 * 를 선택합니다. 다른 필드는 신뢰할 수 있는 엔진 ID를 10자에서 32자 사이의 짝수 문자로 16진수 문자열로 입력해야 하는 위치에 나타납니다.
*** * 인증 자격 증명 * -- 사용자 ID를 보장하는 인증 프로토콜을 선택합니다. 그런 다음 인증 프로토콜을 설정하거나 변경할 때 필요한 인증 암호를 입력합니다. 암호는 8자에서 128자 사이여야 합니다.
*** * 개인 정보 보호 자격 증명 * -- 메시지의 내용을 암호화하는 데 사용되는 개인 정보 보호 프로토콜을 선택합니다. 그런 다음 개인 정보 보호 프로토콜을 설정하거나 변경할 때 필요한 개인 정보 보호 암호를 입력합니다. 암호는 8자에서 128자 사이여야 합니다. 완료되면 * 추가 * 를 클릭한 다음 * 닫기 * 를 클릭합니다.




. SNMP 탭이 선택된 경고 페이지에서 * 트랩 대상 추가 * 를 클릭합니다.
+
트랩 대상 추가 대화 상자가 열립니다.

. 하나 이상의 트랩 대상을 입력하고 관련 커뮤니티 이름 또는 사용자 이름을 선택한 다음 * 추가 * 를 클릭합니다.
+
** * 트랩 대상 * -- SNMP 서비스를 실행하는 서버의 IPv4 또는 IPv6 주소를 입력합니다.
** * 커뮤니티 이름 또는 사용자 이름 * -- 드롭다운에서 이 트랩 대상에 대한 커뮤니티 이름(SNMPv2c) 또는 사용자 이름(SNMPv3)을 선택합니다. (하나만 정의한 경우 이 필드에 이름이 이미 나타납니다.)
** * 인증 실패 트랩 전송 * -- 인식되지 않는 커뮤니티 이름 또는 사용자 이름으로 인해 SNMP 요청이 거부될 때마다 트랩 대상에 알리려면 이 옵션(확인란)을 선택합니다. 추가 * 를 클릭하면 * 알림 * 페이지의 * SNMP * 탭에 트랩 대상 및 관련 이름이 나타납니다.


. 트랩이 유효한지 확인하려면 표에서 트랩 대상을 선택한 다음 * Test Trap Destination * 을 클릭하여 구성된 주소로 테스트 트랩을 보냅니다.


이벤트 모니터는 alertable 이벤트가 발생할 때마다 SNMP 트랩을 서버로 전송합니다.
