---
permalink: sm-settings/configure-nvme-over-roce-ports-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, nvme, roce, ports, 
summary: '컨트롤러에 NVMe over RoCE(RDMA over Converged Ethernet)에 대한 연결이 포함되어 있는 경우 시스템 페이지에서 NVMe 포트 설정을 구성할 수 있습니다.' 
---
= NVMe over RoCE 포트를 구성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러에 NVMe over RoCE(RDMA over Converged Ethernet)에 대한 연결이 포함되어 있는 경우 시스템 페이지에서 NVMe 포트 설정을 구성할 수 있습니다.

.시작하기 전에
* 컨트롤러에 NVMe over RoCE 호스트 포트가 포함되어야 합니다. 그렇지 않으면 System Manager에서 NVMe over RoCE 설정을 사용할 수 없습니다.
* 호스트 연결의 IP 주소를 알아야 합니다.


.단계
. 설정 [시스템] 메뉴를 선택합니다.
. NVMe over ROCE 설정 * 에서 * Configure NVMe over ROCE ports * 를 선택합니다.
. 구성할 NVMe over RoCE 포트가 있는 컨트롤러를 선택합니다. 다음 * 을 클릭합니다.
. 드롭다운 목록에서 구성할 HIC 포트를 선택합니다. 다음 * 을 클릭합니다.
. 포트 설정을 구성합니다.
+
모든 포트 설정을 보려면 대화 상자 오른쪽에 있는 * 추가 포트 설정 표시 * 링크를 클릭합니다.

+
.필드 세부 정보
[%collapsible]
====
[cols="1a,1a"]
|===
| 포트 설정 | 설명 


 a| 
이더넷 포트 속도를 구성했습니다
 a| 
포트에서 SFP의 속도 기능과 일치하는 속도를 선택합니다.



 a| 
IPv4 사용/IPv6 사용
 a| 
IPv4 및 IPv6 네트워크에 대한 지원을 활성화하려면 하나 또는 두 옵션을 모두 선택하십시오.


NOTE: 포트 액세스를 비활성화하려면 두 확인란을 모두 선택 취소합니다.



 a| 
MTU 크기(* 추가 포트 설정 표시 * 를 클릭하여 사용 가능)
 a| 
필요한 경우 MTU(Maximum Transmission Unit)에 대한 새 크기를 바이트 단위로 입력합니다.

기본 MTU(Maximum Transmission Unit) 크기는 프레임당 1,500바이트입니다. 1500에서 9000 사이의 값을 입력해야 합니다.

|===
====
+
IPv4 사용 * 을 선택한 경우 * 다음 * 을 클릭하면 IPv4 설정을 선택할 수 있는 대화 상자가 열립니다. IPv6 사용 * 을 선택한 경우 * 다음 * 을 클릭하면 IPv6 설정을 선택할 수 있는 대화 상자가 열립니다. 두 옵션을 모두 선택한 경우 IPv4 설정에 대한 대화 상자가 먼저 열리고 * 다음 * 을 클릭하면 IPv6 설정에 대한 대화 상자가 열립니다.

. IPv4 및/또는 IPv6 설정을 자동 또는 수동으로 구성합니다.
+
.필드 세부 정보
[%collapsible]
====
[cols="1a,1a"]
|===
| 포트 설정 | 설명 


 a| 
자동으로 구성을 가져옵니다
 a| 
구성을 자동으로 가져오려면 이 옵션을 선택합니다.



 a| 
수동으로 정적 설정을 지정합니다
 a| 
이 옵션을 선택한 다음 필드에 정적 주소를 입력합니다. (필요한 경우 주소를 잘라내어 필드에 붙여 넣을 수 있습니다.) IPv4의 경우 네트워크 서브넷 마스크 및 게이트웨이를 포함합니다. IPv6의 경우 라우팅 가능한 IP 주소와 라우터 IP 주소를 포함합니다. 200GB 사용 HIC를 포함하는 EF600 스토리지 어레이를 구성하는 경우 이 대화 상자에 네트워크 매개 변수에 대한 두 개의 필드 세트가 물리적 포트(외부)에 대해, 가상 포트(내부)에 대해 하나씩 표시됩니다. 두 포트에 대해 고유한 매개 변수를 할당해야 합니다. 이러한 설정을 통해 호스트는 각 포트 간에 경로를 설정하고 HIC는 최대 성능을 달성할 수 있습니다. IP 주소를 가상 포트에 할당하지 않으면 HIC는 약 절반 수준의 속도로 실행됩니다.

|===
====
. 마침 * 을 클릭합니다.

