---
permalink: sm-settings/configure-iscsi-authentication.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, iscsi, authentication, 
summary: 'iSCSI 네트워크의 보안을 강화하기 위해 컨트롤러(타겟)와 호스트(이니시에이터) 간에 인증을 설정할 수 있습니다.' 
---
= iSCSI 인증을 구성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI 네트워크의 보안을 강화하기 위해 컨트롤러(타겟)와 호스트(이니시에이터) 간에 인증을 설정할 수 있습니다.

System Manager에서는 CHAP(Challenge Handshake Authentication Protocol) 방법을 사용하여 초기 링크 중에 대상 및 초기자의 ID를 확인합니다. 인증은 _CHAP secret_이라는 공유 보안 키를 기반으로 합니다.

.시작하기 전에
타겟(컨트롤러)에 대한 CHAP 암호를 설정하기 전이나 후에 이니시에이터(iSCSI 호스트)에 대한 CHAP 암호를 설정할 수 있습니다. 이 작업의 지침을 따르기 전에 호스트가 iSCSI 연결을 먼저 수행할 때까지 기다린 다음 개별 호스트에 CHAP 암호를 설정해야 합니다. 연결이 완료되면 호스트의 IQN 이름과 해당 CHAP 암호가 iSCSI 인증 대화 상자(이 작업에 설명되어 있음)에 나열되며, 수동으로 입력할 필요가 없습니다.

.이 작업에 대해
다음 인증 방법 중 하나를 선택할 수 있습니다.

* * 단방향 인증 * -- 컨트롤러가 iSCSI 호스트의 ID를 인증할 수 있도록 하려면 이 설정을 사용합니다(단방향 인증).
* * 양방향 인증 * -- 컨트롤러와 iSCSI 호스트가 모두 인증(양방향 인증)을 수행할 수 있도록 하려면 이 설정을 사용합니다. 이 설정은 컨트롤러가 iSCSI 호스트의 ID를 인증할 수 있도록 하고, iSCSI 호스트가 컨트롤러의 ID를 인증할 수 있도록 하여 두 번째 수준의 보안을 제공합니다.


[NOTE]
====
iSCSI 설정 및 기능은 스토리지 배열이 iSCSI를 지원하는 경우에만 설정 페이지에 표시됩니다.

====
.단계
. 설정 [시스템] 메뉴를 선택합니다.
. iSCSI 설정에서 * 인증 구성 * 을 클릭합니다.
+
현재 설정된 방법을 보여 주는 Configure Authentication 대화 상자가 나타납니다. 또한 호스트에 CHAP 암호가 구성되어 있는지 여부도 표시됩니다.

. 다음 중 하나를 선택합니다.
+
** * 인증 없음 * -- 컨트롤러가 iSCSI 호스트의 ID를 인증하지 않도록 하려면 이 옵션을 선택하고 * 마침 * 을 클릭합니다. 대화 상자가 닫히고 구성이 완료됩니다.
** * 단방향 인증 * -- 컨트롤러가 iSCSI 호스트의 ID를 인증할 수 있도록 하려면 이 옵션을 선택하고 * 다음 * 을 클릭하여 대상 CHAP 구성 대화 상자를 표시합니다.
** * 양방향 인증 * -- 컨트롤러와 iSCSI 호스트가 인증을 수행하도록 허용하려면 이 옵션을 선택하고 * 다음 * 을 클릭하여 대상 CHAP 구성 대화 상자를 표시합니다.


. 단방향 또는 양방향 인증의 경우 컨트롤러의 CHAP 암호(타겟)를 입력하거나 확인합니다. CHAP 암호는 12자에서 57자 사이의 인쇄 가능한 ASCII 문자여야 합니다.
+
[NOTE]
====
컨트롤러에 대한 CHAP 암호가 이전에 구성된 경우 필드의 문자가 마스킹됩니다. 필요한 경우 기존 문자를 바꿀 수 있습니다(새 문자는 마스킹되지 않음).

====
. 다음 중 하나를 수행합니다.
+
** one-way_authentication을 구성하는 경우 * Finish * 를 클릭합니다. 대화 상자가 닫히고 구성이 완료됩니다.
** two-way_authentication을 구성하는 경우 * Next * 를 클릭하여 이니시에이터 CHAP 구성 대화 상자를 표시합니다.


. 양방향 인증의 경우, 12-57자의 인쇄 가능한 ASCII 문자일 수 있는 iSCSI 호스트(이니시에이터)에 대한 CHAP 암호를 입력하거나 확인합니다. 특정 호스트에 대해 양방향 인증을 구성하지 않으려면 이니시에이터 CHAP 암호 필드를 비워 둡니다.
+
[NOTE]
====
호스트에 대한 CHAP 암호가 이전에 구성된 경우 필드의 문자가 마스킹됩니다. 필요한 경우 기존 문자를 바꿀 수 있습니다(새 문자는 마스킹되지 않음).

====
. 마침 * 을 클릭합니다.


.결과
인증을 지정하지 않은 경우, 컨트롤러와 iSCSI 호스트 간의 iSCSI 로그인 시퀀스 중에 인증이 발생합니다.
