---
permalink: sm-settings/configure-snmp-mib-variables.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, snmp, mib, variables, 
summary: 'SNMP 알림의 경우 SNMP 트랩에 나타나는 MIB(Management Information Base) 변수를 선택적으로 구성할 수 있습니다. 이러한 변수는 스토리지 배열 이름, 배열 위치 및 담당자를 반환할 수 있습니다.' 
---
= SANtricity System Manager에서 SNMP MIB 변수 구성
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMP 알림의 경우 SNMP 트랩에 나타나는 MIB(Management Information Base) 변수를 선택적으로 구성할 수 있습니다. 이러한 변수는 스토리지 배열 이름, 배열 위치 및 담당자를 반환할 수 있습니다.

.시작하기 전에
MIB 파일은 SNMP 서비스 응용 프로그램을 사용하여 서버에서 복사 및 컴파일해야 합니다.

MIB 파일이 없는 경우 다음과 같이 얻을 수 있습니다.

* 로 이동합니다 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"^].
* Downloads * 를 클릭한 다음 * Downloads * 를 선택합니다.
* E-Series SANtricity OS 컨트롤러 소프트웨어 * 를 클릭합니다.
* 최신 릴리스 다운로드 * 를 선택합니다.
* 로그인합니다.
* 주의 사항 및 라이센스 계약에 동의합니다.
* 컨트롤러 유형에 대한 MIB 파일이 표시될 때까지 아래로 스크롤한 다음 링크를 클릭하여 파일을 다운로드합니다.


.이 작업에 대해
이 작업에서는 SNMP 트랩에 대한 MIB 변수를 정의하는 방법에 대해 설명합니다. 이러한 변수는 SNMP GetRequests에 응답하여 다음 값을 반환할 수 있습니다.

* SysName(스토리지 배열 이름)
* 'SysLocation'(스토리지 배열 위치)
* SysContact(관리자 이름)


.단계
. 설정 [알림] 메뉴를 선택합니다.
. SNMP * 탭을 선택합니다.
. SNMP MIB 변수 구성 * 을 선택합니다.
+
Configure SNMP MIB Variables(SNMP MIB 변수 구성) 대화 상자가 열립니다.

. 다음 값 중 하나 이상을 입력한 다음 * 저장 * 을 클릭합니다.
+
** * Name * -- MIB 변수 'SysName'의 값입니다. 예를 들어 스토리지 배열의 이름을 입력합니다.
** * Location * -- MIB 변수 'SysLocation'의 값입니다. 예를 들어 스토리지 배열의 위치를 입력합니다.
** * Contact * -- MIB 변수 'SysContact'의 값입니다. 예를 들어 스토리지 시스템을 담당하는 관리자를 입력합니다.




.결과
이러한 값은 스토리지 배열 경고에 대한 SNMP 트랩 메시지에 표시됩니다.
