---
permalink: sm-settings/create-external-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, external, security, key, 
summary: 키 관리 서버에서 드라이브 보안 기능을 사용하려면 스토리지 어레이에서 키 관리 서버와 보안 가능 드라이브가 공유하는 외부 키를 만들어야 합니다. 
---
= 외부 보안 키를 만듭니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
키 관리 서버에서 드라이브 보안 기능을 사용하려면 스토리지 어레이에서 키 관리 서버와 보안 가능 드라이브가 공유하는 외부 키를 만들어야 합니다.

.시작하기 전에
* 스토리지에 보안 가능 드라이브가 설치되어 있어야 합니다. 이러한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다.
+
[NOTE]
====
FDE 및 FIPS 드라이브가 모두 스토리지 어레이에 설치된 경우 모두 동일한 보안 키를 공유합니다.

====
* 드라이브 보안 기능을 활성화해야 합니다. 그렇지 않으면 이 작업 중에 보안 키를 만들 수 없음 대화 상자가 열립니다. 필요한 경우 스토리지 공급업체에 드라이브 보안 기능 활성화에 대한 지침을 문의하십시오.
* 스토리지 배열 컨트롤러의 서명된 클라이언트 인증서 파일이 있고, System Manager에 액세스하는 호스트에 해당 파일을 복사했습니다. 클라이언트 인증서는 스토리지 어레이 컨트롤러의 유효성을 검사하므로 키 관리 서버가 KMIP(Key Management Interoperability Protocol) 요청을 신뢰할 수 있습니다.
* 키 관리 서버에서 인증서 파일을 검색한 다음 System Manager에 액세스할 호스트에 해당 파일을 복사해야 합니다. 키 관리 서버 인증서는 키 관리 서버의 유효성을 검사하므로 스토리지 배열이 해당 IP 주소를 신뢰할 수 있습니다. 키 관리 서버에 루트, 중간 또는 서버 인증서를 사용할 수 있습니다.
+
[NOTE]
====
서버 인증서에 대한 자세한 내용은 키 관리 서버 설명서를 참조하십시오.

====


.이 작업에 대해
이 작업에서는 키 관리 서버의 IP 주소와 사용하는 포트 번호를 정의한 다음 외부 키 관리를 위해 인증서를 로드합니다.

.단계
. 설정 [시스템] 메뉴를 선택합니다.
. 보안 키 관리 * 에서 * 외부 키 생성 * 을 선택합니다.
+
[NOTE]
====
현재 내부 키 관리가 구성되어 있으면 대화 상자가 열리고 외부 키 관리로 전환할지 확인하는 메시지가 표시됩니다.

====
+
외부 보안 키 만들기 대화 상자가 열립니다.

. 키 서버에 연결 * 에서 다음 필드에 정보를 입력합니다.
+
** * 키 관리 서버 주소 * -- 키 관리에 사용되는 서버의 정규화된 도메인 이름 또는 IP 주소(IPv4 또는 IPv6)를 입력합니다.
** * 키 관리 포트 번호 * -- KMIP 통신에 사용되는 포트 번호를 입력합니다. 키 관리 서버 통신에 사용되는 가장 일반적인 포트 번호는 5696입니다.
+
* 선택 사항: * 백업 키 서버를 구성하려면 * 키 서버 추가 * 를 클릭한 다음 해당 서버의 정보를 입력합니다. 기본 키 서버에 연결할 수 없는 경우 두 번째 키 서버가 사용됩니다. 각 키 서버가 동일한 키 데이터베이스에 액세스할 수 있는지 확인합니다. 그렇지 않으면 어레이에서 오류를 게시하고 백업 서버를 사용할 수 없습니다.

+

NOTE: 한 번에 하나의 키 서버만 사용됩니다. 스토리지 배열이 기본 키 서버에 도달할 수 없는 경우, 스토리지는 백업 키 서버에 접속하게 됩니다. 두 서버 간에 패리티를 유지해야 합니다. 그렇지 않으면 오류가 발생할 수 있습니다.

** * 클라이언트 인증서 선택 * -- 첫 번째 * 찾아보기 * 버튼을 클릭하여 스토리지 배열 컨트롤러의 인증서 파일을 선택합니다.
** * 개인 키 파일 선택 * -- 필요한 경우 두 번째 * 찾아보기 * 버튼을 클릭하여 스토리지 배열의 컨트롤러에 대한 개인 키 파일 파일을 선택합니다.
** * 키 관리 서버의 서버 인증서 선택 * -- 세 번째 * 찾아보기 * 버튼을 클릭하여 키 관리 서버의 인증서 파일을 선택합니다. 키 관리 서버에 대한 루트, 중간 또는 서버 인증서를 선택할 수 있습니다.


. 다음 * 을 클릭합니다.
. Create/Backup Key * 에서 보안을 위해 백업 키를 생성할 수 있습니다.
+
** (권장) 백업 키를 만들려면 확인란을 선택한 상태로 두고 암호를 입력하고 확인합니다. 값은 8자에서 32자 사이여야 하며 다음 각 문자를 포함해야 합니다.
+
*** 대문자(하나 이상) 암호는 대/소문자를 구분합니다.
*** 숫자(하나 이상)
*** !, *, @(하나 이상)와 같은 영숫자 이외의 문자입니다.




+
[CAUTION]
====
* 나중에 사용할 수 있도록 항목을 기록해 두십시오 *. 스토리지 어레이에서 보안 지원 드라이브를 이동해야 하는 경우, 드라이브 데이터를 잠금 해제하려면 암호를 알아야 합니다.

====
+
** 백업 키를 생성하지 않으려면 확인란을 선택 취소합니다.
+
[CAUTION]
====
외부 키 서버에 액세스할 수 없고 백업 키가 없는 경우 다른 스토리지 어레이로 마이그레이션하면 드라이브의 데이터에 액세스할 수 없게 됩니다. 이 옵션은 System Manager에서 백업 키를 생성하는 유일한 방법입니다.

====


. 마침 * 을 클릭합니다.
+
입력한 자격 증명을 사용하여 시스템이 키 관리 서버에 연결됩니다. 그런 다음 보안 키의 복사본이 로컬 시스템에 저장됩니다.

+
[NOTE]
====
다운로드한 파일의 경로는 브라우저의 기본 다운로드 위치에 따라 다를 수 있습니다.

====
. 다운로드한 키 파일의 위치와 암호를 기록한 다음 * 닫기 * 를 클릭합니다.
+
외부 키 관리를 위한 추가 링크가 포함된 다음 메시지가 페이지에 표시됩니다.

+
현재 키 관리 방식: 외부

. 테스트 통신 * 을 선택하여 스토리지 어레이와 키 관리 서버 간의 연결을 테스트합니다.
+
대화 상자에 검사 결과가 표시됩니다.



.결과
외부 키 관리를 사용하도록 설정하면 보안 설정된 볼륨 그룹 또는 풀을 생성하거나 기존 볼륨 그룹 및 풀에 대한 보안을 설정할 수 있습니다.

[NOTE]
====
드라이브 전원을 껐다가 다시 켤 때마다 모든 보안 지원 드라이브는 보안 잠금 상태로 변경됩니다. 이 상태에서는 드라이브 초기화 중에 컨트롤러가 올바른 보안 키를 적용할 때까지 데이터에 액세스할 수 없습니다. 잠긴 드라이브를 물리적으로 제거하고 다른 시스템에 설치하는 경우 보안 잠금 상태는 데이터에 대한 무단 액세스를 방지합니다.

====
.작업을 마친 후
키 파일이 손상되지 않도록 보안 키의 유효성을 검사해야 합니다.
