---
permalink: sm-settings/create-internal-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, internal, security, key, 
summary: 드라이브 보안 기능을 사용하려면 스토리지 어레이에서 컨트롤러와 보안 가능 드라이브에서 공유하는 내부 보안 키를 생성해야 합니다. 내부 키는 컨트롤러의 영구 메모리에 유지됩니다. 
---
= 내부 보안 키를 생성합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
드라이브 보안 기능을 사용하려면 스토리지 어레이에서 컨트롤러와 보안 가능 드라이브에서 공유하는 내부 보안 키를 생성해야 합니다. 내부 키는 컨트롤러의 영구 메모리에 유지됩니다.

.시작하기 전에
* 스토리지 배열에 보안 가능 드라이브가 설치되어 있어야 합니다. 이러한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다.
* 드라이브 보안 기능을 활성화해야 합니다. 그렇지 않으면 이 작업 중에 보안 키를 만들 수 없음 대화 상자가 열립니다. 필요한 경우 스토리지 공급업체에 드라이브 보안 기능 활성화에 대한 지침을 문의하십시오.


[NOTE]
====
FDE 및 FIPS 드라이브가 모두 스토리지 어레이에 설치된 경우 모두 동일한 보안 키를 공유합니다.

====
.이 작업에 대해
이 작업에서는 내부 보안 키와 연결할 식별자와 암호를 정의합니다.

[NOTE]
====
Drive Security의 암호는 스토리지 배열의 관리자 암호와 무관합니다.

====
.단계
. 설정 [시스템] 메뉴를 선택합니다.
. 보안 키 관리 * 에서 * 내부 키 생성 * 을 선택합니다.
+
아직 보안 키를 생성하지 않은 경우 보안 키 만들기 대화 상자가 열립니다.

. 다음 필드에 정보를 입력합니다.
+
** * 보안 키 식별자 정의 * -- 기본값(컨트롤러 펌웨어에 의해 생성되는 스토리지 배열 이름 및 타임 스탬프)을 그대로 사용하거나 값을 직접 입력할 수 있습니다. 공백, 구두점 또는 기호 없이 최대 189자의 영숫자 문자를 입력할 수 있습니다.
+
[NOTE]
====
입력한 문자열의 양쪽 끝에 추가된 추가 문자가 자동으로 생성됩니다. 생성된 문자는 식별자가 고유한지 확인합니다.

====
** * 암호문 정의/암호문 다시 입력 * -- 암호문을 입력하고 확인합니다. 값은 8자에서 32자 사이여야 하며 다음 각 문자를 포함해야 합니다.
+
*** 대문자(하나 이상) 암호는 대/소문자를 구분합니다.
*** 숫자(하나 이상)
*** !, *, @(하나 이상)와 같은 영숫자 이외의 문자입니다.




+
[CAUTION]
====
* 나중에 사용할 수 있도록 항목을 기록해 두십시오 *. 스토리지 어레이에서 보안 지원 드라이브를 이동해야 하는 경우, 드라이브 데이터의 잠금을 해제하려면 식별자와 암호를 알아야 합니다.

====
. Create * 를 클릭합니다.
+
보안 키는 컨트롤러에 액세스할 수 없는 위치에 저장됩니다. 실제 키와 함께 암호화된 키 파일이 브라우저에서 다운로드됩니다.

+
[NOTE]
====
다운로드한 파일의 경로는 브라우저의 기본 다운로드 위치에 따라 다를 수 있습니다.

====
. 키 식별자, 암호 및 다운로드한 키 파일의 위치를 기록한 다음 * 닫기 * 를 클릭합니다.


.결과
이제 보안 설정된 볼륨 그룹 또는 풀을 생성하거나 기존 볼륨 그룹 및 풀에 대한 보안을 설정할 수 있습니다.

[NOTE]
====
드라이브 전원을 껐다가 다시 켤 때마다 모든 보안 지원 드라이브는 보안 잠금 상태로 변경됩니다. 이 상태에서는 드라이브 초기화 중에 컨트롤러가 올바른 보안 키를 적용할 때까지 데이터에 액세스할 수 없습니다. 잠긴 드라이브를 물리적으로 제거하고 다른 시스템에 설치하는 경우 보안 잠금 상태는 데이터에 대한 무단 액세스를 방지합니다.

====
.작업을 마친 후
키 파일이 손상되지 않도록 보안 키의 유효성을 검사해야 합니다.
