---
permalink: sm-settings/define-log-policies.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, define, audit, log, policies, 
summary: 덮어쓰기 정책과 감사 로그에 기록된 이벤트 유형을 변경할 수 있습니다. 
---
= 감사 로그 정책을 정의합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
덮어쓰기 정책과 감사 로그에 기록된 이벤트 유형을 변경할 수 있습니다.

.시작하기 전에
보안 관리자 권한이 포함된 사용자 프로필로 로그인해야 합니다. 그렇지 않으면 Access Management 기능이 나타나지 않습니다.

.이 작업에 대해
이 작업에서는 이전 이벤트를 덮어쓰는 정책과 이벤트 유형을 기록하는 정책을 비롯한 감사 로그 설정을 변경하는 방법에 대해 설명합니다.

.단계
. 메뉴: 설정 [Access Management](액세스 관리)를 선택합니다.
. Audit Log(감사 로그) * 탭을 선택합니다.
. 설정 보기/편집 * 을 선택합니다.
+
감사 로그 설정 대화 상자가 열립니다.

. 기록된 이벤트 유형 또는 덮어쓰기 정책을 변경합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
정책 덮어쓰기
 a| 
최대 용량에 도달할 때 이전 이벤트를 덮어쓰는 정책을 결정합니다.

** * 감사 로그가 가득 차면 감사 로그의 가장 오래된 이벤트를 덮어쓰도록 허용 * -- 감사 로그가 50,000개 레코드에 도달할 때 이전 이벤트를 덮어씁니다.
** * 감사 로그 이벤트를 수동으로 삭제해야 함 * -- 이벤트가 자동으로 삭제되지 않도록 지정합니다. 대신 설정된 백분율로 임계값 경고가 표시됩니다. 이벤트는 수동으로 삭제해야 합니다.
+

NOTE: 덮어쓰기 정책을 사용하지 않도록 설정하고 감사 로그 항목이 최대 한도에 도달하면 보안 관리자 권한이 없는 사용자는 System Manager에 액세스할 수 없습니다. 보안 관리자 권한이 없는 사용자에 대한 시스템 액세스를 복원하려면 보안 관리자 역할에 할당된 사용자가 이전 이벤트 레코드를 삭제해야 합니다.

+

NOTE: 감사 로그 보관을 위해 syslog 서버가 구성된 경우 덮어쓰기 정책은 적용되지 않습니다.





 a| 
기록할 작업 수준입니다
 a| 
기록할 이벤트 유형을 결정합니다.

** * 수정 이벤트만 기록 * -- 사용자 작업이 시스템에서 변경을 수행하는 이벤트만 표시합니다.
** * 모든 수정 및 읽기 전용 이벤트 기록 * -- 정보를 읽거나 다운로드하는 사용자 작업을 포함한 모든 이벤트를 표시합니다.


|===
====
. 저장 * 을 클릭합니다.

