---
permalink: sm-settings/drive-security-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, drive, security, terms, 
summary: 드라이브 보안 조건이 스토리지 어레이에 적용되는 방식에 대해 알아보십시오. 
---
= 드라이브 보안 용어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
드라이브 보안 조건이 스토리지 어레이에 적용되는 방식에 대해 알아보십시오.

[cols="25h,~"]
|===
| 기간 | 설명 


 a| 
드라이브 보안 기능
 a| 
드라이브 보안은 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브를 통해 추가 보안 계층을 제공하는 스토리지 어레이 기능입니다. 이러한 드라이브를 드라이브 보안 기능과 함께 사용하는 경우 데이터에 액세스하려면 보안 키가 필요합니다. 드라이브가 어레이에서 물리적으로 제거되면 다른 어레이에 설치될 때까지 작동할 수 없으며, 이때 올바른 보안 키가 제공될 때까지 보안 잠금 상태가 됩니다.



 a| 
FDE 드라이브
 a| 
FDE(전체 디스크 암호화) 드라이브는 하드웨어 레벨의 디스크 드라이브에서 암호화를 수행합니다. 하드 드라이브에는 쓰기 중에 데이터를 암호화한 다음 읽기 중에 데이터를 해독하는 ASIC 칩이 포함되어 있습니다.



 a| 
FIPS 드라이브
 a| 
FIPS 드라이브는 FIPS(Federal Information Processing Standards) 140-2 레벨 2를 사용합니다. 이러한 드라이브는 강력한 암호화 알고리즘 및 방법을 보장하는 미국 정부 표준을 준수하는 FDE 드라이브입니다. FIPS 드라이브는 FDE 드라이브보다 보안 표준이 더 높습니다.



 a| 
관리 클라이언트
 a| 
System Manager 액세스를 위한 브라우저가 포함된 로컬 시스템(컴퓨터, 태블릿 등)



 a| 
암호 구문
 a| 
암호 구문은 백업을 위해 보안 키를 암호화하는 데 사용됩니다. 드라이브 마이그레이션 또는 헤드 스왑의 결과로 백업된 보안 키를 가져올 때 보안 키를 암호화하는 데 사용된 것과 동일한 암호를 제공해야 합니다. 암호문은 8자에서 32자 사이여야 합니다.

[NOTE]
====
Drive Security의 암호는 스토리지 배열의 관리자 암호와 무관합니다.

====


 a| 
보안 지원 드라이브
 a| 
보안이 가능한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있으며, 이 드라이브는 쓰기 중에 데이터를 암호화하고 읽기 중에 데이터를 해독합니다. 이러한 드라이브는 드라이브 보안 기능을 사용하여 추가 보안을 위해 사용할 수 있으므로 보안 -_가능_으로 간주됩니다. 드라이브 보안 기능이 이러한 드라이브에 사용된 볼륨 그룹 및 풀에 대해 활성화된 경우 드라이브는 secure-_enabled_가 됩니다.



 a| 
보안 지원 드라이브
 a| 
보안 지원 드라이브는 드라이브 보안 기능과 함께 사용됩니다. 드라이브 보안 기능을 활성화한 다음 보안 -_가능_ 드라이브의 풀 또는 볼륨 그룹에 드라이브 보안을 적용하면 드라이브는 보안__- 사용__ 상태가 됩니다. 읽기 및 쓰기 액세스는 올바른 보안 키로 구성된 컨트롤러를 통해서만 사용할 수 있습니다. 이렇게 추가된 보안으로 인해 스토리지 어레이에서 물리적으로 제거된 드라이브의 데이터에 대한 무단 액세스가 방지됩니다.



 a| 
보안 키
 a| 
보안 키는 스토리지 어레이에서 보안 지원 드라이브와 컨트롤러 간에 공유되는 문자의 문자열입니다. 드라이브 전원을 껐다가 켤 때마다 보안 활성 드라이브는 컨트롤러가 보안 키를 적용할 때까지 보안 잠금 상태로 변경됩니다. 스토리지 어레이에서 보안 지원 드라이브를 제거하면 드라이브의 데이터가 잠깁니다. 드라이브가 다른 스토리지 배열에 다시 설치되면 데이터를 다시 액세스할 수 있도록 하기 전에 보안 키를 찾습니다. 데이터의 잠금을 해제하려면 원래 보안 키를 적용해야 합니다. 다음 방법 중 하나를 사용하여 보안 키를 만들고 관리할 수 있습니다.

* 내부 키 관리 -- 컨트롤러의 영구 메모리에 보안 키를 만들고 관리합니다.
* 외부 키 관리 -- 외부 키 관리 서버에 보안 키를 만들고 유지 관리합니다.




 a| 
보안 키 식별자입니다
 a| 
보안 키 식별자는 키를 생성하는 동안 보안 키와 연결된 문자열입니다. 식별자는 컨트롤러와 보안 키와 연결된 모든 드라이브에 저장됩니다.

|===