---
permalink: sm-settings/enable-feature-pack.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, feature, pack, 
summary: '기능 팩은 스토리지 배열 속성을 변경하는 번들(예: 프로토콜을 Fibre Channel에서 iSCSI로 변경)입니다. 기능 팩에는 지원을 위한 특수 키가 필요합니다.' 
---
= SANtricity System Manager에서 기능 팩 활성화
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기능 팩은 스토리지 배열 속성을 변경하는 번들(예: 프로토콜을 Fibre Channel에서 iSCSI로 변경)입니다. 기능 팩에는 지원을 위한 특수 키가 필요합니다.

.시작하기 전에
* 새 스토리지 배열 속성의 변환 및 준비를 설명하는 적절한 지침을 따랐습니다. 호스트 프로토콜 변환 지침은 해당 컨트롤러 모델의 하드웨어 유지보수 가이드를 참조하십시오.
* 스토리지 배열이 오프라인이므로 호스트 또는 애플리케이션이 이를 액세스하지 않습니다.
* 모든 데이터가 백업됩니다.
* 기능 팩 파일을 받았습니다.
+
기능 팩 파일이 관리 클라이언트(System Manager 액세스를 위한 브라우저가 있는 시스템)에 로드됩니다.



[NOTE]
====
다운타임 유지 관리 창을 예약하고 호스트와 컨트롤러 사이의 모든 I/O 작업을 중지해야 합니다. 또한 변환을 성공적으로 완료할 때까지 스토리지 배열의 데이터에 액세스할 수 없습니다.

====
.이 작업에 대해
이 작업에서는 System Manager를 사용하여 기능 팩을 설정하는 방법에 대해 설명합니다. 작업을 마치면 스토리지 배열을 다시 시작해야 합니다.

.단계
. 설정 [시스템] 메뉴를 선택합니다.
. 추가 기능 * 아래에서 * 기능 팩 변경 * 을 선택합니다.
. 찾아보기 * 를 클릭한 다음 키 파일을 선택합니다.
+
대화 상자에 파일 이름이 표시됩니다.

. 필드에 change를 입력합니다.
. 변경 * 을 클릭합니다.
+
기능 팩 마이그레이션이 시작되고 컨트롤러가 재부팅됩니다. 기록되지 않은 캐시 데이터가 삭제되어 입출력 작업이 발생하지 않습니다. 두 컨트롤러가 자동으로 재부팅되므로 새로운 기능 팩이 적용됩니다. 재부팅이 완료되면 스토리지 배열이 응답 상태로 돌아갑니다.


