---
permalink: sm-settings/enable-iscsi-discovery-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, iscsi, discovery, settings, 
summary: iSCSI 네트워크에서 스토리지 디바이스 검색과 관련된 설정을 설정할 수 있습니다. 
---
= iSCSI 검색 설정을 활성화합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI 네트워크에서 스토리지 디바이스 검색과 관련된 설정을 설정할 수 있습니다.

대상 검색 설정을 사용하면 iSNS(Internet Storage Name Service) 프로토콜을 사용하여 스토리지 배열의 iSCSI 정보를 등록하고 명명되지 않은 검색 세션을 허용할지 여부를 결정할 수 있습니다.

.시작하기 전에
iSNS 서버가 정적 IP 주소를 사용하는 경우 iSNS 등록에 해당 주소를 사용할 수 있어야 합니다. IPv4와 IPv6가 모두 지원됩니다.

.이 작업에 대해
iSCSI 검색과 관련된 다음 설정을 활성화할 수 있습니다.

* * iSNS 서버를 사용하여 타겟을 등록합니다. * -- 이 옵션을 설정하면 스토리지 어레이가 iSNS 서버의 iSCSI IQN(Qualified Name) 및 포트 정보를 등록합니다. 이 설정은 iSNS 검색을 허용하므로 이니시에이터는 iSNS 서버에서 IQN 및 포트 정보를 검색할 수 있습니다.
* * 이름 없는 검색 세션 활성화 * -- 이름 없는 검색 세션이 활성화되면 이니시에이터(iSCSI 호스트)가 검색 유형 연결을 위한 로그인 시퀀스 중에 타겟(컨트롤러)의 IQN을 제공할 필요가 없습니다. 비활성화된 경우 호스트는 IQN을 제공하여 컨트롤러에 검색 세션을 설정해야 합니다. 하지만 정상(입출력 베어링) 세션에 대해서는 타겟 IQN이 항상 필요합니다. 이 설정을 비활성화하면 권한이 없는 iSCSI 호스트가 해당 IP 주소만 사용하여 컨트롤러에 연결하는 것을 방지할 수 있습니다.


[NOTE]
====
iSCSI 설정 및 기능은 스토리지 배열이 iSCSI를 지원하는 경우에만 설정 페이지에 표시됩니다.

====
.단계
. 설정 [시스템] 메뉴를 선택합니다.
. iSCSI 설정 * 에서 * 대상 검색 설정 보기/편집 * 을 클릭합니다.
+
대상 검색 설정 대화 상자가 나타납니다. iSNS 서버 사용 *... 필드 아래에 컨트롤러가 이미 등록되어 있는지 여부를 나타내는 대화 상자가 나타납니다.

. 컨트롤러를 등록하려면 * iSNS 서버를 사용하여 대상 등록 * 을 선택한 후 다음 중 하나를 선택합니다.
+
** * DHCP 서버에서 자동으로 구성 가져오기 * -- DHCP(Dynamic Host Configuration Protocol) 서버를 사용하여 iSNS 서버를 구성하려면 이 옵션을 선택합니다. 이 옵션을 사용하는 경우 컨트롤러의 모든 iSCSI 포트에서도 DHCP를 사용하도록 구성해야 합니다. 필요한 경우 컨트롤러 iSCSI 포트 설정을 업데이트하여 이 옵션을 활성화합니다.
+
[NOTE]
====
DHCP 서버가 iSNS 서버 주소를 제공하려면 옵션 43--""공급업체 특정 정보"를 사용하도록 DHCP 서버를 구성해야 합니다. 이 옵션은 데이터 바이트 0xa-0xd(10-13)로 iSNS 서버 IPv4 주소를 포함해야 합니다.

====
** * 수동으로 정적 구성 지정 * -- iSNS 서버의 정적 IP 주소를 입력하려면 이 옵션을 선택합니다. (필요한 경우 주소를 잘라내어 필드에 붙여 넣을 수 있습니다.) 필드에 IPv4 주소 또는 IPv6 주소를 입력합니다. 둘 다 구성한 경우 IPv4가 기본값입니다. 또한 TCP 수신 대기 포트를 입력합니다(기본값 3205를 사용하거나 49152와 65535 사이의 값을 입력합니다).


. 스토리지 배열이 명명되지 않은 검색 세션에 참여할 수 있도록 하려면 * 명명되지 않은 검색 세션 활성화 * 를 선택합니다.
+
** 이 옵션을 설정하면 컨트롤러의 정보를 검색하기 위해 타겟 IQN을 지정하는 데 iSCSI 이니시에이터가 필요하지 않습니다.
** 비활성화된 경우 이니시에이터가 타겟 IQN을 제공하지 않으면 검색 세션이 차단됩니다. 명명되지 않은 검색 세션을 비활성화하면 보안이 강화됩니다.


. 저장 * 을 클릭합니다.


.결과
System Manager에서 iSNS 서버에 컨트롤러를 등록하려고 하면 진행률 표시줄이 나타납니다. 이 프로세스는 최대 5분 정도 걸릴 수 있습니다.
