---
permalink: sm-settings/enable-or-disable-resource-provisioning-for-new-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, disable, resource, provisioning, 
summary: 이전에 리소스 프로비저닝의 기본 기능을 해제한 경우 설정 으로 이동하여 새로 생성한 모든 SSD 볼륨 그룹 또는 풀에 대해 다시 설정할 수 있습니다. 설정을 다시 비활성화할 수도 있습니다. 
---
= 새 볼륨 그룹 또는 풀에 대한 리소스 프로비저닝을 설정하거나 해제합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이전에 리소스 프로비저닝을 위한 기본 기능을 비활성화한 경우 새로 생성한 모든 SSD 볼륨 그룹 또는 풀에 대해 다시 설정할 수 있습니다. 설정을 다시 비활성화할 수도 있습니다.

리소스 프로비저닝은 EF300 및 EF600 스토리지 어레이에서 사용 가능한 기능으로, 백그라운드 초기화 프로세스 없이 볼륨을 즉시 사용할 수 있도록 지원합니다. 볼륨에 할당된 모든 드라이브 블록이 할당 해제(매핑 해제)되어 SSD 마모 수명을 개선하고 최대 쓰기 성능을 높일 수 있습니다.


NOTE: 기본적으로 드라이브가 DULBE를 지원하는 시스템에서 리소스 프로비저닝이 설정됩니다.

.시작하기 전에
* EF300 또는 EF600 스토리지 어레이가 있어야 합니다.
* 모든 드라이브에서 NVMe 할당 해제 또는 DULBE(UnWritten Logical Block Error Enable) 오류 복구 기능을 지원하는 SSD 볼륨 그룹 또는 풀이 있어야 합니다.


.이 작업에 대해
새 볼륨 그룹 또는 풀에 대해 리소스 프로비저닝을 다시 설정하면 새로 생성한 볼륨 그룹 및 풀만 영향을 받습니다. 리소스 프로비저닝이 설정된 기존 볼륨 그룹 및 풀은 변경되지 않습니다.

.단계
. 설정 [시스템] 메뉴를 선택합니다.
. 아래로 스크롤하여 * 추가 설정 * 을 찾은 다음 * 리소스 프로비저닝된 볼륨 * 사용/사용 안 함 을 클릭합니다.
+
설정 설명은 리소스 프로비저닝이 현재 활성화되어 있는지 여부를 나타냅니다.

. 대화 상자에서 작업을 확인합니다.


.결과
리소스 프로비저닝을 설정하거나 해제하면 생성한 새 SSD 풀 또는 볼륨 그룹에만 영향을 줍니다. 기존 풀 또는 볼륨 그룹은 변경되지 않습니다.
