---
permalink: sm-settings/enable-certificate-revocation-checking.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, certificate, revocation checking, 
summary: 'OCSP(Online Certificate Status Protocol) 서버가 비보안 연결을 만드는 사용자를 차단하도록 해지된 인증서를 자동으로 검사할 수 있습니다.' 
---
= 인증서 해지 확인을 사용합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OCSP(Online Certificate Status Protocol) 서버가 비보안 연결을 만드는 사용자를 차단하도록 해지된 인증서를 자동으로 검사할 수 있습니다.

.시작하기 전에
* 보안 관리자 권한이 포함된 사용자 프로필로 로그인해야 합니다. 그렇지 않으면 인증서 기능이 나타나지 않습니다.
* DNS 서버는 두 컨트롤러 모두에 구성되어 OCSP 서버에 정규화된 도메인 이름을 사용할 수 있습니다. 이 작업은 하드웨어 페이지에서 사용할 수 있습니다.
* 사용자 고유의 OCSP 서버를 지정하려면 해당 서버의 URL을 알아야 합니다.


.이 작업에 대해
CA에서 인증서를 잘못 발급했거나 개인 키가 손상된 경우 자동 해지 확인을 사용하는 것이 좋습니다.

이 작업 중에 OCSP 서버를 구성하거나 인증서 파일에 지정된 서버를 사용할 수 있습니다. OCSP 서버는 CA가 예약된 만료 날짜 이전에 인증서를 취소할지 여부를 확인한 다음 인증서가 해지될 경우 사용자가 사이트에 액세스하지 못하도록 차단합니다.

.단계
. 설정 [인증서] 메뉴를 선택합니다.
. 신뢰할 수 있는 * 탭을 선택합니다.
+
[NOTE]
====
키 관리 * 탭에서 해지 확인을 활성화할 수도 있습니다.

====
. Uncommon Tasks * 를 클릭한 다음 드롭다운 메뉴에서 * Enable Revocation Checking * 을 선택합니다.
. 해지 확인을 활성화하겠습니다 * 를 선택하면 확인란에 확인 표시가 나타나고 대화 상자에 추가 필드가 나타납니다.
. OCSP 응답자 주소* 필드에 OCSP 응답자 서버의 URL을 선택적으로 입력할 수 있습니다. 주소를 입력하지 않으면 시스템에서 인증서 파일의 OCSP 서버 URL을 사용합니다.
. Test Address * 를 클릭하여 시스템이 지정된 URL에 대한 연결을 열 수 있는지 확인합니다.
. 저장 * 을 클릭합니다.


.결과
스토리지 배열이 인증서가 해지된 서버에 연결을 시도하면 연결이 거부되고 이벤트가 기록됩니다.
