---
permalink: sm-settings/faq-storage-system-alerts.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager에 대한 스토리지 시스템 알림 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 경고가 비활성화되면 어떻게 합니까?

관리자가 스토리지 어레이에서 발생하는 중요한 이벤트에 대한 알림을 받도록 하려면 경고 방법을 구성해야 합니다.

SANtricity System Manager로 관리되는 스토리지 어레이의 경우 경고 페이지에서 경고를 구성합니다. 경고 알림은 이메일, SNMP 트랩 또는 syslog 메시지를 통해 보낼 수 있습니다. 또한 초기 설정 마법사에서 이메일 경고를 구성할 수도 있습니다.



== SNMP 또는 syslog 알림을 구성하려면 어떻게 합니까?

e-메일 알림 외에도 SNMP(Simple Network Management Protocol) 트랩 또는 syslog 메시지를 통해 보낼 알림을 구성할 수 있습니다.

SNMP 또는 syslog 알림을 구성하려면 설정 [경고] 메뉴로 이동합니다.



== 타임스탬프가 스토리지와 알림 간에 일치하지 않는 이유는 무엇입니까?

스토리지 시스템에서 알림을 보낼 때 알림을 받는 타겟 서버 또는 호스트의 표준 시간대가 올바르지 않습니다. 대신 스토리지 배열은 로컬 시간(GMT)을 사용하여 경고 레코드에 사용되는 타임스탬프를 생성합니다. 따라서 스토리지 어레이의 타임스탬프와 알림을 수신하는 서버 또는 호스트의 일치하지 않는 부분이 표시될 수 있습니다.

스토리지 배열이 경고를 보낼 때 표준 시간대에 대해 올바르지 않기 때문에 경고의 타임스탬프는 GMT-상대 시간이며 시간 영역 오프셋이 0입니다. 현지 시간대에 맞는 타임스탬프를 계산하려면 GMT에서 시간 오프셋을 결정한 다음 타임스탬프에서 해당 값을 더하거나 빼야 합니다.
