---
permalink: sm-settings/faq-storage-drive-security.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager를 위한 스토리지 드라이브 보안 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 보안 키를 생성하기 전에 알아야 할 사항은 무엇입니까?

보안 키는 스토리지 시스템 내의 컨트롤러 및 보안 지원 드라이브에서 공유됩니다. 스토리지 배열에서 보안 지원 드라이브를 제거하면 보안 키가 무단 액세스로부터 데이터를 보호합니다.

다음 방법 중 하나를 사용하여 보안 키를 만들고 관리할 수 있습니다.

* 컨트롤러의 영구 메모리에서 내부 키 관리.
* 외부 키 관리 서버의 외부 키 관리.




=== 내부 키 관리

내부 키는 컨트롤러의 영구 메모리에 액세스할 수 없는 위치에 유지되고 "숨김"됩니다. 내부 보안 키를 생성하기 전에 다음을 수행해야 합니다.

. 스토리지 배열에 보안 가능 드라이브를 설치합니다. 이러한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다.
. 드라이브 보안 기능이 활성화되어 있는지 확인합니다. 필요한 경우 스토리지 공급업체에 드라이브 보안 기능 활성화에 대한 지침을 문의하십시오.


그런 다음 식별자 및 암호 구문을 정의하는 내부 보안 키를 만들 수 있습니다. 식별자는 보안 키와 연결된 문자열이며, 컨트롤러와 키에 연결된 모든 드라이브에 저장됩니다. 암호 구문은 백업을 위해 보안 키를 암호화하는 데 사용됩니다. 작업을 마치면 보안 키가 컨트롤러에 액세스할 수 없는 위치에 저장됩니다. 그런 다음 보안이 설정된 볼륨 그룹 또는 풀을 생성하거나 기존 볼륨 그룹 및 풀에 대한 보안을 설정할 수 있습니다.



=== 외부 키 관리

외부 키는 KMIP(Key Management Interoperability Protocol)를 사용하여 별도의 키 관리 서버에 유지됩니다. 외부 보안 키를 만들기 전에 다음을 수행해야 합니다.

. 스토리지 배열에 보안 가능 드라이브를 설치합니다. 이러한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다.
. 드라이브 보안 기능이 활성화되어 있는지 확인합니다. 필요한 경우 스토리지 공급업체에 드라이브 보안 기능 활성화에 대한 지침을 문의하십시오.
. 서명된 클라이언트 인증서 파일을 가져옵니다. 클라이언트 인증서가 스토리지 어레이 컨트롤러의 유효성을 검사하므로 키 관리 서버가 KMIP 요청을 신뢰할 수 있습니다.
+
.. 먼저 CSR(Client Certificate Signing Request)을 완료하고 다운로드합니다. 설정 [인증서 > 키 관리 > CSR 완료] 메뉴로 이동합니다.
.. 그런 다음 키 관리 서버에서 신뢰할 수 있는 CA로부터 서명된 클라이언트 인증서를 요청합니다. (다운로드한 CSR 파일을 사용하여 키 관리 서버에서 클라이언트 인증서를 생성하고 다운로드할 수도 있습니다.)
.. 클라이언트 인증서 파일이 있는 경우 해당 파일을 System Manager에 액세스할 호스트에 복사합니다.


. 키 관리 서버에서 인증서 파일을 가져온 다음 System Manager에 액세스하는 호스트에 해당 파일을 복사합니다. 키 관리 서버 인증서는 키 관리 서버의 유효성을 검사하므로 스토리지 배열이 해당 IP 주소를 신뢰할 수 있습니다. 키 관리 서버에 루트, 중간 또는 서버 인증서를 사용할 수 있습니다.


그런 다음 외부 키를 생성하여 키 관리 서버의 IP 주소와 KMIP 통신에 사용되는 포트 번호를 정의할 수 있습니다. 이 프로세스 중에 인증서 파일도 로드합니다. 작업을 마치면 입력한 자격 증명을 사용하여 시스템이 키 관리 서버에 연결됩니다. 그런 다음 보안이 설정된 볼륨 그룹 또는 풀을 생성하거나 기존 볼륨 그룹 및 풀에 대한 보안을 설정할 수 있습니다.



== 암호문을 정의해야 하는 이유는 무엇입니까?

암호 구문은 로컬 관리 클라이언트에 저장된 보안 키 파일을 암호화하고 해독하는 데 사용됩니다. 암호 구문이 없으면 보안 키를 해독할 수 없으며 다른 스토리지 배열에 다시 설치한 경우 보안 활성 드라이브에서 데이터의 잠금을 해제하는 데 사용할 수 없습니다.



== 보안 키 정보를 기록하는 것이 중요한 이유는 무엇입니까?

보안 키 정보가 손실되고 백업이 없는 경우, 보안 지원 드라이브를 재배치하거나 컨트롤러를 업그레이드할 때 데이터가 손실될 수 있습니다. 드라이브에서 데이터를 잠금 해제하려면 보안 키가 필요합니다.

보안 키 식별자, 연결된 암호 구문 및 보안 키 파일이 저장된 로컬 호스트의 위치를 기록해야 합니다.



== 보안 키를 백업하기 전에 알아야 할 내용은 무엇입니까?

원래 보안 키가 손상되고 백업이 없는 경우, 한 스토리지 어레이에서 다른 스토리지 어레이로 마이그레이션할 경우 드라이브의 데이터에 액세스할 수 없게 됩니다.

보안 키를 백업하기 전에 다음 지침을 염두에 두십시오.

* 원본 키 파일의 보안 키 식별자 및 암호를 알고 있어야 합니다.
+
[NOTE]
====
내부 키만 식별자를 사용합니다. 식별자를 만들면 추가 문자가 자동으로 생성되고 식별자 문자열의 양쪽 끝에 추가됩니다. 생성된 문자는 식별자가 고유한지 확인합니다.

====
* 백업에 대한 새 암호를 만듭니다. 이 암호문은 원래 키를 만들거나 마지막으로 변경할 때 사용한 암호문과 일치하지 않아도 됩니다. 암호는 생성 중인 백업에만 적용됩니다.
+
[NOTE]
====
드라이브 보안의 암호를 스토리지 배열의 관리자 암호와 혼동해서는 안 됩니다. Drive Security의 암호 구문은 보안 키의 백업을 보호합니다. 관리자 암호를 사용하면 전체 스토리지 시스템이 무단으로 액세스하지 못하도록 보호할 수 있습니다.

====
* 백업 보안 키 파일이 관리 클라이언트에 다운로드됩니다. 다운로드한 파일의 경로는 브라우저의 기본 다운로드 위치에 따라 다를 수 있습니다. 보안 키 정보가 저장된 위치를 기록해 두십시오.




== 보안 드라이브를 잠금 해제하기 전에 알아야 할 사항은 무엇입니까?

보안 지원 드라이브에서 데이터의 잠금을 해제하려면 해당 보안 키를 가져와야 합니다.

보안 지원 드라이브를 잠금 해제하기 전에 다음 지침을 염두에 두십시오.

* 스토리지 배열에 이미 보안 키가 있어야 합니다. 마이그레이션된 드라이브는 대상 스토리지 배열에 다시 연결됩니다.
* 마이그레이션하는 드라이브의 경우 보안 키 식별자와 보안 키 파일에 해당하는 암호 구문을 알아야 합니다.
* 보안 키 파일은 관리 클라이언트(System Manager 액세스에 사용되는 브라우저가 있는 시스템)에서 사용할 수 있어야 합니다.
* 잠긴 NVMe 드라이브를 재설정하는 경우 드라이브의 보안 ID를 입력해야 합니다. 보안 ID를 찾으려면 드라이브를 물리적으로 제거하고 드라이브 레이블에서 PSID 문자열(최대 32자)을 찾아야 합니다. 작업을 시작하기 전에 드라이브를 다시 설치해야 합니다.




== 읽기/쓰기 접근성이란 무엇입니까?

드라이브 설정 창에는 드라이브 보안 속성에 대한 정보가 포함되어 있습니다. "읽기/쓰기 액세스 가능"은 드라이브의 데이터가 잠겨 있는지 여부를 표시하는 속성 중 하나입니다.

드라이브 보안 속성을 보려면 하드웨어 페이지로 이동합니다. 드라이브를 선택하고 * 설정 보기 * 를 클릭한 다음 * 추가 설정 표시 * 를 클릭합니다. 드라이브의 잠금이 해제될 때 페이지 하단에서 읽기/쓰기 액세스 가능 속성 값은 * 예 * 입니다. 읽기/쓰기 액세스 가능 속성 값은 드라이브가 잠겨 있을 때 * 아니오, 유효하지 않은 보안 키 * 입니다. 보안 키를 가져와 보안 드라이브의 잠금을 해제할 수 있습니다(설정 [시스템 > 보안 드라이브 잠금 해제] 메뉴로 이동).



== 보안 키 유효성 검사에 대해 알아야 할 내용은 무엇입니까?

보안 키를 만든 후에는 키 파일이 손상되지 않았는지 확인해야 합니다.

유효성 검사에 실패하면 다음을 수행합니다.

* 보안 키 식별자가 컨트롤러의 식별자와 일치하지 않는 경우 올바른 보안 키 파일을 찾은 다음 확인을 다시 시도하십시오.
* 컨트롤러가 유효성 검사를 위해 보안 키를 해독할 수 없는 경우 암호 구문을 잘못 입력했을 수 있습니다. 암호를 다시 확인하고 필요한 경우 다시 입력한 다음 확인을 다시 시도하십시오. 오류 메시지가 다시 나타나면 키 파일의 백업을 선택하고(있는 경우) 유효성 검사를 다시 시도하십시오.
* 여전히 보안 키의 유효성을 검사할 수 없는 경우 원본 파일이 손상되었을 수 있습니다. 키의 새 백업을 생성하고 해당 복사본을 확인합니다.




== 내부 보안 키와 외부 보안 키 관리의 차이점은 무엇입니까?

드라이브 보안 기능을 구현할 때 스토리지 배열에서 보안 지원 드라이브를 제거할 때 내부 보안 키 또는 외부 보안 키를 사용하여 데이터를 잠글 수 있습니다.

보안 키는 문자열을 말합니다. 이 문자열은 스토리지 어레이에서 보안이 설정된 드라이브와 컨트롤러 간에 공유됩니다. 내부 키는 컨트롤러의 영구 메모리에 유지됩니다. 외부 키는 KMIP(Key Management Interoperability Protocol)를 사용하여 별도의 키 관리 서버에 유지됩니다.
