---
permalink: sm-settings/how-access-management-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, authentication, users, roles, access, Management, 
summary: 액세스 관리는 SANtricity 시스템 관리자에서 사용자 인증을 설정하는 방법입니다. 
---
= 액세스 관리 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
액세스 관리는 SANtricity 시스템 관리자에서 사용자 인증을 설정하는 방법입니다.

구성 및 사용자 인증은 다음과 같이 작동합니다.

. 관리자는 보안 관리자 권한이 포함된 사용자 프로필을 사용하여 System Manager에 로그인합니다.
+
[NOTE]
====
처음 로그인하는 경우 사용자 이름 admin이 자동으로 표시되며 변경할 수 없습니다. admin 사용자는 시스템의 모든 기능에 액세스할 수 있습니다.

====
. 관리자는 사용자 인터페이스에서 Access Management(액세스 관리)로 이동합니다. 스토리지 어레이는 RBAC(역할 기반 액세스 제어) 기능을 구현하는 로컬 사용자 역할을 사용하도록 사전 구성됩니다.
. 관리자는 다음 인증 방법 중 하나 이상을 구성합니다.
+
** * 로컬 사용자 역할 * -- 스토리지 어레이에 적용된 RBAC 기능을 통해 인증이 관리됩니다. 로컬 사용자 역할에는 미리 정의된 사용자 프로필과 특정 액세스 권한이 있는 역할이 포함됩니다. 관리자는 이러한 로컬 사용자 역할을 단일 인증 방법으로 사용하거나 디렉터리 서비스와 함께 사용할 수 있습니다. 사용자 암호 설정 이외의 구성은 필요하지 않습니다.
** * 디렉터리 서비스 * -- 인증은 LDAP(Lightweight Directory Access Protocol) 서버 및 Microsoft의 Active Directory와 같은 디렉터리 서비스를 통해 관리됩니다. 관리자는 LDAP 서버에 연결한 다음 LDAP 사용자를 스토리지 배열에 포함된 로컬 사용자 역할에 매핑합니다.
** * SAML * -- 인증은 SAML(Security Assertion Markup Language) 2.0을 사용하여 ID 공급자(IDP)를 통해 관리됩니다. 관리자는 IdP 시스템과 스토리지 어레이 간의 통신을 설정한 다음 IdP 사용자를 스토리지 어레이에 포함된 로컬 사용자 역할에 매핑합니다.


. 관리자는 사용자에게 System Manager에 대한 로그인 자격 증명을 제공합니다.
. 사용자는 자격 증명을 입력하여 시스템에 로그인합니다.
+
[NOTE]
====
SAML 및 SSO(Single Sign-On)로 인증이 관리되는 경우 시스템은 System Manager 로그인 대화 상자를 건너뛸 수 있습니다.

====
+
로그인 중에 시스템은 다음과 같은 백그라운드 작업을 수행합니다.

+
** 사용자 계정에 대해 사용자 이름과 암호를 인증합니다.
** 할당된 역할에 따라 사용자의 권한을 결정합니다.
** 사용자에게 사용자 인터페이스의 작업에 대한 액세스 권한을 제공합니다.
** 인터페이스의 오른쪽 위에 사용자 이름을 표시합니다.






== System Manager에서 사용 가능한 작업

작업에 대한 액세스 권한은 사용자가 할당한 역할에 따라 다르며, 여기에는 다음이 포함됩니다.

* * 스토리지 관리자 * -- 스토리지 객체(예: 볼륨 및 디스크 풀)에 대한 전체 읽기/쓰기 액세스이지만 보안 구성에 대한 액세스는 없습니다.
* * 보안 관리자 * -- 액세스 관리, 인증서 관리, 감사 로그 관리 및 레거시 관리 인터페이스(기호)를 켜거나 끌 수 있는 기능의 보안 구성에 액세스합니다.
* * 지원 관리자 * -- 스토리지 어레이의 모든 하드웨어 리소스, 장애 데이터, MEL 이벤트 및 컨트롤러 펌웨어 업그레이드에 액세스합니다. 스토리지 객체 또는 보안 구성에 대한 액세스 권한이 없습니다.
* * Monitor * -- 모든 스토리지 객체에 대한 읽기 전용 액세스이지만 보안 구성에 대한 액세스는 없습니다.


사용할 수 없는 작업은 회색으로 표시되거나 사용자 인터페이스에 표시되지 않습니다. 예를 들어 Monitor 역할을 가진 사용자는 볼륨에 대한 모든 정보를 볼 수 있지만 해당 볼륨을 수정하기 위한 기능에는 액세스할 수 없습니다. Copy Services * 및 * Add to Workload * 와 같은 기능에 대한 탭은 회색으로 표시되고 * View/Edit Settings * 만 사용할 수 있습니다.



== Unified Manager 및 Storage Manager의 제한 사항

스토리지에 대해 SAML이 구성된 경우 사용자는 Unified Manager 또는 기존 Storage Manager 인터페이스에서 해당 스토리지에 대한 스토리지를 검색 또는 관리할 수 없습니다.

로컬 사용자 역할 및 디렉터리 서비스가 구성된 경우 사용자는 다음 기능을 수행하기 전에 자격 증명을 입력해야 합니다.

* 스토리지 배열의 이름을 바꿉니다
* 컨트롤러 펌웨어 업그레이드 중
* 스토리지 배열 구성을 로드하는 중입니다
* 스크립트 실행
* 사용하지 않는 세션이 시간 초과된 경우 활성 작업을 수행하려고 합니다

