---
permalink: sm-settings/how-the-drive-security-feature-works.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, Drive Security, 
summary: '드라이브 보안은 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브를 통해 추가 보안 계층을 제공하는 스토리지 어레이 기능입니다.' 
---
= 드라이브 보안 기능의 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
드라이브 보안은 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브를 통해 추가 보안 계층을 제공하는 스토리지 어레이 기능입니다.

이러한 드라이브를 드라이브 보안 기능과 함께 사용하는 경우 데이터에 액세스하려면 보안 키가 필요합니다. 드라이브가 어레이에서 물리적으로 제거되면 다른 어레이에 설치될 때까지 작동할 수 없으며, 이때 올바른 보안 키가 제공될 때까지 보안 잠금 상태가 됩니다.



== 드라이브 보안을 구현하는 방법

드라이브 보안을 구현하려면 다음 단계를 수행하십시오.

. 스토리지 어레이에 FDE 드라이브 또는 FIPS 드라이브와 같은 보안 지원 드라이브를 제공합니다. (FIPS 지원이 필요한 볼륨의 경우 FIPS 드라이브만 사용합니다. 볼륨 그룹 또는 풀에서 FIPS 및 FDE 드라이브를 혼합하면 모든 드라이브가 FDE 드라이브로 처리됩니다. 또한 FDE 드라이브는 All-FIPS 볼륨 그룹 또는 풀에서 스페어로 추가하거나 사용할 수 없습니다.)
. 컨트롤러 및 드라이브에서 읽기/쓰기 액세스를 위해 공유하는 일련의 문자인 보안 키를 생성합니다. 컨트롤러의 영구 메모리에서 내부 키를 만들거나 키 관리 서버에서 외부 키를 만들 수 있습니다. 외부 키 관리의 경우 키 관리 서버를 사용하여 인증을 설정해야 합니다.
. 풀 및 볼륨 그룹에 대해 드라이브 보안 설정:
+
** 풀 또는 볼륨 그룹을 생성합니다(후보 테이블의 * Secure-Capable * 열에서 * Yes * 를 찾습니다).
** 새 볼륨을 생성할 때 풀 또는 볼륨 그룹을 선택합니다(풀 및 볼륨 그룹 후보 테이블에서 * 보안 가능 * 옆에 * 예 * 가 표시됨).






== 드라이브 보안 작동 방식

FDE 또는 FIPS 중 어떤 보안 가능 드라이브도 쓰기 중에 데이터를 암호화하고 읽기 중에 데이터를 해독합니다. 이 암호화 및 암호 해독은 성능 또는 사용자 워크플로에 영향을 주지 않습니다. 각 드라이브에는 드라이브에서 전송할 수 없는 고유한 암호화 키가 있습니다.

드라이브 보안 기능은 보안 기능이 있는 드라이브를 통해 추가 보호 계층을 제공합니다. 드라이브 보안을 위해 이러한 드라이브의 볼륨 그룹 또는 풀을 선택한 경우 드라이브는 데이터에 대한 액세스를 허용하기 전에 보안 키를 찾습니다. 드라이브의 기존 데이터에 영향을 주지 않고 언제든지 풀 및 볼륨 그룹에 대해 드라이브 보안을 설정할 수 있습니다. 그러나 드라이브의 모든 데이터를 지우지 않으면 드라이브 보안을 비활성화할 수 없습니다.



== 스토리지 어레이 레벨에서 드라이브 보안이 작동하는 방식

드라이브 보안 기능을 사용하면 스토리지 배열의 보안 지원 드라이브와 컨트롤러 간에 공유되는 보안 키를 만들 수 있습니다. 드라이브 전원을 껐다가 켤 때마다 보안 활성 드라이브는 컨트롤러가 보안 키를 적용할 때까지 보안 잠금 상태로 변경됩니다.

보안 사용 드라이브가 스토리지 어레이에서 제거되어 다른 스토리지 배열에 다시 설치된 경우 드라이브는 보안 잠금 상태가 됩니다. 재배치된 드라이브는 데이터에 다시 액세스하기 전에 보안 키를 찾습니다. 데이터 잠금을 해제하려면 소스 스토리지 어레이에서 보안 키를 적용합니다. 잠금 해제 프로세스가 완료되면 다시 찾은 드라이브가 대상 스토리지 배열에 이미 저장된 보안 키를 사용하며 가져온 보안 키 파일이 더 이상 필요하지 않습니다.

[NOTE]
====
내부 키 관리의 경우 실제 보안 키는 컨트롤러에 액세스할 수 없는 위치에 저장됩니다. 이 형식은 사람이 읽을 수 있는 형식도 아니며 사용자가 액세스할 수도 없습니다.

====


== 드라이브 보안이 볼륨 수준에서 작동하는 방식

보안 가능 드라이브에서 풀 또는 볼륨 그룹을 생성할 때 해당 풀 또는 볼륨 그룹에 대해 드라이브 보안을 설정할 수도 있습니다. Drive Security 옵션을 사용하면 드라이브 및 관련 볼륨 그룹과 풀의 보안이 __enabled_로 설정됩니다.

보안이 설정된 볼륨 그룹 및 풀을 생성하기 전에 다음 지침을 염두에 두십시오.

* 볼륨 그룹 및 풀은 전적으로 보안이 가능한 드라이브로 구성되어야 합니다. (FIPS 지원이 필요한 볼륨의 경우 FIPS 드라이브만 사용합니다. 볼륨 그룹 또는 풀에서 FIPS 및 FDE 드라이브를 혼합하면 모든 드라이브가 FDE 드라이브로 처리됩니다. 또한 FDE 드라이브는 All-FIPS 볼륨 그룹 또는 풀에서 스페어로 추가하거나 사용할 수 없습니다.)
* 볼륨 그룹 및 풀이 최적의 상태여야 합니다.

