---
permalink: sm-settings/how-alerts-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, alarm, alerts, 
summary: 알림은 스토리지 시스템에서 발생하는 중요한 이벤트를 관리자에게 알립니다. 알림은 이메일, SNMP 트랩 및 syslog를 통해 보낼 수 있습니다. 
---
= 알림의 작동 방식
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
알림은 스토리지 시스템에서 발생하는 중요한 이벤트를 관리자에게 알립니다. 알림은 이메일, SNMP 트랩 및 syslog를 통해 보낼 수 있습니다.

알림 프로세스는 다음과 같이 작동합니다.

. 관리자는 System Manager에서 다음 경고 방법 중 하나 이상을 구성합니다.
+
** * 이메일 * -- 메시지가 이메일 주소로 전송됩니다.
** SNMP * -- SNMP 트랩이 SNMP 서버로 전송됩니다.
** * Syslog * -- 메시지가 syslog 서버로 전송됩니다.


. 스토리지 배열의 이벤트 모니터에서 문제를 감지하면 해당 문제에 대한 정보를 이벤트 로그에 기록합니다(메뉴: 지원 [이벤트 로그]). 예를 들어, 배터리 오류, 최적화에서 오프라인으로 이동하는 구성 요소 또는 컨트롤러의 중복 오류와 같은 이벤트가 문제에 포함될 수 있습니다.
. 이벤트 모니터에서 이벤트가 "alertable"이라고 판단하면 구성된 경고 방법(e-메일, SNMP 및/또는 syslog)을 사용하여 알림을 보냅니다. 모든 중요 이벤트는 일부 경고 및 정보 이벤트와 함께 "alertable"으로 간주됩니다.




== 알림 구성

초기 설정 마법사(e-메일 알림만 해당) 또는 경고 페이지에서 경고를 구성할 수 있습니다. 현재 구성을 확인하려면 설정 [경고] 메뉴로 이동하십시오.

경고 타일에는 다음 중 하나에 해당하는 경고 구성이 표시됩니다.

* 구성되지 않았습니다.
* 구성됨. 하나 이상의 경고 방법이 설정되었습니다. 구성된 경고 방법을 확인하려면 커서를 바둑판식으로 가져갑니다.




== 경고 정보

알림에는 다음과 같은 유형의 정보가 포함될 수 있습니다.

* 스토리지 배열의 이름입니다.
* 이벤트 로그 엔트리와 관련된 이벤트 오류 유형입니다.
* 이벤트가 발생한 날짜 및 시간입니다.
* 이벤트에 대한 간략한 설명입니다.


[NOTE]
====
Syslog 알림은 RFC 5424 메시징 표준을 따릅니다.

====