---
permalink: sm-settings/nvme-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, nvme, 
summary: '일부 컨트롤러에는 패브릭을 통해 NVMe(비휘발성 메모리 익스프레스)를 구현하기 위한 포트가 포함되어 있습니다. NVMe를 사용하면 호스트와 스토리지 어레이 간에 고성능 통신이 가능합니다.' 
---
= NVMe 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
일부 컨트롤러에는 패브릭을 통해 NVMe(비휘발성 메모리 익스프레스)를 구현하기 위한 포트가 포함되어 있습니다. NVMe를 사용하면 호스트와 스토리지 어레이 간에 고성능 통신이 가능합니다.



== NVMe란 무엇입니까?

_NVM_은 "비휘발성 메모리"를 나타내며 다양한 유형의 저장 장치에 사용되는 영구 메모리입니다. _NVMe_(NVM Express)는 NVM 장치와의 고성능 다중 대기열 통신을 위해 특별히 설계된 표준 인터페이스 또는 프로토콜입니다.



== NVMe over Fabrics란?

_NVMe over Fabrics (NVMe-oF) _ 는 NVMe 메시지 기반 명령 및 데이터가 네트워크를 통해 호스트 컴퓨터와 스토리지 간에 전송되도록 하는 기술 사양입니다. Fabric을 사용하는 호스트에서 NVMe 스토리지 어레이(_subsystem_)에 액세스할 수 있습니다. NVMe 명령은 호스트 측과 하위 시스템 측 모두에서 전송 추상화 계층에서 활성화 및 캡슐화됩니다. 이를 통해 고성능 NVMe 인터페이스 엔드 투 엔드를 호스트에서 스토리지로 확장하고 명령 세트를 표준화하여 단순화합니다.

NVMe-oF 스토리지는 호스트에 로컬 블록 스토리지 디바이스로 표시됩니다. 다른 블록 스토리지 디바이스와 마찬가지로 볼륨(_namespace_)을 파일 시스템에 마운트할 수 있습니다. REST API, SMcli 또는 SANtricity System Manager를 사용하여 필요에 따라 스토리지를 프로비저닝할 수 있습니다.



== NVMe 적격 이름(NQN)이란 무엇입니까?

NVMe 정규화된 이름(NQN)은 원격 스토리지 타겟을 식별하는 데 사용됩니다. 스토리지 배열의 NVMe 정규화된 이름은 항상 서브시스템에 의해 할당되며 수정할 수 없습니다. 전체 어레이에 대해 하나의 NVMe 정규화된 이름만 있습니다. NVMe 적격 이름은 223자로 제한됩니다. iSCSI 정규화된 이름과 비교할 수 있습니다.



== 네임스페이스 및 네임스페이스 ID란 무엇입니까?

네임스페이스는 SCSI의 논리 유닛과 동일하며 어레이의 볼륨과 관련이 있습니다. NSCID(Namespace ID)는 SCSI의 LUN(Logical Unit Number)과 동일합니다. 네임스페이스 생성 시 NSID를 만들고 1에서 255 사이의 값으로 설정할 수 있습니다.



== NVMe 컨트롤러란 무엇입니까?

호스트 이니시에이터에서 스토리지 시스템의 타겟으로 연결되는 경로를 나타내는 SCSI I_T Nexus와 마찬가지로, 호스트 연결 프로세스 중에 생성된 NVMe 컨트롤러는 스토리지 어레이의 네임스페이스와 호스트 간의 액세스 경로를 제공합니다. 호스트의 NQN 및 호스트 포트 식별자는 NVMe 컨트롤러를 고유하게 식별합니다. NVMe 컨트롤러는 단일 호스트에만 연결될 수 있지만 여러 네임스페이스에 액세스할 수 있습니다.

SANtricity System Manager를 사용하여 호스트에 대한 네임스페이스 ID를 설정하고 네임스페이스에 액세스할 수 있는 호스트를 구성할 수 있습니다. 그런 다음 NVMe 컨트롤러가 생성되면 NVMe 컨트롤러에서 액세스할 수 있는 네임스페이스 ID 목록을 생성하여 허용 가능한 연결을 구성하는 데 사용합니다.
