---
permalink: sm-settings/obtain-a-feature-key-file.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, obtain, feature, key, file, 
summary: 스토리지 어레이에서 프리미엄 기능 또는 기능 팩을 활성화하려면 먼저 기능 키 파일을 구해야 합니다. 키는 하나의 스토리지 배열에만 연결됩니다. 
---
= SANtricity System Manager에서 기능 키 파일을 가져옵니다.
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 어레이에서 프리미엄 기능 또는 기능 팩을 활성화하려면 먼저 기능 키 파일을 구해야 합니다. 키는 하나의 스토리지 배열에만 연결됩니다.

.이 작업에 대해
이 작업에서는 기능에 필요한 정보를 수집한 다음 기능 키 파일에 대한 요청을 보내는 방법을 설명합니다. 필수 정보는 다음과 같습니다.

* 섀시 일련 번호입니다
* 기능 활성화 식별자
* 기능 활성화 코드


.단계
. System Manager에서 섀시 일련 번호를 찾아 기록합니다. 지원 센터 타일에 마우스를 올려 놓으면 이 일련 번호를 볼 수 있습니다.
. System Manager에서 Enable Identifier 기능을 찾습니다. 설정 [시스템] 메뉴로 이동한 다음 아래로 스크롤하여 * 추가 기능 * 으로 이동합니다. Feature Enable Identifier * 를 찾습니다. 기능 식별자 활성화 의 번호를 기록합니다.
. 기능 활성화를 위한 코드를 찾아 기록합니다. 기능 팩의 경우 이 코드는 변환을 수행하기 위한 적절한 지침에 나와 있습니다.
+
프리미엄 기능의 경우 지원 사이트에서 다음과 같이 활성화 코드에 액세스할 수 있습니다.

+
.. 에 로그인합니다 https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"^].
.. 사용 중인 제품의 * 소프트웨어 라이선스 * 로 이동합니다.
.. 스토리지 어레이 섀시의 일련 번호를 입력하고 * Go * 를 클릭합니다.
.. 라이센스 키 * 열에서 기능 활성화 코드를 찾습니다.
.. 원하는 기능에 대한 기능 활성화 코드를 기록합니다.


. 섀시 일련 번호, 활성화 식별자 및 기능 활성화를 위한 코드와 같은 정보를 사용하여 스토리지 공급업체에 이메일 또는 텍스트 문서를 보내 기능 키 파일을 요청합니다.
+
로 이동할 수도 있습니다 http://partnerspfk.netapp.com["NetApp 라이센스 활성화: 스토리지 어레이 프리미엄 기능 활성화"^] 및 필요한 정보를 입력하여 기능 팩 또는 기능 팩을 얻습니다. (이 사이트의 지침은 기능 팩이 아닌 프리미엄 기능에 대한 것입니다.)



.작업을 마친 후
기능 키 파일이 있는 경우 프리미엄 기능 또는 기능 팩을 활성화할 수 있습니다.
