---
permalink: sm-settings/overview-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, Alerts, 
summary: 이메일, SNMP 트랩 및 syslog 메시지를 통해 스토리지 배열 경고를 보내도록 System Manager를 구성할 수 있습니다. 
---
= 경고 개요
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이메일, SNMP 트랩 및 syslog 메시지를 통해 스토리지 어레이에 대한 경고를 보내도록 SANtricity 시스템 관리자를 구성할 수 있습니다.



== 알림이란 무엇입니까?

_Alerts_ 스토리지 시스템에서 발생하는 중요한 이벤트를 관리자에게 알립니다. 이벤트에는 배터리 장애, 최적화에서 오프라인으로 이동하는 구성 요소 또는 컨트롤러의 중복 오류와 같은 문제가 포함될 수 있습니다. 모든 중요 이벤트는 일부 경고 및 정보 이벤트와 함께 "alertable"으로 간주됩니다.

자세한 내용:

* link:how-alerts-work.html["알림의 작동 방식"]
* link:alerts-terminology.html["경고 용어"]




== 알림을 구성하려면 어떻게 합니까?

경고를 하나 이상의 e-메일 주소로 보내거나, SNMP 서버에 대한 SNMP 트랩으로 보내거나, syslog 서버에 메시지로 보내도록 구성할 수 있습니다. 경고 구성은 설정 [경고] 메뉴에서 사용할 수 있습니다.

자세한 내용:

* link:configure-mail-server-and-recipients-for-alerts.html["메일 서버 및 받는 사람이 알림을 받도록 구성합니다"]
* link:configure-syslog-server-for-alerts.html["경고에 대한 syslog 서버를 구성합니다"]
* link:configure-snmp-alerts.html["SNMP 경고를 구성합니다"]




== 관련 정보

경고와 관련된 개념에 대해 자세히 알아보기:

* link:../sm-support/overview-event-log.html["이벤트 로그 개요"]
* link:why-are-timestamps-inconsistent-between-the-array-and-alerts.html["시간 스탬프가 일치하지 않습니다"]

