---
permalink: sm-settings/overview-drive-security.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, system, security, key, management, 
summary: 보안 키 관리는 시스템 페이지에서 사용할 수 있습니다. 
---
= 드라이브 보안 개요
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보안 키 관리 페이지에서 드라이브 보안 및 키 관리를 구성할 수 있습니다.



== 드라이브 보안이란 무엇입니까?

_Drive Security_ 는 스토리지 어레이에서 제거할 때 보안이 설정된 드라이브의 데이터에 대한 무단 액세스를 방지하는 기능입니다. 이러한 드라이브는 FDE(전체 디스크 암호화) 드라이브 또는 FIPS(Federal Information Processing Standard) 드라이브일 수 있습니다. FDE 또는 FIPS 드라이브를 어레이에서 물리적으로 제거할 경우, 해당 드라이브가 다른 어레이에 설치될 때까지 작동할 수 없으며, 이때 올바른 보안 키가 제공될 때까지 드라이브는 보안 잠금 상태가 됩니다. a_security key_는 이러한 유형의 드라이브와 스토리지 배열의 컨트롤러 간에 공유되는 문자의 문자열입니다.

자세한 내용:

* link:how-the-drive-security-feature-works.html["드라이브 보안 기능의 작동 방식"]
* link:how-security-key-management-works.html["보안 키 관리의 작동 방식"]
* link:drive-security-terminology.html["드라이브 보안 용어"]




== 키 관리는 어떻게 구성합니까?

드라이브 보안을 구현하려면 어레이에 FDE 드라이브 또는 FIPS 드라이브가 설치되어 있어야 합니다. 이러한 드라이브의 키 관리를 구성하려면 메뉴 설정 [시스템 > 보안 키 관리]로 이동하여 컨트롤러의 영구 메모리에서 내부 키를 만들거나 키 관리 서버에서 외부 키를 만들 수 있습니다. 마지막으로 볼륨 설정에서 "보안 가능"을 선택하여 풀 및 볼륨 그룹에 대해 드라이브 보안을 설정합니다.

자세한 내용:

* link:create-internal-security-key.html["내부 보안 키를 생성합니다"]
* link:create-external-security-key.html["외부 보안 키를 만듭니다"]
* link:../sm-storage/create-pool-manually.html["풀을 수동으로 생성합니다"]
* link:../sm-storage/create-volume-group.html["볼륨 그룹을 생성합니다"]




== 드라이브의 잠금을 해제하려면 어떻게 해야 합니까?

키 관리를 구성한 다음 나중에 보안 지원 드라이브를 한 스토리지 어레이에서 다른 스토리지 어레이로 이동하는 경우, 드라이브의 암호화된 데이터에 액세스하려면 보안 키를 새 스토리지 배열에 다시 할당해야 합니다.

자세한 내용:

* link:unlock-drives-using-an-internal-security-key.html["내부 키 관리 사용 시 드라이브 잠금을 해제합니다"]
* link:unlock-drives-using-an-external-security-key.html["외부 키 관리 사용 시 드라이브 잠금을 해제합니다"]




== 관련 정보

키 관리와 관련된 작업에 대해 자세히 알아보십시오.

* link:use-ca-signed-certificates-for-authentication-with-a-key-management-server.html["키 관리 서버에서 인증에 CA 서명 인증서를 사용합니다"]
* link:back-up-security-key.html["보안 키를 백업합니다"]

