---
permalink: sm-settings/overview-certificates.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, certificates, 
summary: 'System Manager를 사용하여 CSR(인증서 서명 요청)을 생성하고 인증서를 가져오고 기존 인증서를 관리할 수 있습니다.' 
---
= SANtricity System Manager의 인증서에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity 시스템 관리자를 사용하여 CSR(인증서 서명 요청)을 만들고, 인증서를 가져오고, 기존 인증서를 관리할 수 있습니다.



== 인증서란 무엇입니까?

_Certificates_는 인터넷 보안 통신을 위해 웹 사이트 및 서버와 같은 온라인 엔터티를 식별하는 디지털 파일입니다. 인증서 유형에는 두 가지가 있습니다. CA(인증 기관)에서 _signed certificate_를 검증하고, 타사 대신 엔터티의 소유자가 _self-signed certificate_를 확인합니다.

자세한 내용:

* link:how-certificates-work-sam.html["인증서 작동 방식"]
* link:certificate-terminology.html["인증서 용어"]




== 서명된 인증서를 구성하려면 어떻게 합니까?

System Manager 또는 외부에서 개인 및 공용 키 쌍을 사용하여 서명 요청을 생성할 수 있습니다. 인증서 파일을 생성하기 위해 서명 요청이 CA로 전송됩니다. CA가 인증서 파일을 반환하면 System Manager를 사용하여 인증서 파일을 가져옵니다.

자세한 내용:

* link:use-ca-signed-certificates-for-controllers.html["컨트롤러에 CA 서명 인증서를 사용합니다"]
* link:use-ca-signed-certificates-for-authentication-with-a-key-management-server.html["키 관리 서버에서 인증에 CA 서명 인증서를 사용합니다"]




== 관련 정보

인증서 관련 작업에 대해 자세히 알아보기:

* link:view-imported-certificates.html["가져온 인증서 정보를 봅니다"]
* link:enable-certificate-revocation-checking.html["인증서 해지 확인을 사용합니다"]

