---
permalink: sm-settings/save-storage-array-configuration.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, save, storage array, configuration, 
summary: 스토리지 배열의 구성 정보를 스크립트 파일에 저장하여 동일한 구성으로 추가 스토리지 배열을 설정하는 시간을 절약할 수 있습니다. 
---
= 스토리지 배열 구성을 저장합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 배열의 구성 정보를 스크립트 파일에 저장하여 동일한 구성으로 추가 스토리지 배열을 설정하는 시간을 절약할 수 있습니다.

스토리지 시스템에서 논리적 구성 설정을 변경하는 작업을 수행해서는 안 됩니다. 이러한 작업의 예로는 볼륨 생성 또는 삭제, 컨트롤러 펌웨어 다운로드, 핫 스페어 드라이브 할당 또는 수정, 볼륨 그룹에 용량(드라이브) 추가 등이 있습니다.

스토리지 배열 구성을 저장하면 스토리지 배열에 대한 스토리지 배열 설정, 볼륨 구성, 호스트 구성 또는 호스트-볼륨 할당을 포함하는 CLI(Command Line Interface) 스크립트가 생성됩니다. 생성된 이 CLI 스크립트를 사용하여 정확히 동일한 하드웨어 구성을 가진 다른 스토리지 어레이로 구성을 복제할 수 있습니다.

그러나 재해 복구에 이 생성된 CLI 스크립트를 사용해서는 안 됩니다. 대신 시스템 복원을 수행하려면 수동으로 생성한 구성 데이터베이스 백업 파일을 사용하거나 기술 지원 부서에 문의하여 최신 자동 지원 데이터에서 이 데이터를 얻으십시오.

이 작업은 _ 이(가) 다음 설정을 저장하지 않습니다.

* 배터리 수명
* 컨트롤러 시간입니다
* NVSRAM(Nonvolatile Static Random Access Memory) 설정입니다
* 모든 프리미엄 기능
* 스토리지 배열 암호입니다
* 하드웨어 구성 요소의 작동 상태 및 상태입니다
* 볼륨 그룹의 작동 상태(최적 상태 제외) 및 상태입니다
* 미러링 및 볼륨 복사본과 같은 복사 서비스를 이용할 수 있습니다


[CAUTION]
====
* 응용 프로그램 오류 위험 * -- 스토리지 배열에 논리 구성 설정을 변경할 작업이 진행 중인 경우에는 이 옵션을 사용하지 마십시오. 이러한 작업의 예로는 볼륨 생성 또는 삭제, 컨트롤러 펌웨어 다운로드, 핫 스페어 드라이브 할당 또는 수정, 볼륨 그룹에 용량(드라이브) 추가 등이 있습니다.

====
.단계
. 설정 [시스템] 메뉴를 선택합니다.
. 스토리지 배열 구성 저장 * 을 선택합니다.
. 저장할 구성 항목을 선택합니다.
+
** 스토리지 배열 설정입니다
** 볼륨 구성
** 호스트 구성
** 호스트-볼륨 할당


+
[NOTE]
====
Host-to-volume Assignments * 항목을 선택하면 * Volume configuration * 항목과 * Host configuration * 항목도 기본적으로 선택됩니다. "볼륨 구성"과 "호스트 구성"을 저장하지 않으면 "호스트 대 볼륨 할당"을 저장할 수 없습니다.

====
. 저장 * 을 클릭합니다.
+
이 파일은 브라우저의 다운로드 폴더에 'storage-array-configuration.cfg'라는 이름으로 저장됩니다.



저장된 스토리지 배열 구성을 다른 스토리지 배열에 로드하려면 "-f" 옵션과 함께 SANtricity 명령줄 인터페이스(SMcli)를 사용하여 ".cfg" 파일을 적용합니다.

[NOTE]
====
Unified Manager 인터페이스를 사용하여 스토리지 어레이 구성을 다른 스토리지 어레이에 로드할 수도 있습니다(메뉴 선택: 관리 [설정 가져오기]).

====