---
permalink: sm-settings/unlock-drives-using-an-external-security-key.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, unlock, drives, external, key, management, 
summary: 외부 키 관리를 구성한 다음 나중에 보안 지원 드라이브를 한 스토리지 어레이에서 다른 스토리지 어레이로 이동하는 경우, 드라이브의 암호화된 데이터에 액세스하려면 보안 키를 새 스토리지 배열에 다시 할당해야 합니다. 
---
= 외부 키 관리 사용 시 드라이브 잠금을 해제합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
외부 키 관리를 구성한 다음 나중에 보안 지원 드라이브를 한 스토리지 어레이에서 다른 스토리지 어레이로 이동하는 경우, 드라이브의 암호화된 데이터에 액세스하려면 보안 키를 새 스토리지 배열에 다시 할당해야 합니다.

.시작하기 전에
* 소스 스토리지(드라이브를 제거할 스토리지)에서 볼륨 그룹을 내보내고 드라이브를 제거했습니다. 대상 어레이에서 드라이브를 다시 설치했습니다.
+

NOTE: 내보내기/가져오기 기능은 System Manager 사용자 인터페이스에서 지원되지 않습니다. 볼륨 그룹을 다른 스토리지 어레이로 내보내기/가져오려면 CLI(Command Line Interface)를 사용해야 합니다.

+
볼륨 그룹 마이그레이션에 대한 자세한 지침은 에 나와 있습니다 https://kb.netapp.com/["NetApp 기술 자료"^]. System Manager 또는 기존 시스템에서 관리하는 최신 어레이에 대한 적절한 지침을 따라야 합니다.

* 드라이브 보안 기능을 활성화해야 합니다. 그렇지 않으면 이 작업 중에 보안 키를 만들 수 없음 대화 상자가 열립니다. 필요한 경우 스토리지 공급업체에 드라이브 보안 기능 활성화에 대한 지침을 문의하십시오.
* 키 관리 서버의 IP 주소와 포트 번호를 알고 있어야 합니다.
* 스토리지 배열 컨트롤러의 서명된 클라이언트 인증서 파일이 있고, System Manager에 액세스하는 호스트에 해당 파일을 복사했습니다. 클라이언트 인증서는 스토리지 어레이 컨트롤러의 유효성을 검사하므로 키 관리 서버가 KMIP(Key Management Interoperability Protocol) 요청을 신뢰할 수 있습니다.
* 키 관리 서버에서 인증서 파일을 검색한 다음 System Manager에 액세스할 호스트에 해당 파일을 복사해야 합니다. 키 관리 서버 인증서는 키 관리 서버의 유효성을 검사하므로 스토리지 배열이 해당 IP 주소를 신뢰할 수 있습니다. 키 관리 서버에 루트, 중간 또는 서버 인증서를 사용할 수 있습니다.


[NOTE]
====
서버 인증서에 대한 자세한 내용은 키 관리 서버 설명서를 참조하십시오.

====
.이 작업에 대해
외부 키 관리를 사용하는 경우 보안 키는 보안 키를 안전하게 보호하도록 설계된 서버에 외부에 저장됩니다. 보안 키는 읽기/쓰기 액세스를 위해 컨트롤러와 드라이브에서 공유하는 일련의 문자입니다. 드라이브가 어레이에서 물리적으로 제거되어 다른 드라이브에 설치된 경우 올바른 보안 키를 제공할 때까지 드라이브가 작동할 수 없습니다.

[NOTE]
====
컨트롤러의 영구 메모리에서 내부 키를 만들거나 키 관리 서버에서 외부 키를 만들 수 있습니다. 이 항목에서는 _EXTERNAL_KEY 관리 사용 시 데이터 잠금 해제를 설명합니다. internal_key 관리를 사용한 경우 를 참조하십시오 link:unlock-drives-using-an-internal-security-key.html["내부 키 관리 사용 시 드라이브 잠금을 해제합니다"]. 컨트롤러 업그레이드를 수행하고 모든 컨트롤러를 최신 하드웨어로 교체하려는 경우, 의 E-Series 및 SANtricity 설명서 센터에 설명된 대로 여러 단계를 수행해야 합니다 link:https://docs.netapp.com/us-en/e-series/upgrade-controllers/upgrade-unlock-drives-task.html["드라이브 잠금을 해제합니다"].

====
다른 어레이에서 보안 지원 드라이브를 재설치하면 해당 어레이에서 드라이브를 검색하고 "주의 필요" 상태와 함께 "보안 키 필요" 상태를 표시합니다. 드라이브 데이터의 잠금을 해제하려면 보안 키 파일을 가져오고 키의 암호를 입력합니다. (이 암호는 스토리지 배열의 관리자 암호와 같지 않습니다.) 이 프로세스 중에 외부 키 관리 서버를 사용하도록 스토리지 배열을 구성한 다음 보안 키를 액세스할 수 있습니다. 보안 키를 연결 및 검색하려면 스토리지 배열에 대한 서버의 연락처 정보를 제공해야 합니다.

다른 보안 지원 드라이브가 새 스토리지 배열에 설치되어 있는 경우 가져오는 것과 다른 보안 키를 사용할 수 있습니다. 가져오기 프로세스 중에 이전 보안 키는 설치 중인 드라이브의 데이터 잠금을 해제하는 데만 사용됩니다. 잠금 해제 프로세스가 성공하면 새로 설치된 드라이브가 대상 스토리지 배열의 보안 키에 다시 입력됩니다.

.단계
. 설정 [시스템] 메뉴를 선택합니다.
. 보안 키 관리 * 에서 * 외부 키 생성 * 을 선택합니다.
. 필수 연결 정보 및 인증서를 사용하여 마법사를 완료합니다.
. 외부 키 관리 서버에 액세스하려면 * 통신 테스트 * 를 클릭합니다.
. 보안 드라이브 잠금 해제 * 를 선택합니다.
+
보안 드라이브 잠금 해제 대화 상자가 열립니다. 보안 키가 필요한 모든 드라이브가 표에 나와 있습니다.

. * 선택 사항: * 드라이브 번호 위로 마우스를 가져가면 드라이브 위치(쉘프 번호 및 베이 번호)가 표시됩니다.
. 찾아보기 * 를 클릭한 다음 잠금을 해제할 드라이브에 해당하는 보안 키 파일을 선택합니다.
+
선택한 키 파일이 대화 상자에 나타납니다.

. 이 키 파일과 관련된 암호를 입력합니다.
+
입력한 문자는 마스크됩니다.

. 잠금 해제 * 를 클릭합니다.
+
잠금 해제 작업이 성공하면 대화 상자에 "연결된 보안 드라이브가 잠금 해제되었습니다."라는 메시지가 표시됩니다.



.결과
모든 드라이브가 잠겼다가 잠금 해제되면 스토리지 배열의 각 컨트롤러가 재부팅됩니다. 그러나 대상 스토리지 배열에 이미 일부 잠금 해제된 드라이브가 있는 경우 컨트롤러는 재부팅되지 않습니다.

.작업을 마친 후
이제 대상 배열(새로 설치된 드라이브가 있는 배열)에서 볼륨 그룹을 가져올 수 있습니다.


NOTE: 내보내기/가져오기 기능은 System Manager 사용자 인터페이스에서 지원되지 않습니다. 볼륨 그룹을 다른 스토리지 어레이로 내보내기/가져오려면 CLI(Command Line Interface)를 사용해야 합니다.

볼륨 그룹 마이그레이션에 대한 자세한 지침은 에 나와 있습니다 https://kb.netapp.com/["NetApp 기술 자료"^].
