---
permalink: sm-settings/use-ca-signed-certificates-for-controllers.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ca-signed, certificates, controllers, 
summary: 컨트롤러와 System Manager 액세스에 사용되는 브라우저 간에 보안 통신을 위해 CA 서명 인증서를 얻을 수 있습니다. 
---
= 컨트롤러에 CA 서명 인증서를 사용합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러와 System Manager 액세스에 사용되는 브라우저 간에 보안 통신을 위해 CA 서명 인증서를 얻을 수 있습니다.

.시작하기 전에
* 보안 관리자 권한이 포함된 사용자 프로필로 로그인해야 합니다. 그렇지 않으면 인증서 기능이 나타나지 않습니다.
* 각 컨트롤러의 IP 주소 또는 DNS 이름을 알아야 합니다.


.이 작업에 대해
CA 서명 인증서를 사용하는 것은 3단계 절차입니다.



== 1단계: CSR을 컨트롤러에 대해 완료합니다

먼저 스토리지 배열의 각 컨트롤러에 대해 CSR(인증서 서명 요청) 파일을 생성해야 합니다.

.이 작업에 대해
이 작업은 System Manager에서 CSR 파일을 생성하는 방법을 설명합니다. CSR은 조직에 대한 정보와 컨트롤러의 IP 주소 또는 DNS 이름을 제공합니다. 이 작업 중에 스토리지 어레이에 컨트롤러가 1개 있고 CSR 파일이 2개 있는 경우 CSR 파일 1개가 생성됩니다.

[NOTE]
====
또는 OpenSSL과 같은 도구를 사용하여 CSR 파일을 생성하고 로 건너뛸 수 있습니다 <<2단계: CSR 파일을 제출합니다>>.

====
.단계
. 설정 [인증서] 메뉴를 선택합니다.
. Array Management(어레이 관리) 탭에서 * Complete CSR * 을 선택합니다.
+
[NOTE]
====
두 번째 컨트롤러에 대해 자체 서명된 인증서를 수락하라는 대화 상자가 표시되면 * 자체 서명된 인증서 수락 * 을 클릭하여 계속 진행합니다.

====
. 다음 정보를 입력하고 * 다음 * 을 클릭합니다.
+
** * 조직 * -- 회사 또는 조직의 전체 법적 이름. Inc. 또는 Corp.와 같은 접미사를 포함합니다
** * 조직 단위(선택 사항) * -- 인증서를 처리하는 조직의 사업부입니다.
** * 시/군/구 * -- 스토리지 배열 또는 비즈니스가 위치한 시/군/구.
** * 주/지역(선택 사항) * -- 스토리지 배열 또는 비즈니스가 위치한 주 또는 지역입니다.
** * 국가 ISO 코드 * -- 미국 등 해당 국가의 2자리 ISO(International Organization for Standardization) 코드입니다.


+
[CAUTION]
====
일부 필드는 컨트롤러의 IP 주소와 같은 적절한 정보로 미리 채워질 수 있습니다. 값이 올바르지 않다고 확신하지 않는 한 미리 채워진 값을 변경하지 마십시오. 예를 들어 CSR을 아직 완료하지 않은 경우 컨트롤러 IP 주소는 ""localhost""로 설정됩니다. 이 경우 "localhost"를 컨트롤러의 DNS 이름 또는 IP 주소로 변경해야 합니다.

====
. 스토리지 어레이에서 컨트롤러 A에 대한 다음 정보를 확인하거나 입력합니다.
+
** * Controller a common name * -- 컨트롤러 A의 IP 주소 또는 DNS 이름이 기본적으로 표시됩니다. 이 주소가 올바른지 확인합니다. 입력한 주소와 정확하게 일치해야 브라우저에서 System Manager에 액세스할 수 있습니다. DNS 이름은 와일드카드로 시작할 수 없습니다.
** * 컨트롤러 대체 IP 주소 * -- 공통 이름이 IP 주소인 경우 컨트롤러 A에 대한 추가 IP 주소 또는 별칭을 선택적으로 입력할 수 있습니다 여러 항목의 경우 쉼표로 구분된 형식을 사용합니다.
** * 컨트롤러 A 대체 DNS 이름 * -- 공통 이름이 DNS 이름이면 컨트롤러 A의 추가 DNS 이름을 입력합니다 여러 항목의 경우 쉼표로 구분된 형식을 사용합니다. 대체 DNS 이름이 없지만 첫 번째 필드에 DNS 이름을 입력한 경우 여기에 해당 이름을 복사합니다. DNS 이름은 와일드카드로 시작할 수 없습니다. 스토리지 배열에 컨트롤러가 하나만 있는 경우 * Finish * (마침 *) 버튼을 사용할 수 있습니다.
+
스토리지 배열에 컨트롤러가 두 개 있는 경우 * Next * (다음 *) 버튼을 사용할 수 있습니다.



+
[NOTE]
====
CSR 요청을 처음 생성할 때 * 이 단계 건너뛰기 * 링크를 클릭하지 마십시오. 이 링크는 오류 복구 상황에서 제공됩니다. 드문 경우지만 한 컨트롤러에서 CSR 요청이 실패할 수 있지만 다른 컨트롤러에서는 그렇지 않습니다. 이 링크를 사용하면 컨트롤러 A에서 CSR 요청을 생성하는 단계를 건너뛸 수 있습니다(이미 정의된 경우). 컨트롤러 B에서 CSR 요청을 다시 생성하기 위한 다음 단계를 계속 진행할 수 있습니다

====
. 하나의 컨트롤러만 있는 경우 * 마침 * 을 클릭합니다. 두 개의 컨트롤러가 있는 경우 * 다음 * 을 클릭하여 컨트롤러 B에 대한 정보(위와 동일)를 입력한 다음 * 마침 * 을 클릭합니다.
+
단일 컨트롤러의 경우 하나의 CSR 파일이 로컬 시스템에 다운로드됩니다. 이중 컨트롤러의 경우 두 개의 CSR 파일이 다운로드됩니다. 다운로드의 폴더 위치는 브라우저에 따라 다릅니다.

. 로 이동합니다 <<2단계: CSR 파일을 제출합니다>>.




== 2단계: CSR 파일을 제출합니다

CSR(인증서 서명 요청) 파일을 생성한 후 CA(인증 기관)에 파일을 보냅니다. E-Series 시스템에는 PEM, .CRT, .CER 또는 .key 파일 형식이 포함된 서명된 인증서에 대한 PEM 형식(Base64 ASCII 인코딩)이 필요합니다.

.단계
. 다운로드한 CSR 파일을 찾습니다.
. CSR 파일을 CA(예: VeriSign 또는 DigiCert)에 제출하고 서명된 인증서를 PEM 형식으로 요청합니다.
+
[CAUTION]
====
* CSR 파일을 CA에 제출한 후 다른 CSR 파일을 다시 생성하지 마십시오. * CSR을 생성할 때마다 시스템에서 개인 및 공개 키 쌍을 생성합니다. 공개 키는 CSR의 일부이며 개인 키는 시스템의 키 저장소에 보관됩니다. 서명된 인증서를 받아서 가져오면 시스템에서 개인 키와 공개 키가 모두 원래 쌍이 되도록 합니다. 키가 일치하지 않으면 서명된 인증서가 작동하지 않으므로 CA에서 새 인증서를 요청해야 합니다.

====
. CA가 서명된 인증서를 반환하면 로 이동합니다 <<3단계: 컨트롤러의 서명된 인증서 가져오기>>.




== 3단계: 컨트롤러의 서명된 인증서 가져오기

CA(인증 기관)에서 서명된 인증서를 받은 후 컨트롤러의 파일을 가져옵니다.

.시작하기 전에
* CA가 서명된 인증서 파일을 반환했습니다. 이러한 파일에는 루트 인증서, 하나 이상의 중간 인증서 및 서버 인증서가 포함됩니다.
* CA가 체인 인증서 파일(예: .p7b 파일)을 제공한 경우, 연결된 파일의 압축을 개별 파일(루트 인증서, 하나 이상의 중간 인증서, 컨트롤러를 식별하는 서버 인증서)에 풀어야 합니다. Windows 'certmgr' 유틸리티를 사용하여 파일의 압축을 풀 수 있습니다(마우스 오른쪽 버튼을 클릭하고 All Tasks[내보내기] 메뉴를 선택). base-64 인코딩이 권장됩니다. 내보내기가 완료되면 체인의 각 인증서 파일에 대해 CER 파일이 표시됩니다.
* 인증서 파일을 System Manager에 액세스하는 호스트 시스템에 복사했습니다.


.단계
. 메뉴 선택: 설정 [인증서]
. Array Management 탭에서 * Import * 를 선택합니다.
+
인증서 파일을 가져올 수 있는 대화 상자가 열립니다.

. 찾아보기 * 단추를 클릭하여 먼저 루트 및 중간 인증서 파일을 선택한 다음 컨트롤러의 각 서버 인증서를 선택합니다. 루트 파일과 중간 파일은 두 컨트롤러 모두에 대해 동일합니다. 서버 인증서만 각 컨트롤러에 대해 고유합니다. 외부 도구에서 CSR을 생성한 경우 CSR과 함께 생성된 개인 키 파일도 가져와야 합니다.
+
파일 이름이 대화 상자에 표시됩니다.

. 가져오기 * 를 클릭합니다.
+
파일이 업로드되고 검증됩니다.



.결과
세션이 자동으로 종료됩니다. 인증서를 적용하려면 다시 로그인해야 합니다. 다시 로그인하면 새 CA 서명 인증서가 세션에 사용됩니다.
