---
permalink: sm-settings/use-ca-signed-certificates-for-authentication-with-a-key-management-server.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ca-signed, certificates, authentication, key, management, server, 
summary: 키 관리 서버와 스토리지 어레이 컨트롤러 간의 보안 통신을 위해 적절한 인증서 세트를 구성해야 합니다. 
---
= 키 관리 서버에서 인증에 CA 서명 인증서를 사용합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
키 관리 서버와 스토리지 어레이 컨트롤러 간의 보안 통신을 위해 적절한 인증서 세트를 구성해야 합니다.

보안 관리자 권한이 포함된 사용자 프로필로 로그인해야 합니다. 그렇지 않으면 인증서 기능이 나타나지 않습니다.

컨트롤러와 키 관리 서버 간의 인증은 2단계 절차입니다.



== 1단계: 키 관리 서버를 사용하여 인증을 위해 CSR을 작성하여 제출합니다

먼저 CSR(인증서 서명 요청) 파일을 생성한 다음 CSR을 사용하여 키 관리 서버에서 신뢰할 수 있는 CA(인증 기관)로부터 서명된 클라이언트 인증서를 요청해야 합니다. 다운로드한 CSR 파일을 사용하여 키 관리 서버에서 클라이언트 인증서를 생성하고 다운로드할 수도 있습니다. 클라이언트 인증서는 스토리지 어레이 컨트롤러의 유효성을 검사하므로 키 관리 서버가 KMIP(Key Management Interoperability Protocol) 요청을 신뢰할 수 있습니다.

.단계
. 설정 [인증서] 메뉴를 선택합니다.
. 키 관리 탭에서 * CSR 완료 * 를 선택합니다.
. 다음 정보를 입력합니다.
+
** * 공통 이름 * -- 인증서 파일에 표시될 스토리지 배열 이름과 같이 이 CSR을 식별하는 이름입니다.
** * 조직 * -- 회사 또는 조직의 전체 법적 이름. Inc. 또는 Corp.와 같은 접미사를 포함합니다
** * 조직 단위(선택 사항) * -- 인증서를 처리하는 조직의 사업부입니다.
** * 시/군/구 * -- 조직이 위치한 시/군/구.
** * 시/도(선택 사항) * -- 조직이 위치한 시/도 또는 지역입니다.
** * 국가 ISO 코드 * -- 귀하의 조직이 위치한 미국과 같은 두 자리 ISO(국제 표준화 기구) 코드입니다.


. 다운로드 * 를 클릭합니다.
+
CSR 파일이 로컬 시스템에 저장됩니다.

. 키 관리 서버에서 신뢰할 수 있는 CA로부터 서명된 클라이언트 인증서를 요청합니다.
. 클라이언트 인증서가 있는 경우 로 이동합니다  2: Import certificates for the key management server.




== 2단계: 키 관리 서버의 인증서를 가져옵니다

다음 단계에서는 스토리지 어레이와 키 관리 서버 간에 인증을 위한 인증서를 가져옵니다. 인증서 유형에는 두 가지가 있습니다. 클라이언트 인증서는 스토리지 시스템의 컨트롤러를 검증하는 반면 키 관리 서버 인증서는 서버를 검증합니다. 컨트롤러의 클라이언트 인증서 파일과 키 관리 서버의 서버 인증서 파일을 모두 로드해야 합니다.

.시작하기 전에
* 서명된 클라이언트 인증서 파일이 있습니다( 참조)  1: Complete and submit CSR for authentication with a key management server), 그리고 System Manager에 액세스하는 호스트에 해당 파일을 복사했습니다. 클라이언트 인증서는 스토리지 어레이 컨트롤러의 유효성을 검사하므로 키 관리 서버가 KMIP(Key Management Interoperability Protocol) 요청을 신뢰할 수 있습니다.
* 키 관리 서버에서 인증서 파일을 검색한 다음 System Manager에 액세스할 호스트에 해당 파일을 복사해야 합니다. 키 관리 서버 인증서는 키 관리 서버의 유효성을 검사하므로 스토리지 배열이 해당 IP 주소를 신뢰할 수 있습니다. 키 관리 서버에 루트, 중간 또는 서버 인증서를 사용할 수 있습니다.
+
[NOTE]
====
서버 인증서에 대한 자세한 내용은 키 관리 서버 설명서를 참조하십시오.

====


.단계
. 설정 [인증서] 메뉴를 선택합니다.
. 키 관리 탭에서 * 가져오기 * 를 선택합니다.
+
인증서 파일을 가져올 수 있는 대화 상자가 열립니다.

. Select client certificate * 옆에 있는 * Browse * 버튼을 클릭하여 스토리지 배열 컨트롤러의 클라이언트 인증서 파일을 선택합니다.
+
대화 상자에 파일 이름이 표시됩니다.

. 키 관리 서버의 서버 인증서 선택 * 옆에 있는 * 찾아보기 * 버튼을 클릭하여 키 관리 서버의 서버 인증서 파일을 선택합니다. 키 관리 서버에 대한 루트, 중간 또는 서버 인증서를 선택할 수 있습니다.
+
대화 상자에 파일 이름이 표시됩니다.

. 가져오기 * 를 클릭합니다.
+
파일이 업로드되고 검증됩니다.


