---
permalink: sm-settings/view-iscsi-statistics-packages.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, iscsi, statistics, packages, 
summary: 스토리지 배열에 대한 iSCSI 연결에 대한 데이터를 볼 수 있습니다. 
---
= SANtricity System Manager에서 iSCSI 통계 패키지 보기
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 배열에 대한 iSCSI 연결에 대한 데이터를 볼 수 있습니다.

.이 작업에 대해
System Manager는 이러한 유형의 iSCSI 통계를 표시합니다. 모든 통계는 읽기 전용이며 설정할 수 없습니다.

* * 이더넷 MAC 통계 * -- MAC(Media Access Control)에 대한 통계를 제공합니다. 또한 MAC는 실제 주소 또는 MAC 주소라는 주소 지정 메커니즘을 제공합니다. MAC 주소는 각 네트워크 어댑터에 할당된 고유한 주소입니다. MAC 주소는 하위 네트워크 내의 대상으로 데이터 패킷을 전송하는 데 도움이 됩니다.
* * 이더넷 TCP/IP 통계 * -- TCP(Transmission Control Protocol) 및 IP(Internet Protocol)인 TCP/IP에 대한 통계를 제공합니다. TCP를 사용하면 네트워크로 연결된 호스트의 응용 프로그램이 서로 연결을 만들어 데이터를 패킷으로 교환할 수 있습니다. IP는 패킷 교환 방식의 네트워크를 통해 데이터를 전달하는 데이터 지향 프로토콜입니다. IPv4 통계 및 IPv6 통계는 별도로 표시됩니다.
* * 로컬 대상/초기자(프로토콜) 통계 * -- iSCSI 대상에 대한 통계를 표시합니다. iSCSI 타겟은 해당 스토리지 미디어에 대한 블록 수준 액세스를 제공하고 비동기 미러링 작업에서 이니시에이터로 사용될 때 스토리지 배열에 대한 iSCSI 통계를 표시합니다.
* * DCBX 작업 상태 통계 * -- 다양한 DCBX(Data Center Bridging Exchange) 기능의 작동 상태를 표시합니다.
* * LLDP TLV statistics * -- LLDP(Link Layer Discovery Protocol) TLV(Type Length Value) 통계를 표시합니다.
* * DCBX TLV 통계 * -- DCB(데이터 센터 브리징) 환경에서 스토리지 배열 호스트 포트를 식별하는 정보를 표시합니다. 이 정보는 식별 및 기능 목적으로 네트워크 피어와 공유됩니다.


각 통계를 원시 통계 또는 기준 통계로 볼 수 있습니다. 원시 통계는 컨트롤러가 시작된 이후 수집된 모든 통계입니다. 기준 통계는 기준 시간을 설정한 후 수집된 시점 통계입니다.

.단계
. 설정 [시스템] 메뉴를 선택합니다.
. iSCSI 통계 패키지 보기 * 를 선택합니다.
. 탭을 클릭하여 다양한 통계 집합을 봅니다.
. * 선택 사항: * 기준선을 설정하려면 * 새 기준선 설정 * 을 클릭합니다.
+
기준을 설정하면 통계 수집에 대한 새로운 시작 지점이 설정됩니다. 모든 iSCSI 통계에는 동일한 기준이 사용됩니다.



다양한 통계 유형에 대한 자세한 내용은 다음 섹션을 참조하십시오.



== MAC 전송 및 MAC 수신 통계

이더넷 MAC 통계를 선택하면 수신 및 전송 통계가 모두 나타납니다. 각 통계를 원시 통계 또는 기준 통계로 볼 수 있습니다.

.MAC 전송 통계:
[%collapsible]
====
[cols="25h,~"]
|===
| 통계 | 정의 


 a| 
F
 a| 
프레임 수



 a| 
B
 a| 
바이트 수입니다



 a| 
메인프레임
 a| 
멀티캐스트 프레임 수입니다



 a| 
BF
 a| 
브로드캐스트 프레임 수입니다



 a| 
PF
 a| 
중지 프레임 수입니다



 a| 
CF
 a| 
제어 프레임 수



 a| 
FDF
 a| 
프레임 지연 수입니다



 a| 
공급
 a| 
프레임 초과 유예 수입니다



 a| 
FLC
 a| 
프레임 지연 충돌 횟수



 a| 
FA
 a| 
프레임 중단 카운트



 a| 
FSC
 a| 
프레임 단일 충돌 카운트



 a| 
FMC
 a| 
여러 충돌 프레임 수



 a| 
FC
 a| 
프레임 충돌 카운트



 a| 
FDR
 a| 
프레임 드롭된 카운트



 a| 
JF
 a| 
점보 프레임 수입니다

|===
====
.MAC 수신 통계:
[%collapsible]
====
[cols="25h,~"]
|===
| 통계 | 정의 


 a| 
F
 a| 
프레임 수



 a| 
B
 a| 
바이트 수입니다



 a| 
메인프레임
 a| 
멀티캐스트 프레임 수입니다



 a| 
BF
 a| 
브로드캐스트 프레임 수입니다



 a| 
PF
 a| 
중지 프레임 수입니다



 a| 
CF
 a| 
제어 프레임 수



 a| 
레
 a| 
프레임 길이 오류 수입니다



 a| 
FD
 a| 
프레임 드롭된 카운트



 a| 
FCRCE
 a| 
프레임 CRC 오류 수입니다



 a| 
요금
 a| 
프레임 인코딩 오류 수입니다



 a| 
LFE
 a| 
큰 프레임 오류 수입니다



 a| 
SFE
 a| 
작은 프레임 오류 수입니다



 a| 
J
 a| 
Jabber 수



 a| 
UCC
 a| 
알 수 없는 제어 프레임 수입니다



 a| 
CSE
 a| 
캐리어 감지 오류 카운트

|===
====


== 이더넷 TCP/IP 통계

이더넷 TCP/IP 통계를 선택하면 TCP 및 IP 통계가 모두 나타납니다. 각 통계를 원시 통계 또는 기준 통계로 볼 수 있습니다.

.이더넷 TCP 통계:
[%collapsible]
====
[cols="25h,~"]
|===
| 통계 | 정의 


 a| 
TxS
 a| 
전송된 세그먼트 수입니다



 a| 
TxB
 a| 
전송된 바이트 수입니다



 a| 
RTxTE
 a| 
재전송 timer expired count



 a| 
TxDACK
 a| 
전송 지연 ACK 수



 a| 
TxACK
 a| 
전송 ACK 수



 a| 
Rxs
 a| 
수신된 세그먼트 수입니다



 a| 
RXB
 a| 
바이트 수가 수신되었습니다



 a| 
RxDACK
 a| 
중복 ACK 수를 수신했습니다



 a| 
RxACK
 a| 
ACK count를 수신함



 a| 
RxSEC
 a| 
세그먼트 오류 수가 수신되었습니다



 a| 
RxSOOC
 a| 
수신된 세그먼트 주문 수 초과



 a| 
RxWP
 a| 
수신 윈도우 프로브 수입니다



 a| 
RxWU
 a| 
윈도우 업데이트 카운트를 수신했습니다

|===
====
.이더넷 IP 통계:
[%collapsible]
====
[cols="25h,~"]
|===
| 통계 | 정의 


 a| 
TxP
 a| 
전송된 패킷 수입니다



 a| 
TxB
 a| 
전송된 바이트 수입니다



 a| 
TxF
 a| 
전송된 단편 카운트



 a| 
RxP
 a| 
수신된 패킷 수 수신된 IPv4 패킷 수를 표시하려면 * Show IPv4 * 를 선택합니다. 수신된 IPv6 패킷 수를 표시하려면 * IPv6 표시 * 를 선택합니다.



 a| 
RXB
 a| 
바이트 수가 수신되었습니다



 a| 
RxF
 a| 
조각 수를 받았습니다



 a| 
RxPE
 a| 
패킷 오류 카운트를 수신했습니다



 a| 
재해 복구
 a| 
데이터그램 재조립 수



 a| 
DRE-OLFC
 a| 
데이터그램 재조립 오류, 중복된 조각 수



 a| 
DRE-OOFC
 a| 
데이터그램 재조립 오류, 주문되지 않았습니다 조각 수



 a| 
DRE - TOC
 a| 
데이터그램 재조립 오류, 시간 초과 수

|===
====


== iSCSI 타겟 통계 및 로컬 이니시에이터 통계

Target(프로토콜) 통계 또는 Local initiator(프로토콜) 통계를 선택하면 iSCSI 통계가 표시됩니다. 각 통계를 원시 통계 또는 기준 통계로 볼 수 있습니다.

.iSCSI 통계:
[%collapsible]
====
[cols="25h,~"]
|===
| 통계 | 정의 


 a| 
서비스 수준
 a| 
성공적인 iSCSI 로그인 수



 a| 
UL
 a| 
실패한 iSCSI 로그인 수입니다



 a| 
토
 a| 
성공한 iSCSI 인증 수(인증이 활성화된 경우)



 a| 
UA
 a| 
실패한 iSCSI 인증 수(인증이 활성화된 경우)



 a| 
PDU입니다
 a| 
iSCSI PDU 처리 수를 수정합니다



 a| 
HDe
 a| 
헤더 다이제스트 오류 수가 포함된 iSCSI PDU



 a| 
DDE
 a| 
데이터 다이제스트 오류 수가 포함된 iSCSI PDU



 a| 
PE
 a| 
PDU와 iSCSI 프로토콜 오류 수



 a| 
우스트입니다
 a| 
예기치 않은 iSCSI 세션 종료 수입니다



 a| 
uct
 a| 
예기치 않은 iSCSI 연결 종료 수입니다

|===
====


== DCBX 작업 상태 통계

DCBX(Data Center Bridging Exchange) Operational State Statistics(DCBX) 를 선택하면 DCBX 통계가 나타납니다.

.DCBX 통계:
[%collapsible]
====
[cols="25h,~"]
|===
| 통계 | 정의 


 a| 
iSCSI 호스트 포트
 a| 
컨트롤러 번호, 포트 번호 형식으로 감지된 호스트 포트의 위치를 나타냅니다.



 a| 
우선 순위 그룹
 a| 
PG(우선 순위 그룹) 응용 프로그램의 작동 상태를 나타냅니다. 상태는 Enabled 또는 Disabled입니다.



 a| 
우선 순위 기반 흐름 제어
 a| 
우선 순위 기반 흐름 제어(PFC) 기능의 작동 상태를 나타냅니다. 상태는 Enabled 또는 Disabled입니다.



 a| 
iSCSI 기능
 a| 
iSCSI(Internet Small Computer System Interface) 응용 프로그램의 작동 상태를 나타냅니다. 상태는 Enabled 또는 Disabled입니다.



 a| 
FCoE 대역폭
 a| 
FCoE(Fibre Channel over Ethernet) 대역폭의 상태를 나타냅니다. 상태는 True 또는 False입니다.



 a| 
FCoE/FIP 맵 불일치 없음
 a| 
FCoE와 FIP(FCoE Initialization Protocol) 간의 맵 불일치가 있는지 여부를 나타냅니다. 값은 True 또는 False입니다.

|===
====

NOTE: 상태 캡처 파일에서 추가 DCBX 작업 상태 통계를 찾을 수 있습니다.



== LLDP TLV 통계

LLDP(Link Layer Discovery Protocol) TLV(Type Length Value) 통계 를 선택하면 두 가지 통계 세트가 나타납니다. 하나는 로컬 장치에, 다른 하나는 원격 장치에 대해 표시됩니다. 로컬 장치가 컨트롤러를 참조합니다. 원격 장치는 컨트롤러가 연결된 피어 장치(일반적으로 스위치)를 나타냅니다.

.LLDP TLV 통계:
[%collapsible]
====
[cols="25h,~"]
|===
| 통계 | 정의 


 a| 
iSCSI 호스트 포트
 a| 
컨트롤러 번호, 포트 번호 형식으로 감지된 호스트 포트의 위치를 나타냅니다.



 a| 
섀시 ID입니다
 a| 
섀시 ID를 나타냅니다.



 a| 
섀시 ID 하위 유형입니다
 a| 
섀시 ID 하위 유형을 나타냅니다.



 a| 
포트 ID입니다
 a| 
포트 ID를 나타냅니다.



 a| 
포트 ID 하위 유형입니다
 a| 
포트 ID 하위 유형을 나타냅니다.



 a| 
라이브까지 시간
 a| 
수신자 LLDP 상담원이 해당 정보를 유효한 것으로 간주하는 시간(초)을 나타냅니다.

|===
====

NOTE: 상태 캡처 파일에서 추가 LLDP TLV 통계를 찾을 수 있습니다.



== DCBX TLV 통계입니다

데이터 센터 브리징 교환(DCBX) 유형 길이 값(TLV) 통계를 선택하면 다음 통계가 나타납니다.

* * 로컬 통계 * -- 공장에서 컨트롤러에 구성된 DCBX 매개 변수입니다.
* * 운영 통계 * -- DCBX 협상으로 인해 발생하는 DCBX 매개 변수입니다.
* * 원격 통계 * -- 컨트롤러가 연결된 피어 장치의 DCBX 매개 변수, 일반적으로 스위치입니다.


.DCBX TLV 통계:
[%collapsible]
====
[cols="25h,~"]
|===
| 통계 | 정의 


 a| 
iSCSI 호스트 포트
 a| 
컨트롤러 번호, 포트 번호 형식으로 감지된 호스트 포트의 위치를 나타냅니다.



 a| 
흐름 제어 모드
 a| 
전체 포트의 흐름 제어 모드 유효한 값은 Disabled, Standard, Per Priority 또는 Indeterminate입니다.



 a| 
프로토콜
 a| 
통신 프로토콜입니다. 유효한 값은 FCoE, FIP, iSCSI 또는 알 수 없습니다.



 a| 
우선 순위
 a| 
통신의 우선 순위 번호를 나타내는 정수 값입니다.



 a| 
우선 순위 그룹
 a| 
프로토콜이 할당된 우선 순위 그룹을 나타내는 정수 값입니다.



 a| 
우선 순위 그룹 % 대역폭
 a| 
우선 순위 그룹에 할당된 대역폭의 양을 나타내는 백분율 값입니다.



 a| 
DCBX PFC 상태
 a| 
특정 포트의 우선 순위 기반 흐름 제어(PFC) 상태입니다. 이 값은 사용 또는 사용 안 함으로 설정됩니다.

|===
====

NOTE: 상태 캡처 파일에서 추가 DCBX TLV 통계를 찾을 수 있습니다.
