---
permalink: sm-settings/view-iscsi-sessions-system.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, iscsi, sessions, 
summary: 스토리지 배열에 대한 iSCSI 연결에 대한 자세한 정보를 볼 수 있습니다. iSCSI 세션은 비동기 미러 관계의 호스트 또는 원격 스토리지 시스템에서 발생할 수 있습니다. 
---
= iSCSI 세션을 봅니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 배열에 대한 iSCSI 연결에 대한 자세한 정보를 볼 수 있습니다. iSCSI 세션은 비동기 미러 관계의 호스트 또는 원격 스토리지 시스템에서 발생할 수 있습니다.

.단계
. 설정 [시스템] 메뉴를 선택합니다.
. iSCSI 세션 보기/종료 * 를 선택합니다.
+
현재 iSCSI 세션 목록이 나타납니다.

. * 선택 사항: * 특정 iSCSI 세션에 대한 추가 정보를 보려면 세션을 선택한 다음 * 세부 정보 보기 * 를 클릭합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 항목 | 설명 


 a| 
세션 식별자(SSID)
 a| 
iSCSI 이니시에이터와 iSCSI 타겟 간의 세션을 식별하는 16진수 문자열입니다. SSID는 ISID와 TPGT로 구성됩니다.



 a| 
이니시에이터 세션 ID(ISID)
 a| 
세션 식별자의 이니시에이터 부분입니다. 초기자는 로그인 중에 ISID를 지정합니다.



 a| 
대상 포털 그룹
 a| 
iSCSI 타겟입니다.



 a| 
대상 포털 그룹 태그(TPGT)
 a| 
세션 식별자의 대상 부분. iSCSI 대상 포털 그룹의 16비트 숫자 식별자입니다.



 a| 
이니시에이터 iSCSI 이름입니다
 a| 
이니시에이터의 전 세계에서 고유한 이름입니다.



 a| 
이니시에이터 iSCSI 레이블
 a| 
System Manager에 설정된 사용자 레이블입니다.



 a| 
이니시에이터 iSCSI 별칭입니다
 a| 
iSCSI 노드와 연결할 수도 있는 이름입니다. 별칭을 사용하면 조직에서 사용자에게 친숙한 문자열을 iSCSI 이름과 연결할 수 있습니다. 그러나 별칭은 iSCSI 이름을 대체하는 것이 아닙니다. 이니시에이터 iSCSI 별칭은 호스트에서만 설정할 수 있고 System Manager에서는 설정할 수 없습니다



 a| 
호스트
 a| 
스토리지 배열에 입력 및 출력을 전송하는 서버입니다.



 a| 
연결 ID(CID)
 a| 
이니시에이터와 타겟 간의 세션 내 접속에 대한 고유한 이름입니다. 초기자는 이 ID를 생성하여 로그인 요청 중에 대상에 제공합니다. 연결이 닫히라는 로그아웃 중에도 연결 ID가 표시됩니다.



 a| 
이더넷 포트 식별자입니다
 a| 
연결과 관련된 컨트롤러 포트입니다.



 a| 
이니시에이터 IP 주소입니다
 a| 
이니시에이터의 IP 주소입니다.



 a| 
협상된 로그인 매개 변수
 a| 
iSCSI 세션 로그인 중에 트랜잭션되는 매개 변수입니다.



 a| 
인증 방법
 a| 
iSCSI 네트워크에 액세스할 사용자를 인증하는 기술입니다. 유효한 값은 * CHAP * 및 * 없음 * 입니다.



 a| 
헤더 다이제스트 방법입니다
 a| 
iSCSI 세션에 대해 가능한 헤더 값을 표시하는 기술입니다. HeaderDigest 및 DataDigest는 * None * 또는 * CRC32C * 일 수 있습니다. 두 가지 모두 기본값은 * 없음 * 입니다.



 a| 
데이터 다이제스트 방법입니다
 a| 
iSCSI 세션에 대해 가능한 데이터 값을 표시하는 기술입니다. HeaderDigest 및 DataDigest는 * None * 또는 * CRC32C * 일 수 있습니다. 두 가지 모두 기본값은 * 없음 * 입니다.



 a| 
최대 연결 수
 a| 
iSCSI 세션에 허용되는 최대 연결 수입니다. 최대 연결 수는 1 ~ 4입니다. 기본값은 * 1 * 입니다.



 a| 
대상 별칭
 a| 
대상과 연관된 레이블입니다.



 a| 
이니시에이터 별칭입니다
 a| 
이니시에이터와 연결된 레이블입니다.



 a| 
대상 IP 주소입니다
 a| 
iSCSI 세션의 타겟의 IP 주소입니다. DNS 이름은 지원되지 않습니다.



 a| 
초기 R2T
 a| 
초기 전송 준비 상태입니다. 상태는 * 예 * 또는 * 아니요 * 일 수 있습니다.



 a| 
최대 버스트 길이
 a| 
이 iSCSI 세션의 최대 SCSI 페이로드(바이트) 최대 버스트 길이는 512에서 262,144(256KB)입니다. 기본값은 * 262,144(256KB) * 입니다.



 a| 
첫 번째 버스트 길이
 a| 
이 iSCSI 세션에 대한 요청되지 않은 데이터의 SCSI 페이로드입니다. 첫 번째 버스트 길이는 512에서 131,072(128KB)일 수 있습니다. 기본값은 * 65,536(64KB) * 입니다.



 a| 
기본 대기 시간입니다
 a| 
연결 종료 또는 연결 재설정 후 연결을 시도하기 전에 대기하는 최소 시간(초)입니다. 기본 대기 시간은 0에서 3600 사이입니다. 기본값은 * 2 * 입니다.



 a| 
기본 유지 시간
 a| 
연결 종료 또는 연결 재설정 후에도 연결이 가능한 최대 시간(초)입니다. 기본 유지 시간은 0에서 3600 사이입니다. 기본값은 * 20 * 입니다.



 a| 
최대 미결 R2T
 a| 
이 iSCSI 세션에 대해 최대 "전송 준비 완료" 수입니다. 전송 준비 완료 최대 값은 1에서 16 사이의 값일 수 있습니다. 기본값은 * 1 * 입니다.



 a| 
복구 수준 오류
 a| 
이 iSCSI 세션에 대한 오류 복구 수준입니다. 오류 복구 레벨 값은 항상 * 0 * 으로 설정됩니다.



 a| 
최대 수신 데이터 세그먼트 길이
 a| 
이니시에이터 또는 타겟이 iSCSI PDU(페이로드 데이터 유닛)에서 수신할 수 있는 최대 데이터 양입니다.



 a| 
대상 이름입니다
 a| 
대상의 공식 이름(별칭 아님). 대상 이름(_iqn_format)입니다.



 a| 
이니시에이터 이름입니다
 a| 
이니시에이터의 공식 이름(별칭 아님) _iqn_ 또는 _eui_format을 사용하는 이니시에이터 이름입니다.

|===
====
. * 선택 사항: * 보고서를 파일에 저장하려면 * 저장 * 을 클릭합니다.
+
이 파일은 브라우저의 다운로드 폴더에 "iscsi-session-connections.txt"라는 파일 이름으로 저장됩니다.


