---
permalink: sm-settings/what-is-cache-flushing.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cache, flushing, 
summary: 캐시에 기록되지 않은 데이터의 양이 특정 수준에 도달하면 컨트롤러는 캐시된 데이터를 드라이브에 주기적으로 씁니다. 이 쓰기 프로세스를 플러싱이라고 합니다. 
---
= 캐시 플러싱이란 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
캐시에 기록되지 않은 데이터의 양이 특정 수준에 도달하면 컨트롤러는 캐시된 데이터를 드라이브에 주기적으로 씁니다. 이 쓰기 프로세스를 "플러시"라고 합니다.

컨트롤러는 캐시 플러싱에 두 가지 알고리즘(요구 기반 및 사용 기간 기반)을 사용합니다. 컨트롤러는 캐시된 데이터의 양이 캐시 플러시 임계값 아래로 떨어질 때까지 수요 기반 알고리즘을 사용합니다. 기본적으로 플러시는 캐시의 80%가 사용 중일 때 시작됩니다.

System Manager에서 "Start demand cache flashing" 임계값을 설정하여 사용자 환경에서 사용되는 입출력 유형을 가장 잘 지원할 수 있습니다. 주로 쓰기 작업을 수행하는 환경에서는 "Start demand cache flashing" 비율을 높게 설정하여 새 쓰기 요청을 디스크로 이동하지 않고 캐시로 처리할 수 있는 확률을 높여야 합니다. 백분율 설정은 더 많은 데이터가 캐시에 남아 있도록 캐시 플러시 수를 제한하여 캐시 적중률이 증가할 수 있습니다.

입출력 오류가 발생하는 환경(데이터 급증)에서는 낮은 캐시 플러시를 사용하여 시스템이 데이터 버스트 사이에 캐시를 자주 플러시할 수 있습니다. 다양한 부하를 처리하는 다양한 I/O 환경에서 또는 로드 유형을 알 수 없는 경우 임계값을 양호한 중간 지면으로 50%로 설정합니다. 시작 비율이 80%보다 낮은 경우 호스트 읽기에 필요한 데이터를 사용할 수 없기 때문에 성능이 저하될 수 있습니다. 낮은 비율을 선택하면 캐시 레벨을 유지하는 데 필요한 디스크 쓰기 수도 증가하여 시스템 오버헤드가 증가합니다.

연령 기반 알고리즘은 쓰기 데이터가 디스크에 플러시되기 전에 캐시에 남아 있을 수 있는 기간을 지정합니다. 컨트롤러는 캐시 플러시 임계값에 도달할 때까지 연령 기반 알고리즘을 사용합니다. 기본값은 10초이지만 이 기간은 비활성 기간 동안에만 계산됩니다. System Manager에서 플러시 타이밍을 수정할 수 없습니다. 대신 CLI(Command-Line Interface)에서 * 스토리지 배열 설정 * 명령을 사용해야 합니다.

[CAUTION]
====
* 데이터 손실 가능성 * -- 배터리 없이 * 쓰기 캐싱 * 옵션을 활성화하고 보호를 위한 범용 전원 공급 장치가 없는 경우 데이터가 손실될 수 있습니다. 또한 컨트롤러 배터리가 없고 * 배터리 없이 쓰기 캐싱 * 옵션을 활성화하면 데이터가 손실될 수 있습니다.

====