---
permalink: sm-settings/what-is-controller-cache.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, controller, cache, 
summary: '컨트롤러 캐시는 두 가지 유형의 I/O(I/O) 작업, 즉 컨트롤러 및 호스트 간, 컨트롤러 및 디스크 간 작업을 간소화하는 물리적 메모리 공간입니다.' 
---
= 컨트롤러 캐시란 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러 캐시는 두 가지 유형의 I/O(I/O) 작업, 즉 컨트롤러 및 호스트 간, 컨트롤러 및 디스크 간 작업을 간소화하는 물리적 메모리 공간입니다.

읽기 및 쓰기 데이터 전송의 경우 호스트와 컨트롤러는 고속 연결을 통해 통신합니다. 그러나 디스크가 상대적으로 느린 장치이기 때문에 컨트롤러의 백엔드에서 디스크와의 통신이 느려집니다.

컨트롤러 캐시가 데이터를 수신하면 컨트롤러는 데이터가 현재 보유 중인 호스트 애플리케이션에 확인합니다. 이렇게 하면 호스트 애플리케이션이 I/O가 디스크에 기록될 때까지 기다릴 필요가 없습니다. 대신 응용 프로그램에서 작업을 계속할 수 있습니다. 또한 서버 애플리케이션에서 캐시된 데이터에 쉽게 액세스할 수 있으므로 데이터에 액세스하기 위해 디스크를 추가로 읽을 필요가 없습니다.

컨트롤러 캐시는 다음과 같은 여러 가지 방법으로 스토리지 어레이의 전반적인 성능에 영향을 줍니다.

* 캐시는 버퍼 역할을 하므로 호스트 및 디스크 데이터 전송을 동기화할 필요가 없습니다.
* 호스트의 읽기 또는 쓰기 작업에 대한 데이터가 이전 작업의 캐시에 있을 수 있으므로 디스크를 액세스할 필요가 없습니다.
* 쓰기 캐시를 사용하는 경우 이전 쓰기 작업의 데이터가 디스크에 기록되기 전에 호스트에서 후속 쓰기 명령을 전송할 수 있습니다.
* 캐시 프리페치가 설정된 경우 순차적 읽기 액세스가 최적화됩니다. 캐시 프리페치를 사용하면 디스크에서 데이터를 읽는 대신 캐시에서 데이터를 더 많이 찾을 수 있습니다.


[CAUTION]
====
* 데이터 손실 가능성 * -- 배터리 없이 * 쓰기 캐싱 * 옵션을 활성화하고 보호를 위한 범용 전원 공급 장치가 없는 경우 데이터가 손실될 수 있습니다. 또한 컨트롤러 배터리가 없고 * 배터리 없이 쓰기 캐싱 * 옵션을 활성화하면 데이터가 손실될 수 있습니다.

====