---
permalink: sm-support/activate-controller-software-and-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, activate, controller, software, firmware 
summary: 업그레이드 파일을 즉시 활성화하거나 더 편리한 시간이 될 때까지 기다릴 수 있습니다. 
---
= 컨트롤러 소프트웨어 및 펌웨어를 활성화합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드 파일을 즉시 활성화하거나 더 편리한 시간이 될 때까지 기다릴 수 있습니다.

.이 작업에 대해
파일을 활성화하지 않고 다운로드 및 전송할 수 있습니다. 다음과 같은 이유로 나중에 정품 인증을 선택할 수 있습니다.

* * 시간 * -- 소프트웨어 및 펌웨어를 활성화하는 데 시간이 오래 걸릴 수 있으므로 I/O 로드가 가벼워질 때까지 기다려야 할 수 있습니다. 활성화 중에 컨트롤러가 페일오버되므로 업그레이드가 완료될 때까지 성능이 평소보다 저하될 수 있습니다.
* * 패키지 유형 * -- 다른 스토리지 어레이의 파일을 업그레이드하기 전에 한 스토리지 어레이에서 새 소프트웨어 및 펌웨어를 테스트할 수 있습니다.


전송되었지만 활성화되지 않은 소프트웨어 또는 펌웨어가 있는 경우 System Manager 홈 페이지의 알림 영역과 업그레이드 센터 페이지에서 알림이 표시됩니다.

[CAUTION]
====
활성화 프로세스가 시작된 후에는 중지할 수 없습니다.

====
.단계
. 메뉴 선택: 지원 [업그레이드 센터].
. SANtricity OS 컨트롤러 소프트웨어 업그레이드 영역에서 * 활성화 * 를 클릭하고 작업을 수행할지 확인합니다.
+
업그레이드 전 상태 점검 중에는 작업을 취소할 수 있지만 활성화하는 동안에는 취소할 수 없습니다.

+
업그레이드 전 상태 점검이 시작됩니다. 업그레이드 전 상태 점검을 통과하면 업그레이드 프로세스에서 파일 활성화를 진행합니다. 업그레이드 전 상태 점검에 실패하면 Recovery Guru를 사용하거나 기술 지원 부서에 문의하여 문제를 해결하십시오. 일부 유형의 경우, 기술 지원 부서에서는 오류 발생 시 * 업그레이드 허용 * 확인란을 선택하여 업그레이드를 계속하도록 조언할 수 있습니다.

+
업그레이드 전 상태 점검이 성공적으로 완료되면 활성화가 발생합니다. 활성화하는 데 걸리는 시간은 스토리지 배열 구성과 활성화 중인 구성 요소에 따라 달라집니다.

. * 선택 사항: * 업그레이드된 항목 목록을 보려면 * 로그 저장 * 을 클릭합니다.
+
파일은 브라우저의 다운로드 폴더에 drive_upgrade_log-timestamp.txt라는 이름으로 저장됩니다.



.작업을 마친 후
* 하드웨어 페이지에 모든 구성 요소가 나타나는지 확인합니다.
* 소프트웨어 및 펌웨어 인벤토리 대화 상자(지원 [업그레이드 센터] 메뉴로 이동한 다음 * 소프트웨어 및 펌웨어 인벤토리 * 링크를 클릭하여 소프트웨어 및 펌웨어 버전을 확인합니다.
* 컨트롤러 NVSRAM을 업그레이드한 경우 기존 NVSRAM에 적용한 모든 사용자 정의 설정은 활성화 과정 중에 손실됩니다. 활성화 프로세스가 완료된 후 NVSRAM에 사용자 정의 설정을 다시 적용해야 합니다.

