---
permalink: sm-support/autosupport-feature-overview.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, autosupport, ASUP 
summary: AutoSupport 기능은 스토리지 배열의 상태를 모니터링하고 자동 디스패치를 기술 지원 부서에 보냅니다. 
---
= AutoSupport 기능 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 기능은 스토리지 배열의 상태를 모니터링하고 자동 디스패치를 기술 지원 부서에 보냅니다.

기술 지원 부서에서는 AutoSupport 데이터를 적극적으로 활용하여 고객의 문제를 더욱 신속하게 진단 및 해결하고 사전에 잠재적 문제를 감지하고 해결합니다.

AutoSupport 데이터에는 스토리지 배열의 구성, 상태, 성능 및 시스템 이벤트에 대한 정보가 포함됩니다. AutoSupport 데이터에 사용자 데이터가 없습니다. 디스패치는 즉시 또는 일정(매일 및 매주)으로 보낼 수 있습니다.



== 주요 이점

AutoSupport 기능의 몇 가지 주요 이점은 다음과 같습니다.

* 신속한 케이스 해결 시간
* 보다 빠른 인시던트 관리를 위한 정교한 모니터링
* 일정에 따라 보고 자동화 및 중요 이벤트에 대한 자동 보고 기능
* 드라이브와 같은 선택한 구성 요소에 대한 자동 하드웨어 교체 요청
* 운영 환경에 영향을 주지 않는 경고 기능을 통해 문제를 알리고 기술 지원 부서에서 수정 조치를 취할 수 있도록 정보를 제공합니다
* 알려진 구성 문제에 대한 디스패치를 모니터링하는 AutoSupport 분석 도구입니다




== 개별 AutoSupport 기능

AutoSupport 기능은 사용자가 별도로 사용하는 세 가지 개별 기능으로 구성됩니다.

* * 기본 AutoSupport * -- 스토리지 어레이에서 자동으로 데이터를 수집하여 기술 지원 부서에 전송할 수 있습니다.
* * AutoSupport OnDemand * -- 문제 해결을 위해 필요한 경우 기술 지원 부서에서 이전 AutoSupport 디스패치의 재전송을 요청할 수 있습니다. 모든 전송은 AutoSupport 서버가 아니라 스토리지 시스템에서 시작됩니다. 스토리지 어레이는 AutoSupport 서버와 주기적으로 확인하여 보류 중인 재전송 요청이 있는지 확인하고 그에 따라 응답합니다.
* * 원격 진단* -- 문제 해결을 위해 필요한 경우 기술 지원 부서에서 새로운 최신 AutoSupport 디스패치를 요청할 수 있습니다. 모든 전송은 AutoSupport 서버가 아니라 스토리지 시스템에서 시작됩니다. 스토리지 어레이는 AutoSupport 서버와 주기적으로 확인하여 보류 중인 새 요청이 있는지 확인하고 그에 따라 응답합니다.




== AutoSupport와 지원 데이터 수집의 차이

스토리지 시스템에 두 가지 방법으로 지원 데이터를 수집할 수 있습니다.

* * AutoSupport Feature * -- 데이터가 자동으로 수집됩니다.
* * 지원 데이터 수집 옵션 * -- 데이터를 수동으로 수집 및 전송해야 합니다.


AutoSupport 기능은 데이터가 자동으로 수집되고 전송되므로 사용이 간편합니다. AutoSupport 데이터를 사전에 사용하여 문제가 발생하기 전에 방지할 수 있습니다. AutoSupport 기능은 기술 지원 부서에서 이미 데이터에 액세스할 수 있기 때문에 문제 해결 시간이 단축됩니다. 이러한 이유로 AutoSupport 기능은 사용하는 기본 데이터 수집 방법입니다.
