---
permalink: sm-support/clear-recovery-mode.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, clear, recovery, mode 
summary: 스토리지 배열 구성을 복원한 후 복구 모드 지우기 작업을 사용하여 스토리지 배열의 I/O를 재개하고 정상 작업으로 되돌립니다. 
---
= 복구 모드를 해제합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 배열 구성을 복원한 후 복구 모드 지우기 작업을 사용하여 스토리지 배열의 I/O를 재개하고 정상 작업으로 되돌립니다.

.시작하기 전에
* 스토리지 배열을 이전 구성으로 되돌리려면 복구 모드를 지우기 전에 백업에서 구성을 복원해야 합니다.
* 복원 성공 여부를 확인하려면 유효성 검사를 수행하거나 기술 지원 부서에 확인해야 합니다. 복원이 성공적이었는 것을 확인한 후 복구 모드를 지울 수 있습니다.


.이 작업에 대해
스토리지 어레이에는 논리적 구성(풀, 볼륨 그룹, 볼륨 등)의 레코드가 포함된 구성 데이터베이스가 포함되어 있습니다. 스토리지 배열 구성을 의도적으로 지우거나 구성 데이터베이스가 손상된 경우 스토리지 배열은 복구 모드로 전환됩니다. 복구 모드는 입출력을 중지하고 구성 데이터베이스를 중지하므로 다음 중 하나를 수행할 수 있습니다.

* 컨트롤러의 플래시 장치에 저장된 자동 백업에서 구성을 복원합니다. 이 작업을 수행하려면 기술 지원 부서에 문의해야 합니다.
* 이전 구성 데이터베이스 저장 작업에서 구성을 복원합니다. 구성 저장 데이터베이스 작업은 CLI(Command Line Interface)를 통해 수행됩니다.
* 스토리지 배열을 처음부터 다시 구성합니다.


스토리지 배열 구성을 복원하거나 재정의하고 모두 잘 되었는지 확인한 후에는 복구 모드를 수동으로 지워야 합니다.

[NOTE]
====
복구 모드 지우기 작업을 시작한 후에는 취소할 수 없습니다. 복구 모드를 지우는 데 시간이 오래 걸릴 수 있습니다. 기술 지원 부서에서 지시한 경우에만 이 작업을 수행하십시오.

====
.단계
. 지원 [지원 센터 > 진단] 탭을 선택합니다.
. 복구 모드 지우기 * 를 선택하고 이 작업을 수행할지 확인합니다.
+
이 옵션은 스토리지 배열이 복구 모드에 있는 경우에만 나타납니다.


