---
permalink: sm-support/enable-or-disable-autosupport-features.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, enable, disable, autosupport, 
summary: 초기 설정 중에 AutoSupport 기능 및 개별 AutoSupport 기능을 활성화하거나 나중에 활성화하거나 비활성화할 수 있습니다. 
---
= AutoSupport 기능을 활성화 또는 비활성화합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
초기 설정 중에 AutoSupport 기능 및 개별 AutoSupport 기능을 활성화하거나 나중에 활성화하거나 비활성화할 수 있습니다.

.시작하기 전에
AutoSupport OnDemand 또는 원격 진단을 활성화하려면 AutoSupport 전송 방법을 HTTPS로 설정해야 합니다.

.이 작업에 대해
언제든지 AutoSupport 기능을 사용하지 않도록 설정할 수 있지만, 이 기능을 활성 상태로 두는 것이 좋습니다. AutoSupport 기능을 사용하면 스토리지 어레이에서 문제가 발생할 경우 문제 확인 및 해결 속도를 크게 높일 수 있습니다.

AutoSupport 기능은 사용자가 별도로 사용하는 세 가지 개별 기능으로 구성됩니다.

* * 기본 AutoSupport * -- 스토리지 어레이에서 자동으로 데이터를 수집하여 기술 지원 부서에 전송할 수 있습니다.
* * AutoSupport OnDemand * -- 문제 해결을 위해 필요한 경우 기술 지원 부서에서 이전 AutoSupport 디스패치의 재전송을 요청할 수 있습니다. 모든 전송은 AutoSupport 서버가 아니라 스토리지 시스템에서 시작됩니다. 스토리지 어레이는 AutoSupport 서버와 주기적으로 확인하여 보류 중인 재전송 요청이 있는지 확인하고 그에 따라 응답합니다.
* * 원격 진단* -- 문제 해결을 위해 필요한 경우 기술 지원 부서에서 새로운 최신 AutoSupport 디스패치를 요청할 수 있습니다. 모든 전송은 AutoSupport 서버가 아니라 스토리지 시스템에서 시작됩니다. 스토리지 어레이는 AutoSupport 서버와 주기적으로 확인하여 보류 중인 새 요청이 있는지 확인하고 그에 따라 응답합니다.


.단계
. 지원 [지원 센터 > AutoSupport] 탭을 선택합니다.
. AutoSupport 기능 활성화/비활성화 * 를 선택합니다.
. 활성화할 AutoSupport 기능 옆의 확인란을 선택합니다.
+
피처는 대화 상자의 항목 들여쓰기로 표시되는 대로 서로 다릅니다. 예를 들어 원격 진단을 활성화하려면 AutoSupport OnDemand를 활성화해야 합니다.

. 저장 * 을 클릭합니다.
+
AutoSupport를 사용하지 않도록 설정하면 홈 페이지에 알림이 표시됩니다. 무시 * 를 클릭하여 알림을 해제할 수 있습니다.


