---
permalink: sm-support/faq-autosupport.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity System Manager에 대한 AutoSupport FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 어떤 데이터를 수집하고 있습니까?

AutoSupport 기능 및 수동 지원 데이터 수집 기능은 고객 지원 번들에서 데이터를 수집하는 방법을 제공하여 기술 지원 팀의 원격 문제 해결 및 문제 분석을 지원합니다.

고객 지원 번들은 스토리지 어레이에 대한 모든 유형의 정보를 압축된 단일 파일로 수집합니다. 수집되는 정보에는 물리적 구성, 논리적 구성, 버전 정보, 이벤트, 로그 파일, 성능 데이터입니다. 이 정보는 기술 지원 부서에서 스토리지 어레이 관련 문제를 해결하는 데 사용됩니다.



== 읽을 수 없는 섹터 데이터는 무엇을 보여 줍니까?

스토리지 배열의 드라이브에서 검색된 읽을 수 없는 섹터에 대한 자세한 데이터를 표시할 수 있습니다.

읽을 수 없는 섹터 로그는 가장 최근의 읽을 수 없는 섹터를 먼저 보여줍니다. 이 로그에는 읽을 수 없는 섹터가 포함된 볼륨에 대한 다음 정보가 포함되어 있습니다. 필드를 정렬할 수 있습니다.

[cols="25h,~"]
|===
| 필드에 입력합니다 | 설명 


 a| 
영향을 받는 볼륨
 a| 
볼륨의 레이블을 표시합니다. 누락된 볼륨에 읽을 수 없는 섹터가 포함된 경우, 누락 볼륨에 대한 월드 와이드 식별자가 표시됩니다.



 a| 
논리 단위 번호(LUN)
 a| 
에는 볼륨의 LUN이 나와 있습니다. 볼륨에 LUN이 없으면 대화 상자에 NA가 표시됩니다.



 a| 
할당 대상
 a| 
에는 볼륨에 대한 액세스 권한이 있는 호스트 또는 호스트 클러스터가 나와 있습니다. 호스트, 호스트 클러스터 또는 기본 클러스터에서 볼륨에 액세스할 수 없는 경우 대화 상자에 NA가 표시됩니다.

|===
읽을 수 없는 섹터에 대한 추가 정보를 보려면 볼륨 옆에 있는 더하기 기호(+)를 클릭합니다.

[cols="25h,~"]
|===
| 필드에 입력합니다 | 설명 


 a| 
날짜/시간입니다
 a| 
읽을 수 없는 섹터가 감지된 날짜와 시간을 표시합니다.



 a| 
볼륨 논리적 블록 주소입니다
 a| 
볼륨의 LBA(논리 블록 주소)를 표시합니다.



 a| 
드라이브 위치
 a| 
에는 드라이브 쉘프, 서랍(드라이브 쉘프에 서랍이 있는 경우) 및 베이 위치가 나와 있습니다.



 a| 
드라이브 논리 블록 주소
 a| 
에서는 드라이브의 LBA를 보여 줍니다.



 a| 
실패 유형
 a| 
에서는 다음 오류 유형 중 하나를 보여 줍니다.

* * 물리적 * -- 물리적 미디어 오류입니다.
* * 논리 * -- 스트라이프의 다른 위치에서 읽기 오류가 발생하여 데이터를 읽을 수 없습니다. 예를 들어, 볼륨의 다른 위치에서 미디어 오류로 인해 읽을 수 없는 섹터가 있습니다.
* * 불일치 * -- 일관성 없는 중복 데이터.
* * Data Assurance * -- Data Assurance 오류입니다.


|===


== 건강 이미지란 무엇입니까?

상태 이미지는 기술 지원 부서에서 컨트롤러 문제를 진단하는 데 사용할 수 있는 컨트롤러 프로세서 메모리의 원시 데이터 덤프입니다.

펌웨어는 특정 오류를 감지하면 자동으로 상태 이미지를 생성합니다. 특정 문제 해결 시나리오에서 기술 지원 부서에서는 사용자가 상태 이미지 파일을 검색하여 해당 파일로 보내도록 요청할 수 있습니다.



== AutoSupport 기능은 어떤 기능을 합니까?

AutoSupport 기능은 사용자가 별도로 사용하는 세 가지 개별 기능으로 구성됩니다.

* * 기본 AutoSupport * -- 스토리지 어레이에서 자동으로 데이터를 수집하여 기술 지원 부서에 전송할 수 있습니다.
* * AutoSupport OnDemand * -- 문제 해결을 위해 필요한 경우 기술 지원 부서에서 이전 AutoSupport 디스패치의 재전송을 요청할 수 있습니다. 모든 전송은 AutoSupport 서버가 아니라 스토리지 시스템에서 시작됩니다. 스토리지 어레이는 AutoSupport 서버와 주기적으로 확인하여 보류 중인 재전송 요청이 있는지 확인하고 그에 따라 응답합니다.
* * 원격 진단* -- 문제 해결을 위해 필요한 경우 기술 지원 부서에서 새로운 최신 AutoSupport 디스패치를 요청할 수 있습니다. 모든 전송은 AutoSupport 서버가 아니라 스토리지 시스템에서 시작됩니다. 스토리지 어레이는 AutoSupport 서버와 주기적으로 확인하여 보류 중인 새 요청이 있는지 확인하고 그에 따라 응답합니다.




== AutoSupport 기능을 통해 수집되는 데이터 유형은 무엇입니까?

AutoSupport 기능에는 이벤트 디스패치, 예약된 디스패치, 주문형 및 원격 진단 디스패치의 세 가지 표준 디스패치 유형이 있습니다.

AutoSupport 데이터에 사용자 데이터가 없습니다.

* * 이벤트 디스패치 *
+
기술 지원에 사전 알림이 필요한 이벤트가 시스템에서 발생할 경우 AutoSupport 기능은 자동으로 이벤트 트리거 디스패치를 보냅니다.

+
** 관리되는 스토리지 어레이에서 지원 이벤트가 발생할 때 발송됩니다.
** 이벤트가 발생한 시점의 스토리지 어레이에 대한 포괄적인 스냅샷이 포함됩니다.


* * 예약된 디스패치 *
+
AutoSupport 기능은 정기적으로 여러 개의 디스패치를 자동으로 전송합니다.

+
** * 일일 디스패치 * -- 사용자가 구성할 수 있는 시간 간격 동안 매일 한 번 발송됩니다. 현재 시스템 이벤트 로그 및 성능 데이터가 포함됩니다.
** * 주별 디스패치 * -- 사용자가 구성할 수 있는 시간 간격 및 일 동안 매주 한 번 발송됩니다. 구성 및 시스템 상태 정보를 포함합니다.


* * AutoSupport OnDemand 및 원격 진단 디스패치 *
+
** * AutoSupport OnDemand * -- 문제 해결을 위해 필요한 경우 기술 지원 부서에서 이전 AutoSupport 디스패치의 재전송을 요청할 수 있습니다. 모든 전송은 AutoSupport 서버가 아니라 스토리지 시스템에서 시작됩니다. 스토리지 어레이는 AutoSupport 서버와 주기적으로 확인하여 보류 중인 재전송 요청이 있는지 확인하고 그에 따라 응답합니다.
** * 원격 진단* -- 문제 해결을 위해 필요한 경우 기술 지원 부서에서 새로운 최신 AutoSupport 디스패치를 요청할 수 있습니다. 모든 전송은 AutoSupport 서버가 아니라 스토리지 시스템에서 시작됩니다. 스토리지 어레이는 AutoSupport 서버와 주기적으로 확인하여 보류 중인 새 요청이 있는지 확인하고 그에 따라 응답합니다.






== AutoSupport 기능의 전달 방법을 구성하려면 어떻게 합니까?

AutoSupport 기능은 기술 지원에 AutoSupport 디스패치를 전달하기 위한 프로토콜 HTTPS 및 SMTP를 지원합니다.

.시작하기 전에
* AutoSupport 기능을 활성화해야 합니다. AutoSupport 페이지에서 활성화되어 있는지 여부를 확인할 수 있습니다.
* 네트워크에 DNS 서버가 설치 및 구성되어 있어야 합니다. DNS 서버 주소는 System Manager에서 구성해야 합니다(이 작업은 하드웨어 페이지에서 사용 가능).


.이 작업에 대해
다양한 프로토콜을 검토합니다.

* * HTTPS * -- HTTPS를 사용하여 대상 기술 지원 서버에 직접 연결할 수 있습니다. AutoSupport OnDemand 또는 원격 진단을 활성화하려면 AutoSupport 전송 방법을 HTTPS로 설정해야 합니다.
* * 이메일 * -- 이메일 서버를 AutoSupport 디스패치 전송 방법으로 사용할 수 있습니다.


[NOTE]
====
* HTTPS 및 이메일 방법의 차이점 *. SMTP를 사용하는 이메일 전달 방법은 HTTPS 전달 방법과 몇 가지 중요한 차이가 있습니다. 먼저, 이메일 방법에 대한 디스패치 크기는 5MB로 제한되며, 이는 일부 ASUP 데이터 수집이 디스패치되지 않음을 의미합니다. 둘째, AutoSupport OnDemand 기능은 HTTPS 전달 방법에서만 사용할 수 있습니다.

====
.단계
. 지원 [지원 센터 > AutoSupport] 탭을 선택합니다.
. AutoSupport 제공 방법 구성 * 을 선택합니다.
+
디스패치 제공 방법이 나열된 대화 상자가 나타납니다.

. 원하는 전달 방법을 선택한 다음 해당 전달 방법에 대한 매개 변수를 선택합니다. 다음 중 하나를 수행합니다.
+
** HTTPS를 선택한 경우 다음 전달 매개 변수 중 하나를 선택합니다.
+
*** * 직접 * -- 이 전달 매개 변수는 기본 선택 항목입니다. 이 옵션을 선택하면 HTTPS 프로토콜을 사용하여 대상 기술 지원 시스템에 직접 연결할 수 있습니다.
*** * 프록시 서버를 통해 * -- 이 옵션을 선택하면 대상 기술 지원 시스템과의 연결을 설정하는 데 필요한 HTTP 프록시 서버 세부 정보를 지정할 수 있습니다. 호스트 주소와 포트 번호를 지정해야 합니다. 그러나 필요한 경우 호스트 인증 세부 정보(사용자 이름 및 암호)만 입력하면 됩니다.
*** * 프록시 자동 구성 스크립트(PAC)를 통해 * -- 프록시 자동 구성(PAC) 스크립트 파일의 위치를 지정합니다. PAC 파일을 사용하면 시스템이 대상 기술 지원 시스템과의 연결을 설정할 적절한 프록시 서버를 자동으로 선택할 수 있습니다.


** 이메일 을 선택한 경우 다음 정보를 입력합니다.
+
*** 메일 서버 주소는 정규화된 도메인 이름, IPv4 주소 또는 IPv6 주소입니다.
*** AutoSupport 디스패치 이메일의 보낸 사람 필드에 나타나는 이메일 주소입니다.
*** * 선택 사항. 구성 테스트를 수행하려는 경우. * AutoSupport 시스템이 테스트 디스패치를 받을 때 확인을 보내는 이메일 주소입니다.
*** 메시지를 암호화하려면 암호화 유형으로 * SMTPS * 또는 * STARTTLS * 를 선택한 다음 암호화된 메시지의 포트 번호를 선택합니다. 그렇지 않으면 * 없음 * 을 선택합니다.
*** 필요한 경우 보내는 보낸 사람과 메일 서버에서 인증을 위한 사용자 이름과 암호를 입력합니다.




. 지정된 전달 매개 변수를 사용하여 기술 지원 서버에 대한 연결을 테스트하려면 * Test Configuration * 을 클릭합니다. AutoSupport 온디맨드 기능을 활성화한 경우 AutoSupport OnDemand 디스패치 전달에 대한 연결도 테스트합니다.
+
구성 테스트에 실패하면 구성 설정을 확인하고 테스트를 다시 실행하십시오. 테스트가 계속 실패하면 기술 지원 부서에 문의하십시오.

. 저장 * 을 클릭합니다.




== 구성 데이터란 무엇입니까?

구성 데이터 수집 을 선택하면 시스템이 RAID 구성 데이터베이스의 현재 상태를 저장합니다.

RAID 구성 데이터베이스에는 컨트롤러의 볼륨 그룹 및 디스크 풀에 대한 모든 데이터가 포함됩니다. 구성 데이터 수집 기능은 'Save storageArray dbmDatabase'에 대한 CLI 명령과 동일한 정보를 저장합니다.



== SANtricity OS 소프트웨어를 업그레이드하기 전에 알아야 할 내용은 무엇입니까?

컨트롤러의 소프트웨어 및 펌웨어를 업그레이드하기 전에 이러한 항목을 숙지하십시오.

* 문서 및 "readme.txt" 파일을 읽었으며 업그레이드를 수행하기로 결정했습니다.
* IOM 펌웨어를 업그레이드할지 여부를 알고 있습니다.
+
일반적으로 모든 구성 요소를 동시에 업그레이드해야 합니다. 하지만 SANtricity OS 컨트롤러 소프트웨어 업그레이드의 일부로 업그레이드하지 않으려는 경우 또는 기술 지원 부서에서 IOM 펌웨어를 다운그레이드하도록 지시한 경우(명령줄 인터페이스를 사용하여 펌웨어를 다운그레이드할 수만 있음) IOM 펌웨어를 업그레이드하지 않을 수도 있습니다.

* 컨트롤러 NVSRAM 파일을 업그레이드할지 여부를 알 수 있습니다.
+
일반적으로 모든 구성 요소를 동시에 업그레이드해야 합니다. 그러나 파일이 패치되었거나 사용자 정의 버전이고 덮어쓰지 않으려는 경우 컨트롤러 NVSRAM 파일을 업그레이드하지 않을 수 있습니다.

* 지금 활성화할지 아니면 나중에 활성화할지 알 수 있습니다.
+
나중에 활성화하는 이유는 다음과 같습니다.

+
** * 시간 * -- 소프트웨어 및 펌웨어를 활성화하는 데 시간이 오래 걸릴 수 있으므로 I/O 로드가 가벼워질 때까지 기다려야 할 수 있습니다. 활성화 중에 컨트롤러가 페일오버되므로 업그레이드가 완료될 때까지 성능이 평소보다 저하될 수 있습니다.
** * 패키지 유형 * -- 다른 스토리지 어레이의 파일을 업그레이드하기 전에 한 스토리지 어레이에서 새 소프트웨어 및 펌웨어를 테스트할 수 있습니다.




이러한 구성요소는 SANtricity OS 컨트롤러 소프트웨어 업그레이드의 일부입니다.

* * 관리 소프트웨어 * -- System Manager는 스토리지 배열을 관리하는 소프트웨어입니다.
* * 컨트롤러 펌웨어 * -- 컨트롤러 펌웨어는 호스트와 볼륨 간의 I/O를 관리합니다.
* * 컨트롤러 NVSRAM * -- 컨트롤러 NVSRAM은 컨트롤러의 기본 설정을 지정하는 컨트롤러 파일입니다.
* * IOM 펌웨어 * -- I/O 모듈(IOM) 펌웨어는 컨트롤러와 드라이브 쉘프 간의 연결을 관리합니다. 또한 구성 요소의 상태를 모니터링합니다.
* * Supervisor 소프트웨어 * -- Supervisor 소프트웨어는 소프트웨어가 실행되는 컨트롤러의 가상 머신입니다.


업그레이드 프로세스의 일부로 호스트의 다중 경로/페일오버 드라이버 및/또는 HBA 드라이버도 업그레이드해야 호스트가 컨트롤러와 올바르게 상호 작용할 수 있습니다.

[NOTE]
====
이 경우에 해당하는지 확인하려면 를 참조하십시오 https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^].

====
스토리지 배열에 컨트롤러가 하나만 포함되어 있거나 다중 경로 드라이버가 설치되어 있지 않은 경우, 어플리케이션 오류를 방지하기 위해 스토리지 배열에 대한 I/O 작업을 중지합니다. 스토리지 어레이에 2개의 컨트롤러가 있는데 다중 경로 드라이버가 설치되어 있는 경우 I/O 작업을 중지할 필요가 없습니다.


CAUTION: 업그레이드가 진행되는 동안 스토리지 배열을 변경하지 마십시오.



== IOM 자동 동기화를 일시 중단하기 전에 알아야 할 내용은 무엇입니까?

IOM 자동 동기화를 일시 중단하면 다음에 SANtricity OS 컨트롤러 소프트웨어 업그레이드가 발생할 때 IOM 펌웨어가 업그레이드되지 않습니다.

일반적으로 컨트롤러 소프트웨어 및 IOM 펌웨어는 번들로 업그레이드됩니다. 인클로저에 보존하려는 IOM 펌웨어의 특수 빌드를 가지고 있는 경우 IOM 자동 동기화를 일시 중지할 수 있습니다. 그렇지 않으면 다음 번에 컨트롤러 소프트웨어 업그레이드를 수행할 때 컨트롤러 소프트웨어와 함께 번들로 제공되는 IOM 펌웨어로 되돌아갑니다.



== 펌웨어 업그레이드가 너무 느리게 진행되는 이유는 무엇입니까?

펌웨어 업그레이드 진행 상황은 시스템의 전체 로드에 따라 다릅니다.

드라이브 펌웨어의 온라인 업그레이드 중에 빠른 재구성 프로세스 중에 볼륨 전송이 발생하면 시스템은 전송된 볼륨에서 전체 재구성을 시작합니다. 이 작업에는 상당한 시간이 걸릴 수 있습니다. 실제 전체 재구성 시간은 재구성 작업 중 발생하는 I/O 활동 양, 볼륨 그룹의 드라이브 수, 리빌드 우선순위 설정 및 드라이브 성능 등 여러 요소에 따라 달라집니다.



== 드라이브 펌웨어를 업그레이드하기 전에 알아야 할 내용은 무엇입니까?

드라이브 펌웨어를 업그레이드하기 전에 다음 항목을 숙지하십시오.

* 예방 조치로 디스크 간 백업, 볼륨 복사(계획된 펌웨어 업그레이드의 영향을 받지 않는 볼륨 그룹에) 또는 원격 미러를 사용하여 데이터를 백업합니다.
* 새 펌웨어의 동작을 테스트하여 올바른 작동을 확인하기 위해 드라이브를 몇 개만 업그레이드할 수 있습니다. 새 펌웨어가 제대로 작동하는 경우 나머지 드라이브를 업그레이드하십시오.
* 오류가 발생한 드라이브가 있는 경우 펌웨어 업그레이드를 시작하기 전에 해결하십시오.
* 드라이브에서 오프라인 업그레이드를 수행할 수 있는 경우 드라이브와 연결된 모든 볼륨에 대한 I/O 작업을 중지합니다. I/O 작업이 중지되면 해당 볼륨과 관련된 구성 작업이 수행되지 않습니다.
* 드라이브 펌웨어를 업그레이드하는 동안 드라이브를 제거하지 마십시오.
* 드라이브 펌웨어를 업그레이드하는 동안 스토리지 배열의 구성을 변경하지 마십시오.




== 수행할 업그레이드 유형을 선택하려면 어떻게 해야 합니까?

풀 또는 볼륨 그룹의 상태에 따라 드라이브에서 수행할 업그레이드 유형을 선택합니다.

* * 온라인 *
+
풀 또는 볼륨 그룹이 중복성을 지원하고 최적의 경우 Online(온라인) 방법을 사용하여 드라이브 펌웨어를 업그레이드할 수 있습니다. 온라인 메소드는 스토리지 어레이가 I/O를 처리하는 동안 _ 펌웨어를 이러한 드라이브를 사용하여 연결된 볼륨에 다운로드합니다. 이러한 드라이브를 사용하여 연결된 볼륨에 대한 I/O를 중지할 필요가 없습니다. 이러한 드라이브는 드라이브에 연결된 볼륨으로 한 번에 하나씩 업그레이드됩니다. 드라이브가 풀 또는 볼륨 그룹에 할당되지 않은 경우 온라인 또는 오프라인 방법으로 해당 펌웨어를 업데이트할 수 있습니다. 드라이브 펌웨어를 업그레이드하는 온라인 방법을 사용할 경우 시스템 성능에 영향을 줄 수 있습니다.

* * 오프라인 *
+
풀 또는 볼륨 그룹이 이중화(RAID 0)를 지원하지 않거나 성능이 저하된 경우, 드라이브 펌웨어를 업그레이드하려면 오프라인 방법을 사용해야 합니다. Offline 방법은 모든 I/O 작업이 중지되어 있는 동안 _ 펌웨어를 해당 드라이브를 사용하는 연결된 볼륨으로 업그레이드합니다. 이러한 드라이브를 사용하여 연결된 볼륨에 대한 모든 I/O를 중지해야 합니다. 드라이브가 풀 또는 볼륨 그룹에 할당되지 않은 경우 온라인 또는 오프라인 방법으로 해당 펌웨어를 업데이트할 수 있습니다.


