---
permalink: sm-support/how-do-i-configure-the-delivery-method-for-autosupport.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, delivery, method, autosupport, 
summary: AutoSupport 기능은 기술 지원에 AutoSupport 디스패치를 전달하기 위한 프로토콜 HTTPS 및 SMTP를 지원합니다. 
---
= AutoSupport 기능의 전달 방법을 구성하려면 어떻게 합니까?
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 기능은 기술 지원에 AutoSupport 디스패치를 전달하기 위한 프로토콜 HTTPS 및 SMTP를 지원합니다.

.시작하기 전에
* AutoSupport 기능을 활성화해야 합니다. AutoSupport 페이지에서 활성화되어 있는지 여부를 확인할 수 있습니다.
* 네트워크에 DNS 서버가 설치 및 구성되어 있어야 합니다. DNS 서버 주소는 System Manager에서 구성해야 합니다(이 작업은 하드웨어 페이지에서 사용 가능).


.이 작업에 대해
다양한 프로토콜을 검토합니다.

* * HTTPS * -- HTTPS를 사용하여 대상 기술 지원 서버에 직접 연결할 수 있습니다. AutoSupport OnDemand 또는 원격 진단을 활성화하려면 AutoSupport 전송 방법을 HTTPS로 설정해야 합니다.
* * 이메일 * -- 이메일 서버를 AutoSupport 디스패치 전송 방법으로 사용할 수 있습니다.


[NOTE]
====
* HTTPS 및 이메일 방법의 차이점 *. SMTP를 사용하는 이메일 전달 방법은 HTTPS 전달 방법과 몇 가지 중요한 차이가 있습니다. 먼저, 이메일 방법에 대한 디스패치 크기는 5MB로 제한되며, 이는 일부 ASUP 데이터 수집이 디스패치되지 않음을 의미합니다. 둘째, AutoSupport OnDemand 기능은 HTTPS 전달 방법에서만 사용할 수 있습니다.

====
.단계
. 지원 [지원 센터 > AutoSupport] 탭을 선택합니다.
. AutoSupport 제공 방법 구성 * 을 선택합니다.
+
디스패치 제공 방법이 나열된 대화 상자가 나타납니다.

. 원하는 전달 방법을 선택한 다음 해당 전달 방법에 대한 매개 변수를 선택합니다. 다음 중 하나를 수행합니다.
+
** HTTPS를 선택한 경우 다음 전달 매개 변수 중 하나를 선택합니다.
+
*** * 직접 * -- 이 전달 매개 변수는 기본 선택 항목입니다. 이 옵션을 선택하면 HTTPS 프로토콜을 사용하여 대상 기술 지원 시스템에 직접 연결할 수 있습니다.
*** * 프록시 서버를 통해 * -- 이 옵션을 선택하면 대상 기술 지원 시스템과의 연결을 설정하는 데 필요한 HTTP 프록시 서버 세부 정보를 지정할 수 있습니다. 호스트 주소와 포트 번호를 지정해야 합니다. 그러나 필요한 경우 호스트 인증 세부 정보(사용자 이름 및 암호)만 입력하면 됩니다.
*** * 프록시 자동 구성 스크립트(PAC)를 통해 * -- 프록시 자동 구성(PAC) 스크립트 파일의 위치를 지정합니다. PAC 파일을 사용하면 시스템이 대상 기술 지원 시스템과의 연결을 설정할 적절한 프록시 서버를 자동으로 선택할 수 있습니다.


** 이메일 을 선택한 경우 다음 정보를 입력합니다.
+
*** 메일 서버 주소는 정규화된 도메인 이름, IPv4 주소 또는 IPv6 주소입니다.
*** AutoSupport 디스패치 이메일의 보낸 사람 필드에 나타나는 이메일 주소입니다.
*** * 선택 사항. 구성 테스트를 수행하려는 경우. * AutoSupport 시스템이 테스트 디스패치를 받을 때 확인을 보내는 이메일 주소입니다.
*** 메시지를 암호화하려면 암호화 유형으로 * SMTPS * 또는 * STARTTLS * 를 선택한 다음 암호화된 메시지의 포트 번호를 선택합니다. 그렇지 않으면 * 없음 * 을 선택합니다.
*** 필요한 경우 보내는 보낸 사람과 메일 서버에서 인증을 위한 사용자 이름과 암호를 입력합니다.




. 지정된 전달 매개 변수를 사용하여 기술 지원 서버에 대한 연결을 테스트하려면 * Test Configuration * 을 클릭합니다. AutoSupport 온디맨드 기능을 활성화한 경우 AutoSupport OnDemand 디스패치 전달에 대한 연결도 테스트합니다.
+
구성 테스트에 실패하면 구성 설정을 확인하고 테스트를 다시 실행하십시오. 테스트가 계속 실패하면 기술 지원 부서에 문의하십시오.

. 저장 * 을 클릭합니다.

