---
permalink: sm-support/review-the-possible-software-and-firmware-upgrade-errors.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, software, firmware, upgrade, errors 
summary: 컨트롤러 소프트웨어 업그레이드 또는 드라이브 펌웨어 업그레이드 중에 오류가 발생할 수 있습니다. 
---
= 가능한 소프트웨어 및 펌웨어 업그레이드 오류를 검토합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러 소프트웨어 업그레이드 또는 드라이브 펌웨어 업그레이드 중에 오류가 발생할 수 있습니다.

[cols="25h,~,~"]
|===
| 펌웨어 다운로드 오류입니다 | 설명 | 권장 조치 


 a| 
할당된 드라이브에 오류가 발생했습니다
 a| 
스토리지 배열에 할당된 드라이브를 업그레이드하지 못했습니다.
 a| 
이 오류가 발생하는 한 가지 이유는 드라이브에 적절한 서명이 없을 수 있기 때문입니다. 영향을 받는 드라이브가 승인된 드라이브인지 확인합니다. 자세한 내용은 기술 지원 부서에 문의하십시오.

드라이브를 교체할 때 교체 드라이브의 용량이 교체 중인 드라이브의 용량보다 크거나 같은지 확인하십시오.

스토리지 배열이 I/O를 수신하는 동안 오류가 발생한 드라이브를 교체할 수 있습니다



 a| 
내장형 핫 스페어 드라이브
 a| 
드라이브가 핫 스페어로 표시되어 있고 볼륨 그룹에서 사용 중인 경우 펌웨어 업그레이드 프로세스가 실패합니다.
 a| 
펌웨어를 업그레이드하기 전에 이 오류 상태를 수정해야 합니다. System Manager를 시작하고 Recovery Guru를 사용하여 문제를 해결합니다.



 a| 
볼륨 그룹이 불완전합니다
 a| 
볼륨 그룹의 일부인 드라이브가 무시되거나 제거되거나 응답하지 않는 경우 불완전한 볼륨 그룹으로 간주됩니다. 볼륨 그룹이 불완전하면 펌웨어 업그레이드가 방지됩니다.
 a| 
하나 이상의 볼륨 그룹 또는 디스크 풀이 불완전하면 펌웨어를 업그레이드하기 전에 이 오류 조건을 수정해야 합니다. System Manager를 시작하고 Recovery Guru를 사용하여 문제를 해결합니다.



 a| 
현재 모든 볼륨 그룹에서 실행 중인 단독 작업(백그라운드 미디어/패리티 검사 제외
 a| 
볼륨에서 배타적 작업이 진행 중인 경우 펌웨어를 업그레이드할 수 없습니다.
 a| 
하나 이상의 배타적 작업이 진행 중인 경우 펌웨어를 업그레이드하기 전에 작업을 완료해야 합니다. System Manager를 사용하여 작업 진행률을 모니터링합니다.



 a| 
볼륨이 누락되었습니다
 a| 
볼륨이 없는 경우 펌웨어를 업그레이드할 수 없습니다.
 a| 
펌웨어를 업그레이드하기 전에 누락된 볼륨 상태를 수정해야 합니다. System Manager를 시작하고 Recovery Guru를 사용하여 문제를 해결합니다.



 a| 
두 컨트롤러 중 하나가 Optimal(최적) 이외의 상태입니다
 a| 
두 컨트롤러 중 하나가 Optimal(최적) 이외의 상태인 경우 펌웨어를 업그레이드할 수 없습니다.
 a| 
스토리지 어레이 컨트롤러 중 하나에 주의가 필요합니다. 펌웨어를 업그레이드하기 전에 이 상태를 수정해야 합니다. System Manager를 시작하고 Recovery Guru를 사용하여 문제를 해결합니다.



 a| 
SPM 데이터베이스 컨트롤러 확인 실패
 a| 
스토리지 파티션 매핑 데이터베이스가 손상되어 펌웨어를 업그레이드할 수 없습니다.
 a| 
컨트롤러에서 스토리지 파티션 매핑 데이터베이스 오류가 발생했습니다. 이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
구성 데이터베이스 유효성 검사(스토리지 배열의 컨트롤러 버전에서 지원되는 경우)
 a| 
구성 데이터베이스가 손상되어 펌웨어를 업그레이드할 수 없습니다.
 a| 
컨트롤러에서 구성 데이터베이스 오류가 발생했습니다. 이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
Mel 관련 검사
 a| 
이벤트 로그에 오류가 있어 펌웨어를 업그레이드할 수 없습니다.
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
지난 7일 동안 10개 이상의 DDE 정보 또는 중요 MEL 이벤트가 보고되었습니다
 a| 
최근 7일 동안 보고된 DDE 정보 또는 중요 MEL 이벤트가 10개를 초과하여 펌웨어를 업그레이드할 수 없습니다.
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
지난 7일 동안 2개 이상의 2c 페이지 주요 MEL 이벤트가 보고되었습니다
 a| 
최근 7일 동안 보고된 2페이지 이상의 2c 중요 MEL 이벤트가 있으므로 펌웨어를 업그레이드할 수 없습니다.
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
최근 7일 동안 성능이 저하된 드라이브 채널 중요 MEL 이벤트가 2개 이상 보고되었습니다
 a| 
최근 7일 동안 성능이 저하된 드라이브 채널 중요 MEL 이벤트가 2개 이상 보고되었기 때문에 펌웨어를 업그레이드할 수 없습니다.
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
지난 7일 동안 4개 이상의 중요한 MEL 항목이 있습니다
 a| 
최근 7일 동안 보고된 중요 이벤트 로그 항목이 4개 이상 있으므로 펌웨어를 업그레이드할 수 없습니다.
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
유효한 관리 IP 주소가 필요합니다.
 a| 
이 작업을 수행하려면 유효한 컨트롤러 IP 주소가 필요합니다.
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
명령을 사용하려면 각 컨트롤러에 대한 액티브 관리 IP 주소가 필요합니다.
 a| 
이 작업을 수행하려면 스토리지 어레이와 연결된 각 컨트롤러의 컨트롤러 IP 주소가 필요합니다.
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
처리되지 않은 다운로드 파일 형식이 반환되었습니다.
 a| 
지정된 다운로드 파일이 지원되지 않습니다.
 a| 
이 문제를 해결하려면 기술 지원 부서에 문의하십시오.



 a| 
펌웨어 다운로드 업로드 절차 중 오류가 발생했습니다.
 a| 
컨트롤러가 요청을 처리할 수 없기 때문에 펌웨어를 다운로드하지 못했습니다. 스토리지 배열이 적합한지 확인하고 작업을 다시 시도하십시오.
 a| 
스토리지 어레이가 최적화되었는지 확인한 후 이 오류가 다시 발생하면 기술 지원 부서에 문의하여 이 문제를 해결하십시오.



 a| 
펌웨어 활성화 절차 중 오류가 발생했습니다.
 a| 
컨트롤러가 요청을 처리할 수 없기 때문에 펌웨어를 활성화하지 못했습니다. 스토리지 배열이 적합한지 확인하고 작업을 다시 시도하십시오.
 a| 
스토리지 어레이가 최적화되었는지 확인한 후 이 오류가 다시 발생하면 기술 지원 부서에 문의하여 이 문제를 해결하십시오.



 a| 
컨트롤러 \{0}의 재부팅을 기다리는 동안 시간 제한에 도달했습니다.
 a| 
재부팅 후 관리 소프트웨어가 컨트롤러 \{0}에 다시 연결할 수 없습니다. 스토리지 시스템에 대한 운영 접속 경로가 있는지 확인하고 성공적으로 완료되지 않은 경우 작업을 다시 시도하십시오.
 a| 
스토리지 어레이가 최적화되었는지 확인한 후 이 오류가 다시 발생하면 기술 지원 부서에 문의하여 이 문제를 해결하십시오.

|===
System Manager의 Recovery Guru를 사용하여 이러한 조건 중 일부를 해결할 수 있습니다. 그러나 일부 조건에서는 기술 지원 팀에 문의해야 할 수 있습니다. 최신 컨트롤러 펌웨어 다운로드에 대한 정보는 스토리지 어레이에서 확인할 수 있습니다. 이 정보는 기술 지원 부서에서 펌웨어 업그레이드 및 다운로드를 방해하는 오류 조건을 이해하는 데 도움이 됩니다.
