---
permalink: sm-support/schedule-autosupport-dispatches.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, schedule, autosupport, dispatches 
summary: System Manager는 AutoSupport 디스패치에 대한 기본 일정을 자동으로 생성합니다. 원하는 경우 자신의 일정을 지정할 수 있습니다. 
---
= AutoSupport 디스패치를 예약합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity System Manager에서 AutoSupport 디스패치에 대한 기본 일정을 자동으로 생성합니다. 원하는 경우 자신의 일정을 지정할 수 있습니다.

.시작하기 전에
AutoSupport 기능을 활성화해야 합니다. AutoSupport 페이지에서 활성화되어 있는지 여부를 확인할 수 있습니다.

.이 작업에 대해
* * 일일 시간 * -- 매일 디스패치는 사용자가 지정한 시간 범위 동안 수집되어 매일 발송됩니다. System Manager는 범위 내에서 임의의 시간을 선택합니다. 모든 시간은 UTC(협정 세계시)로 스토리지의 현지 시간과 다를 수 있습니다. 스토리지의 현지 시간을 UTC로 변환해야 합니다.
* * Weekly Day * -- 매주 디스패치가 수집되어 일주일에 한 번 발송됩니다. System Manager는 사용자가 지정한 일 중에서 임의의 날짜를 선택합니다. 주별 디스패치를 허용하지 않을 요일을 선택 취소합니다. System Manager는 허용되는 일 중에서 임의의 일을 선택합니다.
* * Weekly Time * -- 매주 디스패치는 사용자가 지정한 시간 범위 동안 매주 한 번 수집 및 전송됩니다. System Manager는 범위 내에서 임의의 시간을 선택합니다. 모든 시간은 UTC(협정 세계시)로 스토리지의 현지 시간과 다를 수 있습니다. 스토리지의 현지 시간을 UTC로 변환해야 합니다.


.단계
. 지원 [지원 센터 > AutoSupport] 탭을 선택합니다.
. AutoSupport 디스패치 예약 * 을 선택합니다.
+
AutoSupport 디스패치 예약 마법사가 나타납니다.

. 마법사의 단계를 따릅니다.

