---
permalink: sm-support/upgrade-controller-software-and-firmware.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrade, software, firmware 
summary: '스토리지 어레이의 소프트웨어 및 선택적으로 IOM 펌웨어 및 NVSRAM(Nonvolatile Static Random Access Memory)을 업그레이드하여 최신 기능 및 버그 수정을 확인할 수 있습니다.' 
---
= 컨트롤러 소프트웨어 및 펌웨어를 업그레이드합니다
:allow-uri-read: 


[role="lead"]
스토리지 어레이의 소프트웨어 및 선택적으로 IOM 펌웨어 및 NVSRAM(Nonvolatile Static Random Access Memory)을 업그레이드하여 최신 기능 및 버그 수정을 가할 수 있습니다.

.시작하기 전에
* IOM 펌웨어를 업그레이드할지 여부를 알고 있습니다.
+
일반적으로 모든 구성 요소를 동시에 업그레이드해야 합니다. 하지만 SANtricity OS 소프트웨어 업그레이드의 일부로 업그레이드하지 않으려는 경우 또는 기술 지원 부서에서 IOM 펌웨어를 다운그레이드하도록 지시한 경우(명령줄 인터페이스를 사용하여 펌웨어를 다운그레이드할 수만 있음) IOM 펌웨어를 업그레이드하지 않을 수도 있습니다.

* 컨트롤러 NVSRAM 파일을 업그레이드할지 여부를 알 수 있습니다.
+
일반적으로 모든 구성 요소를 동시에 업그레이드해야 합니다. 그러나 파일이 패치되었거나 사용자 정의 버전이고 덮어쓰지 않으려는 경우 컨트롤러 NVSRAM 파일을 업그레이드하지 않을 수 있습니다.

* 지금 또는 나중에 OS 업그레이드를 활성화할지 여부를 알 수 있습니다.
+
나중에 활성화하는 이유는 다음과 같습니다.

+
** * 시간 * -- 소프트웨어 및 펌웨어를 활성화하는 데 시간이 오래 걸릴 수 있으므로 I/O 로드가 가벼워질 때까지 기다려야 할 수 있습니다. 활성화 중에 컨트롤러가 페일오버되므로 업그레이드가 완료될 때까지 성능이 평소보다 저하될 수 있습니다.
** * 패키지 유형 * -- 다른 스토리지 어레이의 파일을 업그레이드하기 전에 한 스토리지 어레이에서 새 소프트웨어 및 펌웨어를 테스트할 수 있습니다.


* 보안이 설정되지 않은 드라이브로부터 전환할지 또는 드라이브 보안을 위해 외부 키 관리 서버(KMS)를 사용하기 위해 내부적으로 보안된 드라이브로부터 전환할지 여부를 알 수 있습니다.
* 스토리지 시스템에서 역할 기반 액세스 제어를 사용할지 여부를 알 수 있습니다.


.이 작업에 대해
OS 소프트웨어 파일만 업그레이드하거나 컨트롤러 NVSRAM 파일만 업그레이드하도록 선택할 수 있으며 두 파일을 모두 업그레이드하도록 선택할 수도 있습니다.

기술 지원 부서에서 지시한 경우에만 이 작업을 수행하십시오.

[CAUTION]
====
* 데이터 손실 또는 스토리지 배열 손상 위험 * -- 업그레이드 중에 스토리지 배열을 변경하지 마십시오. 스토리지 어레이에 대한 전원을 유지합니다.

====
.단계
. 스토리지 배열에 컨트롤러가 하나만 포함되어 있거나 다중 경로 드라이버가 설치되어 있지 않은 경우, 어플리케이션 오류를 방지하기 위해 스토리지 배열에 대한 I/O 작업을 중지합니다. 스토리지 어레이에 2개의 컨트롤러가 있는데 다중 경로 드라이버가 설치되어 있는 경우 I/O 작업을 중지할 필요가 없습니다.
. 메뉴 선택: 지원 [업그레이드 센터].
. Support 사이트에서 관리 클라이언트로 새 파일을 다운로드합니다.
+
.. 지원 웹 사이트를 시작하려면 * NetApp Support * 를 클릭합니다.
.. 지원 웹 사이트에서 * 다운로드 * 탭을 클릭한 다음 * 다운로드 * 를 선택합니다.
.. E-Series SANtricity OS 컨트롤러 소프트웨어 * 를 선택합니다.
.. 나머지 지침을 따릅니다.


+
[NOTE]
====
버전 8.42 이상에서는 디지털 서명된 펌웨어가 필요합니다. 서명되지 않은 펌웨어를 다운로드하려고 하면 오류가 표시되고 다운로드가 중단됩니다.

====
. 현재 IOM 펌웨어를 업그레이드하지 않으려면 * IOM 자동 동기화 일시 중지 * 를 클릭합니다.
+
단일 컨트롤러가 있는 스토리지 어레이를 사용하는 경우 IOM 펌웨어가 업그레이드되지 않습니다.

. SANtricity OS 소프트웨어 업그레이드 아래에서 * 업그레이드 시작 * 을 클릭합니다.
+
SANtricity OS 소프트웨어 업그레이드 대화 상자가 나타납니다.

. 업그레이드 프로세스를 시작하려면 하나 이상의 파일을 선택하십시오.
+
.. 찾아보기 * 를 클릭하고 지원 웹 사이트에서 다운로드한 OS 소프트웨어 파일을 탐색하여 SANtricity OS 소프트웨어 파일을 선택합니다.
.. [찾아보기] * 를 클릭하고 지원 사이트에서 다운로드한 NVSRAM 파일로 이동하여 컨트롤러 NVSRAM 파일을 선택합니다. 컨트롤러 NVSRAM 파일의 파일 이름은 N2800-830000-000.DLP와 유사합니다.


+
이러한 작업은 다음과 같이 수행됩니다.

+
** 기본적으로 현재 스토리지 배열 구성과 호환되는 파일만 표시됩니다.
** 업그레이드할 파일을 선택하면 파일 이름과 크기가 나타납니다.


. * 선택 사항: * 업그레이드할 SANtricity OS 소프트웨어 파일을 선택한 경우 지금 파일 전송 * 확인란을 선택하여 활성화하지 않고 컨트롤러로 파일을 전송할 수 있습니다(나중에 업그레이드 활성화) *.
. 시작 * 을 클릭하고 작업을 수행할지 확인합니다.
+
업그레이드 전 상태 점검 중에는 작업을 취소할 수 있지만 전송 또는 활성화 중에는 취소할 수 없습니다.

. * 선택 사항: * 업그레이드된 항목 목록을 보려면 * 로그 저장 * 을 클릭합니다.
+
파일은 브라우저의 다운로드 폴더에 drive_upgrade_log-timestamp.txt라는 이름으로 저장됩니다.



.작업을 마친 후
* 하드웨어 페이지에 모든 구성 요소가 나타나는지 확인합니다.
* 소프트웨어 및 펌웨어 인벤토리 대화 상자(지원 [업그레이드 센터] 메뉴로 이동한 다음 * 소프트웨어 및 펌웨어 인벤토리 * 링크를 클릭하여 소프트웨어 및 펌웨어 버전을 확인합니다.
* 컨트롤러 NVSRAM을 업그레이드한 경우 기존 NVSRAM에 적용한 모든 사용자 정의 설정은 활성화 과정 중에 손실됩니다. 활성화 프로세스가 완료된 후 NVSRAM에 사용자 정의 설정을 다시 적용해야 합니다.

