---
permalink: sm-support/use-script-editor.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, script editor, script file, execute script 
summary: 스크립트 편집기를 사용하여 스크립트 파일을 생성 또는 편집하고, 스크립트 파일을 스토리지 관리 스테이션의 로컬 디스크에 저장하거나, 디스크에서 스크립트 파일을 로드할 수 있습니다. 
---
= 스크립트 편집기 사용
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스크립트 편집기를 사용하여 스크립트 파일을 생성 또는 편집하고, 스크립트 파일을 스토리지 관리 스테이션의 로컬 디스크에 저장하거나, 디스크에서 스크립트 파일을 로드할 수 있습니다.

.시작하기 전에
스크립트 편집기는 스토리지 시스템과 통신하여 스크립트 구문 검사 및 명령 실행을 가능하게 합니다. 스크립트 편집기에 입력된 스크립트 명령은 일반적으로 스토리지 시스템에서 실행됩니다.

스크립트 편집기는 창에 두 가지 보기를 제공합니다.

* 편집기 창 – 스크립트 명령을 입력하거나 편집할 수 있는 영역을 제공합니다.
* 출력 창 – 검증 또는 실행 결과를 표시합니다. 구분 막대가 창을 편집 창과 출력 창으로 나눕니다.
* 스크립트 편집기는 컨트롤러 펌웨어, NVSRAM 또는 드라이브 펌웨어 업그레이드와 같이 입력 파일이 필요한 명령을 지원하지 않습니다.
* 스크립트 편집기는 출력 파일을 생성하는 명령을 지원합니다.
* 클라이언트에서 실행되어야 하는 명령이 몇 가지 있습니다(클라이언트 측 명령).
+
** 이번 릴리스에서 지원되는 클라이언트 측 명령은  `on error stop`와  `on error continue`뿐입니다.
** 스크립트 편집기에서 다른 클라이언트 측 명령을 실행하려고 하면 오류가 발생합니다.






== 스크립트 편집기를 엽니다

.단계
. 왼쪽 패널에서 menu:Support[Script editor]를 선택합니다.
+
다음 표에는 스크립트 편집기에서 사용할 수 있는 파일 옵션이 나열되어 있습니다.

+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 작업 | 조치 


 a| 
새 스크립트를 엽니다
 a| 
.. 기존 스크립트 파일을 스크립트 편집기에 업로드하려면 *Load script file*을 클릭하십시오.
+
스크립트 편집기는 선택한 스크립트 파일을 편집기 창에서 엽니다.





 a| 
스크립트 명령 구문을 확인합니다
 a| 
.. 편집기 창에서 현재 스크립트의 구문을 확인하려면 *구문 검사*를 클릭하십시오.
+
스크립트 편집기는 스크립트 파일의 명령문을 한 줄씩 분석하여 구문이 올바른지 확인합니다. 구문 오류가 있는 경우 출력 창에 오류가 발생한 줄 번호와 오류 설명이 표시됩니다.

+
Script 편집기에서 구문 오류가 발생하면 해당 스크립트에 대한 추가 구문 검증은 수행되지 않습니다.

+
구문 오류를 수정하고 *Syntax Check*를 다시 실행하여 오류 수정 사항을 확인하고 스크립트의 나머지 구문도 검사하십시오.





 a| 
스크립트 실행
 a| 
.. *Execute Script*를 클릭하여 편집기 창에서 현재 스크립트를 실행합니다.
+
스크립트 편집기는 구문 검사 작업을 시작한 다음 입력 파일의 각 스크립트 명령에 대해 스토리지 시스템 컨트롤러에서 명령 실행을 수행합니다.

+
스크립트 편집기에서 구문 오류가 발생하면 실행을 중지하고 오류 메시지를 표시합니다.

+
오류를 수정하고 *구문 검사*를 다시 실행하여 오류 수정을 확인합니다.

+

NOTE: 실행 오류가 발생할 경우, 포함된 `On Error` 스크립트 명령에 따라 스크립트 실행이 중단될 수 있습니다.  `On Error Stop` 명령은 실행 오류가 발생하면 스크립트 실행을 중지합니다.  `On Error
Continue` 명령은 실행 오류가 발생하더라도 스크립트 실행을 계속하도록 합니다. 이 명령이 기본 설정입니다.





 a| 
기존 스크립트 편집
 a| 
.. 기존 스크립트 파일을 스크립트 편집기에 업로드하려면 *Load script file*을 클릭하십시오.
.. 편집기 창에서 스크립트를 필요한 대로 변경합니다.




 a| 
스크립트를 로컬 파일에 저장합니다
 a| 
.. 스크립트 창의 변경 사항을 새 스크립트 파일로 다운로드하려면 *스크립트 파일 저장*을 클릭합니다.




 a| 
스크립트 편집기의 편집기 창에서 텍스트 지우기
 a| 
.. 편집기 창의 텍스트를 지우려면 *Clear editor*를 클릭하세요.




 a| 
출력 결과를 로컬 파일에 저장합니다
 a| 
.. 출력 창의 내용을 새 파일로 다운로드하려면 *결과 저장*을 클릭하십시오.


|===
====




=== 스크립트 편집기에서 스크립트 작성

.시작하기 전에
Script editor를 사용하여 스크립트 명령을 작성할 때는 다음 지침을 준수하십시오. * 모든 명령문은 세미콜론(;)으로 끝내야 합니다. * 각 기본 명령과 해당 기본 매개변수 및 보조 매개변수는 공백으로 구분해야 합니다. * Script editor에서 매개변수는 대소문자를 구분하지 않습니다. * 각 명령문은 한 줄에 작성해야 합니다. * 스크립트에 주석을 추가하여 자신과 향후 사용자가 명령문의 목적을 더 쉽게 이해할 수 있도록 하십시오.

.단계
. 여러 줄로 된 주석은  `/*` 및  `*/` 문자로 묶으세요.
+
스크립트 엔진이 시작 주석 표기법과 종료 주석 표기법을 모두 찾지 못하면 오류 메시지가 나타나고 스크립트 실행이 종료됩니다.

. 한 줄짜리 주석은 슬래시 두 개(`//`로 시작하고 줄 바꿈 문자로 끝내며, *Enter* 키를 눌러 삽입할 수 있습니다.
+
스크립트 엔진이 주석 처리 후 스크립트에서 줄 끝 문자를 찾지 못하면 오류 메시지가 표시되고 스크립트 실행이 종료됩니다.

+
이 오류는 일반적으로 스크립트 끝에 주석을 배치하고 *Enter* 키를 누르는 것을 잊었을 때 발생합니다.

.  `show` 구문을 사용하면 스크립트 실행 중에 편집기 창에 표시될 주석을 스크립트에 삽입할 수 있습니다.
+
 `show` 구문은 스크립트 디버깅에 유용합니다.

+
스크립트에 `show setting controller mode` 문을 포함하면 스크립트 실행 중 이 줄이 처리될 때 출력 창에 다음 줄이 나타납니다.

+
[listing]
----
setting controller mode
----




=== 스크립트 실행 결과 해석

스크립트 실행 중에 출력 창에 다음으로 시작하는 메시지가 나타납니다.

[listing]
----
Executing script...
----
구문 분석 단계에서 오류가 발생하면 오류 메시지가 출력 창에 표시됩니다. 오류 메시지에는 줄 번호, 열 번호 및 구문 오류에 대한 설명이 포함됩니다. 다음은 구문 오류 메시지의 예입니다.

스크립트에 다음 문을 입력하면:

`set controller[a] mod = passive;`

출력 창에는 다음과 같은 구문 오류가 표시됩니다.

[listing]
----
Encountered "mod" at line 2, column 19
Was expecting one of...
"mode"...
"availability"...
"NVSRAMbyte"...
----
스크립트 실행 중 오류가 발생하면 출력 창에 명령이 실패했음을 알리는 메시지와 오류에 대한 설명이 표시됩니다.

예를 들어 스크립트에 다음 문을 입력하면 다음과 같습니다.

`set volume [three] userLabel="OneOne";`

다음 출력 창에 결과 오류가 표시됩니다. 스토리지 시스템이 응답하지 않는 상태였기 때문에 명령을 보낼 수 없었습니다.

[listing]
----
Unable to change the volume user label using the Set Volume command at line 1
Error - 1 - Could not communicate with the storage array to complete this request.
----

NOTE: 스토리지 어레이와의 통신 실패를 포함한 특정 실행 오류는 항상 스크립트 실행을 중단시킵니다. 이러한 경우에는 `On Error Continue` 구문을 사용하더라도 실행이 중지됩니다.

.결과
스크립트를 실행한 후 출력 창을 검토하여 성공 또는 오류를 확인하십시오.
