---
permalink: sm-support/view-storage-array-profile.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, storage, array, profile 
summary: 스토리지 배열 프로파일은 스토리지 배열의 모든 구성 요소와 속성에 대한 설명을 제공합니다. 
---
= SANtricity System Manager에서 스토리지 어레이 프로필 보기
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 배열 프로파일은 스토리지 배열의 모든 구성 요소와 속성에 대한 설명을 제공합니다.

.이 작업에 대해
스토리지 배열 프로파일을 복구 과정에서 보조 도구로 사용하거나 스토리지 배열의 현재 구성에 대한 개요로 사용할 수 있습니다. 스토리지 배열 프로파일의 복사본을 관리 클라이언트에 저장하고 스토리지 배열 프로파일의 하드 복사본을 스토리지 배열에 보관할 수 있습니다. 구성이 변경되는 경우 스토리지 배열 프로파일의 새 복사본을 생성합니다.

.단계
. 지원 [지원 센터 > 지원 리소스] 탭을 선택합니다.
. 아래로 스크롤하여 * 자세한 스토리지 배열 정보 시작 * 을 선택한 다음 * 스토리지 배열 프로파일 * 을 선택합니다.
+
보고서가 화면에 나타납니다.

+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 섹션을 참조하십시오 | 설명 


 a| 
스토리지
 a| 
에는 구성할 수 있는 모든 옵션과 스토리지 배열에 대한 시스템 정적 옵션이 나와 있습니다. 이러한 옵션에는 컨트롤러 수, 드라이브 쉘프, 드라이브, 디스크 풀, 볼륨 그룹, 볼륨 및 핫 스페어 드라이브, 허용되는 최대 드라이브 쉘프, 드라이브, SSD(Solid State Disk) 및 볼륨 수, 스냅샷 그룹 수, 스냅샷 이미지, 스냅샷 볼륨 및 일관성 그룹, 기능에 대한 정보, 펌웨어 버전에 대한 정보, 섀시 일련 번호에 대한 정보, AutoSupport 상태 및 AutoSupport 일정 정보 자동 지원 데이터 수집 및 예약된 지원 데이터 수집 설정, 스토리지 어레이 WWID(World-Wide Identifier), 미디어 검색 및 캐시 설정



 a| 
스토리지
 a| 
에는 스토리지 배열의 모든 스토리지 장치 목록이 나와 있습니다. 스토리지 배열 구성에 따라 Storage 섹션에 이러한 하위 섹션이 표시될 수 있습니다.

** * 디스크 풀 * -- 스토리지 배열의 모든 디스크 풀 목록을 표시합니다.
** * 볼륨 그룹 * -- 스토리지 배열의 모든 볼륨 그룹 목록을 표시합니다. 볼륨 및 사용 가능한 용량이 생성된 순서대로 나열됩니다.
** * Volumes * -- 스토리지 배열의 모든 볼륨 목록을 표시합니다. 나열된 정보에는 볼륨 이름, 볼륨 상태, 용량, RAID 레벨, 볼륨 그룹 또는 디스크 풀, 드라이브 유형 및 추가 세부 정보가 포함됩니다.
** * Missing Volumes * -- 현재 누락된 상태가 있는 스토리지 배열의 모든 볼륨 목록을 표시합니다. 나열된 정보에는 누락된 각 볼륨에 대한 WWID(World Wide Identifier)가 포함됩니다.




 a| 
복사 서비스
 a| 
에는 스토리지 시스템에 사용되는 모든 복제본 서비스 목록이 나와 있습니다. 스토리지 배열 구성에 따라 Copy Services 섹션에 다음과 같은 하위 섹션이 표시될 수 있습니다.

** * Volume Copies * -- 스토리지 배열의 모든 복제 쌍 목록을 표시합니다. 나열된 정보에는 복사본 수, 복사본 쌍 이름, 상태, 시작 타임스탬프 및 추가 세부 정보가 포함됩니다.
** * 스냅샷 그룹 * -- 스토리지 배열의 모든 스냅샷 그룹 목록을 표시합니다.
** * 스냅샷 이미지 * -- 스토리지 배열의 모든 스냅샷 목록을 표시합니다.
** * Snapshot Volumes * -- 스토리지 배열의 모든 스냅샷 볼륨 목록을 표시합니다.
** * 정합성 보장 그룹 * -- 스토리지 배열의 모든 정합성 보장 그룹 목록을 표시합니다.
** * 구성원 볼륨 * -- 스토리지 배열의 모든 정합성 보장 그룹 구성원 볼륨 목록을 표시합니다.
** * 미러 그룹 * -- 미러링된 모든 볼륨의 목록을 표시합니다.
** * Reserved Capacity * -- 스토리지 배열의 모든 예약된 용량 볼륨 목록을 표시합니다.




 a| 
호스트 할당
 a| 
에는 스토리지 배열의 호스트 할당 목록이 나와 있습니다. 나열된 정보에는 볼륨 이름, LUN(논리 유닛 번호), 컨트롤러 ID, 호스트 이름 또는 호스트 클러스터 이름, 볼륨 상태가 포함됩니다. 여기에 나열된 추가 정보에는 토폴로지 정의 및 호스트 유형 정의가 포함됩니다.



 a| 
하드웨어
 a| 
에는 스토리지 배열의 모든 하드웨어 목록이 나와 있습니다. 스토리지 배열 구성에 따라 Hardware 섹션에 이러한 하위 섹션이 표시될 수 있습니다.

** * 컨트롤러 * -- 스토리지 어레이에 있는 모든 컨트롤러의 목록을 표시하며 컨트롤러 위치, 상태 및 구성을 포함합니다. 또한 드라이브 채널 정보, 호스트 채널 정보 및 이더넷 포트 정보도 포함됩니다.
** * 드라이브 * -- 스토리지 배열의 모든 드라이브 목록을 표시합니다. 쉘프 ID, 문서함 ID, 슬롯 ID 순서로 드라이브가 나열됩니다. 나열된 정보에는 쉘프 ID, 문서함 ID, 슬롯 ID, 상태, 물리적 용량, 미디어 유형, 인터페이스 유형, 현재 데이터 속도, 제품 ID 및 각 드라이브의 펌웨어 버전입니다. 드라이브 섹션에는 드라이브 채널 정보, 핫 스페어 적용 범위 정보 및 마모 수명 정보(SSD 드라이브 전용)도 포함되어 있습니다. 마모 수명 정보에는 사용된 내구성 비율, 즉 현재까지 SSD 드라이브에 기록된 데이터의 양을 이론적인 드라이브의 총 쓰기 한계로 나눈 값이 포함됩니다.
** * 드라이브 채널 * -- 스토리지 배열의 모든 드라이브 채널에 대한 정보를 표시합니다. 나열된 정보에는 채널 상태, 링크 상태(해당하는 경우), 드라이브 수 및 누적 오류 수가 포함됩니다.
** * 쉘프 * -- 스토리지 어레이의 모든 쉘프에 대한 정보를 표시합니다. 드라이브 유형과 쉘프의 각 구성 요소에 대한 상태 정보가 표시됩니다. 쉘프 구성 요소에는 배터리 팩, SFP(Small Form-factor Pluggable) 트랜시버, 전원 팬 캐니스터 또는 IOM(Input/Output Module) 캐니스터가 포함될 수 있습니다. 스토리지 배열에 보안 키를 사용하는 경우 하드웨어 섹션에는 보안 키 식별자도 표시됩니다.




 a| 
피처
 a| 
에는 설치된 기능 팩 목록과 호스트 또는 호스트 클러스터당 허용되는 최대 스냅샷 그룹, 스냅샷(레거시) 및 볼륨 수가 나와 있습니다. Features(기능) 섹션에 있는 정보에는 Drive Security(드라이브 보안), 즉 스토리지 어레이가 보안이 설정되어 있는지 또는 보안이 비활성화되어 있는지 여부도 포함됩니다.

|===
====
. 스토리지 배열 프로파일을 검색하려면 * 찾기 * 텍스트 상자에 검색어를 입력한 다음 * 찾기 * 를 클릭합니다.
+
일치하는 모든 용어가 강조 표시됩니다. 모든 결과를 한 번에 하나씩 스크롤하려면 * 찾기 * 를 계속 클릭합니다.

. 스토리지 배열 프로파일을 저장하려면 * 저장 * 을 클릭합니다.
+
이 파일은 브라우저의 다운로드 폴더에 'storage-array-profile.txt'라는 이름으로 저장됩니다.


