---
permalink: sm-support/view-events-using-the-event-log.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, events, 
summary: 스토리지 어레이에서 발생한 이벤트의 기록 레코드를 제공하는 이벤트 로그를 볼 수 있습니다. 
---
= 이벤트 로그를 사용하여 이벤트를 봅니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 어레이에서 발생한 이벤트의 기록 레코드를 제공하는 이벤트 로그를 볼 수 있습니다.

.단계
. 메뉴 선택: 지원 [이벤트 로그].
+
이벤트 로그 페이지가 나타납니다.

+
.페이지 세부 정보
[%collapsible]
====
[cols="25h,~"]
|===
| 항목 | 설명 


 a| 
모두 보기 필드
 a| 
모든 이벤트와 위험 이벤트 및 경고 이벤트만 전환합니다.



 a| 
필터 필드
 a| 
이벤트를 필터링합니다. 특정 구성 요소, 특정 이벤트 등과 관련된 이벤트만 표시하는 데 유용합니다



 a| 
열 선택 아이콘
 a| 
볼 다른 열을 선택할 수 있습니다. 다른 열은 이벤트에 대한 추가 정보를 제공합니다.



 a| 
확인란을 선택합니다
 a| 
저장할 이벤트를 선택할 수 있습니다. 표 머리글의 확인란을 선택하면 모든 이벤트가 선택됩니다.



 a| 
날짜/시간 열
 a| 
컨트롤러 시계에 따라 이벤트의 날짜 및 시간 스탬프입니다.


NOTE: 이벤트 로그는 처음에 시퀀스 번호를 기반으로 이벤트를 정렬합니다. 일반적으로 이 순서는 날짜 및 시간과 일치합니다. 그러나 스토리지 어레이에서 두 컨트롤러 클럭의 동기화가 해제됩니다. 이 경우, 이벤트 및 표시된 날짜 및 시간과 관련하여 일부 인지된 비일관성이 이벤트 로그에 나타날 수 있습니다.



 a| 
우선 순위 열
 a| 
이러한 우선순위 값은 다음과 같습니다.

** * Critical * -- 스토리지 배열에 문제가 있습니다. 그러나 즉각적인 조치를 취하는 경우 데이터에 대한 액세스가 손실되는 것을 방지할 수 있습니다. 중요 이벤트는 경고 알림에 사용됩니다. 모든 중요 이벤트는 네트워크 관리 클라이언트(SNMP 트랩 사용) 또는 구성한 전자 메일 수신자에게 전송됩니다.
** * 경고 * -- 스토리지 배열의 성능과 복구 기능이 다른 오류에서 저하되어 오류가 발생했습니다.
** * 정보 * -- 스토리지 어레이와 관련된 중요하지 않은 정보입니다.




 a| 
부품 유형 열
 a| 
이벤트의 영향을 받는 구성 요소입니다. 구성 요소는 드라이브 또는 컨트롤러와 같은 하드웨어이거나 컨트롤러 펌웨어와 같은 소프트웨어일 수 있습니다.



 a| 
부품 위치 열
 a| 
스토리지 배열에 있는 구성 요소의 물리적 위치입니다.



 a| 
설명 열
 a| 
이벤트에 대한 설명입니다.

* 예 * -- '드라이브 쓰기 실패 - 재시도 횟수 초과'입니다



 a| 
시퀀스 번호 열
 a| 
스토리지 배열의 특정 로그 항목을 고유하게 식별하는 64비트 번호입니다. 이 숫자는 모든 새 이벤트 로그 항목에 대해 하나씩 증가합니다. 이 정보를 표시하려면 * 열 선택 * 아이콘을 클릭합니다.



 a| 
이벤트 유형 열
 a| 
기록된 이벤트의 각 유형을 식별하는 4자리 숫자 이 정보를 표시하려면 * 열 선택 * 아이콘을 클릭합니다.



 a| 
이벤트 특정 코드 열
 a| 
이 정보는 기술 지원 부서에서 사용합니다. 이 정보를 표시하려면 * 열 선택 * 아이콘을 클릭합니다.



 a| 
이벤트 범주 열
 a| 
** ** 오류** – 스토리지 배열의 구성요소에 장애가 발생했습니다(예: 드라이브 장애 또는 배터리 장애).
** ** 상태 변경** – 상태가 변경된 스토리지 배열의 요소(예: 볼륨이 최적 상태로 전환되었거나 컨트롤러가 오프라인 상태로 전환된 경우)
** ** 내부** – 사용자 작업이 필요하지 않은 내부 컨트롤러 작업(예: 컨트롤러가 당일 시작을 완료함)
** ** 명령** – 스토리지 배열에 대해 실행된 명령(예: 핫 스페어가 할당되었습니다.
** ** 오류** – 스토리지 배열에서 오류 상태가 감지되었습니다. 예를 들어, 컨트롤러가 캐시를 동기화 및 제거할 수 없거나 스토리지 배열에서 중복 오류가 감지되었습니다.
** ** 일반** – 다른 범주에 적합하지 않은 모든 이벤트. 이 정보를 표시하려면 ** 칼럼 선택** 아이콘을 클릭합니다.




 a| 
로그자 열
 a| 
이벤트를 기록한 컨트롤러의 이름입니다. 이 정보를 표시하려면 ** 칼럼 선택** 아이콘을 클릭합니다.

|===
====
. 스토리지 배열에서 새 이벤트를 검색하려면** 새로 고침** 을 클릭합니다.
+
이벤트가 로깅되고 이벤트 로그 페이지에 표시되려면 몇 분 정도 걸릴 수 있습니다.

. 이벤트 로그를 파일에 저장하려면 다음을 수행합니다.
+
.. 저장할 각 이벤트 옆에 있는 확인란을 선택합니다.
.. 저장 * 을 클릭합니다.
+
이 파일은 브라우저의 다운로드 폴더에 major-event-log-timestamp.log라는 이름으로 저장됩니다.



. 이벤트 로그에서 이벤트를 지우려면 다음을 수행합니다.
+
이벤트 로그는 이벤트를 새 이벤트로 바꾸기 전에 약 8,000개의 이벤트를 저장합니다. 이벤트를 유지하려면 이벤트를 저장하고 이벤트 로그에서 해당 이벤트를 지울 수 있습니다.

+
.. 먼저 이벤트 로그를 저장합니다.
.. 모두 지우기 * 를 클릭하고 작업을 수행할지 확인합니다.



