---
permalink: sm-support/view-unreadable-sectors-log.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, unreadable, sectors, log 
summary: 읽을 수 없는 섹터 로그를 저장하고 기술 지원 부서에 파일을 보내 분석할 수 있습니다. 
---
= SANtricity System Manager에서 읽을 수 없는 섹터 로그 보기
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
읽을 수 없는 섹터 로그를 저장하고 기술 지원 부서에 파일을 보내 분석할 수 있습니다.

.이 작업에 대해
읽을 수 없는 섹터 로그에는 복구할 수 없는 미디어 오류를 보고하는 드라이브로 인해 읽을 수 없는 섹터의 자세한 기록이 포함되어 있습니다. 정상적인 I/O 및 재구성 등의 수정 작업 중에 읽을 수 없는 섹터가 감지됩니다. 스토리지 어레이에서 읽을 수 없는 섹터가 감지되면 스토리지 어레이에 대한 주의 필요 경고가 나타납니다. Recovery Guru는 주의가 필요한 읽을 수 없는 섹터 상태를 구분합니다. 읽을 수 없는 섹터에 포함된 모든 데이터는 복구할 수 없으며 유실된 것으로 간주해야 합니다.

읽을 수 없는 섹터 로그는 최대 1,000개의 읽을 수 없는 섹터를 저장할 수 있습니다. 읽을 수 없는 섹터 로그가 1,000개 항목에 도달하면 다음 조건이 적용됩니다.

* 재구성 중에 읽을 수 없는 새로운 섹터가 감지되면 재구성이 실패하고 아무 항목도 기록되지 않습니다.
* I/O 중에 읽을 수 없는 새로운 섹터가 감지되면 I/O에 장애가 발생하고 항목이 기록되지 않습니다.
+
[NOTE]
====
이러한 동작에는 오버플로가 발생하기 전에 성공한 RAID 5 쓰기 및 RAID 6 쓰기가 포함됩니다.

====


[CAUTION]
====
* 데이터 손실 가능성 * -- 읽을 수 없는 섹터로부터 복구하는 것은 여러 가지 다른 방법이 수반될 수 있는 복잡한 절차입니다. 기술 지원 부서에서 지시한 경우에만 이 작업을 수행하십시오.

====
.단계
. 지원 [지원 센터 > 진단] 탭을 선택합니다.
. 읽을 수 없는 섹터 보기/지우기 * 를 선택합니다.
. 읽을 수 없는 섹터 로그 저장하기:
+
.. 표의 첫 번째 열에서 읽을 수 없는 섹터 로그를 저장할 개별 볼륨을 선택하거나(각 볼륨 옆의 확인란을 클릭) 모든 볼륨을 선택합니다(표 머리글에서 확인란 선택).
+
특정 볼륨을 찾으려면 * Filter * (필터 *) 상자에 원하는 열을 정렬하거나 문자를 입력합니다.

.. 저장 * 을 클릭합니다.


+
이 파일은 브라우저의 다운로드 폴더에 Unreadable-sectors.txt라는 이름으로 저장됩니다.

. 기술 지원 부서에서 읽을 수 없는 섹터 로그를 지우라고 지시하는 경우 다음 단계를 수행하십시오.
+
.. 표의 첫 번째 열에서 읽을 수 없는 섹터 로그를 지우려는 개별 볼륨을 선택하거나(각 볼륨 옆의 확인란을 클릭) 모든 볼륨을 선택합니다(표 머리글에서 확인란 선택).
.. 지우기 * 를 클릭하고 작업을 수행할지 확인합니다.



