---
permalink: sm-support/view-iscsi-statistics-packages-support.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, iscsi, statistics, packages 
summary: 스토리지 배열에 대한 iSCSI 연결에 대한 데이터를 볼 수 있습니다. 
---
= iSCSI 통계 패키지를 봅니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 배열에 대한 iSCSI 연결에 대한 데이터를 볼 수 있습니다.

.이 작업에 대해
System Manager는 이러한 유형의 iSCSI 통계를 표시합니다. 모든 통계는 읽기 전용이며 설정할 수 없습니다.


NOTE: System Manager에 표시되는 통계 유형은 스토리지 어레이에 사용할 수 있는 통계를 기반으로 합니다.

* * 이더넷 MAC 통계 * -- MAC(Media Access Control)에 대한 통계를 제공합니다. 또한 MAC는 실제 주소 또는 MAC 주소라는 주소 지정 메커니즘을 제공합니다. MAC 주소는 각 네트워크 어댑터에 할당된 고유한 주소입니다. MAC 주소는 하위 네트워크 내의 대상으로 데이터 패킷을 전송하는 데 도움이 됩니다.
* * 이더넷 TCP/IP 통계 * -- TCP(Transmission Control Protocol) 및 IP(Internet Protocol)인 TCP/IP에 대한 통계를 제공합니다. TCP를 사용하면 네트워크로 연결된 호스트의 응용 프로그램이 서로 연결을 만들어 데이터를 패킷으로 교환할 수 있습니다. IP는 패킷 교환 방식의 네트워크를 통해 데이터를 전달하는 데이터 지향 프로토콜입니다. IPv4 통계 및 IPv6 통계는 별도로 표시됩니다.
* * 이더넷 커널 통계 * -- iSCSI 장치의 플랫폼 커널 드라이버에 대한 통계를 제공합니다. 커널 통계는 TCP/IP 통계 옵션과 유사한 네트워크 데이터를 표시합니다. 그러나 커널 통계 데이터는 iSCSI 하드웨어에서 직접 수집되지 않고 플랫폼 커널 드라이버에서 수집됩니다.
* * 로컬 대상/초기자(프로토콜) 통계 * -- iSCSI 대상에 대한 통계를 표시합니다. iSCSI 타겟은 해당 스토리지 미디어에 대한 블록 수준 액세스를 제공하고 비동기 미러링 작업에서 이니시에이터로 사용될 때 스토리지 배열에 대한 iSCSI 통계를 표시합니다.
* * DCBX 작업 상태 통계 * -- 다양한 DCBX(Data Center Bridging Exchange) 기능의 작동 상태를 표시합니다.
* * LLDP TLV statistics * -- LLDP(Link Layer Discovery Protocol) TLV(Type Length Value) 통계를 표시합니다.
* * DCBX TLV 통계 * -- DCB(데이터 센터 브리징) 환경에서 스토리지 배열 호스트 포트를 식별하는 정보를 표시합니다. 이 정보는 식별 및 기능 목적으로 네트워크 피어와 공유됩니다.


각 통계를 원시 통계 또는 기준 통계로 볼 수 있습니다. 원시 통계는 컨트롤러가 시작된 이후 수집된 모든 통계입니다. 기준 통계는 기준 시간을 설정한 후 수집된 시점 통계입니다.

.단계
. 지원 [지원 센터 > 진단] 탭을 선택합니다.
. iSCSI 통계 패키지 보기 * 를 선택합니다.
. 탭을 클릭하여 다양한 통계 집합을 봅니다.
. 기준선을 설정하려면 * Set new baseline * 을 클릭합니다.
+
기준을 설정하면 통계 수집에 대한 새로운 시작 지점이 설정됩니다. 모든 iSCSI 통계에는 동일한 기준이 사용됩니다.


