---
permalink: sm-support/what-does-unreadable-sectors-data-show-me.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, unreadable, sectors, 
summary: 스토리지 배열의 드라이브에서 검색된 읽을 수 없는 섹터에 대한 자세한 데이터를 표시할 수 있습니다. 
---
= 읽을 수 없는 섹터 데이터는 무엇을 보여 줍니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 배열의 드라이브에서 검색된 읽을 수 없는 섹터에 대한 자세한 데이터를 표시할 수 있습니다.

읽을 수 없는 섹터 로그는 가장 최근의 읽을 수 없는 섹터를 먼저 보여줍니다. 이 로그에는 읽을 수 없는 섹터가 포함된 볼륨에 대한 다음 정보가 포함되어 있습니다. 필드를 정렬할 수 있습니다.

[cols="25h,~"]
|===
| 필드에 입력합니다 | 설명 


 a| 
영향을 받는 볼륨
 a| 
볼륨의 레이블을 표시합니다. 누락된 볼륨에 읽을 수 없는 섹터가 포함된 경우, 누락 볼륨에 대한 월드 와이드 식별자가 표시됩니다.



 a| 
논리 단위 번호(LUN)
 a| 
에는 볼륨의 LUN이 나와 있습니다. 볼륨에 LUN이 없으면 대화 상자에 NA가 표시됩니다.



 a| 
할당 대상
 a| 
에는 볼륨에 대한 액세스 권한이 있는 호스트 또는 호스트 클러스터가 나와 있습니다. 호스트, 호스트 클러스터 또는 기본 클러스터에서 볼륨에 액세스할 수 없는 경우 대화 상자에 NA가 표시됩니다.

|===
읽을 수 없는 섹터에 대한 추가 정보를 보려면 볼륨 옆에 있는 더하기 기호(+)를 클릭합니다.

[cols="25h,~"]
|===
| 필드에 입력합니다 | 설명 


 a| 
날짜/시간입니다
 a| 
읽을 수 없는 섹터가 감지된 날짜와 시간을 표시합니다.



 a| 
볼륨 논리적 블록 주소입니다
 a| 
볼륨의 LBA(논리 블록 주소)를 표시합니다.



 a| 
드라이브 위치
 a| 
에는 드라이브 쉘프, 서랍(드라이브 쉘프에 서랍이 있는 경우) 및 베이 위치가 나와 있습니다.



 a| 
드라이브 논리 블록 주소
 a| 
에서는 드라이브의 LBA를 보여 줍니다.



 a| 
실패 유형
 a| 
에서는 다음 오류 유형 중 하나를 보여 줍니다.

* * 물리적 * -- 물리적 미디어 오류입니다.
* * 논리 * -- 스트라이프의 다른 위치에서 읽기 오류가 발생하여 데이터를 읽을 수 없습니다. 예를 들어, 볼륨의 다른 위치에서 미디어 오류로 인해 읽을 수 없는 섹터가 있습니다.
* * 불일치 * -- 일관성 없는 중복 데이터.
* * Data Assurance * -- Data Assurance 오류입니다.


|===