---
permalink: sm-support/what-type-of-data-is-collected-through-autosupport.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, data, collected, autosupport, ASUP 
summary: AutoSupport 기능에는 이벤트 디스패치, 예약된 디스패치, 주문형 및 원격 진단 디스패치의 세 가지 표준 디스패치 유형이 있습니다. 
---
= AutoSupport 기능을 통해 수집되는 데이터 유형은 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 기능에는 이벤트 디스패치, 예약된 디스패치, 주문형 및 원격 진단 디스패치의 세 가지 표준 디스패치 유형이 있습니다.

AutoSupport 데이터에 사용자 데이터가 없습니다.

* * 이벤트 디스패치 *
+
기술 지원에 사전 알림이 필요한 이벤트가 시스템에서 발생할 경우 AutoSupport 기능은 자동으로 이벤트 트리거 디스패치를 보냅니다.

+
** 관리되는 스토리지 어레이에서 지원 이벤트가 발생할 때 발송됩니다.
** 이벤트가 발생한 시점의 스토리지 어레이에 대한 포괄적인 스냅샷이 포함됩니다.


* * 예약된 디스패치 *
+
AutoSupport 기능은 정기적으로 여러 개의 디스패치를 자동으로 전송합니다.

+
** * 일일 디스패치 * -- 사용자가 구성할 수 있는 시간 간격 동안 매일 한 번 발송됩니다. 현재 시스템 이벤트 로그 및 성능 데이터가 포함됩니다.
** * 주별 디스패치 * -- 사용자가 구성할 수 있는 시간 간격 및 일 동안 매주 한 번 발송됩니다. 구성 및 시스템 상태 정보를 포함합니다.


* * AutoSupport OnDemand 및 원격 진단 디스패치 *
+
** * AutoSupport OnDemand * -- 문제 해결을 위해 필요한 경우 기술 지원 부서에서 이전 AutoSupport 디스패치의 재전송을 요청할 수 있습니다. 모든 전송은 AutoSupport 서버가 아니라 스토리지 시스템에서 시작됩니다. 스토리지 어레이는 AutoSupport 서버와 주기적으로 확인하여 보류 중인 재전송 요청이 있는지 확인하고 그에 따라 응답합니다.
** * 원격 진단* -- 문제 해결을 위해 필요한 경우 기술 지원 부서에서 새로운 최신 AutoSupport 디스패치를 요청할 수 있습니다. 모든 전송은 AutoSupport 서버가 아니라 스토리지 시스템에서 시작됩니다. 스토리지 어레이는 AutoSupport 서버와 주기적으로 확인하여 보류 중인 새 요청이 있는지 확인하고 그에 따라 응답합니다.



