---
permalink: sm-support/what-do-i-need-to-know-before-upgrading-the-santricity-os-software.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrading, santricity, os, software 
summary: 컨트롤러의 소프트웨어 및 펌웨어를 업그레이드하기 전에 이러한 항목을 숙지하십시오. 
---
= SANtricity OS 소프트웨어를 업그레이드하기 전에 알아야 할 내용은 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러의 소프트웨어 및 펌웨어를 업그레이드하기 전에 이러한 항목을 숙지하십시오.

* 문서 및 "readme.txt" 파일을 읽었으며 업그레이드를 수행하기로 결정했습니다.
* IOM 펌웨어를 업그레이드할지 여부를 알고 있습니다.
+
일반적으로 모든 구성 요소를 동시에 업그레이드해야 합니다. 하지만 SANtricity OS 컨트롤러 소프트웨어 업그레이드의 일부로 업그레이드하지 않으려는 경우 또는 기술 지원 부서에서 IOM 펌웨어를 다운그레이드하도록 지시한 경우(명령줄 인터페이스를 사용하여 펌웨어를 다운그레이드할 수만 있음) IOM 펌웨어를 업그레이드하지 않을 수도 있습니다.

* 컨트롤러 NVSRAM 파일을 업그레이드할지 여부를 알 수 있습니다.
+
일반적으로 모든 구성 요소를 동시에 업그레이드해야 합니다. 그러나 파일이 패치되었거나 사용자 정의 버전이고 덮어쓰지 않으려는 경우 컨트롤러 NVSRAM 파일을 업그레이드하지 않을 수 있습니다.

* 지금 활성화할지 아니면 나중에 활성화할지 알 수 있습니다.
+
나중에 활성화하는 이유는 다음과 같습니다.

+
** * 시간 * -- 소프트웨어 및 펌웨어를 활성화하는 데 시간이 오래 걸릴 수 있으므로 I/O 로드가 가벼워질 때까지 기다려야 할 수 있습니다. 활성화 중에 컨트롤러가 페일오버되므로 업그레이드가 완료될 때까지 성능이 평소보다 저하될 수 있습니다.
** * 패키지 유형 * -- 다른 스토리지 어레이의 파일을 업그레이드하기 전에 한 스토리지 어레이에서 새 소프트웨어 및 펌웨어를 테스트할 수 있습니다.




이러한 구성요소는 SANtricity OS 컨트롤러 소프트웨어 업그레이드의 일부입니다.

* * 관리 소프트웨어 * -- System Manager는 스토리지 배열을 관리하는 소프트웨어입니다.
* * 컨트롤러 펌웨어 * -- 컨트롤러 펌웨어는 호스트와 볼륨 간의 I/O를 관리합니다.
* * 컨트롤러 NVSRAM * -- 컨트롤러 NVSRAM은 컨트롤러의 기본 설정을 지정하는 컨트롤러 파일입니다.
* * IOM 펌웨어 * -- I/O 모듈(IOM) 펌웨어는 컨트롤러와 드라이브 쉘프 간의 연결을 관리합니다. 또한 구성 요소의 상태를 모니터링합니다.
* * Supervisor 소프트웨어 * -- Supervisor 소프트웨어는 소프트웨어가 실행되는 컨트롤러의 가상 머신입니다.


업그레이드 프로세스의 일부로 호스트의 다중 경로/페일오버 드라이버 및/또는 HBA 드라이버도 업그레이드해야 호스트가 컨트롤러와 올바르게 상호 작용할 수 있습니다.

[NOTE]
====
이 경우에 해당하는지 확인하려면 를 참조하십시오 https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^].

====
스토리지 배열에 컨트롤러가 하나만 포함되어 있거나 다중 경로 드라이버가 설치되어 있지 않은 경우, 어플리케이션 오류를 방지하기 위해 스토리지 배열에 대한 I/O 작업을 중지합니다. 스토리지 어레이에 2개의 컨트롤러가 있는데 다중 경로 드라이버가 설치되어 있는 경우 I/O 작업을 중지할 필요가 없습니다.


CAUTION: 업그레이드가 진행되는 동안 스토리지 배열을 변경하지 마십시오.
