---
permalink: um-certificates/access-management-with-directory-services-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, access management, directory services, 
summary: '관리자는 LDAP(Lightweight Directory Access Protocol) 서버와 Microsoft의 Active Directory와 같은 디렉터리 서비스를 사용할 수 있습니다.' 
---
= 디렉토리 서비스를 통한 액세스 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리자는 LDAP(Lightweight Directory Access Protocol) 서버와 Microsoft의 Active Directory와 같은 디렉터리 서비스를 사용할 수 있습니다.



== 구성 워크플로우

네트워크에서 LDAP 서버 및 디렉토리 서비스를 사용하는 경우 구성은 다음과 같이 작동합니다.

. 관리자는 보안 관리자 권한이 포함된 사용자 프로필을 사용하여 Unified Manager에 로그인합니다.
+
[NOTE]
====
admin 사용자는 시스템의 모든 기능에 액세스할 수 있습니다.

====
. 관리자는 LDAP 서버에 대한 구성 설정을 입력합니다. 설정에는 도메인 이름, URL 및 바인딩 계정 정보가 포함됩니다.
. LDAP 서버가 보안 프로토콜(LDAPS)을 사용하는 경우 관리자는 LDAP 서버와 웹 서비스 프록시가 설치된 호스트 시스템 간의 인증을 위해 CA(인증 기관) 인증서 체인을 업로드합니다.
. 서버 연결이 설정되면 관리자는 사용자 그룹을 로컬 사용자 역할에 매핑합니다. 이러한 역할은 미리 정의되어 있으며 수정할 수 없습니다.
. 관리자는 LDAP 서버와 웹 서비스 프록시 간의 연결을 테스트합니다.
. 사용자는 할당된 LDAP/Directory 서비스 자격 증명을 사용하여 시스템에 로그인합니다.




== 관리

인증을 위해 디렉터리 서비스를 사용하는 경우 관리자는 다음 관리 작업을 수행할 수 있습니다.

* 디렉토리 서버를 추가합니다.
* 디렉토리 서버 설정을 편집합니다.
* LDAP 사용자를 로컬 사용자 역할에 매핑합니다.
* 디렉토리 서버를 제거합니다.
* 암호를 변경합니다.
* 암호의 최소 길이를 설정합니다.
* 사용자가 암호 없이 로그인할 수 있도록 허용합니다.

