---
permalink: um-certificates/edit-directory-server-settings-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, edit, directory, server, settings, role, mappings 
summary: 이전에 Access Management에서 디렉터리 서버를 구성한 경우 언제든지 해당 설정을 변경할 수 있습니다. 설정에는 서버 연결 정보와 그룹 대 역할 매핑이 포함됩니다. 
---
= SANtricity Unified Manager에서 디렉토리 서버 설정 및 역할 매핑 편집
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이전에 Access Management에서 디렉터리 서버를 구성한 경우 언제든지 해당 설정을 변경할 수 있습니다. 설정에는 서버 연결 정보와 그룹 대 역할 매핑이 포함됩니다.

.시작하기 전에
* 보안 관리자 권한이 포함된 사용자 프로필로 로그인해야 합니다. 그렇지 않으면 Access Management 기능이 나타나지 않습니다.
* 디렉토리 서버를 정의해야 합니다.


.단계
. 액세스 관리 * 를 선택합니다.
. 디렉터리 서비스 * 탭을 선택합니다.
. 둘 이상의 서버가 정의된 경우 테이블에서 편집할 서버를 선택합니다.
. 설정 보기/편집 * 을 선택합니다.
+
Directory Server Settings(디렉터리 서버 설정) 대화 상자가 열립니다.

. 서버 설정 * 탭에서 원하는 설정을 변경합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
* 구성 설정 *



 a| 
도메인
 a| 
LDAP 서버의 도메인 이름입니다. 여러 도메인의 경우 쉼표로 구분된 목록에 도메인을 입력합니다. 도메인 이름은 로그인(_username_@_domain_)에서 인증할 디렉토리 서버를 지정하는 데 사용됩니다.



 a| 
서버 URL
 a| 
의 형식으로 LDAP 서버에 액세스하기 위한 URL입니다 `ldap[s]://host:port`.



 a| 
BIND ACCOUNT(선택 사항)
 a| 
LDAP 서버에 대한 검색 쿼리 및 그룹 내 검색을 위한 읽기 전용 사용자 계정입니다.



 a| 
바인딩 암호(선택 사항)
 a| 
바인딩 계정의 암호입니다. (이 필드는 바인딩 계정을 입력할 때 나타납니다.)



 a| 
저장하기 전에 서버 연결을 테스트합니다
 a| 
시스템이 LDAP 서버 구성과 통신할 수 있는지 확인합니다. 테스트는 * 저장 * 을 클릭한 후에 수행됩니다. 이 확인란을 선택하고 검사에 실패하면 구성이 변경되지 않습니다. 테스트를 건너뛰고 구성을 다시 편집하려면 오류를 해결하거나 확인란을 선택 해제해야 합니다.



 a| 
* 권한 설정 *



 a| 
검색 기준 DN
 a| 
사용자를 검색하는 LDAP 컨텍스트로, 일반적으로 의 형식입니다 `CN=Users, DC=cpoc, DC=local`.



 a| 
사용자 이름 특성입니다
 a| 
인증을 위해 사용자 ID에 바인딩된 속성입니다. 예를 들어, 'sAMAccountName'을 입력합니다.



 a| 
그룹 속성
 a| 
그룹-역할 매핑에 사용되는 사용자의 그룹 속성 목록입니다. 예를 들어, memberOf , managedObjects 등이 있습니다.

|===
====
. 역할 매핑 * 탭에서 원하는 매핑을 변경합니다.
+
.필드 상세정보
[%collapsible]
====
[cols="25h,~"]
|===
| 설정 | 설명 


 a| 
* 매핑 *



 a| 
그룹 DN
 a| 
매핑할 LDAP 사용자 그룹의 도메인 이름입니다. 정규식이 지원됩니다. 이러한 특수 정규식 문자는 정규식 패턴의 일부가 아닌 경우 백슬래시(\)로 이스케이프되어야 합니다.

\.[]{}() <> * +-=!?^$|



 a| 
역할
 a| 
그룹 DN에 매핑할 역할입니다. 이 그룹에 포함할 각 역할을 개별적으로 선택해야 합니다. SANtricity Unified Manager에 로그인하려면 Monitor 역할이 다른 역할과 함께 필요합니다. 역할은 다음과 같습니다.

** * 스토리지 관리자 * -- 스토리지의 스토리지 객체에 대한 전체 읽기/쓰기 액세스이지만 보안 구성에 대한 액세스는 없습니다.
** * 보안 관리자 * -- 액세스 관리 및 인증서 관리에서 보안 구성에 액세스합니다.
** * 지원 관리자 * -- 스토리지 배열, 오류 데이터 및 MEL 이벤트의 모든 하드웨어 리소스에 액세스합니다. 스토리지 객체 또는 보안 구성에 대한 액세스 권한이 없습니다.
** * Monitor * -- 모든 스토리지 객체에 대한 읽기 전용 액세스이지만 보안 구성에 대한 액세스는 없습니다.


|===
====
+

NOTE: Monitor 역할은 관리자를 포함한 모든 사용자에게 필요합니다.

. 필요한 경우 * 다른 매핑 추가 * 를 클릭하여 그룹 대 역할 매핑을 추가로 입력합니다.
. 저장 * 을 클릭합니다.


.결과
이 작업을 완료하면 활성 사용자 세션이 종료됩니다. 현재 사용자 세션만 유지됩니다.
