---
permalink: um-certificates/faq-user-access-mgmt-um.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다. 
---
= SANtricity Unified Manager에 대한 사용자 액세스 관리 FAQ
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 질문에 대한 간단한 답변을 찾는 경우에 도움이 될 수 있습니다.



== 왜 로그인할 수 없나요?

로그인을 시도할 때 오류가 발생하면 다음과 같은 가능한 원인을 검토하십시오.

다음과 같은 이유 중 하나로 인해 로그인 오류가 발생할 수 있습니다.

* 잘못된 사용자 이름 또는 암호를 입력했습니다.
* 권한이 부족합니다.
* 여러 번 로그인을 시도했으나 실패하여 잠금 모드가 시작되었습니다. 다시 로그인하려면 10분 정도 기다립니다.
* SAML 인증이 활성화되었습니다. 로그인하려면 브라우저를 새로 고치십시오.




== 디렉토리 서버를 추가하기 전에 알아야 할 사항은 무엇입니까?

Access Management에서 디렉터리 서버를 추가하기 전에 특정 요구 사항을 충족해야 합니다.

* 사용자 그룹은 디렉토리 서비스에 정의되어 있어야 합니다.
* 도메인 이름, 서버 URL, 그리고 선택적으로 바인딩 계정 사용자 이름 및 암호를 포함하여 LDAP 서버 자격 증명을 사용할 수 있어야 합니다.
* 보안 프로토콜을 사용하는 LDAPS 서버의 경우 로컬 시스템에 LDAP 서버의 인증서 체인을 설치해야 합니다.




== 스토리지 어레이 역할에 매핑하는 방법에 대해 알아야 할 내용은 무엇입니까?

그룹을 역할에 매핑하기 전에 지침을 검토하십시오.

RBAC(역할 기반 액세스 제어) 기능에는 다음 역할이 포함됩니다.

* * 스토리지 관리자 * -- 스토리지의 스토리지 객체에 대한 전체 읽기/쓰기 액세스이지만 보안 구성에 대한 액세스는 없습니다.
* * 보안 관리자 * -- 액세스 관리 및 인증서 관리에서 보안 구성에 액세스합니다.
* * 지원 관리자 * -- 스토리지 배열, 오류 데이터 및 MEL 이벤트의 모든 하드웨어 리소스에 액세스합니다. 스토리지 객체 또는 보안 구성에 대한 액세스 권한이 없습니다.
* * Monitor * -- 모든 스토리지 객체에 대한 읽기 전용 액세스이지만 보안 구성에 대한 액세스는 없습니다.


[NOTE]
====
Monitor 역할은 관리자를 포함한 모든 사용자에게 필요합니다.

====
LDAP(Lightweight Directory Access Protocol) 서버 및 디렉터리 서비스를 사용하는 경우 다음 사항을 확인하십시오.

* 관리자가 디렉토리 서비스에 사용자 그룹을 정의했습니다.
* LDAP 사용자 그룹의 그룹 도메인 이름을 알고 있습니다.




=== SAML

스토리지 어레이에 포함된 SAML(Security Assertion Markup Language) 기능을 사용하는 경우 다음 사항을 확인하십시오.

* IDP(Identity Provider) 관리자가 IDP 시스템에서 사용자 속성 및 그룹 구성원을 구성했습니다.
* 그룹 구성원 이름을 알고 있습니다.
* 매핑할 그룹의 속성 값을 알고 있습니다. 정규식이 지원됩니다. 이러한 특수 정규식 문자는 정규식 패턴의 일부가 아닌 경우 백슬래시("\")로 이스케이프되어야 합니다.
+
[listing]
----
\.[]{}()<>*+-=!?^$|
----
* Monitor 역할은 관리자를 포함한 모든 사용자에게 필요합니다. Monitor 역할이 없는 모든 사용자는 Unified Manager가 올바르게 작동하지 않습니다.




== SAML을 구성 및 활성화하기 전에 알아야 할 내용은 무엇입니까?

인증을 위해 SAML(Security Assertion Markup Language) 기능을 구성 및 활성화하기 전에 다음 요구 사항을 충족하고 SAML 제한 사항을 이해해야 합니다.



=== 요구 사항

시작하기 전에 다음 사항을 확인하십시오.

* ID 공급자(IDP)가 네트워크에 구성되어 있습니다. IDP는 사용자의 자격 증명을 요청하고 사용자가 성공적으로 인증되었는지 확인하는 데 사용되는 외부 시스템입니다. 보안 팀은 IDP를 유지 관리할 책임이 있습니다.
* IDP 관리자가 IDP 시스템에서 사용자 속성 및 그룹을 구성했습니다.
* IDP 관리자는 IDP가 인증 시 이름 ID를 반환하는 기능을 지원하도록 했습니다.
* 관리자는 NTP 서버를 통해 또는 컨트롤러 클럭 설정을 조정하여 IDP 서버 및 컨트롤러 클록이 동기화되도록 했습니다.
* IDP 메타데이터 파일은 IDP 시스템에서 다운로드되며 Unified Manager 액세스에 사용되는 로컬 시스템에서 사용할 수 있습니다.
* 스토리지 배열의 컨트롤러에 있는 IP 주소 또는 도메인 이름을 알고 있습니다.




=== 제한 사항

위의 요구 사항 외에 다음과 같은 제한 사항을 이해해야 합니다.

* SAML이 활성화되면 사용자 인터페이스를 통해 이를 _비활성화할 수 없으며 IDP 설정을 편집할 수도 없습니다. SAML 구성을 비활성화하거나 편집해야 하는 경우 기술 지원 부서에 지원을 요청하십시오. 최종 구성 단계에서 SAML을 활성화하기 전에 SSO 로그인을 테스트하는 것이 좋습니다. (SAML을 활성화하기 전에 SSO 로그인 테스트도 수행합니다.)
* 나중에 SAML을 사용하지 않도록 설정하면 이전 구성(로컬 사용자 역할 및/또는 디렉터리 서비스)이 자동으로 복원됩니다.
* 디렉토리 서비스가 현재 사용자 인증을 위해 구성된 경우 SAML은 해당 구성을 재정의합니다.
* SAML이 구성된 경우 다음 클라이언트가 스토리지 시스템 리소스에 액세스할 수 없습니다.
+
** 엔터프라이즈 관리 창(EMW)
** CLI(Command-Line Interface)
** SDK(소프트웨어 개발자 키트) 클라이언트
** 대역내 클라이언트
** HTTP 기본 인증 REST API 클라이언트
** 표준 REST API 끝점을 사용하여 로그인합니다






== 로컬 사용자는 무엇입니까?

로컬 사용자는 시스템에 미리 정의되어 있으며 특정 권한을 포함합니다.

로컬 사용자는 다음과 같습니다.

* * admin * -- 시스템의 모든 기능에 액세스할 수 있는 슈퍼 관리자. 이 사용자는 모든 역할을 포함합니다. 암호는 처음 로그인할 때 설정해야 합니다.
* * 스토리지 * -- 모든 스토리지 프로비저닝을 담당하는 관리자. 이 사용자에게는 스토리지 관리자, 지원 관리자 및 모니터 역할이 포함됩니다. 이 계정은 암호를 설정할 때까지 비활성화됩니다.
* * 보안 * -- 액세스 관리 및 인증서 관리를 포함한 보안 구성을 담당하는 사용자입니다. 이 사용자는 보안 관리자 및 모니터 역할을 포함합니다. 이 계정은 암호를 설정할 때까지 비활성화됩니다.
* * 지원 * -- 하드웨어 리소스, 오류 데이터 및 펌웨어 업그레이드를 담당하는 사용자입니다. 이 사용자에게는 지원 관리자 및 모니터 역할이 포함됩니다. 이 계정은 암호를 설정할 때까지 비활성화됩니다.
* * monitor * -- 시스템에 대한 읽기 전용 액세스 권한이 있는 사용자입니다. 이 사용자는 Monitor 역할만 포함합니다. 이 계정은 암호를 설정할 때까지 비활성화됩니다.
* * rw * (읽기/쓰기) -- 이 사용자는 스토리지 관리자, 지원 관리자 및 모니터 역할을 포함합니다. 이 계정은 암호를 설정할 때까지 비활성화됩니다.
* * ro * (읽기 전용) -- 이 사용자는 Monitor 역할만 포함합니다. 이 계정은 암호를 설정할 때까지 비활성화됩니다.

