---
permalink: um-certificates/how-access-management-works-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, authentication, users, roles, access management 
summary: 액세스 관리를 사용하여 SANtricity Unified Manager에서 사용자 인증을 설정합니다. 
---
= 액세스 관리 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
액세스 관리를 사용하여 SANtricity Unified Manager에서 사용자 인증을 설정합니다.



== 구성 워크플로우

Access Management 구성은 다음과 같이 작동합니다.

. 관리자는 보안 관리자 권한이 포함된 사용자 프로필을 사용하여 Unified Manager에 로그인합니다.
+
[NOTE]
====
처음 로그인하는 경우 사용자 이름 admin이 자동으로 표시되며 변경할 수 없습니다. admin 사용자는 시스템의 모든 기능에 액세스할 수 있습니다. 암호는 처음 로그인할 때 설정해야 합니다.

====
. 관리자는 미리 구성된 로컬 사용자 역할이 포함된 사용자 인터페이스에서 Access Management로 이동합니다. 이러한 역할은 RBAC(역할 기반 액세스 제어) 기능 구현입니다.
. 관리자는 다음 인증 방법 중 하나 이상을 구성합니다.
+
** * 로컬 사용자 역할 * -- 인증은 RBAC 기능을 통해 관리됩니다. 로컬 사용자 역할에는 특정 액세스 권한을 가진 사전 정의된 사용자 및 역할이 포함됩니다. 관리자는 이러한 로컬 사용자 역할을 단일 인증 방법으로 사용하거나 디렉터리 서비스와 함께 사용할 수 있습니다. 사용자 암호 설정 이외의 구성은 필요하지 않습니다.
** * 디렉터리 서비스 * -- 인증은 LDAP(Lightweight Directory Access Protocol) 서버 및 Microsoft의 Active Directory와 같은 디렉터리 서비스를 통해 관리됩니다. 관리자가 LDAP 서버에 연결한 다음 LDAP 사용자를 로컬 사용자 역할에 매핑합니다.
** * SAML * -- 인증은 SAML(Security Assertion Markup Language) 2.0을 사용하여 ID 공급자(IDP)를 통해 관리됩니다. 관리자는 IdP 시스템과 스토리지 어레이 간의 통신을 설정한 다음 IdP 사용자를 스토리지 어레이에 포함된 로컬 사용자 역할에 매핑합니다.


. 관리자는 Unified Manager에 대한 로그인 자격 증명을 제공합니다.
. 사용자는 자격 증명을 입력하여 시스템에 로그인합니다. 로그인 중에 시스템은 다음과 같은 백그라운드 작업을 수행합니다.
+
** 사용자 계정에 대해 사용자 이름과 암호를 인증합니다.
** 할당된 역할에 따라 사용자의 권한을 결정합니다.
** 사용자에게 사용자 인터페이스의 기능에 대한 액세스 권한을 제공합니다.
** 상단 배너에 사용자 이름을 표시합니다.






== 기능은 Unified Manager에서 사용할 수 있습니다

기능에 대한 액세스는 사용자가 할당한 역할에 따라 달라집니다. 여기에는 다음이 포함됩니다.

* * 스토리지 관리자 * -- 스토리지의 스토리지 객체에 대한 전체 읽기/쓰기 액세스이지만 보안 구성에 대한 액세스는 없습니다.
* * 보안 관리자 * -- 액세스 관리 및 인증서 관리에서 보안 구성에 액세스합니다.
* * 지원 관리자 * -- 스토리지 배열, 오류 데이터 및 MEL 이벤트의 모든 하드웨어 리소스에 액세스합니다. 스토리지 객체 또는 보안 구성에 대한 액세스 권한이 없습니다.
* * Monitor * -- 모든 스토리지 객체에 대한 읽기 전용 액세스이지만 보안 구성에 대한 액세스는 없습니다.


사용할 수 없는 기능은 회색으로 표시되거나 사용자 인터페이스에 표시되지 않습니다.
