---
permalink: um-certificates/resolve-untrusted-certificates-certificate-page.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, resolve, untrusted, certificates 
summary: 신뢰할 수 없는 인증서는 스토리지 어레이에서 SANtricity Unified Manager에 대한 보안 연결을 설정하려고 시도하지만 연결이 보안으로 확인하지 못할 때 발생합니다. 
---
= 신뢰할 수 없는 인증서를 확인합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
신뢰할 수 없는 인증서는 스토리지 어레이에서 SANtricity Unified Manager에 대한 보안 연결을 설정하려고 시도하지만 연결이 보안으로 확인하지 못할 때 발생합니다.

인증서 페이지에서는 스토리지 배열에서 자체 서명된 인증서를 가져오거나 신뢰할 수 있는 타사에서 발급한 CA(인증 기관) 인증서를 가져와 신뢰할 수 없는 인증서를 확인할 수 있습니다.

.시작하기 전에
* 보안 관리자 권한이 포함된 사용자 프로필로 로그인해야 합니다.
* CA 서명 인증서를 가져올 계획인 경우:
+
** 스토리지 배열의 각 컨트롤러에 대한 인증서 서명 요청(.csr 파일)을 생성하여 CA로 보냈습니다.
** CA가 신뢰할 수 있는 인증서 파일을 반환했습니다.
** 인증서 파일은 로컬 시스템에서 사용할 수 있습니다.




.이 작업에 대해
다음 중 하나라도 해당되는 경우 신뢰할 수 있는 CA 인증서를 추가로 설치해야 할 수 있습니다.

* 최근에 스토리지 배열을 추가했습니다.
* 하나 이상의 인증서가 만료되었습니다.
* 하나 이상의 인증서가 해지되었습니다.
* 하나 이상의 인증서에 루트 또는 중간 인증서가 없습니다.


.단계
. 인증서 관리 * 를 선택합니다.
. 신뢰할 수 있는 * 탭을 선택합니다.
+
이 페이지에는 스토리지 배열에 대해 보고된 모든 인증서가 표시됩니다.

. [인증서] 가져오기 메뉴를 선택하여 CA 인증서를 가져오거나 메뉴: 자체 서명된 [스토리지 배열 인증서] 가져오기 를 선택하여 자체 서명된 인증서를 가져옵니다.
+
보기를 제한하려면 * Show certificates that are... * filtering 필드를 사용하거나 열 머리글 중 하나를 클릭하여 인증서 행을 정렬할 수 있습니다.

. 대화 상자에서 인증서를 선택한 다음 * 가져오기 * 를 클릭합니다.
+
인증서가 업로드 및 검증됩니다.


