---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, administrator, password, protection 
summary: 관리자 암호를 사용하여 SANtricity Unified Manager를 무단 액세스로부터 보호해야 합니다. 
---
= 관리자 암호 보호를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리자 암호를 사용하여 SANtricity Unified Manager를 무단 액세스로부터 보호해야 합니다.



== 관리자 암호 및 사용자 프로필

Unified Manager를 처음 시작하면 관리자 암호를 설정하라는 메시지가 표시됩니다. admin 암호를 가진 모든 사용자는 스토리지 배열에 대한 구성을 변경할 수 있습니다.

관리자 암호 외에도 Unified Manager 인터페이스에는 하나 이상의 역할이 매핑되어 있는 사전 구성된 사용자 프로필이 포함되어 있습니다. 자세한 내용은 을 참조하십시오 link:../um-certificates/how-access-management-works-unified.html["액세스 관리 작동 방식"].

사용자 및 매핑을 변경할 수 없습니다. 암호만 수정할 수 있습니다. 암호를 변경하려면 다음을 참조하십시오.

* link:change-admin-password-unified.html["admin 암호를 변경합니다"]
* link:../um-certificates/change-passwords-unified.html["로컬 사용자 프로필에 대한 암호를 변경합니다"]




== 세션 시간 초과

단일 관리 세션 중에 암호를 입력하라는 메시지가 한 번만 표시됩니다. 기본적으로 30분 동안 활동이 없으면 세션 시간이 초과되며, 이 경우 암호를 다시 입력해야 합니다. 다른 사용자가 다른 관리 클라이언트에서 소프트웨어에 액세스하고 세션이 진행되는 동안 암호를 변경하는 경우 다음에 구성 작업 또는 보기 작업을 시도할 때 암호를 입력하라는 메시지가 표시됩니다.

보안상의 이유로 소프트웨어가 "잠금" 상태가 되기 5회만 암호를 입력할 수 있습니다. 이 상태에서는 소프트웨어가 후속 암호 시도를 거부합니다. 암호를 다시 입력하기 전에 10분 정도 기다린 후 "정상" 상태로 재설정해야 합니다.

세션 시간 초과를 조정하거나 세션 시간 초과를 모두 비활성화할 수 있습니다. 자세한 내용은 을 참조하십시오 link:manage-session-timeouts-unified.html["세션 시간 제한을 관리합니다"].
